### ISSUE TITLE
Cant find UI

### ISSUE THREAD

**Issue by vmpartner** [casbin/casbin#100]
Please say where i can find policy editor that specified on img?

![model editor](https://hsluoyz.github.io/casbin/ui_model_editor.png)

![policy editor](https://hsluoyz.github.io/casbin/ui_policy_editor.png)

**Comment by hsluoyz** [comment]
Please see: https://github.com/casbin/casbin/issues/47

**Comment by M-Razavi** [comment]
https://github.com/casbin/web-ui
