### ISSUE TITLE
[Feature] Performance improvements

### ISSUE THREAD

**Issue by abichinger** [casbin/casbin#1000]
In order to learn Go, I started to re-implement casbin. (https://github.com/abichinger/fastac)

While doing so, I noticed some pieces of code, where the performance could be improved:

1. **regular expressions are slow**
The KeyMatch functions can be implemented without the use of regular expressions.
[PathMatch](https://github.com/abichinger/fastac/blob/7e15e2b51eec19a9ed81a9c11f66f87099501b78/util/builtin_operators.go#L164) is almost equivalent to KeyMatch2
2. **ABAC eval**
[Eval rule names](https://github.com/casbin/casbin/blob/cb944fd5ef0a0029b6e74b8ca658f7dcb72e69f9/enforcer.go#L577) are searched inside the policy loop.
To avoid this an `eval` function could be added to the FunctionMap (that is what I did).
Another solution would be to resolve the names of the eval parameters before the loop. e.g.:
```go
expr := "eval(p.sub_rule) && r.obj == p.obj && r.act == p.act"
expr_template := ReplaceEval(expr) //%s && r.obj == p.obj && r.act == p.act
ruleNames := GetRuleNames(expr) //[]string{"p.sub_rule"}

for policyIndex, pvals := range e.model["p"][pType].Policy {
  rules := GetRules(pvals, ruleNames) //[]string{"r.sub.Age > 18"}
  expr = fmt.Sprintf(expr_template, rules)
}
```

**Comment by sagilio** [comment]
@abichinger about point 2, I think the two solutions may be not in conflict?
 in fact, Casbin.NET used [the another solution](https://github.com/casbin/Casbin.NET/blob/820900f8393df90db6d63504a4ff9d9defb5ace8/Casbin/EnforceView.cs#L103), It will parse all the information required by the enforce in advance as a `EnforceView` and cached them.
