### ISSUE TITLE
[Question]Is there any API to determine whether a user is a super administrator?

### ISSUE THREAD

**Issue by bytegolang** [casbin/casbin#1001]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Your answer here

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act || r.sub == "root"
```

**Your policy:**

```
p, alice, data1, read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write

g, alice, data2_admin
```

**Your request(s):**

```
alice, data2, read ---> false (expected: true)
```

**Comment by tangyang9464** [comment]
@bytegolang As you can see, the super admin is only a matching rule in the matcher (``r.sub == "root"``), it depends on how you define it yourself. In your model, you only need to determine if the user is ``root``.

**Comment by bytegolang** [comment]
> @bytegolang Please edit the title in English. As you can see, the super admin is only a matching rule in the matcher (`r.sub == "root"`), it depends on how you define it yourself. In your model, you only need to determine if the user is `root`.

@tangyang9464 Thank you
