### ISSUE TITLE
Is there a Adapter for Aerospike Database?

### ISSUE THREAD

**Issue by sanudatta11** [casbin/casbin#1006]
We want to use casbin as a auth middleware for our application which primarily uses Aerospike for all data purposes. But I was unable to find any driver/module for the same. 

Is there a way to add casbin to aerospike, we want to save the policies , user creations and all done in aerospike via casbin

**Comment by hsluoyz** [comment]
@sanudatta11 can you create one?

**Comment by sanudatta11** [comment]
I don't think so I have the knowledge depth needed for the same. Just wanted to know if anyone is working on or they have one rn

**Comment by hsluoyz** [comment]
It's not very popular, I'm afraid not.
