### ISSUE TITLE
[Question] How to use a matcher with management API?

### ISSUE THREAD

**Issue by medghaim** [casbin/casbin#1007]
**What's your scenario? What do you want to achieve?**

My policy definition is as follows:
```
[policy_definition]
p = role, gateway, path, method
```

Using the `gateway`, `path`, and `method`, I want to use the  [management API](https://github.com/casbin/casbin/blob/master/management_api.go) in order to retrieve the `role` required by the policy. This is possible via `GetFilteredPolicy(1, gateway, path, method)`. The issue arises if the `path` contains a URL parameter (ie, `/resource/:resourceID`).

[`Enforce(...)`](https://github.com/casbin/casbin/blob/master/enforcer.go#L701-L709)  uses the matcher defined in the model. The matcher I've defined uses [`KeyMatch2`](https://github.com/casbin/casbin/blob/master/util/builtin_operators.go#L105) in order to correctly match against objects which contain URL parameters
- ie, `/resource/some-id` correctly matches against `/resource/:resourceID`

The management API does not use the matcher defined in the model `.conf` file, which makes sense since the managment API provides a different use case than the actual enforcer. Using  `GetFilteredPolicy` in order to retrieve a specific policy does not work if the object contains a URL parameter. This makes sense since the management API does not use the matcher as defined in my model (see below), which handles URL parameters by calling `KeyMatch2` on the request object and policy object to see if they match.
- ie, `GetFilteredPolicy(..., "/resource/some-id", ...)` doesn't match the policy with the resource `/resource/:resourceID`.

I'm attempting to use the management API in conjunction with the `KeyMatch2` util function, so that I can correctly match an object of `/resource/some-resource-id` against a policy which defines its object as `/resource/:resourceID`. 

What's the best way to achieve this? Currently, I took the less than performant approach of simply retrieving all policies for the given `gateway` (as defined in my model, see below), iterating through them, and manually calling `util.KeyMatch2(request.Path, policy.Path)`:
```go
        policies := [][]string{}

        gatewayPolicies := p.enforcer.GetFilteredPolicy(1, req.Gateway)
        for _, p := range gatewayPolicies {
            if util.KeyMatch2(req.Object, p[OBJECT_IDX]) && util.RegexMatch(req.Action, p[ACTION_IDX]) {
                policies = append(policies, p)
            }   
        }
        
        return policies
```

Effectively, I'm manually acting as the matcher in my model for object and action.

Looking at the implementation for `GetFilteredPolicy`, it's essentially doing the same thing -- retrieve all `p` type policies, iterate through them looking for matches with the given filters. The only difference is that it doesn't use the `KeyMatch` and `RegexMatch` functions for the object and action, respectively.

I toyed around with defining a second matcher, one which used `keyMatch` on the request and policy objects, and `regexMatch` on the request and policy actions, but I couldn't see a way to get the management API to use it.

**Your model:**

```ini
[request_definition]
r = role, gateway, path, method

[policy_definition]
p = role, gateway, path, method

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.role, p.role, r.gateway) && r.gateway == p.gateway && keyMatch2(r.path, p.path) && regexMatch(r.method, p.method)
```

**Your policy:**

```
p, standard, web, /resource/:resourceID, GET

g, standard, limited, web
g, standard, limited, app
```

**Your request(s):**

```
GetFilteredPolicy(1, "web", "/resource/some-resource-id", "GET") ---> [[standard web /resource/:resourceID GET]]
```

**Comment by tangyang9464** [comment]
@medghaim see #1009 . You can use ``matcher`` like in conf model file, but here the parameter is only has ``p`` and no ``r``. The  ``r`` becomes a string constant, pay attention to wrap it in single quotes ``''``. In your example, code is ``e.FilteredPolicyWithMatcher("p", "'web' == p.gateway && keyMatch2('/resource/some-resource-id', p.path) && regexMatch('GET', p.method)")
``
