### ISSUE TITLE
[Bug]DeleteRole do not totally work in priority model

### ISSUE THREAD

**Issue by phoenixsqf** [casbin/casbin#1015]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
Enforcer.DeleteRole do not totally work in priority model

**Model used**

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = priority, sub, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = priority(p.eft) || deny

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

Function DeleteRole
```
// DeleteRole deletes a role.
// Returns false if the role does not exist (aka not affected).
func (e *Enforcer) DeleteRole(role string) (bool, error) {
	var err error
	res1, err := e.RemoveFilteredGroupingPolicy(1, role)
	if err != nil {
		return res1, err
	}

	res2, err := e.RemoveFilteredPolicy(0, role)
	return res1 || res2, err
}
```

In this model, priority is the first index of policy definition，but the function try to delete policy by the first index.
So the permission will not be removed. It might caused some problems.

**Expected behavior**
Maybe try to call e.RemoveFilteredPolicy(1, role) when the value of priorityIndex is 0？

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by hsluoyz** [comment]
@JalinWang @tangyang9464

**Comment by tangyang9464** [comment]
@hsluoyz Both ``DeleteRole`` and ``DeleteUser`` default ``sub`` principal in the first column of the ``policy_definition``, which obviously does not apply in all cases. Should we provide parameters to let our user pass in their defined ``sub index`` or just restrict our user to have to define the ``sub`` as the first column?

**Comment by hsluoyz** [comment]
@tangyang9464 here is a simpler method. We can detect what index the `sub` is in within the model. e.g., we can read `p = priority, sub, obj, act, eft` and know `sub` is the 2nd element. Better we can store this information somewhere in the enforcer, so we don't need to retrieve it for every call.

**Comment by tangyang9464** [comment]
> @tangyang9464 here is a simpler method. We can detect what index the `sub` is in within the model. e.g., we can read `p = priority, sub, obj, act, eft` and know `sub` is the 2nd element. Better we can store this information somewhere in the enforcer, so we don't need to retrieve it for every call.

@hsluoyz Not all users will name the subject ``sub``, if only to resolve the current issue, it will be simple, let's assume that the user will be named ``sub`` and always be first, with special treatment for ``priority``

**Comment by hsluoyz** [comment]
@tangyang9464 yes, but this is the simplest way to do. And we assume the user will use `sub`. If the user has changed it to something else, then we cannot support it, because Casbin is too flexible.

**Comment by hsluoyz** [comment]
@Abingcbc

**Comment by JalinWang** [comment]
> Not all users will name the subject `sub`, if only to resolve the current issue, it will be simple, let's assume that the user will be named `sub` and always be first, with special treatment for `priority`

> And we assume the user will use sub. If the user has changed it to something else, then we cannot support it, because Casbin is too flexible.

In fact, I find other hardcode texts, e.g., "dom" for the domain as follows, in the codebase. Casbin has already lost such flexibility. 
![image](https://user-images.githubusercontent.com/20621784/175764004-ab34d08d-978c-4526-b2be-64f58ddcda41.png)

**Comment by JalinWang** [comment]
What's more,  I find there are several `xxxIndex` existing across the codebase.

getDomainIndex in enforcer
![image](https://user-images.githubusercontent.com/20621784/175764210-e5fc431f-7c74-423a-b5b5-be5bde6bab00.png)

initPriorityIndex in assertion
![image](https://user-images.githubusercontent.com/20621784/175764233-34ee7958-45f6-4c88-b8b5-1c83d7a87e66.png)

priorityIndex is assigned in model.go
![image](https://user-images.githubusercontent.com/20621784/175764257-fc056913-3009-47f7-ba20-f2b5f4219c7a.png)

Can I refactor these codes to put them together and make them more generic to support the new `SubjectIndex`? @hsluoyz @tangyang9464

**Comment by tangyang9464** [comment]
@JalinWang You can open a new PR to do it. But now, for the current issue, let's just assume ``sub`` is in the first place, and fix it first.

**Comment by tangyang9464** [comment]
> > Not all users will name the subject `sub`, if only to resolve the current issue, it will be simple, let's assume that the user will be named `sub` and always be first, with special treatment for `priority`
> 
> > And we assume the user will use sub. If the user has changed it to something else, then we cannot support it, because Casbin is too flexible.
> 
> In fact, I find other hardcode texts, e.g., "dom" for the domain as follows, in the codebase. Casbin has already lost such flexibility. ![image](https://user-images.githubusercontent.com/20621784/175764004-ab34d08d-978c-4526-b2be-64f58ddcda41.png)

@JalinWang  Currently we can only assume that the user uses default names such as ``sub, priority, dom``, etc. to get the index. Do you have a better idea?

**Comment by Abingcbc** [comment]
Maybe this issue already can be closed by PR https://github.com/casbin/casbin/pull/1041 ?

https://github.com/casbin/casbin/blob/d471c722ae507d050df7575aec2b1a1f50039ccf/rbac_api.go#L120-L124

**Comment by hsluoyz** [comment]
@phoenixsqf @tangyang9464

**Comment by tangyang9464** [comment]
> Maybe this issue already can be closed by PR https://github.com/casbin/casbin/pull/1041 ?
> 
> https://github.com/casbin/casbin/blob/d471c722ae507d050df7575aec2b1a1f50039ccf/rbac_api.go#L120-L124

@Abingcbc Could you add some tests for this?I forgot. Then we can close it

**Comment by JalinWang** [comment]
Bug of PR https://github.com/casbin/casbin/pull/1041
It seems that there some functions still don't work in the priority model or the model with `sub` placed in an arbitrary location.
model example
```ini
[policy_definition]
p = customized_priority, obj, act, eft, subject
```
functions :
```golang
// DeletePermission deletes a permission.
// Returns false if the permission does not exist (aka not affected).
func (e *Enforcer) DeletePermission(permission ...string) (bool, error) {
	return e.RemoveFilteredPolicy(1, permission...)
}
```

```golang
// DeletePermissionForUser deletes a permission for a user or role.
// Returns false if the user or role does not have the permission (aka not affected).
func (e *Enforcer) DeletePermissionForUser(user string, permission ...string) (bool, error) {
	return e.RemovePolicy(util.JoinSlice(user, permission...))
}
```

**Comment by tangyang9464** [comment]
> 

@JalinWang These two APIs are special, and it seems that they cannot be applied to FieldIndex, and we can only assume that ``sub`` is in the first place.If not, Users can use ``RemoveFilteredPolicy`` or ``RemovePolicy`` instead

**Comment by JalinWang** [comment]
> @JalinWang These two APIs are special, and it seems that they cannot be applied to FieldIndex, and we can only assume that `sub` is in the first place.If not, Users can use `RemoveFilteredPolicy` or `RemovePolicy` instead

Can we use pre-allocate an array and then fill the permission into the slot other than sub&priority-FieldIndex?

**Comment by tangyang9464** [comment]
> 

@JalinWang It sounds weird, but it ok. You can do it.
