### ISSUE TITLE
[Feature] LoadPolicyLine should check the policy length whether match the model policy definition

### ISSUE THREAD

**Issue by qingwave** [casbin/casbin#1016]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Is your feature request related to a problem? Please describe.**
When call `LoadPolicyLine` mothed to load policy from adapter(file-adapter), if some policies is invaild (length not matched the parameters in policy definition), we should return a error or skip. 
https://github.com/casbin/casbin/blob/290ed05ab3ab406e74d2538830410ca2d826a0eb/persist/adapter.go#L25

If not, a invaild policy would cause unexcepted error from Enforce result

**Describe the solution you'd like**
Skip invaild policy or return a error in function `LoadPolicyLine`

**Describe alternatives you've considered**

**Additional context**

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
@qingwave The policy length is checked when enforce is called, but it would be better to add the check in LoadPolicyLine.

**Comment by qingwave** [comment]
> @qingwave The policy length is checked when enforce is called, but it would be better to add the check in LoadPolicyLine.

@tangyang9464 Thanks for your information, that's means an invaild policy couldn't affect the enforce result, it's make sense.
