### ISSUE TITLE
[Feature] should we add paging feature for getRolesForUser or getPermissionsForUser API?

### ISSUE THREAD

**Issue by iyjian** [casbin/casbin#1018]
**Want to prioritize this issue?
LOW

**Is your feature request related to a problem? Please describe.**
when a user get a large scale of roles or permission, it is imposible to get all of the permissions or roles in one request.

**Describe the solution you'd like**
I'd like to add a pagnation options for those API.

**Describe alternatives you've considered**
I am not sure if we already have an alternative to cover this situation.

**Comment by hsluoyz** [comment]
@iyjian how many objects do you query?

**Comment by iyjian** [comment]
for a user, there may be thousands of thousands of granted permission objects, and we have a portal to view this objects, so I was wondering if we have a way to paging this results.

**Comment by iyjian** [comment]
@hsluoyz

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
@iyjian We don't have this option. Could  you make a PR for this?

**Comment by iyjian** [comment]
I can try

**Comment by iyjian** [comment]
the proposal is add  pagnation arguments for method getpermissionsforuser, just like:
```
getpermissionsforuser(user = 'user1', page = 1, limit = 1000000)
```
page and limit should with a default value for adopting old version.

is it ok?

**Comment by tangyang9464** [comment]
> the proposal is add pagnation arguments for method getpermissionsforuser, just like:
> 
> ```
> getpermissionsforuser(user = 'user1', page = 1, limit = 1000000)
> ```
> 
> page and limit should with a default value for adopting old version.
> 
> is it ok?

@iyjian Because getpermissionsforuser traverses all policies and then filters out those that meet the requirements. If we query the second page, should we need to traverse from the beginning?

**Comment by iyjian** [comment]
it depens on adapter implement.  It can be a cursor.

**Comment by tangyang9464** [comment]
> it depens on adapter implement. It can be a cursor.

In fact getpermissionsforuser queries the policies in memory instead of querying the database through the adapter

**Comment by iyjian** [comment]
does getpermissionsforuser intended for searching permissions for management? if so, I think we should implement it in adapter.

**Comment by hsluoyz** [comment]
@iyjian what adapter do you use?

**Comment by tangyang9464** [comment]
> does getpermissionsforuser intended for searching permissions for management? if so, I think we should implement it in adapter.

@iyjian The memory is consistent with the policies in the database. Can reading from adapter bring any changes？

**Comment by hsluoyz** [comment]
@iyjian you can extend the role manager and its GetRoles() function to have pagination.
