### ISSUE TITLE
多节点问题权限动态分配问题

### ISSUE THREAD

**Issue by icowan** [casbin/casbin#102]
这个插件是初始化的时候把db里的数据加载到内存，单节点还好。那么多节点的时候 我配置了权限，执行`e.LoadPolicy() ` 只对当前节点有效果，其他节点并没有加载到内存。
那么这个权限就不是动态配置。
需要重启动服务。

这是不是一个BUG呢？

**Comment by hsluoyz** [comment]
你需要watcher：https://github.com/casbin/casbin#policy-consistence-between-multiple-nodes

**Comment by icowan** [comment]
@hsluoyz 这个 watcher是有问题的，连接zookeeper 没法设置authACL WorldACL 也没有，得修改源码

**Comment by hsluoyz** [comment]
Please raise your issue at: https://github.com/grepsr/casbin-zk-watcher
