### ISSUE TITLE
[Question] Why doesn't DistributedEnforcer use locks?

### ISSUE THREAD

**Issue by kizjig** [casbin/casbin#1022]
**What's your scenario? What do you want to achieve?**
I am attempting to use the DistributedEnforcer with the redis-watcher that has implemented the events for WatcherEx. I am using this in a multi-instance environment where each instance has 1 enforcer inspecting and manipulating the same policy data in a Postgres DB with auto save/incremental saves turned on.

In looking into the DistributedEnforcer implementation I see that it extends the SyncedEnforcer (which I was previously using), but doesn't use it's locking approach for the functions... 

```
AddPoliciesSelf(shouldPersist func() bool, sec string, ptype string, rules [][]string) (effected [][]string, err error)
RemovePoliciesSelf(shouldPersist func() bool, sec string, ptype string, rules [][]string) (effected [][]string, err error)
RemoveFilteredPolicySelf(shouldPersist func() bool, sec string, ptype string, fieldIndex int, fieldValues ...string) (effected [][]string, err error)
UpdatePolicySelf(shouldPersist func() bool, sec string, ptype string, oldRule, newRule []string) (effected bool, err error)
UpdatePoliciesSelf(shouldPersist func() bool, sec string, ptype string, oldRules, newRules [][]string) (effected bool, err error)
UpdateFilteredPoliciesSelf(shouldPersist func() bool, sec string, ptype string, newRules [][]string, fieldIndex int, fieldValues ...string) (bool, error)
```

I would expect all these functions to be getting a lock at the start, eg:
```
func (d *DistributedEnforcer) AddPoliciesSelf(shouldPersist func() bool, sec string, ptype string, rules [][]string) (effected [][]string, err error) {
	d.m.Lock()
	defer d.m.Unlock()
// ...
}
```

Why isn't this happening? Doesn't it need to be using the mutex/lock to be thread safe in these functions?

**Comment by hsluoyz** [comment]
@tangyang9464 @nodece

**Comment by nodece** [comment]
Could you make a PR to fix this?

**Comment by hsluoyz** [comment]
@maocaicai
