### ISSUE TITLE
[Feature] Matcher expressions are always re-evaluated, even when they don't change

### ISSUE THREAD

**Issue by timconinx** [casbin/casbin#1028]
(I'm using the feature template because I'm not sure if this is a bug or an unfortunate feature)

We've started an internal discussion on whether to replace our home-cooked access framework with casbin. First experiments point to casbin being far inferior in terms of performance.

**Is your feature request related to a problem? Please describe.**
Investigation showed that a lot of performance was lost in re-evaluating the Matcher expressions. Each call to `enforce` will trigger `govaluate.NewEvaluableExpressionWithFunctions(expString, functions)` in line 544 of `/enforcer.go`

**Describe the solution you'd like**
As experiment, we tried to cache the matcher expression, by first adding two field to the `Enforcer` struct
```
expression *govaluate.EvaluableExpression
expressionBasedOn string
```
And then making the evalution of the matcher string dependent on the existance and equality of these fields
```
if e.expression == nil || e.expressionBasedOn != expString {
    expression, err = govaluate.NewEvaluableExpressionWithFunctions(expString, functions)
    if err != nil {
        return false, err
    }
    e.expression = expression
    e.expressionBasedOn = expString
} else {
    expression = e.expression
}
```

**Describe alternatives you've considered**
There are probably other or better ways to archieve this, but the question remains: did we find a bug, or is there a reason why the expression should not be cached?

**Additional context**
These are our benchmark numbers

![image](https://user-images.githubusercontent.com/1834193/172376610-d0554c06-2056-4e62-95ea-5b0d55e11b92.png)

The `CasbinR` numbers are those with the described code-change: roughly one fourth of the normal execution time...

**Comment by rvdurm** [comment]
The Knetic/govaluate engine which is used specifies in its readme ...

Expressions are parsed once, and can be re-used multiple times. Parsing is the compute-intensive phase of the process, so if you intend to use the same expression with different parameters, just parse it once.

**Comment by hsluoyz** [comment]
@rvdurm can you make a PR for it?

**Comment by timconinx** [comment]
@hsluoyz You meant a PR for the code I provided, right?

**Comment by hsluoyz** [comment]
@timconinx your solution is not beautiful. Why not use a map[string]Evaluation to store all evaluations? If the map is not hit, we will create a new Evaluation and store into the map.

**Comment by abichinger** [comment]
I thought of an edge case, which is very unlikely, but I thought I should mention it.

A cached expression should be invalidated, if a function inside the `FunctionMap` is modified.
e.g.:
**Model**
```ini
....

[matchers]
m = MyFunc()
```

**Golang code**
```go
e.AddFunction("MyFunc()", func (...) { ... }) // add function MyFunc
e.Enforce() // expression gets compiled with reference to MyFunc
e.AddFunction("MyFunc()", func (...) { ... }) // modify MyFunc
e.Enforce() // should recompile the expression, because MyFunc has changed
```

**Comment by abichinger** [comment]
@hsluoyz no, the govaluate will just keep a reference to the function. I updated the example above to make it more clear.

**Comment by hsluoyz** [comment]
@abichinger OK, for function pointer, we also need to invalidate it.

**Comment by tangyang9464** [comment]
> 

@abichinger How to monitor changes in functionMap, do you have any idea? jcasbin use ``isModify`` field, see [FunctionMap.java#L41-L44](https://github.com/casbin/jcasbin/blob/a21b2199bcd1199a66aebf7e86930b2218dfacd1/src/main/java/org/casbin/jcasbin/model/FunctionMap.java#L41-L44) and [jcasbin#259](https://github.com/casbin/jcasbin/pull/259). But this way doesn'y guarantee thread safety

**Comment by sagilio** [comment]
@abichinger @tangyang9464  I think we only need to remove the cache of compiled function when the existing function is changed,

**Comment by abichinger** [comment]
> @abichinger How to monitor changes in functionMap, do you have any idea?

@tangyang9464 at the moment, I can't think of of a simple thread safe solution to monitor the FunctionMap.

> I think we only need to remove the cache of compiled function when the existing function is changed,

@sagilio I'm not sure if I understood you correctly, but I think it is not possible to remove/exchange the referenced function of a compiled `govaluate.EvaluableExpression`.

I think the simplest solution would be to just drop all cached `govaluate.EvaluableExpression` as soon as `e.AddFunction` is called. Even if the expression is not affected by the modified function.

**Comment by tangyang9464** [comment]
> @abichinger @tangyang9464  I think we only need to remove the cache of compiled function when the existing function is changed,

@sagilio I'm not quite sure how to do it

**Comment by abichinger** [comment]
@timconinx looks like the error comes from [`builtin_operators.go:370`](https://github.com/casbin/casbin/blob/860d290f060d7ec69396dd13ff299b3f35f1882a/util/builtin_operators.go#L370).

**Comment by timconinx** [comment]
Please review this PR https://github.com/casbin/casbin/pull/1031
(and please be gentle ;) )

**Comment by tangyang9464** [comment]
@hsluoyz[TestEnforceConcurrency](https://github.com/casbin/casbin/blob/860d290f060d7ec69396dd13ff299b3f35f1882a/enforcer_test.go#L356)  doesn't seem to be in enforcer_test.go.Now we're using SyncedEnforcer as a thread-safe version of Casbin. Does that mean we should not keep thread safe in enforcer? Becaues it has extra costs such as using ``sync.map``. It is meaningless and reduces efficiency. @abichinger @timconinx So if the ``memorized`` can be used in SyncedEnforcer, then is it not necessary to use ``sync.map``?
