### ISSUE TITLE
Suggestions for using casbin on Hugo static sites secured with oauth2?

### ISSUE THREAD

**Issue by shah** [casbin/casbin#103]
I am using Hugo for static site generation and was wondering if there was a way to use casbin with an [oauth2](https://github.com/golang/oauth2) layer to secure certain pages? It seems quite powerful and seemingly possible but would love to hear if anyone's done something similar so I can learn some techniques.

**Comment by hsluoyz** [comment]
If I understand correct, Hugo runs a static site, which is front-end only (html, js, css). But Casbin is a Golang library, which means you have to use Golang as backend. So how do you want Casbin to serve the authorization need for a static site?

**Comment by shah** [comment]
Good question @hsluoyz - I'm using Hugo as a static site generator but serving it with oauth2_proxy library (basically an HTTP server which wraps the static site in various oauth2 providers like Google, GitHub, LinkedIn, etc.). One of the things the oauth2_proxy lacks is fine-grained authorization so I thought I would try to couple casbin with oauth2_proxy and was wondering if anyone had done anything similar. Thanks!

**Comment by hsluoyz** [comment]
@shah https://github.com/bitly/oauth2_proxy has been deprecated. Will close this issue for now. Welcome if there are new issues!
