### ISSUE TITLE
[Bug] getRoles() result has duplicate items

### ISSUE THREAD

**Issue by greenhandatsjtu** [casbin/casbin#1033]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
In `default-role-manager/role_manager.go`, `func (r *Role) getRoles()` returns result with duplicate items

**To Reproduce**
I write a test:
```go
func TestBasicRoleMatching2(t *testing.T) {
	rm := NewRoleManager(10)
	rm.AddMatchingFunc("keyMatch", util.KeyMatch)

	_ = rm.AddLink("alice", "book_group")
	_ = rm.AddLink("alice", "*")
	_ = rm.AddLink("bob", "pen_group")

	testRole(t, rm, "alice", "book_group", true)
	testRole(t, rm, "alice", "pen_group", true)
	testRole(t, rm, "bob", "pen_group", true)
	testRole(t, rm, "bob", "book_group", false)
	testPrintRoles(t, rm, "alice", []string{"*", "alice", "bob", "book_group", "pen_group"})
	testPrintUsers(t, rm, "*", []string{"alice"})
}
```
Test fails with:
```bash
role_manager_test.go:371: alice: [* book_group alice book_group bob pen_group], supposed to be [* alice bob book_group pen_group]
```
`book_group` appears twice in alice's roles

**Expected behavior**
Alice's roles should be ["\*", "alice", "bob", "book_group", "pen_group"]
In casbin-rs, the result is ["\*", "alice", "bob", "book_group", "pen_group"] https://github.com/casbin/casbin-rs/blob/663e7648652c130660327d3ad90efa9fbef347b7/src/rbac/default_role_manager.rs#L792

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hsluoyz** [comment]
@JalinWang @imp2002 

/cc @tangyang9464
