### ISSUE TITLE
[Question] Add exception permission for existing policy

### ISSUE THREAD

**Issue by hahattan** [casbin/casbin#1035]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

Hi, I'm using Casbin to authorize the API request for different user(role).
For covenicence I'm using RBAC with pattern and KeyMatch function to define the API group.

I'm wondering if it's possible to define some excepetion obj for a specific sub in the model so that I don't need to write extra Go code to determine if the exception API is allowed by current user?
(which means I can simply run `enforcer.Enforce(...)` and get the expected result)

Thanks for the help.

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.obj, p.pbj) && g2(r.sub, p.sub) && regexMatch(r.act, p.act)
```

**Your policy:**

```
p, Viewer, api, GET
p, Operator, api, PUT
# a policy definition to forbid PUT /api/secret for Operator role

g, /api/*, api

g2, Operator, Viewer
g2, Admin, Operator
```

**Your request(s):**

```
Viewer, /api/test, GET ---> true(expected: true)
Operator, /api/test, PUT---> true(expected: true)
Operator, /api/secret, PUT---> true(expected: false)
Admin, /api/secret, PUT---> true(expected: true)
```

**Comment by tangyang9464** [comment]
@hahattan use ``Allow-and-deny`` effect. See example https://casbin.org/docs/en/supported-models#examples

**Comment by hahattan** [comment]
Hi it works for `Operator`.
But since `Admin` inherits `Operator`,  `Admin` is also not allowed to access `/api/secret` in this case. 
(I tried to add `p, Admin, /api/secret, PUT` but doesn't work)
Is it possible to make it specifically works for `Operator` role ?

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.obj, p.pbj) && g2(r.sub, p.sub) && regexMatch(r.act, p.act)
```

**Your policy:**

```
p, Viewer, api, GET
p, Operator, api, PUT
p, Operator, secret_api, PUT, deny
p, Admin, secret_api, PUT

g, /api/*, api
g, /api/secret/*, secret_api

g2, Operator, Viewer
g2, Admin, Operator

```

**Your request(s):**

```
Operator, /api/secret/test, PUT---> false(expected: false)
Admin, /api/secret/test, PUT---> false(expected: true)
```

**Comment by tangyang9464** [comment]
@hahattan Whether the relationship between Operator and admin can be cancelled？Assign permissions to both roles separately

**Comment by hahattan** [comment]
Did you mean not using the role inherit and just assign permission like:
```
p, Viewer, api, GET
p, Operator, api, (PUT)|(GET)
p, Operator, secret_api, PUT, deny
p, Admin, api, (PUT)|(GET)

g, /api/*, api
g, /api/secret/*, secret_api
```

If it's the only working solution I'm happy to go with it I'm just testing the RBAC system to see if I can reduce some similar configuration(policy).

Also might be off-topic here but could you explain more on the `g(r.obj, p.obj)` matcher in RBAC system ?
Take this request for example: Operator, /api/secret/test, PUT
Does that mean the request object, `/api/secret/test`, should have a corresponding role in the policy (`secret_api` in this case) ?

**Comment by tangyang9464** [comment]
> Did you mean not using the role inherit and just assign permission

Yes, because there doesn't seem to be a hierarchy between them

> Also might be off-topic here but could you explain more on the `g(r.obj, p.obj)` matcher in RBAC system ?
> Take this request for example: Operator, /api/secret/test, PUT
> Does that mean the request object, `/api/secret/test`, should have a corresponding role in the policy (`secret_api` in this case) ?

yes, ``g()`` is used to determine whether there is a hierarchical relationship

**Comment by hahattan** [comment]
thanks for the explanation, no more question for now .
