### ISSUE TITLE
[Bug] When SetRoleManager and using v2.43.2 and later verison  causing authorization fail.

### ISSUE THREAD

**Issue by zzzkl** [casbin/casbin#1037]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
Using v2.43.2 and later verison causing authorization fail.
In v2.43.1 the result is true, v2.43.2 the result is false
Maybe related to #942

**To Reproduce**
1. **Set `enforcer.SetRoleManager(defaultrolemanager.NewRoleManager(1))`**

Model:
```
[request_definition]
r = userId, url, namespace, method

[policy_definition]
p = roleId, url, method

[policy_effect]
e = some(where (p.eft == allow))

[role_definition]
g = _, _
g2 = _, _

[matchers]
m = ((r.namespace == "" || g2(r.namespace, p.roleId)) && r.method == p.method && g(r.userId, p.roleId) &&  keyMatch2(r.url, p.url))
````

Policy:
```
p, 12, /api/deployment/:namespace, GET

g, 100001, 12
g2, test-ns, 12
```

Request:
```100001, /api/deployment/test-ns, test-ns, GET```

**Expected behavior**
In all version result should be true. 

**Desktop (please complete the following information):**
 - OS: MacOS 12

**Comment by hsluoyz** [comment]
@JalinWang @imp2002 plz resolve it

/cc @tangyang9464

**Comment by zzzkl** [comment]
Maybe related to https://github.com/casbin/casbin/pull/942

**Comment by hsluoyz** [comment]
@abichinger
