### ISSUE TITLE
RBAC with global roles

### ISSUE THREAD

**Issue by manojSelvam** [casbin/casbin#104]
I am trying to use casbin for a project to perform RBAC with user group and resource group,

From the online examples i created the following,  
```  
p, role:north_site_manager, group:refrigeration_alarms, alarmapi.alarmgroup.create
// assign user to role
g,  user:alice, role:north_site_manager

g2, data2, group:refrigeration_alarms
g2, data5, group:refrigeration_alarms
```

in the above example we are,
-  creating a role , a group along with an action
- adding users to the role
- adding resource to the group

This means while creating a group of resources we need to create a role associated with it. 

But i would like to model  the following scenario,

- create a set of global roles (roles => collection of permissions( resource type + action))
- Create a group of resources
- Add predefined roles  to the group
- Add uses to the group
```
// example global roles on resource type alarm group. 
p, alarmgroup.owner, alarmgroup, alarmapi.alarmgroup.create
p, alarmgroup.owner, alarmgroup, alarmapi.alarmgroup.delete
p, alarmgroup.owner, alarmgroup, alarmapi.alarmgroup.list
p, alarmgroup.owner, alarmgroup, alarmapi.alarmgroup.update

p, alarmgroup.editor, alarmgroup, alarmapi.alarmgroup.list
p, alarmgroup.editor, alarmgroup, alarmapi.alarmgroup.update

p, alarmgroup.viewer, alarmgroup, alarmapi.alarmgroup.list
```
Any help on this would be greatly appreciated!

**Comment by hsluoyz** [comment]
I didn't quite understand your second example. Can you be more specific?

**Comment by manojSelvam** [comment]
```
# role definition by resource type 
p, role:global:alarmgroup.viewer, alarmgroup, alarmapi.alarmgroup.list
p, role:global:alarmgroup.viewer, alarmgroup, alarmapi.alarmgroup.get
p, role:global:alarmgroup.editor, alarmgroup, alarmapi.alarmgroup.create
p, role:global:alarmgroup.owner, alarmgroup, alarmapi.alarmgroup.delete

# role inheritance
g, role:global:alarmgroup.editor, role:global:alarmgroup.viewer
g, role:global:alarmgroup.owner, role:global:alarmgroup.editor

# creating a resource group
p, role:refrigeration_alarms_role, group:refrigeration_alarms, alarmapi.alarmgroup.get

# assign roles to resource group role
g2, role:refrigeration_alarms_role, role:global:alarmgroup.owner

# add role to user
g, alice, role:refrigeration_alarms

# add resources to resource group
g2, alarmgroup:ag1, group:refrigeration_alarms
g2, alarmgroup:ag2, group:refrigeration_alarms
```

in this example alice has inherited **role:global:alarmgroup.owner** but Alice still cannot invoke **alarmapi.alarmgroup.delete** on **alarmgroup:ag1**.  

Can this be modelled in such a way that alice get access to resource **alarmgroup:ag1**  because she is a **role:global:alarmgroup.owner**

So If the permissions associated with the global role were to be changed it could be done in a single location.

**Comment by hsluoyz** [comment]
You said that: ``in this example alice has inherited role:global:alarmgroup.owner``, but what I see in your policy is alice inherits ``role:refrigeration_alarms``. I don't think ``role:refrigeration_alarms`` is the same thing as ``role:global:alarmgroup.owner``?

**Comment by manojSelvam** [comment]
sorry, that is a mistake in the example. 
```
 # assign roles to resource group role
g2, role:refrigeration_alarms_role, role:global:alarmgroup.owner
```
the above should have been 
```
# role inheritance
g, role:refrigeration_alarms_role, role:global:alarmgroup.owner
```
```role:refrigeration_alarms_role``` inherits from ```role:global:alarmgroup.owner``` which makes alice an alarm group owner.

**Comment by manojSelvam** [comment]
@hsluoyz  any thoughts ?

**Comment by hsluoyz** [comment]
Your example is too complicated.. I didn't quite understand it. Can you try to simplify the example? For example, use ``role1, role2, resource1, resource2, group1, group2`` instead of the complicated names.

**Comment by manojSelvam** [comment]
```
# role definition by resource type 
# the roles defined here are by resource type
# project is a type of resource which could contain other resourcs forming a resource hierarchy.

p, project_viewer, project, projects.list
p, project_viewer, project, projects.get
p, project_editor, project, projects.create
p, project_owner, project, projects.delete

# role inheritance
# project_editor inherits project_viewer
# project_viewer inherits  project_editor
g, project_editor, project_viewer
g, project_owner, project_editor

# creating a resource group
p, finance_admin, finance_department, projects.list

# assign roles to resource group role
# all finance admins need to get project_owner permissions on projects 
g2, finance_admin, project_owner

# add role to user
# alice is now a finance admin
g, alice, project_owner

# Adding projects to finance_department
g2, project:projectId1, finance_department
g2, project:projectId2, finance_department
```

Alice is now a finance_admin and she has project_owner level permissions through role inheritance. 

I would want alice to have admin permissions to any projects added to finance_department group.
But while adding a resource to finance_department we add ```project:projectId2``` a project with an id.


Can this be modelled in such a way that alice can perform ```project_owner``` actions on ```project:projectId2```

So If the permissions associated with the project_owner were to be changed it could be done in a single location.

**Comment by manojSelvam** [comment]
eg:- hierarchy 

![image](https://user-images.githubusercontent.com/4885821/41154640-a2f894e0-6b12-11e8-9b86-63096462c16d.png)

``` alice gets access to topic_a  because she is the editor of  the project```
![image](https://user-images.githubusercontent.com/4885821/41154705-f020ec18-6b12-11e8-9285-50269caacaab.png)

**Comment by hsluoyz** [comment]
> g2, finance_admin, project_owner

Should this be ``g`` instead of ``g2``? Because you are describing role on users. ``g2`` is used to describe role on resources.

> alice is now a finance admin
> g, alice, project_owner

I don't see why alice is a finance admin now. The ``g`` statement only means alice is a ``project_owner``.

**Comment by manojSelvam** [comment]
@hsluoyz do you need any more details on the example.

**Comment by hsluoyz** [comment]
Your example is too complicated, you need to make a minimized working example.
