### ISSUE TITLE
Subject priority and then override allow?

### ISSUE THREAD

**Issue by timabilov** [casbin/casbin#1042]
I want to give priority to my subject, and then between subjects i want to use  allow-override but only between my subject policies (ignoring extended policies because of the subject priority) .

**Comment by tangyang9464** [comment]
@timabilov Please give the model and policy you want

**Comment by sagilio** [comment]
@tangyang9464  Priority and allow/deny-override effect expression are combinable, here is a similar issue: https://github.com/casbin/Casbin.NET/issues/188
More like the concept of dividing different policies set by priority.
