### ISSUE TITLE
[Question]Can casbin support clear policy by domain?

### ISSUE THREAD

**Issue by lynnzhang89** [casbin/casbin#1047]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
In my scenario, i have lots of domain. Each domain has lots of policy. After i made a modification on a policy under a domain, i've to load all policy under all domain to update casbin. 
So, is there any possible to support clear specify domain and load specify domain.

**Comment by JalinWang** [comment]
How do you modify the policies? If you modify through Casbin's APIs, there is no need to reload.

**Comment by hsluoyz** [comment]
@lynnzhang89 can you use delete filtered policy API?

**Comment by hsluoyz** [comment]
@lynnzhang89 use: https://casbin.io/docs/management-api#removefilteredpolicy
