### ISSUE TITLE
Can matcher be defined with multiple lines?

### ISSUE THREAD

**Issue by pencil001** [casbin/casbin#105]
Can I define the mathcer as the following?
```
[matcher]
m = r.xxx == p.xxx ||
        r.yyy == p.yyy
```

Because my matcher would be a little long. It will not be maintainable if it in one line.

**Comment by hsluoyz** [comment]
Multi-line matcher is not supported yet. But I think we can add it by allowing ``\`` in the end. For example, in C++, we can express it as:

```c++
char s[] = "abcd\
 efg";
```

Your matcher can be expressed as:

```ini
[matcher]
m = r.xxx == p.xxx || \
    r.yyy == p.yyy
```

Can you make a PR about it?

**Comment by hsluoyz** [comment]
Multi-line matcher is supported now, see: https://github.com/casbin/casbin#how-it-works

```ini
# Request definition
[request_definition]
r = sub, obj, act

# Policy definition
[policy_definition]
p = sub, obj, act

# Policy effect
[policy_effect]
e = some(where (p.eft == allow))

# Matchers
[matchers]
m = r.sub == p.sub && r.obj == p.obj && r.act == p.act

# We also support multi-line mode by appending '\' in the end:
# m = r.sub == p.sub && r.obj == p.obj \ 
#  && r.act == p.act
```
