### ISSUE TITLE
[Feature]GetImplicitResourcesForUser support muti domain

### ISSUE THREAD

**Issue by czyt** [casbin/casbin#1053]
the current `GetImplicitResourcesForUser`defined as below:
```go
func (e *Enforcer) GetImplicitResourcesForUser(user string, domain ...string) ([][]string, error)
```
the domain paramerter can be treated as an optional parameter but for query muti domain,it will show error
```go
domain should be 1 parameter
```
is it possible to allow muti domains pass in as parameters?

**Comment by imp2002** [comment]
@czyt What `GetImplicitResourcesForUser` really executes is:
https://github.com/casbin/casbin/blob/cfc60ff3ef8c45bf9213c39da92070665439e82b/rbac_api.go#L297-L324

From the logic of the code, muti domain should be ok. When param domain unfilled, it will get resources of user in any domain, When param domain filled, it will get resources of user in domains of param domain. Could you post your code and error info?

**Comment by JalinWang** [comment]
> @czyt What `GetImplicitResourcesForUser` really executes is:
> 
> https://github.com/casbin/casbin/blob/cfc60ff3ef8c45bf9213c39da92070665439e82b/rbac_api.go#L297-L324
> 
> From the logic of the code, muti domain should be ok. When param domain unfilled, it will get resources of user in any domain, When param domain filled, it will get resources of user in domains of param domain. Could you post your code and error info?

@imp2002 You can refer to default-role-manager and this is where the error occurs.

```go
func (dm *DomainManager) getDomain(domains ...string) (domain string, err error) {
	switch len(domains) {
	case 0:
		return defaultDomain, nil
	case 1:
		return domains[0], nil
	default:
		return "", errors.ERR_DOMAIN_PARAMETER
	}
}
```

**Comment by JalinWang** [comment]
I think it might be a bug. For dependencies of `GetImplicitResourcesForUser()`,  `GetImplicitPermissionsForUser()` supports multiple domains while `GetImplicitUsersForRole` only supports `len(domain)==1`. 
```go
func (e *Enforcer) GetImplicitResourcesForUser(user string, domain ...string) ([][]string, error) {
	permissions, err := e.GetImplicitPermissionsForUser(user, domain...)  //  GetImplicitPermissionsForUser supports multiple domains!
	// ……
	for _, permission := range permissions {
		// ……
		for _, token := range permission[1:] {
			tokens, err := e.GetImplicitUsersForRole(token, domain...)  // GetImplicitUsersForRole only support len(domain)==1
			// ……
		}
		// ……
	}
	return res, nil
}
```
Should we modify `GetImplicitUsersForRole` or just `GetImplicitResourcesForUser`? 
Or do we need to change `GetImplicitPermissionsForUser` back (of which multi-domain support is introduced by #992 ) for consistency across all the functions that have the` domain ...string` parameter, e.g., `GetRolesForUser(name string, domain ...string)`?

**Comment by JalinWang** [comment]
@czyt Sorry but we don't have much need to support multi-domains. The variadic parameter is designed to make it optional. 
If you want to use APIs with multiple domains, you can wrap them with a `for` loop over domains.

**Comment by JalinWang** [comment]
> @JalinWang In most places domain means single, but this is changed in #992. If it's for easier compatibility, you can revert #992 related change

Roger that.

**Comment by tangyang9464** [comment]
@czyt Is the for loop acceptable to you? Or do you have a lot of domains

**Comment by czyt** [comment]
> @czyt Is the for loop acceptable to you? Or do you have a lot of domains

yes,i use for loop to process muti domains in my project now.
