### ISSUE TITLE
[Feature] add golangci-lint like casdoor

### ISSUE THREAD

**Issue by qianxi0410** [casbin/casbin#1054]
Add the configuration file of golangci check like casdoor, which can improve some code quality.

I'd be happy to provide a pr if possible.

**Comment by tangyang9464** [comment]
@qianxi0410 casbin uses golangci-lint in [default.yml](https://github.com/casbin/casbin/blob/master/.github/workflows/default.yml), are they any big difference?

**Comment by qianxi0410** [comment]
Sorry, I didn't notice this.
But providing the .golangci file allows for some review while the code is being written, rather than deferring to CI.
@tangyang9464

**Comment by tangyang9464** [comment]
> 

It's ok, you can do it.

**Comment by hsluoyz** [comment]
@qianxi0410 let's see the improvement result in the PR

/cc @tangyang9464
