### ISSUE TITLE
[Question] How to keep consistency in casbin operations such as AddPolicy?

### ISSUE THREAD

**Issue by sasakiyori** [casbin/casbin#1059]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

The code below is fetched from casbin source code.

Suppose that I have multiple casbin instances, and one of them get a request to do `AddPolicy` operation. And when it use adpater to add policy for rule persistence, error occurs. But at this moment the dispatcher has broadcasted the message for adding a new policy, and if other instances successfully add it up, the consistency between instances will be broken.

A simpler example is if casbin for single instance persists successfully but error happens after it, user get the response is `fail to add policy`, and when we call `Enforce`, it actually return no matched policy. But if we reload by adapter(like `LoadPolicy`), then `Enforce` will return true now. Datas persisted in database and the role manager in the memory should keep consistency, right?

BTW, I don't think we should easily change the calling sequence in the code to solve this problem(such as dispatch at the end of function). What if adding a `ROLLBACK` mechanism for these similar functions?

**Updated:**
I find when dispatcher is enabled, it will immediately return result by dispatcher's function. Sorry for giving a wrong case, but my question is still for consistency in these operations, especially in multiple instances scenarios. Thanks in advance :)

```go
func (e *Enforcer) addPolicy(sec string, ptype string, rule []string) (bool, error) {
	if e.dispatcher != nil && e.autoNotifyDispatcher {
		return true, e.dispatcher.AddPolicies(sec, ptype, [][]string{rule})
	}

	if e.model.HasPolicy(sec, ptype, rule) {
		return false, nil
	}

	if e.shouldPersist() {
                 // 1st example: what if error occurs here?
		if err := e.adapter.AddPolicy(sec, ptype, rule); err != nil {
			if err.Error() != notImplemented {
				return false, err
			}
		}
	}

        // 2nd example: what if error occurs after here?
	e.model.AddPolicy(sec, ptype, rule)

	if sec == "g" {
		err := e.BuildIncrementalRoleLinks(model.PolicyAdd, ptype, [][]string{rule})
		if err != nil {
			return true, err
		}
	}

	if e.watcher != nil && e.autoNotifyWatcher {
		var err error
		if watcher, ok := e.watcher.(persist.WatcherEx); ok {
			err = watcher.UpdateForAddPolicy(sec, ptype, rule...)
		} else {
			err = e.watcher.Update()
		}
		return true, err
	}

	return true, nil
}
```

**Comment by hsluoyz** [comment]
@JalinWang 

/cc @tangyang9464

**Comment by JalinWang** [comment]
HI~ Thanks for concerning about Casbin. 
In fact, `e.model.AddPolicy` intends not to fail, which only involves in-memory map/array operations and `adapter.AddPolicy(sec, ptype, rule)` should ensure its own ACID https://en.wikipedia.org/wiki/ACID. 
I don't see any case to result in the inconsistency so far. It will be appreciated if you could forge a scenario of inconsistency and provide the code~

**Comment by sasakiyori** [comment]
@JalinWang 
> adapter.AddPolicy(sec, ptype, rule) should ensure its own ACID

Yes, I agree with it, and this is what I do for my own adapter.

> In fact, e.model.AddPolicy intends not to fail, which only involves in-memory map/array operations

If `e.model.AddPolicy` and `e.BuildIncrementalRoleLinks` is guaranteed as absolutely executed successfully, there are no inconsistency cases indeed.

A possible case is watcher's error:
When we are using `Watcher` for consistency in multi-instances, if the message middleware we used in the watcher(such as redis) is temporarily not accessible, the operations for policies cannot be synced to other instances except the requested one. But maybe casbin no need to consider about this scenario? We should leave it to users...?

**Comment by JalinWang** [comment]
> A possible case is watcher's error: When we are using `Watcher` for consistency in multi-instances, if the message middleware such as redis we used in the watcher is temporarily not accessible(or just something error occurs), the operations for policies cannot be synced to other instances except the requested one. But maybe casbin no need to consider about this scenario? We should leave it to users...?

Good point. 
Generally speaking, we can rely on a retry mechanism. However,  it needs to be carefully designed (gap, max attempts, rate-controlling etc.) to avoid some failures, e.g., avalanche effect in micro-service architecture [ref](https://blog.birost.com/a?ID=01350-af11207e-38ef-46ac-8ba0-ef8a3b002bde), and tackle the newly introduced problems, e.g., watcher's idempotence for message delivery [ref](https://cap.dotnetcore.xyz/user-guide/en/cap/idempotence/). 
Consequently, we provide no internal error handling for watcher other than notifying the caller there's an error `return true, err`. Users can resend notifications manually, auto-reload at a specific time schedule, or use the RAFT algorithm, i.e., the [Dispatcher](https://github.com/casbin/hraft-dispatcher) interface for stronger consistency.

**Comment by sasakiyori** [comment]
Yes, it's meaningless for casbin to do so many things, users solve it by themselves would be better.
