### ISSUE TITLE
[Question]Can Casbin read policies from the database without loading them into memory?

### ISSUE THREAD

**Issue by Amf1k** [casbin/casbin#1063]
**What's your scenario? What do you want to achieve?**
We make our service for checking access based on the Restful model. Our policies may change frequently and we must maintain a high rate of request processing.
For our task, we took a postgres adapter and a CachedEnforcer with Redis cache.
We have a problem when we try to update policies in several instances of the service, but they are loaded from the adapter into the application memory in csv representation - we used the WatcherEx interface to solve this problem.
is it possible not to somehow load policies into memory and implement a simple flow - check the value in the cache and if it is not there - contact the database for them? Can a FilteredAdapter help us with this?

**Comment by hsluoyz** [comment]
@JalinWang 

/cc @tangyang9464

**Comment by JalinWang** [comment]
> is it possible not to somehow load policies into memory and implement a simple flow - check the value in the cache and if it is not there - contact the database for them? Can a FilteredAdapter help us with this?

@Amf1k  Sorry, but it seems not possible for now.  
`FilteredAdapter ` is mainly designed to load policies by domains, cf. https://casbin.io/docs/policy-subset-loading. It is not generic enough to deal with your on-request load. Taking an RBAC example, let's assume `alice` is `admin` and `admin` can modify `data`. When you want to enforce `alice, data, modify`, it seems no way to load precisely.
However, I think you can make an attempt by using it & modify `CachedEnforcer` if you can afford the delay (high cache hit rate or low network latency). Further, if you rely on the Redis's high performance and your model is simple, e.g., ACL, you can directly use Redis for matching, where Casbin can not help you a lot.

**Comment by hsluoyz** [comment]
@Amf1k Casbin is a memory model. All policy rules are supposed to be fetched from memory finally. You can manually call Load(Filtered)Policy() at the beginning of each request processing.
