### ISSUE TITLE
[Bug] inconsisitent cache when updating policy & adding a deny rule

### ISSUE THREAD

**Issue by JalinWang** [casbin/casbin#1065]
[`CachedEnforcer`](https://github.com/casbin/casbin/blob/master/enforcer_cached.go) can not handle the update requests, i.e., it does not invalidate the cache.

Also, if `AddPolicy()` add a user deny rule, e.g., `alice, data, read, deny`, or role deny rule, e.g., `admin, data, read, deny`, the cache is also buggy. Do we need to consider such case?

Screenshot about the lack of cached version update in `CachedEnforcer`:
![image](https://user-images.githubusercontent.com/20621784/181756752-bcc481f0-4bfc-4f3c-a1f8-07519bc0b35e.png)

![image](https://user-images.githubusercontent.com/20621784/181756283-6c049aa5-30ec-40de-8d53-3e8d0637b993.png)

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by hsluoyz** [comment]
can't agree more with @tangyang9464

**Comment by michaelknowles** [comment]
If there are no complaints and no work already in progress here, I'd like to work on a PR for this.  We just switched to the CachedEnforcer to reduce allocations from regex and are running into these edge cases now.

**Comment by hsluoyz** [comment]
@michaelknowles the contribution is welcome!

**Comment by hsluoyz** [comment]
Closed as stale
