### ISSUE TITLE
[Question] what does 'sec string' using for?

### ISSUE THREAD

**Issue by RainshawGao** [casbin/casbin#1067]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Hi, thanks for your excellent work!  I want to write a new adapter which only suites my companies.
After looking around, I have few questions:
what does the `sec` param of edit functions of Adapter interface using to do? it seems that it is the same with ptype...

**Comment by hsluoyz** [comment]
@JalinWang

**Comment by JalinWang** [comment]
@RainshawGao Hi~ Thanks for your concern.
`sec` and `ptype` are usually the same, but not always, e.g., `sec=p & ptype=p2`. You can refer to https://casbin.io/docs/syntax-for-models#policy-definition and https://casbin.io/docs/syntax-for-models#multiple-sections-type.

**Comment by RainshawGao** [comment]
oh~ thanks for your comment. I got it.
