### ISSUE TITLE
Difference Between casbin v2 and v3?

### ISSUE THREAD

**Issue by GerryLon** [casbin/casbin#1070]

**Comment by hsluoyz** [comment]
@GerryLon there's no v3 yet.

**Comment by GerryLon** [comment]
> @GerryLon there's no v3 yet.

https://github.com/casbin/casbin/tree/v3.0.0-beta.7

**Comment by hsluoyz** [comment]
@nodece

**Comment by hsluoyz** [comment]
@GerryLon that v3 branch has been deprecated. Please keep on using v2 latest
