### ISSUE TITLE
some questions after judgment

### ISSUE THREAD

**Issue by JarynChen** [casbin/casbin#1077]
After the casbin judgment is completed, I get the result of true or false. If I need to return different errors to the client according to different rules, may I ask if there is a way for me to obtain the specific rule that fails the verification?

**Comment by JalinWang** [comment]
> After the casbin judgment is completed, I get the result of true or false. If I need to return different errors to the client according to different rules, may I ask if there is a way for me to obtain the specific rule that fails the verification?

@JarynChen Are you looking for something like https://casbin.io/docs/management-api#enforceex, i.e., enforcing with explanations?

**Comment by JarynChen** [comment]
> > After the casbin judgment is completed, I get the result of true or false. If I need to return different errors to the client according to different rules, may I ask if there is a way for me to obtain the specific rule that fails the verification?
> 
> @JarynChen Are you looking for something like `EnforceEx`, i.e., enforcing with explanations? Ref: https://casbin.io/docs/api-overview#enforceex-api https://casbin.io/docs/management-api#enforceex

That's exactly what I wanted, thanks!
