### ISSUE TITLE
Is it possible let a user has all permissions by default?

### ISSUE THREAD

**Issue by Humbertzhang** [casbin/casbin#108]
If I want to set a superadmin, if it possible to use a policy to let him has permission for all resources? <br>
I don't want to add permission for the superadmin when I set up a resource, instead of it, I want this user has permission for it by default, but i didn't see this kind of policy in doc.

**Comment by hsluoyz** [comment]
You can see the ``ACL with superuser`` example at: https://github.com/casbin/casbin#examples. In this example, the ``root`` user has the permission to do everything. I paste its model here:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && r.obj == p.obj && r.act == p.act || r.sub == "root"
```

You can also setup a superadmin role, and let the users that have the role have permission to do everything. You can mix the RBAC model with the Superuser model to get it.

**Comment by Humbertzhang** [comment]
I see. Thank you for your response!
