### ISSUE TITLE
[Question] affected vs effected

### ISSUE THREAD

**Issue by JalinWang** [casbin/casbin#1081]
A subtle but divergent problem exists across all the codebase: Should we use `effected` or `affected`?
Example:
```golang
// AddPoliciesWithAffected adds policy rules to the model, and returns effected rules.
func (model Model) AddPoliciesWithAffected(sec string, ptype string, rules [][]string) [][]string {
	var effected [][]string
//...
	return effected
}
// RemovePoliciesWithEffected removes policy rules from the model, and returns effected rules.
func (model Model) RemovePoliciesWithEffected(sec string, ptype string, rules [][]string) [][]string {
///...
}
```
`affected` in Casbin:
https://github.com/casbin/casbin/search?q=affected
`effected` in Casbin:
https://github.com/casbin/casbin/search?q=effected
`affected` in Casdoor:
https://github.com/casdoor/casdoor/search?q=affected

**Comment by hsluoyz** [comment]
@JalinWang `affected` is correct English
