### ISSUE TITLE
[Bug] err not returned in Func LoadPolicyArray

### ISSUE THREAD

**Issue by GerryLon** [casbin/casbin#1083]
Casbin version: v2.52.2
Bug: err not returned in Func LoadPolicyArray
<img width="1259" alt="企业微信截图_f722d946-f311-4426-8e5f-c231b9bb26f3" src="https://user-images.githubusercontent.com/25873611/185780362-f8b56b16-376b-4e26-9909-b1b21fde59be.png">

**Comment by hsluoyz** [comment]
@JalinWang plz work on it

/cc @tangyang9464

**Comment by GerryLon** [comment]
why not allow empty `v5` fields?

**Comment by JalinWang** [comment]
> why not allow empty `v5` field? I use `v5` field as a condition(value can be any string), empty v5 field means "any conditioin can pass(like any client ip)". I think empty string as any condition is general.

@GerryLon  Which adapter?

**Comment by GerryLon** [comment]
> > why not allow empty `v5` field? I use `v5` field as a condition(value can be any string), empty v5 field means "any conditioin can pass(like any client ip)". I think empty string as any condition is general.
> 
> @GerryLon Which adapter?

```go
	"github.com/casbin/casbin/v2/persist"
	mongodbadapter "github.com/casbin/mongodb-adapter/v3"
```

**Comment by GerryLon** [comment]
> > why not allow empty `v5` field? I use `v5` field as a condition(value can be any string), empty v5 field means "any conditioin can pass(like any client ip)". I think empty string as any condition is general.
> 
> @GerryLon Which adapter?

my main codes like below:

```go
package auth

import (
  "github.com/casbin/casbin/v2"
  mongodbadapter "github.com/casbin/mongodb-adapter/v3"
)

func InitCasbin() {
  // 定义基于mongodb的casbin适配器
  adapter, err = mongodbadapter.NewAdapterWithClientOption(mongoClientOption, databaseName)
  if err != nil {
    log.ErrorContext(ctx, err)
    return nil, err
  }
  casbinModel, err = casbinmodel.NewModelFromString(mconf)
  if err != nil {
    log.ErrorContext(ctx, err)
    return nil, err
  }
  enforcer, err = casbin.NewSyncedEnforcer(casbinModel, adapter)
  if err != nil {
    log.ErrorContext(ctx, err)
    return nil, err
  }

  // load policy from db or file into memory
  if err = enforcer.LoadPolicy(); err != nil {
    log.ErrorContext(ctx, err)
    return nil, err
  }
}
```

when I debug above codes, in `enforcer.LoadPolicy()` -> ... -> LoadPolicyArray()` error is not nil:
![image](https://user-images.githubusercontent.com/25873611/185781582-20420983-c9b0-425d-b7f8-cfe3dbd5a8d7.png)

**Comment by hsluoyz** [comment]
> why not allow empty `v5` field? I use `v5` field as a condition(value can be any string), empty v5 field means "any conditioin can pass(like any client ip)". I think empty string as any condition is general.

@GerryLon are you reporting a new issue other than this one? If yes, plz create a new issue here: https://github.com/casbin/mongodb-adapter/issues

**Comment by JalinWang** [comment]
> > > why not allow empty `v5` field? I use `v5` field as a condition(value can be any string), empty v5 field means "any conditioin can pass(like any client ip)". I think empty string as any condition is general.
> > 
> > 
> > @GerryLon Which adapter?
> 
> github.com/casbin/mongodb-adapter/v3 v3.3.0
> 
> ```go
> 	"github.com/casbin/casbin/v2/persist"
> 	mongodbadapter "github.com/casbin/mongodb-adapter/v3"
> ```

Which method do you use?

**Comment by JalinWang** [comment]
> @JalinWang plz work on it
> 
> /cc @tangyang9464

@hsluoyz All the adapters depend on this function without error handling. Should we modify them all?

**Comment by hsluoyz** [comment]
We can add error as return value, but the adapters don't need to be modified to handle the return value
