### ISSUE TITLE
[Question] How to write the model and policy?

### ISSUE THREAD

**Issue by ChenHaolinOlym** [casbin/casbin#1087]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

I'm building a music sheet archive database, which have the following requirements:

- `User` belongs to `Band`
- `User` plays `Instrument`
- `Sheet` belongs to `Song`
- `Sheet` is for `Instrument`

For example:
John and Paul belongs to the Beatles, John plays guitar and Paul plays bass. There are two sheets archived in the database, "Let It Be-Guitar" and "Let It Be-Bass", they belong to song "Let It Be". What I want is when I assign the read permission of "Let It Be" to the Beatles, John can only read "Let It Be-Guitar" and Paul can only read "Let It Be-Bass".

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && r.act == p.act
```

**Your policy:**

```
g, John, guitar
g, Paul, bass
g, John, Beatles??
g, Paul, Beatles??

g2, Let It Be-Guitar, Let It Be
g2, Let It Be-Bass, Let It Be
g2, Let It Be-Guitar, guitar??
g2, Let It Be-Bass, bass??

p, Beatles, Let It Be, read??
```

**Your request(s):**

```
John, Let It Be-Guitar, read ---> true (expected: true)
John, Let It Be-Bass, read ---> true (expected: false)
Paul, Let It Be-Guitar, read ---> true (expected: false)
Paul, Let It Be-Bass, read ---> true (expected: true)
```

Directly assign permissions like `p, John, Let It Be-Guitar, read` is not acceptable, since some of the archived pieces are symphony orchestra ones which normally would have 80+ `User`s and 20+ `Sheet`s each, so it would generate far too much policies as the database growing bigger. For the same reason, the solution in #946 is also not fit for this scenario.

**Comment by hsluoyz** [comment]
@JalinWang @tangyang9464

**Comment by JalinWang** [comment]
@ChenHaolinOlym One example （This is not the only way）:
```
g, John, Beatles
g, Paul, Beatles
g2, John, Guitar
g2, Paul, Bass

p, Beatles, Let It Be-{instrument}, read
```
````
[matchers]
m = g(r.sub, p.sub) && keyMatch3(r.obj,p.obj) && g2(r.sub, keyGet3(r.obj, p.obj, 'instrument')) && r.act == p.act
```


Test Code:
```go

func TestCust(t *testing.T) {
	text :=
		`
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyMatch3(r.obj,p.obj) && g2(r.sub, keyGet3(r.obj, p.obj, 'instrument')) && r.act == p.act
`
	m, _ := model.NewModelFromString(text)
	// The above is the same as:
	// m := NewModel()
	// m.LoadModelFromText(text)

	e, _ := NewEnforcer(m)

	//g, John, Beatles
	//g, Paul, Beatles
	//g2, John, Guitar
	//g2, Paul, Bass
	//
	//p, Beatles, Let It Be-{instrument}, read

	_, _ = e.AddNamedGroupingPolicy("g", "John", "Beatles")
	_, _ = e.AddNamedGroupingPolicy("g2", "John", "Guitar")
	_, _ = e.AddPolicy("Beatles", "Let It Be-{instrument}", "read")

	testEnforce(t, e, "John", "Let It Be-Guitar", "read", true)
	testEnforce(t, e, "John", "Let It Be-Bass", "read", false)
}
```

**Comment by ChenHaolinOlym** [comment]
> @ChenHaolinOlym One example （This is not the only way）:
> 
> ```
> g, John, Beatles
> g, Paul, Beatles
> g2, John, Guitar
> g2, Paul, Bass
> 
> p, Beatles, Let It Be-{instrument}, read
> ```
> 
> ```
> [matchers]
> m = g(r.sub, p.sub) && keyMatch3(r.obj,p.obj) && g2(r.sub, keyGet3(r.obj, p.obj, 'instrument')) && r.act == p.act
> ```
> 
> Test Code:
> 
> ```go
> func TestCust(t *testing.T) {
> 	text :=
> 		`
> [request_definition]
> r = sub, obj, act
> 
> [policy_definition]
> p = sub, obj, act
> 
> [role_definition]
> g = _, _
> g2 = _, _
> 
> [policy_effect]
> e = some(where (p.eft == allow))
> 
> [matchers]
> m = g(r.sub, p.sub) && keyMatch3(r.obj,p.obj) && g2(r.sub, keyGet3(r.obj, p.obj, 'instrument')) && r.act == p.act
> `
> 	m, _ := model.NewModelFromString(text)
> 	// The above is the same as:
> 	// m := NewModel()
> 	// m.LoadModelFromText(text)
> 
> 	e, _ := NewEnforcer(m)
> 
> 	//g, John, Beatles
> 	//g, Paul, Beatles
> 	//g2, John, Guitar
> 	//g2, Paul, Bass
> 	//
> 	//p, Beatles, Let It Be-{instrument}, read
> 
> 	_, _ = e.AddNamedGroupingPolicy("g", "John", "Beatles")
> 	_, _ = e.AddNamedGroupingPolicy("g2", "John", "Guitar")
> 	_, _ = e.AddPolicy("Beatles", "Let It Be-{instrument}", "read")
> 
> 	testEnforce(t, e, "John", "Let It Be-Guitar", "read", true)
> 	testEnforce(t, e, "John", "Let It Be-Bass", "read", false)
> }
> ```

It works, thanks.
