### ISSUE TITLE
[Question] role cross reference is it harmless？

### ISSUE THREAD

**Issue by HimawariSunFlower** [casbin/casbin#1088]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
i'm building a RBAC access control  system,and i wanna kown my AddRolesForUser verify Is it necessary?

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, data1_user, data1, read
p, data2_admin, data2, read
p, data2_admin, data2, write

g, data1_user, data2_admin
```

**Your request(s):**

if Enforcer.AddRolesForUser("data2_admin","data1_user") pass ,policy will add "g,data2_admin,data1_user".Is it harmless？or i need check param before use function.i'm tried testing,it's look like harmless,but i wanna konw a true answer.

**Comment by hsluoyz** [comment]
@JalinWang 

/cc @tangyang9464

**Comment by JalinWang** [comment]
@HimawariSunFlower Thanks for concerning.
I think it's okay. I don't see any problem till now.

**Comment by hsluoyz** [comment]
Closed as resolved

**Comment by HimawariSunFlower** [comment]
> @HimawariSunFlower Thanks for concerning. I think it's okay. I don't see any problem till now.

thanks!
