### ISSUE TITLE
Usage scenarios of Casbin RBAC model in multi-tenancy

### ISSUE THREAD

**Issue by zhulinwei** [casbin/casbin#1091]
**Describe the bug**

model file:
```
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g(r.sub, p.sub, r.dom) || g2(r.sub, "Global")) && keyMatch2(r.obj, p.obj) && (r.act == p.act || p.act == "*")
```

policy file:
```
p, Global, project::project_4, resource::app4, *
g2, user::zlw4, Global
```

1. input `user::zlw4, project::project_4, resource::app4, action::read`, expect `true`, output `true`;
2. input  `user::zlw4, project::project_4, resource::app4, action::anything`, expect `true`, output `true`;
3. input `user::zlw4, project::project_4, resource::anything, action::anything`, expect `false`, but output `true`;
4. input `user::zlw4, project::other, resource::anything, action::anything`, except `false`, but output `true`;

**Desktop (please complete the following information):**
 - OS: mac
 - Browser:  chrome

**Comment by zhulinwei** [comment]
## Scenes 1:  user A1 under Tenant B1 has permissions to resource C1

Configure fine-grained permissions on general user (such as read-only permissions)

```
p, group::develeper1, project::projectId_1, resource::app1, action::read
g, user::zlw1, group::develeper1, project::projectId_1
```
sample
+ input `user::zlw1, project::projectId_1, resource::app1, action::read`, expect `true`, ouput `true`.
+ input `user::zlw1, project::projectId_1, resource::app1, action::write`, expect `false`, ouput `false`.

##  Scenes 2: user A2 under Tenant B2 has all permissions to resource C2.

Configure coarse-grained permissions on general user

```
p, group::develeper2, project::projectId_2, resource::app2, *
g, user::zlw2, group::develeper2, project::projectId_2
```

Sample:

+ input `user::zlw2, project::projectId_2, resource::app2, action::read`, expect `true`, ouput `true`.
+ input `user::zlw2, project::projectId_2, resource::app2, action::anything`, expect `true`, ouput `true`.
+ input `user::zlw2, project::projectId_2, resource::other, action::anything`, expect `false`, ouput `false`


## Scenes 3: User A3 under Tenant B3 has all permissions to all resources

Configure tenant level admin.

```
p, group::projectAdmin_admin3, project::projectId_3, *, *
g, user::zlw3, group::projectAdmin_admin3, project::projectId_3
```

Sample:
+ input `user::zlw3, project::projectId_3, resource::app3, action::read`, expect `true`, ouput `true`;
+ input `user::zlw3, project::projectId_3, resource::app3, action::anything`, expect `true`, ouput `true`;
+ input `user::zlw3, project::projectId_3, resource::anything, action::anything`, expect `true`, ouput `true`;
+ input `user::zlw3, project::other, resource::app3, action::read`, expect `false`, ouput `false`;

## Scenes 4:  User A4 has all permissions to all resources in all tenants.

Cofigure  platform level admin.

```
p, Global, project::project_4, resource::app4, *
g2, user::zlw4, Global
```

Sample:

+ input user::zlw4, project::project_4, resource::app4, action::read, expect true, output true;
+ input user::zlw4, project::project_4, resource::app4, action::anything, expect true, output true;
+ input user::zlw4, project::project_4, resource::anything, action::anything, expect false, but output true;
+ input user::zlw4, project::other, resource::anything, action::anything, except false, but output true;

**Comment by hsluoyz** [comment]
@JalinWang

**Comment by JalinWang** [comment]
@zhulinwei Could you please add some description and title for easier search if others encounter the such issue?

**Comment by JalinWang** [comment]
`KeyMatch2` will interpret anything proceeded with `:` as a pattern. [ref](https://casbin.io/docs/function)
![image](https://user-images.githubusercontent.com/20621784/187681493-de3575e7-0ca1-442e-a65e-8fb66174a391.png)

You can change it to `keyMatch(r.obj, p.obj)` or  `r.obj == p.obj`

**Comment by zhulinwei** [comment]
> `KeyMatch2` will interpret anything proceeded with `:` as a pattern. [ref](https://casbin.io/docs/function) ![image](https://user-images.githubusercontent.com/20621784/187681493-de3575e7-0ca1-442e-a65e-8fb66174a391.png)
> 
> You can change it to `keyMatch(r.obj, p.obj)` or `r.obj == p.obj`

@JalinWang  Thanks, but it don't work. 

Whether  I use `keyMatch(r.obj, p.obj)` or `r.obj == p.obj || p.obj == "*"`：

Change 1:
```
m = (g(r.sub, p.sub, r.dom) || g2(r.sub, "Global")) && keyMatch(r.obj, p.obj) && (r.act == p.act || p.act == "*")
```

Change 2:
```
m = (g(r.sub, p.sub, r.dom) || g2(r.sub, "Global")) && (r.obj == p.obj || p.obj == "*") && (r.act == p.act || p.act == "*")
```

**Comment by zhulinwei** [comment]
@hsluoyz Can I use single casbin model to support multi-tenancy users and global users? 

Or it's should use different casbin model to deal with multi-tenancy users and global users?

**Comment by zhulinwei** [comment]
> 



> @zhulinwei yes
> 
> @JalinWang

**Comment by zhulinwei** [comment]
> @zhulinwei yes
> 
> @JalinWang

@hsluoyz Sorry, I don't understand what `yes` stands for.

 It's mean that I can use single casbin model to support multi-tenancy users and global users? Or I should use different casbin model to deal with multi-tenancy users and global users?

**Comment by hsluoyz** [comment]
@zhulinwei the former

Let @JalinWang explain that for you

**Comment by JalinWang** [comment]
> > `KeyMatch2` will interpret anything proceeded with `:` as a pattern. [ref](https://casbin.io/docs/function) ![image](https://user-images.githubusercontent.com/20621784/187681493-de3575e7-0ca1-442e-a65e-8fb66174a391.png)
> > You can change it to `keyMatch(r.obj, p.obj)` or `r.obj == p.obj`
> 
> @JalinWang Thanks, but it don't work.
> 
> Whether I use `keyMatch(r.obj, p.obj)` or `r.obj == p.obj || p.obj == "*"`：
> 
> Change 1:
> 
> ```
> m = (g(r.sub, p.sub, r.dom) || g2(r.sub, "Global")) && keyMatch(r.obj, p.obj) && (r.act == p.act || p.act == "*")
> ```
> 
> Change 2:
> 
> ```
> m = (g(r.sub, p.sub, r.dom) || g2(r.sub, "Global")) && (r.obj == p.obj || p.obj == "*") && (r.act == p.act || p.act == "*")
> ```

@zhulinwei My test code:
```go

func TestCustomized(t *testing.T) {
	text :=
		`
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g(r.sub, p.sub, r.dom) || g2(r.sub, "Global")) && r.obj == p.obj && (r.act == p.act || p.act == "*")
`
	m, _ := model.NewModelFromString(text)
	// The above is the same as:
	// m := NewModel()
	// m.LoadModelFromText(text)

	e, _ := NewEnforcer(m)

	_, _ = e.AddNamedGroupingPolicy("g2", "user::zlw4", "Global")
	_, _ = e.AddPolicy("Global", "project::project_4", "resource::app4", "*")

	if myRes, _ := e.Enforce("user::zlw4", "project::project_4", "resource::anything",
		"action::anything"); myRes != false {
		t.Errorf("Enforce should return false")
	}

}
```
![image](https://user-images.githubusercontent.com/20621784/187843976-ce620618-d09e-4304-b17d-5e124e5b047f.png)

KeyMatch also works:
![image](https://user-images.githubusercontent.com/20621784/187844093-fff87e99-3cff-430c-950a-9072e74e516f.png)

**Comment by JalinWang** [comment]
> > @zhulinwei yes
> > @JalinWang
> 
> @hsluoyz Sorry, I don't understand what `yes` stands for.
> 
> It's mean that I can use single casbin model to support multi-tenancy users and global users? Or I should use different casbin model to deal with multi-tenancy users and global users?

What do you mean about a `global` user?

1. If you mean something like `admin`, you can define one
2. If you mean something across all domains, you can use a pattern like `"*"` and `e.AddNamedDomainMatchingFunc("g","KeyMatch",util.KeyMatch)` for domain matching. [ref](https://casbin.io/docs/rbac-with-pattern)

**Comment by zhulinwei** [comment]
> 

Thanks very much, I want global user can across all domains, when I use `e.AddNamedDomainMatchingFunc("g","KeyMatch",util.KeyMatch)`, it work!!!
