### ISSUE TITLE
WatcherEx Callback Loop

### ISSUE THREAD

**Issue by Shivansh-yadav13** [casbin/casbin#1092]
Im working on watcherEx for node-casbin, and for testing we created a callback function for updating other enforcer instances for 'addPolicy'.
In the callback function we used 'addPolicyInternal'.
The issue is addPolicyInternal calls the watcherEx callback function and so it will become a loop

proposed solution-
we can maybe call watcherEx callback function in 'addPolicy' and not in 'addPolicyInternal'

same for all other methods

**Comment by JalinWang** [comment]
You are right. Sorry for stalling on https://github.com/casbin/casbin/issues/999 for a while, I'm gonna resume.

**Comment by Shivansh-yadav13** [comment]
@nodece should we make these changes in node-casbin & casbin-core?

**Comment by nodece** [comment]
`addPolicyInternal` means an internal method, do we have a better name?

**Comment by nodece** [comment]
> @nodece should we make these changes in node-casbin & casbin-core?

Yes, you can make a PR to node-casbin.
