### ISSUE TITLE
[Bug] WatcherUpdatable interface needs more params

### ISSUE THREAD

**Issue by RainshawGao** [casbin/casbin#1098]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
now the WathcerUpdatable defines is
```go
// WatcherUpdatable is the strengthen for Casbin watchers.
type WatcherUpdatable interface {
	Watcher
	// UpdateForUpdatePolicy calls the update callback of other instances to synchronize their policy.
	// It is called after Enforcer.UpdatePolicy()
	UpdateForUpdatePolicy(oldRule, newRule []string) error
	// UpdateForUpdatePolicies calls the update callback of other instances to synchronize their policy.
	// It is called after Enforcer.UpdatePolicies()
	UpdateForUpdatePolicies(oldRules, newRules [][]string) error
}
```
but UpdatableAdapter needs more params: sec and ptype.
```go
// UpdatableAdapter is the interface for Casbin adapters with add update policy function.
type UpdatableAdapter interface {
	Adapter
	// UpdatePolicy updates a policy rule from storage.
	// This is part of the Auto-Save feature.
	UpdatePolicy(sec string, ptype string, oldRule, newPolicy []string) error
	// UpdatePolicies updates some policy rules to storage, like db, redis.
	UpdatePolicies(sec string, ptype string, oldRules, newRules [][]string) error
	// UpdateFilteredPolicies deletes old rules and adds new rules.
	UpdateFilteredPolicies(sec string, ptype string, newPolicies [][]string, fieldIndex int, fieldValues ...string) ([][]string, error)
}
```
the management api also needs these params:
```
type IEnforcer interface {
        ...
	SelfUpdatePolicy(sec string, ptype string, oldRule, newRule []string) (bool, error)
	SelfUpdatePolicies(sec string, ptype string, oldRules, newRules [][]string) (bool, error)
}
```

Should we add the params? I searched around and did not find a watcher repo already implemented this interface, so we may just add the params. If yes, I'd like to submit a pr

**Comment by hsluoyz** [comment]
@JalinWang 

/cc @tangyang9464

**Comment by JalinWang** [comment]
uhh, I think it's definitely a bug and should be fixed. We need to specify whether `p` or `p2` is updated.

We have no updatable watcher to fix. However, we need to fix it across four repositories.
https://github.com/search?p=2&q=org%3Acasbin+UpdateForUpdatePolicy&type=Code
Should we go? @tangyang9464

**Comment by hsluoyz** [comment]
@JalinWang It should be `UpdatableWatcher` instead of `WatcherUpdatable`. We can just define a new `UpdatableWatcher` interface with new APIs. Remove the old interface.

BTW, here are typos, it should be rule instead of policy. Plz fix them

![image](https://user-images.githubusercontent.com/3787410/188658852-7caa0d86-dd5a-4a6b-b59f-9d5007bbc80a.png)

**Comment by RainshawGao** [comment]
@hsluoyz  I did not write c++ and lua 😭
