### ISSUE TITLE
Adding wildcard for all users in a role

### ISSUE THREAD

**Issue by sujatapatnaik52** [casbin/casbin#1099]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Hi, I am trying to use `*` for applying all the policies of a specific role to all users. For that, I updated the `rbac_policy.csv` from examples directory to the following and using the following model.

**Your model:**

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, alice, data1, read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write

g, *, data2_admin
```

**Your request(s):**
I wrote up a basic test in `model_test.go` something like below:
```
func TestMatchModel(t *testing.T) {
	e, _ := NewEnforcer("examples/rbac_model.conf", "examples/rbac_policy.csv")
	e.AddNamedMatchingFunc("g", "keyMatch2", util.KeyMatch2)

	testEnforce(t, e, "a", "data2", "read", true)
}
```
It works as expected but I have seen `KeyMatch2` being used in the examples a bit differently like for the urls. I tried to do something similar to what is being done in the `rbac_domain_with_pattern` example. I am still not clear if this is the right way to do it. If it is then how does it work?

Thank you.

**Comment by JalinWang** [comment]
> It works as expected but I have seen `KeyMatch2` being used in the examples a bit differently like for the urls. I tried to do something similar to what is being done in the `rbac_domain_with_pattern` example. I am still not clear if this is the right way to do it. If it is then how does it work?
@sujatapatnaik52 Sorry but I don't understand what you mean. What's the **DIFFERENCE** you mentioned?

> Hi, I am trying to use `*` for applying all the policies of a specific role to all users.

For your scenario, I think your model & policy is ok. But it could be simpler:
```
p, alice, data1, read
p, bob, data2, write
p, *, data2, read
p, *, data2, write
```
```go
e.AddNamedMatchingFunc("g", "keyMatch", util.KeyMatch)
```

**Comment by sujatapatnaik52** [comment]
> Sorry but I don't understand what you mean. What's the DIFFERENCE you mentioned?

Like in this example - https://github.com/casbin/casbin/blob/master/examples/keymatch2_model.conf, it is used in the matcher not for the subject but for the object and the example used is urls. Just wanted to know how these functions work for my example.

**Comment by JalinWang** [comment]
[Doc for built-in functions](https://casbin.io/docs/function)
All the `keyMatch*` function has two parameters, e.g., `keyMatch(url, pattern)`. You can pass anything to them such as `p.sub` and `p.obj`. Different functions check different patterns. Take `keyMatch` which only supports `*` as an example.
`keyMatch(`/proj/resource1`, `/proj/*`)` : `*` will match `resource1` and the result is `true`.
`keyMatch(`/pr/resource1`, `/proj/*`)` : though `*` will match `resource1`, `pr` doesn't match `proj`. The result is `false`.
