### ISSUE TITLE
golang csv export error

### ISSUE THREAD

**Issue by cute-angelia** [casbin/casbin#110]
golang export => 

```
p,12,3
```

but adapter.go is 

```
p, 12, 3
```

![image](https://user-images.githubusercontent.com/26561606/42560255-d1212cc6-8528-11e8-84d4-77cf82e987b4.png)

**Comment by hsluoyz** [comment]
What do you mean by ``golang export``?

**Comment by wuxiandashu** [comment]
panic

**Comment by hsluoyz** [comment]
I can't understand your question. For the grammar of policy rules, please use ``p, 12, 3`` instead of ``p,12,3``.

**Comment by hsluoyz** [comment]
Suppose it is fixed.
