### ISSUE TITLE
[Bug] concurrent data race

### ISSUE THREAD

**Issue by Rainshaw** [casbin/casbin#1101]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
As described in #421, we could do the following change to ensure concurrent requests are deal in correct way.

If user set a watcher, when call add/remove policy/policies api, we should only write it back with the persist adapter, and publish a message with the watcher, we should not modify our model in memory. all of the modification of the model in memory should be hold by the watcher. 

A watcher should do two things, publish the message, and the other thing is to deal with the messages received in sequence.

But this would bring another question: how can a watcher ensure the messages received are in right sequence. The message published by the watchers may be delayed for the poor connection or something else. I think this is the duty of watcher, it should add timestamps in the message and do the things which sort the messages received by the timestamps or anything else.

So in this way, if a user call add/remove policy api, it only checks whether the requests are persisted by the adapter, if not, the user's request would fail, otherwise, it would succeed.

Any idea about this?

**Comment by JalinWang** [comment]
It sounds like a dispatcher that relies on RAFT to keep consistency across instances. https://casbin.io/docs/dispatchers

> I think this is the duty of watcher, it should add timestamps in the message and do the things which sort the messages received by the timestamps or anything else.

I don't think this method solves the out-of-sequence problem which is indeed a strong-consistency scenario, involving delay, message loss, retry strategy, node failure, and so on.😫 
The watcher is pretty much like UDP, a best-effort delivery service.

**Comment by RainshawGao** [comment]
the raft dispatcher is making a stateless pod to a stateful pod, the better solution should use a vote alg, where there is no master node
