### ISSUE TITLE
[Question] How can I access the role name in the matcher

### ISSUE THREAD

**Issue by xorduna** [casbin/casbin#1104]
First of all I would like to thank the community for such an amazing library!!!

I would like to give all permissions if a user belongs to a role named "superadmin". I would like to check the name of the role in the matcher, but I tried many options without any sucess (p.role, p.sub.role, ...)

How can I access the role name in the matcher?

I tried to find an example also in the documenation or the source code, with the same result.

**My model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g(r.sub, p.sub) && r.obj == p.obj && (r.act == p.act || p.act == "write")) || p.sub.role == "superadmin"
```

**My policy:**

```
p, client, tapatapa, read
p, tejada, tapatapa, write
p, reactiva, circutor, write
p, auleda, circutor, read
p, superadmin, tapatapa, write

g, support, superadmin
```

**My request(s):**

```
support, circutor, read ---> false (expected: true)
```

Thanks

**Comment by hsluoyz** [comment]
@JalinWang

**Comment by JalinWang** [comment]
Why don't you change your policies to:
```
p, superadmin, *, *

p, client, tapatapa, read
p, tejada, tapatapa, write
p, reactiva, circutor, write
p, auleda, circutor, read

g, support, superadmin
```
and model to :
```
[matchers]
m = g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && keyMatch(r.act, p.act)
```
?
[ref](https://casbin.io/docs/function)

**Comment by xorduna** [comment]
Wow!

Thats true! Thank you! That might work!

Xavi

-----------------------------
http://www.alcim.net
