### ISSUE TITLE
Call `UpdateForAddPolicies()` and `UpdateForRemovePolicies()`

### ISSUE THREAD

**Issue by Shivansh-yadav13** [casbin/casbin#1105]
Can we call the `UpdateForAddPolicies()` and `UpdateForRemovePolicies()` methods in updateInternalPolicy as watcher method.

_Originally posted by @nodece in https://github.com/casbin/node-casbin/pull/384#discussion_r967673440_

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 see Golang Casbin
