### ISSUE TITLE
[Feature]Return error in method LoadPolicyArray

### ISSUE THREAD

**Issue by eah1** [casbin/casbin#1106]
Hello, we found a slight problem working with casbin. Our problem was the following: 

We wanted to load the list of policies we had on our database, We called loadPolicy and expected the policies to be loaded. The current ones we had were not recognized but the new ones added after startup worked. We found out the reason why this failed is that we had an extra parameter on the policy_definition file, once we fixed it, everything worked fine. 

The problem here is that we had to debug the casbin library to find the problem because no error was returned. We debugged until the LoadPolicyArray function on casbin > v2 > persist > adapter.go > LoadPolicyArray 

```go
func LoadPolicyArray(rule []string, m model.Model) { 
    key := rule[0]  
    sec := key[:1] 

    ok, err := m.HasPolicyEx(sec, key, rule[1:]) 
    if err != nil { 
       return 
    } 

    if ok { 
       return 
    } 

    m.AddPolicy(sec, key, rule[1:]) 
} 
```

The process failed when calling HasPolicyEx but as it is right now, it returns a silent error, if this error was returned or some sort of boolean indicating if something went wrong we would have been able to find the problem much sooner. Having something like this could be a nice addition.

**Comment by JalinWang** [comment]
hi~ Are you finding something like https://github.com/casbin/casbin/pull/1085?
