### ISSUE TITLE
[Bug] unable to extend Casbin with custom role manager

### ISSUE THREAD

**Issue by ovargasmahisoft** [casbin/casbin#1107]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**

The are several parts in the code where instead of calling the objects through the interface the object is being cast to a specific implementation.

Places where you can find the issue:

* https://github.com/casbin/casbin/blob/master/rbac_api.go#L311
* https://github.com/casbin/casbin/blob/master/rbac_api_test.go#L310
* https://github.com/casbin/casbin/blob/master/enforcer.go#L742
* https://github.com/casbin/casbin/blob/master/enforcer.go#L751

**To Reproduce**
1. Create an enforcer
2. Set the role manager with your custom implementation
3. Execute any function that goes through any of the above like `GetNamedImplicitPermissionsForUser` 
4. See error: `interface conversion: rbac.RoleManager is *autz.RoleManager, not *defaultrolemanager.RoleManager`

**Expected behavior**

The function should be called through the interface

**Desktop (please complete the following information):**
 - OS: `macOS 12.6`
 - Casbin Version `github.com/casbin/casbin/v2 v2.54.0`

**Comment by JalinWang** [comment]
Thanks! Disentanglement definitely should be done. I'll try to make the interface more general.
