### ISSUE TITLE
go 1.10 unsupport *sysn.map bug mang panic  piont menory

### ISSUE THREAD

**Issue by wuxiandashu** [casbin/casbin#111]
go 1.10 unsupport *sysn.map bug mang panic  piont menory

**Comment by hsluoyz** [comment]
Can you be more specific? I have successfully run all the tests under Go 1.10.3. You can also see it in our Travis CI: https://travis-ci.org/casbin/casbin. Can you describe the bug and provide the reproduce steps?

**Comment by hsluoyz** [comment]
Closed as stale.
