### ISSUE TITLE
[Question] - Adding domain to RBAC hierarchal model doesn't work (when same model without domain does work) 

### ISSUE THREAD

**Issue by elenasch** [casbin/casbin#1110]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

I am using the RBAC with hierarchy model, and seems to work nicely with multiple levels of nested roles. However, if I add a `domain` to my model and policies, only the first level role works OK, but parent roles do not get access to their children's data. 
 
The reason I need to add a `domain` is to allow for partial policy loads in a multi tenant policies dataset.

**WORKING models and policy (no `domain` added)** 
**--------------------------------------------------**

**model.conf**
```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 =_, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && r.act == p.act
```
**policy**
```
p, editor, viewer, view
p, company_admins, editor, view
p, staff_admins, company_admins, view

p, staff_admins, audit, view

g, bob, editor
g, alice, staff_admins
g, staff_admins, editor
g, company_admins, staff_admins

g2, document1, viewer
g2, document2, viewer
```
**request**
```
alice, document1, view --> true
alice, document2, view --> true
bob, document2, view --> true
bob, audit, view --> false
alice, audit, view--> true
```

**NON-WORKING models and policy (with `domain` added)** 
**--------------------------------------------------**

**model.conf**
```ini
[request_definition]
r = dom, sub, obj, act

[policy_definition]
p = dom, sub, obj, act

[role_definition]
g = _, _, _
g2 =_, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(p.dom, r.sub, p.sub) && g2(p.dom, r.obj, p.obj) && r.act == p.act && r.dom == p.dom
```
**policy**
```
p, dom1, editor, viewer, view
p, dom1, company_admins, editor, view
p, dom1, staff_admins, company_admins, view

p, dom1, staff_admins, audit, view

g, dom1, bob, editor
g, dom1, alice, staff_admins
g, dom1, staff_admins, editor
g, dom1, company_admins, staff_admins

g2, dom1, document1, viewer
g2, dom1, document2, viewer
```
**request**
```
alice, document1, view --> false
alice, document2, view --> false
bob, document2, view --> true
bob, audit, view --> false
alice, audit, view--> false
```

**Your request(s):**

What am I doing wrong here, or is there a better way to address this.

**Comment by hsluoyz** [comment]
@JalinWang 

/cc @tangyang9464

**Comment by JalinWang** [comment]
> ```ini
> m = g(p.dom, r.sub, p.sub) && g2(p.dom, r.obj, p.obj) && r.act == p.act && r.dom == p.dom
> ```

You need to change `g(dom,*,*)` to `g(r.sub, p.sub, r.dom)` [ref](https://casbin.io/docs/rbac-with-domains)

**Comment by elenasch** [comment]
Thank you! That worked. 
The issue was that I changed the location of `dom` and didn't add the `e.SetFieldIndex("p", constant.DomainIndex, 0) ` call as specified in docs. One I updated the location of `dom` in the model and request definitions that worked. 

A follow up question - doesn't look like there is an API to set the field index in NodeJS implementation. Is there a way to do that or this is not supported at all in NodeJS ?

**Comment by JalinWang** [comment]
> A follow up question - doesn't look like there is an API to set the field index in NodeJS implementation. Is there a way to do that or this is not supported at all in NodeJS ?

Probably. This API is introduced very recently. You can open an issue there https://github.com/casbin/node-casbin/issues
