### ISSUE TITLE
Why does casbin query the table structure and generate a large number of slow logs？

### ISSUE THREAD

**Issue by jhansin-zhang** [casbin/casbin#1112]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)
![image](https://user-images.githubusercontent.com/52953730/191654320-bdcb9148-0fa2-4e1a-a0ce-8157a04cdd6c.png)
How should I optimize it
------

**What's your scenario? What do you want to achieve?**
Your answer here

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, alice, data1, read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write

g, alice, data2_admin
```

**Your request(s):**

```
alice, data2, read ---> false (expected: true)
```

**Comment by JalinWang** [comment]
![image](https://user-images.githubusercontent.com/20621784/191684437-de6ac219-4ea9-49f3-83e6-a2dfd037895f.png)

It is a migration SQL generated by `gorm-adapter` and will appear when you create this adapter.
If you are affected by it, you can turn off `AutoMigrate`. Plz refer to: https://github.com/casbin/gorm-adapter#turn-off-automigrate

**Comment by jhansin-zhang** [comment]
Thanks
