### ISSUE TITLE
distributed system,  multiple casbin instance cannot update successfully because of unique_index in postgresql

### ISSUE THREAD

**Issue by zhangmingwalker1633** [casbin/casbin#1118]
**Describe the bug**
A clear and concise description of what the bug is: 
 I have four casbin instances in my distributed system, when one casbin instance update, other casbin instances receive notify message like this, [ {"Method":"UpdateForAddPolicy","ID":"127.0.0.1_T1_main_1579372304080195584", "Sec":"p","Ptype":"p","Params":["T1/role::6666","T1/2","T1/api::test2","rpc"]}] , becase one casbin already insert casbin rule like[INSERT INTO "T1_auth"."casbin_rule"("ptype", "v0", "v1", "v2", "v3", "v4", "v5") VALUES 
('p', 'T1/role::6666', 'T1/1', 'T1/object::admin_user_info/delete_time', 'update', NULL, NULL);], 
other casbin instance call function AddPolicy fail because I have set unique_index in my postgresql , like[CREATE UNIQUE INDEX unique_index ON "T1_auth".casbin_rule USING btree (ptype, v0, v1, v2, v3, v4, v5)], so other casbin instance cannot update Enforcer.model sucessfully.

**To Reproduce**

**Expected behavior**
I wonder if we can update code like this to avoid casbin-adapter executor fail:
<img width="1061" alt="企业微信截图_5bcfcbe9-ea4c-4c77-8b8b-0c5187f9c841" src="https://user-images.githubusercontent.com/33444081/195309422-657658b2-6e30-4fdc-a24c-7f9d5ea2c032.png">

**Screenshots**

**Additional context**

**Comment by hsluoyz** [comment]
Closed as stale
