### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by xiezf77** [casbin/casbin#1120]
Error: Too many arguments to parameter call: got 1 arguments, expected 0

Here is my code:  golang v1.19.2
package perm

import (
	"fmt"
	"testing"

	"github.com/casbin/casbin/v2"
	"github.com/casbin/casbin/v2/model"
)

type Subject struct {
	Name string
	Hour int
}

type Object struct {
	Owner string
}

func (sub *Subject) Validate() bool {
	return true
}

func TestT2(t *testing.T) {
	text := `
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub.Validate() == true && r.sub.Name == r.obj.Owner
`
	m, _ := model.NewModelFromString(text)
	e, err := casbin.NewEnforcer(m)
	fmt.Println("err: ", err)

	sub := &Subject{Name: "dajun", Hour: 20}
	obj := &Object{Owner: "dajun"}
	ok, err := e.Enforce(sub, obj, "read")
	fmt.Println(ok, err)
}

Got: 
err:  <nil>
false Method call failed - 'r_sub.Validate': Too many arguments to parameter call: got 1 arguments, expected 0

Is there some wrong of my code

**Comment by hsluoyz** [comment]
@xiezf77 your defined `Validate()` can not be supported like this. See how to correctly add a custom function: https://casbin.io/docs/function#how-to-add-a-customized-function

**Comment by xiezf77** [comment]
@hsluoyz thank you
