### ISSUE TITLE
[Question] RBAC with domain with domain inheritance

### ISSUE THREAD

**Issue by KamaKAzii** [casbin/casbin#1123]
**What's your scenario? What do you want to achieve?**
I've had a look around but I can't seem to find an answer to this question (just for the record, I'm new and investigating using Casbin for our company) but it is it possible to use RBAC with domains/tenants where domains are grouped/have inheritance as well?

**Your model:**

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && g2(r.dom, p.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, role:manager, class:1, tasks, write
p, role:viewer, class:1, tasks, read
g, role:manager, role:viewer, class:1
g2, school:1, class:1     <--- something like this? 
g, user:1, role:manager, school:1
```

**Your request(s):**

```
user:1, class:1, tasks, write ---> false (expected: true)
```

**Comment by imp2002** [comment]
There is some problem with your `[matchers]` expression.

I roughly understood your needs and re-wrote the `[matchers]` expression. The result is as follows.

You can try write your expression that meets your requirements at https://casbin.io/zh/editor

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, p.dom) && g2(r.dom, p.dom) && r.obj == p.obj && r.act == p.act
```

```csv
p, role:manager, school:1, tasks, write
g, user:1, role:manager, school:1
g, user:2, role:manager, school:1
g2, class:1, school:1
```

```csv
user:1, class:1, tasks, write ---> true
user:2, class:1, tasks, write ---> true
```


![image](https://user-images.githubusercontent.com/41513919/200181997-88a41d4f-5cea-42c0-b91a-90fc63e1f5ae.png)

**Comment by hsluoyz** [comment]
Closed as resolved
