### ISSUE TITLE
[Question] What things does UpdateFilteredPolicies do?

### ISSUE THREAD

**Issue by shengjh** [casbin/casbin#1124]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
I want to `Update`(Rewrite, such as  add policies after delete) policies by filter,  so i tried `UpdateFilteredPolicies`, but it not work. The question is  how `UpdateFilteredPolicies` works?

**Your model:**

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, dom1, alice, data1, read
```

**Your request(s):**

```
newPolicies := [][]string{{"alice", "dom1", "data1", "write"}}
UpdateFilteredPolicies(newPolicies, 0, "alice", "dom1", "data1")
Now alice can both read/write data1 -> expect alice can only write data1
```

**Comment by shengjh** [comment]
@hsluoyz. thanks for  so quick reply.
I have see the test case. But in the test, filterdValues contains action.  
I want to remove all policies of a object, then add some new policies. I can do it by using `RemoveFilteredPolicies` and `AddPolicies`.
I have see the doc, seems `UpdateFiltered`  can aslo do it. But in my test, Like `UpdateFilteredPolicies(newPolicies, sub, obj)`, it didn't remove the old policies.

**Comment by hsluoyz** [comment]
filterdValues can contain empty element.

**Comment by shengjh** [comment]
Do you mean `UpdateFilteredPolicies(newPolicies, sub, obj, "")`?   I tried but it not work either, old policies are not removed.

**Comment by shengjh** [comment]
I simply debugged the cabin source code of UpdateFilteredPolicies. In my test, it removed the old policies data in my database, but not erase policies in the memory model. 
`RemoveFilteredPolicies` works well because it iter over a policy slice to remove it, `UpdateFilteredPolicies ` use function `RemovePoliciesWithEffected`, which quick search old policies from a policyMap.  If old policies is not in the policyMap, so it is nor erase. 
Is it a bug?

**Comment by hsluoyz** [comment]
@Xhy-5000 @imp2002

**Comment by shengjh** [comment]
@hsluoyz Shall we reopen this issue to trace?

**Comment by hsluoyz** [comment]
@shengjh plz create a new issue
