### ISSUE TITLE
How to get all policy but only contain object and action without subject

### ISSUE THREAD

**Issue by hs-dev-web** [casbin/casbin#1125]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

Casbin has method to get all policy by running this code:

`Enforcer.GetPolicy()`

the return data would be something like this:

```
[
    [
      "superadmin", // subject
      "user",       // object
      "create"      // action
    ],
    [
      "superadmin",
      "user",
      "read"
    ],
    [
      "admin",
      "user",
      "read"
    ]
]
```

is there any method to get data without the subject so the data I get would be something like this:

```
[
    [
      "user",       // object
      "create"      // action
    ],
    [
      "user",
      "read"
    ],
]
```

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, superadmin, user, create
p, superadmin, user, read
p, admin, user, read

```

**Your request(s):**

is there any method to get data without the subject so the data I get would be something like this:

```
[
    [
      "user",       // object
      "create"      // action
    ],
    [
      "user",
      "read"
    ],
]
```

**Comment by hsluoyz** [comment]
@hs-dev-web I don't think Casbin has such API. You need to filter the result and remove dups by yourself
