### ISSUE TITLE
RoleManager interface should be context-aware

### ISSUE THREAD

**Issue by checkaayush** [casbin/casbin#1126]
**Is your feature request related to a problem? Please describe.**
`RoleManager` interface methods are missing context.Context argument, which is useful for handling errors (like timeouts) while interacting with external systems (Identity Providers). 

**Describe the solution you'd like**
2 possible options:
- Create a new interface `RoleManagerWithContext` which has the same methods as `RoleManager` but with context.Context as the first argument.
- Update the existing interface in the next major version to include context.Context as first argument to methods

**Describe alternatives you've considered**
Creating and passing around a context with timeout with implementation functions works, but isn't idiomatic and elegant.

**Additional context**
None

**Comment by hsluoyz** [comment]
@checkaayush the `RoleManagerWithContext()` option looks good. Can you make a PR to add it?
