### ISSUE TITLE
[Feature] add context for 

### ISSUE THREAD

**Issue by GerryLon** [casbin/casbin#1128]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------
![image](https://user-images.githubusercontent.com/25873611/200822287-f92927ef-2876-47c2-9e0d-989ddbc6f72e.png)

BatchAdapter's methods shoud have context as the first param.

**Comment by GerryLon** [comment]
> @GerryLon can you explain more?

for example:
```go
type BatchAdapter interface {
  AddPolicies(ctx context.Context, sec string, ptype string, rules [][]string) error
  ...
}
```

**Comment by hsluoyz** [comment]
@GerryLon currently it's not that useful for now. You can define a new interface by yourself.
