### ISSUE TITLE
Watcher on a file based policies

### ISSUE THREAD

**Issue by sujatapatnaik52** [casbin/casbin#1134]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

I have two questions:

1. I have file based policies. When I start the enforcer I use the redis adapter to load any existing policies. After this, I update the model with the file's policies. There are chances that this file may get updated in between. I read some parts of casbin watcher. Is the watcher concept applicable only for whatever is available in this link - https://casbin.org/docs/en/watchers? Can I have a file based watcher which will watch the file and update the enforcer? I am opting towards writing a watcher of my own. Just wanted to check if it is possible with casbin or not.
2. There is `startAutoLoadPolicy` which does periodically update the enforcer. Why I do a need a watcher then?

**Comment by imp2002** [comment]
> 1. Just wanted to check if it is possible with casbin or not.

Yes, you can implement it yourself, when there are many instance of Enforce with though adapter of file not db.

> 2. Why I do a need a watcher then

the `startAutoLoadPolicy(d time.Duration)` It's auto execute `loadPolicy()` in every interval. Such as execute for every 5 seconds. It's a waste of resources when there no need to update and it lacks timeliness when it needs to be updated to be consistence.

But `watcher` no the problem, it only update when need and do it timely.
