### ISSUE TITLE
gorm.DefaultTableNameHandler is not suitable for casbin

### ISSUE THREAD

**Issue by stevemilk** [casbin/casbin#114]
When I use gorm-adapter's DefaultTableNameHandler to add a prefix name to each table, casbin's default table "casbin_rule" cannot be used to remove a policy. 
That's because casbin_rule has no primary key, and policy's remove action is different from add action . I tried to init gorm-adapter in front of DefaultTableNameHandler, it still not woked.
Finially, I change casbin's default table name "casbin_rule" to "$prefix_casbin_rule", and make a judgement in DefaultTableNameHandler : if table name is equal to "$prefix_casbin_rule", prefix name will not be added .
If you any better solution , welcome to reply to me~

**Comment by hsluoyz** [comment]
If this is a gorm-adapter specific issue, please propose the issue here: https://github.com/casbin/gorm-adapter/issues
