### ISSUE TITLE
[Question] policy_definition add new option

### ISSUE THREAD

**Issue by longhao54** [casbin/casbin#1140]
[request_definition]
r = sub, dom, obj, act, clu

[policy_definition]
p = sub, dom, obj, act, eft, tp, clu

[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = (my_func(p.sub, p.dom, p.obj, p.act, p.eft, p.tp) && (p.tp == 't2' && g2(r.sub, p.sub) && ((r.obj == p.obj) || keyMatch2(r.obj, p.obj)) && r.act == p.act ) || ((p.tp == 't1') && g(r.sub, p.sub) && (r.sub == p.sub && keyMatch2(r.obj, p.obj) && r.act == p.act)))

Want add new option  "clu"  in policy_definition

This is casbin_rule table
<img width="583" alt="image" src="https://user-images.githubusercontent.com/17335245/203916221-89ef28ee-5574-48cc-80dd-9629994dea0c.png">

<img width="642" alt="image" src="https://user-images.githubusercontent.com/17335245/203915957-21369db1-5c2e-414f-be30-95453d827bea.png">

Print Result
map[act: dom: eft: obj: sub: tp:]

**Comment by hsluoyz** [comment]
@Xhy-5000

**Comment by longhao54** [comment]
I edited gorm-adapter/adapter.go  CasbinRule struct added V6 and other function. It seems like the problem is solved

**Comment by longhao54** [comment]
Does anyone have better solution to this?

**Comment by hsluoyz** [comment]
@longhao54 you can fork this project to add v6, it's the recommended solution
