### ISSUE TITLE
[Question] - How to implement hierarchy based domain role model

### ISSUE THREAD

**Issue by sujit-baniya** [casbin/casbin#1145]
I am trying to implement following policy

```csv
p, super_admin, *, data1, read
p, super_admin, *, data2, read
p, super_admin, *, data3, read
p, admin, domain1.com, data1, read
p, admin, domain2.com, /blog/1, GET
p, admin, domain2.com, data2, read
p, admin, domain3.com, data3, read

g, sujit, super_admin, *
g, alice, admin, domain1.com
g, bob, admin, domain2.com
g, carol, admin, domain3.com

g2, domain1.com, domain2.com
g2, domain2.com, domain3.com
```

using model

```conf
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && g2(r.dom, p.dom) && \
(regexMatch(r.obj, p.obj) || r.obj == p.obj || keyMatch(r.obj, p.obj)) && \
(regexMatch(r.act, p.act) || r.act == p.act || keyMatch(r.act, p.act))
```

For following request

```
"alice", "domain1.com", "data1", "read" => true, expected true
"alice", "domain1.com", "data2", "read" => true, expected true
"alice", "domain2.com", "data2", "read" => false, expected true
"alice", "domain1.com", "data3", "read" => true, expected true
"alice", "domain1.com", "/blog/1", "GET" => true, expected true
"sujit", "domain1.com", "data1", "read" => false, expected true
```

Anyone please suggest how could I implement the model so that 
1) `g, sujit, super_admin, *` could have access to all domains and `GetDomainsForuser("sujit")` would give me all domains
2) `"alice", "domain2.com", "data2", "read"` return `true` because `alice` is admin on `domain1.com` and `domain1.com` has group with `domain2.com`

**Comment by hsluoyz** [comment]
@imp2002 @maocaicai

**Comment by maocaicai** [comment]
The original route must go to g2. The domain names did not match, so false was returned.
"Machers" can change the "g" and the "g2" matching rules, the change to | |, is originally &&, so you can choose not to g2.
![image](https://user-images.githubusercontent.com/96519760/204732228-bdf81ec3-6aa4-41a6-b24d-46e9f7adf822.png)
=>![image](https://user-images.githubusercontent.com/96519760/204732187-811e79e9-e672-4b6e-adc1-6f1c6b062c4c.png)

**Comment by sujit-baniya** [comment]
@maocaicai Thanks for the response. On initial tests, everything seems to work.

Is there any possibility to get all domains for a user when I use `GetDomainsForuser('sujit')`?
Currently it's just giving me `[*]` instead of all associated domains `[* domain1.com domain2.com domain3.com]`

**Comment by sujit-baniya** [comment]
Also same goes with the roles for user, I wanted to get all roles associated with user.

For e.g. `alice` is `admin` for `domain1.com` and `domain1.com` has `domain2.com`. So `alice` should also be `admin` to `domain2.com` and `enforcer.GetRolesForUserInDomain("alice", "domain2.com")` should have given me `[admin]` but it's empty

**Comment by hsluoyz** [comment]
@imp2002

**Comment by maocaicai** [comment]
> @maocaicai Thanks for the response. On initial tests, everything seems to work.
> 
> Is there any possibility to get all domains for a user when I use `GetDomainsForuser('sujit')`? Currently it's just giving me `[*]` instead of all associated domains `[* domain1.com domain2.com domain3.com]`

You can add a layer of logic yourself and call e.GetAllDomains () to get all domains if the output is "*"

**Comment by maocaicai** [comment]
> Also same goes with the roles for user, I wanted to get all roles associated with user.
> 
> For e.g. `alice` is `admin` for `domain1.com` and `domain1.com` has `domain2.com`. So `alice` should also be `admin` to `domain2.com` and `enforcer.GetRolesForUserInDomain("alice", "domain2.com")` should have given me `[admin]` but it's empty

You can try this api: e.GetImplicitRolesForUser().In contrast to GetRolesForUserInDomain(), this function retrieves indirect roles in addition to direct roles.

**Comment by hsluoyz** [comment]
@sujit-baniya

**Comment by sujit-baniya** [comment]
@maocaicai Thank you for the response. I did check for `GetImplicitRolesForUser()`. It's giving the same data as `GetRolesForUserInDomain()`.

`GetRolesForUser()` for me isn't fetching any data.

I've tried using custom RoleManager. Now most of the test cases (as per my need) works as expected.

**Comment by sujit-baniya** [comment]
I also had created an issue https://github.com/casbin/casbin/issues/1151

**Comment by hsluoyz** [comment]
@sujit-baniya can this issue be closed now?
