### ISSUE TITLE
[Question] How to implement dynamic group naming

### ISSUE THREAD

**Issue by KenanHH** [casbin/casbin#1149]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
I want to have dynamic group naming and define single policy for those groups.

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = (g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && r.act==p.act) 

```

**Your policy:**

```
g, user, group/1/member
p, group/:id/member, /path/:id, GET, allow
```

**Your request(s):**

```
user, /path/1, GET ---> false (want: true)
```

How can I implement this? Is this achievable with g function?

**Comment by hsluoyz** [comment]
@KenanHH see: https://casbin.org/docs/rbac-with-pattern
