### ISSUE TITLE
有没有考虑过增加一些缓存

### ISSUE THREAD

**Issue by maplebeats** [casbin/casbin#115]
整体性能目前测试起来还是很差，没办法加入到一些高性能模块上。
我试着用map做了一个简单的内存缓存，性能会好很多。
如果策略不是变化得很快，判断结果有缓存应该没什么影响吧，而且缓存也可以跟着策略刷新。

**Comment by hsluoyz** [comment]
已经设计了CachedEnforcer，请参考这里的例子使用：https://github.com/casbin/casbin/blob/master/enforcer_cached_test.go

**Comment by maplebeats** [comment]
感谢，我近期会上线测试一下，如果有问题我再提pr
