### ISSUE TITLE
[Question] Implementation of Entity/Resource Roles with row level access

### ISSUE THREAD

**Issue by aksswami** [casbin/casbin#1152]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
We want to implement flexible RBAC Access management which gives us the flexibility to change/enhance the roles in the future. Here is the experimental design we are working on to decide the framework (Casbin or OSO etc.)

- Roles are defined on each resources, example group -> member, admin, org -> member, admin, device_manager etc
- These roles can access particular resource (same as role or other), group_1_member -> group1, read; org_1_admin -> org1, update

<img width="437" alt="CleanShot 2022-12-05 at 10 12 51@2x" src="https://user-images.githubusercontent.com/1496758/205534546-58b83f70-c108-4ac3-9589-e85b7148f3cb.png">

I am able to create above use case if I create policy for each new resource created. But this will make policy size very large. 
  = number of all Resources in different type * per resource roles. 

How can I use casbin pattern matching functionality to reduce this to static policy for roles part. Where I just need to assign these roles to users.

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = keyMatch3(r.sub, p.sub) && keyGet3(r.sub, p.sub, "id") == keyGet3(r.obj, p.obj, "id") && r.act == p.act
```

**Your policy:**

```
# group
p, role::group::{id}::member, group::{id}, read
p, role::group::{id}::admin, group::{id}, update
g, role::group::{id}::admin, role::group::{id}::member

# org
p, role::org::{id}::member, org::{id}, read
p, role::org::{id}::admin, org::{id}, update

g, role::org::{id}::admin, role::org::{id}::member
g, role::org::{id}::member, role::org::{id}::device_manager
g, role::org::{org_id}::member, role::zone::{zone_id}::member
g, role::org::{org_id}::device_manager, role::zone::{zone_id}::device_manager

# zone 
p, role::zone::{id}::member, zone::{id}, read                               
p, role::zone::{id}::device_manager, zone::{id}, create                     
p, role::zone::{id}::device_manager, zone::{id}, update
p, role::zone::{id}::device_manager, zone::{id}, delete     


g, user1, role::org::1::admin
g, user2, role::org::2::member
```

**Your request(s):**

```
user1, org::1, read ---> true 
user2, org::2, update ---> false
user2, org::2, read ---> true
user2, org::1, read ---> false
```

**Comment by hsluoyz** [comment]
Already answered in another issue: https://github.com/casbin/casbin/issues/1154

**Comment by aksswami** [comment]
There are some differences between #1154 and this question. Here I am working on complex dynamic pattern matching as you can see with `org:{org_id}` and `zone:{zone_id}`. 
To solve this, I created simple exmaple as shown in #1154. Let me know if you have any other suggestions on this.
