### ISSUE TITLE
[Question] Dynamic pattern matching for Subject and Object

### ISSUE THREAD

**Issue by aksswami** [casbin/casbin#1154]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
I am trying to implement dynamic role and resource mapping so that I don't have to add each individual object to the policy.
https://editor.casbin.org/#2CSQ4J97P

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = keyMatch3(r.sub, p.sub) && keyGet3(r.obj, p.obj, 'id') == keyGet3(r.sub, p.sub, 'id') &&  r.act == p.act
```

**Your policy:**

```
p, admin:{id}, org:{id}, write
p, member:{id}, org:{id}, read

#p, admin:z:{id}, zone:{id}, write
#p, member:z:{id}, zone:{id}, read

g, admin:{id}, member:{id}
#g2, org:1, zone:1

g, user1, admin:1
g, user2, member:2
```

**Your request(s):**

```
user1, org:1, write ---> false (expected: true)
user2, org:1, read ---> false 
user2 org:2, read ---> false (expected: true)
```

**Comment by hsluoyz** [comment]
@aksswami you should choose `RBAC with pattern` model

![image](https://user-images.githubusercontent.com/3787410/206447038-708aee07-eccc-4ae5-9ef4-0927d6083795.png)

**Comment by aksswami** [comment]
@hsluoyz I have already tried with above suggestion. RBAC with pattern shows example of regex match over action. 
What I am trying to accomplish is to do pattern match over group relationship, subject and object as you can see from above example. 
Here is the attempt as per your suggestion:- https://editor.casbin.org/#FZQGSZMJ2
