### ISSUE TITLE
[Question] Every issue is assigned to @hsluoyz; where is external contribution needed?

### ISSUE THREAD

**Issue by abhi-kr-2100** [casbin/casbin#1155]
I'm want to contribute to Casbin, however, about 99% of all open issues have already been assigned to @hsluoyz. This is true for other Casbin repositories, such as `node-casbin` and `pycasbin`, as well. Some of the issues don't have any replies and have been open for quite some time.

My question is, should I work on such issues or consider them already assigned to someone else?

**Comment by hsluoyz** [comment]
@abhi-kr-2100 the `Assignee` term used in Casbin doesn't mean the one who will make PR to fix the issue. Actually most of the code contributions these days are not made by me. You can view the recently merged PRs. Anyone is welcome to participate in the dicussion of existing issues and offer code contribution via PRs. For now, nearly all existing issues of this repo are not assigned to a specific person.
