### ISSUE TITLE
Suggestion for compined RBAC with ABAC model

### ISSUE THREAD

**Issue by tsoultanopoulos** [casbin/casbin#1156]
hello, i am quite new programmer and i need your help. I need to combine RBAC with ABAC. For the requirements of the application imagine that we have some endpoints that some users with a specific role has access (imagine only the admin can POST an action for a Items). I need to add some granuallity from the items that belongs into groups.So items inherit all permissions from parent group(recursively).The priority is permissions -> group permissions -> global permissions. Also for my model i need every user to has access only to his dashboard page /api/v1/:id. for example user1 has access to api/v1/1 but not to api/v1/2.Is it that possible. Would really appreciate your suggestions , sorry for my bad english.

**Comment by hsluoyz** [comment]
@tsoultanopoulos you can use RBAC model
