### ISSUE TITLE
Matcher line in model conf truncating to 64 characters

### ISSUE THREAD

**Issue by beazizo** [casbin/casbin#116]
I seem to be having a problem with the following model configuration:

```
# Request definition
[request_definition]
r = sub, obj, act

# Policy definition
[policy_definition]
p = sub, obj, act

# Policy effect
[policy_effect]
e = some(where (p.eft == allow))

# Matchers
[matchers]
m = r.sub == p.sub && r.obj == p.obj && r.act == p.act && regexMatch(r.obj, p.obj) && regexMatch(r.act, p.act)

```

The policy file is:

`p, test, .*, .*
`

The Enforce call fails for me no matter what values I have for object or action

Some brief debugging reveals that the model conf line for matcher m gets truncated to this:

`r.sub == p.sub && r.obj == p.obj && r.act == p.act && regexMatch`

Therefore never actuall calls regexMatch function.  Am I doing something wrong?

**Comment by hsluoyz** [comment]
Closed as stale.
