### ISSUE TITLE
[Bug] Slow enforcement with many roles

### ISSUE THREAD

**Issue by sebd71** [casbin/casbin#1161]
**Describe the bug**

With the same number of policies, depending of the number of roles the enforce time may be very very long, 6 seconds demoed in example/test below !
This time depends of the role definition/creation position, fast for first defined roles, slow for last defined roles (in example below: 2499).

```
go test -run ^TestManyRoles$ github.com/casbin/casbin/v2 -v

=== RUN   TestManyRoles
    rbac_api_test.go:598: RESPONSE abu        /projects/1        GET :  true IN: 438.379µs
    rbac_api_test.go:598: RESPONSE abu        /projects/2499     GET :  true IN: 39.005173ms
    rbac_api_test.go:598: RESPONSE jasmine    /projects/1        GET :  true IN: 1.774319ms
    rbac_api_test.go:598: RESPONSE jasmine    /projects/2499     GET :  true IN: 6.164071648s
    rbac_api_test.go:600: More than 100 milliseconds for jasmine /projects/2499 GET : 6.164071648s
    rbac_api_test.go:598: RESPONSE jasmine    /projects/2499     GET :  true IN: 12.164122ms
--- FAIL: TestManyRoles (6.24s)
FAIL
FAIL    github.com/casbin/casbin/v2     6.244s
FAIL
```

**To Reproduce**

Here is the code of a test that can be added for example in `rbac_api_test.go` file to reproduce the problem :

```

const rbac_models = `
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
`

func TestManyRoles(t *testing.T) {

	m, _ := model.NewModelFromString(rbac_models)
	e, _ := NewEnforcer(m, false)

	roles := []string{"admin", "manager", "developer", "tester"}

	// 2500 projects
	for nbPrj := 1; nbPrj < 2500; nbPrj++ {
		// 4 objects and 1 role per object (so 4 roles)
		for _, role := range roles {
			roleDB := fmt.Sprintf("%s_project:%d", role, nbPrj)
			objectDB := fmt.Sprintf("/projects/%d", nbPrj)
			e.AddPolicy(roleDB, objectDB, "GET")
		}
		jasmineRole := fmt.Sprintf("%s_project:%d", roles[1], nbPrj)
		e.AddGroupingPolicy("jasmine", jasmineRole)
	}

	e.AddGroupingPolicy("abu", "manager_project:1")
	e.AddGroupingPolicy("abu", "manager_project:2499")

	// With same number of policies
	// 	User 'abu' has only two roles
	// 	User 'jasmine' has many roles (1 role per policy, here 2500 roles)

	request := func(subject, object, action string) {
		t0 := time.Now()
		resp, _ := e.Enforce(subject, object, action)
		tElapse := time.Since(t0)
		t.Logf("RESPONSE %-10s %s\t %s : %5v IN: %+v", subject, object, action, resp, tElapse)
		if tElapse > time.Millisecond*100 {
			t.Errorf("More than 100 milliseconds for %s %s %s : %+v", subject, object, action, tElapse)
		}
	}

	request("abu", "/projects/1", "GET")        // really fast because only 2 roles in all policies and at the beginning of the casbin_rule table
	request("abu", "/projects/2499", "GET")     // fast because only 2 roles in all policies
	request("jasmine", "/projects/1", "GET")    // really fast at the beginning of the casbin_rule table

	request("jasmine", "/projects/2499", "GET") // slow and fail the only 1st time   <<<< pb here
	request("jasmine", "/projects/2499", "GET") // fast maybe due to internal cache mechanism
	
        // same issue with non-existing roles
 	// request("jasmine", "/projects/999999", "GET") // slow fail the only 1st time   <<<< pb here
	// request("jasmine", "/projects/999999", "GET") // fast maybe due to internal cache mechanism
}
```

**Expected behavior**

Enforce time must be quite constant and independent to the order of role creation even for the 1st enforcement request.

**Comment by sebd71** [comment]
Hello,

i just found that changing the order of expressions in `matchers` definition allows to get back "normal" response time.
Putting     : ` m = r.obj == p.obj && g(r.sub, p.sub) && r.act == p.act `
Instead of: ` m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act `

Here the exact same test (mentioned above) output but with matchers: `m = r.obj == p.obj && g(r.sub, p.sub) && r.act == p.act ` : 

```
go test -run ^TestManyRoles$ github.com/casbin/casbin/v2 -v
=== RUN   TestManyRoles
    rbac_api_test.go:599: RESPONSE abu        /projects/1        GET :  true IN: 786.635µs
    rbac_api_test.go:599: RESPONSE abu        /projects/2499     GET :  true IN: 4.933064ms
    rbac_api_test.go:599: RESPONSE jasmine    /projects/1        GET :  true IN: 2.908534ms
    rbac_api_test.go:599: RESPONSE jasmine    /projects/2499     GET :  true IN: 7.292963ms
    rbac_api_test.go:599: RESPONSE jasmine    /projects/2499     GET :  true IN: 6.168307ms
--- PASS: TestManyRoles (0.05s)
PASS
ok      github.com/casbin/casbin/v2     0.053s
``` 

Knowing that "sub-expressions" in matchers string are evaluated from the left to right and expression contains only AND (`&&`), it's seems to me logic (evaluation stop on 1st false expression) that it's important to put first (on the left) expression that takes less time to evaluate (here simple equality : `==`) and at the end the `g` matcher that will take more time.

Regarding my analysis, expression evaluation is done [in enforcer.go #599](https://github.com/casbin/casbin/blob/master/enforcer.go#L599) and in my case the most consuming function is recursive call of [hasLinkHelper](https://github.com/casbin/casbin/blob/master/rbac/default-role-manager/role_manager.go#L337) function. 

Could some explain why in such case (with many roles), evaluation of `g(r.sub, p.sub)` is so slow ? 

Moreover I think it would be good to mention in documentation (eg. [here](https://casbin.org/docs/syntax-for-models#matchers)) that operators order in matchers expression is important.

**Comment by bofeng96** [comment]
I encounter similar performance issue. Some _enforce_ take more than 5s.

**Comment by yyy1000** [comment]
Thanks for submitting this issue!
We decided to update the official documentation first.
It would be great if you could submit a PR to fix that!
