### ISSUE TITLE
I get an error after compile golang [Question]

### ISSUE THREAD

**Issue by hs-dev-web** [casbin/casbin#1164]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Your answer here

When I compile golang app do the basic_policy.csv and rbac_model.conf files get included in binary file as well? or should I place them next to binary file? for the app to work?

because i get an error related to casbin after compile

**Comment by hsluoyz** [comment]
@hs-dev-web no, you need to find a way to read your files, or using Go embed.

It's just like normally reading files in Go, it's not related to Casbin.

You can also choose not using files:

- https://casbin.org/docs/model-storage
- https://casbin.org/docs/policy-storage
