### ISSUE TITLE
EOL Component 

### ISSUE THREAD

**Issue by satish-suradkar** [casbin/casbin#1168]
```
Here is the list of policies Knetic/govaluate 20181216-snapshot-9aa49832 violates.
Version/Branch EOL
Severity:Major

Category:Security

Scan Modes:Full

Description
Version or branch requested is EOL.   Please update to a supported version.

Conditions
Component Version Approval StatusEQUALS Deprecated
Component UsageNOT EQUAL TO Dev. Tool / Excluded


```
`Knetic/govaluate` is EOL . Any plan to use any alternative?

**Comment by satish-suradkar** [comment]
@hsluoyz Blackduck hub scan reported it as EOL. The repo has last updated 5 years back and no recent version is available.

**Comment by hsluoyz** [comment]
@satish-suradkar I don't think no update in 5 years is a hard-core reason for us to migrate. Migration is not easy. Better motivations include better performance, more powerful syntax, fewer security holes, etc. And there's no better alternative in the field. We tried migrating to expr but proved to be a failure: https://github.com/casbin/casbin/pull/759
