### ISSUE TITLE
[Question]How to add RBAC with domains in loopback4

### ISSUE THREAD

**Issue by PoyuLU** [casbin/casbin#1169]
export class CasbinAuthorizationProvider implements Provider<Authorizer> {
  constructor(
    @inject('casbin.enforcer.factory')
    private enforcerFactory: (name: string) => Promise<casbin.Enforcer>,
  ) {}

  /**
   * @returns authenticateFn
   */
  value(): Authorizer {
    return this.authorize.bind(this);
  }

  async authorize(
    authorizationCtx: AuthorizationContext,
    metadata: AuthorizationMetadata,
  ): Promise<AuthorizationDecision> {
    const subject = this.getUserId(authorizationCtx.principals[0].id);
    const resourceId = await authorizationCtx.invocationContext.get(
      RESOURCE_ID,
      {optional: true},
    );
    const object = resourceId ?? metadata.resource ?? authorizationCtx.resource;
    const request: AuthorizationRequest = {
      subject,
      object,
      action: metadata.scopes?.[0] ?? DEFAULT_SCOPE,
    };

    const allowedRoles = metadata.allowedRoles;

    if (!allowedRoles) return AuthorizationDecision.ALLOW;
    if (allowedRoles.length < 1) return AuthorizationDecision.DENY;

    let allow = false;

    // An optimization for ONLY searching among the allowed roles' policies
    for (const role of allowedRoles) {
      const enforcer = await this.enforcerFactory(role);

      const allowedByRole = await enforcer.enforce(
        request.subject,
        request.object,
        request.action,
      );

      debug(`authorizer role: ${role}, result: ${allowedByRole}`);
      if (allowedByRole) {
        allow = true;
        break;
      }
    }

    debug('final result: ', allow);

    if (allow) return AuthorizationDecision.ALLOW;
    else if (allow === false) return AuthorizationDecision.DENY;
    return AuthorizationDecision.ABSTAIN;
  }

how to add domain in casbin.authorizer?

**Comment by hsluoyz** [comment]
@PoyuLU this repo is for Golang Casbin. Are you using any kind of loopback4-casbin middleware? If yes, please create GitHub issue at that repo directly. If you are directly using Node-Casbin, you should create issue at: https://github.com/casbin/node-casbin

**Comment by PoyuLU** [comment]
> @PoyuLU this repo is for Golang Casbin. Are you using any kind of loopback4-casbin middleware? If yes, please create GitHub issue at that repo directly. If you are directly using Node-Casbin, you should create issue at: https://github.com/casbin/node-casbin

Hi, thank you for your reply. I have create the issus at Node-Casbin. Thank you.

**Comment by hsluoyz** [comment]
Moved to: https://github.com/casbin/node-casbin/issues/412
