### ISSUE TITLE
Does keyMatch5 does not support '*'?

### ISSUE THREAD

**Issue by MkDierz** [casbin/casbin#1176]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
so i'm using RESTful model but when im adding '*' to policy file the request got rejected 

**model:**

```ini
  [request_definition]
  r = sub, obj, act

  [policy_definition]
  p = sub, obj, act, eft

  [role_definition]
  g = _, _

  [policy_effect]
  e = some(where (p.eft == allow))

  [matchers]
  m = g(r.sub, p.sub) && keyMatch5(r.obj, p.obj) && (r.act == p.act || p.act == "*")
```

**policy:**

```
  p, 1, /api/v1/sdm, GET
  p, 1, /api/v1/sdm/*, GET

```

**Your request(s):**

```
1,  /api/v1/sdm , GET ---> true (expected: true)
1,  /api/v1/sdm/20 , GET ---> false (expected: true)
```

**Comment by MkDierz** [comment]
Hey im learning to contribute, this is my first.
may i take on this issue?
@hsluoyz

**Comment by hsluoyz** [comment]
@MkDierz OK, also add test to: https://github.com/casbin/casbin/blob/857bd7f49362691392804117ab04eee4d65e8262/util/builtin_operators_test.go#L485

**Comment by MkDierz** [comment]
Thanks, will do.

**Comment by MkDierz** [comment]
um hey @hsluoyz i can't push my branch into master to do a pull request, am i doing it the wrong way?

**Comment by MkDierz** [comment]
sorry my bad i figured it out

**Comment by MkDierz** [comment]
Hey @hsluoyz I've created pull request please review
