### ISSUE TITLE
[Question] Is it possible to have generic policies?

### ISSUE THREAD

**Issue by geometrikal** [casbin/casbin#1178]
**What's your scenario? What do you want to achieve?**

I have N resource objects *project*. Users can be assigned a role at a per-resource level. Say we have roles *admin* and *viewer* etc. 

From what I can tell, I have to write the policy out N times for each role, e.g.
```
p, project_admin_1, /project/1, read
...
p, project_admin_N, /project/N, read
```

And then I can give a user the role for a project like:
```
g, alice, project_admin_1
g, bob, project_admin_2
```

Instead, I would like to just write the policy once, and have it match using key matching:

```
p, project_admin_{id}, /project/{id}/*, read
```

**Your model:**

E.g. consider this model

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyMatch4(r.obj, p.obj) && r.act == p.act
```

**Your policy:**

```
# Current:
p, project_admin_1, /project/1, read
p, project_admin_2, /project/2, read
# Desired:
p, project_admin_{id}, /project/{id}, read

g, alice, project_admin_1
g, bob, project_admin_2
g, gary, project_admin_3
```

**Your request(s):**

```
alice, /project/1, read ---> true
bob, /project/2, read  ---> true
gary, /project/3, read ---> false (want this to be true)
```

https://editor.casbin.org/#83VWSEULV

**Comment by geometrikal** [comment]
I think I've come up with something using the domain field of a role.

Consider a hierarchical resource tree of *project -> task -> job*, where:

- A `{resourceType}_admin` role for a specific {resourceType} has read and write access to the {resourceType} and everything underneath it.
- A `{resourceType}_viewer` role for a specific {resourceType} has only read access to the {resourceType} and everything underneath it.

We can use the following **model**:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.obj) && keyMatch4(r.obj, p.obj) && regexMatch(r.act, p.act)
```

and the **policies** are generic, they look like this:

```
p, project_admin, /project/{id}/*, read
p, project_admin, /project/{id}/*, write
p, project_viewer, /project/{id}/*, read
p, task_admin, /project/{pid}/task/{tid}/*, write
p, task_admin, /project/{pid}/task/{tid}/*, read
p, task_viewer, /project/{pid}/task/{tid}/*, read
p, job_admin, /project/{pid}/task/{tid}/job/{jid}/*, write
p, job_admin, /project/{pid}/task/{tid}/job/{jid}/*, read
p, job_viewer, /project/{pid}/task/{tid}/job/{jid}/*, read
```

finally the **roles** could look something like:

```
g, alice, project_admin, /project/1/*
g, bob, project_viewer, /project/1/*
g, bob, task_viewer, /project/1/task/1/*
g, bob, task_admin, /project/1/task/2/*
g, fred, job_admin, /project/1/task/2/job/1/*
```

To check access for a resource we request the user, resource path, and activity. The resource path must end in a trailing slash to match the pattern.  (https://editor.casbin.org/#H5DM57A2R)

e.g. alice has write access to project 1 and all of its resources

```
alice, /project/1/, write --->  true
alice, /project/1/task/1/, write --->  true
alice, /project/1/task/1/job/1/, write --->  true
```

**Comment by geometrikal** [comment]
Further update

If the resources have UUIDs, it is possible to simplify further using regexMatch

**Policies**

```
p, project_admin, .*\/project\/.*, read
p, project_admin, .*\/project\/.*, write
p, project_viewer, .*\/project\/.*, read
p, task_admin, .*\/task\/.*, write
p, task_admin, .*\/task\/.*, read
p, task_viewer, .*\/task\/.*, read
p, job_admin, .*\/job\/.*, write
p, job_admin, .*\/job\/.*, read
p, job_viewer, .*\/job\/.*, write
```

**Roles**

```
g, alice, project_admin, .*\/project\/1\/.*
g, bob, project_viewer, .*\/project\/1\/.*
g, bob, task_viewer, .*\/task\/10\/.*
g, bob, task_admin, .*\/task\/20\/.*
g, fred, job_admin, .*\/job\/100\/.*
```

https://editor.casbin.org/#CBKLEYCEY

**Comment by hsluoyz** [comment]
@geometrikal plz close the issue if resolved
