### ISSUE TITLE
[Question] RBAC with ACL + admin

### ISSUE THREAD

**Issue by jesikmin** [casbin/casbin#1179]
**What's your scenario? What do you want to achieve?**
**Q1)** We have been using a simple ACL-based approach with Casbin for a while. Now we want to also add RBAC support as well as the admin (i.e. root) support. So, I added `g(r.sub, "admin") || (r.sub == p.sub && r.obj == p.obj && r.act == p.act)` in matchers in addition to the typical RBAC matcher. Would this achieve RBAC + admin on top of ACL? i.e. The enforcer will respect RBAC. Even though there is no RBAC policy that will pass, the enforcer will also check whether there's (user, object, action) triplet + admin role to see whether it should still allow the permission.

Is this correct understanding?

**Q2)** Also, on a side note, what does `add_permission_for_use` do? Why we do not specify obj for this API?

Thanks! 

**Your model:**

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, "admin") || (g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act) || (r.sub == p.sub && r.obj == p.obj && r.act == p.act)

```

**Comment by hsluoyz** [comment]
@jesikmin 

1. See: https://casbin.org/docs/supported-models#:~:text=basic_policy.csv-,ACL%20with%20superuser,-basic_with_root_model.conf

2. It's part of RBAC API: https://casbin.org/docs/rbac-api#addpermissionforuser , about what is RBAC API, see: https://casbin.org/docs/api-overview

Please see the docs before asking
