### ISSUE TITLE
[Question] Effective db indexing for RBAC

### ISSUE THREAD

**Issue by jesikmin** [casbin/casbin#1180]
**What's your scenario? What do you want to achieve?**
I am using a standard RBAC model and using PostgreSQL to store the policies. I was wondering on which columns I should add indices to in order to make the query that the Casbin engine makes faster.

For example, I'm guessing we'd add a composite index on (v0, v1, v2) triplet - but is there any other recommendation? Perhaps also on `v0` for efficient query of roles that user has?

**Your model:**

```[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Comment by anujcontractor** [comment]
v0 and v1 - For efficient querying of the roles a user has, you could add a composite index on (v0, v1).
v0, v1, v2 - For efficient querying of the policies for a particular role, you could add a composite index on (v0, v1, v2).
Note that the actual indices that you need to add may vary depending on your specific use case and the amount of data you're working with. It's also a good practice to monitor the performance of your queries and make adjustments to your indices as needed.

CREATE INDEX idx_v0_v1 ON <table_name> (v0, v1);
CREATE INDEX idx_v0_v1_v2 ON <table_name> (v0, v1, v2);

Note that you should make sure to create the indices after the policies have been inserted into the database, as creating indices on an empty table is not useful.

**Comment by hsluoyz** [comment]
Closed as resolved
