### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by sujit-baniya** [casbin/casbin#1185]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
I wanted to validate the user access for routes. My data structure

* Organizations - One organization is top-level and allowed to create/manage other organizations
* Domains - Each organization has its own domain
* Institutes - List of client organizations
* Users - One user can have access to one organization. Each user can have different roles for a single institute and can have access to multiple institutes.
* RolePermission - Each role can have to allow/deny routes and methods for a specific organization.

Users from organizations with "is_owner" could perform operations on institutes based on their roles

**Sample Data on each table**

*Organizations*

```csv
id, name, is_owner
1, ABC Company, true
2, XYZ Company, false
```

*Domains*

```csv
id, organization_id, domain
1, 1, domain.com
2, 2, sub.domain.com
```

*Institutes*

```csv
id, name
1, ABC Institute
2, XYZ Institute
```

*Users*

```csv
id, name
1, John Doe
2, John Rambo
```

*Roles*

```csv
id, name
1, Admin
2, Manager
3, User
```

*RolePermissions*

```csv
id, organization_id, role_id, route, method, action
1, 1, 1, /{institute_id}/blog, GET, allow
1, 1, 1, /{institute_id}/blog, POST, deny
1, 1, 1, /{institute_id}/blog/{id}, POST, allow
1, 1, 1, /search, GET, allow
```

*Memberships*

```csv
id,organization_id, user_id, institute_id, role_id
1, 1, 1, 1, 1
```

I'm not sure how the model would look like

**Your model:**

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g(r.sub, p.sub, r.dom) || g2(r.dom, p.dom)) && globMatch(r.obj, p.obj) && globMatch(r.act, p.act)
```

Please help me and suggest the best model configuration for above scenario.

**Comment by hsluoyz** [comment]
@sujit-baniya this issue list is for general discussion about Casbin itself (bugs, features, etc.). It's not a consulting channel for a specific company scenario.
