### ISSUE TITLE
[feature] requested GetAllRolesByDomain(): how to get all roles in specified domain with api

### ISSUE THREAD

**Issue by gsgs-libin** [casbin/casbin#1189]
not found api here : https://casbin.org/zh/docs/rbac-with-domains-api

**Comment by hsluoyz** [comment]
@gsgs-libin which API do you not found?

**Comment by gsgs-libin** [comment]
> 

Gets all roles under the specified dom

**Comment by hsluoyz** [comment]
GetAllRolesByDomain

**Comment by gsgs-libin** [comment]
thanks
