### ISSUE TITLE
[Question]restart the program,the error occurs: Some issue occurred. please reference req_str for detail

### ISSUE THREAD

**Issue by liangshan4** [casbin/casbin#1197]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Your answer here

**Your model:**
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act

**Your policy:**
![image](https://user-images.githubusercontent.com/121852773/219248859-69118bd1-2101-4b0c-a349-3343956760e9.png)
```
![image](https://user-images.githubusercontent.com/121852773/219248859-69118bd1-2101-4b0c-a349-3343956760e9.png)

```

**Your request(s):**
enfocer.enforce('Admin','/admin/add','POST')
like：bob，/admin/add，POST——>false(expected :true)

After the first program starts, add policy and g, there will be no error, and the success will be displayed.（the first time):
await enfocer.add_policy('Admin','/admin/add','POST')
await enfocer.add_role_for_user('bob','Admin')
enfocer.enforce(subject,url,medthod)       <-------this Succeeded
But the second time I started the program, I wanted to run the code directly because the corresponding p and g were already in the database. (the second time)：
enfocer.enforce(subject,url,medthod)       <--------this failed
However：（and then）：
Some issue occurred. please reference req_str for detail

**Comment by liangshan4** [comment]
是因为第二次启动之后数据库就找不到p和g了吗？我必须再手动添加一次p和g之后，才能正常判断。

**Comment by hsluoyz** [comment]
@liangshan4 please modify all texts into English

**Comment by liangshan4** [comment]
> 

I did it

**Comment by liangshan4** [comment]
![image](https://user-images.githubusercontent.com/121852773/219297500-ea041b1e-7e14-416a-8bdd-cf93f73c9538.png)
I find that the lens of policy is 0, how can solve this problem?

**Comment by liangshan4** [comment]
I find the reson: I did not save the policy. I'm stupid.
