### ISSUE TITLE
need to know how to do this?

### ISSUE THREAD

**Issue by isola93** [casbin/casbin#1200]
i am new to casbin, i need to implement RBAC and ABAC policy, so i found this link [https://github.com/casbin/casbin/issues/419](url)
#419 
but i dont know how to implement this casbin editor ,i am using python for casbin. please help

Model
[request_definition]
r = user, domain, action, resource, attributes

[policy_definition]
p = user, domain, eft, action, resource, conditions

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny)) # deny overrides any allow

[matchers]
m = g(r.user, p.user, r.domain) && r.domain == p.domain && r.resource == p.resource && isMatch(r.attributes, p.conditions) && r.action == p.action

Policy

p, user:finance, domainHere, allow, read, expense, { }
p, user:123-413-13, domainHere, deny, read, expense, { id: 10 }
p, role:financePerson, domainHere, allow, write, expense, { }
g, user:finance, role:financePerson, domainHere

also i try to implement this in python
i am using this casbin editor [https://editor.casbin.org/#AEPBFS3GA](url)

this is the casbin editor i am trying to do ,so please help @hsluoyz
@harveyappleton

**Comment by isola93** [comment]
i got the solution .

**Comment by hsluoyz** [comment]
@isola93 what solution?

**Comment by isola93** [comment]
my mistake is the object mismatch in casbin enforcer,so i did this 
```
    if not(enforcer.enforce('user:finance','domainHere','read','expense',{ 'id': 10 })):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Method not authorized for this user")
    return user
```

in the casbin connector i did this 
```

def condition_check_fun(attributes,conditions):
    try:
        conditions_data= json.loads(conditions)
        if attributes['id'] == conditions_data['id']:
            return True
        else:
            return False
    except:
        return False



e = casbin.Enforcer('model.conf', adapter)
e.add_function("isMatch", condition_check_fun)

```
