### ISSUE TITLE
CachedEnforcer does not expire keys

### ISSUE THREAD

**Issue by yugant007** [casbin/casbin#1202]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
We are using cached enforcer to perform authorization. Authorization along with decision is getting cached as per the behaviour of cached enforcer. But Problem is key's in cache are not getting expire.

Our code stub for initialising cached enforcer instance and setting expiry TTL for cache keys.

```
enforcer, err := casbin.NewCachedEnforcer(configPath, RBACLenderDashboardSvc.Adapter)
if err != nil {
	return err
}

enforcer.EnableCache(true)
enforcer.SetExpireTime(10)
```

**First question - We have set expire time value as 10, this TTL is considered in seconds or milliseconds or hour or other ?**

So we deep dived in casbin golang library code and here is the code flow of cached enforcer Authoriser(Enforce method)

```
func (e *CachedEnforcer) Enforce(rvals ...interface{}) (bool, error) {
if atomic.LoadInt32(&e.enableCache) == 0 {
	return e.Enforcer.Enforce(rvals...)
}

key, ok := e.getKey(rvals...)
if !ok {
	return e.Enforcer.Enforce(rvals...)
}

if res, err := e.getCachedResult(key); err == nil {
	return res, nil
} else if err != cache.ErrNoSuchKey {
	return res, err
}

res, err := e.Enforcer.Enforce(rvals...)
if err != nil {
	return false, err
}

err = e.setCachedResult(key, res, e.expireTime)
return res, err
}
```

If we look in above **Enforce** method,  we see we are calling **setCachedResult** method to save result to cache, and we are passing the expireTime in it. 

```
func (e *CachedEnforcer) setCachedResult(key string, res bool, extra ...interface{}) error {
e.locker.Lock()
defer e.locker.Unlock()
return e.cache.Set(key, res, extra...)
}
```

**setCachedResult** method in turn calls to **Set** method with all parameter's. 

```
func (c *DefaultCache) Set(key string, value bool, extra ...interface{}) error {
(*c)[key] = value
return nil
}
```

If we take a look at  **Set** method, we can spot that expireTime value was never used and therefore TTL was never applied to cache key's. Thus preventing key's in cache to expire and make the cache stale. 

**To Reproduce**

**Expected behavior**
Cache key's should expire when TTL is hit.

**Comment by JalinWang** [comment]
You are right. I've made a PR. Would you mind making a review? #1023

**Comment by yugant007** [comment]
@JalinWang I have reviewed it, looks promising. I have given merge approval on PR. Thanks.
