### ISSUE TITLE
[bug] Why some methods are not present in the interface

### ISSUE THREAD

**Issue by nonchan7720** [casbin/casbin#1206]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

I am using Casbin.
I would like to know why there are methods that are not defined in `IEnforcer` but are present in `Enforcer` but not in `IEnforcer`.
At least the method I was able to identify is `UpdateNamedGroupingPolicy`.
I would like to know why it is not defined.

------

**What's your scenario? What do you want to achieve?**
Your answer here

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, alice, data1, read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write

g, alice, data2_admin
```

**Your request(s):**

```
alice, data2, read ---> false (expected: true)
```

**Comment by hsluoyz** [comment]
@nonchan7720 what issue have you encountered?

**Comment by nonchan7720** [comment]
When using with gormAdapter, Interface is passed in a transaction, but since the corresponding method does not exist, it was necessary to perform a type assert.

https://github.com/casbin/gorm-adapter/blob/7e02f10752bf7be9edb27504556633425d551deb/adapter.go#L646

**Comment by hsluoyz** [comment]
@nonchan7720 can you make a PR to fix it?

**Comment by nonchan7720** [comment]
I understand.
I will submit a PR.
