### ISSUE TITLE
[Bug] Data race in GetImplicitPermissionsForUser in SyncedEnforcer in Go library

### ISSUE THREAD

**Issue by byo** [casbin/casbin#1208]
**Describe the bug**

Data race happens when calling `SyncedEnforcer.GetImplicitPermissionsForUser` for RBAC with domains.

**To Reproduce**

Following go test case reproduces the error:

```go
package racetest

import (
	"context"
	"sync"
	"testing"
	"time"

	"github.com/casbin/casbin/v2"
	"github.com/casbin/casbin/v2/model"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestCasbinRace(t *testing.T) {

	model, err := model.NewModelFromString(`
		[request_definition]
		r = sub, dom, obj, act
		
		[policy_definition]
		p = sub, dom, obj, act
		
		[role_definition]
		g = _, _, _
		
		[policy_effect]
		e = some(where (p.eft == allow))
		
		[matchers]
		m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act
	`)
	require.NoError(t, err)

	e, err := casbin.NewSyncedEnforcer(model)
	require.NoError(t, err)

	_, err = e.AddPolicy("group", "domain", "object", "action")
	require.NoError(t, err)

	wg := sync.WaitGroup{}
	ctx, cancel := context.WithCancel(context.Background())

	const numReaders = 10

	for i := 0; i < numReaders; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for ctx.Err() == nil {
				_, err := e.GetImplicitPermissionsForUser("user")
				assert.NoError(t, err)
			}
		}()
	}

	time.Sleep(time.Second)
	cancel()
	wg.Wait()
}
```

Using latest casbin: `github.com/casbin/casbin/v2 v2.65.0`

**Expected behavior**

There should be no data race when using `SyncedEnforcer`

**Stacktrace**

```
WARNING: DATA RACE
Write at 0x00c0000ad8f0 by goroutine 12:
  runtime.mapassign_faststr()
      /usr/lib/go-1.20/src/runtime/map_faststr.go:203 +0x0
  github.com/casbin/casbin/v2/model.Model.GetFieldIndex()
      /home/bartlomiej/go/pkg/mod/github.com/casbin/casbin/v2@v2.65.0/model/model.go:404 +0x344
  github.com/casbin/casbin/v2.(*Enforcer).GetFieldIndex()
      /home/bartlomiej/go/pkg/mod/github.com/casbin/casbin/v2@v2.65.0/internal_api.go:467 +0x137
  github.com/casbin/casbin/v2.(*Enforcer).GetNamedImplicitPermissionsForUser()
      /home/bartlomiej/go/pkg/mod/github.com/casbin/casbin/v2@v2.65.0/rbac_api.go:299 +0xd2
  github.com/casbin/casbin/v2.(*Enforcer).GetImplicitPermissionsForUser()
      /home/bartlomiej/go/pkg/mod/github.com/casbin/casbin/v2@v2.65.0/rbac_api.go:284 +0x13d
  github.com/casbin/casbin/v2.(*SyncedEnforcer).GetImplicitPermissionsForUser()
      /home/bartlomiej/go/pkg/mod/github.com/casbin/casbin/v2@v2.65.0/rbac_api_synced.go:165 +0xed
  race-test.TestCasbinRace.func1()
      /home/bartlomiej/code/casbin/race-test/race_test.go:51 +0xea
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Go version: go1.20.1
 - Casbin version: v2.65.0

**Additional context**

The bug happens because the `Model.GetFieldIndex` modifies the `assertion.FieldIndexMap` even though the `GetImplicitPermissionsForUser` only holds the `RLock`.

**Comment by hsluoyz** [comment]
@byo hi, can you make a PR to fix it?

**Comment by xuantianyingjie** [comment]
Occasionally, there will be errors. It doesn't seem to be a problem with casbin, like a problem with go compilation

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by PokIsemaine** [comment]
@xuantianyingjie In the case of examples/rbac_with_domains_model.conf, an error occurs

GetFieldIndex In the beginning, assertion. The FieldIndexMap is **modified**

This results in read locks not being effectively protected from concurrency

```golang
func (model Model) GetFieldIndex(ptype string, field string) (int, error) {
	assertion := model["p"][ptype]
	if index, ok := assertion.FieldIndexMap[field]; ok {
		return index, nil
	}
	pattern := fmt.Sprintf("%s_"+field, ptype)
	index := -1
	for i, token := range assertion.Tokens {
		if token == pattern {
			index = i
			break
		}
	}
	if index == -1 {
		return index, fmt.Errorf(field + " index is not set, please use enforcer.SetFieldIndex() to set index")
	}
	assertion.FieldIndexMap[field] = index   // <--------------Here
	return index, nil
}
```

The easiest way to handle this is to make the read lock a write lock, and I'll submit a PR. 

But actually, I personally think that the design of this function is also a bit problematic, coupling `Get` and `initializing assertion`. FieldIndexMap, to some extent, induces this problem, and I think this is something we need to pay attention to in the future. @hsluoyz

**Comment by xuantianyingjie** [comment]
> ```go
> GetImplicitPermissionsForUser
> ```

I see! I just thought a Mutex lock was being used. Ignore the use of RWMutex lock

**Comment by xuantianyingjie** [comment]
> @xuantianyingjie In the case of examples/rbac_with_domains_model.conf, an error occurs
> 
> GetFieldIndex In the beginning, assertion. The FieldIndexMap is **modified**
> 
> This results in read locks not being effectively protected from concurrency
> 
> ```go
> func (model Model) GetFieldIndex(ptype string, field string) (int, error) {
> 	assertion := model["p"][ptype]
> 	if index, ok := assertion.FieldIndexMap[field]; ok {
> 		return index, nil
> 	}
> 	pattern := fmt.Sprintf("%s_"+field, ptype)
> 	index := -1
> 	for i, token := range assertion.Tokens {
> 		if token == pattern {
> 			index = i
> 			break
> 		}
> 	}
> 	if index == -1 {
> 		return index, fmt.Errorf(field + " index is not set, please use enforcer.SetFieldIndex() to set index")
> 	}
> 	assertion.FieldIndexMap[field] = index   // <--------------Here
> 	return index, nil
> }
> ```
> 
> The easiest way to handle this is to make the read lock a write lock, and I'll submit a PR.
> 
> But actually, I personally think that the design of this function is also a bit problematic, coupling `Get` and `Initialize` the `assertion.FieldIndexMap`, to some extent, induces this problem, and I think this is something we need to pay attention to in the future. @hsluoyz

I see! I just thought a Mutex lock was being used. Ignore the use of RWMutex lock

**Comment by hsluoyz** [comment]
@PokIsemaine can you check which PR introduced this issue?

**Comment by xuantianyingjie** [comment]
> @xuantianyingjie In the case of examples/rbac_with_domains_model.conf, an error occurs
> 
> GetFieldIndex In the beginning, assertion. The FieldIndexMap is **modified**
> 
> This results in read locks not being effectively protected from concurrency
> 
> ```go
> func (model Model) GetFieldIndex(ptype string, field string) (int, error) {
> 	assertion := model["p"][ptype]
> 	if index, ok := assertion.FieldIndexMap[field]; ok {
> 		return index, nil
> 	}
> 	pattern := fmt.Sprintf("%s_"+field, ptype)
> 	index := -1
> 	for i, token := range assertion.Tokens {
> 		if token == pattern {
> 			index = i
> 			break
> 		}
> 	}
> 	if index == -1 {
> 		return index, fmt.Errorf(field + " index is not set, please use enforcer.SetFieldIndex() to set index")
> 	}
> 	assertion.FieldIndexMap[field] = index   // <--------------Here
> 	return index, nil
> }
> ```
> 
> The easiest way to handle this is to make the read lock a write lock, and I'll submit a PR.
> 
> But actually, I personally think that the design of this function is also a bit problematic, coupling `Get` and `Initialize` the `assertion.FieldIndexMap`, to some extent, induces this problem, and I think this is something we need to pay attention to in the future. @hsluoyz

@PokIsemaine 
hello，I see that the latest version has replaced the RLock method with Lock, but it seems that both the GetImplicitPermissionsForUser method and the GetNamedImplicitPermissionsForUser method will call GetFieldIndex, so should GetNamedImplicitPermissionsForUser be changed to Lock?
