### ISSUE TITLE
How to solve the huge data when I use persistent Database?

### ISSUE THREAD

**Issue by CHCP** [casbin/casbin#121]
Hi hsluoyz,

  I use casbin gorm_adapter to store policies and roles in database,  when I run the program, all policies will be load into memory. But if there are millions policies, I can not do this. How to solve the huge policy data? Can I check only one policy from database?

Cheers
Gordon

**Comment by hsluoyz** [comment]
Casbin supports only loading a section of policy rules via filters. See here: https://github.com/casbin/casbin#policy-enforcement-at-scale

**Comment by CHCP** [comment]
Cool. 
My scenario is: millions users login the system, every user join different roles, and there are only 100 'p' records, but millions of 'g' records(See below image). Even I use the filtered_adapter, I can not load millions of 'g' records into memory.  So can I load all 'p' records at program startup but do not load 'g' records,  load one special users 'g' record  only when this user access system and check the user's permission?

![image](https://user-images.githubusercontent.com/5645296/44126165-e495a6d0-a079-11e8-9960-1a1399a91b08.png)

**Comment by hsluoyz** [comment]
For the ``filtered adapter`` solution, you can use:

```go
import (
    "github.com/casbin/casbin"
)

enforcer := casbin.NewEnforcer()

adapter := fileadapter.NewFilteredAdapter("examples/rbac_policy.csv")
enforcer.InitWithAdapter("examples/rbac_model.conf", adapter)

filter := &fileadapter.Filter{
    P: []string{"", ""}, // load all 'p' records
    G: []string{"current_user", ""}, // load the 'g' records only for the current user.
}
enforcer.LoadFilteredPolicy(filter)

// The loaded policy now only contains the entries pertaining to "domain1".
```

But here's a question that your RBAC hierarchy cannot be multi-level. For example, let's say ``alice`` has role ``ceo``, ``ceo`` has the role ``executives``. The above code only loads: ``g, alice, ceo``, but will not load: ``g, ceo, executives``, as the filter only works literally. But the current [filtered adapter](https://github.com/casbin/casbin#policy-persistence) only supports .CSV file. So if you use DB, e.g. MySQL, you need to implement the filtering feature on the current non-filtering adapter, e.g., Xorm Adapter.

However, if you need to use multi-level RBAC hierarchy, either you must preload all second level and above ``g`` records like the above ``g, ceo, executives``. I think their size will not be too large. And then load the first-level ``g`` records (directly relates to user) like ``g, alice, ceo`` at run-time.

A more flexible way is to implement your own Role Manager, in this way, you can control all the details for your scenario: https://github.com/casbin/casbin#role-manager


The conclusion is:

1. If you use one-level RBAC, if you use .CSV file, use the existing [Filtered File Adapter](https://github.com/casbin/casbin#policy-enforcement-at-scale)
2. If you use one-level RBAC, if you use DB, implement your own filtering-supported adapter based on existing adapters.
3. If you use multiple-level RBAC, implement your own filtering-supported adapter based on existing adapters, customize it to preload all high level (second level and above) ``g`` records, but load first-level ``g`` records at run-time.
4. If you use multiple-level RBAC, and you want to be more flexible, implement your own [Role Manager](https://github.com/casbin/casbin#role-manager) and do whatever you want.

**Comment by CHCP** [comment]
Thanks for your excellent reply. I will try Role Manager.

Would you plan to split 'g' records from 'casbin_rule' to another table?

**Comment by hsluoyz** [comment]
Casbin loads all ``g`` records from adapter to role manager, so if you decide to use role manager, you will not need ``g`` records any more. There are only ``p`` policy rules in your adapter. And your role manager store your customized role information.

**Comment by CHCP** [comment]
OK, thank your help very much.

**Comment by CHCP** [comment]
I am writing a Role Manager which loading roles from database.
With my scenario before told, I will load all p records when program startup, and load user-role records from database only when one user access the program with RESTful call, I don't want to load p records again and again with LoadPolicy(), so when will I call SetRoleManager() and LoadPolicy()?

**Comment by hsluoyz** [comment]
``LoadPolicy()`` will load all `p` and `g` records from database adapter to memory, and call role manager's `AddLink()` function to add each `g` record. When evaluating a request, ``enforce()`` will call role manager's `HasLink()` function to determine role relationship.

As you don't want to use built-in `g` records, so you don't need to care about `AddLink()`. Just load the data in your own way in your role manager, and implement `HasLink()` in a suitable way, so Casbin can call it.

To your questions specifically, you can call ``SetRoleManager()`` just after ``enforcer`` is created. ``LoadPolicy()`` has nothing to do with your role manager. It's just related to your ``p`` records.

**Comment by vaibhavkhl** [comment]
@CHCP Hi, did you write role manager? Would like to see your implementation.

**Comment by CHCP** [comment]
@vaibhavkhl Hi, sorry I have not write the role manager, it is a bit complex and need more time. If I write it, I will merge to Casbin.

Thanks.
Gordon

**Comment by vaibhavkhl** [comment]
@CHCP ok thanks for your reply.

**Comment by kasvith** [comment]
I think this question should be addressed in `casbin` docs. This is a very common issue for many developers. Also in fact storing data in CSV like format in SQL also makes me thinks twice about picking casbin, It doesn't seem effective at all.

Clearly addressing these issues in docs will help lot of people using casbin in future(no I'm not talking about alice, bob csv example. We need something real with Databases involved)

I feel using casbin with csv is super ok, I ve used it in `argocd` as well, but for APIs(most common case) that does not scale nor provided SQL pattern which loads `p,g` to memory doesn't scale too.

Can you provide some guides about developing a real world app tackling these problems in `casbin` way? For example `casl` offers this in their docs

**Comment by hsluoyz** [comment]
Hi @kasvith we have the docs for performance tuning now: https://casbin.org/docs/en/performance

> For example casl offers this in their docs

Can you share the link of CASL docs? So we can learn from it when improving the docs.

**Comment by kasvith** [comment]
Hi @hsluoyz please find it here https://casl.js.org/v5/en/cookbook/roles-with-persisted-permissions

Since this is addressing a real-world use case, its much more familiar.
I found its very difficult to find good examples in casbin(I'm using node btw)

**Comment by hsluoyz** [comment]
@kasvith thanks for suggestion!

@Zxilly @ErikQQY @Gabriel-403 @nodece plz improved the docs based on: https://casl.js.org/v5/en/cookbook/roles-with-persisted-permissions

**Comment by kasvith** [comment]
@hsluoyz also is there any chance to update the data model which fits into databases natively without wasting space? I feel `v0-v6` columns in DB mostly will have empty values

Also as originally mentioned, if we can separate `p` from `g` it would be awesome

**Comment by Zxilly** [comment]
@kasvith You can create your own adapter. The official adapter is meant to cover most of the cases.

**Comment by Gabriel-403** [comment]
@hsluoyz ok

**Comment by Gabriel-403** [comment]
I think it is necessary to solve the problem of mass persistent data in the future, but we need to discuss how to implement it

**Comment by kasvith** [comment]
It's true that we can develop a custom adapter. But official guidelines enforce the way of CSV columns into Database like follows.

https://casbin.org/docs/en/policy-storage#database-storage-format

This leads to the same problem as originally mentioned in this issue. Even with a small amount of roles/permissions/users, I would not like to use that pattern.

Also one thing I noticed in these adapters is, when you save policies it either [drops the table](https://github.com/casbin/gorm-adapter/blob/379427f6a0d7272d3798b29eaa1306f429cff47a/adapter.go#L508) and rebuilds all from the application level. This feels insane for me, Imagine you want to change one user and now you have to update a massive amount.

I think this problem should be clearly addressed. For example, CASL provides a very sophisticated way to store your rules in DB if you like(a json schema).

**Comment by hsluoyz** [comment]
@kasvith 

> @hsluoyz also is there any chance to update the data model which fits into databases natively without wasting space? I feel `v0-v6` columns in DB mostly will have empty values

We set 7 columns to fit most people's need. If you only need 2 or 3, you can fork it and publish your own adapter.

> 
> Also as originally mentioned, if we can separate `p` from `g` it would be awesome

Similarly, we combine `p` and `g` to make it easier for people to write their own adapter. There are definitely good reasons to seperate them. You can implement your own adaper to meet this more advanced need.

**Comment by kasvith** [comment]
Thanks for the explanation. It makes sense that for most cases this might work. I will look into custom adapters.

But is there any special reason to store the data in columns? does `casbin` pull data column wise?

**Comment by hsluoyz** [comment]
@kasvith 

> But is there any special reason to store the data in columns? does casbin pull data column wise?

I think what we chosen is a normal and natural way for DB persistence. Casbin doesn't support to pull the data for one column with current adapters. Casbin always pulls all required rows and then get the elements from the rows.

**Comment by kasvith** [comment]
Cool thanks for all the info :)

**Comment by xuanlongvts** [comment]
I have had the same Problem. Let's me ask more. Can i use redis-adapter, database save at Redis will have better performance when we comparse with MySql?. https://github.com/casbin/redis-adapter/tree/master
