### ISSUE TITLE
[Feature]Can the GenerateGFunction method pass all parameters transparently to the Haslink of the rolemanager?

### ISSUE THREAD

**Issue by xuantianyingjie** [casbin/casbin#1212]
I started using casbin from version 2.6.9. At that time, there was no open source project that supported both domainrolemanager and sessionrolemanager, so I implemented it. At that time, it was found that GenerateGFunction would only pass the first three parameters to the Haslink method at most.
<html>
<body>

<html>
<body>

p_type | v0 | v1 | v2 | v3 | v4 | v5 | parent_id | auth_id
-- | -- | -- | -- | -- | -- | -- | -- | --
p | 角色id | 域（业务pid） | 资源 | 操作（read/write） |   |   |   | 权限id
g | 用户名 | 角色id | 域（业务pid） | 起始时间 | 截止时间 |   |   | 权限id

</body>
</html>

<br class="Apple-interchange-newline">
</body>
</html>

Although I can register my own g(_,_[,_]) method, I did not do so, but got the current timestamp of the system in haslink.
Recently, we have a user permission requirement to judge non-current time, so I remembered this matter

```go
// HasLink determines whether role: name1 inherits role: name2.
// domain is a prefix to the roles.
func (rm *RoleManager) HasLink(name1 string, name2 string, domain ...string) (bool, error) {
	if len(domain) == 1 {
		name1 = domain[0] + "::" + name1
		name2 = domain[0] + "::" + name2
	} else if len(domain) > 1 {
		return false, errors.ERR_DOMAIN_PARAMETER
	}

	if name1 == name2 {
		return true, nil
	}

	if !rm.hasRole(name1) || !rm.hasRole(name2) {
		return false, nil
	}

	role1 := rm.createRole(name1)
	return role1.hasValidSession(name2, rm.maxHierarchyLevel, strconv.FormatInt(time.Now().UnixNano(), 10)), nil
}

// hasValidSession， recursively modify, verify the role permissions of ancestors
func (sr *SessionRole) hasValidSession(name string, hierarchyLevel int, requestTime string) bool {
	if hierarchyLevel == 1 {
		return sr.name == name
	}

	for _, s := range sr.sessions {
		if s.startTime <= requestTime && requestTime <= s.endTime {
			if s.role.name == name {
				return true
			}
			if s.role.hasValidSession(name, hierarchyLevel-1, requestTime) {
				return true
			}
		}
	}
	return false
}

```

**Comment by hsluoyz** [comment]
@xuantianyingjie you should implement your own custom role manager and g function. You can extend the existing code

**Comment by xuantianyingjie** [comment]
> @xuantianyingjie you should implement your own custom role manager and g function. You can extend the existing code

ok
