### ISSUE TITLE
[Feature]add views like this picture，Tencent Cloud

### ISSUE THREAD

**Issue by zhangdongshun** [casbin/casbin#1213]
![企业微信截图_16788505007246](https://user-images.githubusercontent.com/44290655/225197900-c6303499-f7f5-462d-85bc-c82d639383e1.png)

**Comment by hsluoyz** [comment]
@zhangdongshun hi, please use English

**Comment by hsluoyz** [comment]
@zhangdongshun propose the issue at: https://github.com/casdoor/casdoor/issues
