### ISSUE TITLE
[Bug] Casbin Default Cache throws concurrent read/writes error

### ISSUE THREAD

**Issue by yugant007** [casbin/casbin#1214]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
We are using cached enforcer, when there are concurrent calls to below method Enforce method, Default Cache Map throws concurrent read/writes error.

```
func (e *CachedEnforcer) Enforce(rvals ...interface{}) (bool, error) {
	if atomic.LoadInt32(&e.enableCache) == 0 {
		return e.Enforcer.Enforce(rvals...)
	}

	key, ok := e.getKey(rvals...)
	if !ok {
		return e.Enforcer.Enforce(rvals...)
	}

	if res, err := e.getCachedResult(key); err == nil {
		return res, nil
	} else if err != cache.ErrNoSuchKey {
		return res, err
	}

	res, err := e.Enforcer.Enforce(rvals...)
	if err != nil {
		return false, err
	}

	err = e.setCachedResult(key, res, e.expireTime)
	return res, err
}
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by yugant007** [comment]
@hsluoyz @PokIsemaine please reply

**Comment by PokIsemaine** [comment]
@hsluoyz Hey， I noticed that the documentation mentions CacheEnforcer and thread safety. 
![image](https://user-images.githubusercontent.com/46661603/227663903-061ee2be-a874-4708-98a7-9108a99faf53.png)
https://casbin.org/docs/enforcers#supported-enforcers
Should we modify the documentation to avoid ambiguity, or implement thread safety for CacheEnforcer?

**Comment by hsluoyz** [comment]
@yugant007 @PokIsemaine  can you make a PR to add `CachedSyncedEnforcer`?

**Comment by SnowWarri0r** [comment]
Maybe can ensure thread-safe like this?
https://github.com/casbin/casbin/blob/1766ecae0d87431ea4140ac71afc84893772c802/enforcer_synced.go#L194-L198
```
func (e *CachedEnforcer) Enforce(rvals ...interface{}) (bool, error) {
	if atomic.LoadInt32(&e.enableCache) == 0 {
                e.locker.RLock()
	        defer e.locker.RUnlock()
		return e.Enforcer.Enforce(rvals...)
	}

	key, ok := e.getKey(rvals...)
	if !ok {
                e.locker.RLock()
	        defer e.locker.RUnlock()
		return e.Enforcer.Enforce(rvals...)
	}

	if res, err := e.getCachedResult(key); err == nil {
		return res, nil
	} else if err != cache.ErrNoSuchKey {
		return res, err
	}

        e.locker.RLock()
	res, err := e.Enforcer.Enforce(rvals...)
        e.locker.RUnlock()
	if err != nil {
		return false, err
	}

	err = e.setCachedResult(key, res, e.expireTime)
	return res, err
}
```

**Comment by yugant007** [comment]
@SnowWarri0r Nope it will not work, bcs problem is here https://github.com/casbin/casbin/blob/master/persist/cache/default-cache.go#L27-L50

If multiple thread's delete the key then we will get the concurrent read/write error

***
func (c *DefaultCache) Get(key string) (bool, error) {
	if res, ok := (*c)[key]; !ok {
		return false, ErrNoSuchKey
	} else {
		if res.ttl > 0 && time.Now().After(res.expiresAt) {
			***delete(*c, key)***
			return false, ErrNoSuchKey
		}
		return res.value, nil
	}
}
***

**Comment by yugant007** [comment]
@hsluoyz @PokIsemaine

**Comment by hsluoyz** [comment]
@yugant007 so it's better to be `SyncedCachedEnforcer` instead of `CachedSyncedEnforcer`. The locks should guard the cache too.

@SnowWarri0r @yugant007 can you make a PR to add `SyncedCachedEnforcer`?

**Comment by SnowWarri0r** [comment]
tried to add SyncedCachedEnforcer @hsluoyz
