### ISSUE TITLE
[Question] Why does the adapter interface not include GetFilteredPolicy, GetFilteredGroupingPolicy

### ISSUE THREAD

**Issue by osmian** [casbin/casbin#1215]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
## Scenario:
I am using the rbac with domains model and in this scenario I have two resource types:
- organizations (top level)
- folders (child resources of an organization)

I am using the keymatch2 to declare my policy lines once and grouping policies to match. Specifically adding the `enf.AddNamedDomainMatchingFunc("g", "keyMatch2", util.KeyMatch2)` when instantiating my enforcer along with the [casbin-pg-adapter](https://github.com/casbin/casbin-pg-adapter) adapter. 

## Questions
I want to be able to utilize the postgres adapter to call `GetFilteredGroupingPolicy`/`GetFilteredPolicy` to query postgres using the filter rather than the default implementation on the enforcer where it iterates through the rules on the model. Can this be supported via the adapter interface or another way? In my use case, I want to check if a certain domain exists, say "/organizations/org2" and was planning on using the get filtered policy method to achieve that. For performance it would be a lot better to query postgres rather than iterate all the lines in the model. If there are better ways to achieve it though, definitely interested.

**Your model:**

```ini
[request_definition]
r = sub, dom, act

[policy_definition]
p = sub, dom, act, eft

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && keyMatch2(r.dom, p.dom) && regexMatch(r.act, p.act)
```

**Your policy:**

```
p, org_admin, /organizations/:org, .*, allow
p, org_viewer, /organizations/:org, get, allow
p, folder_admin, /organizations/:org/folders/:folder, .*, allow
p, folder_viewer, /organizations/:org/folders/:folder, get, allow
# organization: org1 admin and viewer roles, with folder admin and viewer roles as well
g, org1_admin, org_admin, /organizations/org1
g, org1_admin, folder_admin, /organizations/org1/folders/:folder
g, org1_viewer, org_viewer, /organizations/org1
g, org1_viewer, folder_viewer, /organizations/org1/folders/:folder
# organization: org1 folder: fold1 admin and viewer roles
g, org1_fold1_admin, folder_admin, /organizations/org1/folders/fold1
g, org1_fold1_viewer, folder_admin, /organizations/org1/folders/fold1
```

**Your request(s):**

```
org1_admin,/organizations/org1,create ---> true (expected: true)
org1_admin,/organizations/org1,get ---> true (expected: true)
org1_admin,/organizations/org1,delete ---> true (expected: true)
org1_admin,/organizations/org1/folders/fold1,create ---> true (expected: true)
org1_admin,/organizations/org1/folders/fold1,get ---> true (expected: true)
org1_admin,/organizations/org1/folders/fold1,delete ---> true (expected: true)
org1_viewer,/organizations/org1,create ---> false (expected: false)
org1_viewer,/organizations/org1,get ---> true (expected: true)
org1_viewer,/organizations/org1,delete ---> false (expected: false)
org1_viewer,/organizations/org1/folders/fold1,create ---> false (expected: false)
org1_viewer,/organizations/org1/folders/fold1,get ---> true (expected: true)
org1_viewer,/organizations/org1/folders/fold1,delete ---> false (expected: false)
org1_fold1_admin,/organizations/org1/folders/fold1,create ---> true (expected: true)
org1_fold1_admin,/organizations/org1/folders/fold1,get ---> true (expected: true)
org1_fold1_admin,/organizations/org1/folders/fold1,delete ---> true (expected: true)
org1_fold1_viewer,/organizations/org1/folders/fold1,create ---> false (expected: false)
org1_fold1_viewer,/organizations/org1/folders/fold1,get ---> true (expected: true)
org1_fold1_viewer,/organizations/org1/folders/fold1,delete ---> false (expected: false)
```

**Comment by hsluoyz** [comment]
@osmian we have the `FilteredAdapter` interface:

https://github.com/casbin/casbin/blob/277c1a2b85698272f764d71a94d2595a8d425915/persist/adapter_filtered.go#L21-L29

You can use an adapter that implements the `FilteredAdapter` interface, call its `LoadFilteredPolicy()` method. Then call enforcer's GetFilteredGroupingPolicy/GetFilteredPolicy

**Comment by osmian** [comment]
> @osmian we have the `FilteredAdapter` interface:
> 
> https://github.com/casbin/casbin/blob/277c1a2b85698272f764d71a94d2595a8d425915/persist/adapter_filtered.go#L21-L29
> 
> You can use an adapter that implements the `FilteredAdapter` interface, call its `LoadFilteredPolicy()` method. Then call enforcer's GetFilteredGroupingPolicy/GetFilteredPolicy

Yeah that is one way of doing it i guess. I've got one enforcer currently and dont want to overwrite the contents of its policy which would happen by calling the `LoadFilteredPolicy()` there. Do you recommend creating a temp enforcer and calling `LoadFilteredPolicy()` then GetFilteredGroupingPolicy/GetFilteredPolicy to retrieve that info?

Also might be better as domains grow to maybe create a seperate enforcer per domain, say org1,org2..etc have many different folders it could be better to create an enforcer using a filtered adapter with just that specific domain?

**Comment by hsluoyz** [comment]
@osmian temp enforcer and sharded enforcer are both good ways, see: https://casbin.org/docs/performance
