### ISSUE TITLE
AddPolicies ??? RemovePolicies???

### ISSUE THREAD

**Issue by hubeidon** [casbin/casbin#1222]
enforcer_cached_synced.go

![2023-04-01 18-26-30屏幕截图](https://user-images.githubusercontent.com/58875867/229280755-df383d8c-c3dc-40f6-a472-93a9b22fbbca.png)

AddPolicies ???
RemovePolicies???

**Comment by hsluoyz** [comment]
@hubeidon this is obviously a bug introduced by: https://github.com/casbin/casbin/pull/1217

Hi @SnowWarri0r can you fix it?
