### ISSUE TITLE
[feature] add the GetImplicitUsersForPermission() API

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin#1233]
@FredVi

### Discussed in https://github.com/casbin/casbin/discussions/1231

<div type='discussions-op-text'>

<sup>Originally posted by **FredVi** April 15, 2023</sup>
Hi guys,

I'd want to use casbin to modelize my very simple RBAC policy.
The model looks like this :

```ini
[request_definition]
r = sub, perm

[policy_definition]
p = sub, perm

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.perm == p.perm
```

Permissions can be assigned to roles. Roles can inherit other roles.
Permissions can be assigned to users and roles can be assigned to users... Quite straightforward.

And here is a policy example :

```csv
p, alice, read_object
p, bob, write_object
p, object_admin, read_object
p, object_admin, write_object
g, tom, object_admin
```

So I can easily get all permissions for user tom by using the GetImplicitPermissionsForUser method.
But, is there a way to get all users that have a given permission ?
Lets say I want to get all users that have the permission write_object (tom and bob); can I do this (in an efficient way) using casbin APIs ?
Thanks for your help !</div>

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by PokIsemaine** [comment]
@hsluoyz 
https://github.com/casbin/casbin/blob/6b2c686aea10f2b2845f015827c00c554b44e17e/rbac_api.go#L335

Already exists

**Comment by PokIsemaine** [comment]
But it is not updated to the documentation
![image](https://user-images.githubusercontent.com/46661603/233280843-0e586186-e881-4518-bed4-b5cf4fb42d7b.png)
