### ISSUE TITLE
[Question] What is considered best practice for managing multiple types of objects?

### ISSUE THREAD

**Issue by erenz14** [casbin/casbin#1234]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
I would like to receive guidance as to what the best way is to manage multiple object types using Casbin, and most examples I see only show 1 model type. My questions are essentially:
1. **If I have 3 model types, i.e Project, Dashboard, MLModel, should I create a separate model.conf and policy.csv for each model type i.e. 3 of each?** **And then have a separate enforcer for each model type i.e. 3 enforcers?** I'm imagining my matchers could be based on attributes specific to each of the models, so combining all might create a cluttered matchers section.
2. For the actual object field in the policy, I see most examples use something like data1/data2. **Is 1 and 2 the ID of the object type data in these examples?** I'm imagining the prefix with the model type is only needed for combined policy files.

**Which of the below 2 policy options are best? Or if there's some better 3rd option please let me know.**

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)
```

**Policy Option #1: Combined**
combined_policy.csv
```
p, alice, project_1, write
p, alice, dashboard_1, write
p, alice, ml_model_1, write
p, bob, project_2, write
p, bob, dashboard_2, write
p, bob, ml_model_2, write
```

**Policy Option #2: Separated**
project_policy.csv
```
p, alice, 1, write
p, bob, 2, write
```
dashboard_policy.csv
```
p, alice, 1, write
p, bob, 2, write
```
ml_model_policy.csv
```
p, alice, 1, write
p, bob, 2, write
```

**Comment by PokIsemaine** [comment]
Q1: I'm not sure which way is better for your needs, both ways have their own characteristics
Option #1 (Combined) is simpler to manage as it only requires one policy file, but it may become more difficult to manage as your application scales. 
Option #2 (Separated) may require more effort to manage initially, but it provides more flexibility and scalability as you can modify policies for each object type independently.

Other: You can consider approaching this from an access control model perspective, such as using the RBAC model.


Q2: data1, 1 and 2 of data2 are not the ID of the object, you can represent the object with any string, this is free

**Comment by erenz14** [comment]
Glad to hear that they are both valid options depending on the use case. I'm going to attempt to implement the separated policies for the added flexibility. Thanks for the quick response.
