### ISSUE TITLE
[Bug] enforce optimization analysis

### ISSUE THREAD

**Issue by kooksee** [casbin/casbin#1236]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/6829652/233607436-63a4adf8-4f10-4cc4-92d7-778baf8e5f4a.png">
The cache used internally in the match function severely affects performance

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by PokIsemaine** [comment]
@kooksee Could you provide the benchmark you use and your desired performance goals?

**Comment by PokIsemaine** [comment]
@kooksee Is it convenient to reveal the size of your policies, as well as the configuration of the machine (e.g. memory size)?
Lock operation up to several minutes is not normal.

I tried running the following BenchMark on a 32 G memory, 12th Gen Intel(R) Core(TM) i9-12900H machine, about 100'000'000 policies.
```golang
func BenchmarkDemo(b *testing.B) {
	e, err := casbin.NewEnforcer("examples/rbac_with_domains_model.conf", "examples/rbac_with_domains_policy.csv")
	if err != nil {
		panic(err)
	}
	pPolicies := make([][]string, 0)
	for i := 0; i < 100000000; i++ {
		pPolicies = append(pPolicies, []string{fmt.Sprintf("user%d", i), fmt.Sprintf("data%d", i/10), "read"})
	}
	_, err = e.AddPolicies(pPolicies)
	if err != nil {
		b.Fatal(err)
	}

	_, _ = e.GetNamedImplicitPermissionsForUser("p", "alice", "domain1")
}
```
CPU Profiler as shown in the figure below, it is still far from the minute level

![image](https://user-images.githubusercontent.com/46661603/235045605-8e8e699a-ed97-42a0-92e8-40116360ebe1.png)

I would like to identify the following: 
1. Are you using larger policies? 
2. Can this problem be reproduced stably? 
3. Does my BenchMark match your actual situation?

Looking forward to your reply, this can help me clarify this issue further, thanks!

**Comment by kooksee** [comment]
@PokIsemaine Is there anything else that needs to be added

**Comment by PokIsemaine** [comment]
> @PokIsemaine Is there anything else that needs to be added

Thanks for the benchmark, this helps a lot with the reproduction issue. We will seriously consider whether it is necessary to keep the cache or rewrite a higher-performance cache
