### ISSUE TITLE
[Bug]Manually modifying data in the database, reporting an error

### ISSUE THREAD

**Issue by zhangyuxin123** [casbin/casbin#1238]
**Describe the bug**
Manually modifying data in the database, reporting errors when starting the project: invalid memory address or nil pointer dereference

**To Reproduce**
1. Modify the values in the data;
2. Start the project;
3. Error: runtime error: invalid memory address or nil pointer dereference

**Screenshots**
![image](https://user-images.githubusercontent.com/23115864/233847276-ede3e852-df63-4de0-8540-983984759346.png)

The gorm gin framework used

**Comment by hsluoyz** [comment]
@zhangyuxin123 don't modify DB data manually if you don't know how to make it right

**Comment by zhangyuxin123** [comment]
但是某些时候通过修改数据库中的值更为方便，比如将某个用户的读权限修改为写权限，特别是在测试阶段，通过数据库修改值更为方便

**Comment by hsluoyz** [comment]
@zhangyuxin123 then you can do it by yourself. We don't recommend modifying DB values directly and won't provide any support on it.

**Comment by zhangyuxin123** [comment]
There is another question here. If the ptype in my database is p1 or any other value, this error will also be reported
