### ISSUE TITLE
Can I get all users in one domain? I did not find this function.

### ISSUE THREAD

**Issue by CHCP** [casbin/casbin#124]
If I want to get all users in domain, what ever the user's role, which function would I call?
 I look for such like GetUsersInDomain in rbac_api_with_domains.go, but I did not find this. would you like to implement this function?
  Thanks.

**Comment by hsluoyz** [comment]
The ``RBAC API`` does not provide this call. You have to use the low-level ``Management API``: https://github.com/casbin/casbin#policy-management

If your policy is like this:

```
g, alice, role1, domain1
g, bob, role2, domain1
```

Then you can use [GetFilteredPolicy()](https://github.com/casbin/casbin/blob/master/management_api.go#L63) to get ``alice, bob`` based on the filter ``domain1``.

**Comment by CHCP** [comment]
OK. Can I get domains based on the filter alice/bob use GetFilterPolicy() also?

**Comment by hsluoyz** [comment]
Yes. You can filter any fields of a policy rule with that API.

**Comment by CHCP** [comment]
Another question: How many records and how long will keep in the memory? what is the Replacement Algorithm: FIFO, LFU, LRU? Thank you again.

**Comment by CHCP** [comment]
Thanks very much.
