### ISSUE TITLE
[Question] Implicit users for a resource

### ISSUE THREAD

**Issue by erickhgm** [casbin/casbin#1241]
Hi everyone, how are you?

**What's your scenario? What do you want to achieve?**
I was reading `casbin` docs and I found this: https://casbin.org/docs/rbac-api#getimplicitresourcesforuser
`GetImplicitResourcesForUser` returns all policies that should be true for a user.

For example:
```
p, alice, data1, read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write

g, alice, data2_admin
```
```
GetImplicitResourcesForUser("alice") will return [[alice data1 read] [alice data2 read] [alice data2 write]]

GetImplicitResourcesForUser("bob") will return [[bob data2 write]]
```

**Your request(s):**
This is great, I need this in my project. However, I need the opposite as well. Get all users (implicit too) for a resource.

For example:
```
p, alice, data1, read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write

g, alice, data2_admin
```
```
GetImplicitUsersForResource("data2") will return [[alice data2 read] [alice data2 write] [bob data2 write]]

GetImplicitUsersForResource("data1") will return [[alice data1 read]]
```

Can I get this result? Did I miss something in the docs?

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by PokIsemaine** [comment]
@erickhgm It seems that casbin does not currently provide such an API. We may consider providing related APIs in a future release.
In addition to this, I would like to discuss the results of GetImplicitUsersForResource. Do you want to return Users or Permissions? If you want to return Permissions, it doesn't seem like the API is named appropriately

**Comment by erickhgm** [comment]
HI @PokIsemaine, thank you for the answer!

Actually, as far I understand reading the docs, `GetImplicitResourcesForUser()` is just a friendly name. In the end, we are getting all policies filtered by `sub`. As `casbin` doc says, everything (sub, obj, act) is a string, doesn't matter if we have a role, permission, or group in the `sub`.

```
[policy_definition]
p = sub, obj, act
```

So, what I would like is to filter by `act`. For me, a name that makes sense is: `GetImplicitSubsForAct()`. However, this name is not following the pattern of the other methods in the API, for which I had said `GetImplicitUsersForResource`.

**Comment by erickhgm** [comment]
Sorry @PokIsemaine, there was a typo in my last message, I meant `obj` instead of `act`. I've edited my message.

About the return, it would be good to return the complete policy, as you said: `[[alice, data1, read], [bob, data2, read]]`. Keeping the same idea that we already have in `GetImplicitResourcesForUser`.

**Comment by PokIsemaine** [comment]
@erickhgm  @hsluoyz Naming it `GetPermissionsForResource` or `GetImplicitUsersForResource`, which one do you think is better?

**Comment by erickhgm** [comment]
We have a method that is similar to what we are talking about, `GetImplicitUsersForPermission`: https://casbin.org/docs/rbac-api#getimplicitusersforpermission. But only users are returned and we have to pass a permission.

In my option, `GetImplicitUsersForResource` is better because we will not pass in the args the permission (obj, act), we will pass only the resource (obj). So, the idea is to get all users for a resource, doesn't matter the permission.

**Comment by PokIsemaine** [comment]
Thank you for your explanation. I will consider implementing `GetImplicitUsersForResource` next.

**Comment by erickhgm** [comment]
Usually, how long it takes to be implemented? Just so I know what to do in the short term.

**Comment by PokIsemaine** [comment]
> Usually, how long it takes to be implemented? Just so I know what to do in the short term.

about 3 days
