### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by qazqwe1596357** [casbin/casbin#1244]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

Is there any detail  constraints of [role_definition] syntax ?

I try use g1, g2 for name in role_definition, but in casbin web editer(https://casbin.org/zh/editor) cannot run return Enforcement Result. And say notice: [ matcher result should only be of type boolean, number, or string ].

When change role_definition name g1 back to g, it works fine.

So, Is there any detail syntax for role_definition and the model config ?

doc in [ https://casbin.org/zh/docs/syntax-for-models ] more like an example.

**Your model: [BAD]**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g1 = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g1(r.sub, p.sub) && g2(r.obj, p.obj) && r.act == p.act
```

**Your policy:**

```
p, alice, data1, read
p, bob, data2, write
p, data_group_admin, data_group, write

g1, alice, data_group_admin
g2, data1, data_group
g2, data2, data_group
```

**Your request(s):**

```
alice, data1, read
alice, data1, write
alice, data2, read
alice, data2, write 
```

**Comment by PokIsemaine** [comment]
@qazqwe1596357 I'm sorry for not explaining this clearly. This phenomenon is related to the following code.
https://github.com/casbin/casbin/blob/6b2c686aea10f2b2845f015827c00c554b44e17e/model/model.go#L94-L111
Currently, Casbin expects the order to be `g`, `g2`, `g3`, and so on. For `g1`, we do not add a suffix, but represent it directly as `g`.

**Comment by hsluoyz** [comment]
Closed as resolved
