### ISSUE TITLE
[Question] Modeling a hierarchical file system shared by multiple users like Google Drive

### ISSUE THREAD

**Issue by rawmarshmellows** [casbin/casbin#1247]
**What's your scenario? What do you want to achieve?**
I was wondering what would be the best way to setup my policies where am I trying to model a hierarchical file system shared by multiple users, similar to Google Drive. The requirements are to be able to give granular permissions to each folder & file in the tree potentially containing millions of files and folders.

**Your model:**

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, 'user::user1', 'account::domain2', 'object::file1', 'permission::read'
p, 'user::user1', 'account::domain2', 'object::file2, 'permission::read'
p, 'user::user1', 'account::domain2', 'object::folder1', 'permission::read'
```

**Your request(s):**
The main issues I am facing are around performance for both:
1. authentication for the file/folder
2. ACL-filtering

With regards to authentication, after running some benchmarks, I can see that with `hasPolicy `it seems like each check takes ~1ms per 10000 policies:
<img width="703" alt="image" src="https://user-images.githubusercontent.com/12663823/236609558-d4f61670-7d66-4c0d-902e-e16af71f001c.png">
While this may work for a small number of files, when there’s a large amount of files, i.e. a million files, I would imagine that each hasPolicy call would take ~100ms to run.

As a result of this, the ACL-filtering which would use hasPolicy for each file/folder in the folder the user is it would take too long.

I've read through the docs, and the source code of Casbin and I believe this is the best way to do it, but I may be wrong, open to suggestions!

**Comment by PokIsemaine** [comment]
@rawmarshmellows Thank you for your feedback. I need some time to verify and check the performance issues.

Before that, you can try the following optimization methods:
1. Use CachedEnforcer
2. Use SyncedEnforce with concurrency
3. Adjust the order of expressions in the matcher to take advantage of the short-circuiting behavior of logical operators without having to evaluate each expression's result.

**Comment by rawmarshmellows** [comment]
I’ve tried using all of the enforcers but hasPolicy is a lot faster than calling *Enforce

Best regards,
Kevin
________________________________

**Comment by PokIsemaine** [comment]
`With regards to authentication, after running some benchmarks, I can see that with hasPolicy it seems like each check takes ~1ms per 10000 policies:`

Authentication is generally done using `Enforce()`, so do you think that `HasPolicy()` affects the performance of `Enforce()`? There doesn't seem to be a particularly direct relationship between the two.

**Comment by rawmarshmellows** [comment]
No the reason I'm using `hasPolicy` is because the more policies I add, the longer it takes to run `Enforce` and any of its variants

**Comment by PokIsemaine** [comment]
> No the reason I'm using `hasPolicy` is because the more policies I add, the longer it takes to run `Enforce` and any of its variants. So I end up doing my own enforcement check via a series of `hasPolicy` calls

Thank you for your explanation. 
So you achieved a similar effect to `Enforce` through `hasPolicy`, met your needs, and has better performance than `Enforce`?
This seems that `Enforce` has a wider range of applications, but its performance may be worse than `hasPolicy` in specific situations?

**Comment by rawmarshmellows** [comment]
Yes that's correct, that's what I have experienced

**Comment by PokIsemaine** [comment]
`Enforce` requires complex calculations and traversing policies for wider applicability, whereas `HasPolicy` is basically indexed with maps. There is a performance gap in a particular case, which I think is reasonable. 

This approach may not be a direct replacement for Enforce in all scenarios, but I think it is certainly a method worth considering.

Would you like to provide an implementation that emulates `Enforce` via `HasPolicy`? Perhaps we can add it as an example to the documentation for performance optimization
https://casbin.org/docs/performance

**Comment by hsluoyz** [comment]
Closed as resolved

**Comment by rawmarshmellows** [comment]
> `Enforce` requires complex calculations and traversing policies for wider applicability, whereas `HasPolicy` is basically indexed with maps. There is a performance gap in a particular case, which I think is reasonable.
> 
> This approach may not be a direct replacement for Enforce in all scenarios, but I think it is certainly a method worth considering.
> 
> Would you like to provide an implementation that emulates `Enforce` via `HasPolicy`? Perhaps we can add it as an example to the documentation for performance optimization https://casbin.org/docs/performance

We ended up implementing our own in-house permission system to deal with ReBAC and combine ACLs with permissions based loosely off of Google Zanzibar
