### ISSUE TITLE
[Question] Combine OIDC JWT token with casbin for authorization

### ISSUE THREAD

**Issue by break2make** [casbin/casbin#1249]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

For rest API authentication, we have used OIDC which generates a JWT access token. This access token is used for authorization in resource server (i.e. API). A JWT access token is having `sub` and `group` claims. The API server uses only group information from token for authorization. Since 3rd party identity server is used for authentication, the `user` (aka `sub`) information is not known while defining the policies in API server using casbin. However, we know the group names while defining the policies and thus, we want to use that information in policy definition, instead of `sub`. I am looking for a model as given below. I am not sure whether this thought is correct. Please share your opinion and how to achieve this using casbin.

**Your model:**

```ini
[request_definition]
r = group, obj, act

[policy_definition]
p = group, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.group == p.group && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, designer, data1, read
p, security_manager, data2, write
p, admin, data2, read

**Comment by hsluoyz** [comment]
@break2make your model looks OK. But we suggest using Casdoor from the same team: https://github.com/casdoor/casdoor to manage OIDC and JWT stuff. It has native and seamless integration with Casbin
