### ISSUE TITLE
Field-level Enforcement

### ISSUE THREAD

**Issue by arun0009** [casbin/casbin#1257]
Is there field level access control e.g. show salary field only if user is 'Manager'. I see OSO provides this "Field-level Enforcement" with documentation here https://docs.osohq.com/any/guides/enforcement/field.html.

Is there anything similar in Casbin?

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by PokIsemaine** [comment]
@arun0009 You can try using the ABAC model. For more details on this model please refer to https://casbin.org/docs/abac.

**Comment by arun0009** [comment]
Isn't ABAC different? I see this answer has been given before too but is say user is manager I want to "show" salary field or else hide it. Field level access control. In OSO this is ABAC https://docs.osohq.com/guides/more/attributes.html.

If you can provide an example that be great or update documentation like OSO does.

**Comment by PokIsemaine** [comment]
![image](https://github.com/casbin/casbin/assets/46661603/e060396e-eab7-4ed9-8fcf-a9a5c7b504d7)



model
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub_rule, obj_rule, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = eval(p.sub_rule) && eval(p.obj_rule) && r.act == p.act
```
policy
```
p, r.sub.Role == 'Manager', r.obj.Filed == 'salary', show
```
request
```
{ Role: 'Manager'}, {Filed: 'salary'}, show
{ Role: 'Manager'}, {Filed: 'salary'}, edit
{ Role: 'User'}, {Filed: 'salary'}, show
{ Role: 'Manager'}, {Filed: 'age'}, show
```
result
```
true
false
false
false
```

I think there is no difference between field-level access and access to normal obj. You can do it in many ways, and you don't have to use ABAC

**Comment by arun0009** [comment]
Thankss @PokIsemaine

**Comment by PokIsemaine** [comment]
@arun0009 Shared at https://editor.casbin.org/#6AA6337N3
RBAC is used for a more concise representation.
For casbin, both field-level access and access to normal resources are treated as strings

**Comment by hsluoyz** [comment]
@arun0009 any update?

**Comment by arun0009** [comment]
I don't think thats what I was looking for, I want to hide only certain fields. Anyways closing this issue.
