### ISSUE TITLE
[Question] How to implement temporal roles with casbin?

### ISSUE THREAD

**Issue by tony-spark** [casbin/casbin#1259]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

I want to have temporal roles in RBAC with domain model.

E.g. I want to grant user1 with admin rights for 2 days:

```csv
g, user1, staff, domain1, 0000-01-01, 9999-01-01
g, user1, admin, domain1, 2023-05-25, 2023-05-26
```

Is it possible with casbin?

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by PokIsemaine** [comment]
Casbin does not support this function for the time being, we will expand the function of g later

**Comment by tony-spark** [comment]
Thanks

**Comment by Leonardo-Ferreira** [comment]
I've got a similar necessity
