### ISSUE TITLE
Support multiple policy definitions

### ISSUE THREAD

**Issue by tdb-alcorn** [casbin/casbin#126]
From https://github.com/casbin/casbin/wiki/Policy-definition
> Note: Currently only single policy definition p is supported. p2 is yet not supported. Because for common cases, our user doesn't have the need to use multiple policy definitions. If your requirement has to use additional policy definitions, please send an issue about it.

I have a use case that might be interesting to you: there are users, domains and items. Users usually obtain permission to work with an item via the role they possess in the item's domain, but sometimes I want to allow a user who has no role in a domain to have access to a single item but not the rest of the domain.

```
+--------+     +------------------+
|        |     |                  |
| User 1 +---> |     Domain 1     |
|        |     |                  |
+--------+     |      +--------+  |
               |      |        |  |
+--------+     |      | Item 2 |  |
|        |     |      |        |  |
| User 2 +----------> +--------+  |
|        |     |                  |
+--------+     +------------------+
```

So I would like to be able to model the situation like this:
```ini
[request_definition]
r = user, domain, item, action

[policy_definition]
p = role, domain, action
p2 = user, domain, item, action

[role_definition]
g = user, role, domain

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (r.domain == p.domain && r.action == p.action && g(r.user, p.role, r.domain)) \
	|| (r.user == p2.user && r.domain == p2.domain && r.item == p2.item && r.action == p2.action)
```

Are there workarounds for achieving this behaviour? If not, what would it take to implement multiple policies? I'd be happy to work on it given some guidance about which parts of the code-base need to change.

**Comment by tdb-alcorn** [comment]
I'm not sure I understand: wouldn't there need to be a `g, alice, alice, domain2` line to satisfy the matcher?

**Comment by hsluoyz** [comment]
The RBAC's ``g`` function will return ``true`` if the 1st arg (user) equals the 2nd arg (role), because ``alice`` of course should have the permissions for ``alice`` herself. See the code here: https://github.com/casbin/casbin/blob/master/rbac/default-role-manager/role_manager.go#L104-L106

**Comment by tdb-alcorn** [comment]
Ok that makes sense, although one thing to note is that this is dependent on the implementation of the role manager (e.g. the [Auth0 role manager](https://github.com/casbin/auth0-role-manager/blob/master/role_manager.go#L163) seems to not allow this).

One other concern I have is about the possibility of there being a very large number of items in a given domain, where almost all of them just follow the same default behaviour specified by the <role, domain, action> policy. Then it seems like it could be a lot more efficient to have multiple policies which allow us to specify only the few exceptions.

**Comment by whyzcandy** [comment]
How would the policy look if the request is:
r, user, itemOrDomain, action

In this case, we want to test access to both a domain or an item.

**Comment by hsluoyz** [comment]
@tdb-alcorn you can use the [Deny-override](https://github.com/casbin/casbin#examples) model to deny your exceptions and allow other requests.

For a more complicated and real-world Deny-override example, you can see Grafana's issue: https://github.com/grafana/grafana/issues/8584#issuecomment-308164722 (although it's not accepted)

**Comment by hsluoyz** [comment]
@whyzcandy you have two ways:

1. Use item and domain together. For example, the resource ``domain1`` in domain ``domain1`` means the domain itself. Of course you should avoid having a real resource named ``domain1``.
2. Use two separated Casbin enforcers, one for item and one for domain.

**Comment by tdb-alcorn** [comment]
What would it take to implement multiple policies? I'm happy to work on it, I just need some guidance about where to look.

**Comment by hsluoyz** [comment]
The first issue is where we should use additional policy like ``p2``. I can think of the following way:

- Use ``p2`` when matching with additional request ``r2``. ``r`` and ``r2`` can be differentiated by different number of arguments in ``enforce()`` call. So when a request comes, we know it's ``r2``. Then we know we should use ``p2`` instead of ``p``.

**Comment by tdb-alcorn** [comment]
That actually seems to fit perfectly with the question that @whyzcandy asked about having a request that really means two different things: in that case you could split up the overloaded request into two separate requests. So:

```
r = user, domain, action
r2 = user, item, action

p = role, domain, action
p2 = role, item, action

g = user, domain, role
g2 = user, item, role
```

What do you think?

**Comment by hsluoyz** [comment]
How to differentiate these two categories of the requests? For a Golang function, ``user, domain, action``  and ``user, item, action`` are both three string args. ``Enforce()`` has no way to differentiate them.

**Comment by hsluoyz** [comment]
Closed as stale.

**Comment by nghianguyen1708** [comment]
Could I ask how did u resolve the problem with differentiating the requests?
