### ISSUE TITLE
[Question] How to quickly filter the output of GetPolicy

### ISSUE THREAD

**Issue by HuckOps** [casbin/casbin#1269]
**What's your scenario? What do you want to achieve?**
When i write a fullstack project, always use casbin to manag frontend and api's permission. 

At first, the frontend requested the permission interface to get frontend permission list, but ```GetPolicy``` get all policies, but i always need to filter one or fewer sub's policy. Therefore, i should use ```for``` to filter what policy which i want. 

If my platform has many policies, this way will make my program run slowly and use more resource to filter policies. So, we hpoe to have a filter function to get  appoint policy.

**Your model:**

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act || r.sub == "root"
```

**Your policy:**

Too many, saved on mysql

**Your request(s):**

None

**Comment by HuckOps** [comment]
This is my code:

```go
func GetPermission(ctx *gin.Context) {
	tenant := ctx.GetHeader("TENANT")
	cas := rbac.Enforce.GetPolicy()
	policyList := [][]string{}
	for _, c := range cas {
		if c[3] == tenant {
			policyList = append(policyList, c)
		}
	}
	restful.SuccessResponse(ctx, policyList, "")
}
```

**Comment by PokIsemaine** [comment]
You can consider loading policy subsets or using concurrent methods to optimize
https://casbin.org/docs/performance

**Comment by hsluoyz** [comment]
Closed as resolved
