### ISSUE TITLE
ABAC with tenants?

### ISSUE THREAD

**Issue by vtolstov** [casbin/casbin#127]
Thanks for this great project. I'm need ABAC for my project:
* user can have access to servers, domains that it owns in all public zones
* zone admin have access to all users in zone and all resources created in this zone
* super admin have access to all

How can i do that with abac? Can you share examples? And i'm read that casbin supports root and administrator feature, where i can find how define/use for it?

**Comment by hsluoyz** [comment]
I think you can use this model:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == r.obj.Owner && r.obj.Domain.IsPublic || r.obj.Domain in r.sub.OwnedDomains || r.sub.IsSuperAdmin
```

You can see the model definition here: https://casbin.org/docs/syntax-for-models.html

**Comment by vtolstov** [comment]
Sorry, may be i miss something, I think that obj act and so is string. Where i can find info about owner and so?

**Comment by hsluoyz** [comment]
``obj`` and ``act`` are strings at most times, but they can also be a struct (in Golang). ``obj.Owner`` means to get the property ``Owner`` of the ``obj`` struct instance. This is why it is called ABAC. Please see our ABAC example and you will get it: https://github.com/casbin/casbin/blob/master/model_test.go#L322-L348

**Comment by vtolstov** [comment]
Ah thanks! I miss that in go obj and act may be struct.
