### ISSUE TITLE
[feature] Pass JSON string directly when using ABAC

### ISSUE THREAD

**Issue by nengc** [casbin/casbin#1272]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

Is that possible to pass JSON string directly when using ABAC model?
Now I must define a struct first. And if i can pass JSON string directly, that will be more convenient when the sub object fields change frequently.

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub_rule, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = eval(p.sub_rule) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p,"regexMatch(r.sub.Name, 'test')",/data1,read
```

**Your request(s):**

```
e, _ := casbin.NewEnforcer("./model.conf", "./policy.csv")

sub := `{ "Age": 30, "Name":"tester"}`
obj := "/data1"
act := "read"

if res, err := e.Enforce(sub, obj, act); res {
	fmt.Println(res)
} else {
	fmt.Println(err)
}
```

**Comment by hsluoyz** [comment]
@PokIsemaine
