### ISSUE TITLE
add feature: objects pool 

### ISSUE THREAD

**Issue by jayddzjh** [casbin/casbin#1274]
Can you add a feature similar to the concept of a object pool, where new object can be dynamically added? This way, when assigning permissions to roles, they can directly access all the current objects without the need for manual implementation.

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by hsluoyz** [comment]
@jayddzjh you can use the "RBAC with Pattern" feature: https://casbin.org/docs/rbac-with-pattern to let the pattern of all new objects inherit the object pool via `g` policy
