### ISSUE TITLE
[Bug]ABAC json request only works when the first param is JSON string

### ISSUE THREAD

**Issue by nengc** [casbin/casbin#1278]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
When pass JSON string to the ABAC model, it works only when the first request param is JSON string. And when i put the JSON string param to the end, it will not work.

And i debugged the latest code, and found the  `tokenIndex` will always 0 in the `requestJsonReplace` function.

**To Reproduce**

**Expected behavior**

**Screenshots**
Works well:
![image](https://github.com/casbin/casbin/assets/19792047/b68b2c16-84f5-44e6-bf53-681c01ffdb72)

![image](https://github.com/casbin/casbin/assets/19792047/fb19a6c4-70ca-44f5-9824-67e377202c28)

Not work

![image](https://github.com/casbin/casbin/assets/19792047/7af352f7-a709-41de-9c1a-666d8ceb52a7)
![image](https://github.com/casbin/casbin/assets/19792047/53c9d170-e62f-4de2-9672-81eb15a46d1d)
![image](https://github.com/casbin/casbin/assets/19792047/c07ccdb7-e160-4a2b-96b8-875eb06a70fe)

And the debug:
![image](https://github.com/casbin/casbin/assets/19792047/9090136a-48a3-43c0-8404-2b424e50e826)

And when i changed the policy to `r_obj.Name`, it works
![image](https://github.com/casbin/casbin/assets/19792047/5190ec63-23e3-4ce7-a17b-53ea545adbbc)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PokIsemaine** [comment]
@nengc thanks for your feedback，I will fix it later
