### ISSUE TITLE
Question about the RBAC model example

### ISSUE THREAD

**Issue by aosolao** [casbin/casbin#1280]
![Snipaste_2023-07-21_15-15-13](https://github.com/casbin/casbin/assets/30789071/a307817d-f6a2-4b28-a290-2732f42914ef)

I want to manage user permissions using the RBAC approach.
I referred to the example: [https://github.com/casbin/casbin/blob/master/examples/rbac_model.conf ↗](https://github.com/casbin/casbin/blob/master/examples/rbac_model.conf)
I configured the model, but found that I couldn't allow permissions.
Is there an error in this example?
I believe that the policy_definition should include the eft parameter in order for the p.eft in policy_effect to have a value and be able to be computed.

Also, if I change the policy_effect formula to `p.eft == deny`, I get an error saying that the eft is not supported. Does this mean that only allow can be configured here?

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by hsluoyz** [comment]
@aosolao only `Priority model` supports effect (eft): https://casbin.org/docs/priority-model
