### ISSUE TITLE
Is there any documentation in Chinese?

### ISSUE THREAD

**Issue by wuxiandashu** [casbin/casbin#129]
Is there any documentation in Chinese?

**Comment by hsluoyz** [comment]
There are several kinds of resources:

1. 5 of the 6 tutorials in ``README.md`` are in Chinese: https://github.com/casbin/casbin#tutorials
2. You can search ``casbin`` in https://www.baidu.com/ for more articles and tutorials.
3. You can join the Tencent QQ group: [546057381](https://shang.qq.com/wpa/qunwpa?idkey=8ac8b91fc97ace3d383d0035f7aa06f7d670fd8e8d4837347354a31c18fac885). Its group files contain more Chinese documents.

**Comment by hsluoyz** [comment]
Closed as stale.

**Comment by hsluoyz** [comment]
@wuxiandashu Hi, now we have the official Chinese documentation here: https://casbin.org/docs/zh-CN/overview

**Comment by hsluoyz** [comment]
Noticed that you are using PHP, we also have PHP-Casbin now: https://github.com/php-casbin/php-casbin
