### ISSUE TITLE
[Question]Enforce when user-role mappings are stored in another table

### ISSUE THREAD

**Issue by pot-code** [casbin/casbin#1292]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
I have used a separate table `user_roles` to store the user-role mappings, table `casbin_rule` should only used for policy storage.

No inherited roles, a user can have many **active** roles.

I would like to know how to achieve:
- only load user roles when enforce rules
- all roles should be checked

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, alice, data1, read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write
```

**Your request(s):**

```
alice, data2, read ---> false (expected: true)
```

**Comment by hsluoyz** [comment]
@pot-code see: https://casbin.org/docs/role-managers

**Comment by pot-code** [comment]
@hsluoyz Thanks, I managed to implement a custom RoleManager but don't have a clear understanding of what each method does, like sometimes it will cache the result. 

I have searched the docs and turns out not very helpful, could you shed more light on the topic?

**Comment by hsluoyz** [comment]
@pot-code learn other role manager's code: https://github.com/casbin?q=role-manager&type=all&language=&sort=

**Comment by gopherTathkarah** [comment]
So is this means i can store users and roles in whatever format if i implement a custom rolemanager?

**Comment by hsluoyz** [comment]
@gopherTathkarah yes
