### ISSUE TITLE
[Question] A move from golang mock to uber's fork?

### ISSUE THREAD

**Issue by piusalfred** [casbin/casbin#1299]
The [https://github.com/golang/mock](https://github.com/golang/mock) has been archived. Below is am excerpt from the project README
``` text
Update, June 2023: This repo and tool are no longer maintained. Please see [go.uber.org/mock](https://github.com/uber/mock) for a maintained fork instead.
```
Is it okay for casbin to change the [dependency](https://github.com/casbin/casbin/blob/a50c61c77acde6f602cfaa79ffdf06be1db86354/go.mod#L5) to the suggested uber fork [go.uber.org/mock](https://github.com/uber/mock) ?

**Comment by hsluoyz** [comment]
@piusalfred can you make a PR?

**Comment by hsluoyz** [comment]
https://github.com/uber-go/mock is only v0.2.0 and it's hosted in `uber.org` domain, which is much less official than: https://github.com/golang

I mean, there's no pariticular reason for us to jump to such a new version so quickly, as we don't rely on new features of it either. We only use it a very little bit in some small tests. Just waiting for a more mature replacement would be a better move.

**Comment by peterzernia** [comment]
https://github.com/golang/mock has been archived and no further development will happen on it. The uber library is the offically maintained fork

**Comment by hsluoyz** [comment]
We don't need further versions. The current archived old version is enough. `v0.2.0` and the `uber.org` domain is not that trustable, we don't trust it for now.
