### ISSUE TITLE
Multiple/secondary request subjects?

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin#13]
> For our use case, it would be highly beneficial to be able to send multiple subjects as part of the same request, e.g. "subjects": ["user:peter", "group:admin"] to avoid having to query the API multiple times.
> 
> I'm more than happy to provide a PR for this, just wanted to check first of there are any reservations or concerns?
> 
> Cheers,
> dim

Hi @dim, [Casbin](https://github.com/casbin/casbin) is a new authorization library which supports flexible access control models like ACL, RBAC, ABAC.

Casbin supports defining the request format, the most commonly used format is:
```
[request_definition]
r = sub, obj, act
```
which means subject, object, action.

But you can customize it as:
```
[request_definition]
r = sub, sub2, sub3, obj, act
```

The only requirement is that you design the proper matchers in casbin model. For example, the original model is:
```
[matchers]
m = r.sub == p.sub && r.obj == p.obj && r.act == p.act
```

Now you may need:
```
[matchers]
m = (r.sub == p.sub || r.sub2 == p.sub || r.sub3 == p.sub) && r.obj == p.obj && r.act == p.act
```

It means that if any of sub, sub2, sub3 in a request matches the subject in the policy rules, it will return an allow.

Let me know if you have any questions:)

**Comment by 115100** [comment]
We're using Ladon as part of [Hydra](https://github.com/ory/hydra) and not as a standalone library so unfortunately we aren't able to use this.
