### ISSUE TITLE
[Feature] Adapter supports `ctx`

### ISSUE THREAD

**Issue by shenghui0779** [casbin/casbin#1302]
![image](https://github.com/casbin/casbin/assets/67535398/32ec038f-b34e-4139-9bb8-8d5467c55196)

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by shenghui0779** [comment]
Currently, the context can only be used to control the execution timeout of the adapter and cannot continue to pass down.

**Comment by shenghui0779** [comment]
The adapter's methods cannot use the context passed from external sources internally.

<img width="757" alt="image" src="https://github.com/casbin/casbin/assets/67535398/3ea3cd3b-393a-4716-8ea0-572d9657db1e">

**Comment by hsluoyz** [comment]
@shenghui0779 ctx is added here: https://github.com/casbin/gorm-adapter/blob/master/context_adapter.go

**Comment by shenghui0779** [comment]
<img width="679" alt="image" src="https://github.com/casbin/casbin/assets/67535398/aa98db2f-a696-4b32-9f83-8a84c4c812f7">

**Comment by toppercodes** [comment]
+1 I'm in a situation where I need the context in LoadPolicy
