### ISSUE TITLE
[Bug] Different types of role definition wrong g function

### ISSUE THREAD

**Issue by mtt0** [casbin/casbin#1306]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
G function will be override by wrong generated g function if we have at least *2* different types role definition.

https://github.com/casbin/casbin/blob/e46d08ee10207a3fd89972e40590f794612e27d1/enforcer.go#L584-L594

**To Reproduce**
https://go.dev/play/p/blXW5-bZ1ZA

**Screenshots**
<img width="970" alt="image" src="https://github.com/casbin/casbin/assets/17849741/197c5c9b-cc7c-40b3-a183-7d907414c766">

<img width="834" alt="image" src="https://github.com/casbin/casbin/assets/17849741/3d5e2b4a-9df2-4d4a-b46e-5a02bdc2e92e">

**Comment by hsluoyz** [comment]
@PokIsemaine
