### ISSUE TITLE
[Bug] AddPoliciesEx Duplicates All Rules Instead of Avoiding Duplication

### ISSUE THREAD

**Issue by gabriel-henriq** [casbin/casbin#1310]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
I'm encountering an issue with the AddPoliciesEx function. When using this function to append policies to the storage, it is duplicating all existing rules instead of avoiding duplication.
I'm using the [casbin-bun-adapter](https://github.com/cuipeiyu/casbin-bun-adapter) alongside the casbin library.

According to the documentation:
```go
// AddPoliciesEx adds authorization rules to the current policy.
// If the rule already exists, the rule will not be added.
// But unlike AddPolicies, other non-existent rules are added instead of returning false directly
```

However, the current behavior is that all policies are being duplicated in the storage.

**To Reproduce**

To reproduce this issue, follow the code snippet below. The code is designed to add a new policy if it doesn't exist each time the app restarts.

```go
	rules := [][]string{
		{"role_admin", "*", "(POST)|(GET)|(DELETE)|(PATCH)|(CMD)"},
		{"role_user", "/v1/users/login", "POST"},
		{"role_user", "/v1/users/logout", "POST"},
		{"role_user", "/api/v1/users/sessions/active", "GET"},
		{"role_user", "/api/v1/users/sessions/:id", "DELETE"},
		{"role_user", "/api/v1/users/sessions", "DELETE"},
		{"role_user", "subscribe", "CMD"},
	}
	if _, err = e.AddPoliciesEx(rules); err != nil {
		logger.Fatal("failed to create casbin policies", zap.Error(err))
	}
```
My analysis suggests that the [line](https://github.com/casbin/casbin/blob/master/internal_api.go#L87) in the code is being called every time `AddPoliciesEx` is executed.

**Expected behavior**
The expected behavior of  `AddPoliciesEx` is to only add non-existent policies to the storage, avoiding duplication.

**Screenshots**
Storage state before the second call:
![image](https://github.com/casbin/casbin/assets/67342474/abfa9a62-91cd-4ca9-bb10-8d8cba2a8a11)
Storage After the Second call:
![image](https://github.com/casbin/casbin/assets/67342474/b5ea59b4-9943-4f64-8f3b-438c4e7ab925)

**Comment by PokIsemaine** [comment]
@gabriel-henriq Thank you for your feedback.

Please provide your `model.conf` or I can't reproduce it. 

Also, https://github.com/cuipeiyu/casbin-bun-adapter doesn't seem to be an official Casbin adapter, and we won't be able to fix it directly, so you can consider submitting an issue with `Casbin-Bun-Adapter`

**Comment by hsluoyz** [comment]
@gabriel-henriq this is the adapter's issue. You can see the code: https://github.com/cuipeiyu/casbin-bun-adapter/blob/bb450dd153cbde1750aa764e8efb47d0ad0a1bf8/adapter.go#L312-L318

It doesn't handle duplicated policy rules. So you need to create an issue at that repo instead of here:

https://github.com/cuipeiyu/casbin-bun-adapter/issues

**Comment by gabriel-henriq** [comment]
Right, thanks for your reply guys!
