### ISSUE TITLE
[Feature] Implement Passkey

### ISSUE THREAD

**Issue by VladimirCores** [casbin/casbin#1311]
As a user I would like to login **without password** using passkey.

Info here: https://webauthn.guide/ or https://www.passkeys.io/

**Comment by hsluoyz** [comment]
@VladimirCores I think you got the repo wrong. Are you looking for: https://github.com/casdoor/casdoor ?

**Comment by VladimirCores** [comment]
@hsluoyz I had searched on main web site for "WebAuth" found nothing, so I decided to suggest a feature, but the tool is already up to date with it and has it, that's really awesome! Thanks for pointing me to that and sorry for interruption.
