### ISSUE TITLE
ACL: is it possible to inherit policies?

### ISSUE THREAD

**Issue by Lupici** [casbin/casbin#1314]
Hi, I want to to write a policy like this:

p, user1, obj1, action1
p, user1, obj2, action2

p, user2, obj1, action1
p, user2, obj2, action2
p, user2, obj3, action3

p, user3, obj1, action1
p, user3, obj2, action2
p, user3, obj3, action3
p, user3, obj4, action4

so, at the end, user1 can perform 2 actions, user2 can perform the same 2 actions of user1 + another one, and user 3 can perform the same 3 actions of user 2 + another one.

Is it possible to write the policy in a more condensed way, like (it's just an example)

p, user1, obj1, action1
p, user1, obj2, action2

user2=user1 + p, user2, obj3, action3

user3=user2 + p, user3, obj4, action4

because I have many policies, and they are basically copied from one user to another one... to avoid errors and to be easier when I have to add another policy to all users...

Thanks a lot

Lupix

**Comment by hsluoyz** [comment]
@Lupici RBAC is just what you need: https://casbin.org/docs/rbac

**Comment by Lupici** [comment]
> @Lupici RBAC is just what you need: https://casbin.org/docs/rbac

I already see rbac, but I can't figure out how to achieve the result. Seem a little too bit complicate for what I need

**Comment by Lupici** [comment]
Maybe I found the solution, thanks to the advice on rbac....

with this conf:
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act

and with this policy

p, user1, obj1, action1
p, user1, obj2, action2

g, user2, user1
p, user2, obj3, action3

g, user3, user2
p, user3, obj4, action4

all seems worked as I expected!
thanks
