### ISSUE TITLE
[Question] About GetImplicitResourcesForUser() 

### ISSUE THREAD

**Issue by GinkT** [casbin/casbin#1316]
I want to create a model where i have objects grouped in sets by identifier (_**N** in policy) and by type ( **type**_sources in policy). Access for objects can be granted via type or identifier.

Model works fine. Next, i want to show all available objects for user. However, when i use method _GetImplicitResourcesForUser()_ im not getting output as i expect.

GetImplicitResourcesForUser("bob") produces:
`[[bob doc_sources read]]`
Wanted:
`[[bob source_1_docs read], [bob source_2_docs read]]`

GetImplicitResourcesForUser("alice") produces:
`[[alice source_1 read]]`
Wanted:
`[[alice source_1_docs read], [alice source_1_images read]]`

How can i get a desired output? Or should i use a different method? 
Also, i want to get all available objects by type and by id.

Thanks for your answer!

**Your model:**
```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && g(r.obj, p.obj) && r.act == p.act
```

**Your policy:**
```
p, bob, doc_sources, read
p, alice, source_1, read

g, source_1_images, image_sources
g, source_1_images, source_1

g, source_1_docs, doc_sources
g, source_1_docs, source_1

g, source_2_docs, doc_sources
g, source_2_docs, source2
```

**Your request(s):**

```
bob, source_1_docs, read ---> true (through :doc_sources mapping)
bob, source_2_docs, read ---> true

alice, source_1_docs, read ---> true (through :source_1 mapping)
alice, source_1_images, read ---> true (through :source_1 mapping)
```

**Comment by PokIsemaine** [comment]
@GinkT `g = _, _` is used to represent the inheritance relationship between `user` and `role`. They usually correspond to `sub`, not `obj` (resource)

**Comment by GinkT** [comment]
> @GinkT `g = _, _` is used to represent the inheritance relationship between `user` and `role`. They usually correspond to `sub`, not `obj` (resource)

can i somehow use **g** for resource grouping?

**Comment by osmian** [comment]
@GinkT have you considered using domains for grouping the resource and the g policy of `g = _, _, _`
