### ISSUE TITLE
[Question] Does LoadFilteredPolicy function support FileAdapter only?

### ISSUE THREAD

**Issue by meivaldi** [casbin/casbin#1322]
Hi, I wanna use filtered policy using pg adapter ([Filtered PostgreSQL Adapter](https://github.com/casbin/casbin-pg-adapter)) but when I try to run my service on my local device it got error like `filtered policies are not supported by this adapter`. When I look into the code, I think it's only support for FileAdapter.

https://github.com/casbin/casbin/blob/c907b9054e5a179fe7d1f64b3003837de3969bcc/enforcer.go#L399C2-L403C3

 Am I correct? If not, could you help me the way to use pg adapter instead file adapter. Btw I'm using casbin v2.77.2. Thanks!!!

**Comment by hsluoyz** [comment]
@meivaldi you can use either:

- https://github.com/casbin/gorm-adapter
- https://github.com/casbin/xorm-adapter

They have both implemented the FilteredAdapter interface and support PostgreSQL
