### ISSUE TITLE
Can I Add a Policy CSV File Via Text?

### ISSUE THREAD

**Issue by jimydavis** [casbin/casbin#1323]
The premise is that I am using a DB adapter but wish to use a policy.csv to saturate the DB with the initial policy for the very first time a server starts.

Currently, `AddPolicy` or AddPolicies require an input of comma separated strings such as ("p", "alice", "sub-reader", "sub1").

Do you have an API such as AddPolicyFromFile("my_initial_policy.csv") ?

For example, I would add my initial hierachical RBAC in one shot when the app initializes for the first time:

```
// my_initial_policy.csv

// subscription role to subscription action mapping
g, sub-reader, sub-read
g, sub-owner, sub-read
g, sub-owner, sub-write

// resourceGroup role to resourceGroup action mapping
g, rg-reader, rg-read
g, rg-owner, rg-read
g, rg-owner, rg-write

// subscription role to resourceGroup role mapping
g, sub-reader, rg-reader
g, sub-owner, rg-owner

// subscription resource to resourceGroup resource mapping
g2, sub1, rg1
g2, sub2, rg2
```

I can write my own CSV parser, but I am also trying to figure out why this is not an obvious API and can't be found easily. Do I have the wrong mental model?

**Comment by hsluoyz** [comment]
@jimydavis 

see: https://casbin.org/docs/adapters/#migrateconvert-between-different-adapter

**Comment by hsluoyz** [comment]
@jimydavis thanks, it has been fixed: https://github.com/casbin/casbin-website-v2/commit/811bdef26c0480f71eaca30d9a1c23a02b370b60
