### ISSUE TITLE
[Bug] LoadPolicyFast   perm not work

### ISSUE THREAD

**Issue by rentiansheng** [casbin/casbin#1332]
**Want to prioritize this issue? Try:**

<img width="630" alt="image" src="https://github.com/casbin/casbin/assets/3955934/df2d11de-d081-408a-b222-f2a4dfff46fe">

enforcer_synced.go  新add  	e.invalidateMatcherMap() can work

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hsluoyz** [comment]
@rentiansheng can you make a PR to fix it?

**Comment by rentiansheng** [comment]
> @rentiansheng can you make a PR to fix it?

yes, is testing. later commit
