### ISSUE TITLE
How to use `ContextAdapter` ?

### ISSUE THREAD

**Issue by shenghui0779** [casbin/casbin#1335]
Impl `ContextAdapter` need to impl `Adapter` ?

How can `context` pass to db operation by `Adapter`, eg: `ent.All(ctx)`

Currently, the context can only be used to control the execution timeout of the adapter and cannot continue to pass down.

Related to: https://github.com/casbin/casbin/issues/1302

**Comment by shenghui0779** [comment]
How can `context` pass to db operation by `Adapter`, eg: ent

**Comment by hsluoyz** [comment]
@shenghui0779 are you implementing an adapter? if yes, where's the code?

**Comment by shenghui0779** [comment]
https://github.com/casbin/gorm-adapter/blob/master/context_adapter.go

**Comment by shenghui0779** [comment]
The adapter's methods cannot use the context passed from external sources internally.

<img width="757" alt="image" src="https://github.com/casbin/casbin/assets/67535398/3ea3cd3b-393a-4716-8ea0-572d9657db1e">

**Comment by hsluoyz** [comment]
Don't reply in two places. This issue will be silenced
