### ISSUE TITLE
Are weighted/hierarchical roles supported?

### ISSUE THREAD

**Issue by ldelossa** [casbin/casbin#134]
Is it possible to allow only a specific role to override policy effect? For example let's say I have an Admin role which allows access to Resource A. I have Role1 which denies access to Resource A and I have Role2 which allows access to Resource A. 

Is it possible to have a policy-effect that allows the following:

User1 has Admin role, Role1, and Role2. I want Admin role to weighted the highest, and win the policy effect. If User1 has admin role, allow access to Resource A.

User2 has Role1 and Role2. I want a deny policy here because only admin should be able to override. User2 will not get access to Resource A because both roles are of the same "weight" or hierarchy.

**Comment by hsluoyz** [comment]
It's very simple to do it in Casbin. You can just use the priority model. See the last row of this table: https://github.com/casbin/casbin#examples

In the priority model, the weight of a policy rule is determined by its order in the .csv file or database table. So you can put the Admin policy to the first.

The model (same as the priority model example):

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = priority(p.eft) || deny

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

The policy:

```csv
p, Admin, Resource_A, *, allow
p, Role1, Resource_A, *, deny
p, Role2, Resource_A, *, allow

g, User1, Role1
g, User1, Role2
g, User1, Admin
```

You will get:

```go
e.Enforce("User1", "Resource_A", "read") // == true
```

**Comment by hsluoyz** [comment]
Closed as stale.
