### ISSUE TITLE
[Feature] support return err in GetPermissionsForUser

### ISSUE THREAD

**Issue by dacongda** [casbin/casbin#1357]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Is your feature request related to a problem? Please describe.**
```golang
func main() {
	e, err := casbin.NewEnforcer("example/policy.conf", "example/policy.csv")

	if err != nil {
		log.Fatalf("err :adapter: %s", err)
	}

	// e.SetFieldIndex("p", "app", 2)
	e.SetFieldIndex("p", "dom", 1)

	res := e.GetPermissionsForUser("invoice", "app")

	println(len(res))
}
```
```plain
[request_definition]
r = RoleId, domain, TypeQuery, operationName

[policy_definition]
p = RoleId, domain, TypeQuery, operationName, eft, scope

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.RoleId, p.RoleId, r.domain) && r.domain == p.domain && r.TypeQuery == p.TypeQuery && r.operationName == p.operationName
```

When I use above code and model conf , if have't  `e.SetFieldIndex("p", "dom", 1)` ,the programme will not report any error , and just return an empty result , by the way, it seems that func GetNamedPermissionsForUser only use the first elment of domain list.

**Describe the solution you'd like**
Throw an error like "dom index is not set, please use enforcer.SetFieldIndex() to set index" or support use dynamic domainIndex

**Describe alternatives you've considered**
Create a new func that support return err msg or just rewrite this func

**Additional context**

**Comment by hsluoyz** [comment]
@dacongda can you make a PR?

**Comment by ankan20** [comment]
Is it assigned to anyone or is it closed?
