### ISSUE TITLE
[Question] How to get permissions while using resource roles

### ISSUE THREAD

**Issue by yanwii** [casbin/casbin#1360]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Your answer here

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && r.act == p.act
```

**Your policy:**

```
p, alice, data_group, write

g, alice, data_group_admin
g2, data1, data_group
g2, data2, data_group
```

**Your request(s):**

If I want to get all permissions for user alice and resource data1, it doesn't work  

```go
enforcer.GetFilteredPolicy(0, "alice", "data1")
expected: [["alice", "data1", "write"]...]
actual: []

enforcer.GetImplicitPermissionsForUser("alice") 
expected: [["alice", "data1", "write"]...]
actual: [["alice", "data_group", "write"]...]
```

Is there any API supporte this action?

**Comment by hsluoyz** [comment]
@yanwii right now, `GetFilteredPolicy()` doesn't support g or g2. `GetImplicitPermissionsForUser()` only supports g but doesn't support g2.

We need to support both g and g2 in `GetImplicitPermissionsForUser()`
