### ISSUE TITLE
[Question] Why CachedEnforcer uses sync.RWMutex just like sync.Mutex?

### ISSUE THREAD

**Issue by migregal** [casbin/casbin#1366]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

If I got it right, for now CachedEnforcer uses RWMutex just like simple Mutex: https://github.com/casbin/casbin/blob/master/enforcer_cached.go#L130-L131

My point is we can simply use this code
```go
e.locker.RLock()
defer e.locker.RUnlock()
```

Seems like it can improve CachedEnforcer perfomance by removing unnecessary locks in multithreaded applications like web servers etc.

Doens't seem to be a hard one so I can fix it my self if it's a real issue and not my miss.

**Comment by migregal** [comment]
My bad

Found this one https://github.com/casbin/casbin/pull/1348 and got it clear

Actually, it doesn't seem to be the rigth way to handle expiration

I think i'll be better to have it next way:
* run a separated goroutine to remove expired items ones per interval
* if we got expired item on getCachedResult, skip it (just return ErrNoSuchKey)
* if we have successful Enforce call, save it to cache (even by rewrite of old value)

This approach seems to be much more effective in terms of lock times & doesn't make such silly questions as my one

Seems, that I still can handle it on my own

What do you think about it?

**Comment by hsluoyz** [comment]
@migregal goroutine can be dead. Your solution is fragile.

**Comment by migregal** [comment]
I got your point

Separated goroutine definitely not the best solution but first that i come up with

Actually I check source code one more time & seems that i just don't get it from the first try

As I can see SyncedCachedEnforcer is already there & it does implement all I need

So why do this package still provides CachedEnforcer it there are more safe (in terms of cuncurrency) & perfomant (in terms of lock time) version? Just for backwards compability with existing source code?

**Comment by migregal** [comment]
Also it'll be nice if you'll add other Enforcers benchmark results - I think it'll help developers to better understand what they are using & what changeed from version to version in case of updating deps

**Comment by hsluoyz** [comment]
> Also it'll be nice if you'll add other Enforcers benchmark results - I think it'll help developers to better understand what they are using & what changeed from version to version in case of updating deps

Create new issue for this. This issue will be closed
