### ISSUE TITLE
[Question] Is it expected that keyMatch3 handles `*` pattern?

### ISSUE THREAD

**Issue by mih-kopylov** [casbin/casbin#1367]
Hello!

I'm looking at doc https://casbin.org/docs/function/

It explicitly says that

* `keyMatch` handles a URL path or a `*` pattern like `/alice_data/*`
* `keyMatch3` handles a URL path or a `{}` pattern like `/alice_data/{resource}`

At the same time the https://github.com/casbin/casbin/blob/277c1a2b85698272f764d71a94d2595a8d425915/util/builtin_operators_test.go#L171-L196 tests demonstrate different behaviour:

* testKeyMatch3(t, "/foo/bar", "/foo/*", true)
* testKeyMatch3(t, "/proxy/myid/res", "/proxy/{id}/*", true)

According to the tests, the `keyMatch3` function handles both `{}` pattern AND `*` pattern, while it's not documented.

If that's an expected behaviour, could you please document that explicitly.
Otherwise the tests should be fixed.

Moving forward, there's `keyMatch5` function as well which handles a URL path, a {} or * pattern like /alice_data/{id}/*, according to the documentation.
And the tests https://github.com/casbin/casbin/blob/1cde2646d10ad1190c0d784c3a1c0e1ace1b5bc9/util/builtin_operators_test.go#L485-L526 prove it.

It looks like `keyMatch3` and `keyMatch5` behave equally, while the documentation says they shouldn't.

**Comment by mih-kopylov** [comment]
It's also not quite clear about the `keyMatch3` and `keyMatch4` difference.

According to the doc, the latter handles double `{}` parameters
> a URL path or a {} pattern like /alice_data/{id}/book/{id}

while the former handles only single `{}` parameters
> a URL path or a {} pattern like /alice_data/{resource}

But in the following example both `keyMatch3` and `keyMatch4` work equally

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && keyMatch3(r.obj, p.obj) && (r.act == p.act)
```

```
p, alice, /api/{param1}/data/{param2}, GET
```

```
alice, /api/12/data/23, GET
```

**Comment by hsluoyz** [comment]
@mih-kopylov 

keyMatch3() and keyMatch4() both support * as well

keyMatch4() tests if the same "id" occurrences have the same value

https://github.com/casbin/casbin/blob/277c1a2b85698272f764d71a94d2595a8d425915/util/builtin_operators_test.go#L208-L222

**Comment by mih-kopylov** [comment]
@hsluoyz thanks for your response.

> keyMatch3() and keyMatch4() both support * as well

I spotted some points where the documentation is not clear and ambiguous.

Could you please fix the documentation adding:

* difference between `keyMatch` and `keyMatch3`
* difference between `keyMatch3` and `keyMatch5`
* difference between `keyMatch3` and `keyMatch4`

**Comment by mih-kopylov** [comment]
@hsluoyz could you please reopen the issue until the documentation is fixed?
