### ISSUE TITLE
[Bug]`GetRolesForUser("userId")` will raise nil error when using RBAC with conditions.

### ISSUE THREAD

**Issue by Paygran** [casbin/casbin#1368]
**Describe the bug**
Call `GetRolesForUser("userId")` raises nil error.

**To Reproduce**
1. Use [RBAC with conditions](https://casbin.org/docs/rbac-with-conditions).
2. After build `Enforcer` instance, call `GetRolesForUser("userId")`

**Expected behavior**
A nil error will be raised.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Go Version: 1.21.6
 - Casbin Version: 2.82.0

**Comment by Paygran** [comment]
`Enforcer.model["g"]["g"].RM` is nil

**Comment by MuZhou233** [comment]
Hi @Paygran , I'm getting to handle this, could you provide a model definition that could reproduce this? (The one you used to initialize `Enforcer`)

**Comment by Paygran** [comment]
> Hi @Paygran , I'm getting to handle this, could you provide a model definition that could reproduce this? (The one you used to initialize `Enforcer`)

Same as Cabin Doc:
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _, (_, _)

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Comment by MuZhou233** [comment]
Relate #1294
