### ISSUE TITLE
How to list inherited permissions by father role?

### ISSUE THREAD

**Issue by g0194776** [casbin/casbin#137]
Hi guys,

I am a new user of Casbin, I have some confusions about the role inheritance with RBAC model. For example:

If I have two roles just like that:
`role:admin`  --> has permission: resource1, read
`role:area_admin` --> which inherited by `role:admin` and has permission: resource2, write

I expected that using role name(role:admin) can list all of sub permissions, the result has 2 rows:
- permission: resource1, read
- permission: resource2, write

BUT now, what I listed just ONLY one row in result: `permission: resource1, read` by golang API.

why?

**Comment by hsluoyz** [comment]
I have added a new function in RBAC API called ``GetImplicitPermissionsForUser()``. It can retrieve all implicit permissions, see example here: https://github.com/casbin/casbin/commit/6dde83be5ec2460ddc42cdcc7cd6b19139adf961

**Comment by g0194776** [comment]
@hsluoyz thank you.

**Comment by g0194776** [comment]
@hsluoyz 

It isn't my expected result.  WHY？
![image](https://user-images.githubusercontent.com/2182076/46571880-93be9280-c9af-11e8-8d10-ec879d408141.png)

**Comment by hsluoyz** [comment]
Can you post your ``main()`` body here? So I can copy and test it.

**Comment by g0194776** [comment]
@hsluoyz OK.

## code
```go
package main

import (
	"fmt"
	"github.com/casbin/casbin"
)

func main() {
	e := casbin.NewEnforcer("/Users/kevinyang/Documents/golang/src/test.io/casbin/model.conf", "/Users/kevinyang/Documents/golang/src/test.io/casbin/policy.csv")
	//admin
	e.AddPermissionForUser("role:admin", "ad_campaign", "GET")
	e.AddPermissionForUser("role:admin", "ad_campaign", "LIST")
	//area-admin
	e.AddPermissionForUser("role:area_ad_admin", "campaign", "WRITE")
	e.AddPermissionForUser("role:area_ad_admin", "adgroup", "WRITE")
	e.AddPermissionForUser("role:area_ad_admin", "adcreative", "WRITE")
	//assigns role of area_ad_admin to admin.
	e.AddRoleForUser("role:admin", "role:area_ad_admin")

	//end users.
	e.AddRoleForUser("kevin", "role:admin")
	e.SavePolicy()

	//print.
	fmt.Printf("%#v", e.GetImplicitPermissionsForUser("kevin"))
}
```


## model.conf

```conf
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && r.act == p.act
```

**Comment by hsluoyz** [comment]
It has been fixed, see: https://github.com/casbin/casbin/commit/3e0da645c8d5fff7bb406408e453e5a3383872fc

**Comment by g0194776** [comment]
@hsluoyz 

The bug fix code has been tested successfully. Thanks a lot.

**Comment by g0194776** [comment]
@hsluoyz 

The bug fix code has been tested successfully. Thanks a lot.
