### ISSUE TITLE
How to define a casbin model with actions implied by relationships between objects?

### ISSUE THREAD

**Issue by mnbbrown** [casbin/casbin#138]
How would you define a casbin model in scenarios where a role on one particular object implies a role on another object?

For example, user has role "Administrator" on resource "Group X" implies that user has role "Viewer" on resource "User" but only if "User" is a member of "Group X". 

Or is this something that should managed at an application level by generating policies dynamically?

**Comment by hsluoyz** [comment]
You can use ``RBAC with resource roles`` (aka ``g2``) to express ``User`` has resource role: ``Group X``. Then we can make ``Administrator`` has viewer access to ``Group X``. 

https://casbin.org/docs/en/supported-models

```
p, Administrator, Group X, admin
p, Administrator, Group X, viewer

g, alice, Administrator
g2, User, Group X
```

**Comment by hsluoyz** [comment]
Closed as stale.
