### ISSUE TITLE
[Question] Establish rules of users of different organizations visibility

### ISSUE THREAD

**Issue by taksedo** [casbin/casbin#1380]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
We have users from two organizations.
By default users shall see each other if they are from the same organization.
If users are from different organizations then org1user1 shall see org2user1 only if active contract between org1 and org2 exists (policy has string about relation between two organizations) and if user of 1st org has permissive role in 2nd org.
**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.obj, p.sub) 
```

**Your policy:**

```
p, org::org2, org::org1, read //contract is active
p, org::org1, org::org2, read //contract is active
p, org::org3, org::org3, read //just to allow users from org3 to see each other

// spred users between orgs
g, org1user1, org::org1
g, org1user2, org::org1
g, org2user1, org::org2
g, org2user2, org::org2
g, org3user1, org::org3
g, org3user2, org::org3

// establish permissive roles
g2, org::org1, role::org1::read_users //permissive role of org1
g2, org::org2, role::org2::read_users //permissive role of org2
g2, role::org1::read_users, read //permissive role has permission to read
g2, role::org2::read_users, read //permissive role has permission to read

// assigne users to permissive roles
g2, org1user1, role::org2::read_users // org1user1 allowed to read users from org2
//org2user1 not allowed to read users from org2
```

**Your request(s):**

```
# users from one company
org1user1, org1user2, read ---> true (expected: true)
org1user2, org1user1, read ---> true (expected: true)
org2user1, org2user2, read ---> true (expected: true)
org2user2, org2user1, read ---> true (expected: true)
org3user2, org3user1, read ---> true (expected: true)
org3user1, org3user2, read ---> true (expected: true)
#users from different companies with contract (policy)
org1user1, org2user1, read #user has permission to read ---> true (expected: true) 
org2user1, org1user1, read #user doesn't have permission to read  ---> true (expected: false)
#users from different companies without contract (policy)
org3user1, org1user1, read #orgs don't have active contract ---> true (expected: false)
```

**Comment by hsluoyz** [comment]
@taksedo what's your question? (what you expect and what you get)

**Comment by taksedo** [comment]
@hsluoyz as described in first post I need to establish visibility between users depend on their organization. 

If they are from the same organization then they shall see each other. 

If they are from different organization they shall see each other only if active contract exists.

**Comment by hsluoyz** [comment]
@taksedo I don't think this is an authorization question

**Comment by taksedo** [comment]
@hsluoyz definition from [Wikipedia](https://en.wikipedia.org/wiki/Authorization#:~:text=Authorization): Authorization or authorisation (see spelling differences) is the function of specifying access rights/privileges to resources, which is related to general information security and computer security, and to access control in particular.[1] More formally, "to authorize" is to define an access policy. So I am not agree that is not authorization question.

Morover I find they way with custom function:
```rust
// test stab
pub fn is_active_contract_exists(sub_org: ImmutableString, obj_org: ImmutableString) -> bool {
    let orgs_with_contract = ["org::org1".into(), "org::org2".into()];
    orgs_with_contract.contains(&sub_org)
        && orgs_with_contract.contains(&obj_org)
        && sub_org != obj_org
}
```

Is it the only way to leverage my purpose?
