### ISSUE TITLE
[Question] Effects are ignored for any policy/request other than the first one

### ISSUE THREAD

**Issue by sophiebella28** [casbin/casbin#1383]
I have a model file with multiple scenarios in it. I want to use the eft parameter in my second policy definition rule. However, I find that the deny effect is ignored when used on any rule other than the first one. The scenario below is a dummy example to illustrate this:

```ini
[request_definition]
r = test_name
r2 = test_name
r3 = test_name
r4 = test_name

[policy_definition]
p = test_name, eft
p2 = test_name, eft
p3 = test_name, eft
p4 = test_name, eft

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))
e2 = some(where (p.eft == allow)) && !some(where (p.eft == deny))
e3 = some(where (p.eft == allow)) && !some(where (p.eft == deny))
e4 = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = r.test_name == p.test_name 
m2 = r2.test_name == p2.test_name 
m3 = r3.test_name == p3.test_name 
m4 = r4.test_name == p4.test_name 

```

**Your policy:**

```
p, test1, allow
p, test2, deny

p2, test1, allow
p2, test2, deny

p3, test1, allow
p3, test2, deny

p4, test1, allow
p4, test2, deny
```

**Your request(s):**

With r, p, e, m
```
test1 -> true (as expected)
test2 -> false (as expected)
```

With r2, p2, e2, m2
```
test1 -> true (as expected)
test2 -> true (NOT as expected )
```
The behaviour for the second scenario also applies for the third and fourth scenarios in my model as well.

The documentation appears to indicate that this should be possible - please could you advise on what I'm doing wrong, or if this is a bug? I've been testing this using the online editor

**Comment by sophiebella28** [comment]
I have realised that I was actually facing this issue in node-casbin, not in the go implementation, and I have opened and closed an issue in that repo to correct this. Not sure if this is an issue here as well, but I'll close this issue for now.

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casbin/node-casbin/issues/474
