### ISSUE TITLE
[Question]update user roles failed

### ISSUE THREAD

**Issue by daijiezou** [casbin/casbin#1388]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Your answer here

**Your model:**

```ini
[request_definition]
r = sub, obj

[policy_definition]
p = sub, obj

[role_definition]
g = _, _


[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub,p.sub) && keyMatch2(r.obj,p.obj)

```

**Comment by daijiezou** [comment]
I set redis watcher for casbin,when redis service crash, casbin delete user report error,but the user is deleted successful
This is an operation to update a user role. Subsequent operations to add a role for the user cannot be performed properly, and the previous operations to delete the user cannot be rolled back. What should I do in this case

**Comment by hsluoyz** [comment]
@daijiezou plz provide reproduce steps and code example

**Comment by daijiezou** [comment]
> @daijiezou plz provide reproduce steps and code example
`
step1: delete the role owned by the original user
if _, err := mycasbin.Casbin().DeleteUser(strconv.Itoa(roleId)); err != nil {
        return
}

step2: update the roles owned by the user
_, err = mycasbin.Casbin().AddRolesForUser(strconv.Itoa(roleId), req.PermissionList)
if err != nil {
	return
}
mycasbin.Casbin() is a enforcer instance

`

**Comment by daijiezou** [comment]
> @daijiezou plz provide reproduce steps and code example


`
step1: delete the role owned by the original user
if _, err := mycasbin.Casbin().DeleteUser(strconv.Itoa(roleId)); err != nil {
return
}

step2: update the roles owned by the user
_, err = mycasbin.Casbin().AddRolesForUser(strconv.Itoa(roleId), req.PermissionList)
if err != nil {
return
}
`
mycasbin.Casbin() is a enforcer instance

**Comment by daijiezou** [comment]
> @daijiezou plz provide reproduce steps and code example
step1: delete the role owned by the original user
if _, err := mycasbin.Casbin().DeleteUser(strconv.Itoa(roleId)); err != nil {
return
}

step2: update the roles owned by the user
_, err = mycasbin.Casbin().AddRolesForUser(strconv.Itoa(roleId), req.PermissionList)
if err != nil {
return
}

mycasbin.Casbin() is  a enforcer instance

**Comment by daijiezou** [comment]
### code example:

mycasbin.Casbin() is a enforcer instance

// step1: delete the role owned by the original user
if _, err := mycasbin.Casbin().DeleteUser(strconv.Itoa(roleId)); err != nil {
	return
}


// step2: update the roles owned by the user
_, err = mycasbin.Casbin().AddRolesForUser(strconv.Itoa(roleId), req.PermissionList)
if err != nil {
	return
}

**Comment by MuZhou233** [comment]
@daijiezou You can use the first return value to check whether the function has effect to roles. When the function returns true with error, it means the function is partially succeed (e.g. the watcher crashed).

https://github.com/casbin/casbin/blob/71c8c84e300cf8b276f28e21e555a39ad793d65c/rbac_api.go#L83-L85

@hsluoyz Maybe we can define a global error to divide the watcher error from others.
