### ISSUE TITLE
How to represent ANONYMOUS access authorization?

### ISSUE THREAD

**Issue by CathySha** [casbin/casbin#139]
I'm trying to use casbin to control the access of a website.
So I write model and policy like this:
Model:
```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act, eft

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = (g(r.sub, p.sub, r.dom) && r.dom == p.dom && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)) || r.sub == "root" 
```

Policy:
```csv
p, ns_admin, namespace1, /alice_data/*, GET, allow
p, developer, namespace1, /cathy_data, (GET)|(POST), allow
p, sys_admin, default, /alice_data/resource2, GET, allow
p, developer, namespace1, /alice_data/resource1, POST, deny

g, alice, ns_admin, namespace1
g, bob, developer, namespace1
g, alice, sys_admin, default
g, alice, group1, default
g, bob, group2, default
g, group1, group2, default
```
However, some urls are ANONYMOUS, aka everyone can access the url.
But I don't want to put each sub into a group named anonymous, because there are so many users.
How can I achieve this effect?
Is there any keyword like ALL for sub?
Thank you very much!

**Comment by hsluoyz** [comment]
You can change your matcher to:

```
[matchers]
m = ((g(r.sub, p.sub, r.dom) || p.sub == "ANONYMOUS") && r.dom == p.dom && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)) || r.sub == "root" 
```

``p.sub == "ANONYMOUS"`` will match every request if the policy rule is for ``ANONYMOUS``.

**Comment by CathySha** [comment]
@hsluoyz thank you for your answer.
And I also have another question: can I seperate policies p and g in two different files? 
Because there are so many users and policies, if I put them all together, the file will have so many lines.

**Comment by hsluoyz** [comment]
The built-in ``File Adapter`` loads p and g from one single file. You can implement your own adapter to load from two files: https://casbin.org/docs/en/policy-storage#use-your-own-storage-adapter

**Comment by hsluoyz** [comment]
Closed as stale.
