### ISSUE TITLE
[Question] get matched role from user?

### ISSUE THREAD

**Issue by tulequ** [casbin/casbin#1391]
**What's your scenario? What do you want to achieve?**
I want to define a policy like `p, role:svc/{id}, svc/{id}, read` and two id must equal to allow
In case use role as subject, it is ok
But when use user alice, it is not, because r.sub in `keyGet3(r.sub, p.sub, 'id')` is alice, not `role:...`
Is there anyway to get matched role from r.sub?
If not, is there anyway other than define each policy per service?

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyGet3(r.obj, p.obj, 'id') == keyGet3(r.sub, p.sub, 'id') && keyMatch3(r.obj, p.obj) && r.act == p.act
```

**Your policy:**

```
p, role:svc/{id}, svc/{id}, read
g, alice, role:svc/111
```

**Your request(s):**

```
role:svc/111, svc/111, read ---> true
alice, svc/111, read ---> false (expected: true)
```

**Comment by hsluoyz** [comment]
@tulequ `keyMatch4` is exactly for your case, see docs: https://casbin.org/docs/function/#functions-in-matchers:~:text=go%23L171%2DL196-,keyMatch4,-a%20URL%20path
