### ISSUE TITLE
[Question] Why is the permission check inconsistent

### ISSUE THREAD

**Issue by dhonor-dyj** [casbin/casbin#1394]
After the policy is added, the data is checked. It is found that the check is true at the beginning, false later, and true again a few seconds later
![image](https://github.com/casbin/casbin/assets/71769955/44e52468-a983-4803-8536-5187390b0ae7)

**Comment by MuZhou233** [comment]
@dhonor-dyj Please provide a minimum reproduction.

**Comment by dhonor-dyj** [comment]
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.obj == p.obj && g(r.sub, p.sub) && r.act == p.act

This is the model definition

**Comment by dhonor-dyj** [comment]
The problem is that after you add policies p and g, the user will be checked several times. Not always, but after a few seconds, the user will be checked. The check method is BatchEnforcce().

**Comment by MuZhou233** [comment]
> The problem is that after you add policies p and g, the user will be checked several times. Not always, but after a few seconds, the user will be checked. The check method is BatchEnforcce().

I can't reproduce this problem based on your description. Please provide model(we already have), policy, and code that can reproduce this problem.

**Comment by dhonor-dyj** [comment]
resolved, The reason is that an error occurs when watcher is used for synchronization. Each time the database is changed, the instance is not excluded during synchronization, and the default loadPolicy() function is used to reload the policy during synchronization. During the loading process, a new check fails.
