### ISSUE TITLE
[Question] error: domain should be 1 parameter

### ISSUE THREAD

**Issue by sawman** [casbin/casbin#1398]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
I am trying to implement a policy like in [this link](https://editor.casbin.org/#87DSJTADL) but the error above is shown. What have I implemented wrongly?

The goal is to have a general purpose RBAC model for entity types that I can assign roles to based on specific entities.

**Your model:**

```ini
[request_definition]
r = subject, domain, object, action

[policy_definition]
p = subject, domain, action

[role_definition]
g = _, _
g2 = _, _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.subject, p.subject) && r.domain == p.domain && r.action == p.action || g2(r.subject, r.domain, r.object, p.subject) && r.domain == p.domain && r.action == p.action || g(r.subject, "superuser")
```

**Your policy:**

```
p, admin, account, create
p, admin, permissions, modify
p, owner, workspace, delete
p, owner, workspace, modify
p, owner, workspace, access
p, user, workspace, create

g, admin, owner
g, admin, user
g, owner, user
g, raymond, superuser
g, sharifah, admin
g, wati, user
g2, wati, workspace, klia2, owner
g2, matthew, workspace, klia2, user
```

**Your request(s):**

```
wati, workspace, klia2, access
```

**Comment by hsluoyz** [comment]
@sawman `g` with 4 params (g2 = _, _, _, _) is not supported. Only 2 or 3 params are supported.

See docs: https://casbin.org/docs/rbac-with-domains

**Comment by pi-nuts** [comment]
It seems like it is now possible to use 4 components in a role_definition when using Go engine - see:
https://github.com/casbin/jcasbin/issues/455
