### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by ideahitme** [casbin/casbin#14]
Sorry for creating this issue, but just a reminder to bump the version once migration to `casbin` organisation is done. The problem is that current `go` dependency managers won't work correctly with `github.com/casbin/casbin`, as it will use latest version by default `0.5.0` which still refers to old repository location.

Thanks for great library :)

**Comment by hsluoyz** [comment]
Thanks for the report! First time to know about such an issue, didn't quite use a dep manager before:)

I have just released **casbin 0.0.6** based on the latest master.
