### ISSUE TITLE
How to combine RBAC and  RBAC with domains

### ISSUE THREAD

**Issue by CathySha** [casbin/casbin#140]
Expected:
Groups and sys_admin have no domain.
Ns_admin and developer depend on domain.

Model:
```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act, eft

[role_definition]
g = _, _, _
g2 = _,_

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = (((g(r.sub, p.sub, r.dom) || g2(r.sub, p.sub)) || p.sub == "ANONYMOUS") && r.dom == p.dom && (keyMatch(r.obj, p.obj) || keyMatch2(r.obj, p.obj)) && regexMatch(r.act, p.act)) || r.sub == "root" 
```

Policy:
```csv
p, ANONYMOUS, default, /login, (GET)|(PUT)|(PATCH)|(DELETE)|(POST)|(OPTIONS), allow
p, ns_admin, :namespace, /namespaces/:namespace/maintain, (GET)|(PUT)|(PATCH)|(DELETE)|(POST)|(OPTIONS), allow
p, sys_admin, default, /sys/*, (GET)|(PUT)|(PATCH)|(DELETE)|(POST)|(OPTIONS), allow
p, developer, :namespace, /namespaces/:namespace/status, (GET)|(PUT)|(PATCH), allow
p, ANONYMOUS, default, /namespaces, (POST)|(DELETE), deny

g, group1, ns_admin, namespace1
g, group2, developer, namespace1
g2, alice, sys_admin
g2, alice, group1
g2, bob, group2
g2, group1, group3
```

When inputs are:
```
sub: alice
dom: namespace1
obj: /namespaces/namespace1/maintain
act: POST
```
The expected result is true.
But it always comes out to be false.
How should I get the expected result?
Thank you very much!

**Comment by hsluoyz** [comment]
``r.dom == p.dom`` doesn't hold.

**Comment by hsluoyz** [comment]
When you match request's ``/namespaces/namespace1/maintain`` with policy's ``/namespaces/:namespace/maintain``, Casbin only determines whether it matches, it doesn't parse out the variable like: ``:namespace = namespace1``, then use this information in comparison of other fields. Casbin will only literally compare ``:namespace`` with ``namespace1`` and it simply returns false.

If you want to make Casbin work for your scenario, you should define a custom function such as ``parseNamespaceOut()``, then use it in matcher like:

```
m = parseNamespaceOut(r.obj, p.obj) == r.dom
```

So ``parseNamespaceOut()`` will parse out ``namespace1`` from ``r.obj`` and ``p.obj``, then compare it with ``r.dom``.

**Comment by hsluoyz** [comment]
Let me know if you have further issues.
