### ISSUE TITLE
[Question] loading policies from two places

### ISSUE THREAD

**Issue by sawman** [casbin/casbin#1400]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
I am trying to have policies in two places. In the example below, I want to store p and part of g in a file, and the rest of g and g2 in a database. Future calls to addPolicy or savePolicy should only save new policies to the database. Can this be done?

**Your model:**

```ini
[request_definition]
r = subject, object, action
r2 = subject, object, action

[policy_definition]
p = subject, object, action

[role_definition]
g = _, _
g2 = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.subject, p.subject) && r.object == p.object && r.action == p.action || g(r.subject, "superuser")

m2 = g(r2.subject, p.subject) && p.object == "workspace" && r2.action == p.action || g2(r2.subject, r2.object, p.subject) && p.object == "workspace" && r2.action == p.action || g(r2.subject, "superuser")

```

**Your policy:**

File policy
```
p, admin, account, create
p, admin, permissions, modify
p, admin, workspace, delete
p, admin, workspace, modify
p, admin, workspace, access
p, user, workspace, create
p, ws_user, workspace, access
g, admin, user
```

Policy in db
```
g, user1, admin
g, user2, user
g2, user1, workspace1, admin
```

**Comment by hsluoyz** [comment]
@sawman call Adapter API: https://casbin.org/docs/policy-storage#adapter-details by yourself. Or implement a custom adapter
