### ISSUE TITLE
How to configure group rule in the "matchers" config

### ISSUE THREAD

**Issue by glenson** [casbin/casbin#141]
this is my configuration:
```ini
[request_definition]
r = dom, sub, obj, act

[policy_definition]
p = dom, sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.dom == p.dom && (g(r.sub, p.sub) || g(r.dom, p.dom)) && r.obj == p.obj && (r.act == p.act || p.act == "*")

```
My data:
![image](https://user-images.githubusercontent.com/822127/46778049-7d645e00-cd44-11e8-99ca-814b33140710.png)

My request :
`$boo = $policy->allows('glenson', 'aiias', 'data.info.2', 'r');`

I want it to return **true** but its not happening since 'glenson' is not in the policy.
Yet as you could see in the data 'glenson' is part of the admin group, which in in the policy list.

Is there any thing I'm missing or wrong setting in my "matchers" config to make it work?
Or do I really have to loop throughout the groups of the user, to make it work?

Thanks...

**Comment by hsluoyz** [comment]
Request definition: ``r = dom, sub, obj, act`` in the model file corresponds to the parameters in ``Enforce()``. You didn't follow the same order. In ``r``, you make ``dom`` first. But in the call, you make ``glenson`` first.

**Comment by glenson** [comment]
It works... I appreciate your help.
God bless you.
