### ISSUE TITLE
[Question] call NewEnforcer get error "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by llovvoll** [casbin/casbin#1418]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

I have ptype, v0, v1, v2, v3, v4, v5 fields in my casbin table. If I only use ptype, v0, v1, v2 fields everything works fine, but I want to use v3, v4, v5 as Notes fields, the program will crash whenever these fields have values.
I have tried many methods and searched a lot of information but can't solve it. any suggestions? thanks

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && ParamsMatch(r.obj,p.obj) && ParamsActMatch(r.act,p.act) || p.sub == "2"
```

**Your policy:**

```
p, 1, /api/v1/system/*, GET, admin
```

**Comment by hsluoyz** [comment]
@llovvoll it should be your own issue.

**Comment by llovvoll** [comment]
> @llovvoll it should be your own issue.

Thank you so much. It's my own issue, the problem is my configuration, it's solved after adjustment.
