### ISSUE TITLE
How to get the inheritance tree for UI display?

### ISSUE THREAD

**Issue by nengc** [casbin/casbin#142]
I want to show the role inheritance , but can not find any function to get the inheritance detail. Any advice? Thanks!

**Comment by hsluoyz** [comment]
You can get the role relationship in ``allRoles`` of the following code:

https://github.com/casbin/casbin/blob/3e0da645c8d5fff7bb406408e453e5a3383872fc/rbac/default-role-manager/role_manager.go#L25-L29

If you cannot access it, you can subclass the default role manager, then get your information in your role manager.

**Comment by hsluoyz** [comment]
Closed as stale.
