### ISSUE TITLE
[Bug] Node.js and Golang Casbin Do Not Behave The Same with Glob Matching **

### ISSUE THREAD

**Issue by rrshen** [casbin/casbin#1422]
**Describe the bug**
Golang Casbin does not support ** in globMatch. The online editor at https://casbin.org/editor/ uses Node.js Casbin which does support using the ** syntax to match any number of directories. This is misleading because the https://casbin.org/ website explicitly states that "all implementations share the same API and behaviors". 

I believe the source of the issue is that node-casbin uses a third-party matcher that supports ** for [globMatch](https://github.com/casbin/node-casbin/blob/b2cbdc6d8600a7cf388f6cf04d30063075474af9/src/util/builtinOperators.ts#L317) whereas casbin uses the `path` package's Match function which does not support ** for [globMatch](https://github.com/casbin/casbin/blob/c52a9b5fc5b721e078f411452cb66518c31110e2/util/builtin_operators.go#L372). 

I did a little searching online, and I believe that [doublestar](https://pkg.go.dev/github.com/bmatcuk/doublestar) is meant to be like path.Match() with **. Would it be possible to replace the `return path.Match(key2, key1)` on line 373 of casbin/util
/builtin_operators.go with the doublestar version of Match()? I believe that this would address my problem with the Golang implementation of Casbin not supporting ** the way the Node.js verison does.

**To Reproduce**
1. Paste the following model into the online editor and a model file named "model.conf":

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && globMatch(r.obj, p.obj)
```

2. Paste the following policy into the online editor and a policy file named "policy.csv":

```
p, alice, /alice_data/**, *

p, bob, /**, *
```

3. Paste the following requests into the online editor:

```
alice, /alice_data/hello, GET
alice, /alice_data/hello/and/goodbye, GET
bob, /alice_data/hello, GET
```

4. Run the following block of code using the most recent Golang implementation of Casbin (v2.98.0 at the time of writing this):

```
e, err := casbin.NewEnforcer("model.conf", "policy.csv")
if err != nil {
    printf("Error initializing Casbin enforcer: %s", err.Error())
}

user := "alice"
resource := "/alice_data/hello"
operation := "GET"

accessible, reason, err := e.EnforceEx([]interface{}{user, resource, operation})
if err != nil {
    printf("Error enforcing access: %s", err.Error())
} else {
    printf("%s is allowed to access %s to perform a %s operation: %v due to %v", user, resource, operation, accessible, reason)
}

user = "alice"
resource = "/alice_data/hello/and/goodbye"
operation = "GET"

accessible, reason, err = e.EnforceEx([]interface{}{user, resource, operation})
if err != nil {
    printf("Error enforcing access: %s", err.Error())
} else {
    printf("%s is allowed to access %s to perform a %s operation: %v due to %v", user, resource, operation, accessible, reason)
}

user = "bob"
resource = "/alice_data/hello"
operation = "GET"

accessible, reason, err = e.EnforceEx([]interface{}{user, resource, operation})
if err != nil {
    printf("Error enforcing access: %s", err.Error())
} else {
    printf("%s is allowed to access %s to perform a %s operation: %v due to %v", user, resource, operation, accessible, reason)
}
```

**Expected behavior**
The online Casbin editor's enforcement result will say:
```
true Reason: ["alice","/alice_data/**","*"]
true Reason: ["alice","/alice_data/**","*"]
true Reason: ["bob","/**","*"]
```
Whereas the Golang Casbin will print something like:
```
alice is allowed to access alice_data/hello to perform a GET operation: true due to [alice /alice_data/** *]
alice is allowed to access alice_data/hello/and/goodbye to perform a GET operation: false due to []
bob is allowed to access alice_data/hello to perform a GET operation: false due to []
```

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: Chrome
 - Version: 22H2

**Comment by hsluoyz** [comment]
@rrshen can you make a PR?

**Comment by rshen-tibco** [comment]
I will; I'm working on getting an OK for the Contributor's License Agreement at the moment.
