### ISSUE TITLE
[Bug] AddPoliciesEx does not take effect

### ISSUE THREAD

**Issue by baiyetao** [casbin/casbin#1423]
**Describe the bug**
I am trying to add policies by using AddPoliciesEx. However, I encountered two situations, when the table did not have a unique index on ['ptype', 'v0', 'v1', 'v2', 'v3', 'v4', 'v5'], all the policies were written successfully and when there is a unique index, of course, the write fails.

I am using github.com/casbin/gorm-adapter/v3 as the adapter and postgresql as the database.

**To Reproduce**
Here is my model.

```text
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && r.act == p.act
```

Here are my policies and code.

```golang
policies := [][]string{{"idea-reader", "/ideas/:ideaId", "GET"},{"idea-writer", "/ideas/1", "PUT"}}
flag, err = client.AddPoliciesEx(policies)
if err != nil {
    logger.ErrorWithTrace(log, ctx, "Create ApiPolicies Failed, apiPolicies：%s。Error：%s。", json.MarshalToString(apiPolicies), err.Error())
    err = errors.Join(ErrCreateApiPolicies, err)
    return
}
```

**Expected behavior**
The expected behavior of AddPoliciesEx is to only add non-existent policies to the storage, avoiding duplication.

**Comment by hsluoyz** [comment]
@baiyetao can you make a PR?

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/gorm-adapter/pull/243
