### ISSUE TITLE
[Bug] AddGroupingPolicy does not return false with duplicate policy

### ISSUE THREAD

**Issue by Henelik** [casbin/casbin#1429]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
AddGroupingPolicy does not return `false` when adding a duplicate grouping policy.

**To Reproduce**
1. Use a model with a group definition
2. Run the following code
4. See AddGroupingPolicy returns true twice

```
package main

import (
	"fmt"

	"github.com/casbin/casbin/v2"
)

func main() {
	e, _ := casbin.NewEnforcer("./model.conf", "./policy.csv")

	added, _ := e.AddGroupingPolicy("user", "admin")

	fmt.Println("first added", added)

	added, _ = e.AddGroupingPolicy("user", "admin")

	fmt.Println("second added", added)
}
```

**Expected behavior**
AddGroupingPolicy should return true the first time, and false the second per the documentation.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.2 Cinnamon
 - Browser: N/A
 - Version: v2.97.0

**Comment by hsluoyz** [comment]
@Henelik can you make a PR?

**Comment by Henelik** [comment]
@hsluoyz I spent a couple hours trying to fix the issue, and didn't get to the bottom of it.  I can't afford to spend any more time on this at the moment.

**Comment by hsluoyz** [comment]
@Henelik the affected means the policy is there NOW. Use HasGroupingPolicy to decide whether it exists before.

**Comment by Henelik** [comment]
@hsluoyz that doesn't match AddGroupingPolicy's docstring, and t doesn't make sense to return a bool from AddGroupingPolicy if that's the case.  The bool would always be true because the policy would always exist, unless AddGroupingPolicy errored.

The docstring should be updated, or this should be considered a bug.

https://github.com/casbin/casbin/blob/a98973beed58c2236ee453a126970f00d68c0f34/enforcer_synced.go#L477-L480

**Comment by hsluoyz** [comment]
@Henelik the boolean return value means `isAffected`. So if the policy doesn't change after this call, it will be false.

If it's not this behavior, then it's a bug. Can you make a PR if this is the case?

**Comment by Henelik** [comment]
@hsluoyz right, this is not the current behavior.

I can get approval at work to make a PR, if you re-open the issue.
