### ISSUE TITLE
Puzzled after view the code of "https://github.com/casbin/web-ui"

### ISSUE THREAD

**Issue by nengc** [casbin/casbin#143]
The model in "web-ui" was like below:
![image](https://user-images.githubusercontent.com/19792047/46801313-e8398780-cd8c-11e8-8192-4f2e1360c0ef.png)
And "domain/tenant" at the first position, and "service" at the end position.

But in the online editor was like this:
![image](https://user-images.githubusercontent.com/19792047/46801342-00a9a200-cd8d-11e8-8778-f4d79e46ac21.png)
There was not  "service" at the end position and "domain/tenant" at the second position. 
So the two cases are all right or only one is right ? And what is the "service" meaning? 
Thanks!

**Comment by hsluoyz** [comment]
Both are right. The variable names or order do not matter. You can use any name you want, like changing ``dom`` to ``domain``, or ``tenant``, or anything else. You can view them as the variables in a language like Golang. For Casbin model, there are only 3 rules:

1. The order of arguments in ``Enforce()`` call should match the order of elements in ``[request_definition]``.
2. The order of policy rule elements (e.g., in a .csv file, or columns in a database table) should match the order of elements in ``[policy_definition]``.
3. The variables used in ``[matchers]`` should already be defined in either ``[request_definition]`` or ``[policy_definition]``.

**Comment by nengc** [comment]
Hi @hsluoyz , thanks for your replying. But another question, how the function "GetRolesForUserInDomain" work? In my case, i call the function "GetRolesForUserInDomain" , and get nothing. below is my code:
![image](https://user-images.githubusercontent.com/19792047/46842380-de9d3780-cdff-11e8-8e0b-8db4bd954a70.png)
![image](https://user-images.githubusercontent.com/19792047/46842392-e65cdc00-cdff-11e8-914b-02e915cd558d.png)
Thanks again!

**Comment by hsluoyz** [comment]
``GetRolesForUserInDomain()`` is used to retrieve ``g`` policy rules with three elements, for example:

```
g, user4, admin, domain1
```

You should use ``GetRolesForUser()`` instead.

**Comment by nengc** [comment]
@hsluoyz Oh, get it! And what is the max length of the elements? Limited or else?
Thanks!

**Comment by hsluoyz** [comment]
No limitation for Casbin, you can follow the Golang limitation.

**Comment by nengc** [comment]
Get it, Thanks again!
