### ISSUE TITLE
[Question] How can I get user all permissions with g2

### ISSUE THREAD

**Issue by RogersLei** [casbin/casbin#1430]
Background
`Node-casbin:  5.30.0`
`casbin: v2.98.0`

Want to get user permissions in resource with implicit use getImplicitResourcesForUser('alice') or getImplicitPermissionsForUser('alice') to get alice permissions in data2, but both are only return [[alice, data1, ALL, 15]]

Model
```
[request_definition]
r = sub, obj, attr, act

[policy_definition]
p = sub, obj, attr, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && r.attr == p.attr && r.act == p.act
```

Policy
```
p, alice, data1, ALL, 15

g2, data1, data2
g2, data2, data1
```

Request
`alice, data2, ALL, 15`

Result
`true`

This example in editor is worked, but in code can't get permissions with data2.

Expected
```
[[alice, data1, ALL, 15], [alice, data2, ALL, 15]]
```

**Comment by RogersLei** [comment]
In my case, this is very important.
I need to search for and return the permissions for each object, as the frontend will rely on this information to restrict access to pages without the necessary permissions.
If this is not supported, finding each object's relationships and then fetching everyone's permissions will be very slow, which would be too late.

**Comment by hsluoyz** [comment]
@RogersLei see docs: https://casbin.org/docs/data-permissions

You should use `BatchEnforce`
