### ISSUE TITLE
Does casbin work without persist(in memory)? 

### ISSUE THREAD

**Issue by manjunathtr0039** [casbin/casbin#1434]
Hi Team, 

 We are planning to use redis cache for casbin implementation. Casbin always needs to read from cache( not loading from redis to in memory). Is it possible? Do we have any configuration for the same.

**Comment by hsluoyz** [comment]
@manjunathtr0039 give specific code and more details, versions, libs

**Comment by hsluoyz** [comment]
Closed as stale
