### ISSUE TITLE
[Question]How can I make querying authorization by resource more efficient when using wildcards?

### ISSUE THREAD

**Issue by onnttf** [casbin/casbin#1441]
**What's your scenario? What do you want to achieve?**
Hello,
How can I make querying authorization by resource more efficient when using wildcards?
For example, if I grant user1 the permission of `a/*` and then grant user2 the permission `a/1`, how can I query who can access `a/1` more efficiently?

Does the `GetFilteredPolicy` API support wildcards?
Can I use it this way to return who can access a/1?

```go
filteredPolicy := e.GetFilteredPolicy(1, "a/1")
```

**Your model:**

```ini
[request_definition]
r = user, resource, action

[policy_definition]
p = subject, resource, action, begin_time, end_time

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (r.user == p.subject || g(r.user, p.subject)) \
    && keyMatch2(r.resource, p.resource) \
    && actionMatch(r.action, p.action) \
    && timeMatch(p.begin_time, p.end_time)
```

**Your policy:**

```
p, alice, a/*, view, 2024-01-01, 2024-12-31
p, bob, a/1, edit, 2024-01-01, 2024-12-31

p, admin, a/*, manage, 2024-01-01, 2024-12-31
p, viewer, a/1, view, 2024-01-01, 2024-12-31

g, carol, admin
g, david, viewer
```

**Comment by hsluoyz** [comment]
See: https://casbin.org/docs/data-permissions

**Comment by onnttf** [comment]
> See: https://casbin.org/docs/data-permissions

Hi, I saw this, I am not concerned about implicit inheritance.
I want to ask about wildcards, for example:

If I grant user1 the permission of a/* and then grant user2 the permission a/1, how can I query who can access a/1 more efficiently?

**Comment by onnttf** [comment]
@hsluoyz Hi~
