### ISSUE TITLE
How to solve the slow log

### ISSUE THREAD

**Issue by BainDragneel** [casbin/casbin#1443]
**What's your scenario? What do you want to achieve?**
How to solve the slow log
I use github.com/casbin/xorm-adapter/v3  and github.com/casbin/redis-watcher/v2

**My model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.obj == p.obj && g(r.sub, p.sub) && r.act == p.act
```

**My request(s):**

I am using a PostgreSQL table to store policies. After the data in the casbin_rule table exceeds 200,000 entries, loadPolicy causes slow logs, and Enforce becomes very slow as well.

**Comment by hsluoyz** [comment]
@BainDragneel see performance optimization docs: https://casbin.org/docs/performance
