### ISSUE TITLE
Path Parameters with casbin. How to implement

### ISSUE THREAD

**Issue by youngotutu** [casbin/casbin#145]
If I have a resource in the manner : 

http://google.com/token/:idname/editProfile.

Now I only want a user to access the url, only if his username is same with the :idname parameter. How do I implement?...

Thanks

**Comment by hsluoyz** [comment]
You should implement a custom function: https://casbin.org/docs/en/syntax-for-models#how-to-add-a-customized-function, return the parsed ``:idname`` in that function, then compare it with the username in the matcher.

**Comment by hsluoyz** [comment]
Closed as stale.

**Comment by Teut2711** [comment]
> You should implement a custom function: https://casbin.org/docs/en/syntax-for-models#how-to-add-a-customized-function, return the parsed `:idname` in that function, then compare it with the username in the matcher.

Link is dead

**Comment by hsluoyz** [comment]
@Teut2711 see: https://casbin.org/docs/function#how-to-add-a-customized-function
