### ISSUE TITLE
[Bug]enforcer.LoadPolicy() panic because concurrent map iteration and map write

### ISSUE THREAD

**Issue by daijiezou** [casbin/casbin#1453]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
I set up a Redis-based callback, and when the callback occurs I call the reload Policy, which may cause panic

**Screenshots**
<img width="1132" alt="image" src="https://github.com/user-attachments/assets/5adb9ca1-8628-4a28-8efb-52b69438db96">

**Desktop (please complete the following information):**
 - Version：v2.66.1

**Comment by hsluoyz** [comment]
@daijiezou see docs: https://casbin.org/docs/multi-threading
