### ISSUE TITLE
[Question] Listing accessible resources with only inherited permissions

### ISSUE THREAD

**Issue by girlpunk** [casbin/casbin#1457]
**What's your scenario? What do you want to achieve?**
Using the RESTful (KeyMatch) example model as a starting point, would it be possible to query Casbin for all the resources a user has access to? For example, the included policy confirms that `/alice_data/resource2` exists (though in a production policy, not all objects may be explicitly included) and that the alice has access (from the first policy), but resource2 is not explicitly listed for Alice.

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)
```

**Your policy:**

```
p, alice, /alice_data/*, GET
p, alice, /alice_data/resource1, POST

p, bob, /alice_data/resource2, GET
p, bob, /bob_data/*, POST

p, cathy, /cathy_data, (GET)|(POST)
```

**Your request(s):**

```
getResourcesForUser("alice") ---> ["/alice_data/resource1", "/alice_data/resource2", "/alice_data/resource3"]
```

**Comment by hsluoyz** [comment]
@girlpunk see docs: https://casbin.org/docs/data-permissions/
