### ISSUE TITLE
[Question] permission backwards propagation

### ISSUE THREAD

**Issue by cic1988** [casbin/casbin#1461]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

When using casbin RBAC model with resource role, I could propagate the permissions for both hierarchical groups and resources. I am stuck in the scenario of "list" permission.

See the policy below. The resource hierarchy looks like:

```
root_group:
   -> data_group_1
       -> data1 (group1)
       -> data2
   -> data_group_2
```

If I assign group1 write permission to data1, how could the data1 user list the resource "data_group_1" when they click on the "root_group" on top level?

In general the question is about is there any suggestion on such "backwards" propagation case? Thanks.

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && r.act == p.act
```

**Your policy:**

```
p, group1, data1, write

g, alice, group1
g, bob, group1
g, lee, group2

g2, data1, data_group_1
g2, data2, data_group_1
g2, data3, data_group_2
g2, data_group_1, root_group
g2, data_group_2, root_group
```

**Comment by hsluoyz** [comment]
@cic1988 see Role Hierarchy docs: https://casbin.org/docs/rbac#role-hierarchy
