### ISSUE TITLE
[Question] subjectPriority

### ISSUE THREAD

**Issue by ValeraKorovelkov** [casbin/casbin#1464]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
I'm not sure if it's a bug or I just don't understand how subjectPriority works. I get two different results when I run the model with different amounts of users.

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft     #sub can't change position,must be first

[role_definition]
g = _, _

[policy_effect]
e = subjectPriority(p.eft) || deny

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Your policy:**
Policy with 2 users
```
p, admin, data1, write, deny
p, admin, data2, read, allow
p, bob, data2, write, allow
p, alice, data1, write, allow

g, alice, admin
```
Policy with 1 user
```
p, admin, data1, write, deny
p, admin, data2, read, allow
p, alice, data1, write, allow

g, alice, admin
```

**Your request(s):**
With 2 users
```
Request: alice, data1, write ---> false 
```
With 1 user
```
Request: alice, data1, write ---> true
```

Is it expected behavior? Seems odd to me

**Comment by hsluoyz** [comment]
@ValeraKorovelkov see the example, see how it works. And ask AI: https://ai.casbin.com/

**Comment by ValeraKorovelkov** [comment]
@hsluoyz AI doesn't work and i got this policy and model from the list of examples, so your suggestion is not very helpful.
<img width="893" alt="image" src="https://github.com/user-attachments/assets/3d2c5a6a-3b3b-4ec3-8dc2-53f0d275ce21">

**Comment by hsluoyz** [comment]
@ValeraKorovelkov it's now fixed. Plz try again
