### ISSUE TITLE
need help with some model

### ISSUE THREAD

**Issue by vtolstov** [casbin/casbin#147]
I'm try to experiment with models in casbin that suitable for me.
Now i'm try to do something like this:

1) I have request with tenant, zone, service, method, action, resource
tenant belongs to zone, or to all zones (*)
for easy example: service = central, method = AccountService with action Auth or NotifyService with action send
tenant may be empty for some method and action like AccountService Auth
resource is * or concrete resource that looks like uuid.

2) to minimize policy lines i want to have default groups like
zone_users
zone_admins
zone_managers
superadmins

each tenant belongs to group or not.and have or not additional perms.
if it belongs to specific group it inherit permissions.
for each zone tenant have different permissions on the same service method action.
policy needs to be with priority to have like firewall rules.
superadmins have all rights on all zones and resources.

As i understand this is rbac + rbac with domains + rbac with tenants + abac

**Comment by vtolstov** [comment]
```
[request_definition]
r = tenant, zone, service, method, action, resource

[policy_definition]
p = tenant, zone, service, method, action, resource, eft

[role_definition]
g1 = _, _, _, _, _, _
g2 = _, _

[matchers]
m = (
  (
    (r.tenant == p.tenant) || p.tenant == "*" ||
    (g(r.tenant, p.tenant, r.zone, r.service, r.method, r.action) && g2(r.tenant, p.tenant))
  ) &&
  ((r.zone == p.zone) || p.zone == "*") &&
  ((r.service == p.service) || p.service == "*") &&
  ((r.method == p.method) || p.method == "*") &&
  (p.resource == "*" || keyMatch(r.resource, p.resource)) &&
  ((r.action == p.action) || p.action == "*")
)

```

**Comment by hsluoyz** [comment]
So what is the question?

**Comment by vtolstov** [comment]
Ah sorry =) forget about question.
Question is - how to write matcher to minimize overhead (for example keyMatch2/keyMatch3 uses regexp).

How to deal with groups? As i understand i need group for zone, group for services + method + action and group for group_name, user ?

**Comment by vtolstov** [comment]
```
[request_definition]
r = tenant, zone, service, method, action, resource

[policy_definition]
p = tenant, zone, service, method, action, resource, eft

[role_definition]
g = _, _, _
g2 = _, _
g3 = _, _, _

[policy_effect]
e = priority(p.eft) || deny

[matchers]
m = g2(r.zone, p.zone) && (r.domain == p.domain || p.domain == "*") && r.method == p.method && r.service == p.service && r.action == p.action && (r.resource == p.resource || p.resource == "*")
```

```
g2, user-uuid, zone_users
p, zone_users, *, central, AccountService, Auth, *, allow
```

e.EnforceSafe("user-uuid", "public", "central", "AccountService", "Auth", "*")

says deny

**Comment by hsluoyz** [comment]
``r.domain`` and ``p.domain`` are not defined.

**Comment by vtolstov** [comment]
ah sorry =). thanks. last question - does it possibe to be more verbose on errors and in logs to such cases?

**Comment by hsluoyz** [comment]
I'm just surprised why your code doesn't panic. As I think, Casbin tries to access a non-existent attribute and will cause panic. This panic is currently the best sign to show your errors in Casbin model/policy.

We have plan to provide a syntax & semantic Casbin model/policy checker, but it is still in initial ideas.

**Comment by vtolstov** [comment]
Also i have some strange things if model is invalid EnforcerSafe returns error, but when i'm try to print such error i have null pointer.

**Comment by vtolstov** [comment]
in case of priority , i want to allow Reg action on AccountService only to * (empty user uuid), and deny for registered users with non empty user uuid.

**Comment by vtolstov** [comment]
And if i have about 20 services what is the best - create group for each actions of this services and fill with actions or create group with action as regexp ?

**Comment by vtolstov** [comment]
```
[request_definition]
r = tenant, zone, service, method, action, resource
[policy_definition]
p = tenant, zone, service, method, action, resource, eft
[role_definition]
g = _, _, _
g2 = _, _
g3 = _, _,
[policy_effect]
e = priority(p.eft) || deny
[matchers]
m = (g2(r.tenant, p.tenant) || r.tenant == p.tenant || p.tenant == "*") && \
    (g3(r.action, p.action) || p.action == "*") && \
    (r.zone == p.zone || p.zone == "*") && \
    (r.method == p.method || p.method == "*") && \
    (r.service == p.service || p.service == "*") && \
    (r.action == p.action || p.action == "*") && \
    (r.resource == p.resource || p.resource == "*")
```

```
p, zone_users, public, central, AccountService, account_actions, *, allow
p, guests, public, central, AccountService, Reg, *, allow
p, guests, public, central, AccountService, Auth, *, allow
g2, user-uuid, zone_users
g2, guest, guests
g3, Get, account_actions
```

```
e.EnforceSafe("user-uuid", "*", "central", "AccountService", "Auth", "resource-uuid") --> false
e.EnforceSafe("guest", "*", "central", "AccountService", "Auth", "resource-uuid") --> false
```

**Comment by vtolstov** [comment]
Why this two fails? For my logic it must return true

**Comment by vtolstov** [comment]
If i'm remove in matcher last condition with r.zone == p.zone || p.zone == "*" all works as expected

**Comment by hsluoyz** [comment]
Your ``r.zone`` is ``*``, ``p.zone`` is not ``*``. So of course ``r.zone == p.zone || p.zone == "*"`` doesn't hold.

And please highlight the format of your model and golang code with "```ini" and "```go"

**Comment by vtolstov** [comment]
@hsluoyz thanks!
