### ISSUE TITLE
how to define the 'p' records in different domains?

### ISSUE THREAD

**Issue by CHCP** [casbin/casbin#148]
Hi hsluoyz,
  There is another question. In my project, there are many many domains(products) and users, every domain has about 50  policy records, and the policy records are same except "domain". 
 When I add a new domain(product), I have to copy all policy records and change the domain to different, I do not want do so.  Can I define the same policy records for all domains, only add different 'g' records to effect the policy?  Or Is there a better way to solve the question?

Thanks
Gordon

model file:

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act, eft

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = (g(r.sub, p.sub, r.dom) || p.sub == "Anonymous") && r.dom == p.dom && keyMatch2(r.obj, p.obj) && (r.act == p.act || p.act == "ANY")
```

policy records:

```csv
p, RequirmentAnalyst, 10001, /original-requirements/*, ANY, allow
p, RequirmentAnalyst, 10001, /features/*, ANY, allow
p, RequirmentAnalyst, 10001, /requirements/*, ANY, allow
...

p, RequirmentAnalyst, 10002, /original-requirements/*, ANY, allow
p, RequirmentAnalyst, 10002, /features/*, ANY, allow
p, RequirmentAnalyst, 10002, /requirements/*, ANY, allow
...

p, RequirmentAnalyst, 10003, /original-requirements/*, ANY, allow
p, RequirmentAnalyst, 10003, /features/*, ANY, allow
p, RequirmentAnalyst, 10003,  /requirements/*, ANY, allow
...

g, username1, RequirmentAnalyst, 10001
g, username1, RequirmentAnalyst, 10002
g, username1, RequirmentAnalyst, 10003
```

**Comment by CHCP** [comment]
sorry, I miss the matchers.

**Comment by hsluoyz** [comment]
For the ``p`` records, you can regex to patternize the domain. For example:

Matcher:

```ini
[matchers]
m = (g(r.sub, p.sub, r.dom) || p.sub == "Anonymous") && regexMatch(r.dom, p.dom) && keyMatch2(r.obj, p.obj) && (r.act == p.act || p.act == "ANY")
```

Policy:

```csv
p, RequirmentAnalyst, .*, /original-requirements/*, ANY, allow
p, RequirmentAnalyst, .*, /features/*, ANY, allow
p, RequirmentAnalyst, .*, /requirements/*, ANY, allow
```

``.*`` in the ``p`` records will match all domains in a request based on Regex.

For ``g`` records, currently I'm afraid you have to define them for each domain. Because it does not support regex for now. If you need to support regex in ``g`` records, you can implement your own role manager to support it: https://github.com/casbin/casbin#role-manager

**Comment by CHCP** [comment]
Hi hsluoyz, 
  Thanks for your help. 
I use regex to patternize the domain, yes, it is works. but the real question is:
```
p, RequirmentAnalyst, .*, /features/*, ANY, allow
p, RequirmentAnalyst, .*, /features/*, ANY, allow
p, RequirmentAnalyst, .*, /features/*, ANY, allow

g, username1, RequirmentAnalyst, 10001
g, username2, RequirmentAnalyst, 10002
g, username3, RequirmentAnalyst, 10003
```
username1 belongs to domain 10001, and he only read domain 10001 resources, username2 belongs to domain 10002, and he only read domain 10002 resources, username3 belongs to domain 10003, and he only read domain 10003 resources. When I use regex  to domain, there is no difference.
```
enforcer.Enforce("username1", "10001", "/features*", "GET")---true
enforcer.Enforce("username1", "10002", "/features*", "GET")---true
enforcer.Enforce("username1", "10003", "/features*", "GET")---true
enforcer.Enforce("username3", "10003", "/features*", "GET")---true
```

How I to do to get correct results like this:
```
enforcer.Enforce("username1", "10001", "/features*", "GET")---true
enforcer.Enforce("username1", "10002", "/features*", "GET")---false
enforcer.Enforce("username1", "10003", "/features*", "GET")---false
enforcer.Enforce("username3", "10003", "/features*", "GET")---true
```

**Comment by hsluoyz** [comment]
``g(r.sub, p.sub, r.dom)`` in the matcher can already restrict the domain resources. Take your 2nd example: ``g("username1", "RequirmentAnalyst", "10002")`` will be false, because there's no ``g, username1, RequirmentAnalyst, 10002``. So the final matcher will be false.

**Comment by CHCP** [comment]
I think I use a role Anonymous ,  this role can read every API with method GET, so it could cause some error. I will try another way. Thanks.

**Comment by hsluoyz** [comment]
Please open another issue for it.
