### ISSUE TITLE
Question how to use regex matching in role definition

### ISSUE THREAD

**Issue by ideahitme** [casbin/casbin#15]
Let's say I have a role definition: 
```model.conf
[request_definition]
r = user, group,  path, verb

[role_definition]
g = _, _, _

[matchers]
m = g(r.user, r.group, "admin")
```

and in my policy: 
```policy.csv
g, ideahitme, *, admin
```

so the idea is, if I get a request with user `ideahitme` and **any** group this user should be treated as admin. How would I go about implementing this. I saw `regexMatch` but not sure how it can be invoked in this scenario. I guess I could make it differently by changing `g` semantics to only consider `user` and entirely drop `group`, but is this the only work-around? 

Another question would be if I can only use `g, g1, g2, ...` as naming my role definition? Is this a common convention? 

Thanks in advance :)

**Comment by hsluoyz** [comment]
Hi @ideahitme ,

> so the idea is, if I get a request with user ideahitme and any group this user should be treated as admin.

I saw you have both groups and roles. Casbin actually doesn't quite differentiate groups and roles. They are both roles in RBAC. I saw you are developing related to k8s. Let me guess this is what your scenario is here: 

Every user can belong to one or multiple groups (similar to tenants) and the user can play roles like admin inside a group. The users can have different roles for different groups, for example, ``alice`` can be ``admin`` role in ``group1`` and ``user`` role in ``group2``.

And now you want user ``ideahitme`` to be ``admin`` role automatically for all the groups this user belong to.   Is this correct? If yes, then you should know which part of information you want to store in casbin, the group-user mapping or role-user mapping or both or neither? I saw you have ``group`` in the request, so I guess you won't store group-user mapping in casbin, right? So what about role-user mapping?

If my guess about your scenario is not right, please tell me more about it so I can help you:)

> Another question would be if I can only use g, g1, g2, ... as naming my role definition? Is this a common convention?

They can be any names, as long as the maps to the policy type in policy (the 1st element for every line).

**Comment by hsluoyz** [comment]
> g = _, _, _

FYI, this syntax is not correct. For now, the right part has to be ``_, _``, which means arg1 inherits arg2. Maybe you could tell what the 3rd arg3 is for here.

And I have described role definition here: https://github.com/casbin/casbin#role-definition-optional, which will clear some things about casbin RBAC I think.

**Comment by ideahitme** [comment]
Hi @hsluoyz, thanks for quick reply 

> Every user can belong to one or multiple groups (similar to tenants) and the user can play roles like admin inside a group. The users can have different roles for different groups, for example, alice can be admin role in group1 and user role in group2.

Yes, this is correct. One user can belong to multiple groups, but the scenario can be slightly more complicated, where the user has multiple roles within a group. So let's say you have a group `critical`, and the user might have both `reader, writer` role.

> And now you want user ideahitme to be admin role automatically for all the groups this user belong to. Is this correct? If yes, then you should know which part of information you want to store in casbin, the group-user mapping or role-user mapping or both or neither? I saw you have group in the request, so I guess you won't store group-user mapping in casbin, right? So what about role-user mapping?

Yes this is a viable approach (storing role-user mapping) I think. I tried it out, and it seems plausible: 

```policy.csv
p, admin, *, *, *
p, *, operator*, *, *
p, *, *, /api, get
p, *, *, /api/*, get
p, *, *, /apis, get
p, *, *, /apis/*, get
p, *, *, /version, get
p, alice, *, /api, (get)|(post)

g, kubelet, admin
g, ideahitme, admin
g2, MySuperUserGroup, admin
```

```model.conf
[request_definition]
r = user, group, path, verb

[policy_definition]
p = user, group, path, verb

[role_definition]
g = _, _ 
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.user, "admin") || g2(r.group, "admin") || (keyMatch(r.user, p.user) && keyMatch(r.group, p.group) && keyMatch(r.path, p.path) && regexMatch(r.verb, p.verb))
```

Don't really know how good is this though. Thanks a lot for help

**Comment by ideahitme** [comment]
> FYI, this syntax is not correct. For now, the right part has to be _, _, which means arg1 inherits arg2. Maybe you could tell what the 3rd arg3 is for here.
> 
> And I have described role definition here: https://github.com/casbin/casbin#role-definition-optional, which will clear some things about casbin RBAC I think.
Yes this seems perfectly fine :) I misunderstood the purpose of `role_definition` :)

**Comment by hsluoyz** [comment]
I added the feature about the the tenant-specific roles. So roles can be inside a tenant instead of global. See here: https://github.com/casbin/casbin#role-definition-with-domainstenants-optional.

Maybe this can solve your issue better:)

**Comment by ideahitme** [comment]
Awesome! I will give it a try. Thanks for your support.
