### ISSUE TITLE
how to create database table by self defined 

### ISSUE THREAD

**Issue by wanlp10** [casbin/casbin#156]
when I use casbin, I select Mysql as my database;  I can create database by myself defined ,but I don't know how to create table by myself,(create table to save policy_model)  ,can you tell me what I should do?

**Comment by hsluoyz** [comment]
How to interact with a database (like MySQL) is addressed by an adapter instead of the core library (aka this repo). There are a lot of adapters that can connect with MySQL, including several ORM adapters. Which adapter are you using? Please raise this issue on that repo's issues page.

**Comment by wanlp10** [comment]
We have discussed this question in the QQ group. Thank you very much for your answer and help
