### ISSUE TITLE
Structured logging proposal

### ISSUE THREAD

**Issue by llonchj** [casbin/casbin#157]
Thanks for casbin, this is an amazing product I use in several projects.

I am willing to contribute casbin with a logging abstraction interface so we can deliver structured logging to a logger, which by default will be golang `log` package, as implemented today.

The main benefit will be the ability to push logs to other loggers (zap, logrus, etc...) following casbin's development pattern of keeping the core simple and extensible into specific party solutions.

I am willing to start a discussion in order to gather ideas and requirements to proceed with a PR.

**Comment by vtolstov** [comment]
This is good thing to have, can you provide example changes and does it breaks api compatibility.

**Comment by llonchj** [comment]
Hi @vtolstov!

The main idea will be to enrich `util/log_util.go` with a interface to be able to log using golang's log but also logrus or zap or zerolog...

```go

type Logger interface{
  LogPrint(...interface{})
  LogPrintf(...interface{})
}

// Using golang log
type DefaultLogger struct {}
func (l *DefaultLogger) LogPrint(v ...interface{}) {log.Print(v)}
func (l *DefaultLogger) LogPrintf(v ...interface{}) {log.Printf(v)}

var Logger=DefaultLogger{}

// LogPrint prints the log.
func LogPrint(v ...interface{}) {
	if EnableLog {
            Logger.Print(v)
	}
}
```

This is an *incomplete, partial implementation* just for you to evaluate.

Will not break any changes and will provide an application the ability to log using any of the existing libraries for the purpose. 

It is obvious to say that the interface can be extended implementing `Debug`... `Debugf`... this can be done in a second iteration.

I can start working ASAP on this and push a PR as is a requirement on my current project. What do you think?

**Comment by vtolstov** [comment]
i'm +1, but @hsluoyz needs approve this changes..

**Comment by hsluoyz** [comment]
Thanks for the proposal. It's a good feature I think. My concern is that the main Casbin library should not directly import any 3rd-party logging tools. As your code, we can define a ``Logger`` interface, and provide a built-in ``DefaultLogger``. All other ``Logger`` implementations should be done in a separate project, and will be imported into a Casbin instance via the ``SetLogger()`` call in a dependency injection way. Just like how we do it for Adapter, Watcher, RoleManager.

If a Casbin user doesn't call ``SetLogger()``, he should be able to use ``DefaultLogger`` by default.

**Comment by hsluoyz** [comment]
Closed as it has been fixed.
