### ISSUE TITLE
Move log.Logger to Enforcer

### ISSUE THREAD

**Issue by llonchj** [casbin/casbin#160]
* move log.logger to Enforcer
* deprecate `log.Print` and `log.Printf` in favour of `Enforcer.logger.Print`

@hsluoyz What are your thoughts changing Printf for log level functions (Debug, Info, Warn/Warning, etc...) or adding a log.Level to be added as the first parameter of Print and Printf?

**Comment by llonchj** [comment]
@hsluoyz Sorry if i ask too much. I am willing to understand where to Go...

I understand we should also provide access to a log.GetLogger so extensions (Adapter, etc..) are able to log using the same package. Otherwise, how do you envision logging access to casbin extensions?

Will you implicitly define DefaultLogger in Enforcer? This way will not change the behaviour having to explicitly define a logger. A possible solution might be something like http.DefaultClient in `net/http`.

**Comment by obashistu** [comment]
On logging it would be useful if Casbin had a global logger instance. Currently we use `Zap` as it supports a configurable global instance. Being able to log in different formats is important if you intend to ship them - JSON being the prime candidate.

**Comment by hsluoyz** [comment]
I think Zap can be implemented in the Logger interface:

https://github.com/casbin/casbin/blob/5ff5a6f5e38a392305b3291c5433bf79ea2afb3d/log/logger.go#L17-L30

**Comment by jkour** [comment]
> On logging it would be useful if Casbin had a global logger instance. Currently we use `Zap` as it supports a configurable global instance. Being able to log in different formats is important if you intend to ship them - JSON being the prime candidate.

Not sure how the logger is implemented in Go but in Delphi the logger(s) are injected so you can write your own (global or not) loggers and attach them to Casbin

**Comment by hsluoyz** [comment]
Is this ticket still valid? I think we already provide the Logger interface. Anyone can use it to fit in a specific log implementation. Casbin will just feed all its logs into that interface.

**Comment by hsluoyz** [comment]
Well. It's similar to what @jkour said, I will close this ticket for now.

**Comment by hsluoyz** [comment]
The new Logger interface is ready, see: https://casbin.org/docs/en/log-error
