### ISSUE TITLE
How to implement RBAC with roles dynamically attached to resources?

### ISSUE THREAD

**Issue by anton-khodak** [casbin/casbin#161]
Hi,

I want to understand how to implement a scenario in Casbin where users can have different roles with each role attached to a particular resource.

Simplest version: users can participate in multiple projects, projects can include multiple users, a user can be an owner, a maintainer, an observer in a project. Roles imply actions that are not tied to a particular object when they are defined, they get tied only when I assign a role to a subject-object relation. 

My ideal policy file for this scenario would look like:
```
g2, owner, read
g2, owner, transfer
g2, owner, write
g2, maintainer, read
g2, maintainer, write
g2, observer, read

p, bob, project1, owner
p, alice, project1, observer
p, bob, project2, maintainer
```

[RBAC with resource roles](https://github.com/casbin/casbin/blob/master/examples/rbac_with_resource_roles_policy.csv) won't work here because roles are attached to a particular group of objects, thus users that get a role "Owner" will become owners of all projects of the group when they only need to become an owner of one particular project. Defining an "Owner" role for each object would be an obviously silly duplication.

**Comment by hsluoyz** [comment]
You can use the ``RBAC with domains`` model: https://casbin.org/docs/en/supported-models#examples

**Comment by anton-khodak** [comment]
If I understand correctly, I will need to define a domain for each project with all the roles listed again and again like this:
```
p, owner, domain1, project1, read
p, owner, domain1, project1, write
p, owner, domain1, project1, transfer
p, maintainer, domain1, project1, read
p, maintainer, domain1, project1, write
p, observer, domain1, project1, read

p, owner, domain2, project2, read
p, owner, domain2, project2, write
p, owner, domain2, project2, transfer
...

g, alice, owner, domain1
g, bob, maintainer, domain1
```
but that looks like a serious data duplication due to a wrong abstraction. Do you think a model like the one suggested above could fit Casbin (if implemented)? I think this use case is generic enough to consider.

**Comment by hsluoyz** [comment]
To remove duplicates, you can use ABAC to patternize the comparison between domain and project.

**Comment by anton-khodak** [comment]
I am sorry, I don't understand how to do that in ABAC... could you please draft an example?

**Comment by hsluoyz** [comment]
My first question would be that why don't just use the common patterns: ``domain`` and ``project`` instead of ``domain1`` and ``project1`` if all domains are the same?

**Comment by anton-khodak** [comment]
What do you mean "all domains are the same"? Domains for me define a user-project relationship. If I have a project "foo" and a project "bar", and I want a user "bob" to become an owner of a project "foo", I can't include both projects in one domain, cause then Bob will become an owner of "bar" as well.

**Comment by hsluoyz** [comment]
OK. Then you can use the ``CheckDomainProject()`` function.

**Comment by hsluoyz** [comment]
Closed as stale.

**Comment by anton-khodak** [comment]
Went with the RBAC with domains model, thank you @hsluoyz !

**Comment by pratikmallya** [comment]
@anton-khodak can you paste how you accomplished this? I have the same problem as you do, but I haven't been able to pattern it out. Specifically, my model looks like:
```
[request_definition]
r = dom, sub, act

[policy_definition]
p = rol, act

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[role_definition]
g = _, _, _
g2 = _, _

[matchers]
m = g(r.sub, p.rol, r.dom) && r.act == p.act
```

So my domain is not defined in the policy (I want the policy to be independent of domains) but only in the request and in the role definition. e.g. policy:
```
p, role::distributor, distribute
p, role::deactivate, deactivate

g2, role::admin, role::distributor
g2, role::admin, role::deactivate
g, bob, role::admin, google
```

**Comment by hsluoyz** [comment]
@pratikmallya see: https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac

**Comment by pratikmallya** [comment]
@hsluoyz I do not see how you can use pattern matching to solve the problem I've mentioned above.

**Comment by hsluoyz** [comment]
Not supported:

![image](https://user-images.githubusercontent.com/3787410/67742737-cecab280-fa57-11e9-8a99-73f94f1cdc09.png)

**Comment by anton-khodak** [comment]
@pratikmallya here is my policy a year ago (might be outdated for recent releases!)
```
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act
```

**Comment by elhmarouan** [comment]
> Went with the RBAC with domains model, thank you @hsluoyz !
@anton-khodak Can you share your policy.csv file ?

I have the same problem as yours. I want to attach roles dynamically to resources to avoid policy duplication.
Thanks.

**Comment by anton-khodak** [comment]
@elhmarouan,  I don't use `policy.csv` directly and populate it through calls to Casbin. See here for an example: https://github.com/cellgeni/imaging-experiments-tracker/blob/0ffd27f8d2fa1186a1b688df5e408a276efadc3a/experiments/authorization/casbin.py#L57

**Comment by hsluoyz** [comment]
> Not supported:
> 
> ![image](https://user-images.githubusercontent.com/3787410/67742737-cecab280-fa57-11e9-8a99-73f94f1cdc09.png)

@anton-khodak @elhmarouan BTW, the above is not true any more. We have supported pattern matching (like *) in each arg (1st, 2nd and 3rd) in `g`. See:

PR: https://github.com/casbin/casbin/pull/475
Docs: https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac

**Comment by elhmarouan** [comment]
> > Not supported:
> > ![image](https://user-images.githubusercontent.com/3787410/67742737-cecab280-fa57-11e9-8a99-73f94f1cdc09.png)
> 
> @anton-khodak @elhmarouan BTW, the above is not true any more. We have supported pattern matching (like *) in each arg (1st, 2nd and 3rd) in `g`. See:
> 
> PR: #475
> Docs: https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac

@hsluoyz Thanks, but I still can't manage to get it work with pattern matching.

I have the following model:

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.obj) && r.act == p.act
```
My policy looks like this:

```
#"CASE_ADMIN" permissions
p, CASE_ADMIN, CASE, CASE_EDIT
p, CASE_ADMIN, CASE, CASE_ACCESS_MANAGEMENT
p, CASE_ADMIN, CASE, CASE_DIRECTORY_MANAGEMENT

#"CASE_CONTRIBUTOR" permissions
p, CASE_CONTRIBUTOR, CASE, CASE_EXPORT
p, CASE_CONTRIBUTOR, CASE, CASE_DOCUMENT_IMPORT

#"CASE_READER" permissions
p, CASE_READER, CASE, CASE_READ_TRACES

#Mapping USER-ROLE-CASE
g, user1, CASE_ADMIN, CASE/1
g, user2, CASE_READER, CASE/2
g, user5, CASE_CONTRIBUTOR, CASE/5
g, superadmin, CASE_ADMIN, *
```
The following requests work fine:
```
user1, CASE/1, CASE_EDIT  --> true
user2, CASE/2, CASE_READ_TRACES  --> true
```

I want a superadmin user that could administrate all cases using the following mapping:

`g, superadmin, CASE_ADMIN, *
`

But I always get false with this request:

`superadmin, CASE/5, CASE_EDIT --> false
`

I appreciate your help !

**Comment by hsluoyz** [comment]
@nodece @dovics can you answer this question?

**Comment by while-loop** [comment]
hsluoyz are you correctly setting your custom functions?

I think I also want the same config as you. Here are sample tests (check the custom config section).

￼

**Comment by nodece** [comment]
@elhmarouan The latest version supports this feature.

**Comment by sahil-lakhwani** [comment]
@while-loop So the 3rd `_` in `g` is being used an `obj`. How can we include domains here?
I basically want to use dynamic roles attached to resources in domains.
`*alice* has *viewer* access on *object1* in *domain1*`

**Comment by hsluoyz** [comment]
@sahil-lakhwani create a new issue
