### ISSUE TITLE
What's the standard format of the conf file?

### ISSUE THREAD

**Issue by edl7878** [casbin/casbin#165]
I'd like to edit model config file that named as xxx.conf in vscode with syntax highlighting. And I need to know what is the standard format of the conf file, so that I can install proper plugin of vscode to render it properly.

**Comment by hsluoyz** [comment]
Please ask questions in English.

**Comment by hsluoyz** [comment]
It just follows the ``.conf`` (or ``.ini`` on Windows) format. You should find a configuration | conf | ini plugin for your IDE.

Take GitHub comment for example, you can use ``ini`` keyword to get syntax highlighting, see here:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

I don't use vscode, but for Goland, you will also be prompted with installing the conf plugin:

![image](https://user-images.githubusercontent.com/3787410/49050760-d2d6ca80-f21f-11e8-8301-ea8ff70f8eb2.png)

**Comment by edl7878** [comment]
find a plugin named as 'Gitconfig Syntax' to highlight in vscode.
