### ISSUE TITLE
Is ‘g2’ a keyword that can't substitute by other string?

### ISSUE THREAD

**Issue by edl7878** [casbin/casbin#166]
```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && r.act == p.act
```

Is ``g2`` a keyword that can't substitute by other string? After I changed ``g2`` as ``gresource``，``e.AddNamedGroupingPolicy("gresource","resource","StuInfo")``  will not execute successfully.

**Comment by hsluoyz** [comment]
Please ask questions in English.

**Comment by hsluoyz** [comment]
Please see my explanation here: https://github.com/casbin/casbin/issues/155#issuecomment-433099535
