### ISSUE TITLE
Would you like to implement new function: GetUsersForRoleInDomain

### ISSUE THREAD

**Issue by CHCP** [casbin/casbin#167]
Hi hsluoyz:
  I found some useful functions like: ``GetRolesForUserInDomain, GetRolesForUser, GetUsersForRole``, but there is no ``GetUsersForRoleInDomain``.  Would you like to implement new function ``GetUsersForRoleInDomain``? This is will very useful. Thank you.

![image](https://user-images.githubusercontent.com/5645296/49054887-e26b0900-f249-11e8-8b74-fe71f81e26f2.png)

**Comment by hsluoyz** [comment]
I vote for your idea. Can you make the PR?

**Comment by CHCP** [comment]
I will try this, give me some days.

**Comment by CHCP** [comment]
Hi hsluoyz,
 I implement the function GetUsersForRoleInDomain() in source file rbac_api_with_domains.go as follows:

``
// GetUsersForRoleInDomain gets the users that has a role inside a domain.
func (e *Enforcer) GetUsersForRoleInDomain(name string, domain string) []string {
	res, _ := e.model["g"]["g"].RM.GetUsers(name, domain)
	return res
}
``

But when I test this function, this is nothing return, and there is nothing return when I call  ``GetUsersForRole(name string, domain string)``  either. I confirm there are some users has this role in Domain.

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casbin/pull/170

**Comment by CHCP** [comment]
Very good, thank you.
