### ISSUE TITLE
panic when add empty policy field

### ISSUE THREAD

**Issue by jaredzhou** [casbin/casbin#171]
the model is like this

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj,act, a,b

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.act == p.act && p_matcher(r.sub, r.obj, p.obj, p.a, p.b)
```

the test is like this

```go
params := []string{"rolea", "project", "read", "a", ""}
e.AddPolicy(params)
e.AddRoleForUser("usera", "rolea")
fmt.Println(e.Enforce("usera", "projecta", "read"))
```

when one of the params is "", it add duplicate record in db and panic when executing Enfore() method.
and i think it is a bug
```
github.com/casbin/casbin.(*Enforcer).Enforce(0xc0001b0150, 0xc0000fdf58, 0x3, 0x3, 0x5)
        /Users/jared/workspace/golib/pkg/mod/github.com/casbin/casbin@v1.7.0/enforcer.go:334 +0x176b
```

**Comment by hsluoyz** [comment]
You didn't define the ``p_matcher`` function. Please provide all your code to reproduce it.

**Comment by jaredzhou** [comment]
the p_matcher is like this 
```
obj_type := map[string]string{
      "pa":"typea",
}
user_obj := map[string]bool{
      "usera:pa":true,
}
func PMatcher(userName string, obj string, objtype string, a string, b string) bool {
	if obj_type[obj] != objtype {
		return false
	if a == "a" && b=="b"{
                 return user_obj[userName+":"+obj]
        }
}

func PMatcherFunc(args ...interface{}) (interface{}, error) {
	userName := args[0].(string)
	obj := args[1].(string)
	objtype := args[2].(string)
	ran := args[3].(string)
	ranValue := args[4].(string)
	return AMatcher(userName, obj, objtype, ran, ranValue), nil
}

```
the error is index out of range, i don't think it's related to the mather logic

**Comment by hsluoyz** [comment]
You defined ``AMatcher`` instead of ``PMatcher`` in ``PMatcherFunc()``. Your code just doesn't compile.

You didn't provide the ``AddFunction()`` call either. Please do not let me add or guess that for you.

Could you just give a working example to show this error?

**Comment by jaredzhou** [comment]
sorry! Here is the whole code. Run it twice, i will panic
```
package main

import (
	"fmt"

	"github.com/casbin/casbin"
	"github.com/casbin/mongodb-adapter"
)

var model string = `
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, objt, act, a, b

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.act == p.act && p_matcher(r.sub, r.obj, p.objt, p.a, p.b)
`

var obj_type = map[string]string{
	"pa": "project",
	"pb": "project",
}

var user_obj = map[string]bool{
	"usera:pa": true,
}

func PMatcher(userName string, obj string, objt string, a string, b string) bool {
	if obj_type[obj] != objt {
		return false
	}
	fmt.Println(userName, obj, objt, a, b)
	if a == "self" && b == "" {
		return user_obj[userName+":"+obj]
	}
	if a == "cus" && b == "b" {
		return true
	}
	return false
}

func PMatcherFunc(args ...interface{}) (interface{}, error) {
	userName := args[0].(string)
	obj := args[1].(string)
	objt := args[2].(string)
	a := args[3].(string)
	b := args[4].(string)
	return PMatcher(userName, obj, objt, a, b), nil
}

func main() {
	mongoURL := "mongodb://root:123456@127.0.0.1/admin"

	a := mongodbadapter.NewAdapter(mongoURL)
	e := casbin.NewEnforcer()
	m := casbin.NewModel(model)
	e.InitWithModelAndAdapter(m, a)
	e.LoadPolicy()
	e.AddFunction("p_matcher", PMatcherFunc)
	params1 := []string{"rolea", "project", "read", "self", ""}
	e.AddPolicy(params1)

	params2 := []string{"roleb", "project", "read", "cus", "b"}
	e.AddPolicy(params2)

	e.AddRoleForUser("usera", "rolea")
	e.AddRoleForUser("userb", "roleb")

	fmt.Println("usera->pa:", e.Enforce("usera", "pa", "read"))
	fmt.Println("usera->pb:", e.Enforce("usera", "pb", "read"))
	fmt.Println("userb->pa:", e.Enforce("userb", "pa", "read"))
	fmt.Println("userb->pb:", e.Enforce("userb", "pb", "read"))
}

```

**Comment by nodece** [comment]
@jaredzhou  It is working.

Test Result:
=== RUN   TestIssue171
usera pa project self 
usera->pa: true
usera pb project self 
usera->pb: false
userb pa project cus b
userb->pa: true
userb pb project cus b
userb->pb: true
--- PASS: TestIssue171 (0.00s)
PASS

**Comment by hsluoyz** [comment]
Hi @jaredzhou , I conformed your result. This is because when loading ``"rolea", "project", "read", "self", ""`` the second time, Casbin will only load the first four elements: ``"rolea", "project", "read", "self"`` instead of five elements. But the ``enforce()`` function still tries to load the fifth element, causing index out of range error.

The underlying reason for this behavior is that the MongoDB Adapter defined such a struct to represent a rule:

```go
// CasbinRule represents a rule in Casbin.
type CasbinRule struct {
	PType string
	V0    string
	V1    string
	V2    string
	V3    string
	V4    string
	V5    string
}
```

So empty string "" means no element here. So when you set a empty value "", it's the same as you didn't set it. I don't know if there's a better way like to differentiate empty string and nil, so we can support empty string and use nil to represent non-existent. You can ask the guys in https://github.com/globalsign/mgo to know whether MongoDB and the mgo ORM supports nil.

BTW, I don't think empty string in Casbin policy rule is very meaningful either. So you can just avoid using empty string.

**Comment by jaredzhou** [comment]
Got it, thx!  I will just use a string "nil" to represent empty value!
