### ISSUE TITLE
DeleteRoleForUserInDomain does not delete all roles in domain

### ISSUE THREAD

**Issue by CHCP** [casbin/casbin#173]
Hi hsluoyz,
 There are some roles of a user in domain those store in Database,  when I use DeleteRoleForUserInDomain in a loop,  there always left ONE role in Database, but all roles deleted in memory.  Is there some thing wrong? thanks.

Database: PostgreSQL 9.6
Casbin:  the latest version, commit: 99df23ebbdb11ada28cf6c7e0cbae8dfdc5b8e23
go: v10

**Comment by hsluoyz** [comment]
If that role is still mapped to another user, then that role will still exist. When you use ``DeleteRoleForUserInDomain()``, you are deleting the policy rule: ``g, User, Role, Domain``.

You also need to make sure ``AutoSave`` is supported by your adapter and is enabled (it is enabled by default). See: https://casbin.org/docs/en/policy-storage#autosave

**Comment by CHCP** [comment]
I found the reason:
DeleteRoleForUserInDomain() can't delete the Database records if v3/v4/v5 is NULL but empty-''. 
First I inserted some records with SQL when the System startup, the column v3/v4/v5 is NULL;  later the System insert some new records  with Casbin, the column v3/v4/v5 is empty-''. 

Would you like to make DeleteRoleForUserInDomain() available if the column is NULL or empty? I  can modify my insert SQL first. Thanks.

**Comment by hsluoyz** [comment]
What adapter are you using? The adapter chooses to insert NULL or empty for v3/v4/v5.

**Comment by CHCP** [comment]
I using the Gorm Adapter.

**Comment by hsluoyz** [comment]
I'm OK with the idea to support both NULL and empty in Gorm Adapter, could you propose a PR for it? https://github.com/casbin/gorm-adapter

**Comment by CHCP** [comment]
OK.  I will do this.

**Comment by CHCP** [comment]
Is there any difference between the two functions: rawDelete and rawDeleteAll?   If they are the same functuon, I think we can use rawDeleteAll instead rawDelete?

**Comment by hsluoyz** [comment]
OK for me.

**Comment by CHCP** [comment]
See PR: https://github.com/casbin/gorm-adapter/pull/7
