### ISSUE TITLE
Is there a way to combine RBAC with Domains and Restful auth?

### ISSUE THREAD

**Issue by e-nikolov** [casbin/casbin#174]
In our use case the domain is an Organization, which is specified in the route, for example:

```
/org/:orgname/admin
/org/:orgname/path1
/org/:orgname/path2
```

In this case, the domain is ``orgname``. Is there a way with Casbin to create roles which have access to some subpaths under the ``orgname`` domain?

For example, if we had the domains ``org1`` and ``org2``

There should be the generic roles ``User`` and ``Admin``, where within the specified domain, ``User`` has access to only

```
/org/:orgname/path1
/org/:orgname/path2
```

And ``Admin`` has access to

```
/org/:orgname/admin
/org/:orgname/path1
/org/:orgname/path2
```

If for example the user ``John`` is given the role ``User`` within the domain ``org1``

He should be able to access

```
/org/org1/path1
/org/org1/path2
```

but not 

```
/org/org2/path1
/org/org2/path2
```

**Comment by hsluoyz** [comment]
@e-nikolov , you can also see the similar issue here: https://github.com/casbin/casbin/issues/140

**Comment by hsluoyz** [comment]
Closed as solved.
