### ISSUE TITLE
How to use "keyMatch" with "g"?

### ISSUE THREAD

**Issue by nengc** [casbin/casbin#175]
I defined some ``g``, and one of them is rest URL path group, like ``/user/:id`` etc. And I add ``/user/:id``,``/role/:id`` to ``g2``, when I pass ``user/1`` to enforce, but enforcer always false. 

![image](https://user-images.githubusercontent.com/19792047/49492249-7cf2ca00-f892-11e8-85bd-f3c0f4441db7.png)

**Comment by hsluoyz** [comment]
Please paste your model and policy rules (in .CSV) here.

**Comment by nengc** [comment]
OK, below is my code

[request_definition]
r = sub, tenant, obj, service, act

[policy_definition]
p = sub, tenant, obj, service, act, eft

[role_definition]
g =  _, _, _
g2 =  _, _, _
g3 =  _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.tenant) && g2(r.obj, p.obj, r.tenant) && g3(r.service, p.service, r.tenant) 

p	user_group_1	tenant1	resource_group_1	service_group_1	GET	allow
g	bob	user_group_1	tenant1			
g	/sys/resource/:id	resource_group_1	tenant1	
g	nova	service_group_1	tenant1

and the params like below
Enforce("bob", "tenant1", "/sys/resource/1", "nova", "GET")

**Comment by hsluoyz** [comment]
Hi @nengc , currently, ``g`` doesn't support patterns like this:

```csv
g, /sys/resource/:id, resource_group_1, tenant1
```

We are working on it. Thanks for the report.

**Comment by hsluoyz** [comment]
@nengc , we have supported to use patterns like ``/resource/:id`` in the ``g`` function, see: https://github.com/casbin/casbin/commit/7650cba3506a36ef09bfd689efb15c74a9d37002

**Comment by nengc** [comment]
@hsluoyz thanks! And i have supported it by pre-handle the URL to get the real pattern of it. A litter ugly.
![image](https://user-images.githubusercontent.com/19792047/49713450-b3aa5500-fc83-11e8-81e3-0485fb085d89.png)
And i viewed your commit, seems only support  "KeyMatch2". I think it will better to support   all the "KeyMatch".

**Comment by nodece** [comment]
@nengc  We supported like 
- /resource/:id
- /resource/*

**Comment by nengc** [comment]
Hi @nodece, in Java ,like Spring Boot, the pattern is like  /resource/{id},so i think "KeyMatch3"  is also needed.

**Comment by hsluoyz** [comment]
@nodece We can add a function in the built-in role manager (not the interface) to let people modify the matching function (like from ``KeyMatch2()`` to ``KeyMatch3()`` or ``RegexMatch()``).

**Comment by hsluoyz** [comment]
This issue has been fixed in: https://github.com/casbin/casbin/pull/182 and https://github.com/casbin/casbin/commit/12d9fd1d0654b74d5b59220fee3205275ce5657b
