### ISSUE TITLE
How to combine RBAC and RESTful?

### ISSUE THREAD

**Issue by zwl1619** [casbin/casbin#177]
How to combine RBAC and RESTful?
My backend provides restful api and there are several roles such as admin,user ,editor.   
How to write the `policy.csv` and `model.conf`?

[keymatch_model.conf](https://github.com/casbin/casbin/blob/master/examples/keymatch_model.conf)

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)
```
[keymatch_policy.csv](https://github.com/casbin/casbin/blob/master/examples/keymatch_policy.csv)

```
p, alice, /alice_data/*, GET
p, alice, /alice_data/resource1, POST

p, bob, /alice_data/resource2, GET
p, bob, /bob_data/*, POST

p, cathy, /cathy_data, (GET)|(POST)
```

[rbac_model.conf](https://github.com/casbin/casbin/blob/master/examples/rbac_model.conf)

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```
[rbac_policy.csv](https://github.com/casbin/casbin/blob/master/examples/rbac_policy.csv)

```
p, alice, data1, read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write

g, alice, data2_admin
```

**Comment by hsluoyz** [comment]
A hybrid model would be:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)
```

Policy:

```csv
p, alice, /alice_data/*, GET
p, alice, /alice_data/resource1, POST

p, data2_admin, /alice_data/resource2, GET
p, data2_admin, /bob_data/*, POST

p, cathy, /cathy_data, (GET)|(POST)

g, alice, data2_admin
```

**Comment by hsluoyz** [comment]
Closed as stale.

**Comment by federicosan** [comment]
@hsluoyz I tried this solution you proposed in the casbin's website editor and it says 

Error: matcher result should be boolean or number

Is this a bug in the editor or is this policy wrong?

**Comment by hsluoyz** [comment]
Hi @federicosan , I conformed this bug:

![image](https://user-images.githubusercontent.com/3787410/62846302-bd4bf700-bd01-11e9-853f-743f348041ab.png)

@nodece , can you have a look about this bug?

**Comment by federicosan** [comment]
@hsluoyz thanks 

Also there is something strange about RESTful keymatch one 

For example this police

p, alice, /alice_data/*/new, GET
in keymatch 
I don't know but I would think to be equivalent to this kematch2 policy

p, alice, /alice_data/:id/new, GET

In this last policy 

alice, /alice_data/something   ->  false
alice, /alice_data/something/new  ->  true

but in keymatch one this would be all true, as * would overrite everthing else. Is this ok too?

**Comment by hsluoyz** [comment]
You can choose to use ``keyMatch2()`` if that fits your need. We have keyMatch(), keyMatch2(), keyMatch3() for different needs.

**Comment by federicosan** [comment]
> You can choose to use `keyMatch2()` if that fits your need. We have keyMatch(), keyMatch2(), keyMatch3() for different needs.

But is that behavior ok?

Should keymatch one give false for this
example?

Policy

p, alice, /alice_data/*/new, GET

Request 

alice, /alice_data/something 

or true?

I thing it should give false.

**Comment by nodece** [comment]
Hi @hsluoyz , you lost `role_definition`.

**Comment by hsluoyz** [comment]
keyMatch() is designed as a simple match, omitting all chars after *. For case ``/alice_data/*/new``, please use ``regexMatch()``.

**Comment by hsluoyz** [comment]
@nodece , you are right, thanks!

**Comment by nodece** [comment]
@hsluoyz @federicosan I corrected the model.
