### ISSUE TITLE
[Help wanted] - Need little starting help

### ISSUE THREAD

**Issue by Steinliiippp** [casbin/casbin#179]
I need a little bit of help at the beginning. I read all the documentation of casbian but i dont get it .... Here is what i trie to reach:

I have a REST-Api with a database backend. In this backend there are many users which are allowed to use the api functions. Every user has a role (in the database). I want to implement some ABAC-Pattern with jcasbin. But in every article i found there are the conf-files and policiy files, but i cant set the policies dynamic. I need something like this:

API-Function: /account/1/details
Security: All Admins are allowed and the user who is the owner of the account

But this is not possible with static security files (csv-files) like in the examples.

Is it possible to dynamic evaluate the security rules defined in the .conf-files with random and changing parameters based on database access. For Example:
I access the route /account/1/details and also request the current user entity from the database. Then i compare the account id with the user id and maybe some environment variables with jcasbin and get a allowed or not?

**Comment by hsluoyz** [comment]
We use .csv file to store policy rules in our example because it's easy. In fact, the policy rules can be stored in lots of RDBMS, NoSQL, KV store, cloud, etc via adapters: https://casbin.org/docs/en/policy-storage. We also have two sets of API to modify the policy rules at run-time: https://casbin.org/docs/en/policy-management

And for your example, you can of course compare ``/account/1/details`` with the logged-in account ID. Just write a matcher to do it.

**Comment by Steinliiippp** [comment]
But what is if i have 2 different routes and this routes need different checks. Can i define multiple matcher-files? Or do i have to put them all in one conf-file?

**Comment by hsluoyz** [comment]
You can always put the logic into one matcher. As the matcher supports AND, OR and even custom functions.

**Comment by Steinliiippp** [comment]
Is there any sample project in java i can you for resarch?

**Comment by hsluoyz** [comment]
Here are some examples: https://github.com/casbin/jcasbin#web-frameworks

**Comment by Steinliiippp** [comment]
Sry but i have to ask this one more question ....

Is this the right practice?

URL: /api/v1/user/10
public Result showUser(int id){
       User user = UserService.getUser(id);
       if(isAllowed(session.get(userID), 10, GET)){
              return success;
       }else{
              return error;
       }
}

private boolean isAllowed(String userId, String data, String action){
       enforcer.addPolicy(userId, data, action);
       return enforcer.enforce(userId, data, action);
}

conf_file:
[request_definition]
r = acc, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.acc== p.acc && r.obj == p.obj && r.act == p.act

Im asking this because of:

1. I cannot set policys in advance, because i dont know all users
2. I cannot set policiys in advance, because i dont know the id of the resource
3. I cannot set policiys in advance, because i dont know the Action of the request


Maybe im stupid but i dont get it ................ in german it is called "auf dem Schlauf stehen" (stand on the loop)

Could you show me a short REST-Example in Java where i could start? Is my example useable? I dont think so because of the enforcer.addPolicy(userId, data, action); call ....

**Comment by hsluoyz** [comment]
This is another question. You should ask it in a new issue. And you should ask it to: https://github.com/casbin/jcasbin for jCasbin's issue.
