### ISSUE TITLE
Resource per field permissions.

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [casbin/casbin#180]
What if I do want so more granularity? Say I wand some role "accountant" to be able to see a certain field in a resource ( say "invoice" ), but role "employee" can see all the fields, but not that special field. How do I express that in the conf/policy files. 
Thanks.

**Comment by techoner** [comment]
It still conforms to the rbac model

**Comment by Dragomir-Ivanov** [comment]
Okay, I know that is RBAC, but how this fields get configured in the `casbin` configuration files? Is there any example of this use case? If not, I can make one, if explained properly.

**Comment by hsluoyz** [comment]
@Dragomir-Ivanov For the role part, you can refer to the RBAC example, for the ``can see all the fields`` part, you can use functions like ``keyMatch()``, ``regexMatch()``, see the RESTful example: https://github.com/casbin/casbin#examples

**Comment by hsluoyz** [comment]
Closed as stale.

**Comment by videni** [comment]
@hsluoyz,  I also didn't understand fields permission in Casbin, what did you mean `regexMatch ` can do this job? can you make an example please?  besides, the design of Casbin has a huge drawback, see [access level for resource](https://github.com/casbin/casbin/issues/197)

**Comment by hsluoyz** [comment]
@videni 

Model:

```ini
[request_definition]
r = sub, obj

[policy_definition]
p = sub, obj

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && regexMatch(r.obj, p.obj)
```

Policy:

```csv
p, accountant, invoice
p, employee, .*

g, alice, accountant
g, bob, employee
```

``sub`` is a user, ``obj`` is a field in a resource. ``.*`` means to match anything in regex.

Please raise question in a new issue page if any.
