### ISSUE TITLE
Seems it is a bug?

### ISSUE THREAD

**Issue by nengc** [casbin/casbin#183]
When i update the "casbin_rule" table from the DB rather than the "enforcer" methods, if the update frequency is high, the "enforcer" data will be duplicated.
eg. I use the method below 3 times, and then get data by using "enforcer.GetFilteredGroupingPolicy",the result will be duplicated.
![image](https://user-images.githubusercontent.com/19792047/49856008-c9f21580-fe29-11e8-889a-809ca36f948d.png)

**Comment by hsluoyz** [comment]
I failed to understand your question. ``LoadPolicy()`` doesn't modify the policy rules. The policy won't be duplicated or modified by calling ``LoadPolicy()`` for multiple times.

**Comment by nengc** [comment]
Hi, @hsluoyz , the situation is that when i update  "casbin_rule" table  using "go-xorm/xorm" 3 times. and then i  use "enforcer.GetFilteredGroupingPolicy" to get the data, the data will be duplicated.

**Comment by hsluoyz** [comment]
Can you provide a minimized working example?

**Comment by nengc** [comment]
@hsluoyz Sorry, because I save the data in the DB, and from the frontend call, not that convenient.

**Comment by hsluoyz** [comment]
You are writing SQL instead of using adapters. it's not the suggested way to use Casbin. At least you have to handle more details this way. It's even harder for us to troubleshoot your issue.

You said you have frontend and backend, then you should figure out which part goes wrong. Casbin works on backend, so you have to exclude the issues of frontend. Then provide a minimized example.

**Comment by nengc** [comment]
@hsluoyz I update the  "casbin_rule" table using "go-xorm/xorm" and the data in the DB is right, But using adapters to get the updated data, the data duplicated.
Though is not suggested to using SQL, but sometimes it will be more extensible when using it. And the ```LoadPolicy()``` can be used to refresh the adapter data from the DB, but duplicated indeed.

**Comment by nengc** [comment]
@hsluoyz  below is the UI and the DB. After i updated using SQL 3 times, And every time using the ```LoadPolicy()``` to refresh the adapter, the data in DB is right, but get data from the adapter, the data duplicated. when i restart my service, the data will be correct. I know it is hard to troubleshoot the bug,but i think it will be a fatal bug.
![image](https://user-images.githubusercontent.com/19792047/50152236-0f1cb880-02fe-11e9-8a71-55afeb8b4b6f.png)
![image](https://user-images.githubusercontent.com/19792047/50152252-2196f200-02fe-11e9-95c1-0e06b98376b0.png)
![image](https://user-images.githubusercontent.com/19792047/50152295-35425880-02fe-11e9-807f-f217f4ad7733.png)

After updated by using SQL, the data get by the adapter duplicated.
![image](https://user-images.githubusercontent.com/19792047/50152316-468b6500-02fe-11e9-9f90-2a83a196d0e9.png)
![image](https://user-images.githubusercontent.com/19792047/50152390-7175b900-02fe-11e9-89bc-b2318e938158.png)

The DB is correct.
![image](https://user-images.githubusercontent.com/19792047/50152422-7fc3d500-02fe-11e9-8333-d75c991d1c87.png)

The code:
![image](https://user-images.githubusercontent.com/19792047/50152623-142e3780-02ff-11e9-9ebe-4ff16fe57157.png)

After restart the service, it will be correct.
![image](https://user-images.githubusercontent.com/19792047/50152633-20b29000-02ff-11e9-8035-2cf638a71d49.png)

**Comment by hsluoyz** [comment]
> Sorry, because I save the data in the DB, and from the frontend call, not that convenient.

You can dump your DB into a .sql file and put the file here. It's not that inconvenient.

I'm not familiar with your code or management UI. Taking screenshot doesn't help. Please just create a ``main.go`` and write a minimized example there.

So here's what I need: a ``main.go`` which is a full example and a .sql file which is the DB.

**Comment by nodece** [comment]
@nengc  Casbin is ok, you can use `casbin.NewSyncedEnforcer()`  make the setup work, please pay attention to thread safety during development.

**Comment by nengc** [comment]
@nodece Oh, I think i should to upgrade my casbin lib first. If casbin support thread safe, but where is the Docs.

**Comment by hsluoyz** [comment]
@nengc https://github.com/casbin/casbin#multi-threading

**Comment by nengc** [comment]
@hsluoyz  OK, Thanks! I think ```GetFilteredPolicy``` and ```GetFilteredGroupingPolicy``` should support slice params like ```AddPolicy```. And this is the reason i use SQL to find policy.

**Comment by hsluoyz** [comment]
Hi @nengc , is this issue (duplicated result) resolved? If it has been resolved, please close it. And propose your new question in a new GitHub issue.

**Comment by nengc** [comment]
OK
