### ISSUE TITLE
enforce regexMatch bug

### ISSUE THREAD

**Issue by tokingHong** [casbin/casbin#188]
![image](https://user-images.githubusercontent.com/39825820/50342949-2529b380-0560-11e9-8f4f-4e45eb73dd04.png)

why true ? bug ?

**Comment by hsluoyz** [comment]
It indeed looks weird. Can you provide a full example including the code, model and policy ?

**Comment by hsluoyz** [comment]
Closed as stale.

**Comment by tokingHong** [comment]
> It indeed looks weird. Can you provide a full example including the code, model and policy ?

sorry,no bug.I configured it.  xxxx  can match x when I use keyMatch2 ..... : (.          Thanks

**Comment by hsluoyz** [comment]
Glad to hear you solved it :)
