### ISSUE TITLE
Using regexMatch with g operator

### ISSUE THREAD

**Issue by lucaslrolim** [casbin/casbin#189]
I want to create a model where the same role has different policies according to the domain, where this domain is a pattern like "client_name/product_name/release_number". 

So I think I  will need a conf file like:

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, regexMatch(r.dom, p.dom)) && g2(r.obj, p.obj, regexMatch(r.dom, p.dom))  && (r.act == p.act)
```

And as example of the policies that I want:

```csv
p, admin, client_name/*/*, data, write
p, manager_1, client1/product_1/*, data, read
p, manager_2, client1/product_2/*, data, read
p, developer, client1/product_1/release_1, data, read

p, developer, client2/product_1/*, data, read

g, alice, admin, client1/all/
g, bob, manager_1, client1/product_1/
g, david, developer, client1/product_1/release_1

g, lucas, developer, client2/product_1/
```

In this case, we can see that for client1's domain people with developer role can read only release_1 data, and in client2's domain people with this same role can read data from all releases

My main question is if it's possible to apply this regex matcher inside the g operator. Case not, there is any other possible way to implement the described model?

**Comment by hsluoyz** [comment]
You can use built-in functions (``keyMatch()``, ``regexMatch()``, etc.) or your own function in ``g`` operator. See: https://github.com/casbin/casbin/issues/175

**Comment by hsluoyz** [comment]
Closed as stale.
