### ISSUE TITLE
Provide a way to silence panics

### ISSUE THREAD

**Issue by ideahitme** [casbin/casbin#19]
Hi, 

While writing a module using casbin I figured it is required to recover from panics when using casbin to provide a user with a meaningful error message instead of seeing stacktrace, e.g: 

```go
func (c *CasbinResource) IsAuthorized(*unversioned.UserSpec, *unversioned.ResourceSpec) (allowed bool, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = r.(error)
			allowed = false
		}
	}()
	allowed = c.casbin.Enforce(`something`)
	return
}
```
I was wondering if it is possible to provide an option for casbin not to `panic` when inputs required for Casbin are in wrong format?

**Comment by hsluoyz** [comment]
Hi @ideahitme ,

I can return ``err`` instead of panic instead. But do you know how to overload the return values? For example, if I add ``err`` to the return values of ``Enforce``, then the user has to call this even if he doesn't care about the error:

```go
allowed, _ = c.casbin.Enforce(`something`)
```

But I also want to support the original form:

```go
allowed = c.casbin.Enforce(`something`)
```

Do you know how to support them both at the same time?

**Comment by ideahitme** [comment]
Hi @hsluoyz,

not caring about the error is generally a bad practice :) and in Go it is a fair assumption when you call any function, `a,b,c,err := callMe()` if `err != nil` then `a,b,c` will get their default values and `err` should be handled right away with e.g. `if err != nil { return err }`.  

Regarding your concern, I agree with you that it is not worth to break the API. One thing worth mentioning though is that it really depends why the panic is caused. For me two main APIs exposed by `Casbin` is 1. `NewEnforcer(...)` and 2. `Enforce(...)`. 

1. If I am writing a library wrapper for casbin which gives the user freedom to write `casbin` style configuration file directly, then in case of an error `casbin` will panic somewhere down the `LoadModel` func or similar ( I assume at stage of file parsing).  It would be good if the user could get a feedback on why the parsing has failed (or at least that the provided casbin configuration file format is wrong). So IMO ability to return and error from `NewEnforcer(...)` would be a really useful feature. 

2. `Enforce(...)` on the other hand is controlled by the library wrapper for casbin, so probably it is fair assumption that `Enforce(...)` panics if the provided request format is wrong. But I am not sure if there are other cases where it is possible ?

**Comment by hsluoyz** [comment]
Hi @ideahitme ,

I have added the following two functions, they will return error instead of causing panic.

```go
func NewEnforcerSafe(params ...interface{}) (e *Enforcer, err error) {}
func (e *Enforcer) EnforceSafe(rvals ...string) (result bool, err error) {}
```

I have explained this design on Gitter: https://gitter.im/casbin/lobby

**Comment by ideahitme** [comment]
@hsluoyz this is great, thanks a lot :)

**Comment by hsluoyz** [comment]
Please open it again if you have other questions on it :)
