### ISSUE TITLE
GetFilteredPolicy and GetFilteredGroupingPolicy should support slice params like AddPolicy

### ISSUE THREAD

**Issue by nengc** [casbin/casbin#190]
I think ```GetFilteredPolicy``` and ```GetFilteredGroupingPolicy``` should support slice params like ```AddPolicy```, because dynamic parmas will more flexible.

**Comment by hsluoyz** [comment]
Golang naturally supports to use slice ([]string) as slice params. You can use it like this:

```go
e.GetFilteredPolicy(0, []string{"111", "222"}...)
```

**Comment by nengc** [comment]
Oh, neglected that, thanks anyway!
