### ISSUE TITLE
[BUG] Util EscapeAssertion Function replaces ABAC

### ISSUE THREAD

**Issue by Roman-787** [casbin/casbin#192]
I am actually using the java implementation, but the function works the same as on all the other implementation, so i am posting here.

So the **Util.EscapeAssertion** replaces every "r." and "p." occurrence in the matcher string.
But if i use ABAC and have a matcher string like:

```ini
r.attr.gender == p.gender && r.dataobj.id == p.dataid
```

it gets converted to:

```ini
inir_attr_gender == p_gender && r_dataobj.id == p_dataid
```

But shouldn't it be converted to:
`r_attr.gender`? 
The same as with `r_dataobj.id`
Because my variable ist called **attr** and is ending on the character **r** it get replaced by the EscapeAssertion function. The same goes for variables ending with p.
Will this affect ABAC?  In my project it kinda does, so that i get wrong false evaluations, but i didn't debugged the expression evaluation to be 100% sure.

**Comment by Roman-787** [comment]
I tried building an regular expression.
Looking at the Docs here: https://casbin.org/docs/en/syntax-for-models
and with some trying out i came up with this regex: https://regex101.com/r/V56Kha/2/
Its my first time with golang, but this should work: https://play.golang.org/p/nPVdkry0x_M

Without links:

Regexp:
`(\|| |=|\)|\(|&|<|>|,|\+|-|!|\*|\/)(r|p)\.`
Matches 3 characters

1. A matcher symbol like` |  =  )  (  &  |  <  >  ,  +  -  !  *  /  (space)`
2. The character `r` or `p`
3. A dot `.`

Possible function:
```
func EscapeAssertion(s string) string {
	var regex = regexp.MustCompile(`(\|| |=|\)|\(|&|<|>|,|\+|-|!|\*|\/)(r|p)\.`)
	s = regex.ReplaceAllStringFunc(s, func(m string) string {
		return strings.Replace(m, ".", "_", 1)
	})
	return s
}
```

**Comment by jkour** [comment]
This is a standalone function and there will always be a case that the result will be messed up---or it will impose (unreasonable?) limitations.

The function **should be used** with (or look at) the structure of the request definition, policy definition and ABAC structure but I understand this may require substantial rewriting.

**Comment by hsluoyz** [comment]
I agree with you. The regex should be already enough for now. If there are further issues about it, we will certainly consider a semantic based substitution. For the test, you can just add your simple test into ``util_test.go``.

**Comment by Roman-787** [comment]
I found a mistake in my solution. The given expression string at runtime does not start with "m =  r.obj [...] ". It starts straight with "r.obj [...] ", so the "m=" part is already cut. 
This means a have to add at least an if statement which replaces the first dot

PR: #194

**Comment by hsluoyz** [comment]
@Roman-787 , the PR is merged, thanks for the contribution! 

BTW, your commit (https://github.com/casbin/casbin/commit/4473e17834cd1d5d87a2eeee71931ce44d36d3c6)'s author and committer is not recognized by GitHub, both for this project (like more accurate contributors statistics) and yourself (Show contribution activity in [your profile](https://github.com/Roman-787)), I suggest linking commit's author (and committer) with GitHub account: https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

**Comment by Roman-787** [comment]
@hsluoyz Thanks, i think now it's associated.
 But the bug persists in the other implementations of casbin.
Will there be other issue opened for the specific language? or do we leave this one open? 
I can at least contribute to the java implementation, which i personally use.

**Comment by hsluoyz** [comment]
@Roman-787 Thanks for the contribution!

You can propose a new issue and the related PR in the java implementation:) This issue will be closed.
