### ISSUE TITLE
Question of rbac

### ISSUE THREAD

**Issue by rarpainting** [casbin/casbin#193]
My business code needs to distinguish between role and user in `SavePolicy`, but in the `casbin` rbac model example, role and user are actually not distinguished, so
**how to distinguish between role and user in `SavePolicy`**

**Comment by hsluoyz** [comment]
Casbin doesn't distinguish role from user in its RBAC. They are all treated as strings. If you only use single-level RBAC (a role will never be a member of another role). You can use ``e.GetAllSubjects()`` to get all users and ``e.GetAllRoles()`` to get all roles. They just list all ``x`` and all ``y`` respectively in all ``g, x, y`` rules.

But if you are using multi-level RBAC (with complicated role hierarchy), and you application doesn't record which string is user or role, or you have user and role with same name. You can add a prefix to role like ``admin`` to ``role::admin`` before passing it to Casbin. So you will know if it's a role by checking the prefix.
