### ISSUE TITLE
Breaking change in 1.8.0 where NewEnforcer() panics instead of just returning the enforcer

### ISSUE THREAD

**Issue by Jim-Lambert-Bose** [casbin/casbin#195]
We have come to expect that we can create an enforcer without worrying about whether or not a policy is in place.  Then we sync the policy from GitHub when we are able to, which sometimes takes several attempts if we are rate limited or the network is not working properly.  You're "fix" is a breaking change in behavior.  All we want to do, is init the enforcer and tell it: "hey there will be a file here eventually".   Can we change this back?

**Comment by Jim-Lambert-Bose** [comment]
What a mess.  This really is a fundamental change to how cabin works with its enforcers.

**Comment by hsluoyz** [comment]
@Jim-Lambert-Bose , thanks for this feedback. That change has been reverted in: https://github.com/casbin/casbin/commit/5eec294722043b93883a46128a884a842f6b8d61

**Comment by hsluoyz** [comment]
Closed as resolved.

**Comment by Jim-Lambert-Bose** [comment]
thank you!
