### ISSUE TITLE
Enviroment attribute for ABAC

### ISSUE THREAD

**Issue by M-Razavi** [casbin/casbin#196]
For the ABAC model sometimes needs environment attributes such as time or date to check working time in a company. Is it provided by Casbin?

**Comment by hsluoyz** [comment]
You can write a custom function like ``getCurrentTime()`` or ``isValidTime(time interface{})``, then use it in the matcher with ABAC attributes. See here: https://casbin.org/docs/en/syntax-for-models#how-to-add-a-customized-function

**Comment by M-Razavi** [comment]
Thanks
