### ISSUE TITLE
keyMatch2("/project/1/member", "/project/1") should return false

### ISSUE THREAD

**Issue by heww** [casbin/casbin#199]
keyMatch2("/project/1/member", "/project/1") should return false

**Comment by heww** [comment]
I do not know why at the beginning keyMatch2("/project/1/member", "/project/1") will return true?

And before the fix, KeyMatch2 will make key `/project/:pid/repo/:rid` to be used as `^^/project/[^/]+/repo/[^/]+$$` regex. See more https://play.golang.org/p/yF4m0g0fX2w

Not only keyMatch2, and keyMatch3 may have this problem too.

I think more documents needed for keyMatch2 and keyMatch3.

We will update to new release version which included these fix.

**Comment by hsluoyz** [comment]
Good point. The duplicated starting char and ending char resulted from the for loop:

```go
func KeyMatch2(key1 string, key2 string) bool {
	key2 = strings.Replace(key2, "/*", "/.*", -1)

	re := regexp.MustCompile(`(.*):[^/]+(.*)`)
	for {
		if !strings.Contains(key2, "/:") {
			break
		}

		key2 = re.ReplaceAllString(key2, "$1[^/]+$2")
	}

	return RegexMatch(key1, "^" + key2 + "$")
}
```

So your fix also had a good shot for this one :)

BTW, I think ``keyMatch3()`` doesn't suffer the same issue, see: https://play.golang.org/p/8SG4uoweTvh

**Comment by hsluoyz** [comment]
FYI, Casbin ``1.8.1`` has been released: https://github.com/casbin/casbin/releases/tag/v1.8.1

**Comment by dtarico-suplari** [comment]
I just run KeyMatch3("/abc", "/") using v1.8.1 and it incorrectly returns true.  Should I open a new issue to get this fixed for KeyMatch3 as well?

**Comment by hsluoyz** [comment]
Hi @dtarico-suplari , please open a new issue and link it to this one if you think they are related.
