### ISSUE TITLE
Cache the decisions to improve the enforcement performance.

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin#2]

**Comment by iantanwx** [comment]
I actually really need this for my project. Can I send a PR?

**Comment by hsluoyz** [comment]
sure, please send a PR :)

**Comment by hsluoyz** [comment]
Btw, I think you can implement it as a wrapper of the enforcer, like this one: https://github.com/casbin/casbin/blob/master/enforcer_synced.go

**Comment by iantanwx** [comment]
Sounds good. I was thinking of also implementing the same adapter pattern used for persistence, so that the cache can be either in-memory (default) or redis. It'll also give the user an opportunity to provide their own cache implementation in case they don't want to use the default in-memory cache.

**Comment by hsluoyz** [comment]
Hi @iantanwx , ``CachedEnforcer`` has been implemented, see its usage here: https://github.com/casbin/casbin/blob/master/enforcer_cached_test.go
