### ISSUE TITLE
Is it way to combine RBAC with resource with domain?

### ISSUE THREAD

**Issue by misterion** [casbin/casbin#202]
In our project we have RBAC like rule management there each vendor (domain) have access to related resources (games, discounts and so on) with same resource links. The access check based on bearer tokens and vendor id (domain) inside it. The different users could be associated with different domains (vendors) with different roles. In same time all resource definitions is same. 

So we have set of resources with resource based permission like this: 
```
p, game_admin, /game/*, (POST)|(PUT)
p, game_admin, /game/*, GET
p, game_moderator, /game/*, GET
```
Now, we want to write something like this to split domain access logic to share project_admin access to all resources:
```
With policy maybe?
p, project_admin, game_admin, domain1 <- defined in game_admin for domain1 

or with grouping?
g, project_admin, game_admin, domain1
....
g, alise, project_admin, domain1 
g, bob, project_admin, domain2 
```
The same coule be achieved with adding policy definition for each resource and domain but right now one resource set for REST have ~40 policy and i`m looking for way to not dublicate same rules for different domains becouse only domain is different. 

Can`t find proper way to merge RBAC with domain and resources in same match.

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casbin/casbin/issues/204
