### ISSUE TITLE
Implementing RBAC with custom access to resource by id

### ISSUE THREAD

**Issue by misterion** [casbin/casbin#206]
The role model:
- each role describe access to resource and action
- the user could have role like admin, support and so on.
- each role like admin, support could be described for all resources or for concrete resources by they uuid.

So we have something like this

p, admin, resource.action:*, read
p, custom_admin_uuid, resource.action:uuid, read
g, alise, admin
g, tom, custom_admin_uuid

Each time we add new actions for resource we should enumerate all roles and for each custom role add new policy by action name. Something like 

p, admin, resource.newaction.*
p, custom_admin_uuid1, resource.newaction.uuid1
p, custom_admin.uuid2, resource.newaction.uuid2

Is such aproach have rights to live? Is any way to improve it?

**Comment by hsluoyz** [comment]
It's similar to: https://github.com/casbin/casbin/issues/206
