### ISSUE TITLE
Is here is any way to check policy fields with custom group data by r.sub

### ISSUE THREAD

**Issue by misterion** [casbin/casbin#207]
Here is RBAC + domain model:

```ini
[request_definition]
r = sub, domain, resource, action

[policy_definition]
p = sub, domain, resource, action, eft

[role_definition]
g = _, _, _
g2 = _,_

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = ...
```
And roles

```csv
p, admin, domain, resource:*, all
g, alice, admin, domain
g2, alice,  resource:12345
```

Right now i only see something with custom function there we could get all data from g2 with ``GetFilteredNamedGroupingPolicy`` and intersect by hands. Is here is any way to check ``p.resource`` presents in g2 by ``r.sub`` in matcher without custom functions?

**Comment by hsluoyz** [comment]
I don't know what ``resource:12345`` means here in g2. What do you want to achieve?

**Comment by misterion** [comment]
We have model there role 
could be restricted or not restricted for given resource. I am using g2 as permission storage. The logic is:
1. Chech request resource with policy resource with regexp.
2. If match, check the request resource with g2 for strict equal.

**Comment by hsluoyz** [comment]
One way is using model's matcher. The other way is ``GetFilteredNamedGroupingPolicy()``.
