### ISSUE TITLE
casbin如何做数据权限控制

### ISSUE THREAD

**Issue by cel533** [casbin/casbin#208]
场景如下:
   用户 ,资产(主机,路由之类的)

 组织机构有上级部门跟下级部门

上级部门的用户可以看下级部门的资产跟本部门的资产
下级用户只能看本部门的资产

然后我在查询资产的时候显示的是一个列表,需要在SQL里对字段做过滤,请问如何实现?

**Comment by hsluoyz** [comment]
@cel533 please use English in issue's title and content.
