### ISSUE TITLE
Hierarchical ownership of resources

### ISSUE THREAD

**Issue by F21** [casbin/casbin#209]
For my use-case, I have the following:
- Users own resources (such as records in a CRM).
- Users are assigned to groups.
- Groups are hierarchical and parent groups should be able to access resources of subgroups (recursively). This means that someone in the sales manager (parent) group should be able to see all the resources of someone in the sales executive sub group.
- During runtime, administrators of the application should be able to configure whether users within a group can see each others resources.
- What if we use ABAC's `users.OwnResource` sugar method in the permissions?

This question pertains to the resource only and currently does not consider the actions a user can perform on a resource.

I am currently exploring casbin and do not have a full understanding of its inner workings. Do you have any tips for implementing this?

**Comment by hsluoyz** [comment]
Hi @F21 ,

> Users own resources (such as records in a CRM).

Basic model does it, see: https://casbin.org/docs/en/syntax-for-models

> Users are assigned to groups.

Use RBAC: https://casbin.org/docs/en/rbac

> Groups are hierarchical and parent groups should be able to access resources of subgroups (recursively). This means that someone in the sales manager (parent) group should be able to see all the resources of someone in the sales executive sub group.

Use RBAC hierarchy: https://casbin.org/docs/en/rbac#role-hierarchy

> During runtime, administrators of the application should be able to configure whether users within a group can see each others resources.

Use [API](https://casbin.org/docs/en/api) or [Admin Portal](https://casbin.org/docs/en/admin-portal).

> What if we use ABAC's users.OwnResource sugar method in the permissions?

You can use ABAC with RBAC of course, see ABAC: https://casbin.org/docs/en/abac

You can read through our website for better understanding: https://casbin.org/

**Comment by F21** [comment]
@hsluoyz Thanks for the pointers. I've played around with casbin and came up with a revised list of requirements:
- Users belong to groups
- Roles are assigned to groups
- Permissions are assigned to roles.

I am able to implement this using:
```go
func main() {
	// Initialize the model from a string.
	text :=
		`
[request_definition]
r = sub, act

[policy_definition]
p = sub, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.act == p.act
`
	m := casbin.NewModel(text)

	// Create the enforcer.
	e := casbin.NewEnforcer(m)
	e.AddPolicy("role1", "action1")
	e.AddGroupingPolicy("group1", "role1")
	e.AddGroupingPolicy("user1", "group1")

	sub := "user1"
	act := "action1"

	if e.Enforce(sub, act) == true {
		fmt.Println("allowed")
	} else {
		fmt.Println("denied")
	}
}
```
This deals with actions a user can perform. However, I also need to find a way to restrict access to objects. Objects are owned by users. Since users are part of a group, I want to be able to allow users in a group to access objects owned by users who are in another group.

Do I need to create a second instance of the enforce for dealing with objects?

**Comment by hsluoyz** [comment]
allow users in a group to access objects owned by users who are in another group: ``g2(r.sub, r.obj.Owner.group)``

for users within a group to access each others resources: ``r.sub.group == r.obj.Owner.group``

You can define another enforcer for it.

**Comment by F21** [comment]
thanks @hsluoyz
