### ISSUE TITLE
casbin能否支持dotweb？

### ISSUE THREAD

**Issue by dbsn** [casbin/casbin#21]
dotweb也是国人开发的一款web框架，更新挺勤快的。
作者能否也支持一下，开发dotweb的casbin中间件？

地址：https://github.com/devfeel/dotweb

谢谢。

**Comment by hsluoyz** [comment]
你好 @dbsn ,

已经给他们提交issue了，见：https://github.com/devfeel/middleware/issues/1

如果作者同意的话，我就会开始着手开发这个插件

**Comment by devfeel** [comment]
@dbsn 感谢对dotweb的支持

**Comment by dbsn** [comment]
@hsluoyz   @devfeel 
两位的软件都是我喜欢的，能一起合作，真是太好了。

**Comment by hsluoyz** [comment]
@dbsn ,

你好，中间件已经添加：https://github.com/devfeel/middleware/tree/master/authz
