### ISSUE TITLE
casbin policy to web oauth2 scope

### ISSUE THREAD

**Issue by vtolstov** [casbin/casbin#210]
I'm use casbin for backend, and i have web application (angular typescript). Web application have route guards, so if user does not have permission for some actions related parts of site not available for him.
I can use oauth2 scopes to say about permissions. How do the best transform from casbin policy to oauth2 scopes, and how to parse it effectively in web app?

**Comment by hsluoyz** [comment]
Is your project open-source? If not, can you show a minimized working example of OAuth2 permissions?

**Comment by vtolstov** [comment]
now i have handmade parser for oauth2 scopes, scopes looks like accounts:read accounts:write sshkeys:read sshkeys:write

**Comment by vtolstov** [comment]
p.s. I'm not using node-casbin, but my first thinking about provide via additional api call casbin policy for current user, and use enforcer in web page to detect permissions

**Comment by hsluoyz** [comment]
Closed as stale.
