### ISSUE TITLE
Effector DSL supports only 4 explicit modes, and tests for them by string exact match

### ISSUE THREAD

**Issue by shlomi-nx** [casbin/casbin#211]
I was trying to create a model, and used `e =  some(where (p.eft == allow)) && !some(where (p.eft == deny))` but got `unsupported effect` thrown at me. So I went to check the code, and found that it is simply a string compare, including whitespaces:

https://github.com/casbin/casbin/blob/a5a1667e25abdbc5a4414ea9b6b889764174b7ec/effect/default_effector.go#L32

https://github.com/casbin/casbin/blob/a5a1667e25abdbc5a4414ea9b6b889764174b7ec/effect/default_effector.go#L40

https://github.com/casbin/casbin/blob/a5a1667e25abdbc5a4414ea9b6b889764174b7ec/effect/default_effector.go#L48

https://github.com/casbin/casbin/blob/a5a1667e25abdbc5a4414ea9b6b889764174b7ec/effect/default_effector.go#L58

The problem I had was with an extra whitespace. 

I noticed that this is the exact same implementation in all the variants of casbin: go, node, java, etc.

Now, the semantics of the effects DSL is really very nice. It seems it can be properly composable and could help us capture more intricate requirements. However that is misleading. There are actually only four supported modes of operations. 

My question: Is this supposed to improve? Is it planned to eventually support the actual DSL behind this? Or will it always be one of: "any allow", "none deny", "any allow AND none deny", "line precedence or deny"

If it is not planned, can we at least have some better string comparator? perhaps normalize spaces and parens? Or instead, just an enum with the four supported modes?

Thanks!

**Comment by hsluoyz** [comment]
Hi @shlomi-nx , the design is to support a DSL in effect. But we found the current four effects are enough for 99% scenarios. So we didn't make efforts to implement it. And you can see it's implemented by ``DefaultEffector``, meaning a Casbin user can always enhance it by providing another Effector implementation. Our shipped ``DefaultEffector`` can be viewed as a basic but not yet complete implementation for the design.

Please let me know if you need more flexibility than the current four effects. So we can implement it.

**Comment by hsluoyz** [comment]
Closed as stale.
