### ISSUE TITLE
How to get all related domains for subject

### ISSUE THREAD

**Issue by tpoxa** [casbin/casbin#215]
I would like to display for user list of all domains where it has any policies.
Looks like this is not possible because domain its just prefix. Any idea?

Possible solution is using **GetImplicitRolesForUser** with list of all domains... Not really elegant solution...

**Comment by tpoxa** [comment]
Well, I am using RBAC with domains.
Task is to find a list of domains where user has roles...

**Comment by nodece** [comment]
@tpoxa  I think You can call GetImplicitPermissionsForUser.  It already supports domain parameters.

**Comment by tpoxa** [comment]
@nodece but I don't know domains, that is the question. Find domains for subject.

**Comment by hsluoyz** [comment]
@tpoxa if you mean the ``p`` policies, you can call [GetAllSubjects()](https://casbin.org/docs/en/management-api#getallsubjects). If you mean the ``g`` policies, you can call [GetFilteredNamedPolicy()](https://casbin.org/docs/en/management-api#getfilterednamedpolicy) and extract the users by yourself.

**Comment by tpoxa** [comment]
@hsluoyz thank you, you can close the issue if you want.
