### ISSUE TITLE
how to get all resources that a user could access

### ISSUE THREAD

**Issue by suncl1989** [casbin/casbin#216]
User access different resource in different domains, how can I get all resources that a user could access

**Comment by hsluoyz** [comment]
See: https://casbin.org/docs/en/rbac#how-to-query-implicit-roles-or-permissions

**Comment by suncl1989** [comment]
thanks @hsluoyz  , though Method `GetImplicitPermissionsForUser` is not implemented in nodejs

**Comment by hsluoyz** [comment]
@suncl1989 , those two implicit functions has been added to Node-Casbin: https://github.com/casbin/node-casbin/pull/63  it should be available in latest Node-Casbin v2.0.3

**Comment by suncl1989** [comment]
@hsluoyz  cool! and the Documentation should be updated:)
