### ISSUE TITLE
GetGroupingPolicy does not display g2 or g3

### ISSUE THREAD

**Issue by tpoxa** [casbin/casbin#218]
I would like to print out all grouping policies I get.
I use g, g2 and g3

But GetGroupingPolicy looks like returns only g policies? 
Am I right?

Any solutions maybe?

Thank you!

**Comment by hsluoyz** [comment]
You should use ``GetNamedGroupingPolicy()``: https://casbin.org/docs/en/management-api#getnamedgroupingpolicy

**Comment by tpoxa** [comment]
Hi @hsluoyz, can you show me please an example?

**Comment by hsluoyz** [comment]
Example is:

https://github.com/casbin/casbin/blob/6bfd7470fb81e6442a94e14ad8322ce707a07173/management_api.go#L77-L80
