### ISSUE TITLE
Dealing with temporal dimension in authorization

### ISSUE THREAD

**Issue by jruizaranguren** [casbin/casbin#219]
`casbin` is a perfect fit for our access control needs, but we have some doubts about the application of temporal rules.

We have multiple use cases where granting access depends not only on the `object` identity but also in a time interval (sometimes periodic). We currently express this intervals using ISO 8601.

For us, this intervals are part of the policy rules. Something like `(sub, obj, act, domain, when)`, where `when` is a time interval. Or even `(sub, obj, act, domain, time_from, time_to)`

If we understood correctly, there is no currently way to enforce temporal rules with `casbin` except using  `ABAC`. That is, we should add the contextual information in `obj` and then implement a custom validation function that could be used in the policy model.

Are we right or there is a better approach?

Thank you for your attention and for this fantastic library.

**Comment by hsluoyz** [comment]
Hi @jruizaranguren , you can add a new element ``cur_time`` to request to represent the current time. Then add ``time_from`` and ``time_to`` to policy as you said. At last, check the time in the matcher. I provide an example based on the basic model:

```ini
[request_definition]
r = sub, obj, act, cur_time

[policy_definition]
p = sub, obj, act, time_from, time_to

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && r.obj == p.obj && r.act == p.act && isTimeInRange(r.cur_time, p.time_from, p.time_to)
```

- You need to pass into the current time as an arg in ``Enforce()`` function.
- Define and register the ``isTimeInRange()`` as a custom function.
- Add the ``domain`` element as you like (it's not related to the temporal question here).

**Comment by jruizaranguren** [comment]
Thanks, @hsluoyz . That works. I even may get rid if cur_time and make isTimeInRange compare with an embedded  "utcNow" function.
