### ISSUE TITLE
casbin in a distributed setting

### ISSUE THREAD

**Issue by jruizaranguren** [casbin/casbin#222]
We plan to add `casbin` in a distributed setting. We have:

- collection of machines per tenant enforcing access control on-premise. The policies will be read-only.
- some machines in cloud accepting change requests for access control policies (multi-tenant).

In addition, we must assume that some machines (specially on-premise ones) will be occasionally connected.

So we need a synchronization mechanism that ensure that on-premise machines get updated to last known version when connected.

I have reviewing [watchers](https://casbin.org/docs/en/watchers) functionality. If I understood correctly, `watchers` simply allow the subscription to changes in other enforces, and then we should implement our synchronization protocol.

Could be a better approach to depend on a distributed database that already ensures the synchronization? 
Does anybody facing a similar scenario? Some recommendation?

Thanks.

**Comment by vtolstov** [comment]
You can write own storage interface that uses cockroachdb or use already writed etcd backend or something else

**Comment by hsluoyz** [comment]
Hi @jruizaranguren , Casbin supports to store policy rules into distributed DB, like Redis, etcd: https://casbin.org/docs/en/adapters#supported-adapters. You can find all supported DBs in the above list, or [write your own adapter](https://casbin.org/docs/en/adapters#how-to-write-an-adapter) for a new DB.

**Comment by holajiawei** [comment]
In addition to consistency issues, we also need to consider the UpdatePolicy frequency issue. The simplest way to do this is to update each time in the trigger order with the distributed lock service. Using this method to handle update requests from different instances in a short period of time may not be efficient. Breaking the loading policy process sounds like a good idea.

**Comment by jruizaranguren** [comment]
@holajiawei, I did not understand your concern. Do you mean that watchers imply a distributed lock/transaction that I should avoid?

**Comment by holajiawei** [comment]
> @holajiawei, I did not understand your concern.

I have tried using Casbin in distributed mode，it is not suitable for UpdatePolicy frequent and a big policies set scenes. But I think it might suit your scene.

**Comment by jruizaranguren** [comment]
Thanks for your ideas.
