### ISSUE TITLE
getImplicitRolesForUser and GetImplicitPermissionsForUser get different result in node-casbin

### ISSUE THREAD

**Issue by suncl1989** [casbin/casbin#223]
in  page  [document of RBAC API](https://casbin.org/docs/en/rbac-api#getimplicitpermissionsforuser), the example : 

>p, admin, data1, read
>p, alice, data2, read
>g, alice, admin

>getPermissionsForUser("alice") can only get: [["alice", "data2", "read"]].
>But GetImplicitPermissionsForUser("alice") will get: [["admin", "data1", "read"], ["alice", "data2", "read"]].

I get [["alice", "data2", "read"]] when i run getPermissionsForUser("alice")    

and get [ 'admin' ] when i run getImplicitPermissionsForUser("alice")

the version is node-casbin 2.0.3

**Comment by nodece** [comment]
Please provide model.conf.

**Comment by suncl1989** [comment]
@nodece sorry， my fault by wrong one letter,  remove this issue if possible - -!

**Comment by suncl1989** [comment]
@nodece any chance,  another question, why `getImplicitPermissionsForUser` does not have parameter of domain but `getImplicitRolesForUser` does

**Comment by nodece** [comment]
@suncl1989  Added plan.

**Comment by suncl1989** [comment]
thanks for reply @nodece 
I konw nothing about golang and the following code bothered me all afternoon.

```
// GetPermissionsForUserInDomain gets permissions for a user or role inside a domain.
func (e *Enforcer) GetPermissionsForUserInDomain(user string, domain string) [][]string {
	return e.GetFilteredPolicy(0, user, domain)
}
```
`GetFilteredPolicy() `  was not declared with the parameter domain, why it works well.

**Comment by nodece** [comment]
Use variadic parameters.

node-Casbin v2.0.4 has been published, added domain paramter for GetImplicitPermissionsForUser.
