### ISSUE TITLE
enforcer.Enforce() instrumentation

### ISSUE THREAD

**Issue by Jim-Lambert-Bose** [casbin/casbin#224]
It would be great to add a simple instrumentation feature to:
func (e *Enforcer) Enforce(rvals ...interface{}) bool

Something like:

```go
result, err := expression.Evaluate(parameters)
if log.GetLogger().IsEnabled() {
   log.LogPrint("Result: ", result, " / params: ", parameters)
}
```

Which would produce output like:
```
Result: false / params: map[p_act:GET p_obj:/helloworld p_sub:admin r_act:GET r_obj:/helloworld r_sub:user@foo.com]
```

**Comment by hsluoyz** [comment]
Hi @Jim-Lambert-Bose , we already have this code, is this what you want?

https://github.com/casbin/casbin/blob/9814ac94c19c922c0afd5c2f34255e0d543ef372/enforcer.go#L429-L444

**Comment by Jim-Lambert-Bose** [comment]
@hsluoyz I do know about that and I use it regularly... my suggestion would let me see every evaluated expression that led to the result...  I know, it's not something that would scale across 100k policies and I wouldn't turn on the logging in that situation...  but I recently added my logging hack into my local clone because I couldn't understand what was being evaluated and why a request kept succeeding.

**Comment by hsluoyz** [comment]
Can you make a PR about it?

**Comment by hsluoyz** [comment]
I believe it's too time-consuming if adding hook to every policy match, only for debugging purpose. So will not do it for now. Let me know if you have better reasons.
