### ISSUE TITLE
Casbin Editor Broken

### ISSUE THREAD

**Issue by ximbal** [casbin/casbin#225]
I just tested the casbin editor, in google Chrome, it seems to be broken, tried feeding garbage in the model window, clicked on both buttons, check syntax and run the test, it seems that they both no matter what happens or the actual input of the window is, they both give successful messages. Just a friendly heads up.

Regards,
E

**Comment by hsluoyz** [comment]
Hi @ximbal , you are right. The source code of Casbin editor is here: https://github.com/casbin/editor The syntax highlighting is done by codemirror. Can you help build the syntax checking based on codemirror too?

**Comment by hsluoyz** [comment]
Hi @ximbal , we have started to add a simple and primitive syntax validation via [this commit](https://github.com/casbin/editor/commit/15b2a5f36b66ae460639fc512e58558dc0bcb66a), please try it at: https://casbin.org/editor/

If you have more issues related to Casbin online editor, please open it at: https://github.com/casbin/editor. This repo is mainly for Casbin Golang library.

**Comment by nodece** [comment]
@ximbal
Hi, We have published a new editor in [here](https://casbin.org/en/editor)! 
It supports check syntax and run the test.
