### ISSUE TITLE
Implement RBAC API for resource roles

### ISSUE THREAD

**Issue by ZamenWolk** [casbin/casbin#226]
Casbin says that it supports ressource roles model. However, while this is true, I find that resource roles are not treated as well as user roles, as there is no API to manipulate them within the library. I have made some helpers functions by myself for this, but I think it would be nice to integrate it within the library.

**Comment by hsluoyz** [comment]
Hi @ZamenWolk , given that you have implemented the resource-related RBAC APIs, would you mind proposing a PR to share them?

**Comment by hsluoyz** [comment]
Closed as unnecessary.
