### ISSUE TITLE
Does casbin involve data access control?

### ISSUE THREAD

**Issue by fandayrockworld** [casbin/casbin#227]
#208

**Comment by hsluoyz** [comment]
Hi @fandayrockworld , yes, please see the supported models: https://casbin.org/docs/en/supported-models. The ``obj`` element is just the data you mentioned.

**Comment by fandayrockworld** [comment]
There may be some misunderstand about the word `data access control` (or it should be `data privilege control` ?)
For example what I mean:
A and B have the financial role as same. 
But different is : A belongs to the Head Office, B belongs to the Branch Office.
So A could see all the offices's sales info but B only have the privilege of his Branch Office's.

Could casbin deal with this `data privilege control` ?

Thanks.

**Comment by hsluoyz** [comment]
I think you could do this with RBAC with domains model: https://casbin.org/docs/en/rbac-with-domains

**Comment by fandayrockworld** [comment]
I do not think so. I think the `data1` of `p, admin, tenant1, data1, read` you mentioned in domains model is a `resource`, but not a `data`.  (BTW, the `data1` is confusing I think, `resource1` may be better)

**Comment by hsluoyz** [comment]
How do you define the resource owner? It's a struct member, or specified in Casbin rule?

**Comment by fandayrockworld** [comment]
I don't know the meaning of **struct member** and **specified in Casbin rule**, but I can define the **resource** and **data** I mentioned above.
**resource** is a button or menu on a web page, or a url in RESTFUL.
**data** is the data in database.

**Comment by hsluoyz** [comment]
Casbin cannot replace SQL. You can query permissions in Casbin, but it requires efforts to change allowed permissions into SQL WHERE clause.

**Comment by fandayrockworld** [comment]
OK. Thank you for the replay. But do you have any plan to do some tries on this?

**Comment by oknixus** [comment]
> @noroot777 @oknixus for data permissions, see: https://casbin.org/docs/en/data-permissions
Thanks a lot.
