### ISSUE TITLE
call enforcer.Enforce() panic out of index

### ISSUE THREAD

**Issue by zhaozong** [casbin/casbin#228]
policyEffects = make([]effect.Effect, policyLen)
		matcherResults = make([]float64, policyLen)

		for i, pvals := range e.model["p"]["p"].Policy {
                ........
			if err != nil {
				policyEffects[i] = effect.Indeterminate
				panic(err)
			}
                .........
                }

Sometimes, ``policyLen`` is not the same as ``len(e.model["p"]["p"].Policy)``. It causes the ``out of index`` error. It occurs when calling ``enforcer.Enforce()`` after adding permissions in high parallel manner.

**Comment by hsluoyz** [comment]
Did you try using synced enforcer: https://github.com/casbin/casbin/blob/master/enforcer_synced.go ?

**Comment by zhaozong** [comment]
> Did you try using synced enforcer: https://github.com/casbin/casbin/blob/master/enforcer_synced.go ?

I'll try,thank you

**Comment by zhaozong** [comment]
> Did you try using synced enforcer: https://github.com/casbin/casbin/blob/master/enforcer_synced.go ?

Thank you. It works.
