### ISSUE TITLE
assertion.buildRoleLinks, incorrect 4th argument

### ISSUE THREAD

**Issue by tooolbox** [casbin/casbin#229]
https://github.com/casbin/casbin/blob/4aa316fb68d44d4cc5ddd98d7e9ec80bc0a8b081/model/assertion.go#L54

```go
func (ast *Assertion) buildRoleLinks(rm rbac.RoleManager) {
	ast.RM = rm
	count := strings.Count(ast.Value, "_")
	for _, rule := range ast.Policy {
                // ...
		if count == 2 {
			// ...
		} else if count == 4 {
			// error intentionally ignored
			ast.RM.AddLink(rule[0], rule[1], rule[2], rule[3])
		}
	}
        // ...
}
```

This seems entirely wrong, given:
```go
func (rm *RoleManager) AddLink(name1 string, name2 string, domain ...string) error {
	if len(domain) == 1 {
                 // ...
	} else if len(domain) > 1 {
		return errors.New("error: domain should be 1 parameter")
	}
        // ...
}
```

Want a PR on this?

**Comment by hsluoyz** [comment]
Currently, most of role manager functions like ``AddLink()`` support 3 args: ``user, role, domain``. So what are you using 4th arg for? I believe maybe you want to implement your own role manager which has the 4th arg. You can refer to: https://casbin.org/docs/en/role-managers If it's open source, please also contribute back to the community, thanks!

**Comment by hsluoyz** [comment]
Closed as stale.
