### ISSUE TITLE
role inheritance

### ISSUE THREAD

**Issue by vtanh** [casbin/casbin#23]
Hello,

Please help me to check why following code is not running ok:

Code:

ce := casbin.NewEnforcer(...)

ce.AddRoleForUser("admin", "administrator")
ce.AddRoleForUser("administrator", "feedback")
ce.AddPolicy([]string{"feedback", "/api/v1/feedback", "*"})

ce.Enforce("admin", "/api/v1/feedback", "*")
ce.Enforce("administrator", "/api/v1/feedback", "*")

Model:

[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && (r.act == p.act || p.act == "*")

Log:

2017/06/14 16:37:45 Model:
2017/06/14 16:37:45 r.r: sub, obj, act
2017/06/14 16:37:45 p.p: sub, obj, act
2017/06/14 16:37:45 e.e: some(where (p_eft == allow))
2017/06/14 16:37:45 m.m: g(r_sub, p_sub) && keyMatch(r_obj, p_obj) && (r_act == p_act || p_act == "*")
2017/06/14 16:37:45 g.g: _, _
2017/06/14 16:37:46 Policy:
2017/06/14 16:37:46 p: sub, obj, act: [[feedback /api/v1/feedback *]]
2017/06/14 16:37:46 g: _, _: [[admin administrator] [administrator feedback]]
2017/06/14 16:37:46 Role links for: g
2017/06/14 16:37:46 administrator < feedback
2017/06/14 16:37:46 feedback < 
2017/06/14 16:37:46 admin < administrator
2017/06/14 16:37:46 Role links for: g
2017/06/14 16:37:46 admin < administrator
2017/06/14 16:37:46 administrator < 
2017/06/14 16:37:46 Role links for: g
2017/06/14 16:37:46 admin < administrator
2017/06/14 16:37:46 administrator < feedback
2017/06/14 16:37:46 feedback < 
2017/06/14 16:37:46 Request [admin /api/v1/feedback *]: false
2017/06/14 16:37:46 Request [administrator /api/v1/feedback *]: true

The expect result is user "admin" in group "administrator" can use "feedback" api.

Regards,

Anh

**Comment by hsluoyz** [comment]
Hi @vtanh ,

These settings work on my side:

Model:
```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && (r.act == p.act || p.act == "*")
```

Policy:

```csv
p, feedback, /api/v1/feedback, *

g, admin, administrator
g, administrator, feedback
```

Test:

```go
func TestKeyMatchModel(t *testing.T) {
	e := NewEnforcer("examples/keymatch_model.conf", "examples/keymatch_policy.csv")

	testEnforce(t, e, "admin", "/api/v1/feedback", "GET", true)
}
```

I think the possible cause would be the role inheritance level. I only set the inheritance from 1 to 10 in the latest commit: https://github.com/casbin/casbin/commit/7e5939556e7a6c9435fc67fb2a4e7337d74cfd1e 20 hours ago. It means that Casbin before this commit doesn't support role to inherit another role. You should pull the latest code and try again.

**Comment by hsluoyz** [comment]
I assume this issue is fixed.

**Comment by vtanh** [comment]
Hi @hsluoyz , thanks for your quick reply.
