### ISSUE TITLE
DeleteUser does not remove user related permissions

### ISSUE THREAD

**Issue by NicolasDutronc** [casbin/casbin#231]
Hello,
I'm trying to delete everything related to a user when it is deleted from the database. I'm using a standard rbac model.
My version of casbin is v1.8.1
I saw the method **enforcer.DeleteUser** but it seems to delete only the roles and not the permissions attached to the user. Could you explain why ?
The workaround I found was to use **enforcer.RemoveFilteredPolicy**. It works great but it is not as natural as it would be with the rbac api.

Thanks !

**Comment by hsluoyz** [comment]
@nodece do you have any opinion on this?

**Comment by nodece** [comment]
@NicolasDutronc 
Maybe it help you to understand. 
See [https://casbin.org/docs/en/rbac#how-to-distinguish-role-from-user](https://casbin.org/docs/en/rbac#how-to-distinguish-role-from-user) for more details.

**Comment by NicolasDutronc** [comment]
@nodece Thank you for your answer.
I understand that well and I understand the source code as well. I just found it weird:
**DeleteUser** does actually the exact same thing as **DeleteRolesForUser** but shouldn't it be an alias for **DeleteRole** instead ?

**Comment by nodece** [comment]
@NicolasDutronc 
`DeleteUser()` and `DeleteRolesForUser()` is exact same, deletes a specified user from `group policy`.
`DeleteRole()` is deletes a specified role from `policy` and deletes associated user.

**Comment by NicolasDutronc** [comment]
How do I delete everything related to a user then ? I mean when a user is removed from the database, I want every permission and every role given to this user to be removed as well

**Comment by nodece** [comment]
Call `GetRolesForUser()` then call `DeleteRole()`.

**Comment by nodece** [comment]
@NicolasDutronc Closed as resolved.
