### ISSUE TITLE
role can also be used to enforce?

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin#233]
Hello, I found that in RBAC with domains, when I use role to enforce, casbin will also return true...
I'm not sure if it's the expected behaviour.

Like if I have the following policies:
```
p hr_admin www.example.com /hello (POST)|(PUT)(DELETE)
g hr_name hr_admin www.example.com
```
when I run:
```
e.enforce('hr_admin', 'www.example.com', '/hello', 'POST')
```
casbin returns `true` but I think it should be false.

Because when users register their usernames they can also give themself name like `hr_admin`. It will be very dangerous.

**Comment by nodece** [comment]
@GopherJ  This is right, Casbin allow this rule!

**Comment by GopherJ** [comment]
@nodece Thanks for your reply, I know but maybe it will cause some problems like what I described above?

**Comment by nodece** [comment]
@GopherJ See [https://casbin.org/docs/en/rbac#how-to-distinguish-role-from-user](https://casbin.org/docs/en/rbac#how-to-distinguish-role-from-user) for more details. Maybe you can add a prefix to role.
```
p role::hr_admin www.example.com /hello (POST)|(PUT)(DELETE)
```

**Comment by GopherJ** [comment]
@nodece Thanks for the explanation, I think the prefix should be able to solve my problem~
