### ISSUE TITLE
Dose casbin will add `Audit Log` ability ?

### ISSUE THREAD

**Issue by Wang-Kai** [casbin/casbin#234]
As a ACL(or RBAC) system, tracking of authorization grants and denials is important. So dose casbin plan to add `Audit ability` to output access or denials log ? 

Just like [Ladon Audit Log](https://github.com/ory/ladon#audit-log-warden)

**Comment by hsluoyz** [comment]
Hi @Wang-Kai , we will discuss about this feature. What Go logging library do you recommend to use?

**Comment by vtolstov** [comment]
May be provide interface? For example I'm use for logs loki by grafana.

пт, 14 июн. 2019 г., 17:23 Yang Luo <notifications@github.com>:

**Comment by Wang-Kai** [comment]
> Hi @Wang-Kai , we will discuss about this feature. What Go logging library do you recommend to use?

I recommend [apex/log](https://github.com/apex/log) strongly, it is simple and flexible.

**Comment by mdjunior** [comment]
Hi guys,
This is a very important contribution.

The main auditLog operations should stay in [enforcer](https://github.com/casbin/casbin/blob/master/enforcer.go#L300), right? Looking at [line 432](https://github.com/casbin/casbin/blob/a5a1667e25abdbc5a4414ea9b6b889764174b7ec/enforcer.go#L432) `rvals[0]` has the name of the policy that matches for a true result.

Should we add an auditLog interface [here](https://github.com/casbin/casbin/blob/master/log/logger.go), right?

Could this interface get a `map[string]string` for the information to be structured?

**Comment by hsluoyz** [comment]
Hi @Wang-Kai , Casbin has already provided a Logger interface, you can implement your own Logger with it: https://github.com/casbin/casbin/blob/master/log/logger.go

**Comment by hsluoyz** [comment]
@mdjunior , we already have logging the enforce result:

https://github.com/casbin/casbin/blob/a5a1667e25abdbc5a4414ea9b6b889764174b7ec/enforcer.go#L430-L441

I don't quite get it by ``map[string]string``.

**Comment by mdjunior** [comment]
This event can be a:
```
map[string]interface{
    "logType":"Request",
    "policy": rvals[0],
    "vals": fmt.Sprintf("%v",rvals[1:]),
    "result": result
}
```

In this way, an event can be transformed into a string or to other data structures. The user can manipulate this for your case.

Using the current `LogPrint` interface, the client would have to do the parser of the text.

**Comment by obashistu** [comment]
I can highly recommend Zap logger as it's a configurable levelled logger which makes sense for different environments. In production I don't want `debug` with stack traces but I might in development. The current logger does not support levels or different output formats which makes it difficult to ship/parse logs.

**Comment by hsluoyz** [comment]
Can it be done with the Logger interface?

**Comment by hsluoyz** [comment]
@kocoler can you work on this?

**Comment by hsluoyz** [comment]
The Audit Logs have been added in: https://github.com/casbin/casbin/pull/626

@kocoler please improve the docs here: https://casbin.org/docs/en/log-error to tell people how the log works and how to write a custom logger.

**Comment by hsluoyz** [comment]
@Wang-Kai The new Logger interface is ready, see: https://casbin.org/docs/en/log-error
