### ISSUE TITLE
how to implement transcation

### ISSUE THREAD

**Issue by henrykin** [casbin/casbin#236]
many methods in `rbac_api.go` do not return an error when something wrong in cabin, how can i know these errors and rollback the transaction outside?

**Comment by hsluoyz** [comment]
Hi @henrykin , thanks for the report. We will add the ``error`` as return value as next step. PR is also welcome.

**Comment by hsluoyz** [comment]
Hi @henrykin , this issue has been fixed in: https://github.com/casbin/casbin/pull/241

**Comment by henrykin** [comment]
Wonderful !
