### ISSUE TITLE
Hot to set whitelist and blacklist?

### ISSUE THREAD

**Issue by Atevens** [casbin/casbin#237]

**Comment by hsluoyz** [comment]
Hi @Atevens , what kind of whitelist and blacklist you want to achieve with Casbin? Can you be more specific? BTW, please use English here as we want this to be heard by everyone :)

**Comment by hsluoyz** [comment]
I think you can use the [Priority model](https://casbin.org/docs/en/supported-models), there will be allow policy rules (white-list) and deny rules (black-list). The order of the rules determine which rule applies first.

**Comment by Atevens** [comment]
Thanks
