### ISSUE TITLE
Question: How to create role definition with domains/tenants in run-time?

### ISSUE THREAD

**Issue by zorian-motso** [casbin/casbin#24]
For example, I want to create that structure:

```
p, admin, tenant1, data1, read
p, admin, tenant2, data2, read

g, alice, admin, tenant1
g, alice, user, tenant2
```

**Comment by hsluoyz** [comment]
Hi @zorian-motso ,

I added an example about it. Please refer to: https://github.com/casbin/casbin/blob/master/model_test.go#L157
