### ISSUE TITLE
Question: Does casbin support multiple policy sources?

### ISSUE THREAD

**Issue by DemianTinkiel** [casbin/casbin#240]
Hi,

I was reading [RBAC with Domains](https://casbin.org/docs/en/rbac-with-domains) and for what I see the definition of the policy is always in the same location. Is there support for multiple policy sources. In my case I'd need each domain to be the owner of their policy definition.

**Comment by hsluoyz** [comment]
Hi @DemianTinkiel , so you want to use Casbin to control the access to Casbin policy itself? Casbin can do this. Do you store your different domain policy rules together or separately? Is it a DB or file?

**Comment by DemianTinkiel** [comment]
Hi @hsluoyz, thanks for your quick reply.
 I'm not tied to any specific implementation so DB or file is the same but the main requirement is that each domain defines their own policy and groups stored separately (let's say different DBs to make it more concrete). So if Alice wants to write to data1 in domain2 she must be added to a role in domain2's DB.

**Comment by hsluoyz** [comment]
> So if Alice wants to write to data1 in domain2 she must be added to a role in domain2's DB.

In Casbin's RBAC with Domains model, if Alice needs to write data1 in domain2, she can be added to a role in domain2, but not necessarily domain2's DB. By default, all policy rules for all domains are assumed to be stored in one single DB. I don't know why the Casbin rules for different domains have to be stored in different DBs.

But if it's the case, Casbin can still do it. You can just use ``db1`` to store Casbin rules for domain1. Then use separated enforcer instance for each domain. The enforcer for domain1 only checks the access to domain1's resources, and will only query the Casbin rules from ``db1``.

**Comment by DemianTinkiel** [comment]
>  I don't know why the Casbin rules for different domains have to be stored in different DBs.

In my case different domains = different organizations

> But if it's the case, Casbin can still do it. You can just use db1 to store Casbin rules for domain1. Then use separated enforcer instance for each domain. The enforcer for domain1 only checks the access to domain1's resources, and will only query the Casbin rules from db1.

Yep, that's what I was thinking but I wanted to check if there was a "Casbin way" to do it :)

Thanks a lot for your help!

**Comment by hsluoyz** [comment]
OK. Maybe what you want is Casbin-Server? https://github.com/casbin/casbin-server

**Comment by DemianTinkiel** [comment]
@hsluoyz Interesting, I'll have a look. Thanks!

**Comment by DemianTinkiel** [comment]
@hsluoyz so to confirm I understand correctly, the server acts as a single enforcer point to query and it has read access to all DBs involved. Am I correct?

**Comment by hsluoyz** [comment]
Yes. Casbin-Server is a centralized pool for a number of Casbin enforcer instances. Each enforcer can query a database. So Casbin-Server connects to multiple DBs. It acts like a PDP (Policy Decision Point) in XACML terminology.

**Comment by hsluoyz** [comment]
Closed as solved.
