### ISSUE TITLE
Role-based data permissions

### ISSUE THREAD

**Issue by leubao** [casbin/casbin#243]
Role-based data permissions, such as user A, belong to the role administrator and have all data permissions in the system; user B, the manager, has all rights to the data of his department; user C, the employee, only has rights to public data and view his own data

**Comment by hsluoyz** [comment]
Hi @leubao , you can use the RBAC with domains model: https://casbin.org/docs/en/rbac-with-domains

**Comment by leubao** [comment]
`[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)`

`p, admin, domain1, /alice_data/:resource, GET|POST

p, admin, domain2, /alice_data2/:id/using/:resId, GET


g, alice, admin, domain1
g, bob, admin, domain2`

`bob, domain2, /alice_data2/99/using/22, GET
alice, domain1, /alice_data/hello, POST`

It's always failed to verify that I wrote it. What's wrong with that? Or RBAC with Domains does not support RESTful

**Comment by hsluoyz** [comment]
You should use ``keyMatch2()``.

**Comment by leubao** [comment]
thank you;For example, in system A, User B has access to 100 data specified in the User table, while other data have no access. How to design such permissions.

**Comment by hsluoyz** [comment]
Is there anything in common in the 100 data?

**Comment by leubao** [comment]
100 pieces of data belong to the same merchant or department.

**Comment by hsluoyz** [comment]
You can use the RBAC with domains model: https://casbin.org/docs/en/rbac-with-domains

**Comment by hsluoyz** [comment]
Closed as resolved.
