### ISSUE TITLE
casbin在大规模使用的bug

### ISSUE THREAD

**Issue by listen-lavender** [casbin/casbin#244]
<img width="1116" alt="bug" src="https://user-images.githubusercontent.com/4168558/59668111-7d2d3400-91ea-11e9-9365-7ca5428e323c.png">
rbac模型，当casbin_rule数据量比较大的时候（10万左右），h.Enforcer.AddRoleForUserInDomain和h.Enforcer.DeleteRoleForUserInDomain方法都会触发上图规则数据在内存全量重建，会引起业务接口的性能问题（影响业务超时10s）；而且第一次应用启动的时候也会很慢，影响生产环境的二次部署。所以不要因为casbin的宣传很多就轻易使用，并且不建议在生产环境大规模使用casbin，但是所谓的ACL、RBAC、ABAC等权限控制模型还是值得学习的。

如果有大规模的时候，可以允许casbin的一定程度的性能损耗。建议不要使用内存的规则，关闭内存数据的创建和更新，直接使用redis、mongo之类的做adapter，查询数据不走内存，直接查redis、mongo。

**Comment by hsluoyz** [comment]
Hi @listen-lavender , can you use English in the issue title and content?

**Comment by listen-lavender** [comment]
Sorry, I am not good at translating.
