### ISSUE TITLE
How would I show/hide elements on frontend based on casbin enforce (nodejs)

### ISSUE THREAD

**Issue by krayis** [casbin/casbin#245]
Can I pass the enforcer function to the frontend to decide if something should be shown?

**Comment by hsluoyz** [comment]
Which frontend framework do you use? React or Vue or Angular?

**Comment by krayis** [comment]
I'm not using a frontend framework. Running an express app with ejs. Could
I mount enforcer to locales?

**Comment by krayis** [comment]
Can anyone give some suggestions on how I can load enforcer to the view of my web app using ejs?

**Comment by hsluoyz** [comment]
We actually have a front-end Casbin implementation called [casbin.js](https://github.com/casbin/casbin-website/blob/master/website/static/js/casbin.js), it is imported in [this commit](https://github.com/casbin/casbin-website/commit/ee916d5891eef18bb743c97299b263a036bb6a47). It is already used in our online editor: https://casbin.org/en/editor

We have plan to extract out as a repo from the website. For now you can use its logic.

**Comment by krayis** [comment]
I checked it out, but my problem is that ejs does not support async functions. I am sending enforcer by the use of locales.
Is there any option in casbin that allows you to do call the enforce method synchronously?

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
@krayis  Is it like this ?
```
app.post('/', async (req, res) => {
  const result = await e.enforce(......)
  res.render('index', result)
})
```

**Comment by hsluoyz** [comment]
Hi @krayis , this issue is in the wrong place (this repo is for Golang Casbin only).

- If your issue is related to back-end (Node.js), please go to: https://github.com/casbin/node-casbin/issues
- If your issue is related to front-end (js), please go to: https://github.com/casbin/casbin.js/issues

I will close this issue for now.
