### ISSUE TITLE
Custom rules, Enforce is not available

### ISSUE THREAD

**Issue by GanymedeNil** [casbin/casbin#251]
model

```ini
[request_definition]
r = sub, dom, project, obj, act

[policy_definition]
p = sub, dom, project, obj, act

[role_definition]
g = _, _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom, r.project) && r.dom == p.dom && r.project==p.project && keyMatch2(r.obj, p.obj) && regexMatch(r.act, p.act) || p.sub == "root"
```

```go
func main(){

	e := casbin.NewEnforcer("rbac_with_domains_model.conf")

	e.EnableLog(true)
	e.AddPolicy("admin1","domain1","p1","/a/b/:c","GET")

	e.AddGroupingPolicy("alice","admin1","domain1","p1")

	if e.Enforce("alice","domain1","p1","/a/b/1","GET"){
		fmt.Println(true)
	}else{
		fmt.Println(false)
	}

}
```
Enforce returns false

**Comment by hsluoyz** [comment]
Hi @GanymedeNil , the ``g`` rules only support [two args](https://casbin.org/docs/en/rbac) or [three args](https://casbin.org/docs/en/rbac-with-domains). Four args are not supported.

**Comment by GanymedeNil** [comment]
> 嗨@GanymedeNil，`g`规则只支持[两个args](https://casbin.org/docs/en/rbac)或[三个args](https://casbin.org/docs/en/rbac-with-domains)。不支持四个args。

Will there be plans to support multiple parameters later?

**Comment by hsluoyz** [comment]
You can use it like: ``g(r.sub, p.sub, r.dom + "::" + r.project)`` with 3 args.

**Comment by GanymedeNil** [comment]
> You can use it like: `g(r.sub, p.sub, r.dom + "::" + r.project)` with 3 args.

Yes, I solved it in this way, thank you.
