### ISSUE TITLE
After adding a new user, log in with a new account. Sometimes the query will not be queried when the page is refreshed.

### ISSUE THREAD

**Issue by mrsongindezhou** [casbin/casbin#252]
This is the log printed when adding a new user.
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/15610088/60468277-b5714f80-9c8b-11e9-93e6-9df05d641e8b.png">

Corresponding code
<img width="741" alt="image" src="https://user-images.githubusercontent.com/15610088/60468303-c7eb8900-9c8b-11e9-8d52-5147c1e128db.png">

Below is an interceptor method and a screenshot of the log
<img width="782" alt="image" src="https://user-images.githubusercontent.com/15610088/60468337-e2bdfd80-9c8b-11e9-833a-11767317b51d.png">

When the request is successful, the log is printed as shown below.
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/15610088/60468688-fb7ae300-9c8c-11e9-9988-178e5daed4f1.png">
Request failure failed to query the permissions as shown below
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/15610088/60468723-16e5ee00-9c8d-11e9-92d4-b6024449356c.png">

<img width="964" alt="image" src="https://user-images.githubusercontent.com/15610088/60476053-a3ec6f80-9cac-11e9-9a24-782155c98cff.png">

**Comment by hsluoyz** [comment]
Hi @mrsongindezhou , to keep this project international, can you translate all texts here (issue title, content) into English? When it's done, I will answer your question :)

**Comment by hsluoyz** [comment]
After you call ``e.AddRoleForUser()``, Casbin will internally call ``e.BuildRoleLinks()`` to rebuild the RBAC inheritance hierarchy. Make sure your ``e.Enforce()`` call is after ``e.BuildRoleLinks()`` finishes.

**Comment by mrsongindezhou** [comment]
Thanks, but my question is that when I refresh, sometimes I can't get permission, but sometimes I can get it.

**Comment by hsluoyz** [comment]
I don't quite understand the "refresh" you mean, can you provide a minimized working example in Golang, which can exactly show your problem. There are too many unrelated stuff in your description and code.

**Comment by hsluoyz** [comment]
Closed as stale.
