### ISSUE TITLE
how to release watcher

### ISSUE THREAD

**Issue by henrykin** [casbin/casbin#253]
how can i release watcher, after my transcation is done?
if i do not release watcher, other enforcer's change will trigger this watcher's callback which will occur error:sql: transaction has already been committed or rolled back.
I am using casbin-redis-watcher and i found the same problem in etcd-watcher in which i can not stop the watcher goroutine by myself.

**Comment by hsluoyz** [comment]
Hi @henrykin , your question is very important. Actually I didn't think of releasing the watcher carefully when designing it. We have the finalizer as follows:

https://github.com/billcobbler/casbin-redis-watcher/blob/69cab1cdcf44f298b405920bcc56809a21ea7cfa/watcher.go#L162-L165

But it's a private function and you cannot directly call it. You have to use ``defer watcher`` and wait for Go runtime to release the watcher when the function returns. When the watcher is releases, ``finalizer()`` will be called automatically. The tragedy here is that you have to wait for the end of the function to actually release it.

Maybe a workaround is to put ``defer watcher`` into a function and then call this function. Then when the function returns, all things are done.

Of course, we will also try to add an explicit ``Close()`` method to make it straightforward. But it's a breaking change and we will only do that for the next big release like 2.x.

**Comment by henrykin** [comment]
I am willing to do that

**Comment by billcobbler** [comment]
Thanks for the heads up @henrykin. I've added the `Close()` method to redis-watcher [here](https://github.com/billcobbler/casbin-redis-watcher/commit/1a7b7355ee81302faf73853115f61deb1eee3646), but it'll also need to be added to the persist.Watcher interface.

**Comment by hsluoyz** [comment]
Hi @henrykin @billcobbler , I have added the ``Close()`` method to Watcher interface: https://github.com/casbin/casbin/commit/a0dcac37067c1c2e98b0f3abd879b4fdb276cc19

**Comment by hsluoyz** [comment]
Hi, Casbin watcher authors @AleF83, @Grepsr, @vincentmrg

https://github.com/Soluto/casbin-nats-watcher
https://github.com/grepsr/casbin-zk-watcher
https://github.com/livingpackets/cloudpubsub-watcher

We decide to add a ``Close()`` method to Watcher interface to let the users explicitly close and release the watcher. So please add a ``Close()`` method to the Watcher implementation to follow the interface. You can follow the example here: https://github.com/billcobbler/casbin-redis-watcher/commit/1a7b7355ee81302faf73853115f61deb1eee3646. Thanks for your cooperation!
