### ISSUE TITLE
watcher load policy before transaction commit

### ISSUE THREAD

**Issue by henrykin** [casbin/casbin#254]
hi! I found a problem using transaction and watcher.
step 1. begin a transaction
step 2.update db including casbin_rule
step 3.update other tables
step 4.commit transaction

Wachers will publish and subscribe message in the step 2, so other instances will call LoadPolicy immediately. However transaction is not committed when other instances LoadPolicy, which means they can not get the changes.

**Comment by henrykin** [comment]
I create a pr for casbin-redis-watcher.It will solve the problem ,but I don't know whether it's following your design.
https://github.com/billcobbler/casbin-redis-watcher/pull/5

**Comment by hsluoyz** [comment]
Hi @henrykin , what issue are you trying to solve? Can you describe it in more details? AFAIK, the watcher is definitely not atomic.

**Comment by henrykin** [comment]
Sorry.I mean when I am using both transaction and watcher,  and the watcher will publish update message when I call most create/update/delete methods of Enforcer in a transaction. The other watchers in other instances will subscribe the update message and LoadPolicy immediately. But my transaction is not committed yet. I think other instances should call LoadPolicy after the transaction is committed, otherwise the LoadPolicy of other instances would not load the changes of the transaction.
And my pr is to add a channel which send a message after transaction is committed, and util a message is sent to the channel, the Publish action will not be done.

**Comment by hsluoyz** [comment]
Can you make a PR?

**Comment by bingmwu** [comment]
Any fix for JCasbin in the near future? We have experienced exactly the same issue.

**Comment by hsluoyz** [comment]
@bingmwu what's your suggestion for a fix?

**Comment by bingmwu** [comment]
@hsluoyz We used a work around, leveraging  @TransactionalEventListener for now:

- A CasbinPolicyChangedEvent is created, and is published right after the enforcer API is called to update the policy, for example:

```
        enforcer.addGroupingPolicy(policyRule);
        final CasbinPolicyChangedEvent event = CasbinPolicyChangedEvent.builder().policy(policyRule)
                .policyOperationType(PolicyOperationType.ADD_GROUPING_POLICY).build();
        applicationEventPublisher.publishEvent(event);
```

- Use a event listener to update watcher again, after transaction is committed. This would result in the Casbin policies in memory being refreshed twice, for each policy update on any Casbin instane, but it's the simplest, as long as the performance is not a concern now:

```
public class CasbinPolicyChangedEventListener {
    private final Watcher watcher;

    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)
    public void updateWatchAgain(CasbinPolicyChangedEvent event) {
        log.info("Update watch again for event {}" , event);
        watcher.update();
    }
}
```

**Comment by jamesislebron** [comment]
I have experienced the same issue too, while there is another error occur in my project.
I am using both transaction and watcher. In a single transaction, there would be 3 addPolicy actions.
It would happen error like flowing by accident:
`fatal error: concurrent map writes

goroutine 68 [running]:
runtime.throw(0x1309f8b, 0x15)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc00055e890 sp=0xc00055e860 pc=0x439332
runtime.mapassign_faststr(0x1153800, 0xc0005506f0, 0xc000a1a000, 0x48, 0xc00015a978)
        /usr/local/go/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc00055e8f8 sp=0xc00055e890 pc=0x416311
github.com/casbin/casbin/v2/model.Model.AddPolicy(0xc0001970e0, 0x12f7625, 0x1, 0x12f7625, 0x1, 0xc0006c0280, 0x3, 0x4)
        /root/go/pkg/mod/github.com/casbin/casbin/v2@v2.16.0/model/policy.go:142 +0x2d3 fp=0xc00055e968 sp=0xc00055e8f8 pc=0x5deb73
github.com/casbin/casbin/v2.(*Enforcer).addPolicy(0xc000146600, 0x12f7625, 0x1, 0x12f7625, 0x1, 0xc0006c0280, 0x3, 0x4, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/casbin/casbin/v2@v2.16.0/internal_api.go:45 +0x1ce fp=0xc00055ea08 sp=0xc00055e968 pc=0x8016ae
` 
It seems that the second "addPolicy action" and the watcher were both updated the enforcer at the same time, while it cause the "concurrent map writes" error.

Finally, is there any fix or enhancement for  this  ? Thanks a lot.

**Comment by hsluoyz** [comment]
@jamesislebron plz use SyncEnforcer to sync the addPolicy() calls.

**Comment by hsluoyz** [comment]
@RobotHuang plz follow up this issue.

**Comment by RobotHuang** [comment]
@jamesislebron any update? Maybe you could paste your source code here?

**Comment by hsluoyz** [comment]
Closed as stale.
