### ISSUE TITLE
Setting the table prefix of Gorm in the project will affect the table prefix of casbin

### ISSUE THREAD

**Issue by echobool** [casbin/casbin#255]
Setting the table prefix of Gorm in the project will affect the table prefix of casbin

panic: Error 1146: Table 'casbin.gn4u38i_casbin_rule' doesn't exist

**Comment by hsluoyz** [comment]
Hi @echobool , you should send the PR to Gorm adapter repo: https://github.com/casbin/gorm-adapter and refer to the faulty code. Not in this repo.

**Comment by echobool** [comment]
@hsluoyz ok
