### ISSUE TITLE
distributed microservices world

### ISSUE THREAD

**Issue by vtolstov** [casbin/casbin#256]
firstly thanks for this great package!

i have distributed system in different locations on each location i have 3 casbin services that checks policy. I'm already use custom adapter (store in database/key val). If i modify policy model and need to reload policy in all casbin services what is the best and error prone method?
I see that i can use StartAutoLoadPolicy but this is not atomic (provide atomic update of policy model not really possible in case of different locations).
Also i see watcher. If i'm provide sync of data by my own code, and use watcher, does i need something else to provide atomic loading of policy when changing policy model?

**Comment by hsluoyz** [comment]
Hi @vtolstov, the Casbin policy saving and loading are performed by adapters, which use the standard client/SDK of the database. If you want to make the operation atomic, you should make the access to DB atomic. For example, if your DB is a RDBMS, then probably the adapter already saves or loads rules in a transaction, which is atomic.

Therefore, simply speaking, whether it's atomic is determined by your DB and the adapter, not Casbin.

**Comment by vtolstov** [comment]
but if my backend does not provide atomic updating, and i want to atomic reload rules after i know that backend sync data across all needed locations?

**Comment by hsluoyz** [comment]
OK. Then how do you want Casbin to know the backend is ready? Can the backend also send a notification message like how Casbin Watcher's ``Update()`` method does?

**Comment by vtolstov** [comment]
Yes, backend can notify when data are synced.
Now i have two db tables one for casbin policy rules (user and group access) (casbin policy csv analog)
and the second for casbin policy model (casbin policy config conf analog).
Each of this data can be changed via admin ui, so i need to notify casbin services to reload rules.
Yes i can do external api for such thing and reload all stuff when needed, but i don't understand does this needs to be in casbin or in external tool?

**Comment by hsluoyz** [comment]
I think it can be outside of Casbin for now. For example, check whether the backend is ready on your own, when ready, then call ``watcher.Update()`` to send the notification to other Casbin instances.

**Comment by vtolstov** [comment]
ok, thanks
