### ISSUE TITLE
[question] lock of SyncedEnforcer

### ISSUE THREAD

**Issue by henrykin** [casbin/casbin#257]
Hi! I have a question about SyncedEnforcer, why all read operations in SyncedEnforcer added write lock but not read lock? Is there any consideration?

**Comment by vtolstov** [comment]
I don't think so. check https://github.com/casbin/casbin/blob/master/enforcer_synced.go#L96 RLock/RUnlock

**Comment by henrykin** [comment]
I am sorry I didn't describe well. The methods in rbac_api_synced.go 
like https://github.com/casbin/casbin/blob/ae826fd9c117c839198e23e93e34df2234fa7910/rbac_api_synced.go#L32

**Comment by henrykin** [comment]
I am sorry I didn't description clear. The methods in rbac_api_synced.go like [https://github.com/casbin/casbin/blob/master/rbac_api_synced.go#L25](url)

**Comment by hsluoyz** [comment]
Hi @henrykin , that's a bug, can you make a PR to solve it?

**Comment by henrykin** [comment]
Thank you very much !
