### ISSUE TITLE
EnableEnforce(false) but with logging enabled

### ISSUE THREAD

**Issue by vtolstov** [casbin/casbin#259]
i want to have analog of selinux permissive mode. so you have in log all errors and actions, but always allow access. Does this possible with casbin?
I'm try to 
EnableLog(true)                  
EnableEnforce(false)              
but in this case no logs output. If i'm enable enforce, logs are present, but permissions disabled/enabled.

**Comment by hsluoyz** [comment]
You can call ``enforce()``, and do not use the return value.

**Comment by vtolstov** [comment]
this needs to modify source code, or create ugly if/else
why not EnableEnforce(false) not disables logging?

**Comment by hsluoyz** [comment]
Because false causes return immediately in the code.
