### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by obashistu** [casbin/casbin#261]
**Panic is an awful way to handle errors (internal_api.go)**. 

If I can add a policy to the model via the enforcer but then fail to persist it or the watcher function fails I should be returned an error to allow me to either roll the addition back or ignore it. Looking at the safe enforcer implementation which simply recovers from panics is a poor way of addressing the issue as it never solves the root issue which is - something went wrong, handle it!.

For this I would strongly advise on the propagation of constant/sentinel errors which allow for better error based decision making. For example: there are a finite ways in which adding a policy can fail - as a caller I just need to know at which point the failure occurred to allow me to decide what to do next. This approach works well with detailed logging via something like Zap as I get detailed logging of what actually happened (devs want this) along with a sentinel error to help me decide at runtime what to do with the condition (end users will benefit from this). 

I raise this because I wonder how open the maintainers would be to implementing this or accepting a PR for it in a non-intrusive way (facading)?

**Comment by hsluoyz** [comment]
Most of the functions have return the error, which functions do you want to add error return?
