### ISSUE TITLE
something wrong with go.mod?

### ISSUE THREAD

**Issue by vtolstov** [casbin/casbin#267]
i'm try to go get github.com/casbin/casbin@v2.0.0
but in local go.mod file i'm always have
github.com/casbin/casbin v0.0.0-20190712023727-2cd38e82a491

**Comment by ntrianta** [comment]
For versions v2 and greater, the corresponding changes have to be made in the module declaration of the project according to this specification: https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

Could this please be fixed to ensure that workflows can still work? 

Thanks!

Nick

**Comment by hsluoyz** [comment]
@ntrianta , thanks for the explanation!

@vtolstov , I have provided the fix: https://github.com/casbin/casbin/commit/cf0098690c0b281619e459c5780eaf4b27f77e00, can you try again?

**Comment by vtolstov** [comment]
Yes, nice fix. May be you need to add info to readme that users of this package need to have github.com/casbin/casbin/v2 in import paths

**Comment by hsluoyz** [comment]
Actually the import path is not necessary to update, see this: https://github.com/casbin/xorm-adapter
