### ISSUE TITLE
panic: interface conversion: *gormadapter.Adapter is not persist.Adapter: missing method LoadPolicy

### ISSUE THREAD

**Issue by pengshaomin** [casbin/casbin#273]
![image](https://user-images.githubusercontent.com/17870116/62761649-c480c400-bab9-11e9-87e3-1a439c7e5edd.png)

用的官方例子，接口都实现还是报错

**Comment by hsluoyz** [comment]
Please try Casbin 2.x

**Comment by pengshaomin** [comment]
replace github.com/casbin/casbin/v2
It work fine! 
Thanks

**Comment by baronwithyou** [comment]
Just make sure your adapter and casbin are of the same version.

for example:
```
import (
	"github.com/casbin/casbin/v2"
	gormadapter "github.com/casbin/gorm-adapter/v2"
)
```
