### ISSUE TITLE
Issue with performance of Python Implementation.

### ISSUE THREAD

**Issue by aaaaale** [casbin/casbin#278]
We have profiled a simple Casbin enforcement call over an (admittedly abnormally large) policy set. We did this with a go and a python script. The python version takes about 30x the time per enforcement call (1.5 seconds on an i5).

2 things I would like to ask the authors (who suggested I opened this issue): 
1. does it check out that the Python implementation would take so much more than the go one?
2. even in go, Enforce takes a time that grows linearly with the number of policies, even when the actual policy being asked is laid out explicitly in the policy file (naively, I'd say a lookup shouldn't take linear time, but then we're using a model with deny). Is this normal?

I am attaching a zipfile with the go script, the python script, the model, and the policy file.

[perf.zip](https://github.com/casbin/casbin/files/3520035/perf.zip)

**Comment by hsluoyz** [comment]
@techoner

**Comment by hsluoyz** [comment]
Hi @aaaaale , if you are complaining about PyCasbin's performance, please open issue there: https://github.com/casbin/pycasbin
