### ISSUE TITLE
Initialize the model from Go code

### ISSUE THREAD

**Issue by basefas** [casbin/casbin#279]
When I want to initialize the model from Go code, the docs say that I should use
```go
import  "github.com/casbin/casbin/v2"

m := casbin.NewModel()
```
I tried it but got something error, so I found code below can be right.
```go
import  "github.com/casbin/casbin/v2/model"

m := model.NewModel()
```
So is this the right way to initialize the model, the docs is wrong.
Or the docs is what we want ,the code need be improved.

**Comment by hsluoyz** [comment]
Hi @basefas , I think the docs is wrong. Can you help fix the docs by making a PR ?

**Comment by basefas** [comment]
@hsluoyz  fixed.

**Comment by hsluoyz** [comment]
Thanks!
