### ISSUE TITLE
RBAC with resource roles and RBAC

### ISSUE THREAD

**Issue by neelofer-appdirect** [casbin/casbin#281]
Hi,

We are evaluating Casbin for our project that has REST APIs like this:
1. `/parent/{parentID}`
2. `/parent/{parentID}/child1/{child1ID}`
3. `/parent/{parentID}/child2?queryParam={child2ID}`

We want to deny everything to a subject unless allowed by a policy. 

**Configuration:**
```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = keyMatch(r.sub, p.sub) && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act) && !some(where (p.eft == deny))
```

**Policies:**
```csv
p, *, /parent/*, GET, allow
p, *, /parent/(1)|(2)/child2?queryParam=(1)|(2), GET, allow
```

**Expected results:**
```
me, /parent/1, GET -> true
me, /parent/3, GET -> true
me, /parent/1/child2?queryParam=2, GET -> true
me, /parent/3/child2?queryParam=2, GET -> false
me, /parent/1/child2?queryParam=3, GET -> false
```

**Actual results:**
All true

Please help define the policies / configuration rules for our requirement. Thank you. I've tried couple of things, but they have not worked.

**Comment by hsluoyz** [comment]
@nodece , can we implement this? ``p, *, /parent/(1)|(2)/child2?queryParam=(1)|(2), GET, allow``

**Comment by nodece** [comment]
@hsluoyz Recommend custom keyMatch function.

**Comment by hsluoyz** [comment]
@nodece , can we add a function for him?

**Comment by neelofer-appdirect** [comment]
Thank you both of you for quick response. 

Meanwhile for the other APIs I have another question on how to get this working: 
`/parent/{parentID}`
`/parent/{parentID}/child1/{child1ID}` 

**Policies:**
```
p, *, /parent/*, GET, allow
p, *, /parent/(1)|(2)/child1/(1)|(2), GET, allow
```

**Expected results:**
```
me, /parent/1, GET -> true
me, /parent/3, GET -> true
me, /parent/1/child1/1, GET -> true
me, /parent/3/child1/1, GET -> false
me, /parent/1/child1/3, GET -> false
```

**Actual results:**
All true

**Comment by hsluoyz** [comment]
```
me, /parent/3/child1/1, GET -> false
me, /parent/1/child1/3, GET -> false
```

Casbin doesn't know to match 1 with 3.

**Comment by nodece** [comment]
@hsluoyz It seems impossible. Casbin doesn't know to match.

**Comment by neelofer-appdirect** [comment]
Is there any other way to check for a match when using more than one variable in a single REST API request?

**Comment by nodece** [comment]
Hi @neelofer-appdirect, See: https://casbin.org/docs/en/syntax-for-models#how-to-add-a-customized-function.

**Comment by hsluoyz** [comment]
@nodece we can capture all the vars, then compare them in code.

**Comment by hsluoyz** [comment]
Hi @neelofer-appdirect , ``keyMatch4()`` is added to solve this: https://github.com/casbin/casbin/commit/8e9b785498b544463e30f055e3a012a0d32fba64

Test:

```go
func TestKeyMatch4(t *testing.T) {
	testKeyMatch4(t, "/parent/123/child/123", "/parent/{id}/child/{id}", true)
	testKeyMatch4(t, "/parent/123/child/456", "/parent/{id}/child/{id}", false)

	testKeyMatch4(t, "/parent/123/child/123", "/parent/{id}/child/{another_id}", true)
	testKeyMatch4(t, "/parent/123/child/456", "/parent/{id}/child/{another_id}", true)

	testKeyMatch4(t, "/parent/123/child/123/book/123", "/parent/{id}/child/{id}/book/{id}", true)
	testKeyMatch4(t, "/parent/123/child/123/book/456", "/parent/{id}/child/{id}/book/{id}", false)
	testKeyMatch4(t, "/parent/123/child/456/book/123", "/parent/{id}/child/{id}/book/{id}", false)
	testKeyMatch4(t, "/parent/123/child/456/book/", "/parent/{id}/child/{id}/book/{id}", false)
	testKeyMatch4(t, "/parent/123/child/456", "/parent/{id}/child/{id}/book/{id}", false)
}
```

**Comment by neelofer-appdirect** [comment]
Thank you @hsluoyz

**Comment by neelofer-appdirect** [comment]
@hsluoyz Is the casbin editor below updated to use keymatch4?
https://casbin.org/en/editor

**Comment by hsluoyz** [comment]
@neelofer-appdirect No.

@nodece can we support it?

**Comment by nodece** [comment]
@hsluoyz Of course! I add this feature as soon as possible.

**Comment by nodece** [comment]
@neelofer-appdirect 
```javascript
var fns = {
  keyMatch4: (key1, key2) => {
    key2 = key2.replace(/\/\*/g, '/.*');

    const tokens = [];
    let j = -1;
    for (let i = 0; i < key2.length; i++) {
      const c = key2.charAt(i);
      if (c === '{') {
        j = i;
      } else if (c === '}') {
        tokens.push(key2.substring(j, i + 1));
      }
    }

    let regexp = new RegExp(/(.*){[^/]+}(.*)/g);

    for (; ;) {
      if (!key2.includes('/{')) {
        break;
      }
      key2 = key2.replace(regexp, '$1([^/]+)$2');
    }

    regexp = new RegExp('^' + key2 + '$');

    let values = regexp.exec(key1);

    if (!values) {
      return false;
    }

    values = values.slice(1);

    if (tokens.length !== values.length) {
      throw 'KeyMatch4: number of tokens is not equal to number of values';
    }

    const m = new Map();
    tokens.forEach((n, index) => {
      const key = tokens[index];
      let v = m.get(key);
      if (!v) {
        v = [];
      }

      if (values) {
        v.push(values[index]);
      }
      m.set(key, v);
    });

    for (let value of m.values()) {
      if (value.length > 1) {
        for (let i = 1; i < values.length; i++) {
          if (values[i] != values[0]) {
            return false;
          }
        }
      }
    }

    return true;
  }

};
```
In Editor, add above code to Custom Function

**Comment by neelofer-appdirect** [comment]
@nodece @hsluoyz The following is not working with KeyMatch4:
Model:
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = keyMatch(r.sub,p.sub) && keyMatch4(r.obj, p.obj) && regexMatch(r.act, p.act)
```

Policy:
```
p, alice , /([^a]|a[^p]|ap[^i]).*$ , GET, allow
p, alice , /([^a]|a[^p]|ap[^i]).*$ , PUT, allow
p, alice , /([^a]|a[^p]|ap[^i]).*$ , POST, allow
p, alice , /([^a]|a[^p]|ap[^i]).*$ , DELETE, allow
```

Request:
```
alice, /something, GET
```

Error:
```
KeyMatch4: number of tokens is not equal to number of values
```

Expected result: `true`

**Comment by leopragi** [comment]
> @nodece , can we implement this? `p, *, /parent/(1)|(2)/child2?queryParam=(1)|(2), GET, allow`

Have you guys implemented this? How to use this? I used keyMatch4, which is not working.

**Comment by nodece** [comment]
@leopragi We doesn't support it. We can only support `g, user, pattern`.

**Comment by nodece** [comment]
>Have you guys implemented this? How to use this? I used keyMatch4, which is not working.

We only support `g, pattern, role/user`

> w do I ignore query params? currently, I m removing it manually.

Casbin doesn't remove query params from URL. Let's give it to a user for better handling.

**Comment by hsluoyz** [comment]
Please send new issues for new questions.
