### ISSUE TITLE
how to use casbin in a database permission system

### ISSUE THREAD

**Issue by yywf** [casbin/casbin#282]
I want to use casbin in my database permission system. And I need three object to defines my access resources, they are db, table, colums (eg. db1, table1, *;    db2, table2, column1/column2; 
  db3, *, *;). but I found that casbin has only one object. So how to use one object to define three object.
thanks.

**Comment by hsluoyz** [comment]
You can define ``obj, obj2, obj3`` or other names together.

**Comment by hsluoyz** [comment]
Closed as solved.
