### ISSUE TITLE
Build fails when using cabin.

### ISSUE THREAD

**Issue by vivekthangathurai** [casbin/casbin#284]
I am using Casbin in a project with Go module enabled. I am getting an error on code when building it. But without Go modules it works.
Casbin version:  v1.9.1
Go version go1.12.1
```
e , err := casbin.NewEnforcer("rbac.conf", "policy.csv")

```
```
assignment mismatch: 2 variables but casbin.NewEnforcer returns 1 values

```

**Comment by nodece** [comment]
@vivekthangathurai  
`go get -u github.com/casbin/casbin/v2`

**Comment by mintzhao** [comment]
@nodece  did not work with go1.12, go 1.13

**Comment by hsluoyz** [comment]
See: https://github.com/casbin/casbin/issues/267
