### ISSUE TITLE
https://casbin.org/docs/en/get-started#persistence persistence isn't present

### ISSUE THREAD

**Issue by chmorgan** [casbin/casbin#285]
https://casbin.org/docs/en/get-started#persistence doesn't go anywhere.

**Comment by hsluoyz** [comment]
Hi @chmorgan , can you send a PR to fix it? https://github.com/casbin/casbin-website

**Comment by chmorgan** [comment]
Hi @hsluoyz I couldn't tell where it should have gone or I would have submitted a PR to fix it. If you had more info I can submit one.

**Comment by hsluoyz** [comment]
The source code is: https://github.com/casbin/casbin-website/blob/master/docs/GetStarted.md

BTW, this issue should also be in that repo, instead of this one.

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casbin-website/commit/aee565ae49e63581eb77c77d52298efb070885cb
