### ISSUE TITLE
Looking for abac example

### ISSUE THREAD

**Issue by chmorgan** [casbin/casbin#286]
I was able to put together an rbac example using the tutorial and other info but I’m stumped as to how one should be using Casbin with abac. I’ve heard abac is the new hotness and unfortunately I’m not yet versed in abac or Casbin enough to put the two together.

I’ve created an example from the abac page docs and it authorizes but it looks like I have to pass the same subject and multiple policies into each enforcement call, it isn’t obvious how to use a data store to hold the policy data. I mention this because I did try to figure out how I might use it but can’t put the pieces together.

A more real world example would help a ton.

**Comment by hsluoyz** [comment]
Can you give an example about what kind of grammar you want to achieve in Casbin policy?

**Comment by chmorgan** [comment]
Hi @hsluoyz. I wasn't sure if you remember me from sharppcap or not but I recognized your GitHub handle.

I appreciate that you are even asking me that question. My knowledge of abac is weak at the moment but let me lay out the idea (based on my actual use case), it isn't unique so it may be a helpful example to others.

I'd like to:
- Store policies in a database
- Support controlling access to read/write/delete various things such as devices that represent IoT devices by a user, these are restful API endpoints like:
-- http DELETE of /device/1234
-- or storing data like http POST to /device/1234/status
-- or reading the last status like GET /device/1234/status
- Permit an admin that has access to everything.
- Consider manager accounts, if the service is sold through distributors it would be helpful for them to be able to monitor their customers systems, for example

So maybe what I want is RBAC but without seeing the "why" of ABAC through a real example it's tough to see why I might use it.

Anyway, this isn't a Casbin specific question, and congrats on another cool project, in addition to Npcap.

**Comment by hsluoyz** [comment]
Hi @chmorgan , I also found that you are from SharpPcap. Thanks for using my second project. This world is pretty small :)

> Store policies in a database

Use an adapter

> Support controlling access to read/write/delete various things such as devices that represent IoT devices by a user, these are restful API endpoints like:

See the RESTful example: https://casbin.org/docs/en/supported-models

> Permit an admin that has access to everything.

See the ACL with superuser example: https://casbin.org/docs/en/supported-models

> Consider manager accounts, if the service is sold through distributors it would be helpful for them to be able to monitor their customers systems, for example

See the RBAC with Domains model: https://casbin.org/docs/en/rbac-with-domains

Your every requirement is solved without ABAC. I'm not seeing any reason that you have to use ABAC. ABAC seems to only mean to retrieve the attribute from an object.

**Comment by chmorgan** [comment]
Hi @hsluoyz.

That works for me and was close to the solution I was coming to. It looks like I'll be using Casbin so I'll keep my eye open for ABAC examples to learn more about them. Thank you for your detailed response and see you around!
