### ISSUE TITLE
API needed: get all roles of an user which match permission [object, act]

### ISSUE THREAD

**Issue by liuhuiping2013** [casbin/casbin#287]
user may have several roles, and at least two roles have permission for [object, act].
we need the matched result [roles] in array.

is this requirement reasonable?

**Comment by nodece** [comment]
@liuhuiping2013  You can get all the roles through `GetFilteredPolicy`.

**Comment by liuhuiping2013** [comment]
policy file:
```
p, alice, data1, read
p, bob, data2, write
p, data1_visitor, data1, read
p, data2_admin, data2, read
p, data2_admin, data2, write

g, alice, data2_admin
g, alice, data1_visitor
```
query
```
alice, data2, read
```
i want return
```
data2_admin
```

i want the subset of alice's roles which match permission for [object, act].

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
@liuhuiping2013 Filter the `getImplicitPermissionsForUser("alice")` return values.

**Comment by hsluoyz** [comment]
Closed as resolved.
