### ISSUE TITLE
Multi Tenant authz design

### ISSUE THREAD

**Issue by hdh3000** [casbin/casbin#289]
Disclaimer: I am unfamiliar with casbin, so help in clarifying the question is much appreciated...

I am trying to design an RBAC based authorization model for access to resources for a retail based env
That means that I have multiple tenants, and each tenant has multiple stores.

Certain resources ("company profile") are not scoped to stores, while others ("store profile") are.

Access for certain users, "store-managers" should be allowed only for their own store (i.e. store managers can only update the profile for their own store). Other users should be able to edit all store scoped resources, and tenant scoped resources (i.e. admins should be able to edit the company profile, and all the store profiles). 

I would like to accomplish this without having to restate the same policy for every tenant + store. That will be hard to maintain/ update.

**Comment by hsluoyz** [comment]
You should give an example model and policy, and ask something like ``whether this kind of grammar is supported?`` instead of describing a lot of text.

**Comment by hsluoyz** [comment]
@hdh3000 Is this thread still alive? Do you want regex in g() ?

**Comment by hsluoyz** [comment]
You can split the matcher into two parts:

```ini
m = <cross-tenant logic> | <tenant-specific logic>
```

Then you can have policy rules for cross-tenant logic part. Such rules are the same for every tenant, and only appear once.
