### ISSUE TITLE
Having issues with RBAC with deny-override

### ISSUE THREAD

**Issue by grimmy** [casbin/casbin#290]
This is a pretty in depth issue so I'll try to keep it simple.  However, I do have a full test suite of what I'm trying to do available at https://hg.sr.ht/~grim/casbin-test.  It's public but please note it's using mercurial and not git.

Alright, so the problem.. I'm using a nearly stock example of RBAC with deny-override for my model, but with a few differences...  But first lets take a look at the model:

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = (g(r.sub, p.sub) || p.sub == "public") && keyMatch(r.obj, p.obj) && access(r.act, p.act)
```

`public` is a custom subject that if no other rules match, this should be checked (this assumption is part of the problem).

`access` is a custom function that helps me to avoid having to add additional policies, basically `init` grants `init`, `write`, and `read`, `write` grants `write` and `read`, and `read` just grants `read`.

`keyMatch` is used in the matcher because as we'll see below with the policies, everything is based on a path hierarchy.  The idea is that by default everyone has implicitly has read access to everything but that can be removed later.

Here is a super stripped down version of the policy file.

```
p, public, /*, read, allow
p, admins, /*, init, allow
p, public /admin, read, deny

g, grimmy, admins
```

So the problem comes in with the `effect_policy` when trying to `deny` read to `public` on `/admin`.  That `deny` does what it's supposed to do, and denies everything and not just `public`.

I initially thought I worked around this with the `g(r.sub, p.sub) || p.sub == "public"` in the matcher, but that just creates another matching policy that breaks `admins` ability to `read` `/admin`.  Note that this matcher rule is working as designed to implicitly grant `read` to users that do not have an explicit `read` policy.

So essentially, I think I might need a custom matcher function, but even then I'm not sure if that'll work.  It seems more like I need a custom `policy_effect`, but I looked at the interface for that, and it doesn't look like I'll have enough data to pull the subject out.

I was thinking if I could do something like if we have only denies where `p.sub == "public"` then that could trip the deny override and I'd be good to go.  But as I mentioned, I didn't see a way to get the request or policy let alone their subjects to be able to implement that.

So looking for any suggestions on how to make this work.  I did also try to use the ACL model, but again with overlapping policies I get failures all over the place.

**Comment by hsluoyz** [comment]
Hi @grimmy ,

> access is a custom function that helps me to avoid having to add additional policies, basically init grants init, write, and read, write grants write and read, and read just grants read.

You don't need a custom function here. You can just use RBAC for action, like ``g2(r.act, p.act)``

> So the problem comes in with the effect_policy when trying to deny read to public on /admin. That deny does what it's supposed to do, and denies everything and not just public.

Use the priority model, see this: https://github.com/grafana/grafana/issues/8584

**Comment by QuLogic** [comment]
You can pass all the tests by setting effect policy to `priority(p.eft) || deny` and then re-ordering the policy to:
```
p, pidgin_admin, /pidgin/security/*, init, allow
p, pidgin, /pidgin/security/*, init, deny
p, public, /pidgin/security/*, read, deny
p, pidgin, /pidgin/*, init, allow

p, adium_admin, /adium/*, init, allow
p, adium, /adium/*, write, allow

p, admins, /hgkeeper, write, allow
p, public, /hgkeeper, read, deny
p, admins, /*, init, allow
p, public, /*, read, allow
```

**Comment by grimmy** [comment]
Sorry forgot to reply, but by using the priority policy effect and reordering my policy i did get this to work, thanks again :)
