### ISSUE TITLE
How to have regex on a relation?

### ISSUE THREAD

**Issue by shlomi-nx** [casbin/casbin#291]
It is easy to make a relation:
`m = g(r.sub, p.sub)`

but I would like to specify a regular expression, something like
`m = g(regexMatch(r.sub, p.sub))` 
where in the policy I can put regexs:

`
g, .*@tenant.com, tenant_role
`
Is something like this possible to do?

**Comment by techoner** [comment]
Add a customized function:
https://casbin.org/docs/en/syntax-for-models#how-to-add-a-customized-function

**Comment by shlomi-nx** [comment]
How could customized functions access or influence relations? How do I make, say, a custom `regex_rel(g, a, b)` that applies the regex logic for relation `g` based on `a` and `b`?

**Comment by hsluoyz** [comment]
Hi @shlomi-nx , see: https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac
