### ISSUE TITLE
Add HasImplicitPermissionsForUser()

### ISSUE THREAD

**Issue by Pokerkoffer** [casbin/casbin#292]
Hi,

is there a reason why there is no `HasImplicitPermissionsForUser()`?
There is a corresponding `HasPermissionForUser()` for `GetPermissionsForUser()` though, however there is no corresponding method for `GetImplicitPermissionsForUser()`.

Regards

**Comment by hsluoyz** [comment]
`HasImplicitPermissionsForUser()` is similar to `Enforce()`.

**Comment by Pokerkoffer** [comment]
Yeah, my bad, thats correct. I assigned permissions (in the form of `<action:object>` e.g. `delete:role`) to roles.

I left the object out, so adding it solves my problem ('edit:role' changes to obj=role, action=edit).

Thank you!
