### ISSUE TITLE
Please add clear guidelines for ABAC

### ISSUE THREAD

**Issue by nicky-lenaers** [casbin/casbin#293]
The Casbin project is extremely helpful for the authorization problem. I've implemented RBAC in my NodeJS project with success. However, I'm now trying to understand ABAC models and policies, but the information on casbin.org and in this repo is very limited. There is no policy I can use as an example.

Please add clear guidelines / examples on how to use ABAC with Casbin.

Thanks!

**Comment by techoner** [comment]
@nicky-lenaers  [ABAC with Casbin in PHP](https://github.com/php-casbin/casbin-tutorials/blob/master/tutorials/ABAC-with-Casbin.md), You can use it as a reference.

**Comment by hsluoyz** [comment]
Hi @nicky-lenaers , what's your requirement/scenario ?

**Comment by nicky-lenaers** [comment]
@techoner Thanks for this reference, it will point me in the right direction 👍 . I do think, however, that the documentation on ABAC may be a lot clearer when an example policy is added.

@hsluoyz I'm new to Casbin. Currently, I'm researching ABAC and the differences with respect to RBAC. I'm trying out different implementation to see what each of these do in Casbin. I kinda come up with use cases along the way.

**Comment by hsluoyz** [comment]
There's no policy in ABAC, only model.

**Comment by hsluoyz** [comment]
@nicky-lenaers ABAC in Casbin currently only means to be able to retrieve the attributes from the request ``r`` in the matcher, e.g., `r.obj.name` instead of just `r.obj`. It's orthogonal with the presence of policy rules. Our ABAC example indeed doesn't have policy rules. But you can always add ABAC on the top of other models like RBAC or ACL.

**Comment by nicky-lenaers** [comment]
@hsluoyz Alright, thank you for clarifying! I'll continue trying out some examples to get the hang of it 😄
