### ISSUE TITLE
Where in casbin is DeleteLink function of roleManager is called?

### ISSUE THREAD

**Issue by vaibhavkhl** [casbin/casbin#294]
Hi, 

I am writing custom role manager and can't find in casbin code how/where it is getting called.

**Comment by hsluoyz** [comment]
Please search the function names for RoleManager interface: https://github.com/casbin/casbin/blob/master/rbac/role_manager.go

**Comment by hsluoyz** [comment]
@vaibhavkhl , it's not called anywhere for now, may be used in future.
