### ISSUE TITLE
 Filter attributes based on role

### ISSUE THREAD

**Issue by hgedia** [casbin/casbin#295]
I understand casbin is mainly used as access control based on enforcment policy, i.e it yields true or false based on the request made.

Is it currently possible in casbin to be used as a filtering layer for data. 
Consider the following data structure
```
type Data struct{
    attr1 string
    attr2 string
}
```
For a service which returns the above structure , is it possible to define a filter which on enforcing does the below:

If Role is admin , return attr1 & attr2 
If Role is user , return attr1 only.

Thanks!

**Comment by hsluoyz** [comment]
See: https://casbin.org/docs/en/rbac#how-to-query-implicit-roles-or-permissions

**Comment by hgedia** [comment]
@hsluoyz  Thanks for your reply. 

Perhaps what i am requesting is best suited for logic outside of casbin.  In the above scenario , I have a service which returns this data structure

```
func Service(userRrole string) Data {
...
}
```

Setting policy something like 
```
p,admin,data.attr1,read
p,admin,data.attr2,read
p,user,data.attr1.read
```

Is there any API in casbin with filters the Data object based on the role  to return the attributes?

**Comment by hsluoyz** [comment]
You can call `GetFilteredGroupingPolicy()`: https://casbin.org/docs/en/management-api#getfilteredgroupingpolicy
