### ISSUE TITLE
How to add multiple policy ?

### ISSUE THREAD

**Issue by nqmt** [casbin/casbin#306]
I see it have ```AddPolicy()``` but it just add one by one policy
if I want to add 2000 policy on db adapter ?

**Comment by nodece** [comment]
Can you make a PR?

**Comment by nqmt** [comment]
@nodece I will find time to do it

**Comment by hsluoyz** [comment]
Any progress?

**Comment by nqmt** [comment]
Sorry I'm doing something else, I haven't time to do it

**Comment by supra08** [comment]
Hi @hsluoyz! I would like to take up this issue if nobody else is working on this.

**Comment by nodece** [comment]
@supra08 looking forward to contributing to it.

**Comment by supra08** [comment]
@nodece sorry I couldn't follow you. Will you be working on it or is it free for me to take it up.

**Comment by nodece** [comment]
@supra08 You can add multiple policy API to casbin.

**Comment by nodece** [comment]
added: #388
