### ISSUE TITLE
Expose `Enforcer` interface

### ISSUE THREAD

**Issue by 7abhishek** [casbin/casbin#318]
Can you expose the `Enforcer` interface, Thus enabling easier unit testing with mocking.(because currently cannot mock `Enforcer`)

**Comment by hsluoyz** [comment]
Not bad. Can you make a PR as a starting point?

**Comment by 7abhishek** [comment]
Sure!

**Comment by 7abhishek** [comment]
@7abhishek created the PR 
https://github.com/casbin/casbin/pull/319

**Comment by hsluoyz** [comment]
Merged.
