### ISSUE TITLE
What about regexp in REST sources?

### ISSUE THREAD

**Issue by hackdan** [casbin/casbin#32]
It's possible match with regexp in the rest paths or option area ? 

Ex 

/alice/*/account
/accounts/{name:[a-z]+}/details

**Comment by hsluoyz** [comment]
Hi @hackdan ,

The answer is yes. You can use the built-in function ``regexMatch(arg1, arg2)`` to match a request element to a regex pattern.

Please refer to: https://github.com/casbin/casbin/wiki/Matchers#functions-in-matchers

**Comment by hsluoyz** [comment]
Suppose it has been solved.
