### ISSUE TITLE
Can we provide HasImplicitPermissionForUser() and HasImplicitRoleForUser()?

### ISSUE THREAD

**Issue by techoner** [casbin/casbin#320]

**Comment by hsluoyz** [comment]
Is this anything different than ``Enforce()``?

**Comment by techoner** [comment]
`HasImplicitPermissionForUser()` just determines if a `policy` is owned, not using `matchers` to `enforce()`.
`HasImplicitRoleForUser()` is an enhancement to `HasRoleForUser()`。

**Comment by hsluoyz** [comment]
OK. Can you make a PR?

**Comment by richsoap** [comment]
Hi~I'm working on it for now. I think not only HasImplicitPermissionForUser() but also HasImplicitPermissionForUserInDomain() is needed. Should I make 2 PR for each or 1 PR including both?

**Comment by hsluoyz** [comment]
1 PR is OK.

**Comment by richsoap** [comment]
OK, I'll make a PR after rebasing.

**Comment by hsluoyz** [comment]
Done:

https://casbin.org/docs/en/rbac-api#getimplicitrolesforuser
https://casbin.org/docs/en/rbac-api#getimplicitpermissionsforuser
