### ISSUE TITLE
Extended RBAC model

### ISSUE THREAD

**Issue by gredin** [casbin/casbin#321]
Hi!

First, thanks for your great access control library.

Here's a summary of my use case:

1) we need users, (shared) accounts and corporations
2) there are several resource/objet types; example:
- shoes with category, brand and date attributes
- books with genre, author and date attributes
3) we need to grant permissions to users/accounts/corporations over a set of objets; a set is defined by attribute values
4) we need to grant permissions within a time range

Points 3) and 4) are beyond a simple RBAC model. In particular, we don't want to grant permissions on single objects, but rather on set of objects (for simplifying administration).

For example, I want to grant "SharedAccount1" read access to:
- shoes of category "running", brand "MyBrand" and date in range [2017, 2019]
- books of genre "novel", author "Matheson" and date in range [1960, 1970]

Point 1) is implemented by hierarchical RBAC, which is supported by Casbin. Point 4) can be implemented as well (related issue: https://github.com/Casbin/Casbin/issues/219).

If we had only one object type, I guess 2) and 4) could be implemented by adding custom fields in request definition and policy definition.
For example:

    [request_definition]
    r = sub, obj, act, category, brand

    [policy_definition]
    p = sub, obj, act, time_from, time_to, category, brand

But, in my use case, there are multiple independent object types. I don't want to add numerous and possibly useless custom fields in request/policy definitions.

I guess it could be easily implemented if we were allowed to use attributes on policies, but Casbin do not support these.

Do you have any idea for implementing this model with Casbin?

**Comment by hsluoyz** [comment]
I think you need RBAC model with resource roles: https://casbin.org/docs/en/rbac#role-definition

**Comment by jkour** [comment]
I think it will help your thinking if you see your SETS as ROLES in RBAC

Also see this dicussion here [#8 ](https://github.com/casbin/Casbin.NET/issues/8)

It may help you

**Comment by hsluoyz** [comment]
@gredin closed as stale. Open it if needed.
