### ISSUE TITLE
stackoverflow tag

### ISSUE THREAD

**Issue by jruizaranguren** [casbin/casbin#322]
I have added `casbin` as a [tag in stackoverflow](https://stackoverflow.com/questions/tagged/casbin), albeit description is still under review. It would be nice if all questions related to modeling business scenarios with PML / casbin would be forwarded to stackoverflow. That way we would have a knowledgebase of "how-tos" more practical than closed issues.

What do you think?

**Comment by hsluoyz** [comment]
That's not bad I think. In fact, I'm answering questions from both channels: GitHub and StackOverflow. In fact, I cannot forbid people from asking questions here. Moreover, I must say personally I like the GitHub editor better a little. Do you have any reasons to prefer StackOverflow than GitHub?

**Comment by jruizaranguren** [comment]
Nop, I also use both. Typically, in most open source projects, problems with install, deploy, bugs, feature requests etc. are managed in github, but more general usage problems, or how to apply them in a broader context are asked in stackoverflow. 
It is not a strong preference, just how things tend to work in other projects I use. A lot of people have stackoverflow as first source of problem-solving. 
Solved problems in stackoverflow can be easily found in the knowledgebase, are nicely related to other ones, etc.
Closed issues in Github get a bit buried. So if your are solving a general problem of interest, for instance "RBAC with Tenants and Pattern Matching", it is not so easy to find unless you explicitly search for closed issues.

**Comment by hsluoyz** [comment]
How do you want to encourage users to ask questions on StackOverflow? Should we put some notice somewhere?

**Comment by jruizaranguren** [comment]
[This could work](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors)

And in the contributing guide, specify what kind of issues you expect to solve here in GitHub (I want an adapter for SQLServer, Function X takes too much time, I can't install un Ubuntu 345), vs what kind of issues are of the stackoverflow kind (How can I create a hierarchy of roles for objects in casbin?), etc.

**Comment by hsluoyz** [comment]
Looks good. Can you make a PR about it?

**Comment by jruizaranguren** [comment]
I will try.

**Comment by hsluoyz** [comment]
@jruizaranguren your link is broken (404): https://github.com/casbin/casbin#how-to-contribute

Please fix.

**Comment by jruizaranguren** [comment]
Done
