### ISSUE TITLE
Can't get v2.1.0 using go modules

### ISSUE THREAD

**Issue by chaelub** [casbin/casbin#324]
Hi guys.

I'm tried to get casbin v2.1.0 using go modules, but I've got an error:

`→ go get github.com/casbin/casbin@v2.1.0
                                                                                                                                                                                            
go: finding github.com/casbin/casbin v2.1.0

go: finding github.com/casbin/casbin v2.1.0

go get github.com/casbin/casbin@v2.1.0: github.com/casbin/casbin@v2.1.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2`

The latest available version is v1.9.1

How can we fix it?

**Comment by hsluoyz** [comment]
You don't need to go get it. Just import it into your project, and Go modules will auto-get the code. See: https://github.com/casbin/xorm-adapter

**Comment by chaelub** [comment]
Sorry for stupid question and thanks a lot =)
