### ISSUE TITLE
How to implement RBAC custom function which has to read information from database?

### ISSUE THREAD

**Issue by acim** [casbin/casbin#326]
I am still considereding using Casbin for RBAC in my project and I have browsed the documentation but still have confusion how to proceed with the following problem. I have some documents in NoSQL database which contain owner_id and owners may eventually shared each particular document with some other users so there may be an array of shared_to_ids (also in the document). I want Casbin to check if an authenticated user is owner of the document or his id is in the shared_to_ids list and allow him access just in this case. How to do this?

I saw you have custom policy functions where this could eventually be implemented, but if I put Casbin as (Go) middleware, this means middleware would access the database document just to check the ownership and shared list and in case the user is authorized it would proceed to other middlewares and controllers and later responsible controller would again have to read the same document in order to fulfil the request. So, in this case we have double access to the database and basically neccesary load.

This makes sense in case you have separate authz microservice, but does not make much sense if you use middleware to authz. With separate authz microservice it also makes sense to have caching and so, but not with middleware.

I thought of having "middleware" actually in database access layer or inside the database (store) abstraction and basically check RBAC (using custom function) after the document has been read from the database and before it get's to the controller. Is this viable?

**Comment by hsluoyz** [comment]
It depends on where the ``owner of the document or his id is in the shared_to_ids list `` information is stored.

1. Casbin usually has a cache for all policy rules in memory. If you can store them into Casbin too (e.g., using a custom adapter to load them into Casbin from your DB, or directly in Casbin format). Then Casbin can perform checking with memory data only.

2. If you cannot store them in Casbin, as a workaround, you can use CachedEnforcer (https://github.com/casbin/casbin/blob/master/enforcer_cached.go) to cache the decisions.

**Comment by acim** [comment]
This info is stored in the database together with the document itself, so it is part of the document basically.

1. This means having a kind of hook on upsert/delete so when a document is saved/deleted in NoSQL, hook takes care that rule(s) are saved/deleted in Casbin as well, right?

This further means both operations (to database and to Casbin) have to be done in one transaction and this rises consistency problems which probably involve using message queues and so on, so difficult solutions.

2. Thank you for the tip.

**Comment by hsluoyz** [comment]
Then what kind of solution do you prefer or have in mind? Or what kind of feature do you think Casbin need to support to solve this issue?

**Comment by acim** [comment]
Nothing, just thinking loud and finding out if you have some solution because the documentation is not that good. Anyways, thank you for the great product.

**Comment by jkour** [comment]
>I want Casbin to check if an authenticated user is owner of the document 

I don't think this has something to do with Casbin; I would imagine it as a database query or a microservice call

>or his id is in the shared_to_ids list

Same for this

>and allow him access just in this case. How to do this?

You can simply create a group with the ids and the shared_ids and enforce Casbin to check the permissions

**Comment by acim** [comment]
Thank you for clearing things up :smile:
