### ISSUE TITLE
Could casbin be used for GraphQL? 

### ISSUE THREAD

**Issue by zwl1619** [casbin/casbin#327]
Could casbin be used for GraphQL? Such as  [gqlgen](https://github.com/99designs/gqlgen)

**Comment by hsluoyz** [comment]
@zwl1619 I have asked them for their opinion: https://github.com/99designs/gqlgen/issues/937

**Comment by hsluoyz** [comment]
See: https://github.com/esmaeilpour/graphql-casbin
