### ISSUE TITLE
Error about two people using the same role

### ISSUE THREAD

**Issue by blue-cat** [casbin/casbin#328]
My current configuration is as follows:
```
p,g1_root,/*
p,g0_base,/u/info
g,chen,g1_root
g,shen,g1_root
g,g1_*,g0_base
```
Then, the user chen logged in and everything was fine, with access to any address and the role is 
 g1_root.
but when shen login, no permissions was fine, and the role is g1_*
please help me

**Comment by nodece** [comment]
@blue-cat Could you provide the model for policy?

**Comment by nodece** [comment]
Using the model, it works.
```
[request_definition]
r = sub, obj

[policy_definition]
p = sub, obj

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyMatch(r.obj, p.obj)

```

**Comment by blue-cat** [comment]
> @blue-cat Could you provide the model for policy?

model file：
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)
```

**Comment by blue-cat** [comment]
> @blue-cat Could you provide the model for policy?

and I use it like this:
        e, err := casbin.NewEnforcer("auth_model.conf", "policy.csv")
        if err != nil {
                return nil, err
        }
        rm := defaultrolemanager.NewRoleManager(10)
        rm.(*defaultrolemanager.RoleManager).AddMatchingFunc("KeyMatch", util.KeyMatch)
        e.SetRoleManager(rm)
        err = e.LoadPolicy()
        if err != nil {
                return nil, err
        }

**Comment by nodece** [comment]
@blue-cat Please use the model I provided

**Comment by nodece** [comment]
Suggestion: If you don't need to match `g1_*`, should remove `rm`.
See: [Casbin supported built-in functions](https://casbin.org/docs/en/function#functions-in-matchers).
