### ISSUE TITLE
error parsing regexp: missing argument to repetition operator: `*`

### ISSUE THREAD

**Issue by goapifirst** [casbin/casbin#330]
Just started using this.. and man this library is amazing in what it provides.

I have followed the example on setting up a REST auth. I have auth.conf and auth.csv. They load, and from the example csv whenever I access a path that has the * in it in the .csv, I get the panic and the error message in the subject.

I am using the REST conf as linked to from here: https://casbin.org/docs/en/supported-models

My csv looks like:

```
p, admin, /*, *
p, anonymous, /login, *
p, p, /logout, *
p, p, /p/*, *
p, n, /logout, *
p, n, /n, *
```

I am using Chi, and have followed the example of the chi-authz from here: https://github.com/casbin/chi-authz

When I change the path to /p (removing the /* after it), for example, and try to access via Postman /p, /p/, /p/test, etc.. I either get Forbidden or see a panic output with the error message.

I have verified in my code that the role, path and method types passed to the Enforcer match what is found in the csv.

I am not clear what the first p is on each line though.

Is the regex call in the auth.conf file (e.g. this: [matchers]
m = r.sub == p.sub && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)  ) wrong??

**Comment by hsluoyz** [comment]
`*` is not valid in regex, use `.*` instead.

**Comment by kevinduffey** [comment]
Interesting.. the example for Rest has that in their csv file. How does their code work (or does it)?

I did find another .conf example for Rest that doesn't have the regexp call in it, and it seems to work. Not sure if it is any better or not, but the matcher is:
m = r.sub == p.sub && keyMatch(r.obj, p.obj) && (r.act == p.act || p.act == "*")
vs 
m = r.sub == p.sub && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act) )

Is there anything better/faster with the regex one?

**Comment by kdufeydev-pn** [comment]
Interesting.. the example for Rest has that in their csv file. How does their code work (or does it)?

I did find another .conf example for Rest that doesn't have the regexp call in it, and it seems to work. Not sure if it is any better or not, but the matcher is:
m = r.sub == p.sub && keyMatch(r.obj, p.obj) && (r.act == p.act || p.act == "*")
vs
m = r.sub == p.sub && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act) )

Is there anything better/faster with the regex one?

**Comment by goapifirst** [comment]
Interesting.. the example for Rest has that in their csv file. How does their code work (or does it)?

I did find another .conf example for Rest that doesn't have the regexp call in it, and it seems to work. Not sure if it is any better or not, but the matcher is:
m = r.sub == p.sub && keyMatch(r.obj, p.obj) && (r.act == p.act || p.act == "*")
vs
m = r.sub == p.sub && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act) )

Is there anything better/faster with the regex one?

**Comment by hsluoyz** [comment]
regexMatch() is slower than keyMatch(), which is slower than `r.act == p.act || p.act == "*"`. See the source code.

**Comment by ipman1998** [comment]
> `*` is not valid in regex, use `.*` instead.

it work for me. many thanks
