### ISSUE TITLE
Work in progress: optimizations

### ISSUE THREAD

**Issue by gredin** [casbin/casbin#332]
Hi,

I've been working for a week on optimizing Casbin library.

Basically, I'm trying the following approach:
- store policies in an in-memory database (sqlite - but I might change this);
- transforming a matcher into a parametrized query (for the mentioned database);
- when Enforce(...) is called, we query the database in order to find the related policies;
- the expression evaluator then evaluates only the restricted set of policies.

In addition to that:
- all complex variables in the matcher are transformed to scalar variables (r.obj.property => r_obj_property). This speeds up the evaluation, but I first did it because it's easier to store only scalar variables in the database;
- I use Google's Common Expression Language instead of govaluate, mainly because this lib allows manipulating the expression Abstract Syntax Tree (this is something I need for transforming the expression to a database query).

My main concern is to keep Casbin API unchanged, I hope I'll be able to do this.

Do you have any comments, criticism...? Things I might have not considered?

**Comment by goapifirst** [comment]
So I came across an article regarding an in memory cache for Go (ristretto). From the video I saw it performs as well if not more so than Redis. Would it make sense to look at using something like this to speed it up even more?

As I am new to using casbin, I am wondering.. is it ideal to load your entire user database (or subset of it) into memory (and keep it updated for new/deleted users) along with the policy/conf data to speed things up? Ideally as this is done on every single request, we want this to be as fast as it possibly can, right? I suspect some sites with millions of users may be a bit much to keep in memory... though if you have that many users and hopefully are making some sort of revenue from them, using a larger machine with a lot more memory in the cloud for this particular service for the speed boost seems like a good idea.

**Comment by gredin** [comment]
@goapifirst 
About your first point: Casbin has a `CachedEnforcer` that uses a `map[string]bool` as an in-memory cache for storing past `enforcer.Enforce(...)` results.

About your latter point: yes, that's the design implemented by Casbin. The model and policies are stored in memory (and "synchronized" with a persistent storage).

**Comment by hsluoyz** [comment]
Hi @gredin , your idea sounds good. I just feel worried about the second point: ``transforming a matcher into a parametrized query (for the mentioned database);``

I think it's hard to do because the matcher can be anything?

Also for each `enforce()` call, it queries the DB. Will performance suffer?

**Comment by hsluoyz** [comment]
Closed as stale.
