### ISSUE TITLE
support pattern function in 3rd args of g

### ISSUE THREAD

**Issue by Chellhooo** [casbin/casbin#337]
HI~ 
Would you plan to support pattern function in 3rd args(domain) of g?

In my case, I may want to define some inheritance relations between global roles, and assign a role to a user (like alice) in a specific project. 

The policy and model seem like following:
```csv
g, finance_viewer, app_viewer, *
g, alice, finance_viewer, project_a
```
```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && g2(r.obj,p.obj) && r.dom == p.dom && r.obj == p.obj && r.act == p.act
```  
Although there are some ways to solve in my case, it will be grateful if casbin can support pattern like `*` at domain~

**Comment by nodece** [comment]
Hi @Chellhooo This is a good suggestion. we team need to discuss it.

**Comment by nodece** [comment]
Thanks @dovics for the feature.  
`go get github.com/dovics/domain-role-manager` to your project, it works fine.

**Comment by hsluoyz** [comment]
@nodece can we merge it into our core lib?

**Comment by nodece** [comment]
@hsluoyz I think as a plugin is better.
