### ISSUE TITLE
How does Casbin's RBAC model resolve policy conflicts?

### ISSUE THREAD

**Issue by theChildinus** [casbin/casbin#338]
~question
Thanks to such a great team for making casbin! I am still new to using Casbin and RBAC access control models. I have some questions to ask:

In the [official documentation](https://casbin.org/docs/en/rbac) RBAC model mentions:

> 4. If A has role B, B has role C, then A has role C. This transitivity is infinite for now.

I want to ask:

1. Can this situation be simulated using casbin? can you provide a example ~
2. How does Casbin's RBAC model resolve policy conflicts, can you give an example to explain it? Or suggest what document or source code should I read?

Thanks！

**Comment by hsluoyz** [comment]
@theChildinus first thanks for being interested in Casbin! Can you modify your title and text into English? As we are an international project/community. Thanks ! I will answer your question when it's done.

**Comment by hsluoyz** [comment]
You are talking about detection for circular inheritance conflict? Are you facing such situation in real project or doing research on policy conflict detection area?

1. Casbin doesn't handle/detect/resolve circular inheritance conflict. It may crash for such situation.

2. We may add it, based on how many users want this feature. So please state your scenario.

**Comment by theChildinus** [comment]
Thank you very much for your reply! I am a graduate student. I use casbin for access control in my personal projects. I have not encountered this problem yet, but I also need to understand casbin’s research on policy conflicts. Prepare for my paper.

**Comment by richsoap** [comment]
Hello guys. I want to participate in GSOC this year, and very interested in this problem. Here are my some thoughts about this issue.

First, I believe this is a very meaning problem. One of the most important assumptions in our system is all of the roles are organized as a tree or directed acyclic graph. Without this assumption, it will cost a lot of time and space to make robustness possible in other functions. Considering the role of access control in the system, it will means a lot to ensure the establishment of this assumption.

The next problem is where and when. I've noticed that links are stored in **RoleManager**. Therefore, I think it's a good idea to define this function in class **RoleManager**. I don't think it's a great way to expose these functions to users, which means we should detect circle conflict after functions like **BuildRoleLinks** in **Enforcer** are called. 

Third, as all roles are stored in RoleManager itself, I come up with two type of functions we can define. The first type looks like **func (rm\* RoleManager)DetectCircleConfilct(roleName string) ([]string, error)**. We pass a name as the start point in a graph, and wait for all names on this circle(or some error). However, this kind is memoryless meaning we will waste a lot of time(especially for sync.Map). The second type is like **func (rm\* RoleManager)DetectCircleConfilct() ([]string, error)**, which means we can do some records to save valuable time but traverse the whole graph.

Finally, there are many algorithms to find a circle in directed graph, such as DFS, BFS and DP. This can be discussed later.

I'll keep watching this issue and look forward for further discussion. Thank you.😁😁😁

**Comment by hsluoyz** [comment]
@nodece what do you think?

**Comment by nodece** [comment]
This is just my point:
Casbin can't handle the policy conflicts, the RBAC links as a graph. 

But how does handle it in Casbin? 
> If A has role B, B has role C, then A has role C. This transitivity is infinite for now.

Casbin set the maxHierarchyLevel and uses recursion to check the user role.

**Comment by richsoap** [comment]
In my opinion, policy confilicts indicate there are some errors in input data. I come up with 2 ways to handle this problem.

1. We are strict. We print every roles in the circle, and ask user to make it before running Casbin again, just like my strict GCC.

2. At your own risk. We tell user about the risks of using bad rolelinks, and let user to dicide whether continue use these links or not.

There will be many functions to meet user's requirements. I prefer to standardize user input rather than consider infinite transitivity in every function which need to search the graph.

**Comment by DivyPatel9881** [comment]
Ideally, I don't find out any plausible use-case to define such policy rules in which there is a circular role inheritance hierarchy. In such cases, a fail-safe method can be employed where-in before loading `policy` in an `enforcer` instance, a function must be set up which checks such policy-conflicts and ask the user to fix those discrepancies on their side.

**Comment by DivyPatel9881** [comment]
@hsluoyz and @nodece, what do you think should I give it a chance to this, am I thinking right enough to implement this?

**Comment by GopherJ** [comment]
@DivyPatel9881 @nodece  @richsoap So first of all, I think it's possible to have circular link : 

For example: 

https://github.com/casbin/node-casbin/issues/150

But I don't think it's that difficult to solve, we definitely need to pay attention to the usage of recursive call but except that.  I think it's fine for casbin's scenario.

**Comment by hsluoyz** [comment]
Closed as stale.
