### ISSUE TITLE
Support ArangoDB persistence adapter

### ISSUE THREAD

**Issue by adamwasila** [casbin/casbin#339]
It seems that ArangoDB is quite popular alternative to MongoDB so having a peristence of the former would be quite nice too. 

I wrote some draft implementation which you may see here (heavily inspired by MongoDB adapter, even db structures are the same):

https://github.com/adamwasila/arangodb-adapter

It works and do the job but may have some bugs or limitations as it was used basically by one person now. Please let me know if you consider it worth adding to your list of adapters and if not - what correction points you request.

Otherwise, please help spreading the word - if there will be people using and testing it and there will be some issues, I'll provide a support and make it stable and trustworthy piece of code.

**Comment by hsluoyz** [comment]
Added: https://github.com/casbin/casbin-website/commit/12f8957f4415c5779eafbd11491225045023d7e3

Thanks for the contribution ! I don't know ArangoDB actually. Maybe we should spread it to ArangoDB forum/community?

Please don't forget to add tests.

**Comment by adamwasila** [comment]
Thank you! Yes, unit tests are on TODO's list (in README) as well as full support for filtered adapter interface.
