### ISSUE TITLE
Dynamic route permissions

### ISSUE THREAD

**Issue by kwojcicki** [casbin/casbin#34]
Using pressly chi if I have routes like the following 
```go
r.Route("/test", func(r chi.Router) {
	r.Get("/:id", func(w http.ResponseWriter, r *http.Request){
		id := chi.URLParam(r, "id")
		log.Print(id)
		w.Write([]byte(id))
	})
	r.Get("/all", func(w http.ResponseWriter, r *http.Request){
		log.Print("all")
		w.Write([]byte("all."))
	})
})
```
How would I go about allowing users to access /:id/ but not /all and vice versa?
Currently I am trying to do 
```go
e := &casbin.Enforcer{}
//Uses the example restful model posted in examples 
e.InitWithFile("/home//authz_model.conf", "")
e.AddPermissionForUser("dataset1_admin1","/test/*/","GET")
```
But this gives permissions to both routes.

**Comment by hsluoyz** [comment]
You can refer to the Priority example here: https://github.com/casbin/casbin#examples

Deny /all but allow /:id

```csv
p, alice, /all, GET, deny
p, alice, /:id, GET, allow
```

Allow /all but deny /:id

```csv
p, alice, /all, GET, allow
p, alice, /:id, GET, deny
```

You can directly match /:id with the built-in ``keyMatch2()`` function, see: https://github.com/casbin/casbin/wiki/Matchers#functions-in-matchers

**Comment by kwojcicki** [comment]
Thanks for the quick reply. That seems to work but what if there was one more level to the routing ie /:id/all 
doing 
p, alice, /:id, GET, allow
p, alice, /:id/all, GET deny
Doesnt seem to work.

**Comment by hsluoyz** [comment]
This bug is fixed in: https://github.com/casbin/casbin/commit/391eab9693562007e7fb14ef309c8e761e30f9dd

Please try the latest commit.

**Comment by kwojcicki** [comment]
Seems to break previous working permissions
```
p, alice, /all, GET, deny
p, alice, /:id, GET, allow
```
requests for /all and for /test both return 200 instead of 403 and 200

**Comment by hsluoyz** [comment]
/all will match /all itself, so the result should be deny. Can you paste a full example here? (model, policy, and the Enforce() call)

**Comment by kwojcicki** [comment]
Model: 

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = priority(p.eft) || deny

[matchers]
m = g(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && r.act == p.act
```

Policy I leave blank and generate at run time 
For the Enforce Call i utilise https://github.com/casbin/chi-authz
```
e := &casbin.Enforcer{}
util.EnableLog = false;
e.InitWithFile("/home/priority_model.conf", "")
e.AddPermissionForUser("dataset1_admin1","/test/:id/", "GET", "allow")
e.AddPermissionForUser("dataset1_admin1","/test/all/", "GET", "deny")
r.Use(Authorizer(e))
r.Route("/test", func(r chi.Router) {
	r.Route("/:id", func(r chi.Router) {
		r.Get("/", func(w http.ResponseWriter, r *http.Request) {
			w.Write([]byte("hello"))
			log.Print("hello")
			w.WriteHeader(200)
		})
	})
	r.Get("/all", func(w http.ResponseWriter, r *http.Request){
		log.Print("test")
		w.Write([]byte("test."))
		w.WriteHeader(200)
	})
})
testAuthzRequest(r, "dataset1_admin1", "/test/all/", "GET", 200)
testAuthzRequest(r, "dataset1_admin1", "/test/123/", "GET", 200)
```

**Comment by hsluoyz** [comment]
The priority model you used will check the policy rules in order (from first rule to last). So ``/test/all/`` should be placed before ``/test/:id/`` to let ``/test/all/`` match the path first, all ``/test/:id/`` will then match ``/test/all/``

**Comment by kwojcicki** [comment]
Is there a way to get around that without specifying the order manually? Like a policy that looks for any rules that might deny? 

e = some(where (p.eft == allow)) && !some(where (p.eft == deny)) ?

**Comment by hsluoyz** [comment]
Yes. You can use the [Deny-override model](https://github.com/casbin/casbin#examples) (as you posted). This model will let deny overrides allow when two rules both match the request.

**Comment by kwojcicki** [comment]
Thanks that works :smile:
