### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by kapujiang** [casbin/casbin#342]
vendor/github.com/casbin/casbin/enforcer.go:361:66: cannot use functions (type model.FunctionMap) as type map[string]"net_test/vendor/github.com/Knetic/govaluate".ExpressionFunction in argument to "net_test/vendor/github.com/Knetic/govaluate".NewEvaluableExpressionWithFunctions
vendor/github.com/casbin/casbin/management_api.go:260:18: cannot use function (type "net_test/vendor/github.com/Knetic/govaluate".ExpressionFunction) as type "github.com/Knetic/govaluate".ExpressionFunction in argument to e.fm.AddFunction

**Comment by hsluoyz** [comment]
Show `go version` and `go env`

**Comment by kapujiang** [comment]
go version
go version go1.11.4 darwin/amd64
➜  casbin git:(master) go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kapu/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/kapu/work/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ft/s9j73fdn3bv4q14_6wz3_b300000gn/T/go-build335003421=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by hsluoyz** [comment]
Please update to latest Go.

**Comment by kapujiang** [comment]
为什么我已经升级到go 1.13.5 , 也使用了go mod，但是go.mod的默认版本号是1.9.1，使用这个版本，用如下代码：
	//加载权限策
	E,_ = casbin.NewEnforcer(basePath+"rbac_model.conf", basePath+"rbac_policy.csv", false)
编译提示：
assignment mismatch: 2 variables but casbin.NewEnforcer returns 1 values

文档里说是两个返回值，为什么这里只返回一个？我哪里搞错了吗

**Comment by hsluoyz** [comment]
Please modify your text to English.

**Comment by hsluoyz** [comment]
See how to use Casbin 2.x: https://github.com/casbin/xorm-adapter

**Comment by kapujiang** [comment]
I've got it:
The document is not right：
![image](https://user-images.githubusercontent.com/38183967/70420460-c330c980-1aa2-11ea-86c9-ba36d8562736.png)
We should import "github.com/casbin/casbin/**v2**"
then the NewEnforcer return two values

**Comment by hsluoyz** [comment]
Can you fix the docs?

**Comment by nodece** [comment]
@hsluoyz Fixed.
@kapujiang Thank you for your report! We have updated the document.
