### ISSUE TITLE
Panic loading policy from csv

### ISSUE THREAD

**Issue by jruizaranguren** [casbin/casbin#344]
I have made the following test using golang docker:

```
docker pull golang
docker run -ti golang
``` 
Then I have installed:

```
go get github.com/casbin/casbin
GO111MODULE=off go get -u github.com/motemen/gore/cmd/gore
```

Then, within gore, I have tried:

```go
e, _ := casbin.NewEnforcer("./acl.conf", "./policy.csv")
r, err := e.Enforce("alice", "read", "data1")
```
And I'm getting the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x5273aa]

goroutine 1 [running]:
github.com/casbin/casbin.(*Enforcer).enforce(0x0, 0x0, 0x0, 0xc000092960, 0x3, 0x3, 0xc00004cf50, 0x4062cf, 0xc000080058)
	/go/src/github.com/casbin/casbin/enforcer.go:341 +0x3a
github.com/casbin/casbin.(*Enforcer).Enforce(...)
	/go/src/github.com/casbin/casbin/enforcer.go:495
main.main()
+0xf6
exit status 2

```

This is my conf file:

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && r.obj == p.obj && r.act == p.act
```

And my policy.csv file:

```
p, alice, data1, read
p, bob, data2, write

```

**Comment by hsluoyz** [comment]
Please test it with native Golang code, not in Docker.

**Comment by hsluoyz** [comment]
@nodece

**Comment by jruizaranguren** [comment]
I'm getting the same error.

**Comment by hsluoyz** [comment]
See how our test cases got passed: https://github.com/casbin/casbin/blob/master/model_test.go

**Comment by nodece** [comment]
Do not ignore the return value of caspin. Newenforcer().

**Comment by nodece** [comment]
@jruizaranguren Do not ignore the return value of caspin. NewEnforcer().

**Comment by nodece** [comment]
Now you are using Casbin v1.
ERROR: assignment mismatch: 2 variables but casbin.NewEnforcer returns 1 values

**Comment by jruizaranguren** [comment]
The problem was the path. It is not resolving the relative path.

**Comment by nodece** [comment]
Within gore, Casbin can not resolving the relative path.

**Comment by hsluoyz** [comment]
@jruizaranguren You can load model and policy in your own way and feed what you read to Casbin directly:

https://casbin.org/docs/en/model-storage#load-model-from-string
https://casbin.org/docs/en/management-api
