### ISSUE TITLE
Adapters leveraging domain for data storage segregation

### ISSUE THREAD

**Issue by jruizaranguren** [casbin/casbin#345]
Data persistence in a multi-tenant, multi-domain context may require special strategies. We have tested some postgresql adapter and we have seen that there is a naive mapping between casbin rules and a single table with V1,  V7 columns.

In a production setting, one of the following strategies may apply:
1. A database per domain.
2. A database schema per domain (SQL databases).
3. Partition columns for domain (SQL databases).
4. Specific built-in mechanisms. For instance, etcd has namespaces to isolate tenant keyspaces.

Have any of you faced this problem? Is there any adapter built with this issues in mind?

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
Sorry, I don't know how to understand it.

**Comment by jruizaranguren** [comment]
How do you scale policy storage in the case of multiple tenants?

**Comment by hsluoyz** [comment]
https://casbin.org/docs/en/policy-subset-loading

**Comment by nodece** [comment]
You can implementation https://github.com/casbin/casbin/blob/master/persist/adapter.go interface to scale policy storage.
