### ISSUE TITLE
【RBAC】 How to support  high level domain

### ISSUE THREAD

**Issue by UOvOU** [casbin/casbin#348]
the example about RBAC with Domains，but it is only one level，how can I add 2 domain for every line?  I want My auth project with casbin  serve for muti  applications. I want the other application pass the app_id, user_table_name as params to me.  so I need two domain, thanks for your replay!!!
```
p, admin, tenant1, data1, read
p, admin, tenant2, data2, read

g, alice, admin, tenant1
g, alice, user, tenant2
```

**Comment by nodece** [comment]
I suggest you use https://github.com/casbin/casbin-server.

**Comment by UOvOU** [comment]
> I suggest you use https://github.com/casbin/casbin-server.

这个可以做到，不同的客户端应用，共用一个server端吗？主  
还是说这个需要客户端和服务端是一对一的

**Comment by UOvOU** [comment]
> I suggest you use https://github.com/casbin/casbin-server.

thanks
