### ISSUE TITLE
how to get specific table rabc roles list

### ISSUE THREAD

**Issue by UOvOU** [casbin/casbin#349]
I am new to casbin, I just read all doc yesterday but I still have one question
If one application, have mutil kind user table how can I get the specific table rbac roles list
example table: admin, user

maybe is add table_name as doman ??

**Comment by nodece** [comment]
in Casbin, use `g` to bind users and roles.  Management API: https://casbin.org/docs/en/management-api#getfilteredgroupingpolicy

**Comment by UOvOU** [comment]
> in Casbin, use `g` to bind users and roles. Management API: https://casbin.org/docs/en/management-api#getfilteredgroupingpolicy
 
the db table user and the table admin have the same role name for example: membership , but the permission list of the role is different.

If I use g, I will get  the membership permission list include (user  + admin) (user and admin is not role name , is table name)

**Comment by nodece** [comment]
You can bind different permissions for users.

**Comment by hsluoyz** [comment]
Any update? @UOvOU @nodece

**Comment by nodece** [comment]
I suggest the using RBAC with domain. Please re-open issue if you need help.
