### ISSUE TITLE
Question: How to use casbin in this special condition?

### ISSUE THREAD

**Issue by uphilip1111** [casbin/casbin#35]
I have some situation in RBAC, but I'm not sure casbin can solve this.

Example:
Alice is a role called Role1, Role1 can read data1.
But Alice is special women that she can't read data1.
In model.conf , I define Alice is role1, but I don't know how to solve this problem in casbin.
How is model.conf define that can solve this problem?
Could casbin solve my problem?

**Comment by hsluoyz** [comment]
So you want to deny Alice's access to read data1. In Casbin, you have two ways to do it:

1. Use Deny-override model, then deny Alice' access in a policy rule. Deny will override allow.
2. Use Priority model. All rules are enforced in their order. Deny Alice's access in the first rule, and allow Role1's access in the second rule. So the first rule will apply when the requesting subject is Alice.

Deny-override model is simpler, so I will use it as an example: https://github.com/casbin/casbin#examples

The model is in the above link. The policy can be:

```csv
p, role1, data1, read, allow
p, alice, data1, read, deny

g, alice, role1
```

**Comment by uphilip1111** [comment]
Thank you for answering my question.
I prefer way 2 to solve this problem, cause I have another situation.

Here is another sample:
Role1 can't write data1.
Bob belongs Role1.
But Bob can write data1.

In my two case, I think Priority model can truely solve this condition.
And I try Priority model, but I can't understand policy_effect in Priority model.

[policy_effect]
e = priority(p.eft) || deny

How can I use Priority model to solve my problem?
I really love casbin that It can solve most my authorization condition.

**Comment by hsluoyz** [comment]
``priority(p.eft)`` means: the final decision will use the first-applicable rule's effect.

``|| deny`` means if there's no rule that matches the request, the default decision is deny.

For your example, you can use the following policy:

```csv
p, bob, data1, write, allow
p, role1, data1, write, deny

g, bob, role1
```

Thank you for using Casbin:)

**Comment by uphilip1111** [comment]
Thank you for answering my question.
I tried all method in your post, and I successfully finish my requirement by your help.
Thank you again and hope casbin will be popular authorization library

**Comment by hsluoyz** [comment]
It's my pleasure to help Casbin users do their job:) And don't hesitate to fire issues if you have any suggestions about how to improve or popularize it:)
