### ISSUE TITLE
It's not possible for Casbin to use database capabilities to it's full extent

### ISSUE THREAD

**Issue by pckhoi** [casbin/casbin#350]
Hello, happy user of Casbin for a long while, until recently. I was using Gorm adapter but what I found out was that when I run multiple instances of enforcer, those instances are not synced automatically. I was quite surprised by this because I thought a simple query to PostgreS should suffice but then I found out Casbin does not query the database except when one calls `LoadPolicy`. I thought it was the adapter's fault until I see the Adapter interface does not support anything more than simple load/save mechanism.

Did you guys not think of querying an underlying database directly for each and every `Enforce`? How about insert directly to the underlying database each time a policy is added? If you did that from the start then there would be no need for "watcher" to keep multiple enforcer instances in sync. As it is no matter where I store the data it's no better than a text file.

The concept of Casbin is awesome but the adapter interface leave a lot to be desired IMHO.

**Comment by hsluoyz** [comment]
Hi @pckhoi , thanks for using Casbin !

Simple answer is that Casbin has policy in memory cache to gain performance.

You may notice how powerful Casbin matcher can be. You can write nearly any expression in it. So Casbin cannot know which policy rules will be used for an `Enforce()` call. In another word, if there's no memory cache. Then for each `Enforce()`, Casbin will need to load all rules from DB. You will not tolerate that kind of latency. I don't know if there's a better way to achieve both.

If you really hate syncing policy between instances, you can use: https://github.com/casbin/casbin-server. It's a centralized Casbin cluster. So you will not need to sync any more. As a drawback, every authz (enforce) will need a round-trip time between client and server.

**Comment by pckhoi** [comment]
Thanks for the explanation. And I really do appreciate Casbin's magic. What I meant was for each query to hit a database instead of memory. Loading all rules from DB is not necessary. 

For example I have a line like this in my code to look up all domains a user is a part of:
```
policies := enforcer.GetFilteredGroupingPolicy(0, userID)
```
If that could somehow translate directly to a SQL line such as
```
SELECT * FROM casbin_rule WHERE p_type = 'g' AND v0 = '<userID>';
```
That would not be as fast as memory-fast of course but it's enough for my application. And it would eliminate any need for a centralized service or a way to sync.

I have read some of the code and I feel like a different implementation of the `Model` class might be able to achieve this. What do you think?

**Comment by nodece** [comment]
Using casbin-watcher: https://casbin.org/docs/en/watchers

**Comment by hsluoyz** [comment]
You need filtered policy loading: https://casbin.org/docs/en/policy-subset-loading

**Comment by pckhoi** [comment]
Ah, not quite what I meant. I mean for each and every filter/add/get action to hit the database intelligently. But at this point I realize that I might be asking for the moon here. Anyway, thanks guys!

**Comment by hsluoyz** [comment]
You can call `enforcer.LoadFilteredPolicy(filter)` manually before every `enforce()`. It is the same with what you are saying.

**Comment by pckhoi** [comment]
But only built-in filtered file adapter support it. Is it possible to extend this capability to other adapters as well?

**Comment by hsluoyz** [comment]
Yes. Because we are lacking developers to support other adapters. What adapter do you use? Can you contribute this feature to your adapter?

**Comment by pckhoi** [comment]
I'm willing if the adapter interface support it. Doesn't look like the current interface support it.

**Comment by pckhoi** [comment]
Never mind, I have just found the `FilteredAdapter` interface. Cool, I'll see if it's feasible.

**Comment by pckhoi** [comment]
Check out this adapter: https://github.com/pckhoi/casbin-pg-adapter

Never used but all tests are passing.

**Comment by hsluoyz** [comment]
@pckhoi Thanks for the quick work!

I saw your work is also forked from another person's repo. As a conventional ask to avoid Casbin ecosystem fragmentization:

1. Will you continuously maintain your adapter (handle issues and PR)?

2. Are you willing to host your adapter inside [Casbin org](https://github.com/casbin) (and at the same time you become a Casbin org member)? (It's totally fine if you want to maintain it by yourself)

BTW, the CI can be setup for it.

**Comment by pckhoi** [comment]
Yes to all of the above! Thanks for the invitation. I wouldn't have
bothered sharing my work if I'm not willing to maintain. I'll see about CI
after joining Casbin org.

**Comment by hsluoyz** [comment]
Thanks!

I have sent the invitation :) I have created the repo: https://github.com/casbin/casbin-pg-adapter
