### ISSUE TITLE
Support policy overrides passed in Enforce call 

### ISSUE THREAD

**Issue by dialtone** [casbin/casbin#353]
In our system we have hundreds of thousands of users with hundreds of basic rules and hundreds of thousands of further overrides to the basic rules. This is straightforward to implement in casbin, for example.

A model such as:
```ini
[request_definition]
r = sub, rol, act

[policy_definition]
p = sub, rol, act, eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = (g(r.rol, p.rol) && r.act == p.act) || (r.sub == p.sub && r.act == p.act)
```

And policy such as:
```csv
# general role-level rules
p,      , admin   , write       , allow
p,      , engineer, edit-reports, allow
p,      , user    , report      , allow

# specific user overrides
p, marc ,         , edit-reports, deny
p, alice,         , edit-reports, allow

# role hierarchy 
g, engineer, user
g, admin, user
```

Now the challenge however is that the specific user overrides part is huge in real life and loading it up slows performance down a lot, one could try to use the FilteredAdapter but it clears the main model at each call so it's not suited to be called per-request. The SyncedEnforcer is very coarse locking and effectively would serialize each http request on the permissions check. 

None of this would be necessary if the adapter could load the general role-level ruleset and allow for the user to pass in a set of overrides valid only for the specific Enforce call. This way you would avoid the vast majority of locking problems since nothing shared would need to be mutated, and at the same time you can deal with caching of the overrides separately.

**Comment by hsluoyz** [comment]
You can use priority model to make some overrides: https://casbin.org/docs/en/supported-models#examples

**Comment by dialtone** [comment]
Hey thanks for the answer! The model I shared in the ticket already does well what I need, so my issue is less about supporting priority and more about loading a gigantic set of permissions that slows down casbin when enforcing, and working across threads as well.

**Comment by hsluoyz** [comment]
Can you do sharding? What is the policy size for each shard? https://casbin.org/docs/en/policy-subset-loading

**Comment by dialtone** [comment]
Initially I thought I could, but my implementation would Load that policy subset for every request I receive. Unfortunately the first step of that loading calls `ClearPolicy()` on the model, which is not thread safe and disrupts the other requests running at the same time.

**Comment by hsluoyz** [comment]
Do you have concepts like tenants? Maybe you can load subset by different tenants.

**Comment by dialtone** [comment]
Unfortunately no, this is all one big web application that so far has been running its own permission system off a single server and database by simply loading only the rules needed to satisfy the given request and caching them for the following requests. Since we're rewriting this component in Go I wanted to switch to a more mainstream implementation of a permission system.

**Comment by hsluoyz** [comment]
Can you give example on `hundreds of thousands of users with hundreds of basic rules and hundreds of thousands of further overrides to the basic rules`? So we can optimize it.

**Comment by dialtone** [comment]
The example policy is above in the ticket description that has both the model and the policy file. It's really not that different from that but with the overrides part repeated lots of times. What kind of example would be helpful?

**Comment by hsluoyz** [comment]
```
# general role-level rules
p,      , admin   , write       , allow
p,      , engineer, edit-reports, allow
p,      , user    , report      , allow

# specific user overrides
p, marc ,         , edit-reports, deny
p, alice,         , edit-reports, allow

# role hierarchy 
g, engineer, user
g, admin, user
```

There are only 7 rules here. Please show `hundreds of thousands of users with hundreds of basic rules and hundreds of thousands of further overrides to the basic rules`

**Comment by dialtone** [comment]
Well, no, that's private data from my company so I'm not going to provide that and it doesn't really matter honestly... a set of those can be generated randomly as you would in a benchmark.

**Comment by hsluoyz** [comment]
Benchmark is just for showing performance. But normally you usually don't need 10,000 rules to check a request. 10,000 rules are in different tenants. And for 1 request, maybe only dozens of rules are needed.

**Comment by hsluoyz** [comment]
Please show a minimized runnable example which have your private policy rules obfuscated with fake values.

**Comment by dialtone** [comment]
Sure I can do that, but it will take quite some time. If I have enough free time and/or need I'll get back to you here.

**Comment by hsluoyz** [comment]
Closed as stale.
