### ISSUE TITLE
Explain enforcement by informing matched rules

### ISSUE THREAD

**Issue by jruizaranguren** [casbin/casbin#355]
In some scenarios it would be useful to have a way to explain why an enforcement was or wasn't satisfied.
The simplest idea could be to just inform of the matched rules that allowed satisfying (or not) the model.

Is there any way to accomplish this in casbin?

**Comment by hsluoyz** [comment]
Can you make a PR to show how it works? And don't introduce too much performance downgrade after this change I hope.

**Comment by hsluoyz** [comment]
Can anyone work on it?

**Comment by DivyPatel9881** [comment]
I would like to work on this.

**Comment by DivyPatel9881** [comment]
Tomorrow, I will be posting a working theoretical solution to this

**Comment by dovics** [comment]
I have been working on this issus for a while, Now i have completed my first version #401 @jruizaranguren Can you see if my implementation does meet your expectations？

**Comment by hsluoyz** [comment]
Any further progress on this?

**Comment by nodece** [comment]
I propose my implementation:

In my opinion, I just want to know which policy decides whether to return `true` or `false`.

The following is signature of `ExplainEnforce`:

```golang
type ExplainState struct {
	Ok        bool     // enforce result
	HitPolicy []string // which policy decides the enforce result
}

func (e *Enforcer) ExplainEnforce(rvals ...interface{}) (explain *ExplainState, err error)
```

How to get the hit policy?

We need the `Effector.MergeEffects` returns the hit index then pass it to `model` get the policy. I found that `results` is unused in  `Effector.MergeEffects` so we can use it. Let's define the `len(results)` equal to `len(e.model["p"]["p"].Policy) + 1` then`results[len(results)-1]` as hit index.

What do you think?

**Comment by dovics** [comment]
Why deal with the hit policy in `MergeEffects`? this function will also be called by normal `Enforce()`

In addition, the HitPolicy may be more than one, for example:
```
g, alice, admin
p, admin, data1, read
p, alice, data1, read
```

**Comment by nodece** [comment]
Maybe the following can help to understand.
https://github.com/casbin/casbin/blob/master/effect/default_effector.go#L35
https://github.com/casbin/casbin/blob/master/effect/default_effector.go#L43

It just check `effect` is `Allow` or `Deny` then returns result.

**Comment by nodece** [comment]
Don't worry. `Enforce()` unused the `results`.

**Comment by hsluoyz** [comment]
@jruizaranguren solved by: https://github.com/casbin/casbin/pull/425

**Comment by hsluoyz** [comment]
@jruizaranguren can you verify if it works?

**Comment by hsluoyz** [comment]
Merged in: https://github.com/casbin/casbin/pull/425
