### ISSUE TITLE
Make GetImplicitPermissionsForUser Deep

### ISSUE THREAD

**Issue by erichulburd** [casbin/casbin#357]
Currently `GetImplicitPermissionsForUser` only calls `GetPermissionsForUser(role)` for each role. If we wanted to get a complete set of implicit permissions for the user this should be `GetImplicitPermissionsForUser(role)`.

* Is there a reason this is not the case?
* If not, would you accept a PR?
* The Python implementation includes a max hierarchy level. Should this not be a configurable parameter on the enforcer? In which case `Allow` and `GetImplicitPermissionsForUser` would not traverse hierarchies deeper than this level.

**Comment by hsluoyz** [comment]
Hi @erichulburd ,

> Is there a reason this is not the case?

No.

> If not, would you accept a PR?

OK. But please pay attention to the performance. We don't want to have too much performance downgrade after this change.

> The Python implementation includes a max hierarchy level. Should this not be a configurable parameter on the enforcer? In which case Allow and GetImplicitPermissionsForUser would not traverse hierarchies deeper than this level.

It should be a `NewRoleManager()` arg, see:

https://github.com/casbin/casbin/blob/31a4cf3e119fdace8f02263315e83ca37a3fcc18/rbac/default-role-manager/role_manager.go#L36-L45

**Comment by erichulburd** [comment]
@hsluoyz OK I will take a crack at it within the next couple of weeks.

**Comment by hsluoyz** [comment]
Closed as stale.
