### ISSUE TITLE
not found the package 

### ISSUE THREAD

**Issue by dcdebug** [casbin/casbin#363]
go get github.com/casbin/casbin
package github.com/casbin/casbin/v2/effect: cannot find package "github.com/casbin/casbin/v2/effect" in any of:
        /usr/lib/go-1.6/src/github.com/casbin/casbin/v2/effect (from $GOROOT)
        /home/ubuntu/go/src/github.com/casbin/casbin/v2/effect (from $GOPATH)
package github.com/casbin/casbin/v2/log: cannot find package "github.com/casbin/casbin/v2/log" in any of:
        /usr/lib/go-1.6/src/github.com/casbin/casbin/v2/log (from $GOROOT)
        /home/ubuntu/go/src/github.com/casbin/casbin/v2/log (from $GOPATH)
package github.com/casbin/casbin/v2/model: cannot find package "github.com/casbin/casbin/v2/model" in any of:
        /usr/lib/go-1.6/src/github.com/casbin/casbin/v2/model (from $GOROOT)
        /home/ubuntu/go/src/github.com/casbin/casbin/v2/model (from $GOPATH)
package github.com/casbin/casbin/v2/persist: cannot find package "github.com/casbin/casbin/v2/persist" in any of:
        /usr/lib/go-1.6/src/github.com/casbin/casbin/v2/persist (from $GOROOT)
        /home/ubuntu/go/src/github.com/casbin/casbin/v2/persist (from $GOPATH)
package github.com/casbin/casbin/v2/persist/file-adapter: cannot find package "github.com/casbin/casbin/v2/persist/file-adapter" in any of:
        /usr/lib/go-1.6/src/github.com/casbin/casbin/v2/persist/file-adapter (from $GOROOT)
        /home/ubuntu/go/src/github.com/casbin/casbin/v2/persist/file-adapter (from $GOPATH)
package github.com/casbin/casbin/v2/rbac: cannot find package "github.com/casbin/casbin/v2/rbac" in any of:
        /usr/lib/go-1.6/src/github.com/casbin/casbin/v2/rbac (from $GOROOT)
        /home/ubuntu/go/src/github.com/casbin/casbin/v2/rbac (from $GOPATH)
package github.com/casbin/casbin/v2/rbac/default-role-manager: cannot find package "github.com/casbin/casbin/v2/rbac/default-role-manager" in any of:
        /usr/lib/go-1.6/src/github.com/casbin/casbin/v2/rbac/default-role-manager (from $GOROOT)
        /home/ubuntu/go/src/github.com/casbin/casbin/v2/rbac/default-role-manager (from $GOPATH)
package github.com/casbin/casbin/v2/util: cannot find package "github.com/casbin/casbin/v2/util" in any of:
        /usr/lib/go-1.6/src/github.com/casbin/casbin/v2/util (from $GOROOT)
        /home/ubuntu/go/src/github.com/casbin/casbin/v2/util (from $GOPATH)

my go env is :
 go env 
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ubuntu/go"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

how I fix the question ?

**Comment by nodece** [comment]
go get github.com/casbin/casbin/v2

**Comment by jack17529** [comment]
@nodece I don't think that you have a "v2" folder anymore or am I missing something?
The go-kit is still using the v2 though, so I am getting errors.

**Comment by hsluoyz** [comment]
We use Go Modules for Casbin v2. Please learn Go Modules and see how we import Casbin v2 in Xorm adapter as an example: https://github.com/casbin/xorm-adapter

**Comment by jack17529** [comment]
@hsluoyz , thanks for such quick response. Yep, I looked into Go Modules. I think I still need help.

I have generated the code from "kujtimiihoxha/kit" repository as I was trying to learn to build microservices using go-kit through this tutorial - `https://www.youtube.com/watch?v=1ScP5DyS1_g` . When I try to run my docker-compose file. I get these errors -

src/github.com/go-kit/kit/auth/casbin/middleware.go:7:2: cannot find package "github.com/casbin/casbin/v2" in any of:
/usr/local/go/src/github.com/casbin/casbin/v2 (from $GOROOT)
/go/src/github.com/casbin/casbin/v2 (from $GOPATH)
src/github.com/go-kit/kit/auth/jwt/middleware.go:7:2: cannot find package "github.com/dgrijalva/jwt-go" in any of:
/usr/local/go/src/github.com/dgrijalva/jwt-go (from $GOROOT)
/go/src/github.com/dgrijalva/jwt-go (from $GOPATH)
src/github.com/go-kit/kit/circuitbreaker/hystrix.go:6:2: cannot find package "github.com/afex/hystrix-go/hystrix" in any of:
/usr/local/go/src/github.com/afex/hystrix-go/hystrix (from $GOROOT)
/go/src/github.com/afex/hystrix-go/hystrix (from $GOPATH)
src/github.com/go-kit/kit/circuitbreaker/gobreaker.go:6:2: cannot find package "github.com/sony/gobreaker" in any of:
/usr/local/go/src/github.com/sony/gobreaker (from $GOROOT)
/go/src/github.com/sony/gobreaker (from $GOPATH)
src/github.com/go-kit/kit/circuitbreaker/handy_breaker.go:7:2: cannot find package "github.com/streadway/handy/breaker" in any of:
/usr/local/go/src/github.com/streadway/handy/breaker (from $GOROOT)
/go/src/github.com/streadway/handy/breaker (from $GOPATH)
src/github.com/go-kit/kit/cmd/kitgen/transform.go:15:2: cannot find package "github.com/davecgh/go-spew/spew" in any of:
/usr/local/go/src/github.com/davecgh/go-spew/spew (from $GOROOT)
/go/src/github.com/davecgh/go-spew/spew (from $GOPATH)
src/github.com/go-kit/kit/cmd/kitgen/main.go:14:2: cannot find package "github.com/pkg/errors" in any of:
/usr/local/go/src/github.com/pkg/errors (from $GOROOT)
/go/src/github.com/pkg/errors (from $GOPATH)
src/github.com/go-kit/kit/cmd/kitgen/ast_templates.go:7:8: cannot find package "golang.org/x/tools/godoc/vfs/mapfs" in any of:
/usr/local/go/src/golang.org/x/tools/godoc/vfs/mapfs (from $GOROOT)
/go/src/golang.org/x/tools/godoc/vfs/mapfs (from $GOPATH)
src/github.com/go-kit/kit/cmd/kitgen/transform.go:18:2: cannot find package "golang.org/x/tools/imports" in any of:
/usr/local/go/src/golang.org/x/tools/imports (from $GOROOT)
/go/src/golang.org/x/tools/imports (from $GOPATH)
src/github.com/go-kit/kit/examples/addsvc/cmd/addcli/addcli.go:14:2: cannot find package "github.com/apache/thrift/lib/go/thrift" in any of:
/usr/local/go/src/github.com/apache/thrift/lib/go/thrift (from $GOROOT)
/go/src/github.com/apache/thrift/lib/go/thrift (from $GOPATH)
src/github.com/go-kit/kit/examples/addsvc/cmd/addcli/addcli.go:17:2: cannot find package "github.com/openzipkin-contrib/zipkin-go-opentracing" in any of:
/usr/local/go/src/github.com/openzipkin-contrib/zipkin-go-opentracing (from $GOROOT)
/go/src/github.com/openzipkin-contrib/zipkin-go-opentracing (from $GOPATH)
src/github.com/go-kit/kit/examples/addsvc/pkg/addendpoint/set.go:7:2: cannot find package "golang.org/x/time/rate" in any of:
/usr/local/go/src/golang.org/x/time/rate (from $GOROOT)
/go/src/golang.org/x/time/rate (from $GOPATH)
src/github.com/go-kit/kit/examples/apigateway/main.go:20:2: cannot find package "github.com/gorilla/mux" in any of:
/usr/local/go/src/github.com/gorilla/mux (from $GOROOT)
/go/src/github.com/gorilla/mux (from $GOPATH)
src/github.com/go-kit/kit/sd/consul/client.go:4:2: cannot find package "github.com/hashicorp/consul/api" in any of:
/usr/local/go/src/github.com/hashicorp/consul/api (from $GOROOT)
/go/src/github.com/hashicorp/consul/api (from $GOPATH)
src/github.com/go-kit/kit/examples/shipping/cargo/cargo.go:9:2: cannot find package "github.com/pborman/uuid" in any of:
/usr/local/go/src/github.com/pborman/uuid (from $GOROOT)
/go/src/github.com/pborman/uuid (from $GOPATH)
src/github.com/go-kit/kit/transport/nats/encode_decode.go:6:2: cannot find package "github.com/nats-io/nats.go" in any of:
/usr/local/go/src/github.com/nats-io/nats.go (from $GOROOT)
/go/src/github.com/nats-io/nats.go (from $GOPATH)
src/github.com/go-kit/kit/log/logrus/logrus_logger.go:10:2: cannot find package "github.com/sirupsen/logrus" in any of:
/usr/local/go/src/github.com/sirupsen/logrus (from $GOROOT)
/go/src/github.com/sirupsen/logrus (from $GOPATH)
src/github.com/go-kit/kit/log/zap/zap_sugar_logger.go:5:2: cannot find package "go.uber.org/zap" in any of:
/usr/local/go/src/go.uber.org/zap (from $GOROOT)
/go/src/go.uber.org/zap (from $GOPATH)
src/github.com/go-kit/kit/log/zap/zap_sugar_logger.go:6:2: cannot find package "go.uber.org/zap/zapcore" in any of:
/usr/local/go/src/go.uber.org/zap/zapcore (from $GOROOT)
/go/src/go.uber.org/zap/zapcore (from $GOPATH)
src/github.com/go-kit/kit/metrics/generic/generic.go:13:2: cannot find package "github.com/VividCortex/gohistogram" in any of:
/usr/local/go/src/github.com/VividCortex/gohistogram (from $GOROOT)
/go/src/github.com/VividCortex/gohistogram (from $GOPATH)
src/github.com/go-kit/kit/metrics/cloudwatch/cloudwatch.go:11:2: cannot find package "github.com/aws/aws-sdk-go/aws" in any of:
/usr/local/go/src/github.com/aws/aws-sdk-go/aws (from $GOROOT)
/go/src/github.com/aws/aws-sdk-go/aws (from $GOPATH)
src/github.com/go-kit/kit/metrics/cloudwatch/cloudwatch.go:12:2: cannot find package "github.com/aws/aws-sdk-go/service/cloudwatch" in any of:
/usr/local/go/src/github.com/aws/aws-sdk-go/service/cloudwatch (from $GOROOT)
/go/src/github.com/aws/aws-sdk-go/service/cloudwatch (from $GOPATH)
src/github.com/go-kit/kit/metrics/cloudwatch/cloudwatch.go:13:2: cannot find package "github.com/aws/aws-sdk-go/service/cloudwatch/cloudwatchiface" in any of:
/usr/local/go/src/github.com/aws/aws-sdk-go/service/cloudwatch/cloudwatchiface (from $GOROOT)
/go/src/github.com/aws/aws-sdk-go/service/cloudwatch/cloudwatchiface (from $GOPATH)
src/github.com/go-kit/kit/metrics/cloudwatch2/cloudwatch2.go:11:2: cannot find package "github.com/aws/aws-sdk-go-v2/aws" in any of:
/usr/local/go/src/github.com/aws/aws-sdk-go-v2/aws (from $GOROOT)
/go/src/github.com/aws/aws-sdk-go-v2/aws (from $GOPATH)
src/github.com/go-kit/kit/metrics/cloudwatch2/cloudwatch2.go:12:2: cannot find package "github.com/aws/aws-sdk-go-v2/service/cloudwatch" in any of:
/usr/local/go/src/github.com/aws/aws-sdk-go-v2/service/cloudwatch (from $GOROOT)
/go/src/github.com/aws/aws-sdk-go-v2/service/cloudwatch (from $GOPATH)
src/github.com/go-kit/kit/metrics/cloudwatch2/cloudwatch2.go:13:2: cannot find package "github.com/aws/aws-sdk-go-v2/service/cloudwatch/cloudwatchiface" in any of:
/usr/local/go/src/github.com/aws/aws-sdk-go-v2/service/cloudwatch/cloudwatchiface (from $GOROOT)
/go/src/github.com/aws/aws-sdk-go-v2/service/cloudwatch/cloudwatchiface (from $GOPATH)
src/github.com/go-kit/kit/metrics/cloudwatch2/cloudwatch2.go:14:2: cannot find package "golang.org/x/sync/errgroup" in any of:
/usr/local/go/src/golang.org/x/sync/errgroup (from $GOROOT)
/go/src/golang.org/x/sync/errgroup (from $GOPATH)
src/github.com/go-kit/kit/metrics/influx/influx.go:10:2: cannot find package "github.com/influxdata/influxdb1-client/v2" in any of:
/usr/local/go/src/github.com/influxdata/influxdb1-client/v2 (from $GOROOT)
/go/src/github.com/influxdata/influxdb1-client/v2 (from $GOPATH)
src/github.com/go-kit/kit/metrics/pcp/pcp.go:4:2: cannot find package "github.com/performancecopilot/speed" in any of:
/usr/local/go/src/github.com/performancecopilot/speed (from $GOROOT)
/go/src/github.com/performancecopilot/speed (from $GOPATH)
src/github.com/go-kit/kit/sd/etcd/client.go:13:2: cannot find package "go.etcd.io/etcd/client" in any of:
/usr/local/go/src/go.etcd.io/etcd/client (from $GOROOT)
/go/src/go.etcd.io/etcd/client (from $GOPATH)
src/github.com/go-kit/kit/sd/etcdv3/client.go:9:2: cannot find package "go.etcd.io/etcd/clientv3" in any of:
/usr/local/go/src/go.etcd.io/etcd/clientv3 (from $GOROOT)
/go/src/go.etcd.io/etcd/clientv3 (from $GOPATH)
src/github.com/go-kit/kit/sd/etcdv3/client.go:10:2: cannot find package "go.etcd.io/etcd/pkg/transport" in any of:
/usr/local/go/src/go.etcd.io/etcd/pkg/transport (from $GOROOT)
/go/src/go.etcd.io/etcd/pkg/transport (from $GOPATH)
src/github.com/go-kit/kit/sd/eureka/instancer.go:6:2: cannot find package "github.com/hudl/fargo" in any of:
/usr/local/go/src/github.com/hudl/fargo (from $GOROOT)
/go/src/github.com/hudl/fargo (from $GOPATH)
src/github.com/go-kit/kit/sd/zk/client.go:9:2: cannot find package "github.com/samuel/go-zookeeper/zk" in any of:
/usr/local/go/src/github.com/samuel/go-zookeeper/zk (from $GOROOT)
/go/src/github.com/samuel/go-zookeeper/zk (from $GOPATH)
src/github.com/go-kit/kit/tracing/opencensus/http.go:7:2: cannot find package "go.opencensus.io/plugin/ochttp" in any of:
/usr/local/go/src/go.opencensus.io/plugin/ochttp (from $GOROOT)
/go/src/go.opencensus.io/plugin/ochttp (from $GOPATH)
src/github.com/go-kit/kit/tracing/opencensus/http.go:8:2: cannot find package "go.opencensus.io/plugin/ochttp/propagation/b3" in any of:
/usr/local/go/src/go.opencensus.io/plugin/ochttp/propagation/b3 (from $GOROOT)
/go/src/go.opencensus.io/plugin/ochttp/propagation/b3 (from $GOPATH)
src/github.com/go-kit/kit/tracing/opencensus/endpoint.go:7:2: cannot find package "go.opencensus.io/trace" in any of:
/usr/local/go/src/go.opencensus.io/trace (from $GOROOT)
/go/src/go.opencensus.io/trace (from $GOPATH)
src/github.com/go-kit/kit/tracing/opencensus/grpc.go:7:2: cannot find package "go.opencensus.io/trace/propagation" in any of:
/usr/local/go/src/go.opencensus.io/trace/propagation (from $GOROOT)
/go/src/go.opencensus.io/trace/propagation (from $GOPATH)
src/github.com/go-kit/kit/transport/amqp/encode_decode.go:6:2: cannot find package "github.com/streadway/amqp" in any of:
/usr/local/go/src/github.com/streadway/amqp (from $GOROOT)
/go/src/github.com/streadway/amqp (from $GOPATH)
src/github.com/oklog/oklog/pkg/store/read.go:10:2: cannot find package "github.com/djherbis/buffer" in any of:
/usr/local/go/src/github.com/djherbis/buffer (from $GOROOT)
/go/src/github.com/djherbis/buffer (from $GOPATH)
src/github.com/oklog/oklog/pkg/store/read.go:11:2: cannot find package "github.com/djherbis/nio" in any of:
/usr/local/go/src/github.com/djherbis/nio (from $GOROOT)
/go/src/github.com/djherbis/nio (from $GOPATH)
src/github.com/oklog/oklog/pkg/stream/deduplicate.go:8:2: cannot find package "github.com/google/btree" in any of:
/usr/local/go/src/github.com/google/btree (from $GOROOT)
/go/src/github.com/google/btree (from $GOPATH)
src/github.com/oklog/oklog/pkg/cluster/advertise.go:10:2: cannot find package "github.com/hashicorp/go-sockaddr" in any of:
/usr/local/go/src/github.com/hashicorp/go-sockaddr (from $GOROOT)
/go/src/github.com/hashicorp/go-sockaddr (from $GOPATH)
src/github.com/oklog/oklog/pkg/cluster/peer.go:21:2: cannot find package "github.com/hashicorp/memberlist" in any of:
/usr/local/go/src/github.com/hashicorp/memberlist (from $GOROOT)
/go/src/github.com/hashicorp/memberlist (from $GOPATH)
src/github.com/oklog/oklog/pkg/ingest/conn.go:16:2: cannot find package "github.com/oklog/ulid" in any of:
/usr/local/go/src/github.com/oklog/ulid (from $GOROOT)
/go/src/github.com/oklog/ulid (from $GOPATH)
src/github.com/oklog/oklog/cmd/oklog/ingest.go:17:2: cannot find package "github.com/rs/cors" in any of:
/usr/local/go/src/github.com/rs/cors (from $GOROOT)
/go/src/github.com/rs/cors (from $GOPATH)
src/github.com/opentracing/opentracing-go/harness/api_checkers.go:31:2: cannot find package "github.com/stretchr/testify/assert" in any of:
/usr/local/go/src/github.com/stretchr/testify/assert (from $GOROOT)
/go/src/github.com/stretchr/testify/assert (from $GOPATH)
src/github.com/opentracing/opentracing-go/harness/api_checkers.go:32:2: cannot find package "github.com/stretchr/testify/suite" in any of:
/usr/local/go/src/github.com/stretchr/testify/suite (from $GOROOT)
/go/src/github.com/stretchr/testify/suite (from $GOPATH)
src/github.com/openzipkin/zipkin-go/reporter/kafka/kafka.go:24:2: cannot find package "github.com/Shopify/sarama" in any of:
/usr/local/go/src/github.com/Shopify/sarama (from $GOROOT)
/go/src/github.com/Shopify/sarama (from $GOPATH)
src/github.com/prometheus/client_golang/api/prometheus/v1/api.go:30:2: cannot find package "github.com/json-iterator/go" in any of:
/usr/local/go/src/github.com/json-iterator/go (from $GOROOT)
/go/src/github.com/json-iterator/go (from $GOPATH)
src/github.com/prometheus/common/config/http_config.go:31:2: cannot find package "github.com/mwitkow/go-conntrack" in any of:
/usr/local/go/src/github.com/mwitkow/go-conntrack (from $GOROOT)
/go/src/github.com/mwitkow/go-conntrack (from $GOPATH)
src/github.com/prometheus/common/config/http_config.go:32:2: cannot find package "gopkg.in/yaml.v2" in any of:
/usr/local/go/src/gopkg.in/yaml.v2 (from $GOROOT)
/go/src/gopkg.in/yaml.v2 (from $GOPATH)
src/github.com/prometheus/common/log/log.go:32:2: cannot find package "gopkg.in/alecthomas/kingpin.v2" in any of:
/usr/local/go/src/gopkg.in/alecthomas/kingpin.v2 (from $GOROOT)
/go/src/gopkg.in/alecthomas/kingpin.v2 (from $GOPATH)
src/github.com/prometheus/common/route/route.go:20:2: cannot find package "github.com/julienschmidt/httprouter" in any of:
/usr/local/go/src/github.com/julienschmidt/httprouter (from $GOROOT)
/go/src/github.com/julienschmidt/httprouter (from $GOPATH)
src/golang.org/x/net/http2/h2demo/h2demo.go:29:2: cannot find package "cloud.google.com/go/storage" in any of:
/usr/local/go/src/cloud.google.com/go/storage (from $GOROOT)
/go/src/cloud.google.com/go/storage (from $GOPATH)
src/golang.org/x/net/http2/h2demo/h2demo.go:30:2: cannot find package "go4.org/syncutil/singleflight" in any of:
/usr/local/go/src/go4.org/syncutil/singleflight (from $GOROOT)
/go/src/go4.org/syncutil/singleflight (from $GOPATH)
src/golang.org/x/net/http2/h2demo/h2demo.go:31:2: cannot find package "golang.org/x/build/autocertcache" in any of:
/usr/local/go/src/golang.org/x/build/autocertcache (from $GOROOT)
/go/src/golang.org/x/build/autocertcache (from $GOPATH)
src/golang.org/x/net/http2/h2demo/h2demo.go:32:2: cannot find package "golang.org/x/crypto/acme/autocert" in any of:
/usr/local/go/src/golang.org/x/crypto/acme/autocert (from $GOROOT)
/go/src/golang.org/x/crypto/acme/autocert (from $GOPATH)
src/golang.org/x/net/http2/h2i/h2i.go:38:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
/usr/local/go/src/golang.org/x/crypto/ssh/terminal (from $GOROOT)
/go/src/golang.org/x/crypto/ssh/terminal (from $GOPATH)
src/golang.org/x/text/cmd/gotext/main.go:31:2: cannot find package "golang.org/x/tools/go/buildutil" in any of:
/usr/local/go/src/golang.org/x/tools/go/buildutil (from $GOROOT)
/go/src/golang.org/x/tools/go/buildutil (from $GOPATH)
src/golang.org/x/text/message/pipeline/extract.go:23:2: cannot find package "golang.org/x/tools/go/callgraph" in any of:
/usr/local/go/src/golang.org/x/tools/go/callgraph (from $GOROOT)
/go/src/golang.org/x/tools/go/callgraph (from $GOPATH)
src/golang.org/x/text/message/pipeline/extract.go:24:2: cannot find package "golang.org/x/tools/go/callgraph/cha" in any of:
/usr/local/go/src/golang.org/x/tools/go/callgraph/cha (from $GOROOT)
/go/src/golang.org/x/tools/go/callgraph/cha (from $GOPATH)
src/golang.org/x/text/message/pipeline/extract.go:25:2: cannot find package "golang.org/x/tools/go/loader" in any of:
/usr/local/go/src/golang.org/x/tools/go/loader (from $GOROOT)
/go/src/golang.org/x/tools/go/loader (from $GOPATH)
src/golang.org/x/text/message/pipeline/extract.go:26:2: cannot find package "golang.org/x/tools/go/ssa" in any of:
/usr/local/go/src/golang.org/x/tools/go/ssa (from $GOROOT)
/go/src/golang.org/x/tools/go/ssa (from $GOPATH)
src/golang.org/x/text/message/pipeline/extract.go:27:2: cannot find package "golang.org/x/tools/go/ssa/ssautil" in any of:
/usr/local/go/src/golang.org/x/tools/go/ssa/ssautil (from $GOROOT)
/go/src/golang.org/x/tools/go/ssa/ssautil (from $GOPATH)
src/google.golang.org/grpc/balancer/grpclb/grpclb_remote_balancer.go:31:2: cannot find package "github.com/google/go-cmp/cmp" in any of:
/usr/local/go/src/github.com/google/go-cmp/cmp (from $GOROOT)
/go/src/github.com/google/go-cmp/cmp (from $GOPATH)
src/google.golang.org/grpc/credentials/oauth/oauth.go:28:2: cannot find package "golang.org/x/oauth2" in any of:
/usr/local/go/src/golang.org/x/oauth2 (from $GOROOT)
/go/src/golang.org/x/oauth2 (from $GOPATH)
src/google.golang.org/grpc/credentials/oauth/oauth.go:29:2: cannot find package "golang.org/x/oauth2/google" in any of:
/usr/local/go/src/golang.org/x/oauth2/google (from $GOROOT)
/go/src/golang.org/x/oauth2/google (from $GOPATH)
src/google.golang.org/grpc/credentials/oauth/oauth.go:30:2: cannot find package "golang.org/x/oauth2/jwt" in any of:
/usr/local/go/src/golang.org/x/oauth2/jwt (from $GOROOT)
/go/src/golang.org/x/oauth2/jwt (from $GOPATH)
src/google.golang.org/grpc/xds/internal/client/cds.go:24:2: cannot find package "github.com/envoyproxy/go-control-plane/envoy/api/v2" in any of:
/usr/local/go/src/github.com/envoyproxy/go-control-plane/envoy/api/v2 (from $GOROOT)
/go/src/github.com/envoyproxy/go-control-plane/envoy/api/v2 (from $GOPATH)
src/google.golang.org/grpc/xds/internal/internal.go:23:2: cannot find package "github.com/envoyproxy/go-control-plane/envoy/api/v2/core" in any of:
/usr/local/go/src/github.com/envoyproxy/go-control-plane/envoy/api/v2/core (from $GOROOT)
/go/src/github.com/envoyproxy/go-control-plane/envoy/api/v2/core (from $GOPATH)
src/google.golang.org/grpc/xds/internal/balancer/lrs/lrs.go:27:2: cannot find package "github.com/envoyproxy/go-control-plane/envoy/api/v2/endpoint" in any of:
/usr/local/go/src/github.com/envoyproxy/go-control-plane/envoy/api/v2/endpoint (from $GOROOT)
/go/src/github.com/envoyproxy/go-control-plane/envoy/api/v2/endpoint (from $GOPATH)
src/google.golang.org/grpc/xds/internal/client/rds.go:26:2: cannot find package "github.com/envoyproxy/go-control-plane/envoy/api/v2/route" in any of:
/usr/local/go/src/github.com/envoyproxy/go-control-plane/envoy/api/v2/route (from $GOROOT)
/go/src/github.com/envoyproxy/go-control-plane/envoy/api/v2/route (from $GOPATH)
src/google.golang.org/grpc/xds/internal/client/lds.go:25:2: cannot find package "github.com/envoyproxy/go-control-plane/envoy/config/filter/network/http_connection_manager/v2" in any of:
/usr/local/go/src/github.com/envoyproxy/go-control-plane/envoy/config/filter/network/http_connection_manager/v2 (from $GOROOT)
/go/src/github.com/envoyproxy/go-control-plane/envoy/config/filter/network/http_connection_manager/v2 (from $GOPATH)
src/google.golang.org/grpc/xds/internal/client/types.go:24:2: cannot find package "github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2" in any of:
/usr/local/go/src/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2 (from $GOROOT)
/go/src/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2 (from $GOPATH)
src/google.golang.org/grpc/xds/internal/balancer/lrs/lrs.go:28:2: cannot find package "github.com/envoyproxy/go-control-plane/envoy/service/load_stats/v2" in any of:
/usr/local/go/src/github.com/envoyproxy/go-control-plane/envoy/service/load_stats/v2 (from $GOROOT)
/go/src/github.com/envoyproxy/go-control-plane/envoy/service/load_stats/v2 (from $GOPATH)
src/google.golang.org/grpc/xds/internal/client/eds.go:28:2: cannot find package "github.com/envoyproxy/go-control-plane/envoy/type" in any of:
/usr/local/go/src/github.com/envoyproxy/go-control-plane/envoy/type (from $GOROOT)
/go/src/github.com/envoyproxy/go-control-plane/envoy/type (from $GOPATH)
src/google.golang.org/grpc/xds/internal/proto/udpa/data/orca/v1/orca_load_report.pb.go:8:2: cannot find package "github.com/envoyproxy/protoc-gen-validate/validate" in any of:
/usr/local/go/src/github.com/envoyproxy/protoc-gen-validate/validate (from $GOROOT)
/go/src/github.com/envoyproxy/protoc-gen-validate/validate (from $GOPATH)
src/google.golang.org/grpc/examples/helloworld/mock_helloworld/hw_mock.go:8:2: cannot find package "github.com/golang/mock/gomock" in any of:
/usr/local/go/src/github.com/golang/mock/gomock (from $GOROOT)
/go/src/github.com/golang/mock/gomock (from $GOPATH)
src/google.golang.org/grpc/grpclog/glogger/glogger.go:26:2: cannot find package "github.com/golang/glog" in any of:
/usr/local/go/src/github.com/golang/glog (from $GOROOT)
/go/src/github.com/golang/glog (from $GOPATH)
src/sourcegraph.com/sourcegraph/appdash/cmd/appdash/appdash.go:58:2: cannot find package "github.com/jessevdk/go-flags" in any of:
/usr/local/go/src/github.com/jessevdk/go-flags (from $GOROOT)
/go/src/github.com/jessevdk/go-flags (from $GOPATH)
src/sourcegraph.com/sourcegraph/appdash/traceapp/app.go:34:2: cannot find package "sourcegraph.com/sourcegraph/appdash-data" in any of:
/usr/local/go/src/sourcegraph.com/sourcegraph/appdash-data (from $GOROOT)
/go/src/sourcegraph.com/sourcegraph/appdash-data (from $GOPATH)
src/sourcegraph.com/sourcegraph/appdash/examples/cmd/webapp/main.go:20:2: cannot find package "github.com/urfave/negroni" in any of:
/usr/local/go/src/github.com/urfave/negroni (from $GOROOT)
/go/src/github.com/urfave/negroni (from $GOPATH)

**Comment by hsluoyz** [comment]
This is not a Casbin issue, please get help from other places.
