### ISSUE TITLE
Separate “Watch.Update” from AutoSave

### ISSUE THREAD

**Issue by hongminzhang** [casbin/casbin#365]
1. Why issues this question？
Want to use Watch.Update when I don’t want to use AutoSave

2. What were you trying to achieve? 
Here are a few functions that need to be modified：addPolicy、removePolicy、removeFilteredPolicy ;
Separate “Watch.Update” from AutoSave

**Comment by nodece** [comment]
@hongminzhang Is it a performance issue?

**Comment by hongminzhang** [comment]
Yes, I need to update multiple rules at once，but each rule will notify other instances to reload rules，this puts pressure on the database，So，I don’t use authSave，but，I want to use watch

So，I want to Separate “Watch.Update” from AutoSave

**Comment by nodece** [comment]
It seems a good idea. Casbin should allow multiple rules to be added through the API. 
To improve performance, Casbin should be able to pause watcher to stop notifying other Casbin instance when policy changes.

@hsluoyz What's your opinion?

**Comment by hongminzhang** [comment]
I agree with your opinion. 
Casbin should store data and  notifying other Casbin instance after processing multiple rules in memory. 
This will greatly improve performance.

**Comment by hsluoyz** [comment]
Merged.

**Comment by nodece** [comment]
@hongminzhang Casbin v2.2.1 has been release.
