### ISSUE TITLE
[Security] enforce should return false, if enforcer is disabled

### ISSUE THREAD

**Issue by AmreeshTyagi** [casbin/casbin#367]
**Question:** 
What should be the behaviour, if `e.EnableEnforce(false)`?

**Current behaviour:**
It is returning `true` for all endpoint enforce e.g. `e.Enforce("54893465-371e-4195-a674-b510243aa1ae", "/api/v1/users", "GET")`

**Expected behaviour**
I believe, it should return `false` as a strict security measure, otherwise it will open all endpoint for public use, in case of one accidental change of configuration on production.

**Reference:**
https://github.com/casbin/casbin/blob/ea07e65dbd3fb5cda1b12e9030038d31a9f7a457/enforcer.go#L347
https://github.com/casbin/casbin/blob/ea07e65dbd3fb5cda1b12e9030038d31a9f7a457/enforcer.go#L348

Suggestions!

**Comment by hsluoyz** [comment]
`e.EnableEnforce(false)` means to disable Casbin check. So the request passes through Casbin with no issue.

**Comment by AmreeshTyagi** [comment]
ok. Thanks @hsluoyz . Sounds good.

Though, I have made clear separation in my application.
`EnableEnforce` means enabling/disabling Casbin enforcement (casbin is loaded to manage policies) &
`EnableCasbin` means enabling/disabling Casbin as a complete component(a check in my application).

I believe, configuration of passing through Casbin should be part of any application integrating Casbin not Casbin itself.

BTW, Thanks for clarification.

**Comment by hsluoyz** [comment]
Well. Let's leave this open, I'd like to see other opinions.

**Comment by jkour** [comment]
Having the option to enable/disable Casbin as a component works as a gate for any other requests to Casbin. 

What does it mean to disable the component in you app? You don't compile it with the component or you disable it at runtime? If the second, then this means there is no authorisation service in the app---and what do you expect to happen with permissions? Sounds like it will work in a super user or root mode. In this case, that state of the enforcer is irrelevant.

Now, given the component is active, if you disable the enforcer then everything is granted as @hsluoyz  says

**Comment by suryanshv23** [comment]
@hsluoyz correct me if I am wrong. If `e.EnableEnforce(false)` will disable Casbin considering such a case where a user doesn't need access control then why he/she will use that in the app.

Also on the negative side an accidental change can make all data public causing serious security issues.

**Comment by hsluoyz** [comment]
It's up to the application to have more complex mechanism to define what "disabling Casbin" means. But currently, Casbin itself will let all requests pass if it's disabled.
