### ISSUE TITLE
Add ruby to list of supported languages.

### ISSUE THREAD

**Issue by calebfaruki** [casbin/casbin#368]
I'm actively working on a ruby lang port of Casbin.

https://github.com/calebfaruki/ruby-casbin

**Comment by hsluoyz** [comment]
When will the code function basically?

**Comment by calebfaruki** [comment]
2-3 weeks?

**Comment by hsluoyz** [comment]
What's the project naming convention for Ruby? Which one is better?

1. ruby-casbin
2. casbin-ruby
3. casbin-rb
4. ...

**Comment by calebfaruki** [comment]
I named the git repository `ruby-casbin`. But when included as a dependency in a ruby project, it is simply `casbin`.

**Comment by hsluoyz** [comment]
I have created a repo here: https://github.com/calebfaruki/ruby-casbin, to make it official. I have added you to its admin and also the org member.

**Comment by hsluoyz** [comment]
Sorry that my URL was wrong, it should be: https://github.com/casbin/ruby-casbin

**Comment by hsluoyz** [comment]
@calebfaruki can you add the code to it?

**Comment by hsluoyz** [comment]
Closed as stale.
