### ISSUE TITLE
Panic when I use AutoLoadPolicy, add a policy in DB

### ISSUE THREAD

**Issue by YesXiamo** [casbin/casbin#376]
when I use **NewSyncedEnforcer**, and add policy in db, it panic, I think that's a bug for users,
can this code:`model[sec][key].Policy = append(model[sec][key].Policy, tokens[1:])`
change to 
```go
// verify sec and key 

if _,ok := model[sec][key];ok{
		model[sec][key].Policy = append(model[sec][key].Policy, tokens[1:])
	}
```
thanks!

**Comment by YesXiamo** [comment]
> Use RBAC model.

I already used the RBAC model, it panic when AutoLoadPolicy from DB.Because the key is not in "r,p,g,e,m"  while I add policy or change one.

**Comment by hsluoyz** [comment]
Please provide a minimized, not-confidential, reproducible example.

**Comment by hsluoyz** [comment]
Closed as stale.
