### ISSUE TITLE
Permission with RBAC and RBAC with Domain

### ISSUE THREAD

**Issue by brt-srini-rama** [casbin/casbin#378]
Hi,
  my requirement is some users have a policy bind with Domain, say normal_users(srini@xxxxxx@mrbstest2013.com) in the domain(northZone) could access the resource(desk) for action(view). At the same time admin users don't have any domain boundaries, My policy definition is as below.

p, normal_users, northZone, desk, book
p, normal_users, southZone, desk, view
p, normal_users, southZone, room, book
p, normal_users, northZone, room, view
p, admin_user, desk, assign

g, srini@xxxxxx.com, normal_users, northZone
g2, prashanth@xxxxxx.com, admin_user

my model is
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _,_

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g(r.sub, p.sub, r.dom) || g2(r.sub, p.sub)) && r.dom == p.dom && r.obj == p.obj && r.act == p.act

and my request is 
srini@xxxxxx.com, northZone, desk, book
prashanth@xxxxxx.com, desk, assign

When testing in the Casbin Editor I am getting the error "invalid request size: expected 4, got 3, rvals: prashanth@xxxxxx.com,desk,assign"

If anybody help me to understand the error it is great.

Thanks.

**Comment by nodece** [comment]
You are missing the domain parameter.

**Comment by brt-srini-rama** [comment]
For the second input request,  I don't have a domain information,  so I could not pass it,  only for the first request everything works fine. As soon as I enter the second request,  without domain,  I am getting this error. 
Is there any way that I can pass the request without domain as this is the mixed combination of RBAC and RBAC with domain.  Please advise.

**Comment by nodece** [comment]
Casbin only supports RBAC or RBAC with domain.

**Comment by suryanshv23** [comment]
@brt-srini-rama  in the case where you don't know the domain you can add a default domain in request

**Comment by brt-srini-rama** [comment]
OKay, default domain is an option, is it possible to handle with custom functions? any suggestions.

**Comment by nodece** [comment]
It doesn't support the domain is an optional.

**Comment by brt-srini-rama** [comment]
OKay, will go with the default domain
