### ISSUE TITLE
No Go files in redis adapter

### ISSUE THREAD

**Issue by FredySosa** [casbin/casbin#38]
Hi, I'd like to develop with your library and using redis, but, in the repo with that, there's nothing to use, just a readme but nothing else.
If it is not ready yet, i think is good idea remove that advantage from the main readme.
Thank's and greetings :hand:

**Comment by hsluoyz** [comment]
Hi @ankitm123, someone is asking for your redis adapter now.. But it only has a readme. Do you still have time to finish it?

**Comment by hsluoyz** [comment]
@FredySosa the Redis adapter is finished, please see: https://github.com/casbin/redis-adapter

**Comment by FredySosa** [comment]
Thank you, i appreciate your work so much 👍
