### ISSUE TITLE
casbin addNamedGroupingPolicy() to support domain

### ISSUE THREAD

**Issue by brt-srini-rama** [casbin/casbin#381]
Hi,
 I wonder, how to add the grouping policy to the DB when RBAC with domain is realized.
Basically my modle.conf has two groups one without domain and other with domain.

```ini
[role_definition]
g = _, _, _
g2 = _, _, _
g3 = _, _
g4 = _, _
```

I am using native "casbin-mongodb-adapter" for persisting the policy and group details and loading it on every bootup using adapter, and hence I am forced to use the API "Enforcer.addNamedGroupingPolicy()" but I lately understand the function take only three argument which is Group_Name, Role and the Group_Resource, but I need to pass additional argument which is domain. How to pass the fourth arguments to addNamedGroupingPolicy() function?
Any Clue is greatly appreciated.

Regards,
Srini.

**Comment by hsluoyz** [comment]
Hi, are you using (Golang) Casbin or Node-Casbin?

**Comment by brt-srini-rama** [comment]
NodeJS.... and I just tried passing the third argument and it worked. It could add the entry to the database. 

I will the issue. 

Thanks
