### ISSUE TITLE
NewEnforces should also accept []byte input or switch to a configuration struct

### ISSUE THREAD

**Issue by dalu** [casbin/casbin#383]
Currently you can pass a file path string to the NewEnforcer function
or you can pass a string and an adapter pointer to the function.

Thinking further that is a pretty vague way to accept parameters.
My original suggestion was to also allow []byte input for embedded configuration. (seems like a dirty hack, []byte because you can't distinguish between a file path or embedded configuration with certainty)

But now I believe it should be even more explicit.

```go

type EnforcerConfigurationType int
const (
  EnforcerConfigurationTypeFilename = iota
  EnforcerConfigurationTypeEmbedded
  EnforcerConfigurationTypeFilenameAdapter
)

type EnforcerConfiguration struct {
  Type EnforcerConfigurationType
  Filename string
  Adapter interface{}
  Embedded string
}

func NewEnforcer(config EnforcerConfiguration) (*Enforcer, error) {
  switch config.Type {
  case EnforcerConfigurationTypeFilename:
  // handle load file
  case EnforcerConfigurationTypeEmbedded:
  // handle passed embedded configuration as string
  case EnforcerConfigurationTypeFilenameAdapter:
  // handle filename and adapter
  default:
  // handle unsupported
  }
}
```

Why embedded?
Why would you have the policy configuration outside of the program where it can be edited more easily then an embedded configuration would?

I'm aware this change would introduce a breaking change.
But then again... if you created a new function
```go
func NewEnforcerWithConfig(config EnforcerConfiguration) (*Enforcer, error) {}
```
it would not.

**Comment by brantcam** [comment]
I will start on this today.

**Comment by hsluoyz** [comment]
I don't think `NewEnforcerWithConfig()` is a must-do feature for now. Casbin supports 8 languages. They all use the same API. Adding this merely in Golang doesn't help the whole picture much.

**Comment by dalu** [comment]
You are however unable to embed the security conf otherwise.

Do you understand what this issue is about? It's not about having a config struct, but to have a way to embed the conf file

**Comment by dalu** [comment]
And that's exactly why open source sucks. People who have no clue about what they're doing are publishing badly designed software. Keep your shit software. You will get bad publicity on all occasions anyone writes or says anything about this casbin joke.
Your mongo adapter is even using an abandoned library that hasn't seen new commits in 2 years.
Chinese Shit

**Comment by nodece** [comment]
Hi @dalu , please keep a friendly attitude.

**Comment by GopherJ** [comment]
@dalu, Remember that you represent Germany. If you dont like open source software then just create your own instead of judging the others. We are not paid to design perfect softwares for you, you don't pay to use casbin neither.

**Comment by jkour** [comment]
@dalu Your point about open source code sucks actually...There's a ton of commercial applications that are badly designed as well. 

The difference is that in open source code you are welcome and allowed to offer your opinion as you are doing now and people argue on this. In closed or commercial software run by huge companies, you would be nuisance to the ears of the developers unless you are MS-like.

Anyways, you are not forced to use any open source code and guess what...you can always fork it and add your implementation for your personal use
