### ISSUE TITLE
The Vue-Axios request could not get the request body of 403. There is a cross-domain problem

### ISSUE THREAD

**Issue by 1103036128** [casbin/casbin#385]
When I request the background with axios and return a 401 error, I can read the guard data
![image](https://user-images.githubusercontent.com/35803296/76942785-4468e980-6939-11ea-8a94-50424d4ba1a0.png)
![image](https://user-images.githubusercontent.com/35803296/76942800-4c288e00-6939-11ea-9cfe-29eab89c8aff.png)
I returned a 403 error when I requested the background with axios, but could not get the return information and had cross-domain problems
![image](https://user-images.githubusercontent.com/35803296/76943011-9dd11880-6939-11ea-8322-e2aa938bc79f.png)
![image](https://user-images.githubusercontent.com/35803296/76943050-ae818e80-6939-11ea-9063-a218c9a82730.png)
![image](https://user-images.githubusercontent.com/35803296/76943064-b6d9c980-6939-11ea-9066-4d15a89f9a0f.png)
I hope you can help me, thanks a million~~

**Comment by 1103036128** [comment]
My casbin config as following

**Comment by hsluoyz** [comment]
This is a authN or CORS issue, not Casbin related.
