### ISSUE TITLE
Hardcoded policy effect of model

### ISSUE THREAD

**Issue by stephanhorsthemke** [casbin/casbin#39]
Hey!

I had some issues with understandin the policy effect. 
First it was not clear that this effect is only important when there are multiple matching policies. I finally understood that when viewing the code. 
But that left me with another question: Why did you implement the policy effects so complicated when you just have four different cases.
Do you plan to expand the policy effect cases in the future and use govaluate aswell?

Anyways, it would be cool if it is more obvious when reading the docs! Because I tried to play around with deny/allow and some/any, but nothing went as expected. :)

thanks

**Comment by hsluoyz** [comment]
> Do you plan to expand the policy effect cases in the future and use govaluate aswell?

Yes, although not finished yet.

> Anyways, it would be cool if it is more obvious when reading the docs! Because I tried to play around with deny/allow and some/any, but nothing went as expected. :)

Can you improve the docs or at least tell me how to improve it? :)

**Comment by hsluoyz** [comment]
Closed as stale.
