### ISSUE TITLE
Casbin v2 Error: "panic: interface conversion: *beegoormadapter.Adapter is not persist.Adapter: missing method LoadPolicy"

### ISSUE THREAD

**Issue by MaksNech** [casbin/casbin#390]
My app stop with panic error. What is problem with casbin v2 and beego-orm-adapter? Could You help please?

My "go.mod" file:

go 1.14
require (
	github.com/casbin/beego-orm-adapter v0.0.0-20180421160615-ba104911ae5b
	github.com/casbin/casbin/v2 v2.2.1
)

**Comment by nodece** [comment]
`github.com/casbin/beego-orm-adapter`  need to support `go.mod` and  use the 'github.com/casbin/casbin/v2'

**Comment by hsluoyz** [comment]
Hi @MaksNech I have transferred your first issue to: https://github.com/casbin/casbin/issues/390

Please do not open a new one.

**Comment by DivyPatel9881** [comment]
So, I think docs of this adapter repo should be changed, I think that caused the problem.
