### ISSUE TITLE
Suggestion: provide contribution document for Casbin

### ISSUE THREAD

**Issue by nodece** [casbin/casbin#393]
Casbin is an open-source project.  We need more developer help to make Casbin even more awesome.

## things to do

- Development environment
- Contribution Workflow
- Testing

**Comment by hsluoyz** [comment]
Any progress?

**Comment by DARK-art108** [comment]
is this issue still open can I work upon this? @hsluoyz

**Comment by hsluoyz** [comment]
@nodece any comment?

**Comment by nodece** [comment]
@DARK-art108 We have a [contributing guide](https://github.com/casbin/casbin/blob/master/CONTRIBUTING.md), but it misses the contribution workflow, could you append this or add more?

**Comment by DARK-art108** [comment]
Sure I will add those can list me some details about it @nodece

**Comment by hsluoyz** [comment]
Done at: https://casbin.org/docs/contributing
