### ISSUE TITLE
Suggestion: add automate package releases

### ISSUE THREAD

**Issue by nodece** [casbin/casbin#394]
> automates the whole package release workflow including: determining the next version number, generating the release notes and publishing the package. - https://github.com/semantic-release/semantic-release

I added [semantic-release](https://github.com/semantic-release/semantic-release) to [node-casbin](https://github.com/casbin/node-casbin) and feel great, so I suggest add  automate package releases. 

But I don't know what to do in golang.

**Comment by hsluoyz** [comment]
Good idea. Wait for someone to work on it.

**Comment by GopherJ** [comment]
Hello @nodece is it easy to add it for casbin-rs: https://github.com/casbin/casbin-rs we also want it :)

**Comment by hsluoyz** [comment]
@nodece is this working now? Why I don't see new releases?

**Comment by nodece** [comment]
@GopherJ I will work on it.

**Comment by nodece** [comment]
@hsluoyz We need a PR to test it.

**Comment by GopherJ** [comment]
I created also an issue for casbin-rs: https://github.com/casbin/casbin-rs/issues/90

**Comment by hsluoyz** [comment]
Is there any progress on this? @nodece @GopherJ

**Comment by nodece** [comment]
@hsluoyz I want to use https://github.com/semantic-release/semantic-release, WDYT?

**Comment by hsluoyz** [comment]
I think it works good in Node-Casbin. We can use it in Golang too. I remembered that you made a PR several weeks ago about it, but finally got it closed.

**Comment by nodece** [comment]
I will work on it as soon.

**Comment by nodece** [comment]
Hi @hsluoyz, I added [semantic-release](https://github.com/semantic-release/semantic-release) to current repo. we need to notice that strictly following the [Semantic Versioning specification](https://www.conventionalcommits.org/en/v1.0.0-beta.2/).

Let's add [semantic-pull-requests](https://github.com/zeke/semantic-pull-requests) to check Semantic Versioning specification.

**Comment by hsluoyz** [comment]
@nodece thanks for this work! Look forward to the semantic PR feature!

**Comment by hsluoyz** [comment]
Is this feature finished?

**Comment by nodece** [comment]
@hsluoyz Yeah. If commit doesn't following the [Semantic Versioning specification](https://www.conventionalcommits.org/en/v1.0.0-beta.2/), semantic-release can not trigger release.


see the https://github.com/casbin/casbin/runs/645614357#step:3:37.
