### ISSUE TITLE
Include change's details when calling Watcher.Update()

### ISSUE THREAD

**Issue by urigoori** [casbin/casbin#398]
Hello,

I’m implementing my own watcher using MySQL and when the enforcer call the watcher.update, is there a way to know what was the change? This call is happening in both addPolicy and removePolicy (and probably in other methods as well) and I need to track the change so other enforcer will get updated

Yang Luo: Why do you need to know the change?

To allow scaling, the casbin code is running on several docker containers. To sync those containers - to update other containers with changes happened in one container and to get updates from other running containers - the application is using table called “casbin_changes”. The table is holding the changes every container applied and the other containers get updates from this table (excluding the changes they initiated) . Those sync actions happen using Watcher with “SetUpdateCallback” and “update”. For this to happen the application need to serialize and de-serialize the change and need to understand what the was that change

**Comment by hsluoyz** [comment]
We should implement a new WatchEx interface to add this functionality.

**Comment by nodece** [comment]
Casbin should add the hooks. somethings like:  
`post-policy`:  The `post-policy` hook runs after the add/remove policy is completed.

**Comment by hsluoyz** [comment]
@nodece good idea. We should put logging, watcher notification, etc. into these hooks. Or even let users define custom hooks.

**Comment by hsluoyz** [comment]
We have WatcherEx to resolve this issue from this PR: https://github.com/casbin/casbin/pull/400

The docs is here: https://casbin.org/docs/en/watchers#watcherex
