### ISSUE TITLE
Reloading policies

### ISSUE THREAD

**Issue by sagikazarmark** [casbin/casbin#40]
Nowadays it's quite common that multiple instance of an application run scaled in clouds.

What is the proper way of reloading policies in case they change in one of the instances?

I guess it's a quite common, so some sort of builtin or suggested solution would be nice.

For example:

- automatic reload of policies every X minutes (opt-in)
- some distributed messaging solution (listening to a channel maybe, where a custom messaging solution could push messages)
- add support to adapters to implement a way to check for updates (eg. changed timestamp in a database)

(Update: BTW the library is great, thanks)

**Comment by hsluoyz** [comment]
Thanks for point it out. As I see here, the ways 1) and 2) need to start a new process/goroutine to poll or listen to the channel. the 3) way does not require it. It can check the timestamp right before every Enforce() call. Is it a good practice for Casbin to start a process/goroutine to reload changed policies?

**Comment by sagikazarmark** [comment]
I think it should be somewhat configurable/depend on the use case and adapters.

All the three options should be opt-in and disabled by default. When the user specifically asks for reloading, I think it's okay to start goroutines.

Also, option two requires some sort of custom implementation as well in which case it's not a problem at all.

Ultimately, one could just write a completely custom solution like this:
```go
go func() { e.LoadPolicies() }()
```

But it would be nice to have some kind of builtin support, even if it requires opt-in from the user.

**Comment by hsluoyz** [comment]
I have implemented the 1st way: ``automatic reload of policies every X minutes (opt-in)``. Please see: https://github.com/casbin/casbin/commit/093596e330a509f57dcdf20f3e7e89a32ce08acb

**Comment by sagikazarmark** [comment]
Sorry for late answer.

I'm a bit confused about what `PeriodicallyLoadPolicy` does: it accepts a duration but 30ms is hardcoded? Where is it used?

Also, it might make sense to use some locking for `StartAutoLoadPolicy`? Dunno if `LoadPolicies` is concurrent safe, this way it's easier to get into some trouble because of concurrency.

**Comment by hsluoyz** [comment]
``PeriodicallyLoadPolicy()`` is not used actually, I have removed it.

I have implemented the synced version of ``LoadPolicy()`` and ``SavePolicy()``, please see: https://github.com/casbin/casbin/commit/eccff7aa947a6a0fdafe996a76272ab6f4d58c84

**Comment by hsluoyz** [comment]
The distributed messaging solution is developed, please see: https://github.com/casbin/etcd-watcher
