### ISSUE TITLE
Master-Slaves Pattern

### ISSUE THREAD

**Issue by YoshieraHuang** [casbin/casbin#402]
Hello guys, I'm working on casbin service for scalable backend applications and I try to sync all the stuffs between each containers. In my opinions, Watcher and WatcherEx, which is not released, can only sync the contents of each enforcer but do not help when new enforcer is created. Does casbin support Master-Slave(MS) pattern, where master receives the enforcer operation message, syncs the enforcer to slaves, and slaves do enforce things, like mysql or mongodb?

**Comment by hsluoyz** [comment]
I hope someone can work on the master-slave feature, maybe based on current Watcher, WatcherEx or create a mechanism from scratch.

**Comment by dovics** [comment]
This sounds interesting,I am working on a distributed system, and I need some time to design it, I don't think a simple watcher will meet our needs

**Comment by andrewXuy** [comment]
Hi there, I would like to tackle this issue. May I fork it and try to figure it out?

**Comment by nodece** [comment]
@andrewXuy Fantastic! We are welcome your contribution.

**Comment by pasanh** [comment]
This is important for us also. To ensure we have a cluster of instances to support the volume of enforcement operations we have.

**Comment by hsluoyz** [comment]
@nodece @dovics I think master-slave mode should be supported as part of our Summer 2020 project: https://github.com/casbin/Summer2020#3-casbin%E5%88%86%E5%B8%83%E5%BC%8F%E6%8F%92%E4%BB%B6-golang

@dovics can you take this issue?

**Comment by nodece** [comment]
@hsluoyz hraft-dispatcher has been released. I think we close this issue.

**Comment by hsluoyz** [comment]
@nodece @YoshieraHuang OK, please use: https://github.com/casbin/hraft-dispatcher
