### ISSUE TITLE
Casbin RESTFUL with RBAC

### ISSUE THREAD

**Issue by kowthalganesh** [casbin/casbin#404]
hello everyone,
Facing some issue in casbin validation

My data set
```sql
1	p	Project Manager	/applications/applicationbyuserid/*	GET	allow
3	p	Project Manager	/conversations/*	GET	allow
4	p	Project Manager	/projects/*	GET	allow
5	p	Project Manager	/projectmilestones/*	GET	allow
6	p	Project Manager	/projectteammemberroles/*	GET	allow
7	p	Project Manager	/referencecodedetails/*	GET	allow
8	p	Project Manager	/tasks/*	GET	allow
9	p	Project Manager	/*	GET	allow
10	p	Project Manager	/users/*	GET	allow
11	g	kxg8313	Project Manager	write	
```

Policy.conf

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = regexMatch(r.obj, p.obj) && regexMatch(r.act, p.act) 
```

it always returns as false, I was whitelisting the URL like applications/applicationbyuserid/* 
I don't know where am missing. can anyone help me out @hsluoyz 
actual app URL will be: applications/applicationbyuserid/abc7878

**Comment by nodece** [comment]
@kowthalganesh correct matcher: `m = g(r.sub, p.sub) & regexMatch(r.obj, p.obj) && regexMatch(r.act, p.act)`.

**Comment by nodece** [comment]
We provides built-in function, please refer to https://casbin.org/docs/en/function.

**Comment by kowthalganesh** [comment]
i gone through the documents already. i have updated the matchers what you have shared
![policy](https://user-images.githubusercontent.com/5681640/77651609-0c921f80-6f93-11ea-8ae0-cfbb0cb86333.png)
![tmp](https://user-images.githubusercontent.com/5681640/77651611-0dc34c80-6f93-11ea-9e2f-915ad82163f1.png)

still am getting false as a result

**Comment by nodece** [comment]
You use an error `model` and `policy`. We provide a `https://casbin.org/en/editor` for testing.

**Comment by kowthalganesh** [comment]
I need the model like this, I can't compromise with the model. so better will create a custom function and validate. is it makes sense ?

**Comment by nodece** [comment]
I provide  a `model` and `policy`, hope to help you.

Mode: 
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && regexMatch(r.obj, p.obj) && regexMatch(r.act, p.act)
```

Policy: 
```
p, Project-Manager, /applications/applicationbyuserid/*,  GET
g, kxg8313, Project-Manager
```

It means `kxg8313` inherits/is a member of role `Project-Manager` then`enforcer('kxg8313', '/applications/applicationbyuserid/1', 'GET')` returns `ture`.

**Comment by kowthalganesh** [comment]
@nodece it's working now, what's the mistake I did ? only I change project manager to project-manager and its started working. is anything i missed. Thanks for your support

**Comment by nodece** [comment]
@kowthalganesh , The `policy` needs to match `request_definition` and `policy_definition`.

**Comment by kowthalganesh** [comment]
For Front-end Implementation. 
model = [request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && regexMatch(r.obj, p.obj) && regexMatch(r.act, p.act)

casbinData = [{
	"id": 1,
	"ptype": "g",
	"v0": "PM",
	"v1": "Project-manager",
	"v2": "write",
	"v3": "",
	"v4": "",
	"v5": ""
}, {
	"id": 2,
	"ptype": "p",
	"v0": "PM",
	"v1": "create_project",
	"v2": "write",
	"v3": "",
	"v4": "",
	"v5": ""
}]
const e = await newEnforcer(newModel(model), casbinData);
since its front end angular app, i was getting the model from api as a json response.
But its throwing an error. unable to load this json in to policy

![image](https://user-images.githubusercontent.com/5681640/77817193-1df03e80-70ef-11ea-9ccc-927e0b6b9db0.png)

**Comment by dovics** [comment]
casbinDate should be
```
casbinData = [{
"id": 1,
"ptype": "g",
"v0": "PM",
"v1": "Project-manager",
"v2": "",
"v3": "",
"v4": "",
"v5": ""
}, {
"id": 2,
"ptype": "p",
"v0": "PM",
"v1": "create_project",
"v2": "write",
"v3": "",
"v4": "",
"v5": ""
}]
```
the policy of `g` should be only two values, representing the relationship between them.  this should match `role-definition`

**Comment by nodece** [comment]
@kowthalganesh If have any question in `node-casbin`, please make an issue in https://github.com/casbin/node-casbin/issues.

simple code:

```typescript
import { newEnforcer, newModel, StringAdapter } from "casbin";

const model = `[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && regexMatch(r.obj, p.obj) && regexMatch(r.act, p.act)
`;

const policy = `
p, project-role, /project/*, GET
g, user1, project 
`;

const e = await newEnforcer(newModel(model), new StringAdapter(policy));
```
