### ISSUE TITLE
casbin.SyncedEnforcer does not adhere to casbin.IEnforcer interface

### ISSUE THREAD

**Issue by jimmy-ho** [casbin/casbin#405]
When trying to use the generic  **casbin.IEnforcer** instead of ***casbin.SyncedEnforcer** (I assume the others do not too) it appears the **AddFunction** method does not conform to the interface.

```
        *casbin.SyncedEnforcer does not implement casbin.IEnforcer (wrong type for AddFunction method)
                have AddFunction(string, govaluate.ExpressionFunction)
                want AddFunction(string, func(...interface {}) (interface {}, error))
```

Looking at the other **AddFunction** methods they all use the **govaluate.ExpressionFunction** (and omits any return values) and the interface should possibly change to this, unless there is a reason I am missing?

**Comment by dovics** [comment]
Are you using the latest casbin? If not please upgrade, we have fixed this in #373

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
@jimmy-ho Casbin 2.2.2 has been released.

**Comment by jimmy-ho** [comment]
Thanks for the quick turnaround, latest v2.2.2 fixes the problem
