### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by japettyjohn** [casbin/casbin#41]
In my use case I will have dynamically changing user/role assignments which I was planning to user Enforcer.AddRoleForUser. I've seen a lot of maps and no use of the sync package, I didn't audit the package but is this style of use thread safe?

**Comment by hsluoyz** [comment]
Thanks for pointing this out. My initial plan is using a RWMutex, ``Enforcer.Enforce()`` will be protected with read lock and functions like ``Enforcer.AddRoleForUser()`` will be protected with write lock, what do you think?

**Comment by japettyjohn** [comment]
For my use case this is workable. If anyone else has performance concerns and does not have the use case of dynamic policies etc. this could be made as a thin wrapper.

**Comment by hsluoyz** [comment]
I have added a wrapper here: https://github.com/casbin/casbin/commit/9251d5db63750ff7e476a28dec2b550b03c0efa7

**Comment by japettyjohn** [comment]
This looks great and it dropped in for without issues. I think this will cover most/all concurrent RW scenarios. Thanks!

**Comment by e-nikolov** [comment]
The Safe variants of methods (ones that return an error instead of panic) aren't thread safe at the moment because they are not wrapped.

**Comment by e-nikolov** [comment]
@hsluoyz I know that, but the safe methods are also available from the synced enforcer, however they are not thread safe because they are not wrapped with mutexes the way the non-safe methods are.

**Comment by hsluoyz** [comment]
OK. So you need both safe methods and synced enforcer at the same time, right? We can add the ``enforcer_safe_synced.go`` file to implement those functions.

Can you send a PR for it? I can also do it but it may take several days.

**Comment by hsluoyz** [comment]
BTW, you can also propose a new issue to claim this problem, as this issue has already been closed for long time.

**Comment by e-nikolov** [comment]
I could make a PR. I am only thinking that in the current model, there are enforcer, enforcer_synced, enforcer_safe, enforcer_cached. So every time that a new combination of those is needed, methods would sort of have to be duplicated. Is it an option to use something like Functional Options, and be able to do this: casbin.NewEnforcer(casbin.Synced(), casbin.Cached())?

**Comment by hsluoyz** [comment]
``casbin.NewEnforcer(casbin.Synced(), casbin.Cached())`` will make the constructor even complicated. Do we have a non-intrusive way to specify synced or cached? e.g., ``enforcer.enableCache(), enforcer.enableSync()`` ?
