### ISSUE TITLE
Removing rules and groups by domain

### ISSUE THREAD

**Issue by kispilz** [casbin/casbin#410]
Based on #408 , when I delete a community, I'd also like to remove all the rules and groups for this community(/domain).

Is there a fast way to purge all rules and group definitions associated with a single domain, short of doing manual SQL queries?

| p\_type | v0 | v1 | v2 | v3 | v4 | v5 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| p | owner | 12 | community | \(edit\)\|\(delete\) |  |  |
| p | admin | 12 | post | \(edit\)\|\(delete\) |  |  |
| p | admin | 12 | comment | \(edit\)\|\(delete\) |  |  |
| p | owner | 13 | community | \(edit\)\|\(delete\) |  |  |
| p | admin | 13 | post | \(edit\)\|\(delete\) |  |  |
| p | admin | 13 | comment | \(edit\)\|\(delete\) |  |  |
| g | c46c0637-19a4-454e-a3db-28006e0de009 | owner | 12 |  |  |  |
| g | owner | admin | 12 |  |  |  |
| g | c46c0637-19a4-454e-a3db-28006e0de009 | owner | 13 |  |  |  |
| g | owner | admin | 13 |  |  |  |

`DELETE FROM casbin_rule WHERE v1 = 12`
`DELETE FROM casbin_rule WHERE v2 = 12`

**Comment by nodece** [comment]
Casbin provides the API:
https://casbin.org/docs/en/management-api#removefilteredpolicy
https://casbin.org/docs/en/management-api#removefilteredgroupingpolicy

**Comment by kispilz** [comment]
Hmm...
what about 

g | owner | admin | 12
-- | -- | -- | --

There should be a way to `PurgeDomainPoliciesAndGroups(domain string)` IMHO

**Comment by kispilz** [comment]
`RemoveFilteredGroupingPolicy(0, "owner" )` has deleted all rules from the database, even those that were not associated with "owner".

Here's what I had to do to delete the created policies and group definitions:

```go
	if _, err := s.casbinEnforcer.RemovePolicy("owner", fmt.Sprintf("%d", community.ID), "community", "(edit)|(delete)"); err != nil {
		return err
	}
	if _, err := s.casbinEnforcer.RemovePolicy("admin", fmt.Sprintf("%d", community.ID), "post", "(edit)|(delete)"); err != nil {
		return err
	}
	if _, err := s.casbinEnforcer.RemovePolicy("admin", fmt.Sprintf("%d", community.ID), "comment", "(edit)|(delete)"); err != nil {
		return err
	}
	if _, e := h.s.CasbinEnforcer().DeleteRoleForUserInDomain(subjectID, "owner", id); e != nil {
		cx.AbortWithStatusJSON(500, gin.H{"error": e.Error()})
		return
	}
	if _, e := h.s.CasbinEnforcer().RemoveNamedGroupingPolicy("g", "owner", "admin", id); e != nil {
		cx.AbortWithStatusJSON(500, gin.H{"error": e.Error()})
		return
	}
```

That doesn't take into account subjects that might be part of the admin group of that domain.

GetAllSubjects() returns
```
([]string) (len=2 cap=8) {
 (string) (len=5) "owner",
 (string) (len=5) "admin"
}
```
despite

| p\_type | v0 | v1 | v2 | v3 | v4 | v5 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| p | owner | 20 | community | \(edit\)\|\(delete\) |  |  |
| p | admin | 20 | post | \(edit\)\|\(delete\) |  |  |
| p | admin | 20 | comment | \(edit\)\|\(delete\) |  |  |
| g | c46c0637-19a4-454e-a3db-28006e0de009 | owner | 20 |  |  |  |
| g | owner | admin | 20 |  |  |  |

**Comment by kispilz** [comment]
To get all users or roles of a group in a domain
`s.casbinEnforcer.GetUsersForRoleInDomain("admin", "20")`
this gets all users and roles of the role admin and the domain 20
```
([]string) (len=2 cap=2) {
 (string) (len=36) "e9d0f7a3-548c-46ed-ac09-2155273dfddc",
 (string) (len=5) "owner"
}
```
| p\_type | v0 | v1 | v2 | v3 | v4 | v5 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| p | owner | 20 | community | \(edit\)\|\(delete\) |  |  |
| p | admin | 20 | post | \(edit\)\|\(delete\) |  |  |
| p | admin | 20 | comment | \(edit\)\|\(delete\) |  |  |
| g | c46c0637-19a4-454e-a3db-28006e0de009 | owner | 20 |  |  |  |
| g | owner | admin | 20 |  |  |  |
| g | e9d0f7a3-548c-46ed-ac09-2155273dfddc | admin | 20 |  |  |  |

Is a generic PurgeDomainPoliciesAndGroups possible at all?

For my specific case it is possible but a generic one?

**Comment by kispilz** [comment]
For completeness sake:

This table:

| p\_type | v0 | v1 | v2 | v3 | v4 | v5 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| p | owner | 21 | community | \(edit\)\|\(delete\) |  |  |
| p | admin | 21 | post | \(edit\)\|\(delete\) |  |  |
| p | admin | 21 | comment | \(edit\)\|\(delete\) |  |  |
| g | c46c0637-19a4-454e-a3db-28006e0de009 | owner | 21 |  |  |  |
| g | owner | admin | 21 |  |  |  |
| g | e9d0f7a3-548c-46ed-ac09-2155273dfddc | admin | 21 |  |  |  |

and those commands:

```go
	fmt.Println("--- Subjects ---")
	spew.Dump(s.casbinEnforcer.GetAllSubjects())
	fmt.Println("--- Objects ---")
	spew.Dump(s.casbinEnforcer.GetAllObjects())
	fmt.Println("--- Roles ---")
	spew.Dump(s.casbinEnforcer.GetAllRoles())
	fmt.Println("--- Actions ---")
	spew.Dump(s.casbinEnforcer.GetAllActions())

	fmt.Println("--- owners ---")
	spew.Dump(s.casbinEnforcer.GetUsersForRoleInDomain("owner", "21"))
	fmt.Println("--- admins ---")
	spew.Dump(s.casbinEnforcer.GetUsersForRoleInDomain("admin", "21"))
```

result in this output
```
--- Subjects ---
([]string) (len=2 cap=4) {
 (string) (len=5) "owner",
 (string) (len=5) "admin"
}
--- Objects ---
([]string) (len=1 cap=4) {
 (string) (len=2) "21"
}
--- Roles ---
([]string) (len=2 cap=4) {
 (string) (len=5) "owner",
 (string) (len=5) "admin"
}
--- Actions ---
([]string) (len=3 cap=4) {
 (string) (len=9) "community",
 (string) (len=4) "post",
 (string) (len=7) "comment"
}
--- owners ---
([]string) (len=1 cap=1) {
 (string) (len=36) "c46c0637-19a4-454e-a3db-28006e0de009"
}
--- admins ---
([]string) (len=2 cap=2) {
 (string) (len=5) "owner",
 (string) (len=36) "e9d0f7a3-548c-46ed-ac09-2155273dfddc"
}
```

**Comment by kispilz** [comment]
And my PurgeDomain function looks like this:
```go
func (s *Service) CasbinPurgeDomain(domainID string) error {
	owners := s.casbinEnforcer.GetUsersForRoleInDomain("owner", domainID)
	for _, owner := range owners {
		if _, e := s.casbinEnforcer.DeleteRoleForUserInDomain(owner, "owner", domainID); e != nil {
			return e
		}
	}
	admins := s.casbinEnforcer.GetUsersForRoleInDomain("admin", domainID)
	for _, admin := range admins {
		if _, e := s.casbinEnforcer.DeleteRoleForUserInDomain(admin, "admin", domainID); e != nil {
			return e
		}
	}
	/*
	if _, e := s.casbinEnforcer.RemoveNamedGroupingPolicy("g", "owner", "admin", domainID); e != nil {
		return e
	}
	 */
	if _, err := s.casbinEnforcer.RemovePolicy("owner", domainID, "community", "(edit)|(delete)"); err != nil {
		return err
	}
	if _, err := s.casbinEnforcer.RemovePolicy("admin", domainID, "post", "(edit)|(delete)"); err != nil {
		return err
	}
	if _, err := s.casbinEnforcer.RemovePolicy("admin", domainID, "comment", "(edit)|(delete)"); err != nil {
		return err
	}
	return nil
}
```

A generic one would have to get all policies line by line and analyze them, then build `RemovePolicy` functions, go through all group rules and build `DeleteRoleForUserInDomain` functions.
