### ISSUE TITLE
生产环境，root 权限无法验证通过，复现地址在下面！

### ISSUE THREAD

**Issue by 851091009** [casbin/casbin#411]
复现地址：https://github.com/851091009/casbin

说明：在go 编译环境使用 go run main.go 运行，root 权限可以正常验证，在编译环境 ./main root 权限也可以验证通过。但是把编译后的 main 文件，在生产环境就会出现 root 验证失败的情况！

**Comment by nodece** [comment]
@851091009 Please describe the issue in English.

**Comment by hsluoyz** [comment]
You should extract model and policy out of your complicated example, and test them on our online editor first: https://casbin.org/en/editor
