### ISSUE TITLE
Fix:  adding policy to adapter before trying to add into model

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin#415]
Recently I'm having issue with the following code in `internal_api.go`

```go
func (e *Enforcer) addPolicy(sec string, ptype string, rule []string) (bool, error) {
	ruleAdded := e.model.AddPolicy(sec, ptype, rule)
	if !ruleAdded {
		return ruleAdded, nil
	}

	if e.adapter != nil && e.autoSave {
		if err := e.adapter.AddPolicy(sec, ptype, rule); err != nil {
			if err.Error() != notImplemented {
				return ruleAdded, err
			}
		}
	}

	if e.watcher !=nil && e.autoNotifyWatcher {
		err := e.watcher.Update()
		if err != nil {
			return ruleAdded, err
		}
	}

	return ruleAdded, nil
}
```

It seems logic, but it may cause bugs while having network or io issues. For example it fails to add policy into adapter for some reason but it succeeds to add policy into model. Then it return an error to say that we don't succeed to add policy but actually we already added policies into model and it will influence the enforce result.

To solve this, shall we add policy into adapter first? I mean when auto save has been enabled.

**Comment by GopherJ** [comment]
Will it be better to write like this (example in rust):

```rust
        if self.auto_save {
            if !self.adapter.add_policy(sec, ptype, rule.clone()).await? {
                return Ok(false);
            }
        }

        self.model.add_policy(sec, ptype, rule);

        EMITTER.lock().unwrap().emit(Event::PolicyChange, self);

        Ok(true)
```

**Comment by GopherJ** [comment]
Close as it doesn't cause problems in golang.

**Comment by hsluoyz** [comment]
Why close it? What does `it doesn't cause problems in golang.` mean?

**Comment by GopherJ** [comment]
Hello @hsluoyz it seems that we can return both `rule_added` and `err` in golang. So I'm not sure if it causes problems

**Comment by GopherJ** [comment]
In casbin-rs I think it's better to insert firstly into adapter instead of model, so if it fails to insert into adapter, we don't even need to insert into model.

https://github.com/casbin/casbin-rs/blob/301420c7630cd3b6021f9738facf213e19080dc8/src/internal_api.rs#L52

```rust
 if self.auto_save && !self.adapter.add_policy(sec, ptype, rule.clone()).await? {
            return Ok(false);
        }

        let rule_added = self.model.add_policy(sec, ptype, rule);
        if rule_added {
            EMITTER.lock().unwrap().emit(Event::PolicyChange, self);
        }

        Ok(rule_added)
```

**Comment by hsluoyz** [comment]
@GopherJ I think you are right. We should keep the same behavior for all Casbin implementations. So Golang Casbin can also be updated if needed.

**Comment by nodece** [comment]
I don't think this is correct. 

```rust
if self.auto_save {
    if !self.adapter.add_policy(sec, ptype, rule.clone()).await? {
        return Ok(false);
    }
}

let rule_added = self.model.add_policy(sec, ptype, rule);
if rule_added {
    EMITTER.lock().unwrap().emit(Event::PolicyChange, self);
}
Ok(rule_added)
```

We should call `model.has_policy` to check if there is the policy in the model. When it returns `false` call the `adapter.add_policy`, otherwise return `OK(false)`.

**Comment by hsluoyz** [comment]
@nodece oh, I forgot checking existence. Agreed!

**Comment by GopherJ** [comment]
@nodece why do we need `model.has_policy`? Like in casbin-rs, we use `indexmap` to avoid duplicated policy, I'm not sure how does it goes with golang or node-casbin. But we should guarantee this in `model` and `adapter` level.

**Comment by GopherJ** [comment]
But I agree if the existence is not guaranteed at `Model` and `Adapter` level, we cannot use the following code:

```
f self.auto_save && !self.adapter.add_policy(sec, ptype, rule.clone()).await? {
            return Ok(false);
        }

        // If it succeeds to arrive here that means we already inserted policy into adapter when             auto_save is activated, 
        // and we are sure it can succeed to insert into model
        // however, this may mean we need a "correct" implementation of adapter
        let rule_added = self.model.add_policy(sec, ptype, rule);
        if rule_added {
            EMITTER.lock().unwrap().emit(Event::PolicyChange, self);
        }

        Ok(rule_added)
```

**Comment by GopherJ** [comment]
In general cases we should use @nodece 's advice because there maybe some adapters we cannot add constraint

**Comment by nodece** [comment]
Let's follow up for all Casbin!

**Comment by GopherJ** [comment]
@nodece  Another question,  if we are using `FilteredAdapter`, how can we know if the new policy is duplicated or not?

Like in total we have:
```
p, alice, /data1, read
p, alice, /data2, read
```

**Comment by GopherJ** [comment]
Any idea? @nodece  it seems buggy

**Comment by nodece** [comment]
It seems tricky.  What do you think of the built-in `filter` in Casbin?

**Comment by nodece** [comment]
It seems tricky.  What do you think of the built-in `filter` in Casbin? 

Users can customize rules for `filter` to load policies.

**Comment by hsluoyz** [comment]
@GopherJ we should only allow policy updating on the specific FilteredAdapter. e.g., If an FilteredAdapter instance is configured to show alice policies, then it should also be allowed to edit alice's policies too.

```
p, alice, /data1, read
p, alice, /data2, read
```

**Comment by GopherJ** [comment]
@hsluoyz  I think currently we don't have this? casbin-rs won't need this because util now all the adapter will check if the insert will duplicate policy.

**Comment by hsluoyz** [comment]
@GopherJ no, need development

**Comment by GopherJ** [comment]
@hsluoyz  Ok got it, for this moment casbin-rs doesn't need it because adapter will also check duplicated policy using db constraints

**Comment by hsluoyz** [comment]
@speza I think we agreed on updating adapter first, then update memory. Can you make a PR for it?
