### ISSUE TITLE
enforce_with_filter?

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin#418]
Let's say we have an UI and a backend, I use casbin to secure our backend's REST API, and in frontend we call `getImplicitPermissionsForUser` to get all the policies of certain user. Then with these downloaded policies we can then decide if some SPA component should be shown or not.

It works fine on my side.

But I'm not satisfaid that we cannot have a filter for enforce function. Like in my situation (REST API + SPA), I would like to make the policies of frontend different from the backend's. So I added `NA` to be the action of all the policies designed for frontend.

Certainly I don't want `enforce` to use these policies for enforcing because I just need enforcer being able to return all these **NA** policies.

However in casbin, we don't have something for handling this.

**Comment by GopherJ** [comment]
To be more exact:

```rust
p, alice, dom1, /data1, read
p, alice, dom1, component1, NA  // enforcer should ignore this because its' just static data for UI
```

**Comment by GopherJ** [comment]
```
enforce_with_flter(rvals, ["", "", "", "NA"])
```

can solve this type of problem

**Comment by nodece** [comment]
Why we cannot use multiple casbin?

**Comment by GopherJ** [comment]
@nodece You mean two casbin with `FilteredAdapter` ?

**Comment by nodece** [comment]
@GopherJ Yes, I recommend two cabin instance.

**Comment by GopherJ** [comment]
@nodece It's possible but I would say it's not good enough, we should have a way to distinguish different policies. Also two enforcers may mean that I need to have two ports open (server) for UI.

**Comment by nodece** [comment]
What do you think that ties to use p2?

**Comment by GopherJ** [comment]
Closed because I may handle it in application level

**Comment by hsluoyz** [comment]
@GopherJ why don't use `GetFilteredPolicy()`?
