### ISSUE TITLE
I want to combine RBAC and ABAC. I read a lot of documentation and I have a few questions.

### ISSUE THREAD

**Issue by MatthewPattell** [casbin/casbin#419]
Hello everyone. I wanna choose casbin for manage authorization. I read a lot of documentation and I have a few questions.

I want to combine RBAC and ABAC. With RBAC I want to control the general access to the API. With ABAC, I want to control access to certain entities (records in database). For example, I have the entity of orders and the entity of the company. **Should I create three enforcers?** The first one will be with the RBAC model. The second with the ABAC model to control the entity of orders. The third with the ABAC model to control the entity of companies. **Right?** (each entity has its own set of fields).

The procedure will be as follows (request to API):

Run the RBAC enforcer to determine if the user has access to the entity.
Run the ABAC enforcer for a specific entity (orders or companies).
In the case of ABAC, should I first select an entity from the database and pass it to the enforcer?
What if the user requests a list of orders (pagination = 1000)? How to handle this? For example, I can’t pass 1000 entities to an enforcer (my idea is that there should be a common API point, which, depending on the rule, gives only those records that satisfy the condition of the model matcher)?
P.S. Sorry for my english. Thanks.

**Comment by hsluoyz** [comment]
@nodece @GopherJ

**Comment by hsluoyz** [comment]
You only need one model: RBAC mixed with ABAC.

You can define a function called `getAttribute(p.obj, "owner")` to dynamically evaluate ABAC policies.

**Comment by MatthewPattell** [comment]
@hsluoyz thanks for reply. 

> You can define a function called getAttribute(p.obj, "owner") to dynamically evaluate ABAC policies.

This works for one model, not list models (select 1000 rows and pass to enforcer, it is slowly).

What about part 2:

> What if the user requests a list of orders (pagination = 1000)? How to handle this? For example, I can’t pass 1000 entities to an enforcer (my idea is that there should be a common API point, which, depending on the rule, gives only those records that satisfy the condition of the model matcher)?

**Comment by hsluoyz** [comment]
@nodece @GopherJ

**Comment by nodece** [comment]
@maplebeats 
part 1:
We already support multiple ABAC rule in #427.  With this feature, we can easily combine ABAC and RBAC. 

part2:
Due to I don't know that your logic, I guess you should record user orders to casbin.

**Comment by hsluoyz** [comment]
See docs about scaling ABAC rules feature: https://casbin.org/docs/en/abac#scaling-the-model-for-complex-and-large-number-of-abac-rules

**Comment by MatthewPattell** [comment]
@nodece this simple example:

<details>
<summary>Show casbin model.</summary>
<p>

```js
const model = `
[request_definition]
r = sub, obj

[policy_definition]
p = sub, obj, eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = r.act == p.act && g(r.sub, p.sub) && regexMatch(r.obj, p.obj)
`;
```

</p>
</details> 

```js
const casbin = require('casbin');

const adapter = await SequelizeAdapter.newAdapter(_.merge({
	dialect: 'mysql',
}, {/*some config*/}));
const enforcer = await casbin.newEnforcer(casbin.newModel(model), adapter);

/**
 * Get list project models
 *
 * @param {User} currentUser
 *
 * @return {Array.<Project>}
 */
const list = async (currentUser) => {
	// What is the logic casbin?

	// Select project models from mysql
	const result = await Project.findAll({
		// How to apply casbin ABAC rules to a query?
		where: {
			active: true
		},
		limit: 500,
		offset: 0,
	});

	// What is the logic casbin?
	await enforcer.enforce(???, currentUser);

	return result;
};
```

**Comment by nodece** [comment]
Is user get own projects?

**Comment by MatthewPattell** [comment]
@nodece I updated my [previous reply](https://github.com/casbin/casbin/issues/419#issuecomment-631615413).

**Comment by nodece** [comment]
Maybe we can use RBAC with domain.
Model
```
[request_definition]
r = sub, table, obj

[policy_definition]
p = sub, table, obj

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

Policy
```
p, user1, project, *, GET
p, user2, project, 1, GET
```

Code
```js
const query = await e.getFilteredPolicy(0, 'user1', 'project');
// check the query
```

**Comment by MatthewPattell** [comment]
Thanks for reply.

**Comment by sagarshah1983** [comment]
@MatthewPattell 
Did you get an answer to your question? I am curious how did you solve it?
Could you please provide suggestion on how to solve it for objects that are being loaded from database in thousands or even more size. How do we run policy check against each of them and verify if user has access to that entity or not?

> What if the user requests a list of orders (pagination = 1000)? How to handle this? For example, I can’t pass 1000 entities to an enforcer (my idea is that there should be a common API point, which, depending on the rule, gives only those records that satisfy the condition of the model matcher)?

**Comment by MatthewPattell** [comment]
@sagarshah1983 I had to create an additional table where I saved the roles and the corresponding filtering rules. 
E.g: 
```
userRole | filter
guest       | {"userId": "{{ userId }}"}
user         | {"userId": "{{ userId }}"}
admin      | {}
```

... and I created in gateway middleware function (I have microservices architecture) which get user role and userId from casbin. After thant I send to microservice filter like: {"userId": "1"}, and microservice include this filter in query to DB.

**Comment by sagarshah1983** [comment]
Makes sense to me. Thank you for your prompt reply @MatthewPattell !

**Comment by sagarshah1983** [comment]
@MatthewPattell - I am guessing that this can get too complex specifically when using ABAC policies with multiple criteria in order to determine the access list for the user based on user (sub) as well as resource (obj) attributes. Are there any alternatives?I think, if my records are over thousands, then running enforce for each of them could be a performance overhead, so I would prefer defining access rules in one place (casbin), but I am not sure, how can I use that to define the query filter

**Comment by hsluoyz** [comment]
@sagarshah1983 see: https://casbin.org/docs/en/data-permissions

**Comment by sagarshah1983** [comment]
> @sagarshah1983 see: https://casbin.org/docs/en/data-permissions

Thank you for your reply. That did help!
Having said that, can it be applied for ABAC rules or RBAC with tenants? I tried simple RBAC with tenants and when trying to get implicit permissions for a user, I did not get any permissions that were assigned to his role for a tenant. Not sure, if its an open issue or I missed something?

**Comment by hsluoyz** [comment]
@sagarshah1983 plz send a new github issue with your model and policy

**Comment by sagarshah1983** [comment]
Thank you. I created this - https://github.com/casbin/casbin/issues/767

**Comment by sagarshah1983** [comment]
Thank you @harveyappleton. That was useful! My policy was more or less similar except that I kept rules in the policy itself instead of isMatch function and providing attributes & conditions as properties to policy.
Agree, that this seems more neat than what I was building :)

**Comment by harveyappleton** [comment]
Yeh I would have loved to have kept the rules in Casbin model if possible, but isMatch (partial object property matching) and includes (array includes element) with some custom logic wasn't obvious how to achieve sadly.

**Comment by Tapas059** [comment]
Hi @harveyappleton , I am implementing same , but when i used your model and tried to check in editor . I am getting false result everytime . Can you let me know how you have achieved this **isMatch (partial object property matching)**  .  And for above model  what is the correct match ? Thank you ...

**Comment by harveyappleton** [comment]
Hey @Tapas059 - I added a custom matcher function - this one from Lodash [https://lodash.com/docs/4.17.15#isMatch](url)

eg 
```    
await this.enforcer.addFunction('isMatch', (attributes: object, conditions: string) => isMatch(attributes, JSON.parse(conditions)));
```

Tbh though Casbin is really designed for string matching. I'm bending it to my will here and using a lot of `JSON.stringify` and `JSON.parse` to make it work, so it's not the most ideal solution.
