### ISSUE TITLE
Correct GoDoc link in README.md

### ISSUE THREAD

**Issue by l0nax** [casbin/casbin#420]
The current _godoc_ link refers to https://godoc.org/github.com/casbin/casbin which contains the _old_ documentation for `v1.9.1`.

But the _new_ documentation (starting from `v2.x`) is available under https://pkg.go.dev/github.com/casbin/casbin/v2.

The documentation under https://pkg.go.dev/github.com/casbin/casbin/v2 allows also to view the documentations from old versions (`v1.x` and `v0.x`) so I think the link can easily be changed without any Issues.

**Comment by hsluoyz** [comment]
Not found:

![image](https://user-images.githubusercontent.com/3787410/79234098-5a1bf100-7e9c-11ea-81a2-2e1be8fef18d.png)

**Comment by l0nax** [comment]
I looks like that it works only via https://pkg.go.dev/.

Correct URL: https://pkg.go.dev/github.com/casbin/casbin/v2?tab=doc

**Comment by dovics** [comment]
`godoc` doesn't understand modules, so Pkg.go.dev is a new destination for Go discovery & docs.

https://github.com/golang/go/issues/33654

We can also use this address: https://godoc.org/github.com/casbin/casbin/v2?redirect=on.

**Comment by hsluoyz** [comment]
https://pkg.go.dev/github.com/casbin/casbin/v2 is good.

Can anyone make a PR to fix the README?
