### ISSUE TITLE
wacher cannot handle concurrent request

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin#421]
Image of having 2 enforcers, they synchronize each other by a redis-watcher and when requests come, one of the two enforcers will handle it like load banlancer.

Then two concurrent requests come:
```
// AddPolicy
p, alice, /data1/, read

// RemovePolicy
p, alice, /data1/, read
```

At this time `AddPolicy` request will be allocated to enforcer1, and `RemovePolicy` request will be allocated to enforcer2.

Then image a tricky situation, redis is online and slow to respond, then in this case enforcer2 will handle first `RemovePolicy` request. We will get false result because  enforcer2 doesn't sync policies yet, so enforcer2 will consider:

```
p, alice, /data1, read
```

doesn't exist, not able to remove

**Expected behaviour**

Be able to handle concurrent request:
```
// AddPolicy
p, alice, /data1/, read

// RemovePolicy
p, alice, /data1/, read
```
Make it possible to add and then remove policy correctly

**Actual happenning**

redis can be slow, enforcers may receive request before calling watcher's update callback, we will get false result.

**Comment by GopherJ** [comment]
In my opinion, we shouldn't use this type of mecanisme and we should try to implement #402 , in this case `Master` will be the only open agent for all enforcers, when one request comes, `Master` enforcer decides if the message should be broadcast or handled by one of the `slave` enforcer.

If it's enforcing request, then it chooses a `slave` enforcer to respond
If it's management request (AddPolicy/RemovePolicy...), then it broadcast to every enforcer so that they lock themself before handling a new request

**Comment by hsluoyz** [comment]
@GopherJ the current Watcher is buggy. I love the Master-slave idea. Maybe we can use Casbin-Server: https://casbin.org/docs/en/service as a starting point.

When Master-slave is ready, we can deprecate the Watcher.

**Comment by hsluoyz** [comment]
This is not a Casbin specific issue. Any other system like MySQL can have such issue too. It's more about business logic. So closed here.
