### ISSUE TITLE
how to configure matcher in relationship  user-role-policygroup

### ISSUE THREAD

**Issue by lovelin9** [casbin/casbin#428]
i want build policy model like  user-role-policygroup，but i don`t know how to configure the matcher correctly

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2= _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && regexMatch(r.act, p.act)
```

```csv
ptype | v0 | v1 | v2
g | user | role |  
g2 | role | policygroup1 |  
g2 | role | policygroup2 |  
p | policygroup1 | /a | *
p | policygroup2 | /b | *
```

**Comment by hsluoyz** [comment]
@nodece @GopherJ

**Comment by nodece** [comment]
I provide a simple example use `p` and `g`:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && regexMatch(r.act, p.act)
```

```csv
ptype | v0 | v1 | v2

p | as_user | /a | *
p | as_user | /b | *

p | as_role | /c | *

g | role_or_user | as_user |  

g | user1 | as_role | 
```

Casbin doesn't verify whether a user is a valid user, or role is a valid role. 

It  means `user1` inherits/is a member of role `as_role` and can get access `/a` via `*` action; `role_or_user` inherits/is a member of user `as_user` and can get access `/a` or `/b`  via `*` action;

**Comment by lovelin9** [comment]
Hi, @nodece 
thanks, i will use the base user-role configuration

i want admin user can configure role permission flexible.
so it`s nice to see if able to have a model like user-role-policygroup-policy

**Comment by nodece** [comment]
Casbin supports it.  But Casbin doesn't distinguish is `role` or ` user` in `g` and `p`.

```
ptype | v0 | v1 | v2
g | user | role |  
g | role | policygroup1 |  
g | role | policygroup2 |  
p | policygroup1 | /a | *
p | policygroup2 | /b | *
```

**Comment by lovelin9** [comment]
hi, @nodece 
thansk, this is what i want
