### ISSUE TITLE
suggestion: add github-action-benchmark

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin#429]
https://github.com/rhysd/github-action-benchmark  is cool and can be used for golang.

https://github.com/PsiACE added it for me in https://github.com/casbin/casbin-rs, maybe someone can add it for casbin golang?

So that we can visualize the bench for every commit like: https://casbin.org/casbin-rs/dev/bench/

It can send alert message when there is a big bench regression.

**Comment by hsluoyz** [comment]
Looks great. But we don't have GitHub actions for this repo yet. Should we first enable and configure it? https://github.com/casbin/casbin/actions

**Comment by GopherJ** [comment]
yes @hsluoyz I think

**Comment by nodece** [comment]
What do you think of Migrate from Travis-CI  to GitHub Actions? @hsluoyz

**Comment by hsluoyz** [comment]
I think we can keep both for now. Then slowly deprecate Travis-CI if nothing goes wrong. So you can start working on GitHub Actions now.

**Comment by hsluoyz** [comment]
Is this finished?

**Comment by nodece** [comment]
We've got some problems and waiting to solve the https://github.com/rhysd/github-action-benchmark/issues/30

**Comment by hsluoyz** [comment]
Closed as stale.
