### ISSUE TITLE
Approach Question: Support different level of roles with one policy file

### ISSUE THREAD

**Issue by leopragi** [casbin/casbin#433]
How to implement multiple levels of roles with a single policy file on the RESTful model?

For example,
`
user A is user type creator. Even though he is an creator, we need to assign some roles explicitly, like [read, write]. Now my RESTful policy has to check both the admin type and multiple roles.

All I can think of now is to

create a policy file that has user type (as subject) and compare user type with the enforce method
create a policy file that has roles (as subject) and compare each of the roles with the enforce method
Now when a request comes in, I have to call enforce method 3 times (1 to check user type and 2 to check roles type).

Is this how it should be done or any good approach?

**Comment by hsluoyz** [comment]
@nodece @GopherJ

**Comment by leopragi** [comment]
@hsluoyz 

I was able to implement it with following model and policy:

Model:
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)
```

Policy:
```
p, user:read, /v1/users, GET
p, user:write, /v1/users, (POST)|(PUT)

g, read, user:read

g, write, user:read
g, write, user:write

g2, viewer, read

g2, creator, read
g2, creator, write
```


Request:
```
creator, /v1/users, PUT
read, /v1/users, POST
user:read, /v1/users, GET
```

Where **read** and **write** are roles for the user, and **creator** is the user type. 

SO, if I want to check requests with multiple roles, do I need to check it with one by one?

**Comment by GopherJ** [comment]
@leopragi  Sorry I didn't fully understand your design, why do we need to check `user_type` ?

**Comment by jkour** [comment]
@leopragi According to your design, what do you expect the requests to return in each case in terms of allow and deny?

**Comment by jkour** [comment]
@leopragi and something else...you say user A is creator (a role) and an admin (another role) you need to explicitly add read, write. Do you add them on creator/admin or on user A?

And in terms of what the roles can do, what is the difference between admin and creator?

**Comment by leopragi** [comment]
@jkour @GopherJ 

I m using two different terminologies:

**userType**: creator, viewer
**roles**: read, write

a **userType** can have a subset of **roles**. 
Ex: 
creator [read, write]
creator [read]
viewer [read]

Now I have to check both **userType** and **roles**.
First, it will check on **userType** level and if satisfied, then I will check **roles** level.
If anyone of them is not satisfied, then it should fail.  

Let's look at my question:
When a request comes, I have to check both the **userType** and **roles**. So do I need to make three calls?
Like this: `e.enforce(userType) && (e.enforce(role2) || e.enforce(role1))`


For now, its two roles, I have to check it two times for role1 and role2. What if I have 15 roles assigned to me?

**Comment by jkour** [comment]
It looks like you have to do the enforcement the way you describe (with && and ||) but I don't think your model is correctly defined. It looks to me like an RBAC model with domain/tenants or resources. Have a look at the example models.

So, if I get it correctly, user A can be a creator (with read/write permissions) and viewer (with view permissions) for /v1/users URL.  

According to your policy, what is the result of these calls?
creator, /v1/users, PUT
read, /v1/users, POST
user:read, /v1/users, GET

**Comment by GopherJ** [comment]
@leopragi userType should be considered as attributes and extra information. You can even use rbac_with_domain_model and  instead of putting domain you can put your userType

**Comment by leopragi** [comment]
Results should be:
creator, /v1/users, PUT = true
read, /v1/users, POST = false
user:read, /v1/users, GET = true

are you also suggesting to use RBAC model with domain, instead of for my approach.
@jkour 

This is already working with the above model and policy. I will check about **rbac_with_domain_model** @GopherJ

**Comment by jkour** [comment]
@leopragi I am not sure I see why you have creator, read and then user:read as subject; and it looks weird that you have different policies for user:read and user:write. This in my view shouldn't be correct.

The first part of the policy, as you define it in the model file, should be the subject---so what does it mean in the context of your application to have a subject called 'read'?

The enforce calls don't seem ok too...should be like enforce ('your_username, /v1/users, PUT)?

**Comment by leopragi** [comment]
```
Added few more rules in Policy:

p, user:read, /v1/users, GET
p, user:write, /v1/users, (POST)|(PUT)
p, team:read, /v1/teams, GET
p, team:write, /v1/teams, (POST)|(PUT)

g, read, user:read
g, read, team:read
g, write, user:read
g, write, user:write
g, write, team:read
g, write, team:write

g2, viewer, read
g2, creator, read
g2, creator, write
````
Let me explain it to you:
I have two license types: **viewer, creator**
I have roles: **read, write**
So, viewer license have only **read** role
and creator license have both **read** and **write**

Here user:read, user:write is something that I see called **action**, Which is kind of permission for an API call. A User needs these actions to be present in his role to call that specific API call. 



Reason why i m not using username: enforce(username, /v1/users, PUT)
I m not storing my rules based on username, it's based on roles and license type

Please take a look at this: https://zupzup.org/casbin-http-role-auth/
The guide which I followed, Here they using **user type**. 
I m trying to use both **user type** and **roles**, in my case, both should be satisfied. **user type** may have permission to call an API, but at the end **roles** should decide whether the user have permission to call that API.

The way I implemented should not be correct, something doesn't feel right for me, that why I post this thread. How will you implement this system in your opinion?

**Comment by leopragi** [comment]
<img width="1280" alt="Screenshot 2020-04-24 at 8 42 28 AM" src="https://user-images.githubusercontent.com/25412884/80171283-958a8e00-8607-11ea-8f8d-47a705563f61.png">

Implementation with RBAC with domains/tenants (Looks good for me)

**Comment by nodece** [comment]
@hsluoyz This is a good solutions, we should create a label for good solutions.

**Comment by leopragi** [comment]
@nodece 

Actually I'd prefer to stick with some other solution that I wrote. The problem with the above solution is if you don't assign a role to access a specific feature and if license have access to that specific feature. It will simply allow. 

According to my requirement, even though I have a license that allows me to access `featureA`, it has to be explicitly specified by role also, If not specified, it should not allow.

license(featureA) = true and role(featureA) = true ===> true
license(featureA) = true and role(featureA) = false ===> false
license(featureA) = false and role(featureA) = true ===> false
license(featureA) = false and role(featureA) = true ===> false

The above method doesn't work in that case. So, what I did is to consider the license as a (kind of) subject. Please take a look at this.

<img width="1278" alt="Screenshot 2020-04-30 at 8 12 40 AM" src="https://user-images.githubusercontent.com/25412884/80666613-60c08000-8aba-11ea-9558-24f5dab40a8e.png">

**Comment by hsluoyz** [comment]
@nodece label created: https://github.com/casbin/casbin/labels/good%20solutions
