### ISSUE TITLE
Suggestion: Make ClearPolicy optional during LoadFilteredPolicy

### ISSUE THREAD

**Issue by ashwinsadeep** [casbin/casbin#434]
I'm designing a system where we have a rather small number of access control policies - say less than 1000. These policies will be defined on roles. However, the system has a somewhat large number of users and corresponding group membership policies - say 10M users & 20M group memberships considering an average of 2 groups per user.

I was thinking of an approach where I can load all access control policies - `p`- on initialization and then load the grouping policies - `g` - on demand while processing requests. 

However, every `LoadFilteredPolicy` is also clearing the existing policies which are loaded which is not ideal. I'm proposing that we add an `autoClear` field which can control this behaviour.

Another approach we can take is to make Model pluggable the same way you have done for Adapters & Watchers. This will allow more control over `ClearPolicy` behaviour.

Please note that the group memberships itself will be cached and probably have the enforcers sharded based on a user_id_hash maybe. These details are probably out of scope for this discussion, but mentioning anyway to add some context.

**Comment by GopherJ** [comment]
@ashwinsadeep  The problem of this method is **we can have duplicated policies in memory**, casbin is an auth library but has no ability to do things like Full-text searching to find the part of policies related to request.

we didn't find a good method for implementing `dynamic filtered adapter` yet.

**Comment by ashwinsadeep** [comment]
IMO, this will be a requirement for any medium to large sized system where storing the entire policy information in memory is not practical. In my case at least, the expected access patterns will be such that only a relatively small subset of subjects accessing a small subset of resources will be active at any given point of time.

Further to that, I don't think a `dynamic filtered adapter` in itself is going to be enough. We'll need significant changes in the model implementation to allow for pruning policies by a `filter` as well. For instance, I'll want to build the adapter such that it'll have an in-memory LRU cache on top of the persistent datastore. So whenever a a policy is getting evicted from memory, I'll want to remove it from model as well while removin

**Comment by GopherJ** [comment]
@ashwinsadeep while `dynamic filtered adapter` loads filtered policies, casbin will clean the policies in memory. Actually I don't think we will really need to prune policies from model because we just need to overwrite with filtered policies and then rebuild the role links, the process here is easy to be done in casbin today. It can be improved: like not overwrite all but do incremental changes.

However, I didn't see a clean and efficient method for loading the part of policies related to request. Like a request:

```
alice, domain1, /data1, read
```

we will need to find the list of policies related to it so that we can load them dynamically. The speed here is important because:

```
enforce time = network transport + filter policies + network transport + rebuild role links + enforce

// versus normal enforcer, adapter
enforce time = enforce
```

but how to quickly find the `filtered policies`? I have no idea yet.

**Comment by hsluoyz** [comment]
@ashwinsadeep you can implement your own role manager to handle all `g` policy rule logic: https://casbin.org/docs/en/role-managers . Only provide `p` rules in the Casbin adapter. All `g` rules are handled through the new role manager.

**Comment by ashwinsadeep** [comment]
@hsluoyz We've eventually settled on a somewhat similar approach. Subject role mapping is passed along in a JWT. At the enforcer, we get the subject role mapping from the JWT and use those roles during enforcement.

Casbin adapter is only loading p policies which does not change very often.

**Comment by hsluoyz** [comment]
Good to hear that you found the solution! I will close this issue for now.
