### ISSUE TITLE
assinging a user to an object role in rbac_with_pattern_policy.csv 

### ISSUE THREAD

**Issue by ghaedi93** [casbin/casbin#435]
https://github.com/casbin/casbin/blob/907df7925df1a0e7b565cb915f316278bcb5d19d/examples/rbac_with_pattern_policy.csv#L9

in our model we are dealing subject roles with a g and object roles with g2 but here in this example it seems like user cathy is being assigned to pen_admin role and book_group role both with a g identifier why should we assign a user to a resource role with a g identifier and why exactly should we do so in the first place ?   the purpose is kinda confusing. 
cathy > /book/1/2/3/4/5 > book_group

**Comment by hsluoyz** [comment]
@ghaedi93 that's a typo. It should be `g2`. @nodece can you fix it?

**Comment by hsluoyz** [comment]
@ghaedi93 fixed.
