### ISSUE TITLE
merge_effect quick return?

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin#439]
Currently if we are using effect like:

```
some(where (p_eft == allow))
```

or

```
!some(where (p_eft == deny))
```

or

```
some(where (p_eft == allow)) && !some(where (p_eft == deny))
```

there isn't any optimization (quick return) it always need to iterate the whole list of policy which is not ideal because sometimes we just need to find one match and quick return the enforcing result.

**Comment by hsluoyz** [comment]
I think this idea is good.

**Comment by GopherJ** [comment]
implemented in: https://github.com/casbin/casbin-rs/pull/142

**Comment by DivyPatel9881** [comment]
Okay, then I will implement it for casbin-core

**Comment by GopherJ** [comment]
hi @DivyPatel9881 I just found that channel's overhead is out of my imagination so I reverted the PR and made https://github.com/casbin/casbin-rs/pull/145

**Comment by DivyPatel9881** [comment]
Okay, I will check this out.

**Comment by GopherJ** [comment]
@DivyPatel9881 I would suggest a new interface similar to this: https://github.com/casbin/casbin-rs/blob/master/src/effector.rs

**Comment by nodece** [comment]
@DivyPatel9881 Is there any progress?

**Comment by DivyPatel9881** [comment]
Yes, I am on it. I have added ```EffectorStream``` interface and its corresponding default implementation as ```DefaultEffectorStream``` struct. Now just some changes have to be made in the enforcer implementation. After completion of changes in Enforcer implementation, I will be posting a PR.

**Comment by nodece** [comment]
@DivyPatel9881 Thanks for your contribution. It is greatly improve performance.

**Comment by nodece** [comment]
@DivyPatel9881 How is your progress?

**Comment by DivyPatel9881** [comment]
Almost done. Today I will be posting a PR regarding this.

**Comment by GopherJ** [comment]
I think this can be closed
