### ISSUE TITLE
Port Casbin for Rust's scaling ABAC rules to Golang

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin#440]
See: https://github.com/casbin/casbin/issues/354

Can anyone take this issue?

**Comment by DivyPatel9881** [comment]
@hsluoyz isn't this a fix #427

**Comment by DivyPatel9881** [comment]
If not, I can take this issue.

**Comment by hsluoyz** [comment]
Oh I forgot it. Let's proceed with that PR.

**Comment by GopherJ** [comment]
This can be closed @hsluoyz
