### ISSUE TITLE
GetImplicitUsersForPermission cannot get users in role

### ISSUE THREAD

**Issue by wz369** [casbin/casbin#442]
// GetImplicitUsersForPermission gets implicit users for a permission.
// For example:
// p, admin, data1, read
// p, bob, data1, read
// g, alice, admin
//
// GetImplicitUsersForPermission("data1", "read") will get: ["alice", "bob"].
// Note: only users will be returned, roles (2nd arg in "g") will be excluded.

but,i only got [ "bob"]. no "alice". this function cannot get users only Appears in g

**Comment by nodece** [comment]
Thanks for the report.

I submitted a patch: #443

**Comment by hsluoyz** [comment]
Merged.
