### ISSUE TITLE
Hit "undefined function eval" when trying with ABAC example

### ISSUE THREAD

**Issue by fanqi1909** [casbin/casbin#445]
Hi, 
I am trying to run the ABAC example from https://casbin.org/docs/en/abac with sub_rule.

The policy model is
```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub_rule, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = eval(p.sub_rule) && r.obj == p.obj && r.act == p.act
```
and the policy is
```csv
p, r.sub.Age > 18, /data1, read
p, r.sub.Age < 60, /data2, write
```
I write a sample code as follows:
```go
type UserContext struct {
	Name string
	Age int
}
// in main()
res, err:= enforcer.Enforce(UserContext{
   Name: "alice",
   Age:  18,
}, "data1", "write", )
log.Print(err, "\t", res)
```
This prints
```
 Undefined function eval     false
``` 

Could you please advise how to enable the `eval()` method ?

Thanks.
Jay

**Comment by hsluoyz** [comment]
@nodece @GopherJ @DivyPatel9881 can anyone answer it?

**Comment by fanqi1909** [comment]
Btw, I am using  go version 1.14, and  github.com/casbin/casbin/v2 v2.2.3.

**Comment by GopherJ** [comment]
@fanqi1909 You can check here: https://github.com/casbin/casbin/releases, you need to use the latest version, it's just released

**Comment by fanqi1909** [comment]
thanks @GopherJ ,  I think this is the catch. After changing to v2.3.0, the eval() function works.

Thanks.
Jay
