### ISSUE TITLE
When should i call BuildRoleLinks function

### ISSUE THREAD

**Issue by UnderTreeTech** [casbin/casbin#455]
My App has about 1 millions policies, 800k P policy and 200K G policy. 
Whenever I add new P policy and assign it to one role, should I call BuildRoleLinks function?

**Comment by GopherJ** [comment]
@UnderTreeTech It's called automatically

**Comment by UnderTreeTech** [comment]
@GopherJ I disabled the attribute. I wanna know whether BuildRoleLinks exists performance issue in my scenario.

**Comment by nodece** [comment]
You need to call BuildRoleLinks after add G policy.

**Comment by UnderTreeTech** [comment]
@hsluoyz As far I run the model_b_test.go bench by adjusting parameters to 10k roles, 500k users, it costs about 11m and panic(error run too long). So i worry about the performance of casbin much. Do you guys have any plan to optimize performance?

**Comment by GopherJ** [comment]
@UnderTreeTech Also pay attention that the time of benchmarking != time of enforcing. Could you put the final result? How long it took for one operation?

**Comment by GopherJ** [comment]
In casbin-rs, it's:

test b_benchmark_rbac_model_large         ... bench:  38,076,023 ns/iter (+/- 3,918,314)

for 10k roles, 500k users.

and currently casbin golang is 5x faster than casbin-rs...

**Comment by GopherJ** [comment]
@UnderTreeTech in casbin-rs, we start to support incremental building role links

**Comment by UnderTreeTech** [comment]
> @UnderTreeTech in casbin-rs, we start to support incrementally building role links since: [casbin/casbin-rs#139](https://github.com/casbin/casbin-rs/pull/139)

@hsluoyz Awesome feature, hope go casbin can support it asap.

**Comment by UnderTreeTech** [comment]
> In casbin-rs, it's:
> 
> ```
> test b_benchmark_rbac_model_large         ... bench:  38,076,023 ns/iter (+/- 3,918,314)
> ```
> 
> for 10k roles, 500k users.
> 
> and currently casbin golang is 5x faster than casbin-rs so normally it should be fine for you.

Test failed, the following is panic messages.

```
[root@benchmark casbin]# go test -bench=BenchmarkRBACModelLarge -run=none
SIGQUIT: quit
PC=0x4684a1 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x7812a8, 0x80, 0x0, 0x0, 0x0, 0xc00002df48, 0xc00002df58, 0x7ffcb1c7e108, 0x7ffcb1c7e128, 0x40ba5f, ...)
        /usr/local/go/src/runtime/sys_linux_amd64.s:567 +0x21
runtime.futexsleep(0x7812a8, 0x7ffc00000000, 0xffffffffffffffff)
        /usr/local/go/src/runtime/os_linux.go:45 +0x46
runtime.notesleep(0x7812a8)
        /usr/local/go/src/runtime/lock_futex.go:151 +0x9f
runtime.stopm()
        /usr/local/go/src/runtime/proc.go:1828 +0xc0
runtime.findrunnable(0xc00002c800, 0x0)
        /usr/local/go/src/runtime/proc.go:2360 +0xa0d
runtime.schedule()
        /usr/local/go/src/runtime/proc.go:2520 +0x2fc
runtime.park_m(0xc000180180)
        /usr/local/go/src/runtime/proc.go:2690 +0x9d
runtime.mcall(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [chan receive, 10 minutes]:
testing.(*B).run1(0xc0000ee1c0, 0xc0000ee1c0)
        /usr/local/go/src/testing/benchmark.go:233 +0x9e
testing.(*B).Run(0xc0000ee000, 0x5fb5c6, 0x17, 0x6042e0, 0x4e2600)
        /usr/local/go/src/testing/benchmark.go:651 +0x341
testing.runBenchmarks.func1(0xc0000ee000)
        /usr/local/go/src/testing/benchmark.go:533 +0x78
testing.(*B).runN(0xc0000ee000, 0x1)
        /usr/local/go/src/testing/benchmark.go:191 +0xe8
testing.runBenchmarks(0x5fcc0b, 0x1b, 0xc0000a8220, 0x77c620, 0x19, 0x19, 0xc0000d9e01)
        /usr/local/go/src/testing/benchmark.go:539 +0x390
testing.(*M).Run(0xc0000dc000, 0x0)
        /usr/local/go/src/testing/testing.go:1205 +0x42d
main.main()
        _testmain.go:256 +0x135

goroutine 7 [runnable]:
github.com/casbin/casbin/v2/util.ArrayEquals(0xc0001d07c0, 0x2, 0x2, 0xc000997980, 0x2, 0x2, 0x40cf00)
        /home/sunforcherry/casbin/util/util.go:48 +0xde
github.com/casbin/casbin/v2/model.Model.HasPolicy(0xc000090990, 0x5f68cb, 0x1, 0x5f68cb, 0x1, 0xc0001d07c0, 0x2, 0x2, 0x0)
        /home/sunforcherry/casbin/model/policy.go:87 +0x103
github.com/casbin/casbin/v2/model.Model.AddPolicy(0xc000090990, 0x5f68cb, 0x1, 0x5f68cb, 0x1, 0xc0001d07c0, 0x2, 0x2, 0x10)
        /home/sunforcherry/casbin/model/policy.go:97 +0x84
github.com/casbin/casbin/v2.(*Enforcer).addPolicy(0xc0000ce000, 0x5f68cb, 0x1, 0x5f68cb, 0x1, 0xc0001d07c0, 0x2, 0x2, 0x0, 0x4cd404, ...)
        /home/sunforcherry/casbin/internal_api.go:25 +0x8e
github.com/casbin/casbin/v2.(*Enforcer).AddNamedGroupingPolicy(0xc0000ce000, 0x5f68cb, 0x1, 0xc000111ed0, 0x2, 0x2, 0xa, 0x0, 0x0)
        /home/sunforcherry/casbin/management_api.go:239 +0x155
github.com/casbin/casbin/v2.(*Enforcer).AddGroupingPolicy(...)
        /home/sunforcherry/casbin/management_api.go:215
github.com/casbin/casbin/v2.BenchmarkRBACModelLarge(0xc0000ee1c0)
        /home/sunforcherry/casbin/model_b_test.go:106 +0x4b4
testing.(*B).runN(0xc0000ee1c0, 0x1)
        /usr/local/go/src/testing/benchmark.go:191 +0xe8
testing.(*B).run1.func1(0xc0000ee1c0)
        /usr/local/go/src/testing/benchmark.go:231 +0x57
created by testing.(*B).run1
        /usr/local/go/src/testing/benchmark.go:224 +0x7d

rax    0xca
rbx    0x781160
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x7812a8
rsi    0x80
rbp    0x7ffcb1c7e0f0
rsp    0x7ffcb1c7e0a8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x3
r13    0x780c00
r14    0x0
r15    0x0
rip    0x4684a1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (11m0s).
exit status 2
        return s
FAIL    github.com/casbin/casbin/v2     660.009s
```

**Comment by GopherJ** [comment]
@nodece @UnderTreeTech  I think in benchmark we should use batch operation to AddPilicy. Like AddPolicies, this way we avoid having too much HasPolicy check

**Comment by UnderTreeTech** [comment]
> @nodece @UnderTreeTech I think in benchmark we should use batch operation to AddPilicy. Like AddPolicies, this way we avoid having too much HasPolicy check.
> 
> Can someone adjust bench code?

I don't think it can take positive effective by calling AddPolicies, cause it check HasPolicy too.
```
// AddPolicies adds policy rules to the model.
func (model Model) AddPolicies(sec string, ptype string, rules [][]string) bool {
	for i := 0 ; i < len(rules) ; i++{
		if model.HasPolicy(sec, ptype, rules[i]) {
			return false
		}
	}

	for i := 0 ; i < len(rules) ; i++{
		model[sec][ptype].Policy = append(model[sec][ptype].Policy, rules[i])
	}
	return true
}
```

**Comment by nodece** [comment]
go-benchmark is working in `go version go1.14.1 darwin/amd64`.

Build role links is the main factor affecting performance, so we need to build role links via incrementally way to improve performance.

**Comment by GopherJ** [comment]
@UnderTreeTech addPolicy will cause

O((n-1)(n-2)(n-3)……

**Comment by GopherJ** [comment]
@nodece  I also realized there is a bug in:

```go
for i := 0 ; i < len(rules) ; i++{
		if model.HasPolicy(sec, ptype, rules[i]) {
			return false
		}
	}
```

because it cannot prevent dup inside `rules`

**Comment by nodece** [comment]
Let's improve `AddPolicies` and `RemovePolicies`.

**Comment by UnderTreeTech** [comment]
> @nodece I also realized there is an improvement which can be done in:
> 
> ```go
> for i := 0 ; i < len(rules) ; i++{
> 		if model.HasPolicy(sec, ptype, rules[i]) {
> 			return false
> 		}
> 	}
> ```
> 
> because it cannot prevent dup inside `rules` but not critical, often users will not have two same policies to add....

Yes, we only add or delete P or G policy in my scenario, and i think is common scenario.

**Comment by UnderTreeTech** [comment]
> Let's improve `AddPolicies` and `RemovePolicies`.

Why field `model[sec][ptype].Policy` Policy doesn't use map? Thus it can be overrided even user add dup policy, and leads to average O(1), worst O(n).

```
// AddPolicy adds a policy rule to the model.
func (model Model) AddPolicy(sec string, ptype string, rule []string) bool {
	if !model.HasPolicy(sec, ptype, rule) {
		model[sec][ptype].Policy = append(model[sec][ptype].Policy, rule)
		return true
	}
	return false
}
```

**Comment by GopherJ** [comment]
> Why field model[sec][ptype].Policy Policy doesn't use map? Thus it can be overrided even user add dup policy, and leads to average O(1), worst O(n).

Not sure golang supports `HashSet` or `IndexSet` stuff on vector, @nodece if it's not supported, can we switch to `HashMap` to have `O(1)`?

**Comment by UnderTreeTech** [comment]
> > Why field model[sec][ptype].Policy Policy doesn't use map? Thus it can be overrided even user add dup policy, and leads to average O(1), worst O(n).
> 
> Not sure if golang supports `HashSet` or `IndexSet` stuff on vector, @nodece @DivyPatel9881 if it's not supported, can we switch to `HashMap` to achieve `O(1)`?
> 
> Ref: https://github.com/casbin/casbin-rs/blob/598a9bd00300ba6f74fefc7387790985dc42930f/src/model/assertion.rs#L21

Looking forward to your improvements. Pls keep me posted when it done.

**Comment by UnderTreeTech** [comment]
@GopherJ @nodece update my test result, 500k P Policy and 10K G policy, 38ms per enforce.
It seems BuildRoleLinks doesn't count for the performance issue but  add policy.
```
 go test -v -cpu=2 -run=TestRBACModelLarge -timeout=2h
2020/05/11 17:52:11 start watch filepath: ../../test
=== RUN   TestRBACModelLarge
start add policy 2020-05-11 17:52:11.539454 +0800 CST m=+0.532073604
add policy time 31m55.33670682s
build role links time 31m55.345702094s
enforce time 31m55.729227035s
--- PASS: TestRBACModelLarge (1915.73s)
PASS
ok  	damocles/internal/service	1916.298s
```

**Comment by GopherJ** [comment]
@UnderTreeTech  This bench is not valid because you are putting everything inside a bench function, to fix you just need to use `AddPolicies`, and then bench only `Enforce`

**Comment by UnderTreeTech** [comment]
> @UnderTreeTech This bench is not valid because you are putting everything inside a bench function, to fix you just need to use `AddPolicies`, and then bench only `Enforce`.
> 
> AddPolicy is slow in your case because model's policy is keep growing and every time when a new policy need to be added, it'll iterate the whole policy list for checking => **This will be fixed soon**
> 
> Also `AddPolicies` will rebuild role links only once but in your bench code, you are calling `AddPolicy` so every time when a policy has been added, it'll rebuild all the role links => this is false:) I haven't pay attention to your code

Update test result: 1.66s per enforce. 1000k P and 100k G. am i right now?
```
go test -v -cpu=2 -run=TestRBACModelLarge -timeout=2h
2020/05/11 19:36:48 start watch filepath: ../../test
=== RUN   TestRBACModelLarge
start add policy 2020-05-11 19:36:48.4997 +0800 CST m=+0.521925780
enforce time 1.669579221s
--- PASS: TestRBACModelLarge (1.67s)
PASS
ok  	damocles/internal/service	2.238s
```

Update code snippets.
```
func TestRBACModelLarge(t *testing.T) {
	e, _ := casbin.NewEnforcer("rbac_model.conf")
	// Do not rebuild the role inheritance relations for every AddGroupingPolicy() call.
	e.EnableAutoBuildRoleLinks(false)

	now := time.Now()
	fmt.Println("start add policy", now)

	// 10000 roles, 1000 resources.
	pPolicies := make([][]string, 0)
	for i := 0; i < 1000000; i++ {
		pPolicies = append(pPolicies, []string{fmt.Sprintf("group%d", i), fmt.Sprintf("data%d", i/10), "read"})
	}
	e.AddPolicies(pPolicies)

	// 100000 users.
	gPolicies := make([][]string, 0)
	for i := 0; i < 100000; i++ {
		gPolicies = append(gPolicies, []string{fmt.Sprintf("user%d", i), fmt.Sprintf("group%d", i/10)})
	}
	e.AddGroupingPolicies(gPolicies)

	e.Enforce("user50001", "data1500", "read")

	fmt.Println("enforce time", time.Since(now))
}
```

**Comment by GopherJ** [comment]
@UnderTreeTech You forgot to build role links

**Comment by UnderTreeTech** [comment]
> @UnderTreeTech You forgot to build role links

@GopherJ After build role links, 1.06621303s per enforce. Waiting for your improvements.

**Comment by GopherJ** [comment]
@UnderTreeTech  I believe 1 second is already not bad no? In casbin-rs it took 3.6 seconds. With https://github.com/casbin/casbin/issues/439 the bench of enforcing can be even better.

Let's say 500ms for 1000k + 100k.

**Comment by nodece** [comment]
> > Why field model[sec][ptype].Policy Policy doesn't use map? Thus it can be overrided even user add dup policy, and leads to average O(1), worst O(n).
> 
> Not sure if golang supports `HashSet` or `IndexSet` stuff on vector, @nodece @DivyPatel9881 if it's not supported, can we switch to `HashMap` to achieve `O(1)`?
> 
> Ref: https://github.com/casbin/casbin-rs/blob/598a9bd00300ba6f74fefc7387790985dc42930f/src/model/assertion.rs#L21

Golang doesn't supports `HashSet` or `IndexSet`. Golang supports `HashMap`, but slice cannot as map key.

**Comment by UnderTreeTech** [comment]
@GopherJ @nodece Yes, go don't support slice as map key. We can hash every single element in model[sec][ptype].Policy as the key, just like as:
```
type Assertion struct {
	Key    string
	Value  string
	Tokens []string
	Policy map[string][]string
	RM     rbac.RoleManager
}

Assertion.Policy := make(map[string][]string)
Aseertion.Policyp[hash(rule)] = []string{}
```
If we can use the map data struct, i do believe per enforce can get extraordinary performance improvement. Thus casbin can really set as an infrastructure authentication component in any scenario.

**Comment by nodece** [comment]
@UnderTreeTech Sounds good. Let me improve the Policy.

**Comment by GopherJ** [comment]
@UnderTreeTech  Just to make it clear, bench of  `enforcing` will not change using this, the only thing it improves is: `AddPolicy` and `AddPolicies` speed maybe

**Comment by UnderTreeTech** [comment]
> @UnderTreeTech Just to make it clear, bench of `enforcing` will not change using this, the only thing it improves is: `AddPolicy` and `AddPolicies` speed maybe

okay，i've already send a PR to adjust the policy initialize way in bench case. 
I wanna confirm that whether you'll replace slice by map in struct Assertion or not? if is sure, what's the plan and which version will release this feature? Actually my application is a large saas service, we really have millions of polices.

**Comment by nodece** [comment]
I thought about it yesterday. I found https://github.com/casbin/casbin/issues/439 is a good way to improve performance.  There is no concept of index in Casbin, so convert map to slice will not greatly improve. But it's a good idea in future.

**Comment by GopherJ** [comment]
@UnderTreeTech 

> okay，i've already send a PR to adjust the policy initialize way in bench case.
I wanna confirm that whether you'll replace slice by map in struct Assertion or not? if is sure, what's the plan and which version will release this feature? Actually my application is a large saas service, we really have millions of polices. We can't pay it if every enforce takes 1s.

1 million ~ 1second to me is not so slow, I'll try to find other ways to improve bench like using multi-cores in this case. 

If you see the enforce code you'll find there isn't that much space for improving bench but certainly we will try

**Comment by hsluoyz** [comment]
We can write a mapping function to map a policy slice into a string. The easiest way is to use the CSV format: `p, alice, data1, read` as the string.

Then use this string as hash key. We can create and maintain a map struct besides the policy slice array. This map will add and remove key together with policy add and remove.

Who can implement this?

**Comment by nodece** [comment]
> We can write a mapping function to map a policy slice into a string. The easiest way is to use the CSV format: `p, alice, data1, read` as the string.
> 
> Then use this string as hash key. We can create and maintain a map struct besides the policy slice array. This map will add and remove key together with policy add and remove.
> 
> Does this idea sound good? If yes, who can implement this?

The feature can only improve add/remove policy performance.

**Comment by UnderTreeTech** [comment]
> > We can write a mapping function to map a policy slice into a string. The easiest way is to use the CSV format: `p, alice, data1, read` as the string.
> > Then use this string as hash key. We can create and maintain a map struct besides the policy slice array. This map will add and remove key together with policy add and remove.
> > Does this idea sound good? If yes, who can implement this?
> 
> The feature can only improve add/remove policy performance.

I don't understand why the draft implementation @hsluoyz mentioned couldn't improve enforce performance, could you explain it, thanks a ton.

**Comment by GopherJ** [comment]
@UnderTreeTech

Enforce => **use** policies and request to check if certain user has the right to do something
Policy Management => add/remove policies

`Policy Management`'s changes will not influence `Enforce` speed, you'll just feel quicker when you try to add/remove policy, but `Enforce` will still have the same speed

**Comment by nodece** [comment]
@UnderTreeTech The #439 can improve the enforce performance at the moment.

**Comment by UnderTreeTech** [comment]
> @UnderTreeTech The #439 can improve the enforce performance at the moment.

which go casbin version will implement this feature?

**Comment by nodece** [comment]
If no one implement the feature, I will implement it tomorrow.

The feature will greatly improve the enforce.

Klaus <notifications@github.com>于2020年5月16日 周六00:55写道：

**Comment by hsluoyz** [comment]
@nodece is this feature completed?

**Comment by GopherJ** [comment]
@nodece merge_effect's quick return is missing

**Comment by nodece** [comment]
I don't know that current progress.   Ping @DivyPatel9881 .

**Comment by UnderTreeTech** [comment]
Any updates?
Looking forward to switching to O(1) for inserting/removing policy.

**Comment by hsluoyz** [comment]
@UnderTreeTech see: https://github.com/casbin/casbin/pull/500
