### ISSUE TITLE
字段控制

### ISSUE THREAD

**Issue by bugstark** [casbin/casbin#46]
您好，非常感谢您提供此扩展，节省了我非常多的时间
在使用中我遇到这样的问题，场景如下：
我们使用restful的模式，如有一个users资源，含id,name,pass,wechat字段，我们想要强制用户不能GET->pass，同时允许PUT->WeChat
请问有办法实现吗？

**Comment by hsluoyz** [comment]
可以的，定义请求：
r = sub, obj, act
其中obj表示资源类型，可以为id,name,pass,wechat
act就是GET或者PUT

策略规则就可以这样写：
p, user, wechat, PUT, allow
p, user, pass, GET, deny

然后模型参考deny-override: https://github.com/casbin/casbin#examples

**Comment by bugstark** [comment]
我想在RESTful模式下新增一个类型就像字段的白名单
policy表现为:
p admin /api/articles   GET  (id)|(name)|(wechat)
请问这种方案能实现吗？

**Comment by hsluoyz** [comment]
可以修改r和p来增加新的字段，比如：
r = sub, obj, act, type
然后Enforce()函数把"id"或者"name"或者"wechat"传入进去
策略定义就是：
p = sub, obj, act, type

看到你使用了类似正则的匹配：(id)|(name)|(wechat)
所以matcher可以这样写：
m = regexMatch(r.type, p.type)

**Comment by bugstark** [comment]
非常感谢解答，我尝试一下，再次感谢开源此优秀项目
