### ISSUE TITLE
RABC with domain and resource

### ISSUE THREAD

**Issue by foxluqi** [casbin/casbin#462]
I have the policy as below 
```
p, admin, business1, url1, POST
p, admin, business2, url2, POST
g, alex, admin, business1
g, alex, user, business2
```
How to setup model to let below request success?
```go
e.Enforce("alex","*","url1","POST")
```
I have try to write custom match function for g. But it does not work as expect.
```go
e.GetRoleManager().(*defaultrolemanager.RoleManager).AddMatchingFunc("CusMatch", CusMatch)

func CusMatch(key1 string, key2 string) bool {
	i := strings.Index(key1, "*")
	if i == -1 {
		return key1 == key2
	}
	return strings.HasSuffix(key2, key1[i+1:])
}
```

**Comment by GopherJ** [comment]
@foxluqi Why are you putting `*` in request, it looks strange to me

**Comment by foxluqi** [comment]
@GopherJ I putting * in request is because I have no idea which domain has the right on object at that point.

**Comment by hsluoyz** [comment]
A request should not contain *.
