### ISSUE TITLE
Get implicit permissions with resource group

### ISSUE THREAD

**Issue by enix223** [casbin/casbin#471]
Thank you for such awesome project first.

I am building a system with RBAC and resource group as below, user associates with roles, and resource belongs to group.

## model.conf
```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && r.act == p.act
```

## policy.csv
```csv
p, data_group_admin, data_group, write

g, alice, data_group_admin
g2, data1, data_group
g2, data2, data_group
```

## program
```go
func TestAliceResources(t *testing.T) {
	e, err := casbin.NewEnforcer("./model.conf", "./policy.csv")
	if err != nil {
		log.Print(err)
		return
	}

	perms, err := e.GetImplicitPermissionsForUser("alice")
	assert.Equal(t, [][]string{
		{"data_group_admin", "data1", "write"},
		{"data_group_admin", "data2", "write"},
	}, perms)
}
```

however, the API return the resource group only
```
expected: [][]string{[]string{"data_group_admin", "data1", "write"}, []string{"data_group_admin", "data2", "write"}}
actual  : [][]string{[]string{"data_group_admin", "data_group", "write"}}
```

So, how can I retrieve the resources list instead of resource group?

**Comment by nodece** [comment]
Hi , @hsluoyz , What do you think?

**Comment by hsluoyz** [comment]
@enix223 you can call `GetUsersForRole()` on `data_group` to get `data1` and `data2`.

**Comment by enix223** [comment]
Thanks for your quickly response.

Yes, this solve my problem. However, it doesn't look very neat, is it possible the enforcer API handle this situation internally?

**Comment by hsluoyz** [comment]
Any thought about how to provide such an API? @nodece @GopherJ @DivyPatel9881 @kingiw @dovics

**Comment by GopherJ** [comment]
basically as the name of `GetImplicitPermissionsForUser` says it will just fetch `p` policies. It won't generate new `policies` based on indirect role links.

If we would like to have a new API, we shouldn't adjust this one

**Comment by enix223** [comment]
ok, that's fine, still hoping a new API to support this.
