### ISSUE TITLE
ABAC with different object types

### ISSUE THREAD

**Issue by sagikazarmark** [casbin/casbin#48]
Unfortunatelly I still don't quite understand casbin's model, but doing my best.

Due to the questions in #45 (and partly because of my model) I decided to go with ABAC based access control which checks my object's attributes and tries to decide whether the subject can do the action or not. Unfortunately ABAC does not seem to be the primary use case with casbin. It's a bit underdocumented IMO.

So here is a case which I don't know how to solve: I have multiple entities, multiple actions and I would like to decide which users can what. These entities have several attributes that I want to use.

Let's take a simple example: there are entities which have Owner and Collaborator attributes. Obviously Owners can delete, collaborators can edit. These entities belong to Groups where we have the same actors: Owners and Collaborators. The rule is the same except now we have a create action as well, which only owners can do.

How would I model this in casbin with ABAC? Do I have to create multiple casbin instances? (There are only two entites here, but in large scale there could be much more in which case separate casbin instances could be a huge bottleneck.)

Maybe it can also be interesting that Owners are available as an attribute, Collaborators can be fetched using a method.

I'm not asking you to solve my problem, this is actually only a dummy example, but I can't seem to understand how casbin works.

Thanks a lot!

**Comment by sagikazarmark** [comment]
My idea is creating a matcher function which can handle multiple types. Or even better a matcher that accepts multiple matchers and decides which should be called.

**Comment by hsluoyz** [comment]
Your user case is like a GitHub/GitLab scenario. At least I can think of a very simple solution as below.

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = role, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = getRole(r.sub, r.obj) == p.role && regexMatch(r.act, p.act)
```

```csv
owner, (delete)|(edit)
collaborator, edit 
```

``getRole()`` is a function that can retrieve the highest role the user has for the entity. But maybe you think ``getRole()`` has hidden too many details and Casbin doesn't do very much work. We can improve it by letting Casbin participate more. But first I want to ask what kinds of information do you want Casbin to store? You mentioned that entities can have groups. I think it's like a GitHub repository can have an organization it belongs to? So the ``repo`` has the role ``organ``. Do you want this mapping to be stored in Casbin rules? Can this mapping be hierarchical? If you do not want to store this mapping, then there won't be many rules in Casbin.

**Comment by sagikazarmark** [comment]
Yeah, Github is a perfect example. (As I said the example above is not really my case, but share the common points. In my case there are more attributes to consider, more complex rules) I think it would be great if there was an example of managing access on a site like Github with casbin.

No, I don't really want Casbin to store roles. Most of my cases are not list based access controls, but attribute based using some kind of complex logic to decide whether the user can access a resource or not.

So what I really want is a way to easily evaluate these rules within Casbin to a decision whether a subject can do the action on the object or not. Ultimately I don't want to know in my consumer code whether the decision is made based on a list or attributes. I just want to call casbin ask if I can do something or not.

Actually I really like the idea of mapping these rules to a short list of roles (owner, collaborator, none (?)) This might actually be the solution to my problem (and to this kind of problem in general. I don't have too much experience in access control, so this might be trivial to others though.)

I will try to play with it and get back with the result. Thanks a lot!

**Comment by jmwohl** [comment]
@sagikazarmark @hsluoyz I'm very curious where you landed with this, as this seems like a super common use case for authz. There are several issue threads like this one that have good leads, but I'm yet to find a concrete implementation example that has this type of dynamic user/entity role mapping. I'm certain I can figure out a solution that will work for our use case, but interested in how others have solved this with Casbin.

**Comment by sagikazarmark** [comment]
I ended up using the solution suggested by @hsluoyz , but to be honest, I used in a simple scenario, but never explored the solution any further.

**Comment by M-Razavi** [comment]
How it works if a user has multiple roles?

**Comment by hsluoyz** [comment]
@M-Razavi , but you will only have one role for a single domain/tenant.

**Comment by chrisui** [comment]
Appreciate this issue is long stale now but wanted to weigh in incase any contributors/maintainers spot this and say how valuable a guide/set of examples around this kind of usage would be to the community. Ie. These are the "complex" _real-world_ use cases myself and others come looking to solutions like casbin to solve.
