### ISSUE TITLE
In memory (,read only?) policy adapter

### ISSUE THREAD

**Issue by sagikazarmark** [casbin/casbin#49]
Is there an inmemory implementation of the policy adapter which I can fill manually? I would prefer not using files to store that 4 or 5 roles I'm just about to create.

**Comment by sagikazarmark** [comment]
Or maybe I can just use `persist.LoadPolicyLine`?

**Comment by hsluoyz** [comment]
You can leave empty in the 2nd parameter of NewEnforcer call, then add your policy and roles with the API, either management API or RBAC API.

**Comment by sagikazarmark** [comment]
Great, thanks!
