### ISSUE TITLE
Return multiple matched results?

### ISSUE THREAD

**Issue by Despire** [casbin/casbin#492]
Is there a way I could retrieve all the matches result from the Enforce method? Currently it returns only the [first matched result](https://github.com/casbin/casbin/blob/master/enforcer.go#L520-L529).

https://github.com/casbin/casbin/blob/c6a4ba2082f33e9e3e494151bd95e0e3b183a3fc/enforcer.go#L520-L529

The reason I need all the matched results is the following:
I have something called a scope which can be either 
`Account` - the user can see only things related to his account
or
 `Global` - the user can see everything
(I set the scope based on some attributes..)

And the problem arises when I would set 2 different roles for a user with these scopes for the same resource, that is one role would have `Account` and the other would have `Global`. And since casbin returns the first matched it's not deterministic and it really depends on the order of the policies in the database.
And to solve this I would like to access all the matched result and choose the most generic scope..  (for this example it would be `Global`..)

**Comment by hsluoyz** [comment]
@nodece @dovics

**Comment by nodece** [comment]
Hi @Despire, Casbin should support the feature, but  when casbin found use has certain policy, It will break check.  

You can checkout https://github.com/casbin/casbin/blob/master/effect/default_effector.go.

**Comment by Despire** [comment]
Hi
yes it will break the check. So maybe a different method could be used for that case ?

for example it could look something like this

```go
  
   if someCondition... {
	result, explainIndex, err = e.eft.MergeEffects(e.model["e"]["e"].Value, policyEffects, matcherResults)
	if err != nil {
		return false, err
	}

	if explains != nil {
		if explainIndex != -1 {
			*explains = e.model["p"]["p"].Policy[explainIndex]
		}
	}
   } else {
       matched, err = e.eft.Effects(e.model["e"]["e"].Value, policyEffects, matcherResults)
       if err != nil {
           return false, err
       }
       if len(matched) != 0 {
           result = true
       }
         .....
   }
         ......
```

**Comment by nodece** [comment]
Your idea is very good. Actually, there's only one hit policy.

**Comment by dovics** [comment]
Hi @Despire  Your needs are so special that I don't think many people need it, 

I provide a solution for your needs,  You can write an effort like this
```
func (e *Effector) MergeEffects(expr string, effects []Effect, results []float64) (bool, int, error) {
    e.ch <- effects
    return true, -1, nil
}
```
casbin provide  `SetEffect()` to set youself Effect, You can receive what you want in the channel, 

```
e.SetEffect(effect)
go e.Enforce("alice", "data1", "read")

select {
    case result :=<- effect.ch:
    default:
}
```

**Comment by Despire** [comment]
@dovics Hi, yes I already thought about a custom Effector, 
The issue with that though is that when I receive multiple HTTP request at the same time, and they are use the same SyncedEnforcer they will all use the same channel and the result would be undefined

**Comment by dovics** [comment]
There seems to be no better way than locking, but this will degrade performance. Maybe you can try multiple casbin instances. I know none of these solutions are good, but if the Casbin wants to support https://github.com/casbin/casbin/issues/439, it seems difficult to implement your requirement.

**Comment by Despire** [comment]
I totally agree with that you prefer performance and that most of the times you just need a single hit match.

But there also may be cases where the business logic requires to compare all the matches, (in my case it's the scope I mentioned), even though these are less likely to occur.

One possibility would be to implement one Enforce that would just match a single hit and you could implement #439 for it. And one Enforce for all matches (this wouldn't a big performance hit since it would just traverse the list which is O(N)). Although I think this would bring some duplicity into the codebase 

Anyways If you decide to not implement this feature just let me know By closing this issue and I'll try to find some other way.

**Comment by nodece** [comment]
@Despire Thank you for your understand.
