### ISSUE TITLE
user data management

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin#498]
I'm wondering if we can add custom `data` for RBAC. Sometimes we would like to add custom data for specific user. Or let childrent inherit parent's data (if the data is public)

**Comment by GopherJ** [comment]
Finally I think it's maybe not a good idea to have this because the persistence will be a problem, it's similar to `policy` but just for specific usage.

A workaround is to use: `p2` and use `named` function to fetch them

**Comment by hsluoyz** [comment]
@nodece @dovics
