### ISSUE TITLE
how to set casbin conf if I want to use rabc with resource roles at the same time match the restful api

### ISSUE THREAD

**Issue by msean** [casbin/casbin#501]
I use the casbin with rabc with resource model, this is my conf
```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) &&（r.act == p.act)
```
this is the policy:
```csv
p, Leader, ResGroup1, read
g2, /api/:id, ResGroup1
```
but it can not match the request:
```
Leader, /api/1, read
Leader, /api/2, read
```
if I want to match the /api/:id restful api, how to set the model conf?

this is the go test code
```go
package test

import (
	"fmt"
	"testing"

	"github.com/byronzr/micro/helper"
	"github.com/casbin/casbin/util"
	"github.com/casbin/casbin/v2"
	"github.com/casbin/casbin/v2/model"
	defaultrolemanager "github.com/casbin/casbin/v2/rbac/default-role-manager"
	gormadapter "github.com/casbin/gorm-adapter/v2"
)

var newTestRABCRes = func(adpter string) *casbin.Enforcer {
	adapter, err := gormadapter.NewAdapter("mysql", adpter, true)
	m := model.NewModel()

	m.AddDef("r", "r", "sub, obj, act") // role
	m.AddDef("p", "p", "sub, obj, act")
	m.AddDef("g", "g", "_, _")
	m.AddDef("g", "g2", "_, _")
	m.AddDef("e", "e", "some(where (p.eft == allow))")

	m.AddDef("m", "m", `(r.sub == "admin") || (g(r.sub, p.sub)  && g2(r.obj, p.obj)   && (r.act == p.act || p.act == "*" ))`)

	rm := defaultrolemanager.NewRoleManager(10)
	rm.(*defaultrolemanager.RoleManager).AddMatchingFunc("g2", util.KeyMatch2)
	m.BuildRoleLinks(rm)

	cas, err := casbin.NewEnforcer(m, adapter)
	cas.EnableAutoSave(true)
	cas.ClearPolicy()
	if err != nil {
		helper.Err("casErr", err)
	}
	return cas
}

func Test_RABCWithResource(testcase *testing.T) {

	cas := newTestRABCRes(fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?charset=utf8mb4", "root", "123456", "localhost", "3307", "os"))

	cas.AddNamedGroupingPolicy("g2", "api/:id", "ResGroup1")
	cas.AddPolicy(`Leader`, `ResGroup1`, "read")
	testcase.Log(cas.Enforce("Leader", "api/1", "read"))
}


```

**Comment by GopherJ** [comment]
@msean your code looks good to me, but I didn't find where have you added the following policies:

```
p, Leader, ResGroup1, read
g2, /api/:id, ResGroup1
```

You have executed `ClearPolicy` and then you just called:

```
cas.AddNamedGroupingPolicy("g2", "api/1", "ResGroup1")
	cas.AddPolicy(`Leader`, `ResGroup1`, "read")
```

**Comment by GopherJ** [comment]
BTW @dovics @nodece  do you think that we should remove the `name` parameter of `MatchingFunc`, It's not useful to me and it causes confusion like here:

@msean called:

```
rm.(*defaultrolemanager.RoleManager).AddMatchingFunc("g2", util.KeyMatch2)
```
but `"g2"` has no sense

**Comment by msean** [comment]
It's my fault edit
```json
cas.AddNamedGroupingPolicy("g2", "api/:id", "ResGroup1")
```
now, I  correct the code

**Comment by dovics** [comment]
hi @msean @GopherJ  I think this is a bug. Casbin does not use the rolemanager in the model when creating the enforce, please see https://github.com/casbin/casbin/blob/master/enforcer.go#L168, so if we call `AddNamedGroupingPolicy`, the rolemanager in enforcer will replace the one in model through `BuildIncrementalRoleLinks()`

Currently I have no idea to fix it, so I suggest you call 
```
cas.GetRoleManager().(*defaultrolemanager.RoleManager).AddMatchingFunc("g2", util.KeyMatch2)
```

**Comment by GopherJ** [comment]
Ok I see, let's do this:

```go
cas.GetRoleManager().(*defaultrolemanager.RoleManager).AddMatchingFunc("g2", util.KeyMatch2)
```

**Comment by dovics** [comment]
@GopherJ I totally agree with you, I moved the `RoleManager` to `Model`, Please review

**Comment by msean** [comment]
There is an other question for help:
```code
package test

import (
	"fmt"
	"log"
	"testing"

	"github.com/casbin/casbin/util"
	"github.com/casbin/casbin/v2"
	"github.com/casbin/casbin/v2/model"
	defaultrolemanager "github.com/casbin/casbin/v2/rbac/default-role-manager"
	gormadapter "github.com/casbin/gorm-adapter/v2"
)

var newTestRABCRes = func(adpter string) *casbin.Enforcer {
	adapter, err := gormadapter.NewAdapter("mysql", adpter, true)
	m := model.NewModel()

	m.AddDef("r", "r", "sub, obj, act") // role
	m.AddDef("p", "p", "sub, obj, act")
	m.AddDef("g", "g", "_, _")
	m.AddDef("g", "g2", "_, _")
	m.AddDef("e", "e", "some(where (p.eft == allow))")

	m.AddDef("m", "m", `(r.sub == "admin") || (g(r.sub, p.sub)  && g2(r.obj, p.obj)   && (r.act == p.act || p.act == "*" ))`)

	cas, err := casbin.NewEnforcer(m, adapter)
	cas.GetRoleManager().(*defaultrolemanager.RoleManager).AddMatchingFunc("g2", util.KeyMatch2)
	cas.EnableAutoSave(true)
	if err != nil {
		log.Println("casErr", err)
	}
	return cas
}

func Test_RABCWithResource(testcase *testing.T) {

	cas := newTestRABCRes(fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?charset=utf8mb4", "root", "123456", "localhost", "3307", "os"))

	cas.AddNamedGroupingPolicy("g2", "api/:id", "read", "ResGroup1")
	cas.AddPolicy(`Leader`, `ResGroup1`, "read")
	testcase.Log(cas.Enforce("Leader", "api/1", "read"))
	testcase.Log(cas.Enforce("Leader", "api/1", "write"))
}
```
My expectation is: 
```
true, false
```

**Comment by dovics** [comment]
@msean Casbin don't support setting act in g2, `g` is used to handle inheritance relationship

In fact, your original policy has been able to meet your expectation if don't have`p, Leader, ResGroup1, write`, You maybe want this
```
p, Leader, ResReadGroup1, read
p, Leader, ResWriteGroup1, write
g2, ResGroup1, ResReadGroup1
g2, ResGroup1, ResWriteGroup1
g2, /api/:id, ResReadGroup1
```

**Comment by msean** [comment]
If I want to add two resource into  g2:
```code
p, Leader, ResReadGroup1, read
p, Leader, ResWriteGroup1, write
g2, ResGroup1, ResReadGroup1
g2, ResGroup1, ResWriteGroup1
g2, /api/:id, ResReadGroup1
g2, /api/v2/:id, ResReadGroup1
```
and I just want to  set /api/v2/:id only read access, so it can not to set /api/:id and /api/v2/:id to a group?

**Comment by GopherJ** [comment]
you have put two _ for g2，then your g2 function will only accept two parameters

**Comment by msean** [comment]
@GopherJ if I put three _ for g2,  
The third _ can be regarded as act? 
How to set model conf?

**Comment by GopherJ** [comment]
@msean the third argument is `domain` it's for puting tings in different domain, if you need another group for `act`, I think you can use `g3` with two `_`

**Comment by hsluoyz** [comment]
Hi @msean we have the `SetRoleManager()` API. So after you created your own role manager. You should call it to attach it to the enforcer. See this example:

https://github.com/casbin/casbin/blob/6f8386053d230fdf554aadca6339fd214a374e6c/model_test.go#L352-L366

@GopherJ @dovics if the above way works, we have no reason to modify the model. In the initial design, model is just supposed to handle the model text parsing and the attached policy rules. Role manager is at the same layer of model, both attached to an enforcer.

**Comment by GopherJ** [comment]
@hsluoyz  We don't need role manager in the root level I believe.  Because a role manager is attached to a Policy/Assertion.

**Comment by hsluoyz** [comment]
The most important API for a role manager (https://github.com/casbin/casbin/blob/master/rbac/role_manager.go) is `HasLink()`. And it is only used when an enforcer is executing the g(_, _) function in the matcher, which is defined in a model. So we can see it is the enforcer that integrates all parts (model, adapter, role manager) together. Purely binding a role manager to a model doesn't make much sense to me.

**Comment by hsluoyz** [comment]
Closed as resolved.
