### ISSUE TITLE
Bytes instead path to model file

### ISSUE THREAD

**Issue by tpoxa** [casbin/casbin#503]
I am willing to deliver my app as a single binary file. I use go-bindata to bind static files into go code.
Is there any way to provide casbin bytes instead of a file path?

Thanks.

**Comment by hsluoyz** [comment]
@tpoxa model can be loaded via code or string: https://casbin.org/docs/en/model-storage#load-model-from-code . Policy can also be added/removed via code (mgmt API and RBAC API). Is this what you want?

**Comment by nodece** [comment]
You should need the code:

```golang
func InitEnforcer() {
	model, err := model.NewModelFromString(`
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && r.obj == p.obj && r.act == p.act
	`)
	if err != nil {
		// do somethings
	}

	// This is built in file adapter. You can also implement own adapter.
	adapter := fileadapter.NewAdapter("examples/basic_policy.csv")
	e, err := NewEnforcer(model, adapter)
	if err != nil {
		// do somethings
	}
}
```

**Comment by tpoxa** [comment]
Thank you @nodece  I think I just need to update my casbin.
