### ISSUE TITLE
[QUESTION] what's the difference of `Enforcer` and `SyncedEnforcer` if by default we have locks in every struct with map?

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin#504]
I'm confused while seeing `Lock` in every struct with `map. I'm wondering if it's correct and ncessary?

It's not necessary for `Enforcer` because normal `Enforcer` is not thread-safe.

For syncedEnforcer we can have multiple goroutines reading/writing, we already have a top-level mutex, why do we still need other mutex/lock?

Any idea?

**Comment by GopherJ** [comment]
In go, we can use `go test -race` for testing, have we tested what happens if we remove `child locks`?

**Comment by GopherJ** [comment]
Here the locks which I think unecessary

package model

- https://github.com/casbin/casbin/blob/a5d65bea854ccfa2d9b802813bbcc9323b9e1acd/model/policy.go#L60
- https://github.com/casbin/casbin/blob/a5d65bea854ccfa2d9b802813bbcc9323b9e1acd/model/policy.go#L66
- https://github.com/casbin/casbin/blob/a5d65bea854ccfa2d9b802813bbcc9323b9e1acd/model/policy.go#L75
- https://github.com/casbin/casbin/blob/a5d65bea854ccfa2d9b802813bbcc9323b9e1acd/model/policy.go#L82
- https://github.com/casbin/casbin/blob/a5d65bea854ccfa2d9b802813bbcc9323b9e1acd/model/policy.go#L91
- https://github.com/casbin/casbin/blob/a5d65bea854ccfa2d9b802813bbcc9323b9e1acd/model/policy.go#L98
- https://github.com/casbin/casbin/blob/a5d65bea854ccfa2d9b802813bbcc9323b9e1acd/model/policy.go#L122
- https://github.com/casbin/casbin/blob/a5d65bea854ccfa2d9b802813bbcc9323b9e1acd/model/policy.go#L130
- https://github.com/casbin/casbin/blob/a5d65bea854ccfa2d9b802813bbcc9323b9e1acd/model/policy.go#L143
- https://github.com/casbin/casbin/blob/a5d65bea854ccfa2d9b802813bbcc9323b9e1acd/model/policy.go#L151
- https://github.com/casbin/casbin/blob/a5d65bea854ccfa2d9b802813bbcc9323b9e1acd/model/policy.go#L161
- https://github.com/casbin/casbin/blob/a5d65bea854ccfa2d9b802813bbcc9323b9e1acd/model/policy.go#L179
- https://github.com/casbin/casbin/blob/a5d65bea854ccfa2d9b802813bbcc9323b9e1acd/model/policy.go#L198
- https://github.com/casbin/casbin/blob/a5d65bea854ccfa2d9b802813bbcc9323b9e1acd/model/policy.go#L237

**Comment by GopherJ** [comment]
It's worth noting if we are using `global mutex` I think `sync.Map` is then unecessary for sub structs, because `sync.Map` has also mutex inside.

**Comment by GopherJ** [comment]
In role manager we are using `sync.map` but I'm not sure if it's necessary to have because its performance is worser than `Map` and we already have top-level lock in synced enforcer

https://github.com/casbin/casbin/blob/a5d65bea854ccfa2d9b802813bbcc9323b9e1acd/rbac/default-role-manager/role_manager.go#L44

**Comment by GopherJ** [comment]
I think in go by default we all want `SyncedEnforcer`, that's why these locks exists because many users may use normal enforcers in multiple threads.

**Comment by GopherJ** [comment]
So the question is:

> what's the difference of `SyncedEnforcer` and `Enforcer`? If we have added locks in so many small places, why it's necessary to add lock in top-level (SyncedEnforcer)? 

And:

> if we need thready safety for normal Enforcer, are these locks already enough?

**Comment by hsluoyz** [comment]
@nodece @dovics

**Comment by UnderTreeTech** [comment]
I have different opinion. I don't think SyncedEnforcer or the top level mutex is graceful implementation, **it should be deprecated**. In casbin policy is the core object, it includes G and P policy.  Casbin should handle the concurrent access policy scenario at the bottom which is truely transparent to adapter、enforcer or other policy operators.
I agree with config lock mutex is not necessary. User should safely initialize configures during application startup phrase, it's single thread in common scenario. 
@hsluoyz @GopherJ @nodece

**Comment by nodece** [comment]
Yep, I agree with @UnderTreeTech, Casbin should provides a threadsafe model, It is transparent for adapter、enforcer.

**Comment by nodece** [comment]
Hi @hsluoyz, @GopherJ  I think we should add v3 proposal or roadmap. 

The following is support feature in future:

- [ ] threadsafe model:  deprecated syncedEnforce.
- [ ] audit log: record  enforcer、policy changes and so on log.
- [x] quick return on enforce: #472 
- [x] Refactor RM to model: #505 

and so on

**Comment by GopherJ** [comment]
@nodece  cannot we use meilestone?

**Comment by nodece** [comment]
milestone are also is good idea, it's similar roadmap.

**Comment by UnderTreeTech** [comment]
@nodece In addition, Based on #500 CachedEnforce can be deprecated too. In most RBAC authentication scenario, user can get auth result by using GetRolesForUser and HasPermissionForUser, which authentication result is returned in microseconds.

**Comment by GopherJ** [comment]
@UnderTreeTech I don't think it should be deprecated.  CachedEnforcer is pretty useful for heavy calculations.

**Comment by GopherJ** [comment]
However I do  think current cachedEnforcer lacks of control，how can it defend DOS attack?  It can easily overflow the memory.

**Comment by UnderTreeTech** [comment]
> @UnderTreeTech I don't think it should be deprecated.  CachedEnforcer is pretty useful for heavy calculations. 
> 
> A web service often have the same request during a period. Like when users refresh pages etc. 
> 
> CachedEnforcer is also important for real time application. 
> 
> Why do you think it should be deprecated? 

In my scenario, I store user's role in G policy, userid is the key and roles is the value. At the same, P policy store role's resources in P policy, roleid+object+action is the key and it's index in the slice is the value. @dovics has implemented policy map, find element overhead is O(1), So I can get authentication result asap by using Roles And Policy apis but not enforce. 
I think this is a common way to achieve rbac using casbin, so it is reasonable to deprecate CachedEnforcer. @GopherJ

**Comment by UnderTreeTech** [comment]
> However I do think current cachedEnforcer lacks of flexibility，how can it defend DOS attack? It can easily overflow the memory.

It's not the duty for application to defend or avoid DDOS attack but Advanced Anti-DDoS Service. Application responsible for monitoring abnormal QPS, burst traffic and file warnings timely.

**Comment by GopherJ** [comment]
@UnderTreeTech 

> It's not the duty for application to defend or avoid DDOS attack but Advanced Anti-DDoS Service. Application responsible for monitoring abnormal QPS, burst traffic and file warnings timely.

I think yes and no. A basic control is necessary like the capacity of cache, use LRU,  and clear cache once policy changed etc. Now these features are lacking.

**Comment by GopherJ** [comment]
@UnderTreeTech 
> In my scenario, I store user's role in G policy, userid is the key and roles is the value. At the same, P policy store role's resources in P policy, roleid+object+action is the key and it's index in the slice is the value. @dovics has implemented policy map, find element overhead is O(1), So I can get authentication result asap by using Roles And Policy apis but not enforce.
I think this is a common way to achieve rbac using casbin, so it is reasonable to deprecate CachedEnforcer. @GopherJ

How about more complicated senario?  when there are many policies, I wouldn't want the enforcer to repeat the same work.

**Comment by UnderTreeTech** [comment]
> @UnderTreeTech
> 
> > In my scenario, I store user's role in G policy, userid is the key and roles is the value. At the same, P policy store role's resources in P policy, roleid+object+action is the key and it's index in the slice is the value. @dovics has implemented policy map, find element overhead is O(1), So I can get authentication result asap by using Roles And Policy apis but not enforce.
> > I think this is a common way to achieve rbac using casbin, so it is reasonable to deprecate CachedEnforcer. @GopherJ
> 
> How about more complicated senario? when there are many policies, I wouldn't want the enforcer to repeat the same work.

First, CachedEnforcer doesn't make great performance improvement based on policy map. Second, CachedEnforcer consumed another more memory while user must keep mind to maintain cache changes, otherwise user would get wrong authentication result. Based on the issues i don't think it's worth to use CachedEnforce while we have thread safe policy APIs.

**Comment by GopherJ** [comment]
@UnderTreeTech  so how do you use `keyMatch` and `regexMatch` or other custom functions defined by users, 

An enforce can be really heavy when there is a combination of these things, if these is no cache...I cannot image how bad the performance can be.

**Comment by nodece** [comment]
In my option, I prefer to set cache in my application instead of SyncedEnforcer.

**Comment by UnderTreeTech** [comment]
Yep, my scenario is not complicated, just standard RBAC, I only worry about  CacheEnfocer would cause authorization result is not consistent in concurrent read/write polices. That's disaster to saas applications.

**Comment by GopherJ** [comment]
@UnderTreeTech read is much more frenquently than write. If policies changes, we should clear cache.

**Comment by hsluoyz** [comment]
@GopherJ I think this PR: https://github.com/casbin/casbin/pull/500 added all the locks. Do you have a performance downgrade number? Like 20% performance dropped? If it affects much, I'm considering reverting that PR.

**Comment by GopherJ** [comment]
@hsluoyz I don't think those locks will affect that much. Normally it's quick to acquire a lock. I think we can add new PR to handle this issue instead of recerting that because it adds good feature.

Before that PR we already have many locks

**Comment by hsluoyz** [comment]
@GopherJ can you help remove the unnecessary locks?

**Comment by GopherJ** [comment]
@hsluoyz yes will try to do it

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casbin/pull/510
