### ISSUE TITLE
Enforce method for multiple roles and actions

### ISSUE THREAD

**Issue by AravinthSankar-hash** [casbin/casbin#507]
I have list of users, each user can have multiple roles (assume one have 100 roles), total of 500 roles are available, also there are multiple actions that users can perform (like create file, edit file, delete file). I’m using Casbin for authorization. Attached the sample data below.
Now consider one user logs in (he has 10 roles – role1, role2…etc.), I need to check for 5 actions that this user can access or not, to do this I’m looping the enforce method 10 * 5 times (as I have 10 roles and 5 actions),

**enforce(role, action, ‘write’);**

I want to know whether looping is the only way to check or any other better way I can handle the same.

```go
Sample data = [
    {
        "ptype":"p",
        "v0":"role1",
        "v1":"createfile",
        "v2":"write",
        "v3":"",
        "v4":"",
        "v5":""
     },
     {
        "ptype":"p",
        "v0":"role2",
        "v1":"editfile",
        "v2":"write",
        "v3":"",
        "v4":"",
        "v5":""
    },
    {
        "ptype":"p",
        "v0":"role3",
        "v1":"deletefile",
        "v2":"write",
        "v3":"",
        "v4":"",
        "v5":""
    },
    {
        "ptype":"p",
        "v0":"role4",
        "v1":"readfile",
        "v2":"read",
        "v3":"",
        "v4":"",
        "v5":""
     },
    {
       "ptype":"g",
       "v0":"aravinth",
       "v1":"role1",
       "v2":"",
       "v3":"",
       "v4":"",
       "v5":""
    },
    {
       "ptype":"g",
       "v0":"aravinth",
       "v1":"role2",
       "v2":"",
       "v3":"",
       "v4":"",
       "v5":""
    },
    {
       "ptype":"g",
       "v0":"sankar",
       "v1":"role1",
       "v2":"",
       "v3":"",
       "v4":"",
       "v5":""
    }
]
```

**Comment by GopherJ** [comment]
@AravinthSankar-hash You can use `GetImplicitRolesForUser` to check if specific user has all the roles that it should have.

You can call `GetImplicitPermissionsForUser` to check if specific user has all the actions it should have

**Comment by GopherJ** [comment]
At the same time @nodece @divy9881 @dovics maybe we can offer:

HasImplicitPermissionForUser
HasImplicitPermissionsForUser

**Comment by kowthalganesh** [comment]
@GopherJ Just a thought process to align,
HasImplicitPermissionForUser
HasImplicitPermissionsForUser

it's good and goes to find the permission user-specific, But some projects user details are confidential, if you privilege to roles too, that will make a broader scope to achieve the solutions

Example:

HasImplicitPermissionForRole
HasImplicitPermissionsForRole

**Comment by GopherJ** [comment]
@kowthalganesh casbin will not distinguish user/role. Even we have `user/role` notion in API but when comes to implementation, an user is a role, a role is an user.

**Comment by hsluoyz** [comment]
@AravinthSankar-hash call `enforce(user, action, ‘write’);`, Casbin can automatically calculate all the roles you have, you don't need to pass the roles into that function manually.

The 5 actions are also unnecessary. If you need to check 5 actions for one time, why not define it as a new action. And this new action inherits 5 actions.
