### ISSUE TITLE
setup issue-label-bot?

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin#508]
https://github.com/marketplace/issue-label-bot seems good.

Seems enhancement, question are missing. Not sure if it's a good idea then..

**Comment by hsluoyz** [comment]
Seems interesting! I'd like to see how it works for Casbin-RS first.

**Comment by GopherJ** [comment]
Tried here: https://github.com/casbin-rs/diesel-adapter/issues/43

**Comment by hsluoyz** [comment]
Done at: https://github.com/casbin/casbin-oa
