### ISSUE TITLE
(ABAC) Performance checking many unique rules?

### ISSUE THREAD

**Issue by DGollings** [casbin/casbin#511]
Hi,

Trying to get a complex set of permissions going, because of many actors and domains I got stuck implementing RBAC and am going for a more finegrained approach. It's a logistical platform, so a single shipment has a sender and receiver but also multiple other parties that can (or can't) see or interact with it. 

So I figured it would make sense to allow implementing rules for every single shipment separately. That way any possible combination of actors and access would be supported.

Here's my model

```ini
[request_definition]
r = sub, obj, act, dom, owner

[policy_definition]
p = sub_rule, obj, act, dom, owner

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = eval(p.sub_rule) && r.obj == p.obj && r.act == p.act
```

During creation of a policy the obj is set to a UUID for that shipment, dom and owner are UUIDs that are not used for policy enforcement, but for management. If I ever need to change something for one particular domain or usergroup I'd be able to find them.

So obj is completely unique. No hierarchy or other dependencies

But I'm wondering about performance, in my test database I have 55k rules. And looping over all 55k takes about 2 seconds, which means that if I check 1408 possible shipments that takes ~3000 seconds.

I hacked around a bit and found that filtering out the one rule I need for that one shipment I want to check, applying that one filter to a newly instantiated model and enforcer and then checking it was much faster. 1408 shipments takes 1.2 seconds in parallel (goroutine with unique model and enforcer) and 3.5 seconds serially

Is there a way to tell the enforcer that I want to check a rule, and I already know which rule I want it to check against?
enforcer.EnforceWithRule(rule, request) ?

In a way, what I want is very similar to a regular expression, I want to instantiate ('compile') the model once, give it a rule and request and get a boolean response. Whilst ignoring all the other possible rules which I know, by design, will never match

The current solution, although it feels hacky

```go
(...)
	allowed := []string{}
	wg := sync.WaitGroup{}
	for _, r := range requested { //1408 UUIDs
		wg.Add(1)
		func(r string) {
			defer wg.Done()
//Extract the one UUID from the column I know its in
			filter := config.Casbin.Enforcer.GetFilteredPolicy(int(ObjectID), r)
 //Instatiate a new model, due to concurrent read/write panics
			m, err := model.NewModelFromString(AbacDomainModel)
			if err != nil {
				panic(err)
			}
			oneObjectEnforcer, _ := casbin.NewEnforcer(m)
 //Create a new enforcer with a very minimal set of policies (two, for R/W)
			oneObjectEnforcer.AddPolicies(filter)

			if CustomEnforceRule(
// little helper method that does roughly:
//  rule := parseRule(permissions, objectID, action)
//  accessGranted, err = config.Casbin.Enforce(rule...)
// return accessGranted	
			) {
				allowed = append(allowed, r)
			}
		}(r)
	}
	wg.Wait()
	elapsed := time.Since(start)
	fmt.Printf("checked %d, %d allowed. Took %s total\n", len(requested), len(allowed), elapsed)

	if len(allowed) == 0 {
		return nil, fmt.Errorf("permission denied")
	}
	fmt.Println(time.Now())
	return allowed, nil
}
```

Of all the various combinations I tried, this was the fastest one. By far, but I feel it should be possible to make it even more efficient

**Comment by DGollings** [comment]
Was poking around the documentation. Would defining a 'g' for each shipment make the problem better or worse you think?

(note: I haven't read the docs for `g()`)
So prefilter using `g(r.obj, p.obj)`, then each 'group' would only have the two possible rules, Read/Write

**Comment by hsluoyz** [comment]
@nodece @GopherJ @dovics

**Comment by hsluoyz** [comment]
@DGollings sorry for late response.

First, can you try to modify your matcher to:

```ini
[matchers]
m = r.obj == p.obj && eval(p.sub_rule) && r.act == p.act
```

Casbin uses govaluate for matcher evaluation and it supports "short-circuit" feature:  https://github.com/Knetic/govaluate/issues/36. So ideally, if `r.obj == p.obj` part is true, it will never waste time in evaluating other parts.

If the above doesn't help, we should can a built-in optimization inside Casbin enforcement logic like this:

1. Find any "one-vote veto" part like `r.obj == p.obj` from the matcher in model parse/compile stage.
2. Filter all rules into a subset based on `r.obj == p.obj` explicitly in the top of `Enforce()`. To further speed up, we can even build a map with `r.obj` as the key and rules with the same value in `p.obj` as the value. So we can get those rules in O(1). But it requires us to maintain such a map for every rule update. I don't know if the benefit will win over the cost.
3. Filtered subset will finally be used for real enforcement.

**Comment by DGollings** [comment]
@hsluoyz sorry, can't try your suggestion as I had to abandon Casbin due to time constraints (trying to release version 1.0 of a new project this monday :))

I can however tell you how I fixed it for my usecase:
The problem I was having with the current Casbin implementation was answering the question:
"Casbin - here's all the shipments in the database, every single one of them, which ones does this one user have access to when comparing against every single rule you have in your model?"

Which of course is going to be slow (order of minutes), was able to improve that by implementing a form of map/reduce (earlier hack) into a second or two. But that's still brute forcing it.

Instead I added a new table to the database with two columns: id and rules
ID being a unique UUID for a unique object elsewhere in the system, say a shipment
rule being a jsonb column with an [inverted index](https://www.cockroachlabs.com/docs/stable/inverted-indexes.html)
which basically just turns a json object into tiny indexed tables

within that rule column there's stuff like (paraphrased) {"allowed_access": [_list, of, uuids_]} 

which enables the following question instead:
"Database - please give me all the shipments where table access_rules joined on (shipmentid = access_ruleid) contains this one user uuid"
which returns from all the shipments (~55k) the ones I'm looking for in 40ms instead of 1200ms

In a sense, I'm having the same issues as https://github.com/casbin/casbin/issues/101
where instead of a complex but (relatively) small hierarchy of users/roles/domains there's _many_ very simple checks

>     Find any "one-vote veto" part like r.obj == p.obj from the matcher in model parse/compile stage.
>     Filter all rules into a subset based on r.obj == p.obj explicitly in the top of Enforce(). To further speed up, we can even build a map with r.obj as the key and rules with the same value in p.obj as the value. So we can get those rules in O(1). But it requires us to maintain such a map for every rule update. I don't know if the benefit will win over the cost.
>     Filtered subset will finally be used for real enforcement.

This sounds closer to what I'd need, basically the user could give casbin 'hints', either via model or explicitly during `Enforce` in order to optimize finding the correct r&p

Secondly, casbin could do with a `Query` function, that returns everything that matches a certain request. Instead of feeding casbin everything instead :)

Either way, hope this inspires some optimiziations.

**Comment by hsluoyz** [comment]
Moved to: https://github.com/casbin/casbin/issues/546

**Comment by tlyyxjz** [comment]
Thanks for documenting the numbers so clearly — 55k rules and 1408 shipments is a textbook case of why naive enforce ends up O(all policies).

Two things stood out to me:

1. Short-circuit only pays off if the cheap comparison runs FIRST. Your matcher had `eval(p.sub_rule) && r.obj == p.obj`, so for every rule it evaluated the expensive ABAC sub_rule even when `r.obj == p.obj` was already a guaranteed miss. Flipping it to `r.obj == p.obj && eval(p.sub_rule)` turns a full-scan miss into an O(1) fast path on the common case.

2. You actually landed on the real fix: rule indexing. Going from ~1200ms to ~40ms with an inverted index is exactly the ceiling that brute-force enforce hits, and it's the gap we're trying to close in the tool we build — it diagnoses matcher order, flags expensive `g()`/rule lookups on hot paths, and suggests indexed / filtered enforcement instead of scanning everything. Precisely the "why is my enforce slow" cases people silently walk away from, the way you had to here.

Nice call on the inverted index, by the way.
