### ISSUE TITLE
Performance Issue when Policy Evalution is Slow

### ISSUE THREAD

**Issue by aguss787** [casbin/casbin#516]
There is a use case in our authorization services that requires additional information from other service.

In other locally evaluated policy, casbin is fast enough to meet our requirement. However, it is not the case when we include our use case described above. After some investigation, we found that the problem is that the policy is evaluated sequentially, thus making evaluation of multiple policies quite slow. Our solution is to parallelize the policy by creating multiple enforcer. However, we think the solution can be integrated into casbin so others can benefit from it as well.

**Comment by GopherJ** [comment]
@aguss787  Hi, this can sure be considered adding into casbin, but I think we also need to think about different scenarios. A threshold customizable to activate multi-core ability.

**Comment by aguss787** [comment]
Sure, I think that's make sense. I will try to put it on a parameters or config.

**Comment by aguss787** [comment]
@GopherJ I updated my PR to make it optional with by default it turned off, so others will not affected.
btw, do you mind helping me with the codeclimate's code limit, I don't think I can make it any smaller :sweat_smile:

**Comment by GopherJ** [comment]
@aguss787  it's fine for me, not sure why codeclimate has 500 code limit ~, maybe @nodece  @dovics @divy9881  can help

**Comment by hsluoyz** [comment]
Closed as stale.
