### ISSUE TITLE
[question] How to setup authorization based on OAuth2 JWT?

### ISSUE THREAD

**Issue by michaelkruglos** [casbin/casbin#52]
I'd like to setup authorization based on validition of OAuth2 JWT token, and the claims that appear in it.
I didn't find references to OAuth2 or JWT in the project, is there any information on how this can be accomplished?

**Comment by hsluoyz** [comment]
Which JWT implementation do you want to integrate Casbin with? Is this one? https://github.com/dgrijalva/jwt-go

**Comment by jon-whit** [comment]
@hsluoyz I have the need for this as well. Any recommendations?

**Comment by hsluoyz** [comment]
I suppose you want to setup an OAuth 2.0 Authorization Server like [this](https://github.com/maxzerbini/oauth)? If yes, I think we should determine which OAuth server is the well accepted implementation, and choose that one to integrate Casbin into.

**Comment by jon-whit** [comment]
@hsluoyz close. We are using [Okta](https://www.okta.com/) as our OAuth2 and OpenID provider. Is it best to integrate Casbin? It seems that integrating Casbin is unrealistic for a project like Okta.

**Comment by hsluoyz** [comment]
It seems to be a closed-source and commercial product. AFAIK, OAuth2 provides a simple and standardized support for authorization. e.g., you can specify simple operations in strings when you authorize an app. This is much simpler than what Casbin can provide. If Casbin needs to follow OAuth2 standard, does it mean Casbin will lose its flexibility. Or in another way to ask, what do you want to gain by integrating Casbin with OAuth? use Casbin as a backend of OAuth server? or other types of usage? More details better :)

**Comment by jon-whit** [comment]
The problem that I see with Casbin is that it requires User Identity to be defined inline with the policy table. This is obviously non-ideal if an organization wants to adopt Casbin, but already has a mature IAM provider such as Okta. The question I am most interested in getting your opinion on is, how do you recommend to integrate Casbin with an existing infrastructure like Okta?

Here's my pain point. I don't want to have to go through every single group and user in my existing IAM provider and create an appropriate policy rule for each of them. Instead, I'd prefer to be able to manage User Identity in one place (e.g. Okta) and enforce policy in another (e.g. Casbin). I'd like to externalize policy decisions as it's own service, and so exposing Casbin would be the preferred way of doing this.

I would like to be able to enforce policies based on user attributes, roles, claims, and scopes, all of which would be provided in a JWT from the IAM provider (Okta). Does this make sense?

**Comment by hsluoyz** [comment]
Casbin doesn't store authentication data like the valid usernames and the passwords. So Casbin doesn't have a mechanism to verify the user's identity.

About authorization, there are two kinds of data here:
1) what user can access what resource.
2) what user belongs to what group/role.

You didn't say whether you want to store 1) data in Casbin or not. But I believe this is the core of the Casbin, so if you don't use it, there's no much meaning left to use Casbin. You can use all supported adapters (file, DB, etc) to store this part of information.

For data 2), I understand that you want to keep it in Okta. So Casbin itself doesn't know whether a user belongs to a group and Casbin needs to query an external source. You can implement this by providing a customized function in the model, like the built-in ``g(r.sub, p.sub)`` function. It determines whether the request subject is a group member of the policy subject. But this time, you should implement your own ``g()`` function. And in the implementation, you can query Okta in the way you like (RESTful or JWT or whatever).

**Comment by hsluoyz** [comment]
Hi @jon-whit ,

I'm happy to tell you that Casbin now supports loading roles from Okta via the [Okta Role Manager](https://github.com/casbin/okta-role-manager). See here: https://github.com/casbin/casbin#role-manager

Is this close to what you want?

**Comment by jon-whit** [comment]
@hsluoyz yeah, that's awesome.

I'll have to take a closer look and provide some feedback.

**Comment by exlimit** [comment]
I think this can help you.[Gin JWT Viper Gorm Casbin](http://www.atomicgain.com/go-gin-jwt-viper-gorm-casbin/)
