### ISSUE TITLE
How to query all permissions from grouping policy?

### ISSUE THREAD

**Issue by rrasulzade** [casbin/casbin#527]
I'm looking for a solution to get all permissions which are referenced in grouping policy. i.e:
```
p data1_group data1 read
p data2_group data2 read
p data3_group data3 write

g data2_group data1_group *
g role:admin data2_group domain1
```
Let's say I query `role:admin` to get its permissions which are `[[data1_group data1 read] [data2_group data2 read]]`
How can I achieve this in Casbin?

Thanks

**Comment by rrasulzade** [comment]
Interestingly, `GetImplicitRolesForUser(user, domain)` returns all grouping policies even the ones are not under the given domain.  In an example above I'll get `data2_group data1_group` if I query `role:admin` as a user and `domain1` as a domain inputs.

**Comment by hsluoyz** [comment]
@nodece @GopherJ @dovics @00LT00

**Comment by nodece** [comment]
@rrasulzade I guess you need to call `GetImplicitPermissionsForUser`.

**Comment by rrasulzade** [comment]
Thanks @nodece, Not sure if this is a right thread for this question, What's the update procedure of a policy in Casbin look like? Should I delete the old one and add a new policy? I don't see any API functions for updating an existing policy in Casbin DB

**Comment by nodece** [comment]
Casbin doesn't provide update API, we only supports add and delete APi.
