### ISSUE TITLE
matchers 是什么意思？同时match p p2会怎么样？

### ISSUE THREAD

**Issue by roytan883** [casbin/casbin#53]
RT，文档对matchers写的不清晰。
1：
```ini
[policy_definition]
p = sub, obj, act
p2 = sub, act

[matchers]
m = r.sub == p.sub && r.sub == p2.sub 
```
这到底match的哪一个？

2：
```
m1 = r.sub == p.sub
m2 = r.sub == p2.sub 
```
这样两个matchers又是什么意思？到底match哪一个policy？

3：
然后match到了，就是allow？
```
[policy_effect]
e = some(where (p.eft == allow))
```
这里的p.eft里面的eft是哪里蹦出来的？eft等于什么？ 

看了一个小时看不懂。能不能写一个流程？match是干什么用的，match哪一个，match到的是allow还是deny？match到多个又怎么样？

**Comment by roytan883** [comment]
文档能不能讲清楚r，r1，r2，p，p1，p2，g，g1，g2，e，m的意义？
看了例子，感觉真正csv中实例化的只有p1，p2，g1，g2，而其它几个字母是虚拟意义？
e和m只能有一个？
有多个又是哪个生效呢？
文档写的可以有多个，但又不给多个的例子？
match也是很随意，比如r1，r2，g1，g2，p1，p2混着写到一个match里面 ，match到哪个policy？
能不能混着写，文档上也没说

**Comment by roytan883** [comment]
而且为什么定义文件的字段顺序为什么是r，p，e，m的格式呢？不应该是r，p，m，e吗？
按照流程不应该是：request policy match effect 吗？ 定义请求->定义规则->请求匹配规则->匹配到规则后的结果？还是说我理解有问题？

**Comment by hsluoyz** [comment]
> 这到底match的哪一个？

你这个写法目前不支持，目前一个matcher梨只支持出现一个p，比如p或者p2，不能混着写。

> 这样两个matchers又是什么意思？到底match哪一个policy？

每一个matcher都会尝试匹配所有policy，然effect负责把多个matcher的结果集成。

> 这里的p.eft里面的eft是哪里蹦出来的？eft等于什么？

p.eft如果没有指定的话，默认是allow，如果指定了是deny，那就是deny，可以看一下deny-override的例子

> 看了一个小时看不懂。能不能写一个流程？match是干什么用的，match哪一个，match到的是allow还是deny？match到多个又怎么样？

其实有些地方还不是特别完善，理论上应该实现完全并行的多个matcher的。但是现在的实现程度已经可以实现绝大多数需求了。如果有需求实现不了的话，欢迎讨论。或者想把这个模型完善，也欢迎提PR~

**Comment by hsluoyz** [comment]
> 文档能不能讲清楚r，r1，r2，p，p1，p2，g，g1，g2，e，m的意义？

r代表请求；
p代表策略，可以实例化为规则；
g代表RBAC里的角色继承；
e是matcher决策结果的集成；
m是匹配器。

> 看了例子，感觉真正csv中实例化的只有p1，p2，g1，g2，而其它几个字母是虚拟意义？

可以这么理解

> e和m只能有一个？有多个又是哪个生效呢？文档写的可以有多个，但又不给多个的例子？

e只能有一个，m可以有多个。但是目前只实现了一个，也就是说m2，m3是不支持的。一开始本来想支持，但是后来发现一个m已经可以解决所有问题了，就没有继续完善。欢迎PR~

> match也是很随意，比如r1，r2，g1，g2，p1，p2混着写到一个match里面 ，match到哪个policy？
能不能混着写，文档上也没说

如上述原因，现在不支持多个r、多个p，g可以有多个，参考RBAC with resource roles这个例子。

**Comment by hsluoyz** [comment]
> 而且为什么定义文件的字段顺序为什么是r，p，e，m的格式呢？不应该是r，p，m，e吗？
按照流程不应该是：request policy match effect 吗？ 定义请求->定义规则->请求匹配规则->匹配到规则后的结果？还是说我理解有问题？

你的理解没有问题，matcher的匹配结果是会集成到effect中的。.conf格式写的顺序可以是不一样的，所以可以随便写，把e写在m后面也ok

**Comment by roytan883** [comment]
@hsluoyz 

`[matchers]
m = r.sub == p.sub && r.sub == p2.sub`

> 你这个写法目前不支持，目前一个matcher梨只支持出现一个p，比如p或者p2，不能混着写。

那么问题来了，match只能有一个，而且不能同时用p1，p2，那么定义p1，p2还有什么意义？怎么用呢？

> p.eft如果没有指定的话，默认是allow，如果指定了是deny，那就是deny，可以看一下deny-override的例子

我看到所有例子里面都没有指定allow或者deny的，都是用的`==`

个人觉得文档最大的问题就是没讲明白match和effect，如果只支持一个match那么就该写明，如果可以定义eft，那么就应该文档上写明怎么定义。别简单写一个默认allow，指定可以指定，但是怎么指定又不写。目前感觉就是写hello world一样的一一对应的配置很容易，但是想自己定制，发现文档全没写明怎么弄。

**Comment by roytan883** [comment]
还是说match里面写p就代表了p1，p2？这是一个隐喻？wiki文档上没这样写，但是目前我只能这样理解才能符合你上面的回复

**Comment by roytan883** [comment]
所以，急需一个说明，配置里面那些是实例，哪些是虚拟。说实话单从字面上来，一个conf里面的字母有的是实例对象，有的是虚拟概念，这样混写，歧义太大。
我看其它issue里面也有人这样给你提过。还有人建议你，如果m和e如果是唯一规则，那么就不该写成m=， e= (这样的话都会误以为m，e是实例对象)， 而应该写成[effect] xxxx [match] yyyy

**Comment by roytan883** [comment]
再比如，m，e是关键字吗？
`[matchers] k = r.sub == p.sub` 这种我不写m，写成k，是对是错？
如果是关键字，那么应该写明这个是关键字，只能这样写

**Comment by hsluoyz** [comment]
> 那么问题来了，match只能有一个，而且不能同时用p1，p2，那么定义p1，p2还有什么意义？怎么用呢？

为以后扩展用，现在没用。我本来是想做多个p的，但是开发Casbin的过程中，我发现目前所有的访问控制需求用一个p就都解决了。如果你有必须要多个p才能解决的场景，我们也可以一起讨论、加入该功能。

> 我看到所有例子里面都没有指定allow或者deny的，都是用的==

这里有：https://github.com/casbin/casbin/blob/master/examples/priority_policy.csv

> 个人觉得文档最大的问题就是没讲明白match和effect，如果只支持一个match那么就该写明，如果可以定义eft，那么就应该文档上写明怎么定义。别简单写一个默认allow，指定可以指定，但是怎么指定又不写。目前感觉就是写hello world一样的一一对应的配置很容易，但是想自己定制，发现文档全没写明怎么弄。

因为以后还想着支持多个matcher，所以就没有在文档里说只支持1个matcher。欢迎帮助改进文档：``git pull https://github.com/casbin/casbin.wiki``

**Comment by hsluoyz** [comment]
> 还是说match里面写p就代表了p1，p2？这是一个隐喻？wiki文档上没这样写，但是目前我只能这样理解才能符合你上面的回复

p就是p1, 1隐去了没有写。没有什么隐喻哈。

> 所以，急需一个说明，配置里面那些是实例，哪些是虚拟。说实话单从字面上来，一个conf里面的字母有的是实例对象，有的是虚拟概念，这样混写，歧义太大。
我看其它issue里面也有人这样给你提过。还有人建议你，如果m和e如果是唯一规则，那么就不该写成m=， e= (这样的话都会误以为m，e是实例对象)， 而应该写成[effect] xxxx [match] yyyy

这个其实大部分是为了语法上符合conf格式，必须是```xxx=xxx```的形式，解析起来也容易。你说的有道理，但是那样实现会造成语法上很乱。相比理论上完全make sense，我更侧重于工程实践上简单、一致。

**Comment by roytan883** [comment]
@hsluoyz 
> p就是p1, 1隐去了没有写。没有什么隐喻哈。

那就是说match永远只能用p或者p1，即使上面定义了一个p2，但是也永远在match中不能用p2？我还是不明白，“不能混用”和可以定义多个p的关系

**Comment by hsluoyz** [comment]
> 再比如，m，e是关键字吗？
[matchers] k = r.sub == p.sub 这种我不写m，写成k，是对是错？
如果是关键字，那么应该写明这个是关键字，只能这样写

目前是必须写m的，而且你为啥要换成k啊？最好有一个比较明确的理由，说比如写m会造成什么样的问题，在某种系统上无法应用。不然我换成了k，你又要问为什么不用m？可不可以换成m？然后又要问可不可以既用k又用m，然后在配置文件里指定用哪个，你觉得这样有意义么？

其实这个语言本来就不是为了严谨而生的，而且我也给了很多例子，照着例子写，能解决自己的需求，这个我觉得就算达到目的了。主要是利用这个语言能解决什么样的访问控制问题，这个比较有意义。如果说为了理论上更说得通，影响工程性，我觉得可能就舍本逐末了

**Comment by hsluoyz** [comment]
> 那就是说match永远只能用p或者p1，即使上面定义了一个p2，但是也永远在match中不能用p2？我还是不明白，“不能混用”和可以定义多个p的关系

是的。因为我还没开发这个功能啊。Casbin是个发展中的开源项目，这个语法的功能并没有全部实现。

**Comment by roytan883** [comment]
我不是说我需要特别是换成k，就像c的int， c++的class是关键字的道理。我是说既然是conf定义文件，那么应该清晰，而不是靠猜

按照你的说法，我这种写法是对是错？
```
[request_definition]
r1 = sub, obj, act

[policy_definition]
p1 = sub, obj, act
p2 = sub, act

[matchers]
m1 = r1.sub == p1.sub 
```
如果这是错的（m1必须写成m），那么问题来了，这配置看着很工整啊，也符合99%程序员的常规思维，r1，p1，p2，m1，也是一一对应的
如果这是对的，那么就是有个隐喻：m里面要必须以m开头，m1，m2合法，k1，k2不合法。隐喻靠猜这个太不靠谱了。

**Comment by hsluoyz** [comment]
这是``mysql.ini``文件的一部分内容：
```
APP_NAME = Gitea: Git with a cup of tea
RUN_MODE = prod

[database]
DB_TYPE  = mysql
HOST     = 127.0.0.1:3306
NAME     = testgitea
USER     = root
PASSWD   =
SSL_MODE = disable
PATH     = data/gitea.db
```

这个配置文件也是规定死的啊，你为啥不问，为什么不能写HOST1，HOST2，必须写HOST？

就是一种约定啊，文档里所有的解释和例子都遵守了约定，就是语法的一部分，你非要改一个名字，问可不可以，这个意义不大。

**Comment by roytan883** [comment]
@hsluoyz 你就简单告诉我
```
[request_definition]
r1 = sub, obj, act

[policy_definition]
p1 = sub, obj, act
p2 = sub, act

[matchers]
m1 = r1.sub == p1.sub 
```
这个配置是对的还是错的就行了啊。

> 另外，HOST是关键字当然不能写成HOST1和HOST2了，mysql说明文档里面写的明明白白的，没有任何歧义

**Comment by roytan883** [comment]
@hsluoyz 
> 就是一种约定啊，文档里所有的解释和例子都遵守了约定，就是语法的一部分，你非要改一个名字，问可不可以，这个意义不大。

问题就在这里，你说这是一种约定，但是约定在哪里？“必须写m这个约定”，起码我翻遍了所有文档没看到。那么我前面看到可以写p1，p2，在没有看到明确些只能用m的情况下，我是不是会正常联想到m1，m2也是合法的？

你看其它库的时候，之前看到p1，p2，后面是不是也会自然的想到m1，m2？

**Comment by roytan883** [comment]
@hsluoyz 

> 是的。因为我还没开发这个功能啊。

既然做开源库，那么就该有做开源库的态度，不能说因为我开源，所以我只实现了一半功能的文档我就可以随意写, 实现与未实现的功能应该明确写出来，而不是靠猜这种。当问到关键点功能和文档不符合了，就一句因为我开源，所以不要和我bb的态度。既然前后都有人提文档不清晰，那么可能得话何不改改文档就好了呢？开源是合作，为什么一上来就你就感觉我要和你争对错辨是非的态度？

https://github.com/ice-services/moleculer/issues/107

这是我和moleculer关于他的文档，关于约定协议的讨论。讨论的要点是怎么样改进文档，更加清晰易用，怎么合作，我给他写一个go语言版遇到不清晰的文档，双方讨论如何修正。

**Comment by hsluoyz** [comment]
> 这个配置是对的还是错的就行了啊。

不对，m1应该为m

> 问题就在这里，你说这是一种约定，但是约定在哪里？“必须写m这个约定”，起码我翻遍了所有文档没看到。那么我前面看到可以写p1，p2，在没有看到明确些只能用m的情况下，我是不是会正常联想到m1，m2也是合法的？

确实是个问题，已经在文档上增加相关说明：https://github.com/casbin/casbin/wiki/Matchers

> 既然做开源库，那么就该有做开源库的态度，不能说因为我开源，所以我只实现了一半功能的文档我就可以随意写, 实现与未实现的功能应该明确写出来，而不是靠猜这种。当问到关键点功能和文档不符合了，就一句因为我开源，所以不要和我bb的态度。既然前后都有人提文档不清晰，那么可能得话何不改改文档就好了呢？开源是合作，为什么一上来就你就感觉我要和你争对错辨是非的态度？

老哥对开源很严谨，受教了。已修改文档哈，如上

**Comment by roytan883** [comment]
@hsluoyz 因为你的这个项目很不错，如果文档更清晰一些，这样会有更多的人来用

**Comment by hsluoyz** [comment]
嗯，你用在什么项目上了嘛
