### ISSUE TITLE
SyncedCachedEnforcer

### ISSUE THREAD

**Issue by 6ecuk** [casbin/casbin#537]
Hi, I have a question - is there any solution to have a hybrid with syncedEnforcer and cachedEnforcer? I need a solution to have a performance from cachedEnforcer and auto-update from syncedEnforcer.

**Comment by GopherJ** [comment]
we should just implement those function in cached enforcer

**Comment by nodece** [comment]
We should add lock to model then it is safe in everyway.

**Comment by dovics** [comment]
it is not enough that model is safe. We need to consider adapter

for example `addPolicy`,Its steps are `model.HasPolicy -> adapter.AddPolicy -> model.AddPolicy`, If two threads exec addPolicy at same time, the first thread pauses after the end of adapter.AddPolicy, the second begin execution until finished, hasPolicy will return false, and there will be two identical contents in the adapter

**Comment by dovics** [comment]
Now the `IEnforcer` is very large, maybe we can abstract a new interface to manage the model and adapter, only provide basic functions, and then enforcer to provide API, which can also better integrate casbin-raft

**Comment by GopherJ** [comment]
@dovics if adapter can ensure the duplicate check.  I think it's safe

**Comment by dovics** [comment]
@GopherJ It seems that most of Golang's adapters do not support this feature. Does this require us to read the database twice? I think it is faster to just check the data in memory

**Comment by GopherJ** [comment]
@dovics If this feature is not supported I think we should request their authors to implement，otherwise how can we ensure that there isn't any Adapter.AddPolicy while calling Model.HasPolicy


If we cannot ensure this，there will be duplicates. 

Image when you call HasPolicy，there is already 3 ongoing Adapter.AddPolicy

**Comment by dovics** [comment]
> how can we ensure that there isn't any Adapter.AddPolicy while calling Model.HasPolicy

@GopherJ  this is the key to this problem. We need a new way to ensure strong consistency. The current read-write lock is one way. 

I don’t know what way @nodece wants to ensure this in the model, But if we use this method on the new component, will it be better than reading the database twice?

**Comment by nodece** [comment]
in my opinion, I should add lock to ManagementAPI to ensure that adapter is safe, for model also same.

**Comment by GopherJ** [comment]
> @GopherJ It seems that most of Golang's adapters do not support this feature. Does this require us to read the database twice? I think it is faster to just check the data in memory

Normally db adapter should have constraints to deny duplicates, if not, we should find another solution

It's important to have this, otherwise filtered adapter is also buggy... because check dup in model is useless

**Comment by hsluoyz** [comment]
@6ecuk has this issue been fixed by: https://github.com/casbin/casbin/pull/538 ? If yes, please close it.
