### ISSUE TITLE
Partial evaluation as in Open Policy Agent

### ISSUE THREAD

**Issue by mfzl** [casbin/casbin#545]
As explained in the blog post https://blog.openpolicyagent.org/write-policy-in-opa-enforce-policy-in-sql-d9d24db93bf4

Is this possible with Casbin?

Use case is when you have a list of resources you want to retrieve only the resources subject is allowed to view. Without it, each resource needs to be checked after retrieval before returning response to user.

**Comment by nodece** [comment]
It looks like you want to filter data from DB by policy. 

The image from above blog post:

![image](https://user-images.githubusercontent.com/16235121/88252507-0c0b5a80-cce1-11ea-914e-fd22e0e334d1.png)

Casbin mainly control user if can access Server/Data,  so workflow:` Client` <-> `Casbin` <-> `Server/Data`.

For example: 
> “Pet owners can access their own pet’s profiles.”
> “Veterinarians can access pet profiles from devices at the clinic.”

You should try to use `ABAC with policy rule` on https://casbin.org/en/editor.

**Comment by mfzl** [comment]
Casbin doesn't have to convert policy to SQL. As mentioned in blog post the conversion is for user to do. Open policy agent returns 
expressions that cannot be evaluated and then user converts those expressions to SQL.

**Comment by mfzl** [comment]
For example:

`p, r.sub.Age > 18 && r.sub.Age < 60, /data1, read` 

Would return ` r.sub.Age > 18 && r.sub.Age < 60` as unevaluated

This essentially means subject has read access if this expression evaluates to true but casbin doesn't know how to evaluate the
expression and returns  `r.sub.Age > 18 && r.sub.Age < 60` instead of evaluating.

User can then convert the expression to:
`users.age > 18 AND users.age < 60` to be used in a `WHERE` clause of a query

**Comment by mfzl** [comment]
To clarify further

### Request
```
{ Role: 'Admin'}, /data1, read
```

### Model
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub_rule, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = eval(p.sub_rule) && r.obj == p.obj && r.act == p.act
```

### Policy
```
p, r.sub.Role == 'Admin' && r.sub.Age > 18 && r.sub.Age < 60, /data1, read
```

As you see in this case `Request` doesn't have information about the subject's `Age` so instead of trying to evaluate it
return part of the expression that cannot be fully evaluated i.e `r.sub.Age > 18 && r.sub.Age < 60` for user to evaluate.

`r.sub.Role == 'Admin'` however can be evaluated and it should return `False` if subject is not admin and result can be concluded without further evaluation.

**Comment by nodece** [comment]
you should note is `eval(p.sub_rule)`, Casbin will eval `p.sub_rule` as expression.

**Comment by mfzl** [comment]
> you should note is `eval(p.sub_rule)`, Casbin will eval `p.sub_rule` as expression.

I'm not sure what you mean. Are you saying it's possible to do.

**Comment by nodece** [comment]
please visit https://casbin.org/docs/en/abac#scaling-the-model-for-complex-and-large-number-of-abac-rules for details.

**Comment by nodece** [comment]
For you above example, `r.sub.Role == 'Admin' && r.sub.Age > 18 && r.sub.Age < 60` will returns false, because ` r.sub.Age` is undefined.

**Comment by mfzl** [comment]
> For you above example, `r.sub.Role == 'Admin' && r.sub.Age > 18 && r.sub.Age < 60` will returns false, because ` r.sub.Age` is undefined.

This is the problem I'm getting at. Is there a possible way to tell casbin to not evaluate in case it's undefined and return the expression.

I understand it evaluates to `false`. I tried with https://casbin.org/en/editor

**Comment by mfzl** [comment]
I think partial evaluation is a powerful feature to enforce policies on huge lists of resources.

**Comment by nodece** [comment]
> This is the problem I'm getting at. Is there a possible way to tell casbin to not evaluate in case it's undefined and return the expression.

Casbin dependent on  https://github.com/Knetic/govaluate. I think govaluate cannot support the feature.

**Comment by nodece** [comment]
In Casbin, we also support add owner function to matcher.

**Comment by mfzl** [comment]
> Casbin dependent on https://github.com/Knetic/govaluate. I think govaluate cannot support the feature.

I thought so, hence why I opened https://github.com/Knetic/govaluate/issues/144

**Comment by GopherJ** [comment]
Casbin currently doesn't support **partial evaluation**

**Comment by mfzl** [comment]
Do you think it's in the realm of possibilities if `govaluate` adds support for it?

**Comment by GopherJ** [comment]
@mfzl it's not on `govaluate` side, it's more on our side, but yes we also need to know if `expression evaluator` has this error type

**Comment by SPopenko** [comment]
@GopherJ could you please suggest the recommended  way how to solve this resource list filtration task? 
Like ‘Alice’ owns a few pets (A, B) and as well she is veterinarian who treats another pets (C, D),  how we could return the list of “pets” that she has access to: A,B,C,D ?

**Comment by hsluoyz** [comment]
Closed here. Stay tuned at: https://github.com/casbin/casbin/issues/617
