### ISSUE TITLE
Rule Indexing feature

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin#546]
Ref: 

1. https://blog.openpolicyagent.org/optimizing-opa-rule-indexing-59f03f17caf3
2. https://github.com/casbin/casbin/issues/511

**Comment by hsluoyz** [comment]
@GopherJ good point about this optimization.

I think it is @00LT00 's responsibility to take this issue. Can you do it?

**Comment by nodece** [comment]
I note is that is Consul also use similar method to optimizing policy, the https://github.com/armon/go-radix used by Consul.

**Comment by 00LT00** [comment]
I'm trying to solve the update of caddy @hsluoyz .And then I will learning it.

**Comment by divy9881** [comment]
Yeah, storing policy rules in hierarchical data-structure like `Trie` can be very fruitful in cases where there are a large number of policy rules. Storing it in linear data-structure like `list` does not allow you to optimize further than O(N), under this we can get result generation optimized by O(log(N)) roughly. If everyone is okay, can I take this issue, I will be very happy to work on this.

**Comment by GopherJ** [comment]
@divy9881 I think yes, could you elaborate your idea once you got it?

**Comment by hsluoyz** [comment]
@00LT00 is there any progress for this issue?

**Comment by chanced** [comment]
roaring bitmaps may also help. But that may not be an option for all client languages.
