### ISSUE TITLE
How to synchronize multiple Casbin enforcer instances running with a single pg Gorm adapter?

### ISSUE THREAD

**Issue by rrasulzade** [casbin/casbin#547]
I'm using Casbin library with pg Gorm adapter in one of my services. I wonder how I can keep Casbin enforcers synched if I'm running multiple instances of that services? Since Casbin policies are loaded once at startup and stored in memory, if one of the instances updates policies later, other enforcers wouldn't be notified. I looked at Casbin server but not sure if that would be helpful in this case, if so how I can achieve the synchronization by using Casbin server? or what are the other options?

**Comment by rrasulzade** [comment]
maybe I should implement Watcher / WatcherEx interface for pg Gorm? Are there any examples of SQL/ORM db watchers?

**Comment by nodece** [comment]
For multiple Casbin instances , We only supports use Watcher / WatcherE. 

When policy changes, Casbin will call Watcher / WatcherEx to notify other Casbin. 

Please visit https://casbin.org/docs/en/watchers for Watcher details.

**Comment by rrasulzade** [comment]
Thanks @nodece.  As I understand, the watcher will notify other instances to reload policies from DB but doesn't that sound an expensive operation?

**Comment by hsluoyz** [comment]
@rrasulzade yes, that's why we have introduced WatcherEx: https://github.com/casbin/casbin/pull/400. WatcherEx instances will only sync policy diff than the whole policy data.

**Comment by rrasulzade** [comment]
@hsluoyz 
I check that interface too but I don't see any examples/implementations of it for Redis or other tools on https://casbin.org/docs/en/watchers. Something I need to implement on my own?

**Comment by hsluoyz** [comment]
@dovics is it possible to use WatcherEx with Redis backend? Can you add WatcherEx's docs to our website?

**Comment by dovics** [comment]
@rrasulzade It is feasible to use redis to implement watcherEx. We can subscribe to the same channel, let the instance that received the modification request publish, and then let other instances update according to the published content.

Currently we do not have an implementation of watcherEx yet, maybe I will try it next month

**Comment by rrasulzade** [comment]
hey @dovics, any luck of trying above you mentioned?

**Comment by nodece** [comment]
@rrasulzade We are going to prepare [casbin-raft](https://github.com/casbin/casbin-raft).

**Comment by rrasulzade** [comment]
@dovics that seems something different than Redis watcher. Could you please provide some details about casbin-raft? Will that also achieve https://github.com/casbin/casbin/issues/402? Thanks

**Comment by nodece** [comment]
@rrasulzade Using casbin-raft can solve the any sync issue, we are still testing casbin-raft, so we only have test code, you can checkout casbin-raft to visit more information. one thing to note that it is in beta phase, and it works on casbin v3 beta version.

**Comment by rrasulzade** [comment]
hey @nodece, Will casbin-raft be supported on casbin v2? Currently, I'm using v2 and I'm not sure about the new changes on v3 beta which I suppose will be v3 later.

**Comment by rrasulzade** [comment]
@hsluoyz @nodece @dovics 
Hi all, I wonder where I can get updates and status on `casbin raft` implementation? Will it be released with `casbin` v3 and how does the timeline look like for this release? Thanks

**Comment by hsluoyz** [comment]
@dovics 

/cc @nodece

**Comment by rrasulzade** [comment]
@hsluoyz  @nodece  @dovics 
Hi everyone, could you please provide the estimated time for Casbin-raft and v3 to go to public? Thanks

**Comment by rrasulzade** [comment]
Hi again, as you noticed this feature is very crucial for us, in order to run multiple instances to perform policy enforcement operations using Casbin. I'm very curious when we'll be able to use casbin-raft to support cluster of instances of casbin enforcer?

**Comment by hsluoyz** [comment]
@rrasulzade sorry for so late response. Please see: https://github.com/nodece/casbin-hraft-dispatcher

**Comment by hsluoyz** [comment]
@nodece why is this (https://github.com/casbin/casbin-raft) archived? Do we have a replacement?

**Comment by rrasulzade** [comment]
@hsluoyz  I thought this was already implemented and released in Casbin v2.19. Am I missing something here?
https://github.com/casbin/casbin/releases/tag/v2.19.0

**Comment by hsluoyz** [comment]
OK. Maybe we should add the new DistributedEnforcer class (https://github.com/casbin/casbin/commit/449a09dab556c695090622c2134a42c84f24c677) to our docs: https://casbin.org/docs/en/dispatchers

@closetool

**Comment by nodece** [comment]
> @nodece why is this (https://github.com/casbin/casbin-raft) archived? Do we have a replacement?

casbin-raft needs update, I don't have time to do it. currently I recommend https://github.com/casbin/hraft-dispatcher.

**Comment by rrasulzade** [comment]
@nodece what is the difference between [hraft-dispatcher](https://github.com/casbin/hraft-dispatcher) and [v2.19.0](https://github.com/casbin/casbin/releases/tag/v2.19.0)? can't I use the latter?

**Comment by nodece** [comment]
@rrasulzade v2.19.0 provides a distributed enforcer, it is main feature is to provide an interface for dispatcher to update policies by dispatcher.
