### ISSUE TITLE
Add priority policy element support

### ISSUE THREAD

**Issue by wndrr101** [casbin/casbin#550]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2421%20Funded-%2300A156.svg" />](https://issuehunt.io/r/casbin/casbin/issues/550)

Hello,

It seems that I stuck in the middle with trivial issue. Hope you'll help me with a guidance.
Trying to build a model for REST API authorisation with an option to override "parent" permission.

<h3>Option 1</h3>

Test model:
```ini
[request_definition]
r = subj, obj, act

[policy_definition]
p = subj, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = priority(p.eft) || deny

[matchers]
m = (g(r.subj, p.subj) || (r.subj == p.subj)) && regexMatch(r.obj, p.obj) && regexMatch(r.act, p.act)
```

Test policy:
```ini
p, alice, /foo/bar/.+/.+baz.+, GET, allow
p, alice, /foo/bar/.+/baz$, GET, deny
p, alice, /foo/bar/.+, GET, allow
p, alice, /foo/bar.+, GET, deny
p, alice, /foo/bar$, GET, allow
p, alice, /foo/.+, GET, deny
p, alice, /foo.+, GET, deny
p, data2_admin, /foo$, GET, allow
p, alice, /.+, GET, deny

g, alice, data2_admin
```

Test requests:
```ini
alice, /zed, GET
alice, /zed, POST

alice, /foo, GET
data2_admin, /foo, GET
alice, /foo-bar, GET
alice, /foo/zed, GET
alice, /foo/bar, GET
alice, /foo/bar-zed, GET
alice, /foo/bar/zed, GET

alice, /foo/bar/*/baz-q, GET
alice, /foo/bar/zed/baz, GET

alice, /foo/bar/*/*baz*, GET
alice, /foo/bar/zed/aaa-baz=val, GET
```

Everything woks as expected **BUT** the longest (most precise) rule should be added on top of rules list.
So, "priority" needs to be in place in particular here:
```ini
1. p, alice, /foo/bar/.+/.+baz.+, GET, allow
2. p, alice, /foo/bar/.+/baz$, GET, deny
3. p, alice, /foo/bar/.+, GET, allow
```

for
```ini
alice, /foo/bar/*/baz-q, GET ---> true
alice, /foo/bar/zed/baz, GET ---> false
```

How should be and addition of any new more specific rule handled if there is no option for "numbered insertion" for any new particular rule? For example there is a new REST API endpoint and new authorisation rule needed.
Let's say I need "rule zero on top of existing list"
```ini
0. p, alice, /foo/bar/.+/.+baz-q$, GET, deny
1. p, alice, /foo/bar/.+/.+baz.+, GET, allow
2. p, alice, /foo/bar/.+/baz$, GET, deny
3. p, alice, /foo/bar/.+, GET, allow
```
Should it be done aside of Casbin and then policy reloaded forcibly by Casbin server? Or there is more convenient way?
p.s. actually it is somewhat alike to #290 

<h3>Option 2</h3>

Everything is the same but Effector is "allow-override"

Test model:
```ini
[request_definition]
r = subj, obj, act

[policy_definition]
p = subj, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g(r.subj, p.subj) || (r.subj == p.subj)) && regexMatch(r.obj, p.obj) && regexMatch(r.act, p.act)
```

Test policy:
```ini
p, alice, /foo/bar/.+/.+baz.+, GET, allow
p, alice, /foo/bar/.+/baz$, GET, deny
p, alice, /foo/bar/.+, GET, allow
p, alice, /foo/bar.+, GET, deny
p, alice, /foo/bar$, GET, allow
p, alice, /foo/.+, GET, deny
p, alice, /foo.+, GET, deny
p, data2_admin, /foo$, GET, allow
p, alice, /.+, GET, deny

g, alice, data2_admin
```

Test requests:
```ini
alice, /zed, GET
alice, /zed, POST

alice, /foo, GET
data2_admin, /foo, GET
alice, /foo-bar, GET
alice, /foo/zed, GET
alice, /foo/bar, GET
alice, /foo/bar-zed, GET
alice, /foo/bar/zed, GET

alice, /foo/bar/*/baz-q, GET
alice, /foo/bar/zed/baz, GET

alice, /foo/bar/*/*baz*, GET
alice, /foo/bar/zed/aaa-baz=val, GET
```

With this Effector in place result is different:
```ini
alice, /foo/bar/*/baz-q, GET ---> true
alice, /foo/bar/zed/baz, GET ---> true
```

Second request is improperly (or am I wrong?) rendered to "true" also.
And here I think it would be nice to be able to choose "longest/precise match", that is request 
```ini
/foo/bar/zed/baz
```
described more precisely by the
```ini
/foo/bar/.+/baz$
```
regex rule rather than
```ini
/foo/bar/.+/.+baz.+
```

What I try to achieve is that no matter the order of the policy rules examined, most precise rule should be chosen as a result.
or
Ability to re-balance policy rules list during create/update/delete operations with those rules to comply with "priority eft".

Or did I chose effector and matcher in a wrong way?

***

Any input would be appreciated.
Thanks.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $21.00)

- [<img src='https://avatars0.githubusercontent.com/u/3787410?v=4' alt='hsluoyz' width=24 height=24> hsluoyz](https://issuehunt.io/u/hsluoyz) ($1.00)
- $20.00 have been anonymously funded.

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/casbin/casbin/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by hsluoyz** [comment]
@wndrr101 very good question. I think Option 1 would be easier. We should add a new column for rules called "priority number". It works very similar to classic firewall rules:

`
Rules are processed in priority order; the lower the number, the higher the priority. We recommend leaving gaps between rules - 100, 200, 300, etc. - so that it's easier to add new rules without having to edit existing rules.
`

![image](https://user-images.githubusercontent.com/3787410/89002153-f1636200-d32e-11ea-9e2a-28e4e4e97572.png)

@nodece @dovics @00LT00 can you do it?

**Comment by hsluoyz** [comment]
@00LT00 please work on this issue.

**Comment by 00LT00** [comment]
I'm trying to do

**Comment by 00LT00** [comment]
@nodece @wndrr101 Hi, I'm trying to add priorityID for the policy. Now I have some problems.
1. is the new column priorityID optional? front or back?
2. can priority be equal?

**Comment by wndrr101** [comment]
Hello @00LT00,

Here is my 2c:
>1. is the new column priorityID optional? front or back?
it might be optional on my opinion, if it's optional than req_definition and pol_definition should be created new verb line "num"
```ini
[request_definition]
r = num, subj, obj, act
````
no "num" - no numbered priority

>"front or back?"
didn't get what you mean.

>2. can priority be equal?
Don't think so. What would be "choosing function" in this case with same prioriries? It's like now.

***
While I'm using now my own hack for pycasbin (just length sort WHEN saving policy with AUTO_SAVE disabled) I've found one moment worth to consider:
one should also number properly "user's rules" and "group's rules"

```ini
[request_definition]
r = dom, sub, obj, act

[policy_definition]
p = dom, sub, obj, act, eft

[role_definition]
g = _, _, _

[policy_effect]
e = priority(p.eft) || deny

[matchers]
m = (((r.sub == p.sub) || g(r.sub, p.sub, r.dom)) && r.dom == p.dom && regexMatch(r.obj, p.obj) \
&& regexMatch(r.act, p.act)) || ((g(r.sub, "root", p.dom) || r.sub == "admin") && r.dom == p.dom)
```

Test policy:
```ini

p, domain1, data2_admin, /foo$, GET, allow
p, domain1, alice, /foo$, GET, deny
p, domain1, root, /foo$, GET, deny
p, domain1, alice, /.+, GET, deny

g, alice, data2_admin, domain1
g, bob, root, domain1
```

As you can see, Alice is in group data2_admin.
If rules for data2_admin would be (un-)intentionally set before Alice's rules, they would be evaluated first, like in case above.

And here
```ini
domain1, alice, /foo, GET
domain1, data2_admin, /foo, GET
```

first rule would be evaluated as True. But it should be False if we're tend to think that user is more specific than group.
It might be semi-auto like any Group/Role's rules are numbered after User's  OR it may be left on dev/admin discretion.

--
thanks

**Comment by 00LT00** [comment]
@hsluoyz @nodece @dovics What do you think about the Group/Role's rules? I feel a little too complicated.

**Comment by hsluoyz** [comment]
@nodece @GopherJ @xcaptain

**Comment by nodece** [comment]
> @wndrr101 very good question. I think Option 1 would be easier. We should add a new column for rules called "priority number". It works very similar to classic firewall rules:
> 
> `Rules are processed in priority order; the lower the number, the higher the priority. We recommend leaving gaps between rules - 100, 200, 300, etc. - so that it's easier to add new rules without having to edit existing rules.`
> 
> ![image](https://user-images.githubusercontent.com/3787410/89002153-f1636200-d32e-11ea-9e2a-28e4e4e97572.png)
> 
> @nodece @dovics @00LT00 can you do it?

@00LT00 This is good idea, but I also know it is quite complex, so I recommend starting with #546,  because I don't think our data struct of policy can supports the feature.

maybe the best work for you on Summer 2020.

what do you think?

**Comment by nodece** [comment]
> Hello @00LT00,
> 
> Here is my 2c:
> 
> > 1. is the new column priorityID optional? front or back?
> >    it might be optional on my opinion, if it's optional than req_definition and pol_definition should be created new verb line "num"
> 
> ```ini
> [request_definition]
> r = num, subj, obj, act
> ```
> 
> no "num" - no numbered priority
> 
> > "front or back?"
> > didn't get what you mean.
> 
> > 1. can priority be equal?
> >    Don't think so. What would be "choosing function" in this case with same prioriries? It's like now.
> 
> While I'm using now my own hack for pycasbin (just length sort WHEN saving policy with AUTO_SAVE disabled) I've found one moment worth to consider:
> one should also number properly "user's rules" and "group's rules"
> 
> ```ini
> [request_definition]
> r = dom, sub, obj, act
> 
> [policy_definition]
> p = dom, sub, obj, act, eft
> 
> [role_definition]
> g = _, _, _
> 
> [policy_effect]
> e = priority(p.eft) || deny
> 
> [matchers]
> m = (((r.sub == p.sub) || g(r.sub, p.sub, r.dom)) && r.dom == p.dom && regexMatch(r.obj, p.obj) \
> && regexMatch(r.act, p.act)) || ((g(r.sub, "root", p.dom) || r.sub == "admin") && r.dom == p.dom)
> ```
> 
> Test policy:
> 
> ```ini
> p, domain1, data2_admin, /foo$, GET, allow
> p, domain1, alice, /foo$, GET, deny
> p, domain1, root, /foo$, GET, deny
> p, domain1, alice, /.+, GET, deny
> 
> g, alice, data2_admin, domain1
> g, bob, root, domain1
> ```
> 
> As you can see, Alice is in group data2_admin.
> If rules for data2_admin would be (un-)intentionally set before Alice's rules, they would be evaluated first, like in case above.
> 
> And here
> 
> ```ini
> domain1, alice, /foo, GET
> domain1, data2_admin, /foo, GET
> ```
> 
> first rule would be evaluated as True. But it should be False if we're tend to think that user is more specific than group.
> It might be semi-auto like any Group/Role's rules are numbered after User's OR it may be left on dev/admin discretion.
> 
> --
> thanks

I wonder #496 can solve the question. could you upgrade casbin to v2.10.0 and using `e = some(where (p_eft == allow)) || !some(where (p_eft == deny))` as policy_effect?

**Comment by wndrr101** [comment]
@nodece , I've been thinking about #496, but I'm using pycasbin at the moment. Either I'll port $496 functionality to python or may be in future make a transition to Casbin Server.

@hsluoyz , could you please tell me why there are 2 versions of pycasbin - one is https://github.com/casbin/pycasbin and another is https://github.com/pycasbin and what is the difference?

**Comment by hsluoyz** [comment]
@wndrr101 

- https://github.com/casbin/pycasbin is the core library for Python. https://github.com/pycasbin/pycasbin is just a fork of it.
- https://github.com/pycasbin is a place to hold all PyCasbin related adapters, middlewares, etc.

@techoner can we delete the fork: https://github.com/pycasbin/pycasbin to avoid misunderstanding?

**Comment by hsluoyz** [comment]
The final plan is:

```ini
[request_definition]
r = dom, sub, obj, act

[policy_definition]
p = priority, dom, sub, obj, act, eft

[role_definition]
g = _, _, _

[policy_effect]
e = priority(p.eft) || deny

[matchers]
m = (((r.sub == p.sub) || g(r.sub, p.sub, r.dom)) && r.dom == p.dom && regexMatch(r.obj, p.obj) \
&& regexMatch(r.act, p.act)) || ((g(r.sub, "root", p.dom) || r.sub == "admin") && r.dom == p.dom)
```

If there is a `priority` in policy definition, then this integer value in p will be used as the priority for the p rule. Like I said here: https://github.com/casbin/casbin/issues/550#issuecomment-666924986 , the smaller `priority` value will have higher priority, just like a firewall.

We will first implement this feature in Go, and finally port it to Python.

/cc @closetool

**Comment by hsluoyz** [comment]
@closetool plz add a new document page named "Priority Model" to the official docs and write about this new feature.
