### ISSUE TITLE
Make a Casbin middleware for "gorilla/mux" web framework

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin#551]
https://github.com/gorilla/mux is one of the most popular Go web frameworks (with 12.4k stars). But we still don't have an authz middlware for it yet.

There are already some users complaining about it on Reddit:

https://www.reddit.com/r/golang/comments/i18qoo/a_little_confused_about_authorization/fzysms0/

![image](https://user-images.githubusercontent.com/3787410/89114977-f6eab480-d4b4-11ea-9966-7d2372879d67.png)

So we should make one ASAP. Here's how to make a middlware for gorilla/mux: https://github.com/gorilla/mux#middleware

**Comment by hsluoyz** [comment]
@nodece @GopherJ @divy9881 @dovics @00LT00 can anybody take this task?

**Comment by 00LT00** [comment]
I'm create mux-authz in [mux-authz](https://github.com/casbin/mux-authz) @hsluoyz

**Comment by 00LT00** [comment]
But now I have a problem. 
Should we only verify the whole path like 
`r.obj = "/dataset1/resource1/*/*..." `
or verify only a single field like `/xxx/{token}/xx` 
`r.obj = token`
The mux isn't support '*'.Therefore, if the first method is used, users must use regular expressions to match paths like `r.HandleFunc("/{url:[A-Za-z0-9\\/]+}", handler)`
But if the second method is used, there are not many fields that can be verified
`/{dom}/{obj}`

**Comment by hsluoyz** [comment]
@00LT00 are you asking a Casbin core library question? Here's the wrong place. In this middleware, you can just copy the example and test from other middlewares.

**Comment by hsluoyz** [comment]
@00LT00 also please do this: https://github.com/casbin/mux-authz/issues/1

**Comment by 00LT00** [comment]
> @00LT00 also please do this: [casbin/mux-authz#1](https://github.com/casbin/mux-authz/issues/1)

finished casbin/mux-authz#2

**Comment by 00LT00** [comment]
updated casbin/mux-authz#3 @hsluoyz

**Comment by hsluoyz** [comment]
Done: https://github.com/casbin/mux-authz
