### ISSUE TITLE
Combine ABAC and RBAC for dynamic roles list

### ISSUE THREAD

**Issue by ngjaying** [casbin/casbin#553]
I have a similar request as #63 but thinking to apply it to dynamic roles list. We would like to let the user create customized roles at runtime. So we will have dynamic roles list which can be categorized as
- A dynamic list of roles which can access all objects. e.g.  roles [admin, customAdmins ... ]
- Another dynamic list of roles which can access only owned objects. e.g.  roles [admin, customAdmins ... ]
- A list of roles which cannot access any objects. e.g. roles [banned]

The model in #63 is quite close to meet the request, except that the matcher hard coded the role "admin". How can we extend it to support a dynamic admin list.
```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == r.obj.owner || g(r.sub, "admin")
```

**Comment by 00LT00** [comment]
I've been thinking for a long time how to use dynamic roles.But I have no good idea temporary. Can you give me some hints especially the matchers? How do you want matchers to write... @ngjaying

**Comment by hsluoyz** [comment]
@ngjaying you can do this:

Model:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == r.obj.owner || g(r.sub, g.sub) && p.obj == "*"
```

Policy:

```csv
p, admin, *, read
g, admin1, admin
g, admin2, admin
```
