### ISSUE TITLE
RBAC with domain pattern

### ISSUE THREAD

**Issue by DarkSorrow** [casbin/casbin#554]
Hello,

I'm using the go version of casbin ""github.com/casbin/casbin/v2"
And i took as exemple those files
https://github.com/casbin/casbin/blob/master/examples/rbac_with_domain_pattern_model.conf
https://github.com/casbin/casbin/blob/master/examples/rbac_with_all_pattern_policy.csv

but when i try to do
`test, _ := casEnforcer.Enforce("alice", "domain1", "data1", "read")`
The result i get is false, but if i understood the documentation well i should have it as true since with pattern policies alice is in all domains no?

**Comment by hsluoyz** [comment]
@DarkSorrow please use https://casbin.org/en/editor to test first.

**Comment by DarkSorrow** [comment]
hello well i was the one that raised that issue already on the editor and then was told that the editor wasn't up to date but that this was working on the real server. But then maybe i'm lacking something?

here was the issue there:
https://github.com/casbin/casbin-editor/issues/16

**Comment by nodece** [comment]
@DarkSorrow please visit https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac for using pattern.

**Comment by DarkSorrow** [comment]
I visted your documentation but the code you provide as example doesn't work with what you show as exemple in the start
where does your e.rm comes from? I don't have it when i import the "github.com/casbin/casbin/v2".
I understand the concept of open source library and that people can read the code and all but you seems to be importing package in different ways with the file examples. It would be nice to have examples for people that are trying to integrate it in a clean project from your own "Get started" :p

**Comment by DarkSorrow** [comment]
I'm trying to do this with the casbin v2

```
casEnforcer, errorCasbin := casbin.NewEnforcer("rights/model.conf", "rights/policy.csv")
if errorCasbin != nil {
	bymeLog.Zap.Fatal(errorCasbin.Error())
}
rm := defaultrolemanager.RoleManager{}
rm.AddDomainMatchingFunc("KeyMatch", casbinUtils.KeyMatch)
casEnforcer.SetRoleManager(&rm)
```

But it doesn't seems to work either with the file example you gave

**Comment by nodece** [comment]
@DarkSorrow  This is test code: https://github.com/casbin/casbin/blob/master/rbac_api_test.go#L236.

**Comment by DarkSorrow** [comment]
@nodece well i tried what was in that line too but it doesn't work with the domain pattern file.
Did you try to test the rbac_with_domain_pattern_model.conf? Cause i admit i'm not sure what else to try at the moment, i'm thinking of trying a last thing by implementing a role manager but my need seems to be pretty basic, i just want to have a role with a wildcard for the domain :x 
The library seems to have a lot of different possibilities i guess it's why i'm slightly confused on the usage from it but maybe its the file itself that should have a keyMatch isntead of an equality on the dom? tho this fucntion AddDomainMatchingFunc kinda makes me think that we should be able to just add a specific function on dom no?

**Comment by DarkSorrow** [comment]
I added the matcher with the AddDomainFunc and it seems to be working now, maybe the doc could be updated to show this later :x

**Comment by hsluoyz** [comment]
@nodece @00LT00 can you add this to docs?
