### ISSUE TITLE
Domain pattern and LoadFilteredPolicy

### ISSUE THREAD

**Issue by DarkSorrow** [casbin/casbin#560]
Hello,

I'm still trying to implement something with domains.
I've been using the domain pattern because i might have a lot of domains and wanted to have the right to create some superdomain.

I'm trying to use an adapter such as this one https://github.com/casbin/casbin-pg-adapter
So far it seems to work however it seems that casbin erase everything when you start a loadFilteredPolicy, the problem is that the user from the domain pattern get erased as well so each time i make a loadFilterPolicy i lose the super users but also on the higher picture, each time i will want to start a domain it means that my enforcer will lose the rights existing for all other domains.
Is there some better way to just load a subset of policies and keep them alive until refresh by a new loadFilter on the domain or is it something that would require some custom code on the adapter instead?

**Comment by hsluoyz** [comment]
@nodece @00LT00

**Comment by hsluoyz** [comment]
@DarkSorrow if this is the adapter issue, can you send the issue here instead? https://github.com/casbin/casbin-pg-adapter/issues

**Comment by DarkSorrow** [comment]
Well i was thinking about doing it on the adapter and checked most adapter but they all work a bit the same, they seems to erase previous value, i somehow thing that i can bypass this by making my own query and translation but i don't know if there would be some possibilities of having something in the core that erase the policyline filtered only instead of the whole policy line. Because in the end the filtered loading is a bit problematic if you plan to have multiple refresh on a domain and such.

But then maybe there is something that i don't see? My use case is having pattern domain matching that can be loaded and "reloaded" when changed by a client

**Comment by hsluoyz** [comment]
@DarkSorrow can you make a PR?

**Comment by wingdog** [comment]
I have the same issue and this is where clear policy happens:
https://github.com/casbin/casbin/blob/master/enforcer.go#L263

For me it seems to be more like a bug than a feature request.

**Comment by DarkSorrow** [comment]
@hsluoyz i'll try to put what i made but it's not well tested yet cause i'm on holidays xD. I kinda fork the repo tho because i'm using pgx for postgres but i should be able to isolate the code otherwise i'll just publish my adapter i suppose

But still i think it could be nice to have just a "clearFilteredPolicy" or something like that to remove only the filtered policy and keep the rest still in the enforcer :x do you think it's doable? I can try to take a look too maybe

**Comment by nodece** [comment]
@DarkSorrow  I think you want to keep old role_manager then load filtered data by call LoadFilteredPolicy.

Currently, most adapter just supports load the policy with pure domain, we cannot sure what you need when you are using domain pattern, it is quite complex, because casbin builds user role links at run time through the associated domain of pattern search, so I recommend you make own adapter.

**Comment by DarkSorrow** [comment]
@nodece but the thing is that i'm actually making my own adapter however casbin only seems to have this `persist.LoadPolicyLine(line.String(), model)`
And it seems that when this is called it erase the thing that are in the model the thing i lack is somehow link to the persist package because i need to just erase things filtered and add the refresh value but this doesn't seems to be possible in the adapter because the persisted part can only erase all and add no? Or maybe i'm missing something?

**Comment by nodece** [comment]
I remember now, If you want to keep role links, you can call `e.EnableAutoBuildRoleLinks(false)`, the Casbin doesn't clear role links, but Casbin will clear all policy.

look like: `e.EnableAutoBuildRoleLinks(false)` -> `e.LoadFilteredPolicy()` -> `e.EnableAutoBuildRoleLinks(true)`.

**Comment by DarkSorrow** [comment]
@nodece but it's not the roles the problem, it's the removal of all policies. In the use case i have i can have many domain being loaded at different time and changed as well, each time a domain is loaded it erase all policies, the code uses policies to manage rights and not just role. In the solution you are giving me there is no more use for policies

What i'm trying to do is to have domain being loaded on use and refresh at some point. There could be millions of domain and each domain have their own set of policies. Because of the amount and the fact that people could be refreshing their domain policies often, reloading all policies on all apps often will be too heavy.
Another solution i'm thinking of is to have a lot of enforcers and somehow recreate a model per domain but i think the overhead on creation is kinda heavy too. 
Tho in my use case the more simple solution i'm thinking is to have functions that does erase the persisted data for the enforcer and that can help manage it by removing domain and adding domain only

**Comment by DarkSorrow** [comment]
Actually my question would be, is it possible to have a flag preventing the call to loadFilteredPolicy to erase all existing policies
And a function allowing to remove a specific domain policy from the persisted policy?

**Comment by nodece** [comment]
I realized the problem, if we can provides append policy is best way. Casbin provides ManagerAPI to remove specific domain.

@DarkSorrow  Do you have any ideas? we most welcome contribution.

**Comment by DarkSorrow** [comment]
@nodece I think it would be nice to have an appendPolicy yes
Tho also, i think it would be good to have a flag a bit like the AutoSave that actually make the `e.model.ClearPolicy()` be called when the filteredPolicy is called, something like `EnableFilteredAutoClean()`.
Then from what i'm seeing there is already a RemovedFilteredPolicy so i'm thinking we are already suppose to be able to remove only a specific domain policy no? if we can call a removedFilterPolicy in the appendFilterPolicy it could be a good solution to "reload" partial policies when needed what do you think?

And i'd be happy to try to contribute to some part of it

**Comment by nodece** [comment]
@DarkSorrow Do you mean to remove specific domain policy in appendFilterPolicy? Casbin cannot sure what data.

**Comment by DarkSorrow** [comment]
@nodece i'm thinking that this `func (model Model) RemoveFilteredPolicy` which is there https://github.com/casbin/casbin/blob/master/model/policy.go#L177 is actually all is needed to remove the policies from the persistent data before loading the "fresh" policy for that domain. I mean in order to keep data consistent when you make an AppendFiltteredPolicy the steps would be
Remove the filtered data (a bit like the ClearPolicy)
Append the filtered data by using the https://github.com/casbin/casbin/blob/master/enforcer.go#L262 but without the ClearPolicy (it's replaced by the RemoveFilteredPolicy)

I'm not sure if you see what i mean :D

**Comment by nodece** [comment]
sounds good,  could you make the PR? @DarkSorrow

**Comment by DarkSorrow** [comment]
Well i'm checking a bit how to implement it but i kinda don't know if it works well with how the adapter and policies are built, the removedFilter seems to actually part of adapters so i guess it shouldn't be implemented in the enforcer code and actually since the variables seems to have to be declared in adapter the same way the filter object works i think i can't really add them as i was planning to do =/

Maybe i should start with only the second approach which consist of having a new flag to allow policies to not be "cleared" before a load filter is called and leave a removeFilter be called by the one implementing their adapter?

**Comment by hsluoyz** [comment]
@DarkSorrow can you add the new API LoadIncrementalFilteredPolicy() to our docs?

/cc @closetool

**Comment by hsluoyz** [comment]
@closetool we can do following:

1. Add it after: https://casbin.org/docs/en/management-api#loadfilteredpolicy
2. Add its description to this page: https://casbin.org/docs/en/policy-subset-loading
