### ISSUE TITLE
Repo weekly advertising (RVA) plan

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin#561]
To better advertise each Casbin project, every student should write & send out a post to a related forum/community to advertise the project repo that he/she is working on each week.

Some good places I know (but not limited to):

- https://www.reddit.com/
- https://news.ycombinator.com/
- https://www.v2ex.com/
...

This task can be done before your weekly report. Please remember to attach the URL link of your post in your weekly report.

Please note:

1. Send to the sub-forum with the correct language (e.g., Go, Java).
2. Either English or non-English (e.g., your mother language) would be OK.
3. Send to a place with high exposure. Do not send to your personal website or personal blog which has only limited followers.
4. Either write your own words or piece together from Internet. Both are OK.
5. At least one post is required for every week.

**Comment by hsluoyz** [comment]
GSoC students: @hackerchai @divy9881 @kingiw 

Summer2020 students: @00LT00 @kocoler @dovics @PsiACE @ZipoChan @tldyl @Xhy-5000 @yk17310320725 @zhmushan @Sagilio @438561537 @yahoo17

**Comment by hackerchai** [comment]
https://www.v2ex.com/t/703209
Here is the Casbin-RS advertising post in V2EX community.
