### ISSUE TITLE
get implicit permissions for a user per domain is not working for me, maybe my policies are wrong?

### ISSUE THREAD

**Issue by sumia01** [casbin/casbin#563]
Hi, 

I need some help.
I have an RBAC model with object hierarchy.
The enforcer works fine, the rules are applied and the result is correct.

But I can't get implicit permissions for a user per domain (team in my case).

The goal of this model and policies: 
- there are teams, 
- teams have custom permission groups (team_owner in team1 and admin in team2)
- users are in this permission groups
- I want to order permissions (g2) in a hierarchy
- I want to allow users to access multiple teams with different role groups (it's a nice to have if I can add users to specific permission `p, user1, 2, message, allow` for example)

Model:
```go
	m.AddDef("r", "r", "subject, team, object, action")
	m.AddDef("p", "p", "subject, team, object, action")
	m.AddDef("g", "g", "_, _, _")
	m.AddDef("g", "g2", "_, _")
	m.AddDef("e", "e", "some(where (p.eft == allow))")
	m.AddDef("m", "m", "g(r.subject, p.subject, r.team) && "+
		"g2(r.object, p.object) && "+
		"r.team == p.team && "+
		"r.action == p.action")
```

policy: 
```csv
    p, team_owner, 1, team, allow
    p, admin, 2, team, allow
    p, user1, 2, message, allow

    g, user1, team_owner, 1
    g, user2, admin, 2


    g2, app, team
    g2, message, app

    g2, team/create, team
    g2, team/read, team
    g2, team/update, team
    g2, team/delete, team

    g2, app/create, app
    g2, app/read, app
    g2, app/update, app
    g2, app/delete, app

    g2, message/create, message
    g2, message/read, message
    g2, message/update, message
    g2, message/delete, message
```

example request with correct result: 
```go
    // request
    _, _ = e.Enforce("user1", "1", "app/delete", "allow")
    _, _ = e.Enforce("user1", "1", "message/delete", "allow")

    _, _ = e.Enforce("user1", "2", "app/delete", "allow")
    _, _ = e.Enforce("user1", "2", "message/delete", "allow")
    _, _ = e.Enforce("user1", "2", "team/delete", "allow")
    _, _ = e.Enforce("user1", "2", "team/read", "allow")
    _, _ = e.Enforce("user1", "1", "team/delete", "allow")

    _, _ = e.Enforce("user2", "2", "app/delete", "allow")
    _, _ = e.Enforce("user2", "2", "team/read", "allow")
    _, _ = e.Enforce("user2", "1", "team/read", "allow")
    _, _ = e.Enforce("user2", "1", "team/update", "allow")

    // result for request: 
    2020/08/12 09:22:54 Request: user1, 1, app/delete, allow ---> true
    2020/08/12 09:22:54 Request: user1, 1, message/delete, allow ---> false

    2020/08/12 09:22:54 Request: user1, 2, app/delete, allow ---> true
    2020/08/12 09:22:54 Request: user1, 2, message/delete, allow ---> true
    2020/08/12 09:22:54 Request: user1, 2, team/delete, allow ---> false
    2020/08/12 09:22:54 Request: user1, 2, team/read, allow ---> false
    2020/08/12 09:22:54 Request: user1, 1, team/delete, allow ---> true

    2020/08/12 09:22:54 Request: user2, 2, app/delete, allow ---> true
    2020/08/12 09:22:54 Request: user2, 2, team/read, allow ---> true
    2020/08/12 09:22:54 Request: user2, 1, team/read, allow ---> false
    2020/08/12 09:22:54 Request: user2, 1, team/update, allow ---> false

```

Actual result: 
```
r, _ := e.GetImplicitPermissionsForUser("user1", "1", "2")
// 2020/08/12 09:17:31 GetImplicitPermissionsForUser:  []
```

expected result: 
```
r, _ := e.GetImplicitPermissionsForUser("user1", "1", "2")
// 2020/08/12 09:17:31 GetImplicitPermissionsForUser:  [
    [user1 1 team/create]
    [user1 1 team/read]
    [user1 1 team/update]
    [user1 1 team/delete]
    [user1 1 app/create]
    [user1 1 app/read]
    [user1 1 app/update]
    [user1 1 app/delete]
    [user1 1 message/create]
    [user1 1 message/read]
    [user1 1 message/update]
    [user1 1 message/delete]
    [user1 2 message/create]
    [user1 2 message/read]
    [user1 2 message/update]
    [user1 2 message/delete]
]
```

I expect this result because user1 is team_owner in team 1 and has permission to message object in team2. Team_owner has permission to team, app < team, message < app.

The result of the above code is correct, but I can't get implicit permissions per user.

**Comment by hsluoyz** [comment]
@nodece @GopherJ @dovics @00LT00

**Comment by hawle** [comment]
+1 I would also like to know that. Have a similar problem with GetImplicitPermissionsForUser

**Comment by nodece** [comment]
@sumia01 You ignore return value of `e. GetImplicitPermissionsForUser`.

**Comment by sumia01** [comment]
true, it's my bad, sorr. The error said: domain should be 1 parameter.
the function param (domain ...string) confused me, but I see now in the source code. 

So `e.GetImplicitPermissionsForUser("user1", "1")` returns 
`2020/08/12 14:05:37 GetImplicitPermissionsForUser:  [[team_owner 1 team allow]]`

It means this func can't return every permission what belongs to team_owner? 
`p, team_owner, 1, team, allow`
```
  g2, app, team
    g2, message, app

    g2, team/create, team
    g2, team/read, team
    g2, team/update, team
    g2, team/delete, team
...
...
```

Can I somehow get this information?

**Comment by nodece** [comment]
:( maybe you can get these information by `e.GetFilteredNamedGroupingPolicy("g2",1,"team")`.  

@hsluoyz Could you give @sumia01 more information?

**Comment by hsluoyz** [comment]
Currently, `GetImplicitPermissionsForUser()` get only get the permissions directly assigned to a user or or implicitly assigned to the user via a role. It has no knowledge about the matcher (your matcher is kind of complex) and cannot query out all the permissions that fulfilled the matcher.

We definitely need to improve on this part. @00LT00 can you work on it?

**Comment by sumia01** [comment]
@nodece thanks for your help & answers
@hsluoyz thanks for your answer, I'll follow this issue

**Comment by hsluoyz** [comment]
Closed here. Stay tuned at: https://github.com/casbin/casbin/issues/617
