### ISSUE TITLE
SyncedEnforcer missing functions & CachedEnforcer should overload functions to clear cache

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin#568]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%241%20Funded-%2300A156.svg" />](https://issuehunt.io/r/casbin/casbin/issues/568)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $1.00)

- [<img src='https://avatars0.githubusercontent.com/u/3787410?v=4' alt='hsluoyz' width=24 height=24> hsluoyz](https://issuehunt.io/u/hsluoyz) ($1.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/casbin/casbin/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by GopherJ** [comment]
If we compare `enforcer_synced.go` with `enforcer_interface.go`, there are couple of functions missing, that means those functions may cause thread safety problems


CachedEnforcer currently don't clear cache automatically, we should overload functions

**Comment by GopherJ** [comment]
Example: https://github.com/casbin/casbin-cpp/pull/61

**Comment by dschmidt** [comment]
`CasbinJsGetPermissionForUser(...)` accepts only `*Enforcer`, it would be cool to be able to pass a `*SyncedEnforcer` to it.
For that at least `GetImplicitPermissionsForUser(...)` is missing in the `SyncedEnforcer`.

**Comment by hsluoyz** [comment]
@00LT00 can you fix this issue?

/cc @nodece

**Comment by 00LT00** [comment]
@hsluoyz @dschmidt  plz review #605

**Comment by 00LT00** [comment]
@hsluoyz @nodece @dschmidt  Plz review #607 and #608

**Comment by dschmidt** [comment]
> @hsluoyz @nodece @dschmidt Plz review #607 and #608

commented on #607, no idea about #608 :)

**Comment by hsluoyz** [comment]
@00LT00 congrats! Please claim your $1 funding at: https://issuehunt.io/r/casbin/casbin/issues/568
