### ISSUE TITLE
how many QPS does casbin support?

### ISSUE THREAD

**Issue by andyyumiao** [casbin/casbin#569]
I need a performance metric, how many QPS does casbin support？

**Comment by nodece** [comment]
I plan add go-metrics to casbin. what do you think ? @andyyumiao

**Comment by hsluoyz** [comment]
@andyyumiao we have a benchmark here: https://casbin.org/docs/en/benchmark

And Casbin for different languages have different performances. I don't have concrete numbers for all languages. But generally speaking, we can have:

```
C++ > Rust > Go > Java = .NET > Node.js = PHP > Python
```

Maybe we need to have a performance ranking for all Casbins. Please show your numbers here.

Java: @tldyl 
C++: @divy9881 
Node.js: @nodece @zhmushan
PHP: @techoner @yk17310320725
Python: @techoner @Xhy-5000 
.NET: @huazhikui @sagilio
Rust: @GopherJ @hackerchai @PsiACE 

Do you agree with the above ranking?

**Comment by hackerchai** [comment]
> @andyyumiao we have a benchmark here: https://casbin.org/docs/en/benchmark
> 
> And Casbin for different languages have different performances. I don't have concrete numbers for all languages. But generally speaking, we can have:
> 
> ```
> C++ > Rust > Go > Java = .NET > Node.js = PHP > Python
> ```
> 
> Maybe we need to have a performance ranking for all Casbins. Please show your numbers here.
> 
> Java: @tldyl 
> C++: @divy9881 
> Node.js: @nodece @zhmushan
> PHP: @techoner @yk17310320725
> Python: @techoner @Xhy-5000 
> .NET: @huazhikui @sagilio
> Rust: @GopherJ @hackerchai @PsiACE 
> 
> Do you agree with the above ranking?

@hsluoyz Agree with that. I will supply a casbin-rs wrk performance test below.

**Comment by divy9881** [comment]
Currently, casbin-cpp is going through a huge change, as we are changing the method interface to the constructor interface, it would be wise if we set-up the benchmark pipeline and get the benchmark, after making this changes.

**Comment by GopherJ** [comment]
casbin-rs's current benchmark on i7-10gen, 8 cores

```
running 15 tests
test b_benchmark_abac_model               ... bench:       4,381 ns/iter (+/- 61)
test b_benchmark_basic_model              ... bench:       4,327 ns/iter (+/- 233)
test b_benchmark_key_match                ... bench:      18,583 ns/iter (+/- 7,579)
test b_benchmark_priority_model           ... bench:       5,378 ns/iter (+/- 249)
test b_benchmark_raw                      ... bench:           5 ns/iter (+/- 0)
test b_benchmark_rbac_model               ... bench:       7,369 ns/iter (+/- 247)
test b_benchmark_rbac_model_large         ... bench:  11,039,315 ns/iter (+/- 2,280,984)
test b_benchmark_rbac_model_medium        ... bench:   1,121,222 ns/iter (+/- 86,155)
test b_benchmark_rbac_model_small         ... bench:     103,212 ns/iter (+/- 12,020)
test b_benchmark_rbac_model_with_domains  ... bench:       7,565 ns/iter (+/- 253)
test b_benchmark_rbac_with_deny           ... bench:      10,967 ns/iter (+/- 477)
test b_benchmark_rbac_with_resource_roles ... bench:       5,698 ns/iter (+/- 252)
test b_benchmark_role_manager_large       ... bench:   3,325,519 ns/iter (+/- 882,779)
test b_benchmark_role_manager_medium      ... bench:     294,008 ns/iter (+/- 4,367)
test b_benchmark_role_manager_small       ... bench:      33,076 ns/iter (+/- 797)
```

**Comment by andyyumiao** [comment]
How dare you open source such projects? You are advised to close the source, because you have a waste leader @hsluoyz 
 who resists opinions and resists proposals，get out of GitHub!!!

**Comment by GopherJ** [comment]
@andyyumiao It's not opinions OR proposals, you were flooding us with junk issues. You should be ashamed!

The other open source projects will just add you into blacklist without wasting time to talk to you.
