### ISSUE TITLE
support user role authority resource model

### ISSUE THREAD

**Issue by aisq2008** [casbin/casbin#57]
If you know the java web framework spring,then you must know spring have a module named spring security, the spring security has four concepts as below:

1. user -> the people of web's visitors.

2. role -> roles are associate with users and authorities. User and role have the  relation of many-many.

3. authority -> authorities are associate with  roles and resources. Role and authority also have the relation of many-many.

4. resource -> resource could be URLs in web project, one URL always mean one web request. Authority and resource have the relation of many-many.

In the spring security ,if an user want to  access an URL, then the user must have been associate with a role, and the role have been associate with an authority,and the authority  must have been associate with the resource(the request URL).

the relation as below:
```
user>role>authority>resource
```

in  simple terms, an user visits a web page ,then the system(web system) check whether the user can access the system by the authority. If the user have the authority ,the user must have the right role . 

I don't know whether casbin could implement the functions as below that what i want:

1. an user visit a web page ,then the system could control whether user can access by the user's authority.
2. an user visit a web page ,the page contains some URL that associate with authority,if the user don't have the authority,then the URL couldn't visible. 

If casbin can implement the functions,some body could give a complete example with a web project,thank you!

**Comment by hsluoyz** [comment]
Casbin supports RBAC model with role hierarchy. You can view 1st level roles as role and 2nd level roles as authority.

The examples for a web service are here: https://github.com/casbin/casbin#others. Pay more attention to the ``Intel RMD`` example and their policy rules.

**Comment by aisq2008** [comment]
sorry,i still don't know how does casbin work with user role authority resource model,could you give an example?

**Comment by hsluoyz** [comment]
The basic [RBAC](https://github.com/casbin/casbin#examples) model works with your scenario. You can see the model file and policy file in the above link. The content of the model file is:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

The policy file can be:

```csv
p, authority1, resource1, read
p, authority2, resource2, read
p, authority2, resource2, write

g, alice, role1
g, bob, role2

g, role1, authority1
g, role2, authority2
```

This policy means:
```
alice -> role1 -> authority1 -> resource1
bob-> role2 -> authority2 -> resource2
```

**Comment by hsluoyz** [comment]
Suppose it has been solved.
