### ISSUE TITLE
Is there HTTP service support？

### ISSUE THREAD

**Issue by andyyumiao** [casbin/casbin#570]
Is there an HTTP interface in casbin? I mean most production environments may access centralized services through HTTP, so it's language independent.

**Comment by hsluoyz** [comment]
See Casbin services: https://casbin.org/docs/en/service

**Comment by andyyumiao** [comment]
> https://casbin.org/docs/en/service

the url cann't be open...   should i use http proxy?

**Comment by hsluoyz** [comment]
It's hosted in GitHub pages. Maybe you need to use a proxy. Or run it on localhost: https://github.com/casbin/casbin-website
