### ISSUE TITLE
 Is there a detailed HTTP service?

### ISSUE THREAD

**Issue by andyyumiao** [casbin/casbin#572]
I can't find what I need through these places:
https://casbin.org/docs/en/service
https://github.com/casbin/casbin-server
https://github.com/paysuper/casbin-server

And some of my questions are：
1.How can I update the policy through the HTTP interface? 
2.How to update model through HTTP interface? 
3.Where is the API for verifying permissions(I mean HTTP interface)?
4.Do I need to implement it myself, or if there are detailed HTTP interface documents, can you provide them?

**Comment by hsluoyz** [comment]
Please send issue at: https://github.com/casbin/casbin-server
