### ISSUE TITLE
How to build global permission system

### ISSUE THREAD

**Issue by andyyumiao** [casbin/casbin#574]
If i want to build a company level permission system, how to use caspin? How to isolate authority policies and rules of different business parties? I mean, we have to connect all the departments of the whole company

**Comment by hsluoyz** [comment]
Use `RBAC with domains` model: https://casbin.org/docs/en/rbac-with-domains

**Comment by andyyumiao** [comment]
> Use `RBAC with domains` model: https://casbin.org/docs/en/rbac-with-domains

Can ABAC model support this？

**Comment by hsluoyz** [comment]
Closed as not being specific.
