### ISSUE TITLE
[Bug]RBAC Verification incorrect

### ISSUE THREAD

**Issue by andyyumiao** [casbin/casbin#575]
**model.conf:**
[role_definition]
g = _, _

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act

**policy.csv:**
p, data2_admin, data2, read
g, alice, data2_admin

**test function：**
package main

import (
	"fmt"

	"github.com/casbin/casbin/v2"
)

func check(e *casbin.Enforcer, sub, obj, act string) {
	ok, _ := e.Enforce(sub, obj, act)
	if ok {
		fmt.Printf("%s CAN %s %s\n", sub, act, obj)
	} else {
		fmt.Printf("%s CANNOT %s %s\n", sub, act, obj)
	}
}

func main() {
	e, _ := casbin.NewEnforcer("./model.conf", "./policy.csv")

	check(e, "alice", "data2", "read")
}

**But i got：**
alice CANNOT read data2

**Comment by vtolstov** [comment]
firstly try to not ignore error from Enforce because ok have reasonable value if err is nil

**Comment by andyyumiao** [comment]
> firstly try to not ignore error from Enforce because ok have reasonable value if err is nil

thanks for the reply, and i just printed the error, should you take a look it?
**panic: runtime error: invalid memory address or nil pointer dereference**

**Comment by vtolstov** [comment]
you need to get full backtrace

**Comment by andyyumiao** [comment]
> you need to get full backtrace

panic: panic: runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
main.check(0x0, 0x117f50e, 0x5, 0x117f531, 0x5, 0x117f3f7, 0x4)
	/Users/wl/workspace/casbindemo/1stACL.go:11 +0x1a0
main.main()
	/Users/wl/workspace/casbindemo/1stACL.go:23 +0xc4

**Comment by vtolstov** [comment]
i think that you check func receives nil in e variable (*casbin.Enforcer)

**Comment by andyyumiao** [comment]
> i think that you check func receives nil in e variable (*casbin.Enforcer)

yes it's a nil,  many thanks!!!

**Comment by andyyumiao** [comment]
thanks @vtolstov
