### ISSUE TITLE
how to create/modify model files dynamically in the database?

### ISSUE THREAD

**Issue by andyyumiao** [casbin/casbin#576]
We all know that policy files can be created dynamically in the database, but how to create or modify new model files dynamically in the database?

**Comment by hsluoyz** [comment]
We only support these ways: https://casbin.org/docs/en/model-storage

Model is just a string. And you can simply store it into DB in your own way.

**Comment by andyyumiao** [comment]
> https://casbin.org/docs/en/model-storage

But for ABAC model, for example, how to dynamically modify the matcher for different business parties? this requirement may come from different business parties. I mean, I want to build a unified permission system

[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[matchers]
m = r.sub.Hour >= 9 && r.sub.Hour < 18 || r.sub.Name == r.obj.Owner

[policy_effect]
e = some(where (p.eft == allow))

**Comment by hsluoyz** [comment]
See Casbin-Server
