### ISSUE TITLE
[Bug] Pattern matching in RBAC not working

### ISSUE THREAD

**Issue by afdecastro879** [casbin/casbin#577]
**Describe the bug**
I'm using pattern matching with RBAC but seems like it's not working as expected. I'm following https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac

I'm using casbin V2

**To Reproduce**

**rbac_model.conf**
```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**rbac_policy.csv**
```
p, reader, /some/path/a/*, read
g, alice, reader
```

main.go
```go
package main

import (
	"fmt"
	"github.com/casbin/casbin/v2"
	defaultrolemanager "github.com/casbin/casbin/v2/rbac/default-role-manager"
	"github.com/casbin/casbin/v2/util"
)

func main() {
	e, _ := casbin.NewEnforcer("./rbac_model.conf", "rbac_policy.csv")
	e.GetRoleManager().(*defaultrolemanager.RoleManager).AddMatchingFunc("keyMatch", util.KeyMatch)
	ok, err := e.Enforce("alice", "/some/path/a", "read")
	fmt.Println(ok, err)
	ok, err = e.Enforce("alice", "/some/path/a/something", "read")
	fmt.Println(ok, err)
}
```

The result of running this sript is:
```
false <nil>
false <nil>
```

**Expected behavior**
I would expect both permission checks to be true as `/some/path/a` and `/some/path/a/something` match the policy `/some/path/a/*`

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Golang version: go version go1.14.4 darwin/amd64

**Comment by GopherJ** [comment]
@afdecastro879 I think you are mixing `pattern matching` in role manager with custom functions.

Basically what you want is to put  a groupt of **object** in the same group. In this case you should use custom functions by editing your `rbac_model.conf`:

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && r.act == p.act
```
