### ISSUE TITLE
Aboud casbin-dashboard and casbin-server

### ISSUE THREAD

**Issue by andyyumiao** [casbin/casbin#578]
What is the relationship between these projects? 
https://github.com/casbin/casbin
https://github.com/casbin/casbin-dashboard
https://github.com/casbin/casbin-server
https://github.com/paysuper/casbin-server

casbin-dashboard and casbin-server seems not stable, or do I have other options? For casbin-dashboard and casbin-server

**Comment by hsluoyz** [comment]
Closed as not being specific.
