### ISSUE TITLE
how can ABAC model implement multi tenant isolation？

### ISSUE THREAD

**Issue by andyyumiao** [casbin/casbin#580]
1.how can ABAC model implement multi tenant isolation？
2.how can ABAC model support adding and modifying matchers dynamically？This is because we usually add a lot of rules in complex business scenarios

**Comment by hsluoyz** [comment]
Closed as not being specific.

**Comment by andyyumiao** [comment]
> Closed as not being specific.

Why close the post, is the description not clear？

**Comment by hsluoyz** [comment]
Please stop spamming issues in the project. Please look at the docs first and raise valuable and specific questions. Ideally, please only raise 1 or 2 issues totally in all Casbin repos.

**Comment by andyyumiao** [comment]
> Please stop spamming issues in the project. Please look at the docs first and raise valuable and specific questions.
> 
> Ideally, please only raise 1 or 2 issues totally in all Casbin repos per day.
> 
> Currently, you are sending > 10 issues in just a few hours.

These problems are not the same. Is this how you do open source projects? Garbage Project！！！bye
