### ISSUE TITLE
[Feature] Log actions, AddPolicy, RemovePolicy ...

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin#581]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when casbin golang cannot have a clear and concise log on what's happening on the following events

- Enforce
- AddPolicy
- RemovePolicy
- AddPolicies
- RemovePolicies
- RemoveFilteredPolicy
- ClearCache

Currently this is possible with `watcher` but users need to implement their own logger, the built in logger doesn't support

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casbin/pull/591
