### ISSUE TITLE
[Feature] Add the "UpdatePolicy()" API to update a single policy rule

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin#584]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

Currently, we recommend the users to remove and then add a policy for updating. There are two drawbacks:

1. Performance for two operations: add & remove is low.
2. The order of policy will be changed.

We need to add a new API called `UpdatePolicy()` to allow modifying an existing policy.

**Comment by hsluoyz** [comment]
@nodece @GopherJ @00LT00 can anyone take this issue?

**Comment by pokid** [comment]
i  usually check if policy existed  before i add or del policy,if existed,i won‘t do that operation.
but when i try to use add & remove to update policy , the result of getting policy for role in domain is different before del and after del,i feel confused about this.
to resolve this,i hava to keep the result of getting policy for role in domain before del,and transmit this result to add operation,it makes my code readability pool.
i think it's autobuildlink delay after my code

if has a update method, i will makes my code very easy

**Comment by 00LT00** [comment]
yeah, we will add `UpdatePolicy()` . But it is a break change. So it will be merged late. I think you can refer to #592  to add this function yourself. @pokid

**Comment by hsluoyz** [comment]
@00LT00 why is `UpdatePolicy()` a breaking change? We can first make it an optional function in the interface, like add and remove.
