### ISSUE TITLE
[Question] Implement RBAC with domain + resource policies the most efficient way

### ISSUE THREAD

**Issue by Gaadek** [casbin/casbin#585]
**My scenario**

I'm designing a file storage system (similar to a FTP) and I'm looking for the best option to design my security with Casbin

I have several `servers`, each containing `folders`, themselves storing `files`.
In parallel, I have a pool of `users`.

A `server` is a root element on which `user` role is defined:  a `user` can have 1 and only 1 role for a given `server` (e.g. `alice` is `admin` of `server_01` and `user` of `server_02`)

In a `server`, each `folder` has got its own security policy (i.e. `users` of `server_01` does not have full access to all `folders` of this `server`). I have to specify `policy` to grant `users` with appropriate `rights` for a `folder`.

Furthermore, some `permissions` are denied for some profiles: a `user` should never be able to perform `admin` tasks, even if it's explicitly given by mistake.

To complicate the things, we should be able to disable `users` or `resources` (`server` or `folder`) to deny access

Eventually, I want a direct file grant option (e.g. for `audit` purpose)

That's quite complex, but I already found a lot of ideas! 

**Test cases**
- `alice` has got `user` role on `server_01` + `read` right on `folder_01`
- `alice` has got `user` role on `server_01` + `read` right on `folder_02`
- `folder_02` of `server_01` is `disabled`
- `alice` has got `admin` role on `server_02` + `manage` for all folders
- `bob` has got `user` role on  `server_01` + `write` right on `folder_01` (of `server_01`)
- `bob` has got `user` role on  `server_02` + `write` right on `folder_01` (of `server_02`)
- `carla` has got `user` role on `server_01` + `read` right on `folder_01`
- `carla` has got `disabled` role on `server_01`
- `david` has got grant to `server_01`/`folder_01`/file_01` with `read`

**My model:**

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act, eft

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.sub, p.sub, r.dom) && keyMatch(r.dom, p.dom) && keyMatch(r.obj, p.obj) && keyMatch(r.act, p.act)
```

Explanations:
- I'm using a RBAC with domain model (the domain is my `server`)
- I'm using a deny-override policy effect because that fit perfectly my needs: I can disable users easily (with the `disabled` group) and if someone applies a right that user role should not accept, the most restrictive policy applies, which is what I expect.
- I'm also using KeyMatch in order to reduce the number of policies (I can disable all domains/resources with 1 policy)

**My policy:**

```
p, disabled, *, *, *, deny
p, user, *, *, manage, deny
p, admin, *, *, read, deny
p, admin, *, *, write, deny

g, alice, user, server_01
p, alice, server_01, folder_01/*, read
p, alice, server_01, folder_02/*, read

g, alice, admin, server_02
p, alice, server_02, *, manage

g, bob, user, server_01
p, bob, server_01, folder_01/*, write

g, bob, user, server_02
p, bob, server_02, folder_01/*, write

g, carla, user, server_01
p, carla, server_01, folder_01/*, read
g, carla, disabled, server_01

p, david, server_01, folder_01/file_01, read
```

**My requests:**

```
alice, server_01, folder_01/*, read ---> true (expected: true)
alice, server_01, folder_01/abcd, read ---> true (expected: true)
alice, server_01, folder_01/*, manage ---> false (expected: false)
alice, server_01, folder_02/*, read ---> true (expected: false; but normal cause I don't know how to disable resources)

bob, server_01, folder_01/a, write ---> true (expected: true)
bob, server_01, folder_01/a, read ---> false (expected: false)

carla, folder_01, cont_01/*, read ---> false (expected: false)

david, server_01, folder_01/file_01, read ---> true (excepted: true)
david, server_01, folder_01/file_02, read ---> false (excepted: false)
david, server_01, folder_01/file_01, write ---> false (excepted: false)
```

**My questions:**
- Is there any way to use Casbin to manage the resources rights? I saw there is the possibility to use g2, but I have no idea on how to use it in my case
- Do you think I have the good approach? It seems I'm mixing up groups/permissions for my users, and I'm wondering if my model is OK for waht I want to achieve

Thanks for your help!

**Comment by hsluoyz** [comment]
@nodece @GopherJ @00LT00

**Comment by Gaadek** [comment]
Hi, after some days working on this topic, I think my approach is not the good one.
I now believe the resources should not be disabled, I should use the permissions to manage that.

Furthermore, I realize my problem comes from probably from some kind of misunderstanding of the various models and in which cases I can apply them or not. Do you have a good resources to get some training on that (in English if possible?)

I think we can close this issue

**Comment by hsluoyz** [comment]
Sorry that none of our contributors have answered this question. Actually this question is long and tailored for your scenario instead of a question directly pointing to Casbin bugs or features. If you still expect an answer, I personally suggest this: https://github.com/casbin/casbin/issues/567
