### ISSUE TITLE
[Question] Get roles for user with matcher_functions in the role_definition

### ISSUE THREAD

**Issue by PhilippSeitz** [casbin/casbin#588]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Hi, i want to apply a preset of policies to all my groups like in the model below, which works pretty nice on enforcing the policies. But now i am facing the issue, that I can't tell which permissions a user has across multiple objects.

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.sub, p.sub, r.obj) && keyMatch(r.obj, p.obj) && r.act == p.act
```

**Your policy:**

```
p, owner, *, write
p, member, *, read

g, alice, owner, data1
g, alice, owner, data2
g, bob, member, data1
```

**Your request(s):**

```
enforcer.GetRolesForUser("alice") => [] (expected: [ ["data1", "owner"], ["data2", "owner"] ]
enforcer.GetRolesForUser("alice", "data1") => ["owner"] which is the expected

```
Is this somehow possible with the default role manager, or by creating a custom role manager?

**Comment by hsluoyz** [comment]
@PhilippSeitz you can call `GetImplicitPermissionsForUser()`.

**Comment by PhilippSeitz** [comment]
@hsluoyz for this i need to pass the domain. But i want to get all permissions across `domains` (not really used as domains here)

**Comment by hsluoyz** [comment]
@nodece @00LT00

**Comment by 00LT00** [comment]
May be we need a func to get roles, whether domain is used or not ?

**Comment by hsluoyz** [comment]
@00LT00 please add `GetImplicitPermissionsForUserForAllDomains()`

**Comment by PhilippSeitz** [comment]
@hsluoyz but it seems like the `GetImplicitPermissionsForUser()`  does use the keymatcher while filtering the policies.

```
enforcer.GetImplicitPermissionsForUser(alice, data1) == [] 
```

i would expect it to equal `[["owner", "data1", "write" ], ["owner", "data1", "read" ]`.
Because `Enforce(alice, data1, read)` does return `true`. 

Maybe we can add the possibility to intercept the matching here, by a custom matcher:
https://github.com/casbin/casbin/blob/c730e2689d1f9e60206fbe30f0995d48899b6760/model/policy.go#L93

**Comment by 00LT00** [comment]
@PhilippSeitz Hi, does it meets your requirement?

**Comment by hsluoyz** [comment]
@00LT00 does this PR: https://github.com/casbin/casbin/pull/612 consider the matcher expression like `keyMatch()` in it?

**Comment by PhilippSeitz** [comment]
@hsluoyz @00LT00 First of all thank you for the quick responses. Unfortunately this does not seems to be the case https://github.com/casbin/casbin/pull/612#discussion_r495756036.

**Comment by 00LT00** [comment]
Now, this function was return the value of model(Policy.csv). In fact, member can read anythins. But it is determined during operation. `model[p][p]` wasn't have this permission.
If we need get this permission, we need the `e.model[p][p].RM` has default value.
Do you have any ideas? @nodece @hsluoyz

**Comment by hsluoyz** [comment]
`GetImplicitPermissionsForUser()` is a simplified version of batch enforce. It doesn't use the matcher as what enforce() does. Because we know, matcher is an expression actually. There's no way to know which permissions and user will make matcher hold.

Another way to solve it is to add a `batchEnforce()` function to allow enforce multiple elements (maybe users, or permissions) at the same time. `batchEnforce()` works like a filter to give you the final allowed permissions. Of course this requires to know an initial set of possible allowed permissions in advance. I don't know if this is possible for your scenario.

**Comment by PhilippSeitz** [comment]
@hsluoyz sounds good. `GetRolesForUserForAllDomains` is already a great help. With that i can get the permissions for each role.

**Comment by hsluoyz** [comment]
OK. Close this for now. Raised another issue about `batchEnforce()` API here: https://github.com/casbin/casbin/issues/617
