### ISSUE TITLE
Dynamic policy rules

### ISSUE THREAD

**Issue by pagesuite-github** [casbin/casbin#596]
We are creating a new administrative portal for our clients to manage resources within their account. Example resources in the account are publications, editions within that publication, and pages within an edition. There will also be many users in each client account. We would like to have granular control over all operations on all resources, down at the identifier level.

I thought this would be a good way to create policies, and add these policies to roles

```
p, publication-admin, publication:*, (create-edition)|(edit-edition)|(delete-edition)|(read-edition)
p, account-admin, account:*, (create-publication)|(delete-publication)

p, alice, publication:123456, (create-edition)|(edit-edition)|(delete-edition)|(read-edition)

g, john, account-admin
g, john, publication-admin
```

From the above, user Alice should be able to perform actions _create-edition, edit-edition, delete-edition,_ and _read-edition_ on publication with ID 123456, and user John should be able to perform those actions on all publications, as well as _create-publication_ and _delete-publication_ on all accounts.

The next hurdle is limiting her requests to only her account, without having to manually specify the IDs each time. I have looked into custom matching functions, and my solution was to extract accountID from the object, make a DB query to see if the user belongs to the same account as the accountID in the request, and if so return true.

This has been discussed here:
https://github.com/casbin/casbin/issues/33

This quote describes my needs perfectly:

> "I was wondering about this problem too. The issue is that we the route may be dynamic. For example, we may want a user to only be able to view his own purchases. Consider:
> 
> GET /orders/:id
> 
> We don't want non-owners retrieving arbitrary orders, so we must check if this order is owned by the requesting user based on his token.
> 
> If you use a file based policy, there is currently no way to protect such a route unless you literally fill in every user in your system. Either that, or authorise in the route handler, which in my opinion is a bad idea."

I was wondering if I am going in the right direction, or am I approaching this wrong? Any examples would be massively appreciated, as I'm having difficulty setting up the policy rules and groups correctly and I can't find any examples that fully apply to the needs of this situation.

Best Regards

**Comment by hsluoyz** [comment]
@pagesuite-github hi, what's your question specifically?

**Comment by pagesuite-github** [comment]
Thanks for getting back to me so soon :)

Would using a custom matching function to check the resource ID in the request object is owned by the user making the request be the correct way to enforce the dynamic route issue mentioned above? We don't want a user from one account requesting publication:123456, which (could) belong to another account. We need to check first that publication:123456 is in the users account before we let them access the resource, but with a wildcard that can't be done, and we don't want to manually specify each publication one policy at a time, as it's not scalable. 

The custom matching function would extract the resource and ID from the object (probably using RegEx), then make a DB query to find the account ID that owns the resource, and check that the user belongs to that account. Accounts with us can contain many users. Am I approaching this issue the right way, or is there a better way to do it?

This is my current matcher, which works in the way I would like, but does not check ownership:

`m = g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)`

What I would like I believe is this

`m = g(r.sub, p.sub) && userInAccount(r.sub, getAccountId(r.obj)) && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)`

Then the matching functions would be as follows:

function userInAccount(subject, accountId) {
          // find account ID from subject (user)
          // compare account IDs
          // return result
}

function getAccountId(requestObject) {
          // requestObject example: publication:123456
          // regex example: ^(<resource>.+):(<identifier>.+)$
          // query the DB on resource and identifier to find account ID it belongs to
          // return it
}

My idea here being that it will check the subject is in a role that can access this resource first (e.g. John, publication-admin), then check the subject has access to _this_ specific resource, then check they can perform such action upon the specified resource.

Any advice would be greatly appreciated, hopefully I'm on the right path!

**Comment by hsluoyz** [comment]
sub's account ID can be passed into matcher via request, like r.sub_account. Similar to obj's account ID: r.obj_account. Then in matcher, you can just compare: `r.sub_account == r.obj_account`. It looks better.

For RBAC, I don't know what you mean, but you can easily use it as:

```
p ,user_group             ,publication:123456 ,(create-edition)|(edit-edition)|(delete-edition)|(read-edition)

g, alice, user_group
```

**Comment by pagesuite-github** [comment]
Thanks again for the quick response and continued help!

The issue there is that we may not know the accountID for the resource at the point of the request. Take this example

`enforcer.enforce("alice", "publication:123456", "create-edition");`

At this point, we know Alice wants to create an edition for publication 123456, but we don't know which account that publication belongs to. To find this information, we would need to query a database. I suppose we could query it before we get to the _enforce()_ function call in the endpoint handler, and then take your approach, but it would be preferred if we could consolidate that logic into a Casbin custom matching function, then all enforcement comes from that single function call.

My other question is, how can I grant domain specific roles? In my above example, I'm creating a policy to allow Alice to access publication 123456. But I instead want to be able to say Alice is a publication-admin for a particular publication, without having to redefine new publication specific policies for her each time. If also then want to say shes an edition-admin for a particular account, at the moment that will require yet another custom policy, and when I use the RBAC API to pull out her list of roles, it wont appear because shes not in a role, just directly on a policy. This will make it difficult to present a users roles in the admin portal, as we will need to access all her roles so they can be shown to her.

This might make it clearer, although I'm not sure about how I would adjust the config to make it work:

`g, alice, 123456, publication-admin //gives admin access to publication 123456 within that account`
`g, john, *, publication-admin // gives admin access to all publications within that account`

Is the above approach something that could be achieved? Or is there a better way to implement it? I hope I'm explaining it well enough, if you don't understand let me know and I'll have another go!

**Comment by pagesuite-github** [comment]
Thanks again for the quick response and continued help!

The issue there is that we may not know the accountID for the resource at the point of the request. Take this example

enforcer.enforce("alice", "publication:123456", "create-edition");

At this point, we know Alice wants to create an edition for publication 123456, but we don't know which account that publication belongs to. To find this information, we would need to query a database. I suppose we could query it before we get to the enforce() function call in the endpoint handler, and then take your approach, but it would be preferred if we could consolidate that logic into a Casbin custom matching function, then all enforcement comes from that single function call.

My other question is, how can I grant domain specific roles? Consider your above example:

p ,user_group             ,publication:123456 ,(create-edition)|(edit-edition)|(delete-edition)|(read-edition)

g, alice, user_group
You are creating a policy to allow "user_group" access to access publication 123456. But I will then need to name the group "123456-publication-admin". But I instead want to be able to say Alice is a publication-admin for a particular publication, without having to redefine new publication specific policies each time.

If I also then want to say shes an edition-admin for a particular account, at the moment that will require yet another custom policy, and she will need adding to that policy via a role. This doesn't feel scalable, but perhaps I'm worrying too much.

This might make it clearer, although I'm not sure about how I would adjust the config to make it work:

g, alice, 123456, publication-admin //gives admin access to publication 123456 within that account
g, john, *, publication-admin // gives admin access to all publications within that account

For the administration/management side of these roles, I want to use the RBAC API to create endpoints to find roles for each user. I want to be able to see from that call something like this:

GET /users/alice/roles

"roles": [
    "publication-admin": {
        "resources": [
            "123456",
            // could be more than 1!
        ],
        "actions": [
            "create-edition",
            "edit-edition",
            "delete-edition",
            "read-edition"
        ]
    },
    "edition-admin": {
        "resources": "*",
        "actions": [
            "create-section",
            "edit-section",
            "delete-section",
            "read-section"
        ]
    }
]
This would allow me to easily present to the user via a webpage which roles they have, and what access that grants them to which resources.

Is the above approach something that could be achieved? Or is there a better way to implement it? I hope I'm explaining it well enough, if you don't understand let me know and I'll have another go!

**Comment by pagesuite-github** [comment]
Thanks again for the quick response and continued help!

The issue there is that we may not know the accountID for the resource at the point of the request. Take this example

`enforcer.enforce("alice", "publication:123456", "create-edition");`

At this point, we know Alice wants to create an edition for publication 123456, but we don't know which account that publication belongs to. To find this information, we would need to query a database. I suppose we could query it before we get to the _enforce()_ function call in the endpoint handler, and then take your approach, but it would be preferred if we could consolidate that logic into a Casbin custom matching function, then all enforcement comes from that single function call.

My other question is, how can I grant domain specific roles? Consider your above example:

```
p ,user_group             ,publication:123456 ,(create-edition)|(edit-edition)|(delete-edition)|(read-edition)

g, alice, user_group
```

You are creating a policy to allow "user_group" access to access publication 123456. But I will then need to name the group "123456-publication-admin". But I instead want to be able to say Alice is a publication-admin for a particular publication, without having to redefine new publication specific policies each time.

If I also then want to say shes an edition-admin for a particular account, at the moment that will require yet another custom policy, and she will need adding to that policy via a role. This doesn't feel scalable, but perhaps I'm worrying too much.

This might make it clearer, although I'm not sure about how I would adjust the config to make it work:

`g, alice, 123456, publication-admin //gives admin access to publication 123456 within that account`
`g, john, *, publication-admin // gives admin access to all publications within that account`

For the administration/management side of these roles, I want to use the RBAC API to create endpoints to find roles for each user. I want to be able to see from that call something like this:

```
GET /users/alice/roles

"roles": [
    "publication-admin": {
        "resources": [
            "123456",
            // could be more than 1!
        ],
        "actions": [
            "create-edition",
            "edit-edition",
            "delete-edition",
            "read-edition"
        ]
    },
    "edition-admin": {
        "resources": "*",
        "actions": [
            "create-section",
            "edit-section",
            "delete-section",
            "read-section"
        ]
    }
]
```

This would allow me to easily present to the user via a webpage which roles they have, and what access that grants them to which resources.

Is the above approach something that could be achieved? Or is there a better way to implement it? I hope I'm explaining it well enough, if you don't understand let me know and I'll have another go!

**Comment by pagesuite-github** [comment]
After playing around for a bit longer, I believe I am now close to having it setup correctly for our needs. I've added _"domain"_ to the request definition and the group role matcher:

Policy file:

```
p,  publication-admin,  publication,    (create-edition)|(edit-edition)|(delete-edition)|(read-edition)

g,  alice,  publication-admin,  *
g,  bob,    publication-admin,  3934bdcb-6f03-46bc-9084-d9aba1b6c0fb
```

Model file:

```
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = regexMatch(g(r.sub, p.sub, r.dom)) && r.obj == p.obj && regexMatch(r.act == p.act) 
```

This means the policy file reads logically, there is no need to redefine a policy each time to give users single-access privileges like before, we can simply add a user to the policy via a rule, specifying either "*" to give them access to all domains in that object.

So for example:

```
{
    "subject": "bob",
    "object": "publication",
    "domain": "3934bdcb-6f03-46bc-9084-d9aba1b6c0fb",
    "action": "create-edition"
}
```

This will match for "Bob" (as he is granted access to this _one_ domain in the publication object), and it will match for Alice as she is granted access to all domains in the publication object. If I wanted to add another user as a publication-admin for a single publication, I can simply now just add another role with the appropriate domain identifier.

My only issue is the NodeJS RBAC API is returning unexpected results from the _`getRolesForUser(user, domain)`_ function.

Code:
```
 const roles = await localEnforcer.getRolesForUser(subject, domain);
 console.log(`Roles:   ${roles}`);
```

Result:
```
[
    "*::alice",
    "*::publication-admin"
]
```

Is there a way I can define which subject string is a _"role"_, and which is a _"user"_, so only _"publication-admin"_ is returned in the above call?

**Comment by pagesuite-github** [comment]
Am I asking for something that Casbin doesn't support?

**Comment by hsluoyz** [comment]
@00LT00 

/cc @nodece

**Comment by 00LT00** [comment]
@pagesuite-github  Hi, I think you should understand to [use function](https://casbin.org/docs/en/function). The usage of `regexMatch(r.act == p.act)` is wrong.
You can try
Model:
```
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && keyMatch(r.dom , p.dom) && r.obj == p.obj && regexMatch(r.act , p.act)
```
Policy
```
p, admin, domain1, data1, (create)|(edit)|(delete)|(read)
p, admin, domain2, data2, (read)|(write)

g, alice, admin, *
g, bob, admin, domain2
```
And you need to register the `keyMatch` to casbin Enforcer

```go
	r := e.GetRoleManager()
	r.(*defaultrolemanager.RoleManager).AddDomainMatchingFunc("KeyMatch",util.KeyMatch)
```

Now, the `alice` can do anything as admin not limited by domains

**Comment by hsluoyz** [comment]
Closed as stale.
