### ISSUE TITLE
ABAC with policy rules using JSON

### ISSUE THREAD

**Issue by rillazoid72** [casbin/casbin#597]
Hi folks! 

I am wanting to implement ABAC with policy rules into my project but I need to use JSON or BSON. How can the policy rules be evaluated? Maybe something like json rule engine? For example, evaluating "r.sub.Age > 18" or "r.sub.Age < 60".

What methods have you seen using ABAC on JSON files?

[using golang, json/bson, mongodb]

**Comment by hsluoyz** [comment]
@rillazoid72 you can use the JSON adapter: https://github.com/casbin/json-adapter

It's on our adapter list: https://casbin.org/docs/en/adapters

**Comment by rillazoid72** [comment]
@hsluoyz My question is how do you use "r.sub.Age > 18" or "r.sub.Age < 60" in the JSON file?

A more in depth example would be:
{"PType":"p","V0": [What do I put here for JSON],"V1":"data1","V2":"read"}

I already know about the adapters, please re-open

**Comment by hsluoyz** [comment]
Can't write like this?

```json
{"PType":"p","V0": "r.sub.Age > 18","V1":"data1","V2":"read"}
```

**Comment by rillazoid72** [comment]
Hey @hsluoyz  thanks for your fast responses. The problem was coming from the mongodb side, casbin is working just fine. While I have your attention, what does "V0", "V1", "V2" come from, what does it mean?

Once again thanks for your responses.

**Comment by hsluoyz** [comment]
"V0", "V1", "V2" are just placeholders for policy elements. We defined up to "V5" to allow at most 6 elements in policy. This is usually enough for most of use cases.

**Comment by rillazoid72** [comment]
@hsluoyz I appreciate the information!
