### ISSUE TITLE
[Feature] missing domain support in some RBAC APIs

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin#598]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when the following RBAC APIs don't support domain parameter

- HasRoleForUser
- AddRoleForUser
- AddRolesForUser
- DeleteRoleForUser
- DeleteRolesForUser
- GetPermissionsForUser

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hsluoyz** [comment]
@00LT00 please try to solve this issue.

**Comment by hsluoyz** [comment]
@jpatters I noticed you sent an issue here: https://github.com/teramoby/speedle-plus/issues/11 . Actually Casbin has a friendly RBAC API here: https://casbin.org/docs/en/rbac-api  let me know if you have any questions.

**Comment by 00LT00** [comment]
When I was working on this issue. I found that there are several functions with the "indomain" suffix that can achieve the same function.@hsluoyz @GopherJ

**Comment by GopherJ** [comment]
@00LT00 we can replace those old functions, because `indomain` suffix is not necessary

**Comment by 00LT00** [comment]
I think you can look at the `rabc_api_with_domains` file. @GopherJ

**Comment by 00LT00** [comment]
plz review the pr #601 @GopherJ @hsluoyz @nodece
