### ISSUE TITLE
[Question] Is it possible to define policies in RBAC with domain without domain restriction?

### ISSUE THREAD

**Issue by Gaadek** [casbin/casbin#599]
Hello,

For my app I've implemented the RBAC with domain model.
I'd like users with specific role, no matter its domain, to perform some actions.

In my case, I want users with `admin` role, in any domain, to be able to `create` users in a central repository.
Once the user is created in the repository, the `admin` user can "map" the user to a domain with a role (and there the domain is important)

Is there a way to achieve that?

For the moment, I'm doing that outside Casbin:
1) I look for all `roles` allowed to perform the `action`,
2) Look for my requester if it has for one domain the expected role. 
3) Call the enforcer with the correct sub\domain\role\act tuplet

It works, but it's made outside Casbin. Can Casbin handle such situation?

Thanks

**Comment by hsluoyz** [comment]
@Gaadek please give an example model and policy, and request and expected result.

**Comment by Gaadek** [comment]
Sure,

Here is the  model I'm using:
```
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act, eft

[role_definition]
g = _, _, _
g2 = _, _, _


[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.sub, p.sub, r.dom) && keyMatch(r.dom, p.dom) && (g2(r.obj, p.obj, r.dom) || keyMatch(r.obj, p.obj)) && keyMatch(r.act, p.act)
```

The policies I'm using:
```
p, User, *, *, Read, allow
p, Admin, *, *, Read, deny
p, User, *, *, CreateUser, deny
p, Admin, *, *, CreateUser, allow

g, alice, Admin, domain1
g, bob, User, domain1

g2, data1, folder1, domain1
```

And the test cases:
```
alice, *, *, CreateUser
alice, domain1, folder1, Read
alice, domain1, folder1, Write
bob, domain1, *, CreateUser
bob, domain1, data1, Read
bob, domain1, *, Write
```

The very first test case is to check if `alice` can create a user, which is expected to be `true` because `alice` is `admin` for 1 domain. It returns `false` because `alice` is not directly linked to domain `*`

Thetest case #4 returns `false` as expected because `bob` is not `admin`on any domain.

**Comment by 00LT00** [comment]
I think we do not support the wildcards of domains at the moment. @Gaadek

**Comment by 00LT00** [comment]
@Gaadek I think #600 could give you some help.

**Comment by Gaadek** [comment]
Thanks for the comment, I reviewed the #600.

I need to determine if that's acceptable for me to assign the users to the "*" domain

**Comment by dwang7** [comment]
you can define your conf like this:

```
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.obj == p.obj && r.act == p.act
```

The domain is not specified in the policy definition. It is only specified in the role and request definition.

**Comment by hsluoyz** [comment]
Closed as resolved.
