### ISSUE TITLE
[Question]wildcard or keyMatch func for rbac domain ?

### ISSUE THREAD

**Issue by jamesislebron** [casbin/casbin#600]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

I am trying to create a rbac model with domain.
I want to achieve that a role has some permissions in all domains.So I use "*" for domain in policy.
Then I use keyMatch(r.domain, p.domain) in mode conf.
But it seems not work.

While I try find some examples in docs.
I see that there is doc like this:

![image](https://user-images.githubusercontent.com/20439714/93079126-37e20580-f6be-11ea-825e-31176d403019.png)

I try to register keyMatch func to enforcer, but it result a unexported error:
    
    e.rm undefined (cannot refer to unexported field or method rm)

words blow is my config:

**My model:**

```ini
[request_definition]
r = sub, resource, method, domain

[policy_definition]
p = sub, resource, method, domain

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.domain) && keyMatch(r.domain, p.domain) && keyMatch4(r.resource, p.resource) && r.method == p.method
```

**My policy:**

```
p, role_b, /v1/pen/{id}/, GET, *
g, user2, role_b, *
```

**My request(s):**

```
user2, /v1/pen/a2jfk844jnnv/, GET, domain1 ---> false (expected: true)
```

**Comment by hsluoyz** [comment]
@nodece @00LT00

**Comment by 00LT00** [comment]
`e.rm` is a private struct for Enforcer
![image](https://user-images.githubusercontent.com/47566260/93132078-a1d2cd00-f707-11ea-921f-20b374133d73.png)
So you can try 
```go
r := e.GetRoleManager()
r.(*defaultrolemanager.RoleManager).AddDomainMatchingFunc("KeyMatch2",util.KeyMatch2)
```

**Comment by jamesislebron** [comment]
It works.
While it means that the docs and examples are both wrong ?
Hope that there are some correct for this cause it really confused.
Thanks a lot !

**Comment by hsluoyz** [comment]
@jamesislebron @00LT00 can you update the wrong docs here: https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac ?

**Comment by jamesislebron** [comment]
sure, I'll correct it in docs and examples.

**Comment by 00LT00** [comment]
updated. @hsluoyz

**Comment by hsluoyz** [comment]
Um.. I see two exactly the same PRs. I merge the earlier one (131) this time.

https://github.com/casbin/casbin-website/pull/131
https://github.com/casbin/casbin-website/pull/132
