### ISSUE TITLE
[Question] eval support in policy

### ISSUE THREAD

**Issue by lucas-57blocks** [casbin/casbin#603]
With the code in pr [fix: compatible RBAC in ABAC](https://github.com/casbin/casbin/pull/583), change the replace role of eval string in policy, why? How to support scenario  below? #583

@hsluoyz @GopherJ @nodece 

**Model:**
```ini
[request_definition]
r = user, url, method

[policy_definition]
p = role, ext, url, method

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (r.user.Role == p.role && eval(p.ext)) && keyMatch2(r.url, p.url) && regexMatch(r.method, p.method)
```

**Policy:**

```
p, employee, true, /user/profile, (GET)
p, employee, r.user.Age > 18, /user/game, (GET
```

**Request:**

```
{employee 10}, /user/profile, GET ---> false (expected: true)
```

**Comment by hsluoyz** [comment]
@00LT00 can you reply to this question?

/cc @nodece

**Comment by 00LT00** [comment]
@lucas-57blocks Now we don't support `r.user.Role == p.role`  writing directly in Conf. So you can try 
Policy:
```
p, employee, r.user.Role == p.role, /user/profile, GET
p, employee, r.user.Age > 18, /user/game, GET
```
Model:
```
[matchers]
m = (eval(p.ext)) && keyMatch2(r.url, p.url) && regexMatch(r.method, p.method)
```
test.go
```go
type testUser struct {
	Age int
	Role string
}

func newTestUser(name int, role string) testUser {
	s := testUser{}
	s.Age = name
	s.Role = role
	return s
}

func Test(t *testing.T) {
	e, _ := NewEnforcer("examples/abac_with_rbac.conf", "examples/abac_with_rbac.csv")

	user := newTestUser(10, "employee")

	ok, err := e.Enforce(user, "/user/profile", "GET")
	if err != nil || ok != true {
		t.Fatal("expected Enforce returns true, nil, but got", ok, err)
	}
}
```
And it's ABAC in fact.

**Comment by lucas-57blocks** [comment]
@00LT00  Now, the code is
```go
if strings.Contains(rule, ">") || strings.Contains(rule, "<") || strings.Contains(rule, "=") {
    expWithRule = util.ReplaceEval(expWithRule, rule)
} else {
    expWithRule = util.ReplaceEval(expWithRule, "false")
}
```
That means, only support ">", "<", "==", ">=", "<=", "!=", "=~", but other operators, key match function, custom function can't be supported without those operators?

**Comment by 00LT00** [comment]
Sorry, I made a serious mistake, the real problem should be here
`p, employee, **true**, /user/profile, (GET)`
it should be `1=1`, and I think we should add `"true"`

Umm..I think the `key match function, custom function` should be used at `Model` rather than at `Policy`

**Comment by lucas-57blocks** [comment]
@00LT00  That's great if you add `"true"`.
There is another thing I want to discuss. We use matcher to check all policies, logic may be complex, so matcher is very flexible, we can also use `eval` to do policy-specific checks, the logic also can be complex, why restrict flexibility? Is it required by the tenets of ABAC?

**Comment by hsluoyz** [comment]
@lucas-57blocks see the scaling ABAC feature: https://casbin.org/docs/en/abac#scaling-the-model-for-complex-and-large-number-of-abac-rules

**Comment by nodece** [comment]
@lucas-57blocks You are right, we should consider the bool in part of ABAC.

**Comment by lucas-57blocks** [comment]
> @lucas-57blocks see the scaling ABAC feature: https://casbin.org/docs/en/abac#scaling-the-model-for-complex-and-large-number-of-abac-rules

@hsluoyz I've read it before, but it doesn't explain the question about restrict flexibility in policy.

**Comment by hsluoyz** [comment]
@nodece I still didn't get why we restrict the eval here: https://github.com/casbin/casbin/pull/583/commits/7c9f78f6a964183442201037e723600080df7a8c#r475317157

> Once user use RBAC with ABAC model, we have to make sure eval slot is boolean.

Can you explain this line?

**Comment by nodece** [comment]
@hsluoyz  For example, we should eval p.sub, which should be an expression, but what the user provides is not an expression.

Model: 
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[role_definition]
g = _, _

[matchers]
m = (g(r.sub, p.sub) || eval(p.sub)) && r.act == p.act
````
Policy
```
p, admin, post, write
p, r.sub == r.obj.Author, post, write

g, alice, admin
```

**Comment by hsluoyz** [comment]
@nodece it's the end user's responsibility to know that column means "rule" which is an expression instead of a element like "sub", "obj", "act". As the end user controls both the model and policy rules, he can well know that "admin" in the first rule is not an expresssion. Actually I suggest changing a different name, use "rule" as an additional column will be better:

Model:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, rule

[policy_effect]
e = some(where (p.eft == allow))

[role_definition]
g = _, _

[matchers]
m = (g(r.sub, p.sub) || eval(p.rule)) && r.act == p.act
```

Policy:

```csv
p, admin, post, write, true // means not used
p, not_used, post, write, r.sub == r.obj.Author

g, alice, admin
```

@lucas-57blocks what's your input?

**Comment by lucas-57blocks** [comment]
> @nodece it's the end user's responsibility to know that column means "rule" which is an expression instead of a element like "sub", "obj", "act". As the end user controls both the model and policy rules, he can well know that "admin" in the first rule is not an expresssion. Actually I suggest changing a different name, use "rule" as an additional column will be better:
> 
> Model:
> 
> ```ini
> [request_definition]
> r = sub, obj, act
> 
> [policy_definition]
> p = sub, obj, act, rule
> 
> [policy_effect]
> e = some(where (p.eft == allow))
> 
> [role_definition]
> g = _, _
> 
> [matchers]
> m = (g(r.sub, p.sub) || eval(p.rule)) && r.act == p.act
> ```
> 
> Policy:
> 
> ```
> p, admin, post, write, true // means not used
> p, not_used, post, write, r.sub == r.obj.Author
> 
> g, alice, admin
> ```
> 
> @lucas-57blocks what's your input?

@hsluoyz This example is the same as mine, "rule" is "ext". I use "ext" as additional expresssion in policy, but this expresssion was been restricted.

**Comment by hsluoyz** [comment]
Then I think we can roll back this change.

**Comment by hsluoyz** [comment]
@lucas-57blocks reverted in: https://github.com/casbin/casbin/pull/611
