### ISSUE TITLE
[Question] Is it possible to get reason of permissions denied from casbin enfocer with boolean response?

### ISSUE THREAD

**Issue by brt-alok-adhao** [casbin/casbin#606]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Your answer here

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, alice, data1, read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write

g, alice, data2_admin
```

**Your request(s):**

```
alice, data2, speak ---> false (expected: {result:false, reason: "Action not present"} )
```

**Comment by brt-alok-adhao** [comment]
Hello,
I have updated the example and included what I am looking for.
I have used Cabin RBAC with domains in one of my projects. 
Now if the decision is false then I also need to respond back to the user with the reason why he is not having Access.
As enforcer just returns a boolean value. I am not sure if the action is not present or the policy is not present or the user is not present. 

So, My expectation was - As Casbin has its own rule engine and it evaluates the final result then can it also responds with the reason where it failed.

**Comment by hsluoyz** [comment]
@00LT00 can you work on this feature (responds with the reason where it failed.) ?

/cc @nodece

**Comment by 00LT00** [comment]
I will try.

**Comment by GopherJ** [comment]
@hsluoyz  @brt-alok-adhao Is there a method to implement this? In my opinion it's currently not possible, because model.conf's matcher will be parsed to an AST, and we need to find the first `false` while evaluating to be able to return back the failed expression.

However, govaluate and rhai don't support this from my understanding...

If we don't do this way, it'll be hard to implement, even if we succeed to do, it'll bing too much overhead to casbin

**Comment by 00LT00** [comment]
May be we can split expression ourselves, use tree. But it will take us further and further away from govaluate... And we cannot ensure stability. Do you have some idea?

**Comment by hsluoyz** [comment]
@GopherJ we don't need to return the matcher AST level information. Just return the currently triggered rule, e.g., the first allowed rule index or rule itself for Allow-override model.

**Comment by hsluoyz** [comment]
This issue is resolved by the new EnforceEx() API:

- issue: https://github.com/casbin/casbin/issues/355
- PR: https://github.com/casbin/casbin/pull/425

**Comment by hsluoyz** [comment]
@closetool plz add the new API into the docs, after: https://casbin.org/docs/en/management-api#enforce

**Comment by hsluoyz** [comment]
@brt-alok-adhao new API is added to docs: https://casbin.org/docs/en/management-api#enforceex
