### ISSUE TITLE
Model and policy serialization and deserialization

### ISSUE THREAD

**Issue by michaelkruglos** [casbin/casbin#61]
How can I serialize/deserialize casbin models and policies to and from JSON?

**Comment by hsluoyz** [comment]
You can load and save policies in JSON with the JSON adapter: https://github.com/casbin/json-adapter

For model, there's no way to use JSON right now. But we support very flexible ways to load the model, see here: https://github.com/casbin/casbin/wiki/Load-model-from-string

**Comment by michaelkruglos** [comment]
Thank you so much for this quick response!
