### ISSUE TITLE
[Question]Is it possible to ignore func (rm *RoleManager) PrintRoles() when i disable log

### ISSUE THREAD

**Issue by holayao** [casbin/casbin#614]
------

**What's your scenario? What do you want to achieve?**
Your answer here

i have been  study with GC recently , and i found func (rm *RoleManager) PrintRoles() took up a lot of heap memory due to this line as shown in the red box 
![image](https://user-images.githubusercontent.com/41869842/94640989-a22bb480-0312-11eb-89b6-d787d90a615d.png)
so i wonder if this function can be ingored when i disable log to avoid large memory allocs

**Comment by hsluoyz** [comment]
@nodece @00LT00

**Comment by 00LT00** [comment]
@holayao I noticed that you are still using the old version of casbin. So I suggest you should update the version for the many feature.
And you can how to turn off the log [here](https://casbin.org/docs/en/log-error#logging).
```go
e.EnableLog(false)
```

**Comment by holayao** [comment]
I have already disable log feature,but this function will be executed when call buildRoleLinks, as > [here](https://github.com/casbin/casbin/blob/c730e2689d1f9e60206fbe30f0995d48899b6760/enforcer.go#L253)

it looks like we must enable function buildRoleLinks,or when i add or delete a role ,it wont work

**Comment by hsluoyz** [comment]
We can wrap the log printing in `buildRoleLinks()` with an EnableLog flag check. @00LT00 or @holayao can you make a PR?

**Comment by holayao** [comment]
> We can wrap the log printing in `buildRoleLinks()` with an EnableLog flag check. @00LT00 or @holayao can you make a PR?

**Comment by holayao** [comment]
@hsluoyz of course,it's my pleasure
