### ISSUE TITLE
[Bug] documentaion for error handling needs to be updated

### ISSUE THREAD

**Issue by CSRaghunandan** [casbin/casbin#616]
The logs for error handling is outdated as per the latest major version of Casbin: https://casbin.org/docs/en/log-error#error-handling

It mentions using `NewEnforcerSafe` and `LoadModelSafe`, both of which are not present on v2 of casbin.

**Comment by hsluoyz** [comment]
@CSRaghunandan thanks for pointing it out! Are you willing to make a PR to fix it?
