### ISSUE TITLE
请问为什么不像gogs一样出中文文档呢

### ISSUE THREAD

**Issue by naiba** [casbin/casbin#62]
还有vue，他们都有中文文档。

**Comment by hsluoyz** [comment]
主要没有时间呀，而且缺乏一个契机，比如和国内的组织、个人的深度合作~ 不过欢迎帮忙完善中文文档哈~

有问题可以加QQ群：546057381

**Comment by hsluoyz** [comment]
Hi @naiba , we have Chinese documentation now: https://casbin.org/docs/zh-CN/overview

**Comment by naiba** [comment]
awesome @hsluoyz

**Comment by naiba** [comment]
test replay email directly2018年11月14日 下午10:01，Yang Luo <notifications@github.com>写道：Hi @naiba , we have Chinese documentation now: https://casbin.org/docs/zh-CN/overview
