### ISSUE TITLE
[Bug] Log Spam after upgrade to 2.15.0

### ISSUE THREAD

**Issue by niallnsec** [casbin/casbin#629]
**Describe the bug**
After upgrading to version 2.15.0 Casbin is writing unwanted log messages to stdout.

**To Reproduce**
Init Casbin with a model with logging disabled by passing false as the third argument.

**Expected behavior**
No log will be written to stdout, as in previous versions.

**Desktop (please complete the following information):**
 - OS: Any

**Additional context**
I think this is related to the last merge request which changes the logger, it appears that in the old implementation log output is disabled in the loggers Printf routine by the enable flag. That is no longer the case and calls to the logger are not all wrapped by calls to IsEnabled in the source.
On loading, the model is always printed due to the lack of such a call.

**Comment by hsluoyz** [comment]
@kocoler can you take a look at this issue?

**Comment by hsluoyz** [comment]
@niallnsec fixed in: https://github.com/casbin/casbin/pull/630
