### ISSUE TITLE
combine ABAC and RBAC

### ISSUE THREAD

**Issue by mostafasolati** [casbin/casbin#63]
Hi
I want to combine these two models , some roles may have owner permission and should access their very own data , some other roles can access to data regardless of whether being owner or not
How to achieve that ?

**Comment by hsluoyz** [comment]
I think you can use the following model. ``r.sub == r.obj.owner`` determines whether the subject is the owner of the resource. If yes, then allow. ``r.obj`` is a Golang struct that has an ``owner`` member. ``g(r.sub, "admin")`` determines whether the subject has the role ``admin``. And in the policy, we specified ``bob`` is a member of ``admin``. So if bob wants to access, he will be allowed too.

Model:
```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == r.obj.owner || g(r.sub, "admin")
```

Policy:
```csv
g, bob, admin
```

**Comment by huangxianyuan** [comment]
The project has a data permission feature, you can customize the data permissions, the project workflow model list to join the data permissions, you can refer to this module. Note: This is translated by Goolgle and may not be accurate





At 2018-01-01 16:02:47, "mostafasolati" <notifications@github.com> wrote:


Hi
I want to combine these two models , some roles may have owner permission and should access their very own data , some other roles can access to data regardless of whether being owner or not
How to achieve that ?

**Comment by hsluoyz** [comment]
@huangxianyuan  What do you mean? I don't quite understand it after Google translation.

**Comment by huangxianyuan** [comment]
Are you using hxyFrame project? You re-describe the problems you now encounter?






At 2018-01-04 11:11:27, "Yang Luo" <notifications@github.com> wrote:


@huangxianyuan What do you mean? I don't quite understand it after Google translation.

**Comment by hsluoyz** [comment]
@huangxianyuan  I think you came to the wrong place.  This is the Golang authorization library: Casbin's issue list, not hxyFrame. The URL for this issue is: https://github.com/casbin/casbin/issues/63

**Comment by ngjaying** [comment]
> I think you can use the following model. `r.sub == r.obj.owner` determines whether the subject is the owner of the resource. If yes, then allow. `r.obj` is a Golang struct that has an `owner` member. `g(r.sub, "admin")` determines whether the subject has the role `admin`. And in the policy, we specified `bob` is a member of `admin`. So if bob wants to access, he will be allowed too.
> 
> Model:
> 
> ```ini
> [request_definition]
> r = sub, obj, act
> 
> [policy_definition]
> p = sub, obj, act
> 
> [role_definition]
> g = _, _
> 
> [policy_effect]
> e = some(where (p.eft == allow))
> 
> [matchers]
> m = r.sub == r.obj.owner || g(r.sub, "admin")
> ```
> 
> Policy:
> 
> ```
> g, bob, admin
> ```

@hsluoyz This model hard coded the role name in the matcher. If we allow to customize the roles so that the roles are dynamic added, how can we model it. The core requirement is:
- A dynamic list of roles which can access all objects
- Another dynamic list of roles which can access only owned objects
Thanks

**Comment by vtolstov** [comment]
you can add you own func to matcher to get owner of object

**Comment by ngjaying** [comment]
> you can add you own func to matcher to get owner of object

Yes, but my problem is that the owner rule is not universal for all roles. Some roles does not need to check own func; some roles should always be rejected; some roles should always be accepted. And the roles list are dynamic.

Example, roles [admin, customAdmins ... ] can access all; roles [users, ausers ...] can access owned obj; roles [banned ...] cannot access any obj.
With the proposed matchers as below,  users of customAdmins will be rejected.
[matchers]
m = r.sub == r.obj.owner || g(r.sub, "admin")

**Comment by vtolstov** [comment]
so if for some roles you don't need to check owner you can pass roles to matcher func and return early ?

**Comment by ngjaying** [comment]
> so if for some roles you don't need to check owner you can pass roles to matcher func and return early ?

right, but the roles list are not static.  How can the matcher func filter roles against a dynamic list?

**Comment by hsluoyz** [comment]
@ngjaying please fire new issue for your problem. This issue will be locked.
