### ISSUE TITLE
[Question] How to document the business rules of your application

### ISSUE THREAD

**Issue by adrianwix** [casbin/casbin#632]
Hi, I was wondering if anyone could recommend a way to keep track of the rules/permissions that are used or can be use in an application.
I have for example a set of resources
```ts
enum Resources {
    DOCUMENT = "DOCUMENT"
    USER = "USER"
    ROLE = "ROLE"
}
```
and a set of actions that can be use with this permissions
```ts
enum Actions {
    READ = "READ"
    EDIT = "EDIT"
    CREATE = "CREATE"
    GRANT = "GRANT"
    INVITE = "INVITE"
}
```
Then the funny thing beginns when we have _different set of possible combinations_.
Like for example
```
const ActionsPerResource = {
    ROLE: [CREATE, GRANT],
    DOCUMENT: [READ, EDIT, CREATA]
}
```
So `ROLE` can only have the actions CREATE and GRANT and even here we need to distinguish between the actions that need a particular ID or a placeholder like ":id". For example the GRANT action of role needs an id like GRANT/1, GRANT/:id but CREATE doesn't (either you can create a role or not).

If there a recommended approach to document the permissions and actions? I use TypeScript for my backend but I can be useful to know how is this problem tackle in other languages.

Another thing to take into account is that even business persons (CEO, designers) need to be aware of it. 

Another thing that can change is the combination of `sub, dom, obj, act` let's say usually you always give a userId and a tenantId to your rules. But there are some cases where that's not always true.

For example you want to controll the visibility of an assets. There are 3 types of visibility PUBLIC, TENANT, PRIVATE. You could define 3 rules as follow
Any user from any tenant can read resource 1 `*, *, document/1, read`
Any use from tenant 1 can read resource 2 `*, tenant1, document/2, read`
User 1 can read resource 3 from tenant 2 `user1, tenant2, document/3, read`

I wrote some ugly code that kind of deal with this (The type inference has some problems). This still feel suboptimal.

```ts
export enum Actions {
    CREATE = 'CREATE',
    READ = 'READ', // Read by id => GET "/:id"
    READ_ALL = 'READ_ALL', // Read all => GET "/"
    EDIT = 'EDIT',
    GRANT = 'GRANT',
}

export enum Resources {
    USER = 'USER',
    DOCUMENT= 'DOCUMENT',
    ROLE = 'ROLE',
}

type ResourcesAndActionsType = {
    [r in keyof typeof Resources]: { [a in keyof typeof Actions]?: a }
}

export const ResourcesAndActions = {
    DOCUMENT: {
        READ: Actions.READ,
        READ_ALL: Actions.READ_ALL,
        EDIT: Actions.EDIT,
        ADMIN: Actions.ADMIN,
    },
    ROLE: {
        GRANT: Actions.GRANT,
        CREATE: Actions.CREATE
    },
    USER: {
        READ_ALL: Actions.READ_ALL,
        CREATE: Actions.CREATE,
    },
}

type ResourceAndActionsKeys = keyof typeof ResourcesAndActions

type ActionsKeys<
    T extends ResourceAndActionsKeys
> = typeof ResourcesAndActions[T]

type PermisisonKeyFields = {
    [Res in ResourceAndActionsKeys]: {
        [Act in keyof ActionsKeys<Res>]:
            | (() => [Res, Act])
            | ((id?: string | number) => [string, Act])
    }
}

function TupleFactory<R, A>(res: R, act: A): () => [typeof res, typeof act] {
    return () => [res, act]
}

function TupleFactoryByID<R, A>(
    res: R,
    act: A,
): (arg0: string) => [string, typeof act] {
    return (id) => [`${res}/${id}`, act]
}

interface IPermissions extends PermisisonKeyFields {}

export const permissions: IPermissions = {
    DOCUMENT: {
        EDIT: TupleFactoryByID(Resources.DOCUMENT, Actions.EDIT),
        ADMIN: TupleFactoryByID(Resources.DOCUMENT, Actions.ADMIN),
        READ: TupleFactoryByID(Resources.DOCUMENT, Actions.READ),
        READ_ALL: TupleFactory(Resources.DOCUMENT, Actions.READ_ALL),
    },
    ROLE: {
        GRANT: TupleFactoryByID(Resources.ROLE, Actions.GRANT),
        CREATE: TupleFactoryByID(Resources.ROLE, Actions.CREATE),
    },
    USER: {
        READ_ALL: TupleFactory(Resources.USER, Actions.READ_ALL),
        CREATE: TupleFactory(Resources.USER, Actions.CREATE),
    },
}

```

**Comment by hsluoyz** [comment]
@nodece @kocoler

**Comment by nodece** [comment]
@adrianwix Do you want to log the policy?

**Comment by hsluoyz** [comment]
@adrianwix sorry for late response, but I think you are not writing Casbin model and policy.

**Comment by adrianwix** [comment]
Let me try to explain better as I probably wrote that without proper sleep last time :D.
While writing casbin policy rules (sub, dom, obj, act) you want to has some kind of documentation about the rules in your application because otherwise the code will be a complete mess.
For a given resource like Documents, you only want a set of actions to be defined like for example "READ", "EDIT", "DELETE". You do NOT want someone to create a casbin rule with an action like "READ_ONE" that does the same as "READ". Furthermore you want the business people in your organization to have an idea of how this works.
Assuming casbin has been used in large scale projects someone has probably come up with a solution for documenting possible set of permissions. It can be in any language, a markdown file or a word document for all I care.
Does anyone has some advice for doing it? (Documenting possible set of casbin permissions)

**Comment by hsluoyz** [comment]
I think you should provide something like Web UI, then use Select control to provide limited options for a given situation.

I don't think the business people will directly write Casbin model or policy. Casbin is mainly for developers. So a Web UI is needed for them. See something like:

- https://dashboard.casbin.org/#/dashboard/policy
- https://cloud.casbin.org/PolicyEditor.html?policy_name=custom-policy.csv&tenant_id=tenant1&tenant_name=Company%20A

![image](https://user-images.githubusercontent.com/3787410/109328354-54e94a00-7894-11eb-999a-2fc21c9810d0.png)
