### ISSUE TITLE
[Question] Passing a list in the enforcer in an ABAC model

### ISSUE THREAD

**Issue by kanika21011** [casbin/casbin#633]
Hi,
I am working on an ABAC model, where I have to check if an entity is allowed to access a resource 
Something like,
p, r.sub.Name == 'Alice' || r.sub.Name == 'Bob', data1, read
Now is there a way I can pass the list in enforcer instead of checking for individual names?

**Comment by nodece** [comment]
I'm not sure if it's this: https://casbin.org/docs/en/abac#scaling-the-model-for-complex-and-large-number-of-abac-rules

**Comment by kanika21011** [comment]
It is something similar to it.
What I am trying to do is have a list of names that can access a specific resource. 
Like Alice and bob can access data1 on read-write mode. It is easy to do right now as we are looking at only two rows for now. If this turns to be 1000 rows then instead of writing each policy separately, is there a way I can have a list in the policy file and the pass list in the enforcer also.

**Comment by hsluoyz** [comment]
@kanika21011 I think you need `batchEnforce()`: https://github.com/casbin/casbin/issues/617

@nodece can we implement it?

**Comment by nodece** [comment]
@hsluoyz I guess he wants to pass the `policy` to enforcer.

@kanika21011 Do you mean this?

**Comment by kanika21011** [comment]
No, I want to pass the list in the enforcer.
Something like,

list = ["Alice","Bob"]
e.enforce(list, "data1", "read_write")
and my policy file might look like,
p, r.sub.Name in ("Alice", "Bob"), data1, read_write

The enforce should check if the list("Alice", "Bob") is allowed to do a read_write operation on data1 or not

**Comment by hsluoyz** [comment]
@nodece @kocoler can you help implement this? https://github.com/casbin/casbin/issues/617

**Comment by kanika21011** [comment]
@hsluoyz yes. 
and the policy should also contain the list and not the individual rule
Is this possible?

**Comment by hsluoyz** [comment]
Closed here. Stay tuned at: https://github.com/casbin/casbin/issues/617
