### ISSUE TITLE
[Question] Using Casbin for data filtering

### ISSUE THREAD

**Issue by kevinlu1211** [casbin/casbin#634]
Hello I understand that the output of Casbin is for enforcing authorization, but I was wondering if it is a common pattern where people are using Casbin for data filtering?

For example, 

```
user_documents = []
for document in documents:
    user_can_read_document = Casbin.Enforcer(document.id, user, 'read')
    if user_can_read_document:
        user_documents.append(document)
```

**Comment by hsluoyz** [comment]
@kevinlu1211 yes, see: https://github.com/casbin/casbin/issues/617

**Comment by kevinlu1211** [comment]
@hsluoyz I've read through it, could you elaborate a bit?

**Comment by hsluoyz** [comment]
Closed here. Stay tuned at: https://github.com/casbin/casbin/issues/617
