### ISSUE TITLE
function "LoadModel" is not synchronized in structure [SyncedEnforcer]

### ISSUE THREAD

**Issue by sangalao** [casbin/casbin#639]
See content of file : 
https://github.com/casbin/casbin/blob/master/enforcer_synced.go

function "LoadModel" is not present, and thus not synchronized in this structure.
Therefore, thread concurrency issues may occur while calling [LoadModel] functions and other methods through different go routines

**Comment by hsluoyz** [comment]
@sangalao can you make a PR to fix it?

**Comment by hsluoyz** [comment]
@nodece

**Comment by closetool** [comment]
I'll try to fix it, thanks
