### ISSUE TITLE
[Bug] LoadPolicyLine method crashes in adapter.go if model is empty (robustness issue)

### ISSUE THREAD

**Issue by sangalao** [casbin/casbin#640]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**

[Bug] LoadPolicyLine method crashes in adapter.go if model is empty and policy non-empty (robustness issue)

to reproduce : 
Use an empty model and a non-empty policy, and try to create enforcer.
It crashes with following stack trace  : 

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x83047e]

github.com/casbin/casbin/persist.LoadPolicyLine(0xc00037e9f0, 0x22, 0xc000d56480)
        C:/Users/user/go/pkg/mod/github.com/casbin/casbin@v1.9.1/persist/adapter.go:36 +0x22e
github.com/casbin/casbin/persist/file-adapter.(*Adapter).loadPolicyFile(0xc000d55e80, 0xc000d56480, 0xe2aa80, 0x0, 0x0)
        C:/Users/user/go/pkg/mod/github.com/casbin/casbin@v1.9.1/persist/file-adapter/adapter.go:86 +0x1b0
github.com/casbin/casbin/persist/file-adapter.(*Adapter).LoadPolicy(0xc000d55e80, 0xc000d56480, 0xd1e180, 0xd465e0)
        C:/Users/user/go/pkg/mod/github.com/casbin/casbin@v1.9.1/persist/file-adapter/adapter.go:46 +0x95
github.com/casbin/casbin.(*Enforcer).LoadPolicy(0xc0001bac40, 0x106cea0, 0xc000d55e80)
        C:/Users/user/go/pkg/mod/github.com/casbin/casbin@v1.9.1/enforcer.go:214 +0x5a
github.com/casbin/casbin.(*Enforcer).InitWithModelAndAdapter(0xc0001bac40, 0xc000d56480, 0x106cea0, 0xc000d55e80)
        C:/Users/user/go/pkg/mod/github.com/casbin/casbin@v1.9.1/enforcer.go:128 +0x2ca
github.com/casbin/casbin.(*Enforcer).InitWithAdapter(0xc0001bac40, 0xdec975, 0x1d, 0x106cea0, 0xc000d55e80)
        C:/Users/user/go/pkg/mod/github.com/casbin/casbin@v1.9.1/enforcer.go:109 +0xa0
github.com/casbin/casbin.(*Enforcer).InitWithFile(...)
        C:/Users/user/go/pkg/mod/github.com/casbin/casbin@v1.9.1/enforcer.go:103
github.com/casbin/casbin.NewEnforcer(0xc00101bae0, 0x2, 0x2, 0xc0000febd0)
        C:/Users/user/go/pkg/mod/github.com/casbin/casbin@v1.9.1/enforcer.go:72 +0x1dc

**To Reproduce**
See details above

Suggestion of correction : 

in [adapter.go], replace :  

m[sec][key].Policy = append(m[sec][key].Policy, tokens[1:])

per 

	if _, ok := model[sec]; ok {
		model[sec][key].Policy = append(model[sec][key].Policy, tokens[1:])
	} else {
// some error message
}

**Expected behavior**
No crash when model is empty, but a WARN/ERROR log instead (robustness issue)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GopherJ** [comment]
@sangalao basically model shouldn't be empty, it should at least contain: `r, p, e, m` section, otherwise casbin may crash. I don't think it's good to add this check because if this happens, casbin should stop working immediately.

However, maybe we should change to make it `panic` with an error message which I think is a correct way of handling this

**Comment by hsluoyz** [comment]
Good point!

**Comment by hsluoyz** [comment]
Closed as invalid.
