### ISSUE TITLE
[Question] Result with same model , policy and request is not the same on editor casbin page

### ISSUE THREAD

**Issue by dragonborngem** [casbin/casbin#641]
I tested this model policy and request below, expected result must be

```
true
true
false
true
true
true
true
```
but it only on ABAC example page, if I switched to other example and paste same config, result will be
```
true
true
false
true
true
true
false
```
the different is last request, It true on ABAC example page and false on other example page, any reason why this happen or I missconfig something? 
link to result image

![image](https://user-images.githubusercontent.com/3787410/99353466-8474d780-28df-11eb-87f1-a87dd9d78516.png)

![image](https://user-images.githubusercontent.com/3787410/99353469-88a0f500-28df-11eb-8d9e-b118919c4951.png)

Tks !!!
------

**What's your scenario? What do you want to achieve?**
Is my config correct or this is editor page problem ?

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m =( r.sub == r.obj.Owner ) ||  g(r.sub, p.sub) && (g2(r.obj, p.obj) && r.act == p.act || keyMatch2(r.obj, p.obj) && regexMatch(r.act, p.act)) 
```

**Your policy:**

```
p, alice, data1, read
p, bob, data2, write
p, data_group_admin, data_group, write


p, data_group_admin, /alice_data/:resource, GET
p, data_group_admin, /alice_data2/:id/using/:resId, GET

g, alice, data_group_admin
g2, data1, data_group
g2, data2, data_group
```

**Your request(s):**

```
alice, data1, read
alice, data1, write
alice, data2, read
alice, data2, write 
alice, /alice_data/hello, GET
alice, /alice_data2/23/using/32, GET
alice, { Owner: 'alice'}, GET
```

**Comment by hsluoyz** [comment]
Please send the issue to: https://github.com/casbin/casbin-editor instead.
