### ISSUE TITLE
[Question] How to combine RBAC with ABAC to find owner of r.obj

### ISSUE THREAD

**Issue by dragonborngem** [casbin/casbin#642]
**What's your scenario? What do you want to achieve?**
Hi, I'm new to casbin 
After read some docs, I have defined my model as below, but I'm still confuse about how can I combine RBAC and ABAC together 
My case: I want admin to access any resource , It's ok, but I also want user who created resource can access them also
example for simple endpoint
```
/api/conversation/{id} 
```
I can get user and obj from request , but r.obj is : '/api/conversation/{is}' not { Owner: 'alice'} likes example. 
So do I need to write a custom function so I can get owner from Database, transform to " { Owner: 'alice'}" like and compare with r.user ?
I haven't found any code or example about handle this simple ABAC example, just small example in homepage , so I don't know how to do it properly :(

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, sub_rule, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m =(eval(p.sub_rule) && r.obj == p.obj && r.act == p.act) ||  g(r.sub, p.sub) && (g2(r.obj, p.obj) && r.act == p.act || keyMatch2(r.obj, p.obj) && regexMatch(r.act, p.act)) || ( r.sub == r.obj.Owner )"					

```

**Your policy:**

```
p, alice, data1,, read
p, bob, data2,, write
p, data_group_admin, data_group,, write
p, data_group_admin, data_group,, read

p, data_group_admin, /alice_data/*,, GET
p, data_group_admin, /alice_data2/*/using/*,, GET

g, alice, data_group_admin
g, bob, admin
g2, data1, data_group
g2, data2, data_group
```

**Your request(s):**

```
alice, data1, read
alice, data1, write
alice, data2, read
alice, data2, write 
alice, /alice_data/3535, GET
alice, /alice_data2/23/using/32, GET
alice, { Owner: 'alice'}, GET
```

**Comment by hsluoyz** [comment]
@dragonborngem how is your owner stored? Can you pass the owner in the Enforce() call?

**Comment by hsluoyz** [comment]
Moved to this issue: https://github.com/casbin/casbin/issues/673
