### ISSUE TITLE
[Bug] GetRolesForUser Does not work with a list of domain in parameter

### ISSUE THREAD

**Issue by dragonborngem** [casbin/casbin#643]
**Describe the bug**

I'm using go 1.15 with casbin v2.17.0 and gorm  v1.20.6

As i can see , function 
**func (*casbin.Enforcer).GetRolesForUser(name string, domain ...string) ([]string, error)**
can pass list of domain or slice of domain as second argument, but if I pass more than one domain, I will get this err
**domain should be 1 parameter**

So is this my config err or bug? Tks 

**My model**

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub.Email, p.sub, r.dom) && r.dom == p.dom && ( r.obj == p.obj || keyMatch2(r.obj, p.obj) ) && r.act == p.act
```

**Comment by nodece** [comment]
@dragonborngem This is not a bug.

If you want to get the roles for a user with multiple domain, you can only pass each domain to `GetRolesForUser` via loop.

Case: we have a user named `alice`,  which has `a`, `b` domain. I want to know what roles `alice` has in the `a` and `b` domain.
```
inA, err := GetRolesForUser("alice", "a") 
inB, err := GetRolesForUser("alice", "b") 
```

**Comment by dragonborngem** [comment]
> @dragonborngem This is not a bug.
> 
> If you want to get the roles for a user with multiple domain, you can only pass each domain to `GetRolesForUser` via loop.
> 
> Case: we have a user named `alice`, which has `a`, `b` domain. I want to know what roles `alice` has in the `a` and `b` domain.
> 
> ```
> inA, err := GetRolesForUser("alice", "a") 
> inB, err := GetRolesForUser("alice", "b") 
> ```

I know I should do it this way, but I don't think this function should be shown that it can be passed with multiple domains

**Comment by hsluoyz** [comment]
@dragonborngem we use `domain ...string` to support 0 domain and 1 domain, but not >1 domains.
