### ISSUE TITLE
How to determine if a user has any permissions for a resource

### ISSUE THREAD

**Issue by fernandezvara** [casbin/casbin#65]
Hi, thanks for this library!

Sorry to came with a question but I don't know how to achieve this with the current management API.

I have a simple rule set that uses regexp matches for resources and accesses:

```
[request_definition]
r = sub, obj, act
[policy_definition]
p = sub, obj, act
[role_definition]
g = _, _
[policy_effect]
e = some(where (p.eft == allow))
[matchers]
m = g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)
```

So I have policies like these:

```
p, 123, resource1/*, read|write
p, 234, resource1/123, read|write
p, 234, resource1/234, read
```

How can I ask for a policy in order to change its accesses? I have tried with `enforcer.HasPermission("234", "resource1/123")` thinking that it could return `true` on found, but it seems that looks for the full policy.

So can I partially ask for a policy?

Hope I have explained myself.

**Comment by hsluoyz** [comment]
You can use [GetFilteredPolicy](https://github.com/casbin/casbin/blob/c413903cd2e6366f3b0b887eed3f4224c9e1d3bf/management_api.go#L67:20) to partially ask for a policy. If you only need true or false, returning something means true.

**Comment by fernandezvara** [comment]
After using GetFilteredPolicy and some testing I could do it.

Thank you so much
