### ISSUE TITLE
[Question] Best way to combine RBAC and external LDAP groups membership

### ISSUE THREAD

**Issue by wndrr101** [casbin/casbin#650]
Hello, could you please provide an approach on best way to handle external LDAP groups and RBAC?

Let's say we have:
role-1  - just Casbin role for RBAC
user-1 - external user from LDAP
user-2 - external user from LDAP
group-1 - group in LDAP (members are user1 and user2)
group-2 - group in LDAP (member is the user2)

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act, eft

[role_definition]
g = _, _, _

[policy_effect]
e = priority(p.eft) || deny

[matchers]
m = (((r.sub == p.sub) || g(r.sub, p.sub, r.dom)) && r.dom == p.dom && regexMatch(r.obj, p.obj) && regexMatch(r.act, p.act)) || (g(r.sub, "root", p.dom) || r.sub == "admin")
```

P- and G-policy is just like that:
```ini
p    role-1, domain-1, /rest/api/path, GET, allow
g    group-2, role-1, domain-1
```

So, we have this membership in Casbin
```
domain-1::role-1  <  group-2
```
and this membership in LDAP
```
group-1  <=  user-1, user-2
group-2  <=  user-2
```

My question is: how can I take into account group membership of user-1 and user-2 from LDAP?
So, to be able to evaluate
```
domain-1::role-1 < group-2 < user-2
```
Group membership in LDAP could be any

On the beginning of session I can request group membership of user-1 (group-1) or user-2 (group-1, group-2), but what next?

Should it be custom "RoleManager" (doing what?) or any simpler approach?
It just don't fit in my head although I suspect that solution is quite simple.

Thanks.

**Comment by hsluoyz** [comment]
@wndrr101, maybe you need to implement a custom LDAP role manager: https://casbin.org/docs/en/role-managers

**Comment by wndrr101** [comment]
I think I've found an answer (could be any easier??)

Since we're able to manipulate with "request" we can go for "grouping for ABAC" (no need for custom RoleManager just for groups acquisition, right?)

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g(r.sub, p.sub) || g2(r.sub.Group, p.sub)) && r.obj == p.obj && r.act == p.act
```

```ini
p, alice, data-1, read
p, bob, data-2, write
p, role-1, data-1, read
p, role-1, data-1, write
p, role-2, data-2, read

g, alice, role-1
g2, alice_group, role-1
g2, bob_group, role-2
```
And here we dynamically loading "group membership" via ABAC and using **g2** for role-groups membership checks (last request is the most interesting - inheritance checks do work for roles and ABAC)
```ini
alice, data-1, read
alice, data-2, read
bob, data-2, read
bob, data-2, write

{ Group: 'alice_group' }, data-1, read
{ Group: 'bob_group' }, data-1, read
{ Group: 'alice_group', Group: 'bob_group' }, data-2, read
```
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/65179083/100105455-717e7c00-2e78-11eb-86ca-8fb9753a0df8.png">


@hsluoyz , could you please answer, why am I not able to use **g1** for example for P-, G-policy and for model definition in web editor? Why setup like above on picture doesn't work _only_ with g2 (no **g** model, only **g2** everywhere - it doesn't work) and how many g's (g/g2/g4 - like this?) can be used in model and policy?

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/65179083/100106333-7c85dc00-2e79-11eb-8943-240fa51b9a2e.png">

Thanks.

**Comment by hsluoyz** [comment]
Glad that you found a solution by yourself! @nodece will answer for the Casbin-editor questions.

**Comment by hsluoyz** [comment]
@wndrr101 The model g naming convention is just defined as so: g, g2, g3, .. The code works by finding in such order and pattern.
