### ISSUE TITLE
RBAC filtering roles based on a domain

### ISSUE THREAD

**Issue by inamvar** [casbin/casbin#655]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
I have set up "Role definition with domains tenants" model and it works well. I need to get the list of all roles in a domain. getAllRoles() returns all roles for all domains that is not what I need. I tried function `GetFilteredNamedPolicy("p",1, "tenant_1")` but the result is not distinct for role name and the role names are repeated. is there a pretty way to get list of roles available in a specific domain?

**Your model:**

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom &&  keyMatch(r.obj, p.obj) && (r.act == p.act || p.act == "*")
```

**Your policy:**

```
p, admin, tenant_1, /route1, GET
p, admin, tenant_1, /route2, POST
p, customer, tenant_1, /route1,GET
p, merchant, tenant_2, /route1,GET
p, customer, tenant_2, /route1,GET

g, alice, admin, tenant_1
```
The result I expect for `tenant_1` is : `["admin","customer"]`

**Comment by hsluoyz** [comment]
Call: https://casbin.org/docs/en/management-api#getfilteredpolicy and extract the column out.

**Comment by hsluoyz** [comment]
Call: https://casbin.org/docs/en/management-api#getfilteredpolicy and extract the column out.
