### ISSUE TITLE
[Question] there are some confuse about the user constraint  permission?

### ISSUE THREAD

**Issue by colynn** [casbin/casbin#656]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

As described in the docs, [`casbin`](https://github.com/casbin/casbin) already support RBAC1 and  `RBAC with domains`.

For example, if I have a project, but there are many applications or environments within the project, is it more appropriate to use the application or environment as a constraint in this scenario?

If I didn't use constraints, is there a better solution for [`casbin`](https://github.com/casbin/casbin)?

**Comment by hsluoyz** [comment]
@colynn can you give more details about what kind of RBAC2 support you wants?

**Comment by colynn** [comment]
eg, support for constraint definitions for user and role latitude.

**Comment by hsluoyz** [comment]
@nodece @abichinger

**Comment by hsluoyz** [comment]
@colynn a constraint is something like user alice cannot have role A and role B at the same time. We will provide an init time checking (when an enforcer is initialized) for all constraints. It will panic if any constraints are violated. Does this sound OK?

**Comment by colynn** [comment]
@hsluoyz This is not how I envision it,  I can give an example as below,   

User Alice and use Jerry have the same role name role01 but have different resource constraint, 
then  role01  of we defined have `get Project List` resource operation,  but user Alice can see project 01 only,  user Jerry can see project 02 only. 

Note:  project 01/02 is a resource constraint of the user.

**Comment by hsluoyz** [comment]
@colynn Those're permissions, not RBAC constraint: https://ldapwiki.com/wiki/RBAC%20constraints It's about something like Separation of Duty.

**Comment by colynn** [comment]
Okay sorry,  `casbin` should not include this part, yeah?

**Comment by hsluoyz** [comment]
@colynn 

From your description:

```
User Alice and use Jerry have the same role name role01 but have different resource constraint,
then role01 of we defined have get Project List resource operation, but user Alice can see project 01 only, user Jerry can see project 02 only.

Note: project 01/02 is a resource constraint of the user.
```

I think you need the RBAC with Domain model: https://casbin.org/docs/en/supported-models

**Comment by colynn** [comment]
Okay, very thank you

**Comment by hsluoyz** [comment]
Closed as resolved.
