### ISSUE TITLE
RegexMatch on g2 (second RBAC system)

### ISSUE THREAD

**Issue by sebd71** [casbin/casbin#658]
Hello,
Below are my RBAC model and policies.
In order to reduce policies definition for an 'admin' subject / role, I would like to chain g2 + regexMatch on object :
 `p, admin, /projects/[0-9]+, (GET)|(POST)`

So matcher would be something like that :
m = g(r.sub, p.sub) && **g2(regexMatch(r.obj, p.obj))** && regexMatch(r.act, p.act)

Note that one solution would be to "hardcode" admin notion in matcher line but it's a not way for me to define 'admin' string statically in matcher line of model.

So how to set g2 + regexMatch applied on object ?
I also try to write a custom function without success. If a custom function is the solution, please help me to write it.

Thanks in advance for any help.
Seb.

**model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && regexMatch(r.act, p.act)
```

**policy:**

```
p, manager_123, /projects/123, (GET)|(POST)
p, developer_123, /projects/123, GET
p, manager_456, /projects/456, (GET)|(POST)
p, developer_456, /projects/456, GET

p, admin, /projects/[0-9]+, (GET)|(POST)

g, alice, manager_123
g, bob, developer_456
g, seb, admin

g2, /apps/111, /projects/123
g2, /apps/222, /projects/123
g2, /apps/444, /projects/456
g2, /builds/110, /apps/111
g2, /builds/220, /apps/222
```

**request(s):**

```
alice, /projects/123, GET  ---> true
alice, /projects/123, POST ---> true
alice, /projects/456, GET ---> false
alice, /projects/456, POST ---> false
alice, /apps/111, GET ---> true
alice, /apps/222, GET ---> true
alice, /builds/110, GET ---> true
alice, /builds/220, GET ---> true

seb, /projects/123, GET ---> false (expected: true)
seb, /projects/456, GET ---> false (expected: true)
seb, /apps/111, GET ---> false (expected: true)
seb, /apps/444, GET ---> false (expected: true)
seb, /builds/110, GET ---> false (expected: true)
seb, /builds/220, GET ---> false (expected: true)
```

**Comment by hsluoyz** [comment]
@nodece

**Comment by sebd71** [comment]
Any help? 
Thanks.

**Comment by hsluoyz** [comment]
@sebd71 I think you need this: https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac

**Comment by hsluoyz** [comment]
Closed as solved.
