### ISSUE TITLE
How to query for all permissions that a user has?

### ISSUE THREAD

**Issue by jon-whit** [casbin/casbin#66]
Consider two different cases:
1. Forward policy evaluation - Can a user under a certain domain perform the requested action on the given resource under some environmental conditions?

2. Reverse policy evaluation - What actions can a user under a certain domain perform on a given resource?

My authorization server needs to define a mechanism to support these two different types of queries in addition to a hybrid RBAC/ABAC access control model. I *think* Casbin can do this based on the examples and documentation I have seen, but I was hoping you may be able to provide some more examples. If I had a group of users who had a set of roles and also unique attribute based policy rules that applied to them, what would that look like with the Casbin model syntax? For these purposes, all actions can be assumed to be HTTP/RESTful actions (GET, PUT, POST, DELETE, etc..) and the resources are either API endpoints or web resources.

**Comment by hsluoyz** [comment]
> Forward policy evaluation - Can a user under a certain domain perform the requested action on the given resource under some environmental conditions?

This is the normal usage of Casbin: call ``Enforcer.Enforce()`` to check whether a tuple (subject, object, action) is allowed.

> Reverse policy evaluation - What actions can a user under a certain domain perform on a given resource?

You have two ways to do it. 1) enumerate all actions and call ``Enforcer.Enforce()`` for each action to get the allowed actions. 2) call [GetFilteredPolicy](https://github.com/casbin/casbin/blob/c413903cd2e6366f3b0b887eed3f4224c9e1d3bf/management_api.go#L67:20) to get the filtered raw policy rules. And then parse out the actions from them on your own. Or you can just query the database used to store Casbin rules if you like.

**Comment by jon-whit** [comment]
@hsluoyz that's awesome! Thanks :)

**Comment by Huweicai** [comment]
It's seems that GetFilteredPolicy  not work for RBAC models, for example, if have the polices below:
```
p,viewer,books,read
p,viewer,users,read
g,alice,viewer
p,alice,users,read

```
GetFilteredPolicy(0, "alice") will only return the 'users' authorized throgh ABAC, however alice do hav permissions to read 'books'.
Any better ways to get all authorized permissions in a RBAC system?

**Comment by hsluoyz** [comment]
@Huweicai please create new issue for your problem instead of digging up this old one
