### ISSUE TITLE
Performance issue for too many policies and offering Casbin as a service

### ISSUE THREAD

**Issue by hatami57** [casbin/casbin#660]
As I've read some parts of the source code, it seems like the library is loading all the policies at the beginning (as in LoadPolicy method).

If we have millions of policies for hundreds of thousands of users (or millions) for several applications, is it really required to load all the policies beforehand?

When I need to check permission for a specific user, does the engine need all other users policies to decision and produce the result? So why database adapter load them all at once?

There are two main question when we want to use Casbin to make an authorization app as a service which can support multi-tenancy (if it's really possible to use it for such a scenario):

1. Can Casbin work properly with the least data needed from database, when we need to check a user permission for a resource in a specific tenant? what are the least needed data?

2. Can Casbin data structure uses cache to make its decision more performant, along side database adaptor?

**Comment by hsluoyz** [comment]
Hi @hatami57 

For 1, see: https://casbin.org/docs/en/policy-subset-loading

For 2, see: https://github.com/casbin/casbin/blob/master/enforcer_cached.go

**Comment by hatami57** [comment]
Hi @hsluoyz,

Thank you for your response. I will check the links to see if they answer my questions.
By the way I came across one of your projects named [casbin-server](https://github.com/casbin/casbin-server). Is that do what I asked here? Can it be used in production environment as a service?!

**Comment by hsluoyz** [comment]
@hatami57 yes, there's already production use for Casbin-Server, see more details: https://casbin.org/docs/en/service

**Comment by hsluoyz** [comment]
Closed as resolved.
