### ISSUE TITLE
In casbin/dbal-adapter, the loadPolicy method select column is different ?

### ISSUE THREAD

**Issue by 894480109** [casbin/casbin#661]
In casbin/dbal-adapter, the loadPolicy method runs select the column ptype,  but the table is p_type, why ?

**Comment by hsluoyz** [comment]
@894480109 which `casbin/dbal-adapter`? Can you give a URL?

**Comment by 894480109** [comment]
> @894480109 which `casbin/dbal-adapter`? Can you give a URL?

Of course, it is in the php packagist, the URL is https://packagist.org/packages/casbin/dbal-adapter
The file is src/Adapter.php，on Line 117,  Thanks!

**Comment by hsluoyz** [comment]
@894480109 please send the issue to: https://github.com/php-casbin/dbal-adapter/issues instead. Closed here.

**Comment by 894480109** [comment]
> @894480109 please send the issue to: https://github.com/php-casbin/dbal-adapter/issues instead. Closed here.

ok，thanks
