### ISSUE TITLE
[Question] Can I split to multiple policy files and load into casbin?

### ISSUE THREAD

**Issue by bill0119** [casbin/casbin#662]
Can I split to multiple ploicy files and load into casbin?

model.conf
```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

policy1.csv
```
p, alice, data1, read
```

policy2.csv
```
p, alice, data2, read
```

How to load multiple policy into casbin?
```
e, err := casbin.NewEnforcer("./model.conf", "./policy1.csv")
//load policy2.csv into casbin...
```

**Comment by hsluoyz** [comment]
Hi @bill0119 

The built-in file adapter code is here: https://github.com/casbin/casbin/blob/master/persist/file-adapter/adapter.go

You can load multiple CSV files on your own and call the AddPolicy() API: https://casbin.org/docs/en/management-api#addpolicy to add rules into the enforcer.

Or you can use a database-based adapter.

**Comment by hsluoyz** [comment]
Resolved.
