### ISSUE TITLE
[Question]strSlice

### ISSUE THREAD

**Issue by maxiloEmmmm** [casbin/casbin#663]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Your answer here
version: github.com/casbin/casbin/v2 v2.17.0

```go
rule := []string{"role1", "obj", "act"}
e.AddPolicy(rule)
//that's ok
rule[0] = "role2"
e.AddPolicy(rule)
//adapter data ok
//e.model["p"]["p"].Policy is invaild, role1,obj,act not exist role2,obj,act exist
pass, _ := e.Enforce("role1", "obj", "act")
//pass is false
```
there will make role2 replace role1 for e.model["p"]["p"].Policy
https://github.com/casbin/casbin/blob/11b54bfb32cc2fff2bbb46fba1ffbbd26ec3cc34/management_api.go#L135-L138
Q1:
why not deal with here for `params[0].([]string)`
https://github.com/casbin/casbin/blob/11b54bfb32cc2fff2bbb46fba1ffbbd26ec3cc34/management_api.go#L139-L142

**Comment by hsluoyz** [comment]
Closed for now.

**Comment by maxiloEmmmm** [comment]
slice会造成引用问题你看不到么？
麻烦能好好看看问题？

**Comment by maxiloEmmmm** [comment]
@hsluoyz  thk

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casbin/pull/671
