### ISSUE TITLE
[Question] Possible to filter table data based on who is asking to read it?

### ISSUE THREAD

**Issue by avikagg** [casbin/casbin#668]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
We have a big table where users should see only data points which are allowed for them (enforced using policy).
Instead of going through each row and figuring out, is it possible to do this in batch manner.

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, alice, data1, read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write

g, alice, data2_admin
```

**Your request(s):**

```
alice, data2, read ---> false (expected: true)
```

**Comment by hsluoyz** [comment]
Duplicated with: https://github.com/casbin/casbin/issues/617
