### ISSUE TITLE
[question]data race?

### ISSUE THREAD

**Issue by zhaitianduo** [casbin/casbin#67]
Hi, I got a concern on multi goroutine reads and writes.

If I use a watcher to update new rules or new roles, it will reload the policies.

```go
// SetWatcher sets the current watcher.
func (e *Enforcer) SetWatcher(watcher persist.Watcher) {
	e.watcher = watcher
	watcher.SetUpdateCallback(func (string) {e.LoadPolicy()})
}
```

When `LoadPolicy`, `BuildRoleLinks` is executed. In `defaultRoleManager`, there is a map maintained all the roles here.

```go
type defaultRoleManager struct {
	allRoles map[string]*Role
         level    int
}
```

If I have a request to query roles at the same time, it's updating the map. There is a data race here?

Thank you~

**Comment by hsluoyz** [comment]
You can use ``SyncedEnforcer`` to avoid the data race: https://github.com/casbin/casbin/blob/master/enforcer_synced.go#L64

**Comment by zhaitianduo** [comment]
OK, thank you!

BTW, when will the next release version rolled out?

**Comment by zhaitianduo** [comment]
I see some methods of `SyncedEnforcer` is still not multi-thread safe. Like `GetPermissionsForUser`.

Any workaround for this?

**Comment by hsluoyz** [comment]
You can use this synced RBAC API: https://github.com/casbin/casbin/blob/master/rbac_api_synced.go

Next version won't be too soon because there're still no enough improvements. You can specify the latest commit number in systems like glide.

**Comment by zhaitianduo** [comment]
OK, thank you for the quick enhancement!
