### ISSUE TITLE
[Feature] Extracting variables from paths like `/foo/:id`

### ISSUE THREAD

**Issue by fr3fou** [casbin/casbin#673]
**Is your feature request related to a problem? Please describe.**
There currently isn't a built in way to extract variables from an HTTP URL Path (`/foo/:id`). It is incredibly useful when doing ABAC and want to check whether a subject has ownership of a given object.

```csv
p, r.sub.Role == 'blog_writer' && id in r.sub.Posts, /post/:id, (PUT|DELETE)
# - - - - - - - - - - - - - - - - ^ here, this doesn't work
```

**Describe the solution you'd like**
There needs to be a function or some other that let's you extract given variables from the object path or any generic string.

- Accessing the policy's object `id` variable directly
```csv
p, r.sub.Role == 'blog_writer' && p.obj.id in r.sub.Posts, /post/:id, (PUT|DELETE) #
```

- Having a function that does the same as the previous approach
```csv
p, r.sub.Role == 'blog_writer' && urlParam(p.obj, 'id')  in r.sub.Posts, /post/:id, (PUT|DELETE)
# or
p, r.sub.Role == 'blog_writer' && urlParam('/post/:id', 'id')  in r.sub.Posts, /post/:id, (PUT|DELETE)
# this approach would involve copy pasting the object, which can be annoying / easy to have a mismatch between both
```

**Describe alternatives you've considered**
Making a function in the "host" language for every parameter that I have.

**Comment by hsluoyz** [comment]
Like we discussed in Gitter: https://gitter.im/casbin/Lobby, we need to add the built-in `keyGet()` functions.

For example, for `keyMatch()`, we will have `keyGet()`. For `keyMatch2()`, we have `keyGet2()`.

**Comment by RobotHuang** [comment]
Could I try to address this issue?

**Comment by hsluoyz** [comment]
@RobotHuang plz go ahead.

**Comment by fr3fou** [comment]
When can we expect docs?

**Comment by hsluoyz** [comment]
@fr3fou yeah, I think @closetool is working on the docs.

**Comment by hsluoyz** [comment]
@fr3fou docs ready now: https://github.com/casbin/casbin-website/issues/149
