### ISSUE TITLE
[Question] Whether a nested struct supported in ABAC model

### ISSUE THREAD

**Issue by yangzhares** [casbin/casbin#677]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Want a nested struct supported in ABAC model, but as follow stuff described, it didn't work. Due to i don't find a doc that guides how to use a nested struct in ABAC model, so the format of requests is wrong, i'm not sure, please help check.

**Model: ABAC**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == r.obj.Owner && r.obj.Name == 'resource' && r.Obj.Attributes.Age == 15
```

**Policy:**

```
No policy
```

**Request(s):**

```
alice, { Owner: 'alice', Name: 'resource', Attributes: {Age: 15}} # expect true, but got "Cannot read property 'Attributes' of undefined"
bob, { Owner: 'bob', Name: 'resource', Attributes: {Age: 16}}
```

**Comment by hsluoyz** [comment]
@closetool can you help follow up this issue?

**Comment by closetool** [comment]
sure

**Comment by closetool** [comment]
@yangzhares I believe you should change ``r.Obj.Attributes.Age`` into ``r.obj.Attributes.Age``

**Comment by closetool** [comment]
![image](https://user-images.githubusercontent.com/52988625/104540384-551de500-565a-11eb-8df6-5a77a7c689c8.png)

**Comment by yangzhares** [comment]
yeah, it works as my expectation, sorry for typo
