### ISSUE TITLE
[Bug] Severe Performance issues when number of policies is high

### ISSUE THREAD

**Issue by arafat-java** [casbin/casbin#681]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
When the number of policies high (I tried with 1.6 million policy records), it takes around **12-18 seconds** to create the Enforcer object using ==> casbin.NewEnforcer("model.conf", a)
I tried this with mongo db as well as JDBC using MySQL
With Mongo DB it takes between 12-15 seconds
With JDBC it takes between 14-18 seconds

Also to check permissions ( e.Enforce("Alice", "data1", "read") ) it takes around **1.2 to 1.5 seconds** 

**To Reproduce**
1. Insert 16,00,000 records in casbin_rule table
2. Use any of the programs either for mongo or JDBC to check the performance

**Expected behavior**
Both the actions (creating Enforcer and checking permissions) should be in milli seconds

**Environment Details**
 - OS: Windows 10, RAM 16GB
 - MongoDB : v4.4.3
 - MySQL : v8.0

**Sample programs**
Attaching the following sample files for creating data dump and data query
- main_mongo_datadump.go : This can be used to create test data in mongo
- main_mongo_query.go : This can be used to query permissions in mongo
- main_jdbc_query.go : This can be used to query permissions in MySQL

**Additional context**
We are planning to use casbin for object level permissions in cloud based environment where we would be having multiple tenants and each tenant would be having millions of objects and each object having 10-15 permissions 
So even the limit of 1.6 M is on the lower side and we expect to have much more that that number of policy records in persistence

[go-casbin-example.zip](https://github.com/casbin/casbin/files/5837024/go-casbin-example.zip)

**Comment by hsluoyz** [comment]
@arafat-java can you also provide the example model and policy that contains:

1. object 1 having 10-15 permissions
2. object 2 having 10-15 permissions
3. object 3 having 10-15 permissions
..

I think we can have a way to reduce the 16,00,000 rules into < 100.

**Comment by arafat-java** [comment]
Thanks @hsluoyz 

Attached are the example model and policy 

[casbin_model_policy.zip](https://github.com/casbin/casbin/files/5840686/casbin_model_policy.zip)

**Comment by hsluoyz** [comment]
Better just posted here, because it's not long.

Model:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

Policy:

```csv
p, Jack, EarlyBirdOffer, read
p, Jill, EarlyBirdOffer, write
p, John, EarlyBirdOffer, read
p, rdtUsr001, EarlyBirdOffer, read
p, rdtUsr002, EarlyBirdOffer, write
p, rdtUsr003, EarlyBirdOffer, read
p, rdtUsr004, EarlyBirdOffer, write
p, rdtUsr005, EarlyBirdOffer, read
p, rdtUsr006, EarlyBirdOffer, write
p, rdtUsr007, EarlyBirdOffer, write
p, rdtUsr008, EarlyBirdOffer, read
p, rdtUsr009, EarlyBirdOffer, read
p, tstUsr001, EarlyBirdOffer, write
p, tstUsr002, EarlyBirdOffer, write
p, tstUsr003, EarlyBirdOffer, write
p, tstUsr004, EarlyBirdOffer, read
p, tstUsr005, EarlyBirdOffer, read
p, tstUsr006, EarlyBirdOffer, write
p, tstUsr007, EarlyBirdOffer, write
p, tstUsr008, EarlyBirdOffer, read
p, FinalOuterGroup, EarlyBirdOffer, write

p, rdtUsr00111, ChristmasOffer, read
p, rdtUsr00112, ChristmasOffer, read
p, rdtUsr00113, ChristmasOffer, read
p, rdtUsr00114, ChristmasOffer, read
p, rdtUsr00115, ChristmasOffer, read
p, rdtUsr00116, ChristmasOffer, read
p, rdtUsr00117, ChristmasOffer, read
p, rdtUsr00118, ChristmasOffer, read
p, rdtUsr00119, ChristmasOffer, read
p, tstUsr00111, ChristmasOffer, read
p, tstUsr00112, ChristmasOffer, read
p, tstUsr00113, ChristmasOffer, write
p, tstUsr00114, ChristmasOffer, read
p, tstUsr00115, ChristmasOffer, read
p, tstUsr00116, ChristmasOffer, write
p, tstUsr00117, ChristmasOffer, write
p, tstUsr00118, ChristmasOffer, read
p, FinalOuterGroup, ChristmasOffer, write

p, John, NewYearOffer, read
p, Alice, NewYearOffer, read
p, rdtUsr00111, NewYearOffer, write
p, rdtUsr002, NewYearOffer, write
p, rdtUsr003, NewYearOffer, write
p, rdtUsr00114, NewYearOffer, write
p, rdtUsr00115, NewYearOffer, write
p, rdtUsr006, NewYearOffer, write
p, rdtUsr00117, NewYearOffer, write
p, rdtUsr00118, NewYearOffer, write
p, rdtUsr009, NewYearOffer, write
p, tstUsr00111, NewYearOffer, write
p, tstUsr002, NewYearOffer, write
p, tstUsr00113, NewYearOffer, write
p, tstUsr00114, NewYearOffer, write
p, tstUsr005, NewYearOffer, write
p, tstUsr00116, NewYearOffer, write
p, tstUsr007, NewYearOffer, write
p, tstUsr00118, NewYearOffer, write
p, Grp3, NewYearOffer, write

g, Jack, InnerGroup
g, InnerGroup, OuterGroup
g, OuterGroup, FinalOuterGroup
g, Jill, Grp1
g, Grp1, Grp2
g, Grp2, Grp3
g, John, Grp3
```

**Comment by hsluoyz** [comment]
@arafat-java is there any pattern for who can read and who can write? e.g., by default 99.9% of users can only read. Some staff people can write, or the owner of a resource can write.

If it's just purely ~50% of random usernames can read and the other half can write, you know that there's no cheap "short-cut" way to use some simple rules to abstract the behinding logic.

One optimization would be doing a pre-filtering on the rules based on the username. For example, if r.sub is rdtUsr00111, then we pre-filter out the related two p rules:

```
p, rdtUsr00111, ChristmasOffer, read
p, rdtUsr00111, NewYearOffer, write
```

and only use these 2 p rules together with all g rules to do the enforcement. So we don't need to run millions of p rules for a single check.

**Comment by arafat-java** [comment]
@hsluoyz I assume that by "_pre-filtering on the rules based on the username_" you mean `e.getFilteredPolicy(0, "usr1")`

If that is correct how do I do the other part _"only use these 2 p rules together with all g rules to do the enforcement. So we don't need to run millions of p rules for a single check"_

**Comment by hsluoyz** [comment]
> But if we had that pattern of say 90% read and only some people can write, how would we have optimized the policies

I suggest making a RBAC role like `readers` to hold all users that can read and similar for `writers`. Then let the users have the role.

```
p, readers, NewYearOffer, read

g, John, readers
g, Alice, readers
```

This will speed up things because Casbin's RBAC is implemented by a role inheritance tree (as a cache). So given a user like `Alice`, Casbin only uses O(1) time to query the RBAC tree for role-user relationship and do enforcement. If your g rules don't change often, then the RBAC tree won't need to update.

> Also I assume that by "pre-filtering on the rules based on the username" you mean e.getFilteredPolicy(0, "usr1")

Yes, very similar but done with Casbin built-in code. This feature is just on my mind and not implemented yet. But it's not hard. Just make a cache map to hold the rules for each user.

But I think maybe the above RBAC tree idea is better.

**Comment by arafat-java** [comment]
> Yes, very similar but done with Casbin built-in code. This feature is just on my mind and not implemented yet

Any timeline when this is implemented into casbin

Also can you please give some pointer regarding my following question from previous post

> how do I do the other part "only use these 2 p rules together with all g rules to do the enforcement. So we don't need to run millions of p rules for a single check"

**Comment by hsluoyz** [comment]
@arafat-java why don't use the RBAC tree idea?

**Comment by arafat-java** [comment]
Actually our use case does not fit that scenario 

> if we had that pattern of say 90% read and only some people can write, how would we have optimized the policies

We would have ~50% of random usernames can read and the other half can write,
So we cant use that RBAC tree

We would be having 50%

**Comment by arafat-java** [comment]
After digging in a bit further I realize that all the policies (1.6 M ) are read at time of Enforcer object creation and are held in local memory cache and that seems to be the bottleneck in our case. Because after creating indexes on the casbin_rule table when I fetch a record using vanilla JDBC program with v0, v1 and v2 in where clauses it returns me response within 4mS whereas the single enforce() call is taking more than 1.8s

Is it possible that the behavior of caching all the policies be changed to reading records whenever the enforce() call is made so that we leverage the speed that we get out of DB Indexing and that the enforce() method instead of taking 1.8s returns response in milli seconds ?

**Comment by hsluoyz** [comment]
@arafat-java can you first try `e.getFilteredPolicy(0, "usr1")`?

**Comment by arafat-java** [comment]
@hsluoyz as I said earlier, I am not very sure how to use enforce() after e.getFilteredPolicy(0, "usr1")
Can please give some pointers for the same

**Comment by hsluoyz** [comment]
@arafat-java see example code at: https://casbin.org/docs/en/policy-subset-loading

- https://github.com/casbin/gorm-adapter/issues/61
- https://github.com/casbin/gorm-adapter/pull/62/files

https://github.com/casbin/casbin/blob/d495a30e42d36ab73a63542ee7a4ee6be1b890d3/enforcer.go#L154-L175

**Comment by arafat-java** [comment]
Thanks @hsluoyz 
Filtered policies work at lightening speed

**Comment by filwaline** [comment]
> > But if we had that pattern of say 90% read and only some people can write, how would we have optimized the policies
> 
> I suggest making a RBAC role like `readers` to hold all users that can read and similar for `writers`. Then let the users have the role.
> 
> ```
> p, readers, NewYearOffer, read
> 
> g, John, readers
> g, Alice, readers
> ```
> 
> This will speed up things because Casbin's RBAC is implemented by a role inheritance tree (as a cache). So given a user like `Alice`, Casbin only uses O(1) time to query the RBAC tree for role-user relationship and do enforcement. If your g rules don't change often, then the RBAC tree won't need to update.
> 
> > Also I assume that by "pre-filtering on the rules based on the username" you mean e.getFilteredPolicy(0, "usr1")
> 
> Yes, very similar but done with Casbin built-in code. This feature is just on my mind and not implemented yet. But it's not hard. Just make a cache map to hold the rules for each user.
> 
> But I think maybe the above RBAC tree idea is better.

What if g rules change often?
For example, while using **RBAC with resource roles** model(*for fine-grained access control*), numbers of resources keep growing, so as `g2` rules.

**Comment by hsluoyz** [comment]
@filwaline then maybe you need to update the RBAC tree in an incremental way: just add or remove specific nodes in the tree instead of rebuild the tree from scratch.

**Comment by mato51** [comment]
Hello, any hint on how to add specific nodes in the tree?

**Comment by hsluoyz** [comment]
@closetool we need to add some docs for the Role Manager API.

**Comment by hsluoyz** [comment]
@mato51 

> Hello, any hint on how to add specific nodes in the tree?

Call AddLink(): https://casbin.org/docs/en/rolemanager-api#addlink

**Comment by 204070** [comment]
I'm currently implementing casbin and thinking about this scale issue for millions of users. I think putting so many user policies will take time to load and take lots of memory space. Has anybody ever managing a user's roles outside casbin and just using casbin to check the role permissions.

Saving role permissions alone should take less space than saving user roles. Casbin will just do the permission checks for the role which is what it's best at.
