### ISSUE TITLE
[Question] Best practices to use Enforcer in a cloud based multi tenant environment

### ISSUE THREAD

**Issue by arafat-java** [casbin/casbin#682]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
We are planning to use casbinin a cloud based solution and the policies will be stored in RDBMS. So what are the recommendations pertaining tenant policies separation. Should we have one Enforcer per tenant ?

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, alice, data1, read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write

g, alice, data2_admin
```

**Comment by hsluoyz** [comment]
Answered here: https://github.com/casbin/casbin/issues/681
