### ISSUE TITLE
[Question] Paid support for Casbin

### ISSUE THREAD

**Issue by arafat-java** [casbin/casbin#683]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Do we have some sort of paid premium support for Casbin?
Maybe for help related to using Casbin properly for our scenario or for sorting other queries

**Comment by hsluoyz** [comment]
Hi @arafat-java , you can choose to sponsor us via GitHub Sponsors: https://github.com/sponsors/hsluoyz . The last few tiers will show the support level. You can also ping me at Gitter for any further questions.
