### ISSUE TITLE
[Question] Using g3 in role_definition to group act

### ISSUE THREAD

**Issue by gonzalad** [casbin/casbin#684]
**What's your scenario? What do you want to achieve?**

Hello, 

I have played today (for the first time) with casbin (very nice project !)  

I've used both g and g2 in the role_definition.

From what I understand, I can use g and g2 as group of users and group of objects.

I need to have the notion of group of actions.

So I used g2 to have some action groups in the casbin editor (g2(p.act, r.act))

I've tried to use some g3 prefix to group users, but no way.

Is there a way to have group of users, group of obj and group of act ?
 
**Your model:**

This works:

```ini
[request_definition]
r = sub, obj, act
 
[policy_definition]
p = user, obj, act
 
[role_definition]
g = _, _ 
g2 = _, _
 
[policy_effect]
e = some(where (p.eft == allow))
 
[matchers]
m = r.sub == p.user && g(p.obj, r.obj) && g2(p.act, r.act)
```

This does not work:

```ini
[request_definition]
r = sub, obj, act
 
[policy_definition]
p = user, obj, act
 
[role_definition]
g = _, _ 
g2 = _, _
g3 = _, _

[policy_effect]
e = some(where (p.eft == allow))
 
[matchers]
m = g(p.obj, r.obj) && g2(p.act, r.act) && g3(r.sub == p.user)
```

**Your policy:**

```
p, toto, MAI, GESTIONNAIRE
p, toto, DRT, ADMIN
p, tutu, DRT, GESTIONNAIRE
p, tata, MAI, GESTIONNAIRE
 
g, MAI, OM:OF1
g, MAI, OM:F1
g, DRT, OM:F2
g2, GESTIONNAIRE, COF_ObjetMaquette_Lire
g2, GESTIONNAIRE, COF_ObjetMaquette_Modifier
g2, ADMIN, AUTHZ_Habilitation_Detruire
```

**Request Samples:**

```
toto, OM:OF1, COF_ObjetMaquette_Lire
toto, OM:OF2, COF_ObjetMaquette_Lire
toto, OM:F1, COF_ObjetMaquette_Modifier
toto, OM:F2, COF_ObjetMaquette_Modifier
tutu, OM:F1, COF_ObjetMaquette_Lire
tata, OM:OF1, COF_ObjetMaquette_Lire
```

Thanks !

**Comment by hsluoyz** [comment]
@gonzalad this is wrong: `g3(r.sub == p.user)`, should be `g3(r.sub, p.user)`. `g3` is just a function with 2 or 3 arguments.

**Comment by gonzalad** [comment]
thanks @hsluoyz !

It works fine now
