### ISSUE TITLE
[Feature] Multiple policy operations as a transaction

### ISSUE THREAD

**Issue by fgblomqvist** [casbin/casbin#688]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Is your feature request related to a problem? Please describe.**
If you have multiple changes you want to make to the policy, but you want to ensure that they happen atomically, you currently can't. One example would be if you wanted to replace the policy for a specific subject. You can delete all of the rules and then add a new set of rules, however, it's possible that the adding fails and you end up with no rules for that subject.

**Describe the solution you'd like**
I'm open to ideas here. This is obviously quite trivial to achieve using most DB adapters, however, casbin would have to add a layer of abstraction. Perhaps being able to pass a list of operations to the adapter? Alternatively, doing something similar to what the DB libraries do and allow you to pass a function (that e.g. receives a parameter `tx interface{}` on which you can do all the usual operations).

Either way, any solution here would require quite a bit of work, both to Casbin and to any adapters.

**Describe alternatives you've considered**
Adding a simple `UpdatePolicyForSubject` method to both the adapter and casbin. Doesn't solve the larger issue though.

**Comment by hsluoyz** [comment]
@fgblomqvist are you looking for an atomic UpdatePolicies() API like this: https://github.com/casbin/casbin/issues/690 ?

**Comment by fgblomqvist** [comment]
For the specific example, it would be more like a "SetPolicies()" API which would wipe all the existing policies for a subject, and then set them to whatever you passed. I don't want to have to know which policies I am replacing, just that the final result looks like what I'm passing in.

**Comment by hsluoyz** [comment]
@fgblomqvist I think `SavePolicy()` is exactly what you need?

1. Call `e.EnableAutoSave(false)` to disable AutoSave.
2. Modify the policy rules in memory via adding, removing policy API. The rules will not sync to DB as AutoSave is disabled.
3. Call `SavePolicy()` to replace all DB rules with all memory rules.
4. Call `e.EnableAutoSave(true)` to enableAutoSave. (if you want)

**Comment by fgblomqvist** [comment]
If I disable auto save, won't that disable auto save for the whole instance of the enforcer? As in, if someone tries to use an endpoint that assumes that auto-save is on, things will go wrong.

That being said, I guess the solution then is to not use auto-save at all, and always save manually. However, I'm not sure what casbin uses as the source of truth. Is it the in-memory data or is it the adapter data? I thought it always used the in-memory data (after loading from the db), which would mean that fiddling with auto-save does not solve this problem at all.

**Comment by hsluoyz** [comment]
@fgblomqvist  OK. What about this:

```go
policies := e.GetPolicy()
e.UpdatePolicies(policies, newPolicies)
```

**Comment by fgblomqvist** [comment]
What does that operation do? Remove all the policies in the first arg and add all the ones in the second arg?

**Comment by fgblomqvist** [comment]
In that case I'm guessing you'd have to first filter out all the policies for the subject you're trying to modify, then pass those as the first arg to UpdatePolicies.

**Comment by hsluoyz** [comment]
See: https://casbin.org/docs/en/management-api#updatepolicies

**Comment by fgblomqvist** [comment]
Those docs are too vague.
"UpdatePolicies updates all old policies to new policies." sounds like it tries to match the new policies with the old policies and individually update the values of each one. I don't have time to dig into the code atm but maybe I can do so later to find out what it actually does. If it does anything else than the above it should imo not be named `UpdatePolicies` since in that case it's not actually updating existing policies.

**Comment by typhoonbb** [comment]
It seem that transaction commit policy is not support, Can I just manually update the database with db  transaction, and call e.LoadPolicy(), is there any problem?

**Comment by nodece** [comment]
> It seem that transaction commit policy is not support, Can I just manually update the database with db transaction, and call e.LoadPolicy(), is there any problem?

No problem. The transaction feature depends on the adapter, you should check whether the adapter supports that.

**Comment by dahu33** [comment]
> @fgblomqvist OK. What about this:
> 
> ```go
> policies := e.GetPolicy()
> e.UpdatePolicies(policies, newPolicies)
> ```

For reference, this won't work to set / update the policies of a subject as the length of the "old" policies need to be the same as the "new" policies (which may not be the case when you set / update the policies of a subject)... In its current state, the `UpdatePolicies` ManagementAPI is pretty much useless IMO. So far, I didn't find any workable solution outside of the inefficient `e.LoadPolicy()`...

**Comment by arafat-java** [comment]
Is this finally solved?

My requirement is exactly as follows

> 
For the specific example, it would be more like a "SetPolicies()" API which would wipe all the existing policies for a subject, and then set them to whatever you passed. I don't want to have to know which policies I am replacing, just that the final result looks like what I'm passing in.

_Originally posted by @fgblomqvist in https://github.com/casbin/casbin/issues/688#issuecomment-768787523_

But I cant use 
1. SavePolicy because that wipes out the database
2. UpdatePolicies because that just handles the updates to existing policies of an object. If there are addition/deletions then that is not hanldled

**Comment by hsluoyz** [comment]
@dahu33 @arafat-java can you send a new GitHub issue and describe your specific problem, so we could track its progress? Thanks.

**Comment by hsluoyz** [comment]
@dahu33 @arafat-java moved to here: https://github.com/casbin/casbin/issues/728

**Comment by arafat-java** [comment]
> 
> 
> @dahu33 @arafat-java can you send a new GitHub issue and describe your specific problem, so we could track its progress? Thanks.

@hsluoyz Raised https://github.com/casbin/casbin/issues/731
