### ISSUE TITLE
[question][enhancement]Minio/AWS S3 adapter for casbin

### ISSUE THREAD

**Issue by AleF83** [casbin/casbin#69]
I found that there are file adapter and xorm-adapters.
Do you have another adapter types? Like minio/s3?
If not, I want to implement one.

**Comment by hsluoyz** [comment]
AFAIK, there is no Minio or Amazon S3 adapters. The list in README is all I know. New adapters are welcome!

**Comment by AleF83** [comment]
I've implemented [minio adapter](https://github.com/Soluto/casbin-minio-adapter).
Can you take a look please?
Thanks!

**Comment by hsluoyz** [comment]
I ran ``adapter_test.go``, and got this error:

```
GOROOT=C:\Go #gosetup
GOPATH=C:\GoPath #gosetup
C:\Go\bin\go.exe test -c -i -o C:\Users\luo\AppData\Local\Temp\___adapter_test_go.exe github.com/Soluto/casbin-minio-adapter #gosetup
# github.com/fsouza/go-dockerclient
..\..\fsouza\go-dockerclient\distribution.go:14:53: undefined: registry.DistributionInspect
..\..\fsouza\go-dockerclient\swarm_configs.go:35:2: undefined: swarm.ConfigSpec

Compilation finished with exit code 2
```

``distribution.go`` seems to refer to the deprecated Docker source: ``github.com/docker/docker/api/types/registry``, which is 404 in GitHub now. Can you fix it?

**Comment by AleF83** [comment]
It works for me and passed travis CI.
Do you have `Docker` on your machine?

I used dockertest package to set up Minio server docker container.
Maybe you need to run
```
go get gopkg.in/ory-am/dockertest.v3
```
before running the tests

**Comment by hsluoyz** [comment]
OK. I believe my OS doesn't have the regular Docker as Linux. Seems good as it passed Travis CI. Already added to the list: https://github.com/casbin/casbin#policy-persistence
