### ISSUE TITLE
[Question] Case Insensitive Policy Enforcement

### ISSUE THREAD

**Issue by arafat-java** [casbin/casbin#694]
**What's your scenario? What do you want to achieve?**
I would like my user ids and group ids match to be case insensitive while checking permissions

So if '**userABC**' is given '**read**' permissions on object '**objXYZ**' 
When I try to check '**read**' permissions for user  '**userABC**' on object  '**objXYZ**' but instead of  '**userABC**' I use  '**UserAbc**' the system should still return me true

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, alice, data1, read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write

g, alice, data2_admin
```

**Your request(s):**

```
ALICE, data2, read ---> false (expected: true)
```

**Comment by hsluoyz** [comment]
@arafat-java the most simple way is when you pass args into e.Enforce(), just lower-case them. You can also define a custom matcher function like `toLower()` and use it in matcher expression.

**Comment by arafat-java** [comment]
Thanks @hsluoyz for the prompt response.
Is there any place where I can get help/pointers for writing custom matchers apart from https://casbin.org/docs/en/syntax-for-models

**Comment by hsluoyz** [comment]
https://casbin.org/docs/en/function

**Comment by shridhar-purandare** [comment]
@arafat-java : How did you solve it? As writing function does not work on user although it works on group names.
