### ISSUE TITLE
[Bug] Permission enforce is not considering the user permissions inherited via groups when using FilteredPolicy approach

### ISSUE THREAD

**Issue by arafat-java** [casbin/casbin#695]
**Describe the bug**
As suggested in issue https://github.com/casbin/casbin/issues/681, for performance enhancements we are using filtered policies.
That solved the performance  issue, however now we have another issue that the enforce is not considering the user permissions inherited via groups 

**To Reproduce**
1. Insert 3 records into mysql as follows
mysql> SELECT * FROM `casbin_rule` where p_type = 'g' or v1='data1' or v1='data2';
```
+---------+--------+-------------+-------------+-------+------+------+------+
| id      | p_type | v0          | v1          | v2    | v3   | v4   | v5   |
+---------+--------+-------------+-------------+-------+------+------+------+
| 1600004 | g      | alice       | data2_admin | NULL  | NULL | NULL | NULL |
| 1600006 | p      | alice       | data1       | write | NULL | NULL | NULL |
| 1600005 | p      | data2_admin | data2       | write | NULL | NULL | NULL |
+---------+--------+-------------+-------------+-------+------+------+------+
```
2. Use the model pasted in subsequent sections
3. Use the golang test program that is attached to check the permissions
4. Check the results... When using non-filtered approach it correctly returns 'true'
5. However when using the filtered approach it returns 'false' which is incorrect

**Expected behavior**
In both the filtered as well as non-filtered approach it should return true for alice, data2, write
However that is not the case. In case of filtered approach it incorrectly returns false

**Desktop (please complete the following information):**
 - OS: Windows 10, RAM 16GB
 - MySQL : v8.0

**Model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Policy:**

```
p, alice, data1, read
p, data2_admin, data2, read

g, alice, data2_admin
```

**Additional context**
The filtering loads the data for users and groups correctly with following query
```
SELECT * FROM `casbin_rule` WHERE v1 in ('data2') ORDER BY ID
```
However at the time of enforcement it is having issues. So the issue is purely at the time of enforcement as against to data loading

**Test Program**
```go
package main

import (
	_ "github.com/go-sql-driver/mysql"
	"github.com/casbin/gorm-adapter/v3"
	"github.com/casbin/casbin/v2"
	"fmt"
)

var userId = "alice"
var objectId = "data2"
var permission = "write"

func main() {
	checkPermNonFiltered()
	checkPermFiltered()
}

func checkPermFiltered() {
	a, _ := gormadapter.NewFilteredAdapter("mysql", "root:mysql123@tcp(127.0.0.1:3306)/")
	e, _ := casbin.NewEnforcer()
	e.InitWithAdapter("model.conf", a)
	
	filter := gormadapter.Filter{
	    V1: []string{objectId},
	}
	e.LoadFilteredPolicy(filter)	

	perm, _ := e.Enforce(userId, objectId, permission)
	fmt.Println(objectId, " \t", userId, " \t", perm, " \t")
}

func checkPermNonFiltered() {
	a, _ := gormadapter.NewAdapter("mysql", "root:mysql123@tcp(127.0.0.1:3306)/")
	e, _ := casbin.NewEnforcer("model.conf", a)
	
	perm, _ := e.Enforce(userId, objectId, permission)	
	fmt.Println(objectId, " \t", userId, " \t", perm, " \t")
}
```

**Comment by hsluoyz** [comment]
@arafat-java can you provide the current memory policies ("p" and "g") after `e.LoadFilteredPolicy(filter)` ?

**Comment by arafat-java** [comment]
How do I get that.
I am primarily a Java guy and have started off with Go some days back

**Comment by hsluoyz** [comment]
https://casbin.org/docs/en/management-api#getnamedpolicy

respectively for "p" and "g"

**Comment by arafat-java** [comment]
Here's the enforcer's memory policies ("p" and "g") after e.LoadFilteredPolicy(filter) 

namedPolicy :-  [[data2_admin data2 write]]
groupingPolicy :-  []

**Comment by hsluoyz** [comment]
It seems the "g" rules are not loaded. Try this:

```go
func checkPermFiltered() {
	a, _ := gormadapter.NewFilteredAdapter("mysql", "root:mysql123@tcp(127.0.0.1:3306)/")
	e, _ := casbin.NewEnforcer()
	e.InitWithAdapter("model.conf", a)
	m := e.GetModel()

	filter := gormadapter.Filter{
		V1: []string{objectId},
	}
	a.LoadFilteredPolicy(m, filter)

	filter2 := gormadapter.Filter{
		PType: []string{"g"},
	}
	a.LoadFilteredPolicy(m, filter2)

	perm, _ := e.Enforce(userId, objectId, permission)
	fmt.Println(objectId, " \t", userId, " \t", perm, " \t")
}
```

Note: we use `a.LoadFilteredPolicy(m, filter)` instead of `e.LoadFilteredPolicy(filter)` because the latter will clear previous policies, the former will not.

**Comment by arafat-java** [comment]
It doesn't work even with the above mentioned change. Still the filtered ones continue to return false
Although after the change the memory policy for "g" gives proper output as follows

namedPolicy :-  [[data2_admin data2 write]]
groupingPolicy :-  [[alice data2_admin]]

**Comment by hsluoyz** [comment]
Try at editor first: https://casbin.org/en/editor

**Comment by arafat-java** [comment]
How do I try the filtered policy option in the editor
It's working properly in non filtered way

**Comment by hsluoyz** [comment]
@arafat-java try this:

```go
func checkPermFiltered() {
	a, _ := gormadapter.NewFilteredAdapter("mysql", "root:mysql123@tcp(127.0.0.1:3306)/")
	e, _ := casbin.NewEnforcer()
	e.InitWithAdapter("model.conf", a)
	m := e.GetModel()

	filter := gormadapter.Filter{
		V1: []string{objectId},
	}
	a.LoadFilteredPolicy(m, filter)

	filter2 := gormadapter.Filter{
		PType: []string{"g"},
	}
	a.LoadFilteredPolicy(m, filter2)

	e.BuildRoleLinks() // <---- add this

	perm, _ := e.Enforce(userId, objectId, permission)
	fmt.Println(objectId, " \t", userId, " \t", perm, " \t")
}
```

**Comment by arafat-java** [comment]
Thanks @hsluoyz 
Adding e.BuildRoleLinks() worked.

Just wanted to confirm if this (adding additional filter and using e.BuildRoleLinks()) is a workaround or this is the way to go.
Reason I ask this is because when using non-filtered way I dont need these extra steps

**Comment by hsluoyz** [comment]
It's a workaround as you see the code is not very elegant. We may add some new and more friendly API to perform such a task.

**Comment by arafat-java** [comment]
@hsluoyz Any rough idea when this will be actually fixed in an elegant way

**Comment by hsluoyz** [comment]
@arafat-java you can use it for now. It may take some time for us to figure out a good way to solve it.
