### ISSUE TITLE
[Question] How to know if the returned permissions are directuser permissions or inherited via groups

### ISSUE THREAD

**Issue by arafat-java** [casbin/casbin#696]
**What's your scenario? What do you want to achieve?**
When the evaluation engine returns 'true' for e.Enforce I would like to know if those permissions are obtained via direct user permissions or inherited via group permissions. How can I know that?

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, alice, data1, read
p, data2_admin, data2, read

g, alice, data2_admin
```

**Your request(s):**

```
alice, data2, read ---> would give me true but I would like to know that it was obtained via group permissions
alice, data1, read ---> would give me true but I would like to know that it was obtained via direct user permissions

```

**Comment by hsluoyz** [comment]
Call API: https://casbin.org/docs/en/rbac-api#hasroleforuser

**Comment by arafat-java** [comment]
@hsluoyz hasRoleForUser is not what I want

Basically I want to know whether the permission returned by the enforce() method was achieved via group inherited permission or direct permission

**Comment by hsluoyz** [comment]
@arafat-java this cannot be done directly for now. You can use a workaround: a model with RBAC and another model without RBAC. If a request is only allowed under model 1, then it's based on RBAC inherited permissions.
