### ISSUE TITLE
[Bug] GetUsersForRole returns error when there are no users for a role

### ISSUE THREAD

**Issue by fgblomqvist** [casbin/casbin#698]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
Calling `GetUsersForRole(...)` with a role that doesn't have any users assigned to it returns a `name not found` error.

**To Reproduce**
1. Using the RBAC model, add a few rules for a role name `x`
2. Don't add any users to this role
3. Call `GetUsersForRole`
4. Get the error

**Expected behavior**
It should return an empty list.

**Comment by hsluoyz** [comment]
@fgblomqvist I think the current handling is OK. Casbin doesn't know the subject in p rules is actually a user or a role. So `name not found` means the same thing as returning empty list. If we change the behavior to return empty list, then someone would say I even don't have such a role, why return am empty list for me.

**Comment by fgblomqvist** [comment]
You're saying that we can't do x because someone would complain about it working that way. Yet, here's clearly a person that complains about it not working that way. What if you want to define a role as existing by it simply either 1. having users or 2. having rules. You're currently saying that a role _only_ exists if it has users. That seems like an odd limitation to me.
