### ISSUE TITLE
Multiple roles support

### ISSUE THREAD

**Issue by seonixx** [casbin/casbin#70]
I've seen a previous question about casbin supporting enforcement of multiple roles, which it apparently does, however I can't find any guidance on how to implement this with regards to enforcement. EnforceSafe checks a single role against a policy.

Any guidance on how to check against multiple roles for access?

**Comment by seonixx** [comment]
Ah yes I see - apologies, I misinterpreted the API. Thanks for your detailed response!

**Comment by leopragi** [comment]
More of an approach question:

How to implement multiple levels of roles with a single policy file on the RESTful model?

For example,
`
**user A** is user type **admin**. Even though he is an admin, we need to assign some roles explicitly, like **[data_admin, query_admin]**. Now my RESTful policy has to check both the admin type and multiple roles. 

All I can think of now is to 
1. create a policy file that has user type (as subject) and compare user type with the enforce method
2. create a policy file that has roles (as subject) and compare each of the roles with the enforce method
`

Now when a request comes in, I have to call `enforce` method 3 times (1 to check user type and 2 to check roles type). 

Is this how it should be done or any good approach?

**Comment by hsluoyz** [comment]
@leopragi please start a new issue, this issue will be frozen.
