### ISSUE TITLE
RoleManager with MatchingFunc depends on order of link creation.

### ISSUE THREAD

**Issue by abichinger** [casbin/casbin#701]
**Describe the bug**
The behavior of the `RoleManager` should be independent of the order in which the links between roles are created.

**To Reproduce**
1. Add the following function to `role_manager_test.go`:
```go
func TestMatchingFuncOrder(t *testing.T) {
	rm := NewRoleManager(10)
	rm.(*RoleManager).AddMatchingFunc("regexMatch", util.RegexMatch)

	rm.AddLink("g\\d+", "root")
	rm.AddLink("u1", "g1")
	testRole(t, rm, "u1", "root", true)

	rm.AddLink("u1", "g1")
	rm.AddLink("g\\d+", "root")
	testRole(t, rm, "u1", "root", true)
}
```
2. Run `go test ./...`

**Expected behavior**
The test shouldn't fail.

**Additional context**
Issue is already resolved in https://github.com/casbin/pycasbin/issues/107

**Comment by hsluoyz** [comment]
@RobotHuang plz take a look.

**Comment by RobotHuang** [comment]
@hsluoyz 
```
	rm.AddLink("g\\d+", "root")
	rm.AddLink("u1", "g1")
	testRole(t, rm, "u1", "root", true)
```
This code also outputs false possibly because `syn.Map` is disordered.
