### ISSUE TITLE
[Feature] Clean documentation of filtered adapter

### ISSUE THREAD

**Issue by memwey** [casbin/casbin#707]
**Is your feature request related to a problem? Please describe.**

I am the owner of the [casbin-sqlx-adapter](https://github.com/memwey/casbin-sqlx-adapter). I found that the adapter [xorm-adapter](https://github.com/casbin/xorm-adapter) had implemented some undocumented features, for example, [LoadFilteredPolicy](https://github.com/casbin/xorm-adapter/blob/master/adapter.go#L408) and [UpdatePolicy](https://github.com/casbin/xorm-adapter/blob/master/adapter.go#L460). These implements are not ducumented in the [doc](https://casbin.org/docs/en/adapters).

**Describe the solution you'd like**

Is it a testing feature or just forget the documentation? If it is a feature, please document it in the docs. With filtered policy, performance could be improved facing large policies.

**Comment by hsluoyz** [comment]
@memwey they are actually documented:

- https://casbin.org/docs/en/policy-subset-loading
- https://casbin.org/docs/en/management-api#updatepolicy

**Comment by memwey** [comment]
Well, I think these should be written in the part of [adapter](https://casbin.org/docs/en/adapters#how-to-write-an-adapter).
So you mean I should implement these according to [xorm-adapter](https://github.com/casbin/xorm-adapter) instead of [How to write an adapter](https://casbin.org/docs/en/adapters#how-to-write-an-adapter). It's OK but I think implement according to an interface defination will be clearer than according to an existed implement.

**Comment by hsluoyz** [comment]
@memwey can you click "EDIT" to improve the docs?
