### ISSUE TITLE
[Question] I don't understand the result with RBAC

### ISSUE THREAD

**Issue by codering** [casbin/casbin#709]
**What's your scenario? What do you want to achieve?**
Just learn RBAC example, have doubts about the results.

![image](https://user-images.githubusercontent.com/2271825/108498510-f0ece180-72e7-11eb-8f15-9db7430e8acb.png)

why the first result is `true` ?

**Comment by hsluoyz** [comment]
@codering it's because you have exactly the same p rule there:

![image](https://user-images.githubusercontent.com/3787410/108500292-84271680-72ea-11eb-9fdb-b3c4977beb29.png)

`g` functions always return true if 1st and 2nd args are equal.

**Comment by codering** [comment]
I thought the 'g' function only check ”g” prefix policy. 

Have doc about this？

**Comment by hsluoyz** [comment]
@codering see how Casbin RBAC works: https://casbin.org/docs/en/rbac
