### ISSUE TITLE
Interpretation of [policy_effect] and customized role manager

### ISSUE THREAD

**Issue by sipt** [casbin/casbin#71]
1. 关于[policy_effect]
当我看源码中：
``` go
       if e.model["e"]["e"].Value == "some(where (p_eft == allow))" {
		// ...
	} else if e.model["e"]["e"].Value == "!some(where (p_eft == deny))" {
		// ...
	} else if e.model["e"]["e"].Value == "some(where (p_eft == allow)) && !some(where (p_eft == deny))" {
		// ...
	} else if e.model["e"]["e"].Value == "priority(p_eft) || deny" {
		// ...
	}
```
这样的做法有点局限我们使用者的拓展，最好还是解析执行，不知是否安排在开发行程中

2. 关于Role的级别问题
例如：
```
p, role1, data1, read, allow
p, role1, data2, read, deny
p, role2, data1, read, deny
p, role2, data2, read, allow
p, alice, data1, read, allow
p, alice, data2, read, deny

g, role2, role1
g, alice, role2
```
当我运行
```go
e.Enforce("alice", "data1", "read") // 期望值是true
e.Enforce("alice", "data2", "read") // 期望值是false
```
就是距离本身越近的角色p.eft的运算结果能决定最后的结果
因为这是我的业务场景所需要，所以我没有发PR，如果觉得并不需要可以在此处Return了
```go
// RoleManager provides interface to define the operations for managing roles.
type RoleManager interface {
	// ...
	// domain is a prefix to the roles (can be used for other purposes).
        // 在这里我添加了一个Level的返回
	HasLink(name1 string, name2 string, domain ...string) (bool, int)
        //...
}
```
在对应的defaultRoleManager也做出的修改
```go
func (r *Role) hasRole(name string, level int) (bool, int) {
	if r.name == name {
		return true, level
	}
	if level <= 0 {
		return false, level
	}
	for _, role := range r.roles {
		if ok, l := role.hasRole(name, level-1); ok {
			return true, l
		}
	}
	return false, level
}
```

**Comment by hsluoyz** [comment]
@sipt 

> 这样的做法有点局限我们使用者的拓展，最好还是解析执行，不知是否安排在开发行程中

其实本来是打算解析执行的，可是后面发现没有必要。因为目前写死就可以完成绝大多数需求了。你在这里需要实现什么样的场景呢？如果有必要支持，而现有的不足以支持，我会考虑添加的。

> 就是距离本身越近的角色p.eft的运算结果能决定最后的结果
因为这是我的业务场景所需要，所以我没有发PR，如果觉得并不需要可以在此处Return了

我今天设计了新的role manager机制，可以独立作为第三方组件集成了，参见：https://github.com/casbin/casbin#role-manager  ，参照session role manager例子，你可以开一个项目专门实现你的role manager。实现完后通知我下，我加到README里 :)

**Comment by sipt** [comment]
@hsluoyz 

关于role_manager那块，可能是我没有表述清楚
>>就是距离本身越近的角色p.eft的运算结果能决定最后的结果
>>因为这是我的业务场景所需要，所以我没有发PR，如果觉得并不需要可以在此处Return了
>
>我今天设计了新的role manager机制，可以独立作为第三方组件集成了，参见：https://github.com/casbin/casbin#role-manager ，参照session role manager例子

`default-role-manager`已经可以解决我的需求了，现在的问题是在于
```go
	var policyResults []Effect
```
这个结果只有一个`p.eft`的值，信息量比较少。是否考虑加入**User/Role**到**Role**的步长？
比如：
```
p, role1, data1, read, allow
p, role1, data2, read, deny
p, role2, data1, read, deny
p, role2, data2, read, allow
p, alice, data1, read, allow

g, role2, role1
g, alice, role2
```
基于以上数据，执行以下代码：
```go
roleManager.HasLink("alice", "alice") // alice : 返回(ok: true, step: 0)
roleManager.HasLink("alice", "role2") // alice > role2 : 返回(ok: true, step: 1)
roleManager.HasLink("alice", "role1") // alice > role2 > role1返回(ok: true, step: 2)
```
这样的话可以通过判断`step`可以做到权限的覆盖，也就是之前说到的
>就是距离本身越近的角色p.eft的运算结果能决定最后的结果

在匹配("alice", "data1", "read") 时可以得到三个结果：

|No.|eft|step|policy|
|---|---|---|---|
|1|allow|2|p, role1, data1, read, allow|
|2|deny|1|p, role2, data1, read, deny|
|3|allow|0|p, alice, data1, read, allow|

然后通过定制`[policy_effect]`来完成`step`小的权限覆盖`step`大的

**Comment by hsluoyz** [comment]
明白你的需求了。现在我在matcher里增加了返回int和float的功能，你可以直接把你的step作为matcher的返回值。之前matcher返回值只能是bool，现在可以为int或float。需要注意的是，返回0表示不匹配。非0值表示匹配。因此，HasLink还是只有一个返回值，就是step。你需要把step最小值设为1。因为多返回值比较麻烦，这样就绕过了多返回值的问题。具体来说：

···
roleManager.HasLink("alice", "alice") // alice : 返回(1)
roleManager.HasLink("alice", "role2") // alice > role2 : 返回(2)
roleManager.HasLink("alice", "role1") // alice > role2 > role1返回(3)
roleManager.HasLink("alice", "non_exist") // alice > role2 > role1返回(0)
···

上述逻辑你都可以实现一个role manager来搞定

```ini
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

然后假设你的matcher如上所示，可以改写为这样：

```ini
m = (r.obj == p.obj && r.act == p.act)? g(r.sub, p.sub) : 0
```

也就是说主体、资源、动作都匹配的时候，返回g(r.sub, p.sub)的值，也就是step。否则返回0。这样就把step传出来了

第二步就是怎么实现step小的优先，你提到了可以把policy effect也解释执行，这个后面会做，不过暂时有点困难。因为怕解释执行会严重影响速度。现在我提出了一个[Effector](https://github.com/casbin/casbin/blob/master/effect/effector.go)的设计，你可以直接设计一个Effector，在里面控制你想要的逻辑，实现那个step小的优先，参数我都传进去了。expr是effect表达式，effects是allow或者deny那个p.eft，results是matcher匹配的结果，也就是你的step。返回true|false以及error。你设计好了可以直接PR发到casbin代码里，我可以加进来，然后你自己用的时候调用Enforcer.SetEffector()设置你的effector就可以了。

暂时先这样，effect的解释执行后面会继续做。

**Comment by hsluoyz** [comment]
你的role manager实现好了也可以告诉我，我加到README里面的列表里

**Comment by hsluoyz** [comment]
Closed as stale.
