### ISSUE TITLE
Distributed policy enforcement via a Casbin enforcer cluster based on Raft

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin#713]
Issues:

- https://github.com/casbin/casbin/issues/402
- https://github.com/casbin/casbin/issues/547

Existing code:

- https://github.com/casbin/casbin-raft - Not available
- https://github.com/casbin/hraft-dispatcher - Beta Release

Existing docs:

- https://casbin.org/docs/en/dispatchers

**Comment by WenyXu** [comment]
I read some source code of https://github.com/casbin/hraft-dispatcher, and the related project https://github.com/otoolep/hraftd.

It's a good idea which using raft algorithm with an embedded database to sync multi-state of multi-nodes. We can easily implement the above application using Hashicorp-raft and boltDB(or bboltDB).

**Comment by hsluoyz** [comment]
Done
