### ISSUE TITLE
Is this worth adding to the example list?

### ISSUE THREAD

**Issue by natbusa** [casbin/casbin#715]
Hi, I have a written a model which supports roles and expand them into api scopes and hierarchical user groups. Is it worth adding to the example list?

NOTE: it requires GlobMatch to be enabled as a matching function for g2 to work

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, role

[role_definition]
g  = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g2(r.act, p.role) && g(r.sub, p.sub) && keyMatch(r.obj, p.obj)
```

**Your policy:**

```
# choose any role in reader,editor, admin, owner, app-reader, app-editor, app-admin
# choose any user in alice, teamA, teamB
p, teamB, /w/1/*, app-admin

g, alice, teamA
g, teamA, teamB


## roles to scope.verb ##

# basic concentric roles
g2, *.read, reader

g2, reader, editor
g2, *.update, editor

g2, editor, admin
g2, *.create, admin
g2, *.delete, admin

g2, *.*, owner

# custom (concentric) roles
g2, app.read, app-reader

g2, app-reader, app-editor
g2, app.update, app-editor

g2, app-editor, app-admin
g2, app.create, app-admin
g2, app.delete, app-admin
```

**Your request(s):**

```
alice, /w/1/, _.read
alice, /w/1/, _.update
alice, /w/1/, _.create
alice, /w/1/, _.policy
alice, /w/1/, app.read
alice, /w/1/, app.update
alice, /w/1/, app.create
alice, /w/1/, app.policy

```

**Comment by hsluoyz** [comment]
Hi @natbusa thanks for your thoughts! Why not write a tutorial about your model? Bringing only the model and policy into the examples without any description don't help that much I think.

You can either write a tutorial at other places and place a pointer at: https://casbin.org/docs/en/tutorials or we can even add it directly to the official site inside a dedicate tutorial section (if the quality is good). What do you say?

**Comment by hsluoyz** [comment]
Closed as stale.
