### ISSUE TITLE
Restrictive access to nested objects

### ISSUE THREAD

**Issue by Aggtaa** [casbin/casbin#716]
What would be a config for this taks?

1. Users and their roles are standard RBAC.

2. Objects can be nested (or grouped using RBAC terminology)
For an object X in group Y and group Y in group Z, a user access is granted if the user `has allow rules for X AND Y AND Z` and `has no deny rule on any of X, Y, Z`. So every nested object or object group applies more restrictions on top of their parent.

How to implement such a policy set?

**Comment by hsluoyz** [comment]
@closetool

**Comment by hsluoyz** [comment]
@Aggtaa use `Allow-and-deny` model, with `RBAC with resource roles` model: https://casbin.org/docs/en/supported-models

**Comment by Aggtaa** [comment]
Resource roles as given in the docs url are implemented with RBAC on g2 grouping policy, which implies:
obj X has role Y and user A is allowed on Y => A is allowed on X.

Am I correct?
If yes - it is not what requested.

**Comment by hsluoyz** [comment]
@Aggtaa

`
require A to be allowed on both X and Y to be granted on X.
`

This doesn't make sense. Please give a more real example about what you are trying to solve actually.

**Comment by closetool** [comment]
@Aggtaa Could you provide`model` and `policy` file, and tell us what you want to achieve?

**Comment by Aggtaa** [comment]
@hsluoyz 
We had a simple RBAC with domains model for access control with simple plain resource list in an app that consists of microservices. Each service controls its own list of resources and connects to the 'security center' to validate users access to the resources. 
At some point resource hierarchy was added, e.g. a service is a resource, resources within a service can be grouped by virtual folders and so on.
In this example to be able to access a resource, a user or a role must have 3 explicit rules that allow their access to the service, to the folder and finally to the resource. If a user is allowed to access the service and the folder, but not the resource, the resource remains unavailable.
At the same time, if the user access to the resource is denied, it does not matter what rules apply to the upper resource groups (the service and the folder)

So, now with all this additional complexity of hierarchical resources we are evaluating casbin.

@closetool my question is how to implement the model

**Comment by hsluoyz** [comment]
Use 

```ini
[request_definition]
r = sub, act, service, folder, resource

[policy_definition]
p = sub, act, service, folder, resource

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.act == p.act && ((p.service != "" && p.service == r.service) || (p.folder != "" && p.folder == r.folder) || (p.resource != "" && p.resource == r.resource))
```

**Comment by closetool** [comment]
@Aggtaa Is this works for you, plz try it.If this don't achieve your goals, you could try [priority model](https://casbin.org/docs/en/supported-models#examples)
![image](https://user-images.githubusercontent.com/52988625/109110863-de086000-7772-11eb-9f6e-08598a27375d.png)

You could test your model on https://casbin.org/editor

**Comment by Aggtaa** [comment]
Awesome, thank you!

Is there a more generic way for unknown levels of nesting?

**Comment by closetool** [comment]
@Aggtaa Our domain only has one level, so there's not a generic way for now. : )

**Comment by hsluoyz** [comment]
@Aggtaa 

you can merge `service, folder, resource, ..` into a path like "/service/folder/resource/name4/name5", so you have unlimited nesting in path.

Model:

```ini
[request_definition]
r = sub, act, path

[policy_definition]
p = sub, act, path, eft

[role_definition]
g = _, _

[policy_effect]
e = priority(p.eft) || deny

[matchers]
m = g(r.sub, p.sub) && r.act == p.act && isSubPath(r.path, p.path)
```

Policy:

```csv
p, alice, read, /service1, deny
p, alice, read, /service1/folder1, deny
p, alice, read, /service1/folder1/resource1, allow

g, ...
```

`isSubPath(arg1, arg2)` is a custom function you can implement, it returns true if arg1 is a subpath of arg2.

- isSubPath("/service1/folder1/resource1", "/service1") == true

**Comment by hsluoyz** [comment]
Closed as resolved.

**Comment by hsluoyz** [comment]
@Aggtaa any update?
