### ISSUE TITLE
[Question] how to control access of forum topic owner and global admin?

### ISSUE THREAD

**Issue by birdycn** [casbin/casbin#717]
What are the best practices for posting users and super administrators to perform certain operations?

Is the use of adapters to insert casbin tables when users post posts: users, resources, increase or decrease, or do they intercept dynamic judgments in routing middleware? If it's a dynamic judgment, it's good to have role permission management

For example, when userid = 1 publishes a topic = 2, do you want to insert the permission of caspin at this time? Is it necessary? If you insert the delete permission and want to cancel the user's post permission, do you want to ignore the previously recorded bin permission

**Comment by hsluoyz** [comment]
@birdycn plz change to English. Thanks!

**Comment by birdycn** [comment]
What are the best practices for posting users and super administrators to perform certain operations?



Is the use of adapters to insert casbin tables when users post posts: users, resources, increase or decrease, or do they intercept dynamic judgments in routing middleware? If it's a dynamic judgment, it's good to have role permission management



For example, when userid = 1 publishes a topic = 2, do you want to insert the permission of caspin at this time? Is it necessary? If you insert the delete permission and want to cancel the user's post permission, do you want to ignore the previously recorded bin permission

**Comment by hsluoyz** [comment]
You can compare the topic owner with the username, if they equal, then it will have owner right.
