### ISSUE TITLE
What model would be efficient for hierarchial objects? [Question]

### ISSUE THREAD

**Issue by emgageadmin** [casbin/casbin#718]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/casbin/casbin/issues/718)

**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

We have scenario similar to a file system, where the location in the hierarchy determines if a subject is authorized for particular object.  

This is for a multi-tenant environement 
There could be millions of objects and 96% of the objects will not have their own policy but will inherit a policy from their parent or an ancestor.
the hierarchy will be relativly static and small (maybe 12 deep with 20 to 300 nodes)
subjects will be individual users or roles
roles wil be hierarchical and it will be relativly static

# for example #

- h1  (p, alice, data1, read)
- - h2
- - - h3  (p, alice, data2, read)
- - - - h4 (p, aplice, data1, delete)
- - - - h5  (p, bob, data1, write)
- - - h6
- - - - h7 (p, admin_role, data1, write)
- - - h8  (p, alice, data1, write)

**This hierarchy should produce these authorization results:**
A) alice is granted read data1 at h1
B) alice is granted read data1 at h2 (because it deos not specify a policy for data1 and thus it inherits from h1)
C) alice is granted read for data2, data1 at h3 (there is data2 read policy at h3 and data1 read policy is inherited from h1)
D) alice is granted delete data1 and read data1 at h4 (there is data1 delete policy at h4 and data1 read policy inherited from h1) 
E) bob is granted write data1 at h5
F) bob is NOT granted any access at h1, h2, h3, h4, h6, h7, h8 
G) alice is granted read data2 at h6 and h7 
H) admin_role members are is granted  write data1 at h7
I) alice is granted  write data1 at h8

sorry if i belabered my question with too many example. just want to make sure there is no confusion. :)

# the question #

The question is, what would be the optimal model for this type of structures? 
We would like to model that would scale and be relativly performant.

any ideas would be greatly appreciate. Love casbin! and i have funded this question.
keep up the awesome work

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- $40.00 have been anonymously funded.

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/casbin/casbin/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by hsluoyz** [comment]
@emgageadmin try:

Model:

```ini
[request_definition]
r = hierarchy, sub, obj, act

[policy_definition]
p = hierarchy, sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.hierarchy, p.hierarchy) && r.obj == p.obj && r.act == p.act
```

Policy:

```csv
p, h1, alice, data1, read
p, h3, alice, data2, read
...

g, alice, admin_role
g2, h2, h1
g2, h3, h2
g2, h6, h2
g2, h4, h3
g2, g5, h3
...
```

**Comment by emgageadmin** [comment]
@hsluoyz thanks for the quick reply. 
I have some clarification requests:

* what is the purpose of the `g(r.sub, p.sub)` and `g2(r.hierarchy, p.hierarchy)` functions in the maracher? is it basically checking to see if the subject is the required role and hierarchy?


* also, how would this work when there is no explicit policy but it's inheirted from ancestor nodes? such as in example B above.

**Comment by hsluoyz** [comment]
@emgageadmin see how RBAC and `g` works: https://casbin.org/docs/en/rbac

I think you can just try your case at: https://casbin.org/en/editor  Make sure to complete the policy first.

**Comment by Sefriol** [comment]
I actually want to spice up this question a little bit:

What I have been using for an year is a hierarchical authz model where domains have hierarchy, but roles too.

What I have been using is model like this:
```
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && g2(r.dom, p.dom) && regexMatch(r.obj, p.obj) && regexMatch(r.act, p.act)
```
with example set of policies:

```
p, admin, domain1, data1, (read|write)
p, admin, domain2, data2, (read|write)

g, alice, admin, domain1
g, bob, admin, domain2
g2, domain2, domain1
```
where I would assume that domain1 > domain2. However with following examples it does not work:
```
alice, domain1, data1, read --> true, correct
alice, domain2, data2, read --> false, incorrect
bob, domain2, data2, read --> true, correct
```
However, if I change it a little bit, it does **kinda** work:

```
p, admin, domain1, data1, (read|write)
p, admin, domain2, data2, (read|write)

g, alice, admin, domain1
g, bob, admin, domain2
g2, domain1, domain2
```
But now I have to ask from domain which I consider "higher".
```
alice, domain1, data2, read --> true, partially correct, but asked from wrong domain domain
bob, domain2, data2, read --> true, correcrt
```

Any idea what I am doing wrong? @hsluoyz

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@Sefriol Which version are you using? 
My result shows that `alice, domain2, data2, read` is always to be false, and I thought that's right.
Role inheritance relays on string replacement. This means, policy for alice only has one piece, `alice, domain1, data1, (read|write)`.
```csv
p, admin, domain1, data1, (read|write)
p, admin, domain2, data2, (read|write)

g, alice, admin, domain1
g, bob, admin, domain2
g2, domain1, domain2
```
This model is quite complex.

**Comment by Sefriol** [comment]
Results described above are produced with Node-Casbin (latest) or CasbinJS provided by the website.

I guess the idea would be that if alice is an admin in domain1 and domain1 has dominance over domain2, alice should have admin rights for domain2 as well.

**Comment by closetool** [comment]
@Sefriol I tried it with website enforcer, and the result shows below, it still to be false.
![image](https://user-images.githubusercontent.com/52988625/123197060-8e962e80-d4dd-11eb-8fe3-f1acd2df7681.png)

**Comment by closetool** [comment]
@Sefriol I must tell you casbin behaves as expected, the result is right.
role inheritance will only replace matched string in `p` section, so this model policy will not work as you expected.

**Comment by Sefriol** [comment]
`alice, domain1, data2, read` will be true though and I am wondering whether it is possible to generate model which says that `alice, domain2, data2, read` is true.

**Comment by Sefriol** [comment]
@hsluoyz So, do you think this problem is solvable by Casbin? I think this is pretty typical use case of hierarchical RBAC where you do not want to define global role hierarchy into each domain.

General idea woudl be pretty similar to the original question:

- global domain
- - subdomain1
- - - lowersubdomain1
- - subdomain2

1. So if `alice` is an `admin` in `global domain`, she should be an `admin` in all domains below it (`subdomain1`, `lowersubdomain1`, `subdomain2`).
    1. This should happen without any additional policy lines. `g, alice, admin, global domain` should be sufficient
    2. Defining what permissions `admin` has in each domain is still required.
2. If `bob` is an `admin` in `subdomain1`, he should have `admin` access to `lowersubdomain1`
    1. But no access to any other domain

**Comment by zhulinwei** [comment]
> @hsluoyz So, do you think this problem is solvable by Casbin? I think this is pretty typical use case of hierarchical RBAC where you do not want to define global role hierarchy into each domain.
> 
> General idea woudl be pretty similar to the original question:
> 
> * global domain
> * * subdomain1
> * * * lowersubdomain1
> * * subdomain2
> 
> 1. So if `alice` is an `admin` in `global domain`, she should be an `admin` in all domains below it (`subdomain1`, `lowersubdomain1`, `subdomain2`).
>    
>    1. This should happen without any additional policy lines. `g, alice, admin, global domain` should be sufficient
>    2. Defining what permissions `admin` has in each domain is still required.
> 2. If `bob` is an `admin` in `subdomain1`, he should have `admin` access to `lowersubdomain1`
>    
>    1. But no access to any other domain

Right.
