### ISSUE TITLE
How to get allowed list?

### ISSUE THREAD

**Issue by GerryLon** [casbin/casbin#719]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Your answer here

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

如何获取某人可查看的某类资源?
如: 
获取 某用户(subject=alice)可查看(action=read)的项目(resource:{type=project})

在casbin中如何实现这种需求?

谢谢!

**Comment by hsluoyz** [comment]
@GerryLon plz change both title and text to English, thanks!
