### ISSUE TITLE
use multiple policies

### ISSUE THREAD

**Issue by lixiangru-creator** [casbin/casbin#720]
I intend to use multiple strategies. For example: p1 as a role-path strategy, p2 as a role-chart strategy, and p3 as a role-game verification. But currently Casbin seems to only introduce a single strategy. Excuse me, how to configure this model config file and policy file.

**Comment by hsluoyz** [comment]
@lixiangru-creator why not use the same 'p' for all these? See the yellow note here: https://casbin.org/docs/en/syntax-for-models#policy-definition

![image](https://user-images.githubusercontent.com/3787410/109615580-0a571e80-7b6f-11eb-9c44-505a75d39fe2.png)

**Comment by hsluoyz** [comment]
Closed as resolved.
