### ISSUE TITLE
Question is related to RBAC with ABAC

### ISSUE THREAD

**Issue by kirill-kosenko** [casbin/casbin#722]
Hello
I guess the question is related to RBAC with ABAC
I have following roles: admin, user, read_only. 

```
p, read_only, overview, view, allow
// ... read_only permission

p, user, ap_records, open_query, allow
//... user permissions

p, admin, user_settings, transaction_approval_limits, allow

g, user, read_only
g, admin, user

g, 1, user
```

While admin is allowed to set any value for 'transaction_approval_limits',
user with 'user' type of a role has some limits. For example user 1 has 'transaction_approval_limits' set to 100. If this user tries to set 101 instead - the result should be false. Every user can have different 'transaction_approval_limits'.

Is it possible to implement that with Casbin?
How to write the policy and model?
Hope it was clear
Thanks

**Comment by hsluoyz** [comment]
@kirill-kosenko what's transaction_approval_limits ?

**Comment by nodece** [comment]
@hsluoyz I guess that `transaction_approval_limits` is a value.

**Comment by kirill-kosenko** [comment]
'transaction_approval_limits' is a value. Admin can set any value. But user has some limit. I guess that limit should be included in policy file somewhere.

**Comment by nodece** [comment]
- Model
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

- Policy
```
p, read_only, overview, view, allow

p, user, ap_records, open_query, allow

p, admin, user_settings, *, allow

p, 1, user_settings, 100, allow

g, user, read_only
g, admin, user

g, 1, user
```

- Request
```
1, user_settings, 100
1, user_settings, 101

admin, user_settings, 89
admin, user_settings, 110
```

You can test the above data in https://casbin.org/en/editor.

**Comment by hsluoyz** [comment]
@kirill-kosenko I think you can use the scaling ABAC model: https://casbin.org/docs/en/abac#scaling-the-model-for-complex-and-large-number-of-abac-rules

See example: https://casbin.org/en/editor

![image](https://user-images.githubusercontent.com/3787410/109675654-f03f2f80-7bb2-11eb-82ac-58192833c2ab.png)

**Comment by kirill-kosenko** [comment]
@hsluoyz Thank you

**Comment by kirill-kosenko** [comment]
@hsluoyz Thank you

If I need to have two types of model RBAC and scaling ABAC model, for example:

`p, alice, data1, read`
`p, r.sub.Age > 18 && r.sub.Age < 60, /data1, read`

Should I create 2 model files, 2 policy files, 2 Enforcers?
Or it can be in a single model, policy files?
Thanks

**Comment by hsluoyz** [comment]
@kirill-kosenko you can use model which mixed RBAC and ABAC, single model, single policy file, single enforce. I didn't see why can't do this.

**Comment by nodece** [comment]
@hsluoyz Casbin doesn't support which mixed RBAC and ABAC: #https://github.com/casbin/casbin/pull/611.

**Comment by hsluoyz** [comment]
@nodece it's true, but you can write RBAC and ABAC in different parts of the matcher.

**Comment by nodece** [comment]
@hsluoyz can we support this feature in a model?

**Comment by hsluoyz** [comment]
I think we can write this:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub_rule, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = eval(p.sub_rule) && g(r.obj, p.obj) && r.act == p.act
```

**Comment by kirill-kosenko** [comment]
@hsluoyz Thank you

It works

I combined RBAC and scaling ABAC into a single file 

Model
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub_rule, sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = eval(p.sub_rule) && g(r.sub.user, p.sub) && r.obj == p.obj && r.act == p.act
```

Policy
```
p, 1 == 1, read_only, overview, view
p, 1 == 1, ap_standard, ap_records, open_query

p, r.sub.limit <= 1000, 1, transaction_approval_limit, update
p, r.sub.limit <= 500, 2, transaction_approval_limit, update

p, 1 == 1, ap_admin, transaction_approval_limit, update

g, ap_standard, read_only
g, ap_admin, ap_standard

g, 100, ap_admin
g, 1, ap_standard
g, 2, ap_standard
```
Reques
```
{ limit: 1000, user: 1 }, transaction_approval_limit, update
{ limit: 100000, user: 100 }, transaction_approval_limit, update
{ limit: 500, user: 2 }, transaction_approval_limit, update
{ user: 2 }, overview, view
```

As you can see in policy file there's RBAC policy like `p, 1 == 1, read_only, overview, view`
I created some `true` condition - `1 == 1`. Looks like workaround.

What do you think?
Is there a better way to write RBAC policy?

Thanks

**Comment by hsluoyz** [comment]
@kirill-kosenko why `1 == 1` can't be "true" directly?

Also if you like this style:

```ini
[matchers]
m = (p.sub_rule == "" || eval(p.sub_rule)) && g(r.sub.user, p.sub) && r.obj == p.obj && r.act == p.act
```

```csv
p,, read_only, overview, view
p,, ap_standard, ap_records, open_query

p, r.sub.limit <= 1000, 1, transaction_approval_limit, update
p, r.sub.limit <= 500, 2, transaction_approval_limit, update

p,, ap_admin, transaction_approval_limit, update

g, ap_standard, read_only
g, ap_admin, ap_standard

g, 100, ap_admin
g, 1, ap_standard
g, 2, ap_standard
```

Or change empty sub_rule to a *, anything you want.

**Comment by hsluoyz** [comment]
Closed as stale.
