### ISSUE TITLE
How to stop policy rule evaluation after first allow match

### ISSUE THREAD

**Issue by MichaelBurgess** [casbin/casbin#727]
Looking at the [docs](https://casbin.org/docs/en/syntax-for-models#policy-effect), the use of `some` in the policy effect like this in the model:

```ini
[policy_effect]
e = some(where (p.eft == allow))
```

...means that if any of the policy rules produce an allow effect, then the request is allowed.

I am adding Authz to a RESTful Gin API with Casbin and for us that means you either have permission to call that API, or you don't (which produces a 403)

If a policy rule produces an allow effect, I want short-circuit evaluation e.g. they have permissions, don't evaluate any other rules. Given none of my rules are going to produce a deny effect, there's nothing that could be subsequently checked to block the request.

How can I optimise my model so that we don't keep checking other rules after you get an allow?

**Model**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = keyMatch2(r.obj, p.obj) && (isOrgOwner(p.sub, r.sub, r.obj, p.obj) || isOrgMember(p.sub, r.sub, r.obj, p.obj)) && regexMatch(r.act, p.act)
```  

My `isOrgOwner` and `isOrgMember` custom functions look up the subject, find their role and then return a true or false result.

**Policy**

```ini
p, org:owner, /org/:org_handle/*, (GET|POST|PUT|PATCH|DELETE)
p, org:member, /org/:org_handle/foo, GET
```

**Requests**

Let's assume that:

- `alice` has `org:owner` on org `acme`

```
alice, /org/acme/foo, GET ---> true (expected: true)
```

The issue is that for a GET request to `/org/acme/foo`, both the policy rules will key & regex match, but after getting an allow for `org:owner` on the first rule, the engine still checks the second rule for `org:member`. These are wasted efforts as my first rule has already matched - as the number of APIs grow and the potential for more path matches grows, so will the cost to evaluate.

How can I stop Casbin from evaluating subsequent rules after it gets a successful allow?

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@MichaelBurgess priority model might be helpful https://casbin.org/docs/en/priority-model

**Comment by MichaelBurgess** [comment]
@closetool so if you had this policy:

```
p, 1, org:owner, /org/:org_handle/*, (GET|POST|PUT|PATCH|DELETE)
p, 2, org:member, /org/:org_handle/foo, GET
```

...would the second rule not be evaluated? The docs don't suggest that, so feels like the same amount of work would still be undertaken? My rules will be ordered correctly anyhow so the highest priority will come first.

**Comment by closetool** [comment]
@MichaelBurgess If a rule evaluated to be true, method `enforce` will stop, plz refer to https://github.com/casbin/casbin/blob/f588eb693e2bf3fd509c71757e66cac5caf7bb0c/enforcer.go#L554

**Comment by hsluoyz** [comment]
ping @MichaelBurgess

**Comment by hsluoyz** [comment]
Closed as invalid.

**Comment by zavre-c** [comment]
So Just for Confirmation,
If I am using **Priority Model** with need of the **super-admin** access

with Matcher
`m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act || r.sub == "root"`

I should have some policy with top priority having allow then result is true 
if top priority is deny then its false 
cause matcher matches the first highest priority 

Eg.
> 1. highest priority as allow
>
>Policy 
p, 100, all, resource, read, allow
p, 1, top, all, any, allow
>
>Request: 
root, anything, anything  -> allow

> 2. highest priority as deny
>
>Policy
p, 100, all, resource, read, allow
p, 1, top, all, any, deny
>
>Request:
root, anything, anything -> deny

**Comment by hsluoyz** [comment]
@zavre-c yes, you'd better setup a default policy for root. Like

```
p, 10000, root, anything, anything, allow
```

With:

```
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act || r.sub == "root" && p.sub == "root"
```
