### ISSUE TITLE
Run-As or Impersonlation feature

### ISSUE THREAD

**Issue by aannuujj** [casbin/casbin#73]
Is there any plan to support a 'run-as' or user impersonation feature? For example - a user with enough admin rights can impersonate a particular user in order to support or troubleshoot some issue within the system.

**Comment by hsluoyz** [comment]
Can you be more specific about the support you desire Casbin to add? In my understanding, you want a user A to have exactly the same rights as another user B? Or add all the permissions that B has to user A? If latter, just grant the role B to user A. So A will inherit all the permissions that role B has (in fact it's user B here, but Casbin doesn't differentiate between user and role).

**Comment by hsluoyz** [comment]
Any update?

**Comment by aannuujj** [comment]
Hi. The feature is as follows 
IF User A has the permissions to impersonate (for e.g. ADMIN role) then User A can temporarily impersonate and access resources by impersonating User B.

This is a temporary access and hence granting role B to user A wouldn't make sense.

**Comment by aannuujj** [comment]
@hsluoyz 

> ADMIN role has the B role. So A having ADMIN role will lead to that A has B role.

This statement is not entirely accurate. What I meant to say is for User A to have User B's role, User A needs to have an `ADMIN` role. 

It is definitely temporary.

Here's an example of user impersonation implemented by auth0 https://auth0.com/docs/user-profile/user-impersonation

Please let me know if your suggestion about using SessionRoleManager is still valid.

**Comment by hsluoyz** [comment]
OK. So you want all ADMIN to have the right to impersonate another user. So the user uses latter's rights to do operations. I think you can make impersonation an action, like adding a policy rule:

```csv
p, ADMIN, *, impersonate
g, alice, ADMIN
```

It means ADMIN role can impersonate anyone (*). ``alice`` has the ADMIN role. So ``alice`` can impersonate anyone.

But you need to implement impersonation on your own in your system. For example, write the following code:

```go
func do_impersonate(sub string, obj string, act string) {
  if enforcer.Enforce(sub, obj, act) {
    change_current_user_from_sub_to_obj()
  } else {
    fail()
  }
}
```

**Comment by hsluoyz** [comment]
Close as solved.
