### ISSUE TITLE
[Feature] Wipe all the existing policies on an object, and then set them to whatever is passed afresh

### ISSUE THREAD

**Issue by arafat-java** [casbin/casbin#731]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Is your feature request related to a problem? Please describe.**
Wipe all the existing policies on an object, and then set them to whatever is passed afresh
For the specific example, it would be more like a "SetPolicies()" API which would wipe all the existing policies for a subject, and then set them to whatever you passed. I don't want to have to know which policies I am replacing, just that the final result looks like what I'm passing in. All the policies of other objects should remain unaffected

**Describe the solution you'd like**
Assume that I have my original policies as follows

```
-------+----------+--------+--------
p_type | v0       | v1     | v2     
-------+----------+--------+--------
p      | alice    | data1  | write  
p      | jill     | data1  | read   
-------+----------+--------+--------
p      | jill     | data2  | read   
-------+----------+--------+--------
p      | bobby    | data3  | write  
p      | jack     | data3  | read   
-------+----------+--------+--------
p      | alice    | data4  | write  
p      | bob      | data4  | write  
p      | jack     | data4  | read   
p      | jill     | data4  | read 
-------+----------+--------+--------
```

Now I want to modify the policies only for data4 as follows
 1. Remove polcies for alice and bob
 2. Change the permissions of jack to write
 3. Leave jill unchanged
 4. Add extra user bobby with write permissions

In short I want to wipe out policies of data4 and completely overwrite that with the new policies for data4 
So my new policy set would look as follows

```
-------+----------+--------+--------
p_type | v0     | v1     | v2     
-------+--------+--------+--------
p      | alice  | data1  | write  
p      | jill   | data1  | read   
-------+--------+--------+--------
p      | jill   | data2  | read   
-------+--------+--------+--------
p      | bobby  | data3  | write  
p      | jack   | data3  | read   
-------+--------+--------+--------
p      | jack   | data4  | write   
p      | jill   | data4  | read   
p      | bobby  | data4  | write  
-------+--------+--------+--------
```

**Describe alternatives you've considered**
So far to achieve this I was using the following code snippet

```go
e.RemoveFilteredPolicy(1, "data4")
var rules [][]string
rules = append(rules, []string{"jack", "data4", "read"})
rules = append(rules, []string{"jill", "data4", "read"})
rules = append(rules, []string{"bobby", "data4", "read"})
e.AddPolicies(rules)
```

However, I want delete and add to happen as part of same transaction so that if add fails the delete is rolled back
So I tried 

```go
e.EnableAutoSave(false)
Did the delete and add
e.EnableAutoSave(true)
e.SavePolicy()
```

But e.SavePolicy() wipes out the database so cannot use that

Other option was UpdatePolicies but in that only the policies that pre-exist were modfied. Add/Delete was not handled. Right now with https://github.com/casbin/casbin/pull/729 it attempts to wipe the old and write the new policies, but I see that it is using e.SavePolicy() which will wipe out the database so I cannot use that because I want only a single object policies to be modified

**Additional context**

**Comment by dahu33** [comment]
We have the same requirements but our use case is slightly different: we want to be able to replace (in a transaction) the policies of a subject when using the RBAC model.

As commented here: https://github.com/casbin/casbin/pull/729#issuecomment-793941380

I would suggest to add an `UpdateFilteredPolicy(fieldIndex int, fieldValues[], newRules [][]string) error` function to the management API but also to the `UpdatableAdapter` interface so we can preserve atomicity between the model and the storage while using the `AutoSave` feature. This function would provide the equivalent of calling
`RemoveFilteredPolicy` and `AddPolicies` in a transaction and cover most of use cases imaginable.

**Comment by hsluoyz** [comment]
@closetool

**Comment by hsluoyz** [comment]
Is this issue anything difference with https://github.com/casbin/casbin/issues/728 ?

**Comment by closetool** [comment]
@arafat-java @dahu33 @hsluoyz I have modified the implementation, `SavePolicy` is no longer needed, plz review

**Comment by hsluoyz** [comment]
@arafat-java Is this issue anything different with https://github.com/casbin/casbin/issues/728 ?

**Comment by arafat-java** [comment]
@hsluoyz It seems similar but this issue has a more clear description of the problem statement and step by step solution details.
When I read https://github.com/casbin/casbin/issues/728 I dont get a clear sense of understanding of the requirement

**Comment by hsluoyz** [comment]
@arafat-java 

> Now when I call e.UpdatePolicies([][]string{{"*"}}, [][]string{{"arafat", "data4", "write"}})
It will simply clear the old policies for data4 and only add user "arafat" to "data4" with write

Old policy should not share the "knowledge" from the new policy, it can't know what data4 is.

**Comment by arafat-java** [comment]
@hsluoyz We dont need to share the "knowledge" between old and new policy.
My only requirement is that when I call the UpdatePolicies for an object, all the old policies of that object should be wiped out and simply apply  the new set that I send.

data4 is the object id 
You can check the detailed description that I had put in this issue to get clear context

**Comment by hsluoyz** [comment]
@arafat-java but `[][]string{{"*"}}` shows nothing about data4.

```go
e.UpdatePolicies([][]string{{"*"}}, [][]string{{"arafat", "data4", "write"}})
```

should work like:

```go
e.startTransation()
e.RemovePolicies([][]string{{"*"}})
e.AddPolicies([][]string{{"arafat", "data4", "write"}})
e.endTransaction()
```

**Comment by arafat-java** [comment]
So how can I make it work such that the policies for data4 are first wiped out.
I thought of passing then but looking into the code of internal_api.go I can see following code
```
if patternRule[len(patternRule)-1] == "*" {
	return e.updatePoliciesEnhance(sec, ptype, patternRule, newRules)
}
```
So with that in play if I pass anything that tells it to delete the policies for data4 then the if condition would fail and the new method updatePoliciesEnhance() itself will not get called

That was the first problem 

The second problem is that I dont think that
`e.UpdatePolicies([][]string{{"*"}}, [][]string{{"arafat", "data4", "write"}})`

would work like:

```
e.startTransation()
e.RemovePolicies([][]string{{"*"}})
e.AddPolicies([][]string{{"arafat", "data4", "write"}})
e.endTransaction()
```

because on currently line 241 is e.EnableAutoSave(true) instead of e.EnableAutoSave(false).
The 'true' flag would cause it to work like follows

```
e.startTransaction()
e.RemovePolicies([][]string{{"*"}})
e.endTransaction()
e.startTransaction()
e.AddPolicies([][]string{{"arafat", "data4", "write"}})
e.endTransaction()
```

**Comment by hsluoyz** [comment]
@arafat-java this is what we **will** achieve, but its current state

```go
e.UpdatePolicies([][]string{{"*", "data4", "*"}}, [][]string{{"arafat", "data4", "write"}})
```

**Comment by dahu33** [comment]
> @arafat-java this is what we **will** achieve, not its current state
> 
> ```go
> e.UpdatePolicies([][]string{{"*", "data4", "*"}}, [][]string{{"arafat", "data4", "write"}})
> ```

Sounds great. But instead of introducing a new wildcard (`*`) pattern which is not used anywhere else, why not reusing the same logic as in `RemoveFilteredPolicy` with the field index and field values? At the end of the day, what @arafat-java  and I need is just running the equivalent of `RemoveFilteredPolicy` + `AddPolicies` in a single transaction.

**Comment by hsluoyz** [comment]
Honestly, this issue is hard. Can anyone sponsor this issue via IssueHunt?

**Comment by hsluoyz** [comment]
@dahu33 @arafat-java we still need to update the adapter code. Which adapters do you use?

**Comment by arafat-java** [comment]
@hsluoyz we use https://github.com/casbin/casbin-pg-adapter

**Comment by nodece** [comment]
@hsluoyz I think we should introduce transactions feature.

**Comment by arafat-java** [comment]
Any updates on this

**Comment by hsluoyz** [comment]
@arafat-java plz review: https://github.com/casbin/casbin-pg-adapter/pull/25
