### ISSUE TITLE
[Question] RBAC with all pattern model doesn't work

### ISSUE THREAD

**Issue by giefferre** [casbin/casbin#737]
**What's your scenario? What do you want to achieve?**

in the online editor on casbin.org/editor, I've tried with the `RBACL with all pattern`.

I've filled the model with the following content

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.obj) && keyMatch4(r.obj,p.obj) && regexMatch(r.act, p.act)
```

and then I've inserted the following policies

```csv
p, basic-user, /me, Users.GetMyUserData
p, basic-user, /me, Users.SetUserProfile
g, office-staff, basic-user, *
p, office-staff, /organizations/{orgID}/offices/{officeID}/services/{serviceID}, MyService1.GetReservationParameters
p, office-staff, /organizations/{orgID}/offices/{officeID}, MyService5.GetOfficeSettings
p, office-staff, /organizations/{orgID}/offices, MyService6.GetMyOffices
p, office-staff, /organizations/{orgID}, MyService6.GetMyOrganizations
p, office-staff, /organizations/{orgID}/offices/{officeID}/services/{serviceID}/reservations/{reservationID}, MyService3.CompleteReservation

g, staff@company.org, office-staff, /me
g, staff@company.org, office-staff, /organizations/1
g, staff@company.org, office-staff, /organizations/1/offices
g, staff@company.org, office-staff, /organizations/1/offices/OFFICE123
g, staff@company.org, office-staff, /organizations/1/offices/OFFICE123.*

```

I've tried the following requests, and they all worked as expected:

```csv
# expected to be allowed
staff@company.org, /organizations/1/offices/OFFICE123, MyService5.GetOfficeSettings
staff@company.org, /organizations/1/offices, MyService6.GetMyOffices
staff@company.org, /organizations/1, MyService6.GetMyOrganizations
staff@company.org, /me, Users.GetMyUserData
staff@company.org, /organizations/1/offices/OFFICE123/services/ABCDE/reservations/FGHI, MyService3.CompleteReservation

# expected to be blocked
staff@company.org, /organizations/1/offices/OFFICE999, MyService5.GetOfficeSettings
staff@company.org, /organizations/1, Users.GetUsersForOffice
staff@company.org, /organizations/1/offices/OFFICE999/services/TRWYE/reservations/DGSAF, MyService3.CompleteReservation
staff@company.org, /organizations/1/offices/OFFICE123, MyService5.EnableServiceTimeTracking
staff@company.org, /organizations/1/offices/OFFICE123/counters/123, MyService5.SetCounterName

```

Then I've moved all this behaviour to `go` code.

The code implementing such behaviour is the following:

```go

	e, err := casbin.NewEnforcer("model.conf", "policies.csv")
	if err != nil {
		log.Fatal(err)
	}

	tc := []struct {
		requestSubject string
		requestObject  string
		requestAction  string
		expectedGrant  bool
	}{
		{"staff@company.org", "/organizations/1/offices/OFFICE123", "MyService5.GetOfficeSettings", true},
		{"staff@company.org", "/organizations/1/offices", "MyService6.GetMyOffices", true},
		{"staff@company.org", "/organizations/1", "MyService6.GetMyOrganizations", true},
		{"staff@company.org", "/me", "Users.GetMyUserData", true},
		{"staff@company.org", "/organizations/1/offices/OFFICE123/services/ABCDE/reservations/FGHI", "MyService3.CompleteReservation", true},
		{"staff@company.org", "/organizations/1/offices/OFFICE999", "MyService5.GetOfficeSettings", false},
		{"staff@company.org", "/organizations/1", "Users.GetUsersForOffice", false},
		{"staff@company.org", "/organizations/1/offices/OFFICE999/services/TRWYE/reservations/DGSAF", "MyService3.CompleteReservation", false},
		{"staff@company.org", "/organizations/1/offices/OFFICE123", "MyService5.EnableServiceTimeTracking", false},
		{"staff@company.org", "/organizations/1/offices/OFFICE123/counters/123", "MyService5.SetCounterName", false},
	}

	for testIndex, test := range tc {
		grant, err := e.Enforce(test.requestSubject, test.requestObject, test.requestAction)
		if err != nil {
			t.Fatal(err)
		}
		if grant != test.expectedGrant {
			t.Errorf("#%d expected grant %v differs from received", testIndex, test.expectedGrant)
			t.Log(test.requestSubject, test.requestObject, test.requestAction, "\n")
		}
	}

```

Instead, the application fails the following assertions

```go

{"staff@company.org", "/me", "Users.GetMyUserData", true},
{"staff@company.org", "/organizations/1/offices/OFFICE123/services/ABCDE/reservations/FGHI", "MyService3.CompleteReservation", true},

```

And I can't understand why.

Hope my message was clear enough, thanks in advance for your patience ✌️

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
![image](https://user-images.githubusercontent.com/52988625/111139516-2ff71580-85bc-11eb-9da8-5c1dd6e8c918.png)
No, I believe it with no fault, plz refer to [rbac](https://casbin.org/docs/en/rbac-with-domains)

**Comment by giefferre** [comment]
@closetool thanks for your prompt response.

In Casbin web editor the above model configuration works if I use `RBAC with all pattern`.

Should I change something on the code to use such RBAC type?

**Comment by closetool** [comment]
@giefferre plz add domain matching function manually, refer to https://casbin.org/docs/en/rolemanager-api & https://casbin.org/docs/en/role-managers, and I highly recommanded you to read docs about [rbac domain](https://casbin.org/docs/en/rbac-with-domains)
![image](https://user-images.githubusercontent.com/52988625/111154324-12cb4280-85ce-11eb-90a5-11451841a27a.png)

**Comment by giefferre** [comment]
@closetool thanks for your reply, but still it is not clear to me.

Is the problem on the model? I can use `RBAC with all pattern` on the web editor, but it is not listed [here](https://casbin.org/docs/en/supported-models).

I've tried with the following code, with no tangible results:

```go

	e, err := casbin.NewEnforcer("assets/enforcer_model.conf", "assets/policies.csv")
	if err != nil {
		t.Fatal(err)
	}

        // trying to mimic the Custom Config section of the web editor
	e.AddNamedDomainMatchingFunc("g", "", util.KeyMatch2)
	e.AddNamedMatchingFunc("g", "", util.KeyMatch2)
```

On the online web editor the custom configuration is set as follows:

```javascript
(function() {
  return {
    /**
     * Here is custom functions for Casbin.
     * Currently, there are built-in globMatch, keyMatch, keyMatch2, keyMatch3, keyMatch4, regexMatch, ipMatch.
     */
    functions: {},
    /**
     * The value comes from config.functions, Casbin will not use this configuration if the value is undefined.
     * example:
     * matchingForGFunction: 'globMatch'
     * matchingDomainForGFunction: 'keyMatch'
     */
    matchingForGFunction: 'keyMatch2',
    matchingDomainForGFunction: 'keyMatch2'
  };
})();
```

Is it correct?

**Comment by closetool** [comment]
https://casbin.org/docs/en/function this is about matching function, and `g,_,_,_` the third `_` means domain, it perhaps shouldn't be `obj`

**Comment by closetool** [comment]
@giefferre

**Comment by giefferre** [comment]
yes but as you can see in my request definition I use

```
[request_definition]
r = sub, obj, act
```

so what I want to achieve is to use the `r.obj` as domain (since I use RESTful like objects).

The problem is the fact that it *perfectly works* on the editor, while it doesn't in the golang implementation.

Maybe you would help me a lot if you can show me the golang code for the Casbin editor configuration using the `RBAC with all pattern` model 😄

**Comment by giefferre** [comment]
The problem is somehow related to Role Inheritance.

In fact, if I run 

```go
	log.Println(e.GetImplicitPermissionsForUser("admin@company.org", "/me"))
	log.Println(e.GetImplicitRolesForUser("admin@company.org", "/me"))
```

the commands produce

```
2021/03/16 17:49:00 [[office-staff /me Users.GetMyUserData] [office-staff /me Users.SetUserProfile]] <nil>
2021/03/16 17:49:00 [organization-manager office-manager office-staff] <nil>
```

But when I do call Enforce it fails on requests which should be `true` according to Role Inheritance 😕 

/cc @closetool @hsluoyz

**Comment by closetool** [comment]
@giefferre Like the docs said, keyMatch2 for pattern `:`, instead keyMatch for pattern `*`, I guess you should use keyMatch like I did
![image](https://user-images.githubusercontent.com/52988625/111416775-8466d600-871f-11eb-9b11-9268164baee7.png)

![image](https://user-images.githubusercontent.com/52988625/111416720-69946180-871f-11eb-8bb9-6ed381fb03ed.png)

![image](https://user-images.githubusercontent.com/52988625/111416826-9cd6f080-871f-11eb-8101-2a7f3d9e1ec5.png)

**Comment by giefferre** [comment]
@closetool I've read all of the documentation so far before opening this issue, with no help.

I've tried:
- `KeyMatch`
- `KeyMatch2`
- `KeyMatch4`
- `RegexMatch`

But none of them worked.

As I mentioned [here](https://github.com/casbin/casbin/issues/737#issuecomment-800444639) the issue seems to be in the hierarchy of the roles -- basically what happens is that the tests that fail are those which try to use an *action* on a *subject* who *should have inherited* a specific role.

Could you just try to copy & paste my code to reproduce my problem?

**Comment by closetool** [comment]
![image](https://user-images.githubusercontent.com/52988625/111471203-9c604900-8763-11eb-9e94-c38a6b387f01.png)
@giefferre casbin works well, 
you wrote some unexpected results for 5th & 7th

**Comment by closetool** [comment]
![image](https://user-images.githubusercontent.com/52988625/111471383-cf0a4180-8763-11eb-8f12-2b8043f4eb01.png)
@giefferre casbin works well, you worte unexpected results for 5th & 7th

**Comment by hsluoyz** [comment]
@giefferre is this issue resolved?

**Comment by hsluoyz** [comment]
Closed as resolved.

**Comment by mvbn6789** [comment]
@closetool  @hsluoyz  hey
 sorry for my poor english:
 I am use the most same case according to this issue, now i have question about to get user implict permmison api like :
	GetImplicitPermissionsForUser,_ := e.GetImplicitPermissionsForUser("staff@company.org")
	fmt.Print("GetImplicitPermissionsForUser ", GetImplicitPermissionsForUser)
	
i think expected result will  hit some  permiisons :
	 p, office-staff, /organizations/{orgID}/offices/{officeID}/services/{serviceID}, MyService1.GetReservationParameters
          p, office-staff, /organizations/{orgID}/offices/{officeID}, MyService5.GetOfficeSettings
          p, office-staff, /organizations/{orgID}/offices, MyService6.GetMyOffices
          p, office-staff, /organizations/{orgID}, MyService6.GetMyOrganizations
          p, office-staff, /organizations/{orgID}/offices/{officeID}/services/{serviceID}/reservations/{reservationID}, MyService3.CompleteReservation
          
but now result is empty

what i have try : 
GetRolesForUser and other apis seem alse  not work

**Comment by hsluoyz** [comment]
@mvbn6789 use batchEnforce()

**Comment by mvbn6789** [comment]
> @mvbn6789 use batchEnforce()

ok think you so much, I will try it 
so it means rbac_apis not support this usage case now ?

**Comment by hsluoyz** [comment]
@mvbn6789 No. `GetImplicitPermissionsForUser()` only works for basic scenarios like simple matcher + RBAC.
