### ISSUE TITLE
Use of embed

### ISSUE THREAD

**Issue by imarsman** [casbin/casbin#741]
It would be nice for bundled applications to be able to use golang 1.16 embed capability to create a new enforcer. Looking at the code for the file-based embed enforcer I see that it has a save method, which would not work with embed currently. Use of embedded model and policy for an enforcer would allow a packaged application to include these resources with the build. I can live without the use of embed but thought it might be worth considering.

**Comment by hsluoyz** [comment]
@imarsman hi, so what code change you do suggest?

**Comment by imarsman** [comment]
Embed supports a Filesystem interface, so if there was a NewFromFilesystem(model fs.File, policy fs.File) initializer that would work reasonably well but again, the embed filesystem is readonly. The enforcer could call InitWithFile(p0, p1) but instead of strings as paths it could be two fs.File arguments. I see that the file-adapter assumes a path that can be used to create a file for reading. Passing in a File argument would either require additional logic in the file-adapter package or a separate embed-adapter package or something like that. If it were me I would favour the separate package method, as there would be less code required to do double duty for an OS filesystem and an abstracted embed filesystem.

**Comment by imarsman** [comment]
Actually, if one did not need a file abstraction of any sort one could just make an adapter that used a string for the model and a string for the policy, or a set of byte arrays. This also would not allow saving the model but the file-adapter already disallows UpdatePolicy.

**Comment by hsluoyz** [comment]
For model string, see: https://casbin.org/docs/en/model-storage

For policy string, see: https://casbin.org/docs/en/adapters

![image](https://user-images.githubusercontent.com/3787410/111937560-f2861100-8b02-11eb-8e36-b4fb0bca16f1.png)

**Comment by imarsman** [comment]
I will read the manual better next time. Sorry to take up your time.
