### ISSUE TITLE
[Feature] Migrating from `Knetic/govaluate` to `antonmedv/expr`

### ISSUE THREAD

**Issue by fr3fou** [casbin/casbin#742]
**Is your feature request related to a problem? Please describe.**
The Go implementation of Casbin uses https://github.com/Knetic/govaluate, which at this point seems to be abandoned. Last commit was made on Oct 22, 2017 and the files haven't been updated in 4-5 years 
![image](https://user-images.githubusercontent.com/1344906/112514065-9ab70680-8d9d-11eb-9129-dd48f2993316.png)
There are as well some long-standing bugs that are annoying to deal with, such as 

![image](https://user-images.githubusercontent.com/1344906/112514400-f1bcdb80-8d9d-11eb-8e99-63932f33cfd5.png)
https://github.com/Knetic/govaluate/issues/79

**Describe the solution you'd like**
Casbin should migrate to a more maintained library, such as https://github.com/antonmedv/expr

**Describe alternatives you've considered**
 Forking https://github.com/Knetic/govaluate and fixing the bugs seems like an option, but it might be easier to just migrate.

**Comment by hsluoyz** [comment]
@fr3fou what about https://github.com/PaesslerAG/gval ?

**Comment by fr3fou** [comment]
> @fr3fou what about https://github.com/PaesslerAG/gval ?

also seems fine, we should pick whichever will take the least time to migrate to

**Comment by tson1111** [comment]
Hi, I want to have a try on this issue! I'll look at https://github.com/PaesslerAG/gval

**Comment by hsluoyz** [comment]
@tson1111 https://github.com/PaesslerAG/gval is just an option. Please choose the best one from all options.

**Comment by tson1111** [comment]
@hsluoyz Cool. I’ll do some research.

**Comment by tson1111** [comment]
@hsluoyz Hi, I took a look at some evaluation expression packages. It turns out that [expr](https://github.com/antonmedv/expr) has better performance (comparison [here](https://github.com/antonmedv/golang-expression-evaluation-comparison)) while [gval](https://github.com/PaesslerAG/gval) is better-documented and seems easier to migrate to. Since performance isn't our major concern and [gval](https://github.com/PaesslerAG/gval) is completely fine (https://github.com/PaesslerAG/gval#performance), [gval](https://github.com/PaesslerAG/gval) seems like a better choice. If it looks go to you, I'll start to code.

**Comment by hsluoyz** [comment]
@tson1111 the performance matters a lot to us. Especially for such a result: https://github.com/antonmedv/golang-expression-evaluation-comparison

gval is 40x slower than expr. Of course we will choose expr.

![image](https://user-images.githubusercontent.com/3787410/114009950-349aab00-9896-11eb-8af6-88401d2640f8.png)

**Comment by tson1111** [comment]
> gval is 40x slower than expr. Of course we will choose expr.
I don't think it's a fair play, coz the compilation time of gval has been included. However, I re-ran the benchmark, calculated only the evaluation time of gval, and found that gval is still 5~6x slower than expr. So from a performance perspective, expr is a better choice. I'll start to migrate if you agree with expr.

**Comment by hsluoyz** [comment]
I have included that open PR (https://github.com/hsluoyz/golang-expression-evaluation-comparison) and here's my result, so gval is 6x slower than expr.

```
goos: windows
goarch: amd64
pkg: github.com/antonmedv/golang-expression-evaluation-comparison
cpu: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
Benchmark_expr-16                       79314982               173.4 ns/op
Benchmark_goja-16                       40089358               266.6 ns/op
Benchmark_govaluate-16                  39998852               319.1 ns/op
Benchmark_celgo-16                      38878056               337.3 ns/op
Benchmark_expr_startswith-16            33225046               366.9 ns/op
Benchmark_celgo_startswith-16           22849460               530.4 ns/op
Benchmark_otto-16                       13417436               782.6 ns/op
Benchmark_bexpr-16                      14457985               914.8 ns/op
Benchmark_gval-16                       16230129              1012 ns/op
Benchmark_evalfilter-16                  4862834              2408 ns/op
Benchmark_starlark-16                    2432724              4877 ns/op
PASS
```

**Comment by tson1111** [comment]
@hsluoyz So we have similar results, I'll use expr.

**Comment by hsluoyz** [comment]
@tson1111 see: https://github.com/antonmedv/golang-expression-evaluation-comparison/pull/5

**Comment by tson1111** [comment]
@hsluoyz I've created a PR for this migration. Please take a look. #758

**Comment by hsluoyz** [comment]
We already have this PR: https://github.com/casbin/casbin/pull/759 and its performance is not ideal. So we on-hold this issue and close it for now.
