### ISSUE TITLE
How to write policies with field filters (single level and hierarchical)?

### ISSUE THREAD

**Issue by dbi1** [casbin/casbin#743]
Hi,

Ruby's [CanCanCan](https://github.com/CanCanCommunity/cancancan/blob/develop/docs/Defining-Abilities.md#hash-of-conditions) has a nice way of defining policies for certain special situations:

1) Applying field filters:

Example: User can only read active projects which he owns.
Policy: can :read, Project, active: true, user_id: user.id

2) Applying field filters to parent records:

Example: Project can only be read if the category it belongs to is visible.
can :read, Project, category: { visible: true }

Example: Similar, with even deeper nesting:
can :manage, Part, service: { account: { user: { id: user.id } } }

Might somebody be able to help me figure out how I could write policies like these in Casbin (assuming it is possible)?

Thank you.

**Comment by hsluoyz** [comment]
@dbi1 see ABAC and scaling ABAC: https://casbin.org/docs/en/abac

**Comment by dbi1** [comment]
Thank you @hsluoyz.

What if I wanted to have more than one field filter, for example:
brand = "Toyota" AND color="Blue"

Would a policy look something like this:

p, r.brand = "Toyota", r.color = "Blue", /data1, read

**Comment by hsluoyz** [comment]
@dbi1 use:

```ini
p, r.brand = "Toyota" && r.color = "Blue", /data1, read
```

The scaling rules support all grammar in: https://github.com/Knetic/govaluate

**Comment by hsluoyz** [comment]
Closed as resolved.
