### ISSUE TITLE
Add GetDomainsForUser() API

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin#744]
See: https://github.com/casbin/Casbin.NET/issues/148#issuecomment-809174721

**Comment by hsluoyz** [comment]
@closetool @RobotHuang

**Comment by RobotHuang** [comment]
Does it return all domains one user has?

**Comment by Sagilio** [comment]
See: https://github.com/casbin/Casbin.NET/issues/147#issue-841030349
