### ISSUE TITLE
Is it possible to group resources [Question]

### ISSUE THREAD

**Issue by EladProject** [casbin/casbin#745]
Hi,
I'd like to use Casbin to authorize API calls.

My model may look like this:

```ini
[request_definition]
r = sub, tenantId, url, verb

[policy_definition]
p = sub, tenantId, url, verb

[role_definition]
g = _, _ , _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.tenantId) && \
    (r.tenantId == p.tenantId || p.tenantId == "*") && \
    (keyMatch(r.obj, p.obj) && regexMatch(r.verb, p.verb)))
```

My policy may look like this:
```
p, role_USER_DEFINED_2, TENANT_ID_1, /my_url/printer, (GET)|(POST)
g, USER_ID_4, role_USER_DEFINED_2, TENANT_ID_1
```

Is there a way to group urls together and reference only the group in the policy?
(The policy will reference a group, the request will ask for a specific resource).
For example,
I will have a group management_urls which includes severals urls:
/my_url/printer, (GET)|(POST)
/my_url/keyboard,(GET)|(POST)|(PATCH)

And in the policy I will set them:
```
p, role_USER_DEFINED_2, TENANT_ID_1, management_urls
```

And the following request will return true:
```
USER_ID_4, TENANT_ID_1, /my_url/printer, GET
```

**Comment by hsluoyz** [comment]
@EladProject of course, see `RBAC with resource roles` model: https://casbin.org/docs/en/supported-models#examples

**Comment by EladProject** [comment]
Thanks,
I think that an alternative way to what you suggested is to do role inheritance and group by roles:
```
p, role_MANAGEMENT_URLS, /my_url/printer, (GET)|(POST)
p, role_MANAGEMENT_URLS, /my_url/keoboard, (GET)|(POST)|(PATCH)

g, USER_ID_4, role_USER_DEFINED_2
g, role_USER_DEFINED_2, role_MANAGEMENT_URLS
```

Assuming this also works (didn't try), is there a preference between the methods?

**Comment by hsluoyz** [comment]
@EladProject no much difference. You can choose based on whether you prefer:

1. A user role can access a single resource.
2. A single user can access a resource group.

Or even better:

1. A user role can access a resource group.
