### ISSUE TITLE
[Bug] CasbinJsGetPermissionForUser incompatible with casbin-js > 0.1.0

### ISSUE THREAD

**Issue by rickardgranberg** [casbin/casbin#747]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
Trying to use the example described here: https://casbin.org/docs/en/frontend to feed our frontend with permissions, but it doesn't work as documented. 
* First problem is that casbin-js now passes `subject` as the query key and not `casbin_subject` (documentation issue)
* Second problem is that casbin-js expects a JSON object as:
```json
{
  "m": "model string",
  "p": [
      "policy",...
   ]
}
```
The implementation of `casbinJsGetPermssionForUser` in `node-casbin` returns the correct JSON: 
https://github.com/casbin/node-casbin/blob/master/src/frontend.ts

**To Reproduce**
1. Not applicable

**Expected behavior**

I expected `CasbinJsGetPermissionForUser` to return the correct, compatible JSON and the documentation describing how to use this feature to be correct

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 83

**Smartphone (please complete the following information):**
 - Device: Not applicable
 - OS: -
 - Browser -
 - Version -

**Additional context**
Casbin version: v2.25.5
Casbin-js version: 0.2.0

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
got it, will working on this

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
In fact, node-casbin implement also has bug, it has unexpected side affect.
I will first fix that bug, later to resolve this.

**Comment by hsluoyz** [comment]
@closetool @RobotHuang

**Comment by hsluoyz** [comment]
@Zxilly plz also run Go code and see what difference the Go Casbin and Node-Casbin has for `CasbinJsGetPermissionForUser()`, then we need to determine which side has bugs, then fix it.

**Comment by closetool** [comment]
Node output:
![image](https://user-images.githubusercontent.com/52988625/114266051-aefa3500-9a26-11eb-9360-024852a0c821.png)
Golang output:
![image](https://user-images.githubusercontent.com/52988625/114266064-be797e00-9a26-11eb-829e-0b3bb536f89a.png)

@hsluoyz @Zxilly @rickardgranberg I guess node js version got a bug.
And like @rickardgranberg said, casbin-js now passes `subject` as the query key instead of `casbin_subject`

**Comment by Zxilly** [comment]
@closetool CasbinJsGetPermissionForUser() in Node-casbin used to have side effect. I have fixed it.
Any other problem you noticed?

**Comment by closetool** [comment]
@Zxilly I used casbin.js 5.6.1, the output is different from casbin's

**Comment by Zxilly** [comment]
casbin.js is a separate library, you mean node-casbin?
kingiw refactor the data structure at casbin.js 0.1.0, but he forget to change CasbinJsGetPermissionForUser() in casbin-golang.
node-casbin now have the right implement. casbin-golang should have the same output to work with casbin.js

**Comment by closetool** [comment]
![image](https://user-images.githubusercontent.com/52988625/114268554-3601da00-9a34-11eb-81ea-882f1a4dfc42.png)
If the output is right, the param `user` would be useless.

**Comment by Zxilly** [comment]
![image](https://user-images.githubusercontent.com/31370133/114270828-10c79880-9a41-11eb-9f01-72c1b0d37c27.png)
Yes, it's useless. kingiw totally refactor the logic and no longer use user variable.

**Comment by hsluoyz** [comment]
@Zxilly then why not remove the 2nd arg `user` in casbinJsGetPermissionForUser() ?

**Comment by Zxilly** [comment]
@hsluoyz As a fallback compatibility, I will add a default value to it.
