### ISSUE TITLE
Can we create custom matchers ?

### ISSUE THREAD

**Issue by dr1ss** [casbin/casbin#75]
Hello guys, I wonder if there is a way to have a custom matcher.
I think we need to have one that checks if a value exists in an array, this will be useful for ABAC and hierarchical authorization.

**Comment by hsluoyz** [comment]
You can implement a custom function which can be used in the matcher. See: https://github.com/casbin/casbin/wiki/Matchers#how-to-add-a-customized-function

**Comment by dr1ss** [comment]
Very nice, thank you and sorry I didn't find this before :S
