### ISSUE TITLE
[Bug] Go

### ISSUE THREAD

**Issue by belief428** [casbin/casbin#750]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casbin/casbin/issues/751
