### ISSUE TITLE
[Bug] Golang AddPolicies Abnormal

### ISSUE THREAD

**Issue by belief428** [casbin/casbin#751]
![image](https://user-images.githubusercontent.com/24927606/113654168-d620d180-96c9-11eb-9080-aaf151c0a724.png)

Hello guys：
   I have a problem and AddPolicies  can't save to the database

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@belief428 which adapter do you use? gorm or xorm

**Comment by hsluoyz** [comment]
Closed as stale.
