### ISSUE TITLE
[Feature] Improve enforce to improve performance 

### ISSUE THREAD

**Issue by techoner** [casbin/casbin#752]
```go
func (e *Enforcer) enforce(matcher string, explains *[]string, rvals ...interface{}) (ok bool, err error) {
    // ...
    			if j, ok := parameters.pTokens["p_eft"]; ok {
				eft := parameters.pVals[j]
				if eft == "allow" {
					policyEffects[i] = effect.Allow
				} else if eft == "deny" {
					policyEffects[i] = effect.Deny
				} else {
					policyEffects[i] = effect.Indeterminate
				}
			} else {
				policyEffects[i] = effect.Allow
			}

			if e.model["e"]["e"].Value == "priority(p_eft) || deny" {
				break
			}
    // ...
}
```
All policies will be executed in the `for` loop, [Pycasbin #134](https://github.com/casbin/pycasbin/pull/134) provides a more effective idea to break the loop when necessary .

**Comment by hsluoyz** [comment]
@closetool

**Comment by Sagilio** [comment]
I think [default_effector_stream](https://github.com/casbin/casbin/blob/beta/effect/default_effector_stream.go) in the beta branch is for this issue too. It will also break the loop when `PushEffect` returns true, and it also can return the explain like a trace.

**Comment by Sagilio** [comment]
I think [default_effector_stream](https://github.com/casbin/casbin/blob/beta/effect/default_effector_stream.go) in the beta branch is for this issue too. It will also break the loop when `PushEffect` returns true, and it also can return the explain like a trace.

**Comment by hsluoyz** [comment]
See: https://github.com/casbin/casbin/pull/753#issuecomment-815899090

**Comment by hsluoyz** [comment]
@closetool plz add the new Effector API to official docs: https://github.com/casbin/casbin/blob/master/effector/effector.go
