### ISSUE TITLE
RBAC patterns doesn't work when using Resource roles

### ISSUE THREAD

**Issue by wgarunap** [casbin/casbin#755]
I tried to use RBAC patterns matching with Resource roles and it does not work as expected.

model.conf file

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2=_,_

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj,p.obj) && regexMatch(r.act, p.act)
```

policy.csv file
```
p, book_admin, data1, GET
g, /book/:id, book_admin
```
When I requested `/book/1, data1, GET` , the model returns `false` when I am expecting a `true`

<img width="934" alt="Screenshot 2021-04-08 at 8 43 04 AM" src="https://user-images.githubusercontent.com/16771997/113963137-b236ca80-9846-11eb-88ee-a9201245841a.png">

If I remove the pattern in the policy file, it works,

<img width="934" alt="Screenshot 2021-04-08 at 8 53 39 AM" src="https://user-images.githubusercontent.com/16771997/113963828-f1195000-9847-11eb-85f7-ddebe110ee9b.png">

**Comment by hsluoyz** [comment]
@wgarunap plz call `AddMatchingFunc()`, see: https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac

**Comment by hsluoyz** [comment]
You should select "RBAC with pattern" option to enable `matchingForGFunction` in the online editor:

![image](https://user-images.githubusercontent.com/3787410/116689262-72e53f00-a9ea-11eb-970f-822373805dcf.png)

![image](https://user-images.githubusercontent.com/3787410/116689312-842e4b80-a9ea-11eb-83f0-89fc21e5117f.png)

In code, you should call `AddMatchingFunc()`, see: https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac

**Comment by wgarunap** [comment]
Thanks @hsluoyz
