### ISSUE TITLE
The docker image of casbin/casbin doesn't exists

### ISSUE THREAD

**Issue by hegphegp** [casbin/casbin#76]
## The docker image of casbin/casbin doesn't exists
the url is https://hub.docker.com/r/casbin/casbin/builds/
![360 20180304234846224](https://user-images.githubusercontent.com/26202719/36947446-a7d3c8b0-2006-11e8-85eb-521ddaeec0ae.png)

**Comment by hsluoyz** [comment]
Can you help add the docker file to Casbin and build the image on DockerHub for me?

**Comment by hsluoyz** [comment]
That Docker image is just a placeholder and doesn't contain anything meaningful.

If you need to run Casbin as a server, see: https://github.com/casbin/casbin#how-to-use-casbin-as-a-service

**Comment by FarhadF** [comment]
I can help to create a Dockerfile for casbin server if you see fit.

**Comment by hsluoyz** [comment]
That's excellent:) But the first thing is to determine which Casbin server should be packaged into Dockerfile. The official https://github.com/casbin/casbin-server is only a prototype and not yet ready.

**Comment by FarhadF** [comment]
I'll just create a base Dockerfile for it, and you can have it in the repo, when you determine its ready for release, use it to create the image. I think this issue can be closed.

**Comment by hsluoyz** [comment]
Thanks. BTW, do you have any idea about which ``Casbin as a server`` project is better? It seems that there are not many people there that use Casbin as a server. And I don't know how to proceed in this direction.

**Comment by FarhadF** [comment]
No Idea, I have only used casbin as a lib. Let me know when you decide.

**Comment by hsluoyz** [comment]
OK.

**Comment by hsluoyz** [comment]
@FarhadF We have started the Casbin Server project here: https://github.com/casbin/casbin-server

Feel free to use it and add the DockerFile :)
