### ISSUE TITLE
[Bug] Casbin is authorizing when the policy.csv is empty

### ISSUE THREAD

**Issue by iamshreeram** [casbin/casbin#760]
**What's your scenario? What do you want to achieve?**
Your answer here

**Your model:**

```ini
[request_definition]
r = sub, dom, tab, act

[policy_definition]
p = sub, dom, tab, act

[role_definition]
g = _, _, _

[policy_effect]
e = !some(where (p.eft == deny))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.tab == p.tab && r.act == p.act
```

**Your policy:**

```

```

**Your request(s):**

```
ram, defaultdomain, basictabile, write ---> true (expected: false)
```

**Comment by iamshreeram** [comment]
I provided below policy, 
```
p, admin, domain1, todo, read
p, admin, domain1, todo, write
p, admin, domain2, table1, write
p, admin, domain2, table2, write

g, user, admin, domain1
g, user2, admin, domain2
```

And tried to enforce with `user2:domain1:todo:write`. This is returning **true** as well. Basically, Authorization is successful for any enforcer.

Also, How do I print the logs from enforcer?

**Comment by hsluoyz** [comment]
@iamshreeram can you try with online editor? https://casbin.org/en/editor

**Comment by iamshreeram** [comment]
@hsluoyz , It works as expected in online editor. But,  I'm seeing this behavior When I use casbin in my _go_ code.

**Comment by iamshreeram** [comment]
Below is the access control function - 

```
func accessControl(subject, domain, table, act string) (res bool) {
	allNamedSubjects := enforcer.GetAllNamedSubjects("p")
	log.Print(allNamedSubjects) // returning empty slice [] - when no policy but it enforcer still returns true.

	ok, err := enforcer.Enforce(subject, domain, table, act) // returning true
	log.Print("ok:", ok)
	if err != nil {
		log.Print("error is : ", err)
		return false
	}
	if ok == true {
		return true
	}
	log.Print("There is no error. But, Authorization failed")
	return false
}
```

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@iamshreeram Thanks for using casbin!
I noticed you used `Deny Override` effect in your model file.
It means if you has no deny policy in your policy file, then your request will return true
And its behaviour acts exactly the same with casbin editor(You should check your model file/effect section)
https://casbin.org/docs/en/syntax-for-models#policy-effect

**Comment by iamshreeram** [comment]
Thanks @closetool ; Moving from Deny override to Allow override fixed the issue. I'm still confused on why casbin was authorizing without anything on policy.csv file.

I have another question :
I want to authorize a subject against multiple tables. Is there a way to provide list of tables in single `Enforce` instead of one at a time? 

With current implementation, 
```
ok, err := enforcer.Enforce(subject, domain, table, act) // returning true
```
**Enforce** just accepts only one table.

**Comment by closetool** [comment]
There's no such that solution, but casbin uses adapter reads data from db, you could implement your own multiple table adapter on your own : )

**Comment by hsluoyz** [comment]
@iamshreeram see: https://casbin.org/docs/en/data-permissions

**Comment by hsluoyz** [comment]
Closed as resolved.
