### ISSUE TITLE
[Bug]Using priority-model Won't get any implicit permission

### ISSUE THREAD

**Issue by yockii** [casbin/casbin#762]
**Describe the bug**
using priority model, and has the policy as follow:
p, 10, data_group, data, read, allow

when u try to get implicit permission with GetImplicitPermissionsForUser("data_group")
it will return nil

for the function GetPermissionsForUser, it write e.GetFilteredPolicy(0, args...)
but index=0 is the priority field.

will it be a bug, or if i use the wrong method to get a user's permission?

**Comment by hsluoyz** [comment]
@yockii It's more of a convention instead of a bug that we usually put `user` or sub as the 1st element. For your case, please put priority elsewhere after sub.

**Comment by yockii** [comment]
@hsluoyz Thanks for reply, but as I use priority as non 1st element, the enforce won't work well.
after reading source, i found function SortPoliciesByPriority() in model.go:`if assertion.Tokens[0] != fmt.Sprintf("%s_priority", ptype) {
			continue
		}`
so it must be the 1st element when using priority?

**Comment by hsluoyz** [comment]
@closetool please fix this bug. We should check if any element in p definition is `priority`, instead of only checking the first element.
