### ISSUE TITLE
[Bug] policy not getting returned by EnforceEx

### ISSUE THREAD

**Issue by JeyoungKwon** [casbin/casbin#763]
**Describe the bug**
I'm not 100% sure this is a casbin limitation due to the policy_effect or bugged behavior, but EnforceEx sometimes returns empty even when there is a policy match. 

**To Reproduce**
https://gist.github.com/JeyoungKwon/9d4e9e97b173ce0a3941eb30f1ff5b30

The assert on line 52 fails (returns empty string slice), but the assert on line 97 passes. The only difference between the tests is the value for policy_effect.

**Expected behavior**
EnforceEx should always return the matched policy

**Comment by hsluoyz** [comment]
@closetool

**Comment by hsluoyz** [comment]
The reproducible code can be put into the root folder of casbin repo to test:

```go
package casbin

import (
	"testing"

	casbinModel "github.com/casbin/casbin/v2/model"
	"github.com/stretchr/testify/assert"
)

func Test_ExforceExDeny(t *testing.T) {
	modelStr := `
[request_definition] 
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = r.sub == p.sub && keyMatch(r.obj, p.obj) && r.act == p.act
`

	model, err := casbinModel.NewModelFromString(modelStr)
	if err != nil {
		t.Errorf("failed to load model: %v", err)
	}

	enforcer, err := NewEnforcer(model)
	if err != nil {
		t.Errorf("failed to initialize enforcer: %v", err)
	}

	user := "john"

	enforcer.ClearPolicy()

	_, err = enforcer.AddPolicy(user, "books", "read", "allow")
	if err != nil {
		t.Error("fail")
	}

	ok, reason, err := enforcer.EnforceEx("john", "books", "write")
	assert.Equal(t, false, ok)
	assert.Equal(t, []string{}, reason)
	assert.Nil(t, err)

	ok, reason, err = enforcer.EnforceEx("john", "books", "read")
	assert.Equal(t, true, ok)
	assert.Equal(t, []string{"john", "books", "read", "allow"}, reason)
	assert.Nil(t, err)
}

func Test_ExforceExNoDeny(t *testing.T) {
	modelStr := `
[request_definition] 
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && keyMatch(r.obj, p.obj) && r.act == p.act
`

	model, err := casbinModel.NewModelFromString(modelStr)
	if err != nil {
		t.Errorf("failed to load model: %v", err)
	}

	enforcer, err := NewEnforcer(model)
	if err != nil {
		t.Errorf("failed to initialize enforcer: %v", err)
	}

	user := "john"

	enforcer.ClearPolicy()

	_, err = enforcer.AddPolicy(user, "books", "read", "allow")
	if err != nil {
		t.Error("fail")
	}

	ok, reason, err := enforcer.EnforceEx("john", "books", "write")
	assert.Equal(t, false, ok)
	assert.Equal(t, []string{}, reason)
	assert.Nil(t, err)

	ok, reason, err = enforcer.EnforceEx("john", "books", "read")
	assert.Equal(t, true, ok)
	assert.Equal(t, []string{"john", "books", "read", "allow"}, reason)
	assert.Nil(t, err)
}
```

**Comment by closetool** [comment]
@JeyoungKwon Thanks for using casbin.
It was designed to act like that, https://casbin.org/docs/en/syntax-for-models#policy-effect.
When the effect section is `e = some(where (p.eft == allow)) && !some(where (p.eft == deny))`, `EnforceEx` only returns deny policy.

**Comment by JeyoungKwon** [comment]
Ah, ok. It makes sense to me now. In that case I would like to suggest this as a feature. The way I am thinking about it is if we flip the terms like this:
```
[policy_effect]
e =  !some(where (p.eft == deny)) && some(where (p.eft == allow)) 
```
Then it could be like short circuit evaluation where if the left side is false, then the deny policy is returned, but if true, then it goes on to check the allow policy, and returns that, if any. More like the deny takes precedence, rather than overrides. Just a suggestion. I would personally find it useful, at least.

**Comment by hsluoyz** [comment]
It doesn't make sense. A policy is either allow or deny. You will always return the 1st policy. Or you can provide a non-trivial example to illustrate your idea.

**Comment by JeyoungKwon** [comment]
So the current behavior of EnforceEx when using the allow-and-deny policy is to return the first deny policy?

I was under the impression that the policy effect depends on all matching policies, not just the first matching deny.

From the paper(3.1): "The effect primitive determines whether the request should be approved if multiple policy rules match the request. In other words, it can form a single decision by combining multiple decision results from the matched policy rules"

From reading this it seemed to me that if there is a matching allow policy and no deny policy, then it should be possible to return the matching allow policy, whether or not the policy_effect is the allow-and-deny effect. 

Sorry if this doesn't make sense for casbin, I know that returning the matching policy wasn't necessarily the intended purpose of the project.

**Comment by hsluoyz** [comment]
@JeyoungKwon for `allow-and-deny` effect, what about this?

1. If the final result is allow, we will return the first matched allow rule, we don't return any matched deny rules because we know no deny rules will be matched.
2. If the final result is deny, we will return the first matched deny rule, we don't return any matched allow rules because deny overrides.

**Comment by JeyoungKwon** [comment]
Yup, that would be perfect for what I was trying to do. It'd allow me to use the EnforceEx api and still keep the ability to use the allow-and-deny effect.
