### ISSUE TITLE
why this group role with group resource test is false?

### ISSUE THREAD

**Issue by hanaimin** [casbin/casbin#764]
![image](https://user-images.githubusercontent.com/31823408/115122191-375d7480-9fe9-11eb-9476-a1d7cfc80510.png)

**Comment by hsluoyz** [comment]
@hanaimin missed comma after "g":

![image](https://user-images.githubusercontent.com/3787410/115130644-e5861000-a023-11eb-9a10-6bc56ead0c9f.png)
