### ISSUE TITLE
[Bug] Getting Implicit roles/permissions for a user for ABAC with policy model + RBAC tenants

### ISSUE THREAD

**Issue by sagarshah1983** [casbin/casbin#767]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
I am trying to evaluate my model and see if I can implicit roles/permissions for the user that one may have inherited, but I am not seeing those when I call the API. I see the results fine, when I use just RBAC with tenants model

**Your model:**

```ini
[request_definition]
r = sub, sub2, dom, obj, obj2, act

[policy_definition]
p = sub, rule, dom, obj, act, eft

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.sub, p.sub, r.dom) && eval(p.rule) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
g, john, nurse, fac_b
g, chris, nurse, fac_b
g, chris, physician, fac_a
g, alice, admin, fac_a

p, admin, (r.sub2.viewPreliminary == true), fac_a, observation, write, allow


```

**Your request(s):**
I am trying to call following function from java client

```
System.out.println(enforcer.getImplicitPermissionsForUserInDomain("alice", "fac_a"));
```
And I see output as empty. 
Please note that, if I remove rule from policy in the model, then it works fine. 
So questions is -
- Can we use ABAC with policy for this feature? OR
- Shall we use only RBAC with tenants and avoid ABAC policy rules to get implicit roles/permissions assigned to the user.

Appreciate your suggestions.

Thanks for reading.

Regards,
Sagar

**Comment by hsluoyz** [comment]
@closetool

**Comment by hsluoyz** [comment]
@sagarshah1983 plz state your expected output for `System.out.println(enforcer.getImplicitPermissionsForUserInDomain("alice", "fac_a"));`

**Comment by sagarshah1983** [comment]
@hsluoyz 
I am expecting output to print the permissions assigned to admin user via policies. But instead, I get empty array
```
p, admin, (r.sub2.viewPreliminary == true), fac_a, observation, write, allow
```
Thanks!

**Comment by closetool** [comment]
@sagarshah1983 
model.conf
```
[request_definition]
r = sub, dom, sub2,  obj, obj2, act

[policy_definition]
p = sub, dom, rule,  obj, act, eft

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.sub, p.sub, r.dom) && eval(p.rule) && r.obj == p.obj && r.act == p.act
```
policy.csv
```
g, john, nurse, fac_b
g, chris, nurse, fac_b
g, chris, physician, fac_a
g, alice, admin, fac_a

p, admin, fac_a,(r.sub2.viewPreliminary == true),  observation, write, allow
```
Changing your configuration file to this will fix it.

**Comment by hsluoyz** [comment]
@closetool can you explain it?

**Comment by sagarshah1983** [comment]
Swapping the order of domain and rule in policy helped. But I am not sure, why it did not work earlier as my policy input was in compliance with model defined earlier too.

**Comment by closetool** [comment]
@sagarshah1983 @hsluoyz For it depends on GetFilteredPolicy()
![image](https://user-images.githubusercontent.com/52988625/115513827-17aea080-a2b6-11eb-9b07-19c5a28330a8.png)

**Comment by hsluoyz** [comment]
@closetool plz fix this bug.

**Comment by sagarshah1983** [comment]
Thank you @hsluoyz . Just a question (maybe my misunderstanding).. I am using casbin using jcasbin java client library (v 1.8.3). How can I know, if its referring casbin 2.28.3 or not. Is there a matrix of compatible versions between jcasbin & casbin?

**Comment by hsluoyz** [comment]
@sagarshah1983 we have a feature set table: https://casbin.org/docs/en/overview#feature-set-for-different-languages

There's no mapping between Go and Java, but generally you should always use the latest version of that language.

**Comment by sagarshah1983** [comment]
Thanks for clarifying @hsluoyz .
I think I still see the same issue with original model and policy that I had posted. Did I do something wrong there.
I was testing with jcasbin library and I used latest version, which was 1.8.3
Should that be working now? Or Am I still missing something?
Please suggest!
