### ISSUE TITLE
[Bug] several: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by arigon** [casbin/casbin#768]
**Describe the bug**
There are several nil pointer dereferences which are not properly checked. I will create some PRs linked to this issue, but it will take some time to find most of them. :-)

**To Reproduce**
For example: Trying to add a grouping policy without any existing policy.

**Additional context**
`_, ok := model[sec][ptype].PolicyMap[strings.Join(rule, DefaultSep)]`
If model[sec] has no hit, it will panic. If model[sec][ptype] has no hit it will panic as well.

**Comment by hsluoyz** [comment]
Won't fix due to: https://github.com/casbin/casbin/pull/769#issuecomment-826354184
