### ISSUE TITLE
Multiple policy definitions

### ISSUE THREAD

**Issue by adamkl** [casbin/casbin#77]
Are multiple policies supported?

The [wiki documentation](https://github.com/casbin/casbin/wiki/Policy-definition) seems to suggest that they are, but looking at the source, it appears as though only one policy definition is supported (same for requests, effects, and matchers).

This is confirmed by issue #29.

If they aren't supported yet, it might be a good idea to update the wiki so as not to give the wrong impression. 

I'm investigating casbin to see if it fits our requirements (I'm not even sure what our requirements are! :upside_down_face:), and I just want to make sure I have an accurate picture.

Thanks!

**Comment by hsluoyz** [comment]
The multiple policy definitions are a future work. I'm not doing it because it seems not very urgent. The current way already works for most cases. I have updated the WiKi. Thanks for pointing it out!

**Comment by Noah-Huppert** [comment]
Hi,

I would suggest removing the idea of multiple policy definitions from the wiki page all together. Although the note about multiple policy definitions not being supported pointed me in the right direction I was still quite confused until I read your comment.
