### ISSUE TITLE
[Question] my model and policy didn't work

### ISSUE THREAD

**Issue by DaiJiezou** [casbin/casbin#772]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Your answer here

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
[request_definition]
r = sub, obj

[policy_definition]
p = sub, obj

[role_definition]
g = _, _


[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && g(r.obj, p.obj)

```

**Your policy:**

```
g	DELETE#/admin/codeset/*	2001
g	DELETE#/admin/datasource/*	2002
g	DELETE#/admin/imageRepository/*	2003
g	DELETE#/admin/job/*	1005
g	DELETE#/admin/jobenv/*	1006
g	DELETE#/admin/ops/component	1004
g	DELETE#/admin/ops/node/*	1002
g	DELETE#/admin/quota/*	3004
g	DELETE#/admin/space/*	3003
g	DELETE#/admin/system/*	4001
g	DELETE#/role/*	3002
g	DELETE#/user/*	3001
g	GET#/admin/codeset/*	2001
g	GET#/admin/datasource/*	2002
g	GET#/admin/imageRepository/*	2003
g	GET#/admin/job/*	1005
g	GET#/admin/jobenv/*	1006
g	GET#/admin/ops/component	1004
g	GET#/admin/ops/component/*	1004
g	GET#/admin/ops/dashboard	1001
g	GET#/admin/ops/dashboard/:resource	1001
g	GET#/admin/ops/gpu	1003
g	GET#/admin/ops/gpu/*	1003
g	GET#/admin/ops/node	1002
g	GET#/admin/ops/node/*	1002
g	GET#/admin/quota/*	3004
g	GET#/admin/space/*	3003
g	GET#/admin/system/*	4001
g	GET#/role/*	3002
g	GET#/user/*	3001
g	POST#/admin/codeset/*	2001
g	POST#/admin/datasource/*	2002
g	POST#/admin/imageRepository/*	2003
g	POST#/admin/job/*	1005
g	POST#/admin/jobenv/*	1006
g	POST#/admin/ops/node/*	1002
g	POST#/admin/quota/*	3004
g	POST#/admin/space/*	3003
g	POST#/role/*	3002
g	POST#/user/*	3001
g	PUT#/admin/codeset/*	2001
g	PUT#/admin/datasource/*	2002
g	PUT#/admin/imageRepository/*	2003
g	PUT#/admin/job/*	1005
g	PUT#/admin/jobenv/*	1006
g	PUT#/admin/ops/node/*	1002
g	PUT#/admin/quota/*	3004
g	PUT#/admin/space/*	3003
g	PUT#/role/*	3002
g	PUT#/user/*	3001
p	1	1001
p	1	1002
p	1	1003
p	1	1004
p	1	1005
p	1	1006
p	1	2001
p	1	2002
p	1	2003
p	1	3001
p	1	3002
p	1	3003
p	1	3004
p	1	4001
p	2	1001
p	2	1002
p	2	1003
p	2	1004
p	2	1005
p	2	1006
p	3	2001
p	3	2002
p	3	2003
```

**Your request(s):**

```
1,PUT#/user/edit/1 ---> true (expected: true)
这个过程花费了太长的时间（this process is taking too long）
```

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@dai3023273 Sorry, your model and policy has severe problems, and I couldn't get `true`, plz fix your model and policy first, refer to https://casbin.org/docs/en/syntax-for-models. : )

**Comment by dai3023273** [comment]
You  need to register the function with the enforcer like:
r := e.GetRoleManager()
r.(*defaultrolemanager.RoleManager).AddMatchingFunc("KeyMatch2",util.KeyMatch2)
then,enforce("1",PUT#/user/edit/1)

**Comment by closetool** [comment]
@dai3023273 Nop, KeyMatch2 is buildin function, so you don't need to load it manually.
Actually, there's much bugs in you model and policy.

**Comment by dai3023273** [comment]
If I don't register the function with the enforcer, the enforcer will not match “PUT#/user/edit/1” and “PUT#/user/edit/:id”,
I've now found a better model and policy，But the previous model and strategy worked just fine, it was just too slow。

**Comment by closetool** [comment]
@dai3023273 modify `KeyMatch2` to `keyMatch2`, and you don't need to import it.

**Comment by closetool** [comment]
@dai3023273 And I see that you put obj in `g` section, that's not correct, `g` is for role inheritance.
I highly recommand you to read the docs about rbac. https://casbin.org/docs/en/rbac

**Comment by dai3023273** [comment]
OK, thank you for your patience

**Comment by hsluoyz** [comment]
@DaiJiezou update?

**Comment by DaiJiezou** [comment]
It's working just fine。

**Comment by DaiJiezou** [comment]
The modified model and policy can work very well .
I used the wrong model and policy before, although it works

**Comment by hsluoyz** [comment]
Closed as resolved.
