### ISSUE TITLE
[Bug] CasbinJsGetPermissionForUser broken

### ISSUE THREAD

**Issue by arigon** [casbin/casbin#774]
**Describe the bug**
In at least Version 2.28.4 the CasbinJsGetPermissionForUser function needed for casbin.js is broken. The commit id which removes the user policy is: 3ab5e9ac41ee0448b76594c39363732e839c8f7f

**To Reproduce**
1. Call CasbinJsGetPermissionForUser with a user (which is mandatory anyway)
2. The user attribute isn't processed in the function
3. casbin.js is not working because no user based policies are loaded

**Comment by hsluoyz** [comment]
@Zxilly @closetool

**Comment by Kliton** [comment]
To fix this i just added locally the old function content to a new  function that i call from frontend:

```go
func GetJsPermission(user string) (string, error) {
	domain := "default"
	policy, err := Enforcer.GetImplicitPermissionsForUser(user, domain)
	if err != nil {
		return "", err
	}

	permission := make(map[string][]string)
	for i := 0; i < len(policy); i++ {
		permission[policy[i][3]] = append(permission[policy[i][3]], policy[i][2])
	}
	b, _ := json.Marshal(permission)
	return string(b), nil
}
```

**Comment by hsluoyz** [comment]
Plz use `CasbinJsGetPermissionForUserOld()`: https://github.com/casbin/casbin/pull/805/files
