### ISSUE TITLE
[Question] WatcherEx methods should have ptype parameter.

### ISSUE THREAD

**Issue by gonsuke** [casbin/casbin#775]
Hi team,

I'm looking into WatcherEx mechanisms and the [redis-watcher](https://github.com/casbin/redis-watcher) implementation.
As far as I understand so far, there are 2 ways of trigger of `UpdateForAddPolicy` for example.
One is `Enforcer.AddNamedPolicy`, https://github.com/casbin/casbin/blob/ab6b8e7e136ff05b251abc374e7be38fe9c80e13/management_api.go#L145   and the other is `Enforcer.AddNamedGroupingPolicy`. https://github.com/casbin/casbin/blob/ab6b8e7e136ff05b251abc374e7be38fe9c80e13/management_api.go#L259

Now I'm writing `UpdateForAddPolicy` and other WatherEx event handlers on my application, and I'm trying to call [LoadPolicyLine](https://github.com/casbin/casbin/blob/ab6b8e7e136ff05b251abc374e7be38fe9c80e13/persist/adapter.go#L25-L44) so that the application can load only policy which is delivered from WatcherEx without querying to backend storage.

However, WatcherEx methods don't have `ptype` parameter, so it's unable to construct policy line for `LoadPolicyLine`.
Any thoughts? Should we have `ptype` parameter for each WatcherEx methods?

**Comment by hsluoyz** [comment]
@closetool
