### ISSUE TITLE
[Question]why `SyncedEnforcer`.`EnforceEx` doesn't use `mutex`?

### ISSUE THREAD

**Issue by zsh1995** [casbin/casbin#777]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
`SyncedEnforcer`.`EnforceEx` doesn't use `mutex`, so it can't return a wrong result when `LoadPolicy` clear the policies

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@zsh1995 Thanks for report! Is there still api which hasn't not been implemented?
