### ISSUE TITLE
[Question] Performance with a lot of policies

### ISSUE THREAD

**Issue by RedMonster727** [casbin/casbin#778]
**What's your scenario? What do you want to achieve?**
Hello! We want to use casbin with ACL scenario.
We've made a load test with 30k policies in database and found out, that performance in not good enough, .
We looked on our CPU metrics and noticed, that server is using CPU too much, that is the reason of bad performance. I've tried to understand whats the problem by myself and I think the main cause of big latency is because the complexity of method `Enforce` is O(n) with some recursions inside.
Can you confirm please, is my theory right?

We are going to have pretty loaded service, at least with 5k rps with about 43kk policies. There will be several instances.  I have some thoughts, that we may be cooking Casbin not in the right way.

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, alice, data1, read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write
```

Initialization:
```go
func initPolicyEnforcer(db *database.DB) (*utils.Enforcer, error) {
	var enforcer utils.Enforcer

	aclAdapter, err := sqlxadapter.NewAdapter(db.DB, "acl_rules_test")
	if err != nil {
		return nil, err
	}
	enforcer.AclAdapter = aclAdapter

         // Here we've tried also `NewEnforcer`
	aclEnforcer, err := casbin.NewSyncedEnforcer("policy_models/client_acl_model.conf", aclAdapter)
	if err != nil {
		return nil, err
	}
	enforcer.AclEnforcer = aclEnforcer

	if err = aclEnforcer.LoadPolicy(); err != nil {
		return nil, err
	}

	return &enforcer, nil
}
```

Usage:
```go
func (h *Handler) Handle(ctx context.Context, in *dto.IsAllowedByPolicyIn, out *dto.IsAllowedByPolicyOut) error {
	i := in.In

	var userId string
	if i.Subject.Id != nil {
		userId = *i.Subject.Id
	}

	if res, err := h.Enforcer.Enforce(userId, i.Object.Type, i.Action.Name); res {
		out.Allow = res
	} else {
		out.Allow = res
		if err != nil {
			errMsg := err.Error()
			out.Error = &errMsg
		}
	}

	return nil
}
```

**Comment by hsluoyz** [comment]
Hi @RedMonster727 

1. What's your current qps with Casbin and without Casbin?
2. Why use SyncedEnforcer? SyncedEnforcer will slow down the parallel handler into a serial manner. I don't think you want this. If you are read-only for this part, use Enforcer instead.
3. What Casbin version do you use?
4. What are your requests for testing?

**Comment by RedMonster727** [comment]
1. 
test 1: open load
Linear from 1 to 500 rps and then const 500 rps for 10 minutes,
load - https://prnt.sc/127m55t 
cpu usage - https://prnt.sc/127m6yb
instance crashed couple of times


test 2: close load
linear from 1 to 200 rps
load - https://prnt.sc/127maqu
cpu usage - https://prnt.sc/127mbw5
in this test loader controls that service is capable to answer, so rps was 140-150 with max response time 99%% about 2.5 sec

2. We used both of them and there were no big difference
3. github.com/casbin/casbin/v2 v2.26.1
4. It's a configured list of requests for an instrument called `Yandex.Tank`. Requests contain close to production data, like unique ID of our entity with an object and an action, like ["1234", "item", "publish"]

**Comment by hsluoyz** [comment]
> 1. qps

Can you check https://casbin.org/docs/en/benchmark ? You are using ACL model with 4 p rules. You are expected to have at least 0.02ms/op performance. Plz run that benchmark with a similar machine (CPU).

![image](https://user-images.githubusercontent.com/3787410/116489673-1984ef00-a8c8-11eb-83bf-876212db8fa3.png)

That's an old result and currently I jusr ran with latest Casbin v.2.28.4, it's even faster:

```
goos: windows
goarch: amd64
pkg: github.com/casbin/casbin/v2
cpu: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
BenchmarkRaw
BenchmarkRaw-16                           	70581176	        18.08 ns/op
BenchmarkBasicModel
BenchmarkBasicModel-16                    	   99844	     10295 ns/op
BenchmarkRBACModel
BenchmarkRBACModel-16                     	   81397	     14738 ns/op
BenchmarkRBACModelSmall
BenchmarkRBACModelSmall-16                	    8570	    124912 ns/op
BenchmarkRBACModelMedium
BenchmarkRBACModelMedium-16               	    1015	   1229042 ns/op
BenchmarkRBACModelLarge
BenchmarkRBACModelLarge-16                	      79	  14364478 ns/op
BenchmarkRBACModelWithResourceRoles
BenchmarkRBACModelWithResourceRoles-16    	   76470	     15825 ns/op
BenchmarkRBACModelWithDomains
BenchmarkRBACModelWithDomains-16          	   58558	     20527 ns/op
BenchmarkABACModel
BenchmarkABACModel-16                     	  233829	      5116 ns/op
BenchmarkKeyMatchModel
BenchmarkKeyMatchModel-16                 	   64356	     17933 ns/op
BenchmarkRBACModelWithDeny
BenchmarkRBACModelWithDeny-16             	   77612	     15175 ns/op
BenchmarkPriorityModel
BenchmarkPriorityModel-16                 	  108980	     11212 ns/op
PASS
```

> 3. github.com/casbin/casbin/v2 v2.26.1

Plz use latest Casbin v.2.28.4, it includes a short-circuit feature in your effect: https://github.com/casbin/casbin/releases/tag/v2.27.0 , which improves the performance.

**Comment by RedMonster727** [comment]
> You are using ACL model with 4 p rules.
That one in the first message was just an example of policy. In our load test we had 32k and on production our prediction is about 43kk in first year.

We didn't have some possibility to launch your benchmarks on our machines, but we saw, that if there are about 150 requests per second our CPU gone overloaded.

With updated version it became a little better, but not enough.

Also we wanted to use batchEnforce, what would also make the performance worse.

**Comment by hsluoyz** [comment]
@RedMonster727 I think your performance is expected given our benchmark table. You can provide a more-real version of your model and policy (remove any secret stuff) here, so we can help optimize it based on this scenario.

**Comment by hsluoyz** [comment]
Closed as stale.
