### ISSUE TITLE
[Question] Really slow execution of LoadPolicy method on an existing enforcer instance

### ISSUE THREAD

**Issue by giefferre** [casbin/casbin#781]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Funded-%2300A156.svg" />](https://issuehunt.io/r/casbin/casbin/issues/781)

**What's your scenario? What do you want to achieve?**

Hi 👋 
We are using Casbin in production.

We recently moved from the [GCP Cloud Storage Adapter](https://github.com/qurami/casbin-cloud-storage-adapter) to the [Gorm Adapter](https://github.com/casbin/gorm-adapter).

The enforcer is exposed via an HTTP server.

For internal reasons we offer an HTTP endpoint to forcefully reload permission configuration from database. It basically consists in the execution of the `enforcer.LoadPolicy` method on the enforcer instance.

When launching such method the application freezes for a large amount of time (~4.2 minutes!) to reprocess the database. This behaviour is pretty weird as we only have ~4K rows in the database (64 policies, all other rows are grants). Moreover, when the program bootstraps, the load time is normal.

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.obj) && keyMatch4(r.obj, p.obj) && regexMatch(r.act, p.act)
```

**Your policy:**

You can hereby find a couple examples of our policies

```
p, staff, /orgs/{orgID}/sites/{siteID}, Appointments.GetParameters
p, staff, /orgs/{orgID}/sites/{siteID}, Appointments.GetResources
p, manager, /orgs/{orgID}/sites/{siteID}, .* // while the staff can only run specific methods, the manager can execute any method

g, sampleManagerUser, manager, /orgs/1/sites/site001
g, sampleStaffUser, staff, /orgs/1/sites/site001
```

**Your request(s):**

Enforcer works well

```
sampleStaffUser, /orgs/1/sites/site001, Appointments.GetResources --> true (OK)
sampleStaffUser, /orgs/1/sites/site001, Appointments.NewMethod --> false (OK)
sampleManagerUser, /orgs/1/sites/site001, Appointments.NewMethod --> true (OK)
```

When we run the `LoadPolicy` method on the enforcer, it freezes!

**Environment**

part of the `go.mod`:

```
go 1.15

require (
	github.com/casbin/casbin/v2 v2.28.4
	github.com/casbin/gorm-adapter/v3 v3.2.9
	github.com/go-sql-driver/mysql v1.6.0
)
```

(same results on go 1.16 and go 1.13)

**Additional information**

1. We do use the `SyncedEnforcer` as we expose the enforcer via HTTP in a multithreaded environment
2. Again, we have no problem at all when the enforcer is initialized
3. We ran the go profiler on the execution of the `LoadPolicy`, I've attached the results in a PDF hereafter 👇 
[profile001.pdf](https://github.com/casbin/casbin/files/6399436/profile001.pdf)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars.githubusercontent.com/u/1171932?v=4' alt='giefferre' width=24 height=24> giefferre](https://issuehunt.io/u/giefferre) ($5.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/casbin/casbin/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@giefferre Can I have your data and code?

**Comment by hsluoyz** [comment]
@giefferre it seems to be related with the HTTP framework. Can you share an example repo? So we can reproduce it.

What DB do you use? MySQL what version? Is it intranet or internet?

**Comment by giefferre** [comment]
@closetool I can't share any other data. As I already mentioned, there are 64 policies like the ones I've pasted in the issue, they can be:

```
p, staff, /orgs/{orgID}/sites/{siteID}, Appointments.GetParameters
p, staff, /orgs/{orgID}/sites/{siteID}, Appointments.GetResources
```

they also include

```
p, staff, /orgs/{orgID}, Some.OtherAction
p, staff, /orgs/{orgID}/sites, .*
p, staff, /orgs, Another.Action
```

The grouping policies (aka the grants) are ~4K.

@hsluoyz

1. I've copied an excerpt of the code in the paragraph below
2. We use MySQL 8.0.20; it's via internet, but this is completely irrelevant -- the same happens if we run the application and the DB server with the same data on the same machine. As mentioned above, the initialisation works fine while the LoadPolicy executed manually after the initialisation freezes the application
3. Yes, same behaviour. We switched from GCP Cloud Storage Adapter for architectural reasons, not for this issue
4. Yes, we do need `keyMatch4()` as we run grants or enforces like

```
g, sampleManagerUser, manager, /orgs/1/sites/site002
g, sampleManagerUser, manager, /orgs/1/sites/site003
g, sampleManagerUser, manager, /orgs/1/sites/site004
g, sampleStaffUser, staff, /orgs/1/sites/site001
g, sampleManagerUser, manager, /orgs/2/sites/site001
```

and so on

---

As you can see from the pasted code, there's nothing to do with the HTTP server and/or any other package.

The following code freezes as well:

```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/casbin/casbin/v2"
	"github.com/casbin/casbin/v2/model"
	"github.com/casbin/casbin/v2/util"
	gormadapter "github.com/casbin/gorm-adapter/v3"
	_ "github.com/go-sql-driver/mysql"
)

const (
	permissionConfiguration = `
	[request_definition]
	r = sub, obj, act
	
	[policy_definition]
	p = sub, obj, act
	
	[role_definition]
	g = _, _, _
	
	[policy_effect]
	e = some(where (p.eft == allow))
	
	[matchers]
	m = g(r.sub, p.sub, r.obj) && keyMatch4(r.obj, p.obj) && regexMatch(r.act, p.act)
`
)

func main() {
	sqlConnectionString := os.Getenv("SQL_CONNECTION_STRING")

	gormAdapter, err := gormadapter.NewAdapter("mysql", sqlConnectionString, "casbin", "rbac")
	if err != nil {
		log.Fatal(fmt.Errorf("unable to initialize gorm adapter: %s", err))
	}

	permissionConfigurationModel, err := model.NewModelFromString(permissionConfiguration)
	if err != nil {
		log.Fatal(fmt.Errorf("unable to initialize permission configuration model: %s", err))
	}

	casbinEnforcer, err := casbin.NewSyncedEnforcer(permissionConfigurationModel, gormAdapter)
	if err != nil {
		log.Fatal(fmt.Errorf("unable to initialize casbin enforcer: %s", err))
	}

	casbinEnforcer.LoadPolicy()

	casbinEnforcer.EnableAutoSave(true)
	casbinEnforcer.AddNamedDomainMatchingFunc("g", "", util.KeyMatch4)
	casbinEnforcer.AddNamedMatchingFunc("g", "", util.KeyMatch4)

	log.Println(
		casbinEnforcer.Enforce("sampleManagerUser", "/orgs/1/sites/site001", "Appointments.GetParameters"),
	)

	log.Println(
		casbinEnforcer.GetGroupingPolicy(),
	)

	log.Println("before executing casbinEnforcer.LoadPolicy()...")
	casbinEnforcer.LoadPolicy() // this second execution takes ~4 minutes
	log.Println("after executing casbinEnforcer.LoadPolicy()...")
}
```

@closetool @hsluoyz by analysing the code via debugger, it appears to be really slow in the `assertion.go` method, in this part of casbin code:

```go
func (ast *Assertion) buildRoleLinks(rm rbac.RoleManager) error {
	ast.RM = rm
	count := strings.Count(ast.Value, "_")
	if count < 2 {
		return errors.New("the number of \"_\" in role definition should be at least 2")
	}
	for _, rule := range ast.Policy {
		if len(rule) < count {
			return errors.New("grouping policy elements do not meet role definition")
		}
		if len(rule) > count {
			rule = rule[:count]
		}
		// if we try to add a log.Println(rule) method it works like a charm at the first execution while it is really slow at the second execution
		err := ast.RM.AddLink(rule[0], rule[1], rule[2:]...)
		if err != nil {
			return err
		}
	}

	return nil
}
```

As a workaround we tried to create a new instance of casbin enforcer every time we need to reload policies from the adapter, but it definitely is a _rag rug_, we expect the `LoadPolicy` method to work properly.

**Comment by giefferre** [comment]
Another piece of information: the issue doesn't show up for database with a lower amount of grants (~1200 grouping policies, same amount of policies)

**Comment by hsluoyz** [comment]
@closetool plz investigate the slow performance of the `buildRoleLinks()` function.

**Comment by giefferre** [comment]
@hsluoyz @closetool 👋  
any news on this issue? we're having problems in production due to this

**Comment by hsluoyz** [comment]
@tson1111

**Comment by Sagilio** [comment]
When using pattern and  domain pattern, `BuldRoleLinks` will call the `domainMatchingFunc` and `matchingFunc` `(p + 1) * d * r * 4` times.
- p = grouping policy count
- d = now domain count
- r = now role count

 There are 2 regexes that will be compiled when calling `KeyMatch4` one time.
 So, if you use `KeyMatch4` as `domainMatchingFunc` and `matchingFunc`, I think the regex will call a large time.

I think the performance can be improved mainly from two perspectives ：
1. Reduce call `domainMatchingFunc` and `matchingFunc` count at `AddLink`.
2. Improve the `KeyMatch4` performance.

I have changed a bit to try to improve the performance. #801

**Comment by hsluoyz** [comment]
@Sagilio excellent thought on the time complexity analysis! It also inspired me of something:

1. Can we move more calculation from HasLink() to AddLink()? Like caching `KeyMatch4()` results between two nodes in the RBAC graph.
2. What's the current time complexity after your PR?
3. Can you run a test to get the real performance gain for your PR?

**Comment by sagilio** [comment]
@hsluoyz 
1. This issue is mainly about the performance of `buildRoleLinks(AddLink)`, there is already a cache for `HasLink`.
2. The times of invoking `KeyMatch4` change from `p * d * r * (1 - 4)` to `p * d * r * (1 - 2)`. But it will reduce half of the regex compile time.
3. I have written a test for this case, the real performance gain is about 35%, not up to orders of magnitude (10x). This result is expected, we need more changes to fix this issue.

model file: [rbac_with_pattern_large_scale_model.conf](https://github.com/sagilio/casbin/blob/fix%23781/examples/performance/rbac_with_pattern_large_scale_model.conf)
policy file: [rbac_with_pattern_large_scale_policy.csv](https://github.com/sagilio/casbin/blob/fix%23781/examples/performance/rbac_with_pattern_large_scale_policy.csv)
scale: 132 policies / 3000 grouping policies / 300 subjuects / 6 roles
test case: 
```go
func BenchmarkBuildRoleLinksLarge(b *testing.B) {
	e, _ := NewEnforcer("examples/performance/rbac_large_scale_model.conf", "examples/performance/rbac_large_scale_policy.csv")
	e.AddNamedDomainMatchingFunc("g", "", util.KeyMatch4)
	e.AddNamedMatchingFunc("g", "", util.KeyMatch4)

	b.ResetTimer()
	_ = e.BuildRoleLinks()
}
```
```
goos: windows
goarch: amd64
pkg: github.com/casbin/casbin/v2
cpu: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

BenchmarkBuildRoleLinksLarge
BenchmarkBuildRoleLinksLarge (New)   	       1	65013839800 ns/op
BenchmarkBuildRoleLinksLarge (Old)   	       1	101521028000 ns/op
```

**Comment by sagilio** [comment]
@giefferre According to your example, `AddNamedMatchingFunc` may be unnecessary, Need you use the `keyMatch4` between subjects and roles or users?

**Comment by sagilio** [comment]
The performance of the current version has a good improvement (#801), in my test cases, the real performance gain is about 6400%. Can you have a try on this version?
