### ISSUE TITLE
[Feature] Add Some APIs to on RBAC API

### ISSUE THREAD

**Issue by sujit-baniya** [casbin/casbin#782]
**Want to prioritize this issue? Try:**
Yes

------

**Is your feature request related to a problem? Please describe.**
Currently I'm not able to get all users based on domain. I need to use multiple APIs to get all users of a domain. Also looking for some new APIs (if not already available)

**Describe the solution you'd like**
I'm looking for addition of following APIs (if possible)

- `GetAllUsersByDomain(name string)` - This would get all users associated with the domain
- `DeleteAllUsersByDomain(name string)` - This would delete all users associated with the domain
- `DeleteDomains(name ...string)` - This would delete all domains if parameter is not provided. Also this would delete all associated users and roles

**Comment by hsluoyz** [comment]
@closetool

**Comment by hsluoyz** [comment]
@sujit-baniya docs added: https://github.com/casbin/casbin-website/pull/211
