### ISSUE TITLE
[Question] Are different group/role systems supposed to be isolated or merged?

### ISSUE THREAD

**Issue by lanmarti** [casbin/casbin#783]
**What's your scenario? What do you want to achieve?**
We're attempting to have distinct groups for subjects and objects with the same name (subjects can also occur as objects). However, it seems Casbin does not care whether you use g, g2, g3... to group items together. Any grouping seems to work at any position. Therefore, `g, a, b` has the same effect as `g2, a, b` or `g3, a, b`.
From reading the documents, it is not clear to me whether this is intended behaviour or not. I would expect g, g2, g3 etc to be isolated from each other, but it seems that they are all treated as one big group and the group name does not carry any functional meaning.

The original issue was spotted using jCasbin, further testing was done using the online Casbin Editor. 
I am aware that with proper namespacing for subject, objects and actions, this will not lead to  issues. However, this will give unexpected results when there is any overlap between subject, object or action names. We discovered this issue because some subjects are also used as objects, using the same exact string.

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _
g3 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && g3(r.act, p.act)
```

**Your policy:**
Example 1
```
p, alpha, one, actA
g, beta, alpha
g, two, one
g, actB, actA
```

**Your request(s):**

```
alpha, one, actA  --> true
beta, one, actA  --> true
beta, two, actA  --> true (expected: false)
beta, two, actB  --> true (expected: false)
beta, one, actA  --> true (expected: false)
alpha, two, actA  --> true (expected: false)
```
Example 2
```
p, alpha, one, actA
g2, beta, alpha
g2, two, one
g2, actB, actA
```

**Your request(s):**

```
alpha, one, actA  --> true
beta, one, actA  --> true (expected: false)
beta, two, actA  --> true (expected: false)
beta, two, actB  --> true (expected: false)
beta, one, actA  --> true (expected: false)
alpha, two, actA  --> true
```

Additional notes: you can replace the matcher of the model with any combination of g, g2, g3, it always results in the same request results. e.g. `m = g(r.sub, p.sub) && g(r.obj, p.obj) && g(r.act, p.act)` ==  `m = g2(r.sub, p.sub) && g2(r.obj, p.obj) && g2(r.act, p.act)`

**Comment by hsluoyz** [comment]
Hi @lanmarti 

g and g2 are two different RBAC systems. Their role links are totally separated. So g and g2 are supposed to have nothing to do with each other. See docs: https://casbin.org/docs/en/rbac

If I remember right, Casbin Golang may have such bugs to have shared some states between g and g2, but we already got it fixed. Plz use latest version.

If you are using other languages than Golang, please fire GitHub issues at that repo and we will fix it for you.

**Comment by hsluoyz** [comment]
@closetool

**Comment by lanmarti** [comment]
Thank you for the clarification, @hsluoyz 
I'm not using the golang version directly, so I can't say if the issue is present here or not. I'll open tickets in the relevant repositories.

**Comment by shy1st** [comment]
> Hi @lanmarti
> 
> g and g2 are two different RBAC systems. Their role links are totally separated. So g and g2 are supposed to have nothing to do with each other. See docs: https://casbin.org/docs/en/rbac
> 
> If I remember right, Casbin Golang may have such bugs to have shared some states between g and g2, but we already got it fixed. Plz use latest version.
> 
> If you are using other languages than Golang, please fire GitHub issues at that repo and we will fix it for you.

@hsluoyz @closetool  Please tell me the code of casbin to solve this problem. I want to solve this problem: https://github.com/casbin/jcasbin/issues/186

**Comment by hsluoyz** [comment]
@closetool can you provide a link to the PR that resolved this bug in Golang?

**Comment by closetool** [comment]
@hsluoyz @shy1st @lanmarti plz refer to https://github.com/casbin/casbin/issues/685 https://github.com/casbin/casbin/pull/724
