### ISSUE TITLE
[Bug]GetAllUsersByDomain

### ISSUE THREAD

**Issue by wusphinx** [casbin/casbin#789]
**Describe the bug**
I got nothing with `GetAllUsersByDomain`

**To Reproduce**
[model.conf](https://github.com/casbin/casbin/blob/master/examples/rbac_with_domains_model.conf)
[policy.csv](https://github.com/casbin/casbin/blob/master/examples/rbac_with_domains_policy.csv)
```go
package domain

import (
	"testing"

	"github.com/casbin/casbin/v2"
)

func TestDomain(t *testing.T) {
	e, err := casbin.NewEnforcer("model.conf", "policy.csv")
	if err != nil {
		t.FailNow()
	}

	users := e.GetAllUsersByDomain("domain2")
	t.Logf("users :%v", users)
}
```

**Expected behavior**
According to the configuration, at least admin should be in the returned results

**Comment by hsluoyz** [comment]
@closetool
