### ISSUE TITLE
[Help wanted] your comments about Casbin are welcomed

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin#79]
Hi everyone,

First thank you all for using Casbin! I am Yang Luo, a Ph.D student in Peking University. I major in ``Software Engineering`` and my research area is ``Access Control``. I'm going to have my Ph.D thesis defense this semester. And Casbin is one of my best research products. So I'd like to collect some information about Casbin's usage in companies/organizations.

I know there are already some uses from Intel, VMware, Cisco, Verizon, etc. But my list is far from complete. So your help here will be very useful for me. I expect the following kinds of information. You can just reply in this issue:)

1. Your company or organization name.
2. What kind of project did you use Casbin in? Better with a project name and a short description. If it is also open-source, you can just throw me with a link:)
3. The scale of your system/project. Like the number of users and policy rules that are used.
4. Please comment about Casbin? Just several sentences would be good.

Thanks again for your cooperation!

Regards,
Yang

**Comment by hsluoyz** [comment]
@faceless-saint @cdennison @neosab

**Comment by zhanghepeng** [comment]
您好，能否多提供一些 casbin 的 完整的例子，我在使用iris web框架来写一些项目的时候，想用casbin来做控制，官方提供的demo 不是太理解。

**Comment by hsluoyz** [comment]
@zhanghepeng please add QQ group: 546057381 for discussion.

**Comment by zhanghepeng** [comment]
ok

**Comment by TechMaster** [comment]
Hi Yang Luo,

We are going to use Casbin. I will update to you frequently.

Thanks for writing a good library.

Cuong,

**Comment by hsluoyz** [comment]
@neosab @ArthurHlt

**Comment by shlomi-nx** [comment]
Just started using casbin, and I must say that the PERM metamodel is absolutely fantastic. It is extremely malleable and enables very wide range of customizations with just a few lines of code. 

I could not find any papers on this metamodel, is it your invention? 

Thanks!

**Comment by hsluoyz** [comment]
@shlomi-nx thanks for using it!

We have a paper at Arxiv: https://arxiv.org/abs/1903.09756

**Comment by obashistu** [comment]
We're currently looking at using Casbin however it feels like theres a lot of work to do to make the library (Go) robust enough for our needs. Looking through the code `panic` is used in several places when error propagation would be the sensible thing to do. In production I never want software to panic - I want to capture (and log) errors before making a decision on what to do next. 

In other places I notice policy lines are simply hacked onto a model using it's internal structures which isn't particularly safe and bypasses any sanity checking introduced in `model.AddPolicy` (I have a small PR up for this).

Overall I like Casbin but have more than a few concerns that I hope can be addressed inside the main repo. 

Thanks.

**Comment by hsluoyz** [comment]
@obashistu thanks for using. I have replied to your issues and PRs.

**Comment by obashistu** [comment]
Unfortunately we have decided not to use Casbin for our platform due to the poor quality Go implementation. Unfortunate because the concept is fantastic and would have been perfect for our situation. 

Pouring over the code it was painfully clear that error handling has been largely omitted with runtime panics and logic bombs all over the place. **For production purposes nobody should be ignoring errors or allowing their software to panic.** Seeing comments such as `error intentionally ignored` with zero logging around it almost made me cry...bad enough you ignore the error but because you fail to log it nobody knows anything is wrong!! I could go on and on about functions with string slice params, slice handling in general and thread safety...but I wont. 

The main power and flexibility of Casbin is derived from the ability to parse and execute matcher rules - something that anyone can get by using the awesome https://github.com/Knetic/govaluate.

**Comment by shlomi-nx** [comment]
I agree with the concerns raised by @obashistu. We are not using the go implementation at all, for similar reasons. Another reason we stay away from the go implementation is that it diminishes usability of ABAC models (https://github.com/casbin/casbin-server#limitation-of-abac). 

Currently we are using the node version, it is nicely typed and works very well for us. Would be nice to get casbin-server node implementation as well as go.

**Comment by hsluoyz** [comment]
Hi, we have released v2.0.0 which addresses the error handling problem: https://github.com/casbin/casbin/releases/tag/v2.0.0

**Comment by obashistu** [comment]
> Hi, we have released v2.0.0 which addresses the error handling problem: https://github.com/casbin/casbin/releases/tag/v2.0.0

Good news that error handling is better. Since this is a breaking change would it be possible to make: 

`NewModel` in `enforcer.go` **Private** ?

The code here needs a good refactor and that function needs to be removed (over time) so may aswell descope it now.

**Comment by hsluoyz** [comment]
Why ``NewModel()`` needs to be private?

**Comment by obashistu** [comment]
> Why `NewModel()` needs to be private?

Well for one it's a Model constructor which is found in the enforcer code - it should be defined as part of the Model code. 

For another the actual constructor logic is awful. It uses the length of input to determine what to do without ever using more than the first argument. 

The actual function should be hidden then eventually removed. If you need to construct a Model and invoke loading behaviour my suggestion would be:

`NewModelFromFile` or `NewModelFromtext`

Both of which may return a Model and an error (if the file or text could not be parsed)

**Comment by hsluoyz** [comment]
I think you are right. It has been fixed in: https://github.com/casbin/casbin/commit/0be51c9a1dfc06d543c52e29ab26dca16357109f

**Comment by obashistu** [comment]
> I think you are right. It has been fixed in: [0be51c9](https://github.com/casbin/casbin/commit/0be51c9a1dfc06d543c52e29ab26dca16357109f)

Looks good. While on an API breaking spree would it make sense to now fully deprecate `LoadModel` since we now have 2 new functions that support loading from file and string?

Further API breaks should be communicated - someone somewhere may have been using the `NewModel` function since it was public.

**Comment by obashistu** [comment]
> I think you are right. It has been fixed in: [0be51c9](https://github.com/casbin/casbin/commit/0be51c9a1dfc06d543c52e29ab26dca16357109f)

Looks good.

**Comment by 100101001** [comment]
Hi~ I m trying to use casbin RBAC with pattern model to control backend API access，and it fails to match patterns。i've downloaded the example and run the corresponding test, it FAILED as my case!NEED INSTRUCTIONS ON usage of RBAC WITH PATTERN MODEL

**Comment by weberr13** [comment]
Hello, I am evaluating Casbin for our RBAC system and I am curious about your decision to only support one matcher (or how I'm supposed to use EnforceWithMacher).  Here is the use case:

User has access to "foo/*" with write permissions
User has a role that restricts access to "foo/bar" (read only)

I want to check roles for write access, but take away write access if the object is restricted.  I need a "not_match" matcher to do this.  Any thoughts?

**Comment by hsluoyz** [comment]
@weberr13 please send a new issue.
