### ISSUE TITLE
[Bug] Enforcer.LoadPolicy error prone if adapter has intermittent database error

### ISSUE THREAD

**Issue by hiteshsethi** [casbin/casbin#791]
**Describe the bug**
In cases when the adapter(example: etcd or redis) is having intermittent database issues, casbin enforcer can make the model map empty

```go
e.model.ClearPolicy()
if err := e.adapter.LoadPolicy(e.model); err != nil && err.Error() != "invalid file path, file path cannot be empty" {
return err //if this throws an error model map will become empty
}
```
This will lead to all new authorization requests become false

**To Reproduce**
1. Start the casbin enforcer with etcd/redis adapter and related watcher
2. Add a new policy
3. Introduce a network error, make etcd down
4. In callback, load policy is called which makes the model map empty

**Expected behavior**
LoadPolicy should either rollback the model with an error
OR
New method should be written to LoadPolicyWithZeroSideEffects
1. By checking the diff of the model(new/old), reapply 
2. OR Store the state temporarily and reapply

Currently I'm setting this in callback
```go
    func enforceLoadPolicy(s string) {
            //this in retry loop
             mu.Lock()
	    defer mu.Unlock()
	    model := casbinEnforcer.GetModel()
	    pModel := copyCasbinMap(model["p"])
	    gModel := copyCasbinMap(model["g"])
	    err := casbinEnforcer.LoadPolicy()
	    if err != nil {
		    glog.Error("critical error happened while loading policy: ", err)
		    if err.Error() == "intermitted error" //or anything related {
			    //we know we can safely revert
			    model["p"] = pModel
			    model["g"] = gModel
		    }
	    }
	    return 
    }
```

Happy to raise a Pull Request for this if this is acknowledged.

**Comment by hsluoyz** [comment]
@closetool @tson1111

**Comment by hsluoyz** [comment]
Re-opened owing to: https://github.com/casbin/casbin/pull/822
