### ISSUE TITLE
[Question] got a panic when I using EnforceWithMatcher to define my custom comparator

### ISSUE THREAD

**Issue by sameor** [casbin/casbin#793]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Your answer here
I got a panic when I using EnforceWithMatcher to define my custom comparator
**Your model:**

```ini
[request_definition]
r = role, url

[policy_definition]
p = role, url

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = my_func(r.role, p.role) && r.url == p.url
```

**Your policy:**

```
p, assistant, /classroom/room/v1/enter_room/
p, teacher, /classroom/room/v1/finish_room/

g, assistant, teacher
```

**Your request(s):**
```go
package main

import (
	"fmt"
	
	"github.com/casbin/casbin/v2"
)

func KeyMatch(args ...interface{}) (interface{}, error) {
	return args[0] == args[1], nil
}

func main() {
	cas, err := casbin.NewEnforcer("model.conf", "policy.csv")
	if err != nil {
		panic(err)
	}

	cas.AddFunction("my_func", KeyMatch)

	userRole := "assistant"
	requestURL := "/classroom/room/v1/enter_room/"

	ok, err := cas.EnforceWithMatcher("my_func", userRole, requestURL)
	if err != nil {
		panic(err)
	}
	if ok {
		fmt.Println("accept")
		return
	}
	fmt.Println("deny")
}
```

```
panic: Unexpected end of expression (expected: accept will be print)
```

**Comment by hsluoyz** [comment]
@closetool @tson1111

**Comment by RobotHuang** [comment]
EnforceWithMatcher should pass a matcher, not a function.

**Comment by closetool** [comment]
@sameor Like @RobotHuang said, `EnforceWithMatcher` receives a matcher as its parameter.
And I noticed there's `[role_definition]` but no `g` function in your matcher, that's not correct, plz refer to https://casbin.org/docs/en/rbac

**Comment by hsluoyz** [comment]
Closed as resolved.
