### ISSUE TITLE
SQL backed RBAC

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin#8]
> Maybe this is possible and I am just not clear on how I would implement it. Is it possible for me to save/load my role and permission data out of a mysql database (or another type of DB)?

Hi @swill, [Casbin](https://github.com/casbin/casbin) is a new authorization library which supports flexible access control models like ACL, RBAC, ABAC.

Casbin supports persisting the policy in database, including RDBMS (like MySQL) and No-SQL (like Cassandra). Let me know if you have any questions:)

**Comment by gnanakeethan** [comment]
I just wonder how the DB migrations are handled and how the data is stored into Backends?

**Comment by hsluoyz** [comment]
Hi @gnanakeethan ,

> I just wonder how the DB migrations are handled

what do you mean by migrations? migrate from old version policy to a new version policy? or migrate from a DB instance to another DB instance? If you mean the former (version update), there's no such mechanism for now, because the policy format is still steady since its born. If mean the latter, it's quite simple. Just use two adapters, load policy from an adapter to an enforcer, and then save policy to the other adapter.

> and how the data is stored into Backends?

it differs for different adapters (backends). for DB like MySQL, one Casbin policy rule is inserted into the table as one record.

**Comment by gnanakeethan** [comment]
Do I have to create a table for Casbin, or casbin can do it itself? I do not see a clear statement regarding the data storage into MySQL. It would be easier to understand than to go through code to understand the mechanism.

**Comment by hsluoyz** [comment]
The MySQL adapter will use the DB named ``casbin``. If it doesn't exist, the adapter will create it automatically. The only public API for an adapter is ``LoadPolicy()`` and ``SavePolicy()``.

**Comment by gnanakeethan** [comment]
Thanks. That was bit confusing there.

**Comment by hsluoyz** [comment]
You're welcome:)
