### ISSUE TITLE
DeleteRole in domain，Need DeleteRole only in some Domains

### ISSUE THREAD

**Issue by piyongcai** [casbin/casbin#808]
In current casbin version, delete a role will delete all policies。

Is there a way to only remove policies in some domain
eg ： DeleteRole(role string, domain... string)

**Comment by hsluoyz** [comment]
@piyongcai plz use English

**Comment by hsluoyz** [comment]
@closetool

**Comment by piyongcai** [comment]
In current casbin version, delete a role will delete all policies。

Is there a way to only remove policies in som domain
eg ： DeleteRole(role string, doains... string)

**Comment by closetool** [comment]
@piyongcai plz refer to https://casbin.org/docs/en/rbac-with-domains-api#deletealluserbydomain
https://casbin.org/docs/en/rbac-with-domains-api#deleteroleforuserindomain
https://casbin.org/docs/en/rbac-with-domains-api#deleterolesforuserindomain,
does these meet your requirements?

**Comment by hsluoyz** [comment]
Closed as resolved.
