### ISSUE TITLE
[Question]how to support Multi-tier tenants

### ISSUE THREAD

**Issue by hzliangbin** [casbin/casbin#813]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Casbin supports [RBAC with Domains](https://casbin.org/docs/zh-CN/rbac-with-domains). 
In my scenario, i have tenants as first-class domain. In tenant there is a second-class isolation such as namespace.
Both need rbac system. how to write a model conf?

thanks!

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
Hi @hzliangbin thanks for chosing casbin. In your scenario, you need namespace but domain has been used. You could using `KeyMatch`.
https://github.com/casbin/casbin/blob/master/examples/keymatch_policy.csv
https://github.com/casbin/casbin/blob/master/examples/keymatch_model.conf

**Comment by hsluoyz** [comment]
@hzliangbin

**Comment by hsluoyz** [comment]
Closed as resolved.
