### ISSUE TITLE
The `index` parameter is not used by the `DeleteDomains(...)` method

### ISSUE THREAD

**Issue by remyduthu** [casbin/casbin#814]
It seems that the `DeleteDomains(index int, domains ...string)` method does not use the `index` parameter anymore. Could it be removed?

https://github.com/casbin/casbin/blob/bdee23aafb01ac406e1efc9265f94528a840699d/rbac_api_with_domains.go#L121

**Comment by hsluoyz** [comment]
@closetool remove index as a fix commit.
