### ISSUE TITLE
[Question] Whether planning support to load related policy from storage when process enforce?

### ISSUE THREAD

**Issue by cnwangjie** [casbin/casbin#816]
Hi, @hsluoyz.

I'm learning Casbin recently. It made a really good abstract for authorization. But I noticed it need to load all policies in memory and need to travel all policies instead use some data structure to improve search policy for a request. So I think it is suitable for a single instance service or a single tenant system, right? It's hard to imagine using it in a multi-tenant SaaS.

I think if we do some abstraction for enforcer internal to allow it load some related policy for one request can solve this problem and make Casbin have more usage in the production enviroment. Whether this in your plan or not?

**Comment by hsluoyz** [comment]
@cnwangjie see:

https://casbin.org/docs/en/policy-subset-loading

https://casbin.org/docs/en/performance

**Comment by cnwangjie** [comment]
@hsluoyz, thanks for your reply.

I've read these docs. You mentioned doing sharding for Casbin enforcer and gave an example for this. But he is still not applicable in many cases, although can solve some cases.

> Do sharding

For smaller shard in one instance, a tenant can be treated as an obj and we only load the data related by one tenant in an instance. But in extreme cases it may still contain a huge number of users and policies.

So, go further, we may need to load the data related to one user and one action in one instance. But in this case we cannot construct "Casbin Enforcers" all possible requests in advance. And then we need to make a new "enforcer" for each request.
At this time, current policy adapters are not suitable. Casbin users need to make a filter for their storage (maybe some DB queries).

Do sharding by Casbin users may be a solution. But I think Casbin can do more for these cases. Such as abstract the DB queries in the adapter. For these, the interface of adapters may become more complex. But I think it is worth having an open source project to make these.

What's your think about it? :)

**Comment by hsluoyz** [comment]
@cnwangjie you can write your own adapter to fulfill your special need, just need to follow our adapter interface. If it's open-source, we are also happy to put it into the official site.

**Comment by hsluoyz** [comment]
Closed as resolved.

**Comment by tuchuants** [comment]
Since casbin suggests to use a low-number-policies pattern, I think what make sense is a load-at-runtime role manager rather than a complex adapter. Loading all users and roles relations into the memory of every instance is quite unacceptable when there are millons of users in the database.
