### ISSUE TITLE
GetPermissionsForUser() under RBAC model 

### ISSUE THREAD

**Issue by JokerBruceChan** [casbin/casbin#82]
I have mapped the user "u_1" with the role "r_1", and the role "r_1" has the permissions "add","update","select". but ,when i use GetPermissionForUser() mothed to get the u_1's permissions,
the result is [].

why?

**Comment by hsluoyz** [comment]
``GetPermissionForUser()`` does not handle the indirect links. You will only get the permissions directly assigned to ``u_1``.  Only ``Enforce()`` function handles indirect links. Or you can implement a custom role manager and expose your desired functions on your own.

**Comment by hsluoyz** [comment]
Close as staled.
