### ISSUE TITLE
[Bug] `initRmMap` overriding custom `RoleManager`s with the default one

### ISSUE THREAD

**Issue by natsukagami** [casbin/casbin#820]
**Describe the bug**
`enforcer.initRmMap` is overriding the custom `RoleManager` with the default one. 
This function is used in numerous places, including `enforcer.initialize` and whenever `LoadPolicy` is run, if `autoBuildRoleLinks` is enabled.

This change was introduced in 
https://github.com/casbin/casbin/commit/8e99d455df8d6cf7fcfe913a793c88e76568c138#diff-52fa32ffe98987501702e518f1b8ed9404f47f96bc246daa564bcfac253cd88bR392-R394

WIth this change, it is unpredictable to know when the `RoleManager` gets overwritten, and thus rendering the usage of a custom `RoleManager` impossible.

**To Reproduce**
1. Create an `Enforcer` with a custom `RoleManager`.
2. Run a query, notice that the custom `RoleManager` is never used.

**Expected behavior**
The custom `RoleManager` should be used.

**Additional context**
The above issue occured in v2.31.4, where the above change was effective.

**Comment by hsluoyz** [comment]
@closetool @tangyang9464

**Comment by hsluoyz** [comment]
@natsukagami we will revert the PR: https://github.com/casbin/casbin/pull/819 first

**Comment by hsluoyz** [comment]
@closetool I can't auto-revert the PR: https://github.com/casbin/casbin/pull/819  can you manually revert it?
