### ISSUE TITLE
[Question] When to refresh cache in enforcer_cached

### ISSUE THREAD

**Issue by ziranl16** [casbin/casbin#832]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

Hi, I was trying to used the cached version of enforcer in casbin, but I am a little confused about cache refreshing. It seems from the `enforcer_cached_test.go` that when cache is enabled, if we remove a policy rule the cache will not be refreshed. 

The only time cache will be refreshed is when we call `e.InvalidateCache()` which clears all cache. Wondering shall we use a cache-aside pattern here, which would be more efficient. So if there are any updates in the policies, we just delete the keys. In this way, the cache would be consistent with our policy rule data.

**Comment by hsluoyz** [comment]
@closetool @tangyang9464

**Comment by ziranl16** [comment]
Hi @hsluoyz, thanks a lot for ur fast reply. just another small suggestion here, wondering if it would be even better if we set a survival time for the cache record. So this preserves the consistency of data in the worst case, if `invalidateCache` fails or have errors.

**Comment by sagilio** [comment]
Casbin now only clears the cache when calling `e.InvalidateCache()` manually, I think we can support to auto-call `e.InvalidateCache()` when the policy changed firstly, and this can provide a little more efficient experience as you said.

For more features such as survival time, we can try to provide a cache interface to use some exist common cache lib like a plugin.

**Comment by ziranl16** [comment]
> Casbin now only clears the cache when calling `e.InvalidateCache()` manually, I think we can support to auto-call `e.InvalidateCache()` when the policy changed firstly, and this can provide a little more efficient experience as you said.
> 
> For more features such as survival time, we can try to provide a cache interface to use some exist common cache lib like a plugin.

seems good to me

**Comment by hsluoyz** [comment]
@closetool @tangyang9464 plz work on these two features:

1. Invalidate a specific key for a policy change (add, remove, update, etc.).
2. Invalidate a specific key by its expire time.

@ziranl16 is this correct?

**Comment by ziranl16** [comment]
> @closetool @tangyang9464 plz work on these two features:
> 
> 1. Invalidate a specific key for a policy change (add, remove, update, etc.).
> 2. Invalidate a specific key by its expire time.
> 
> @ziranl16 is this correct?

Hi @hsluoyz ! Yup I think it would be a great idea from my humble opinion haha

**Comment by ziranl16** [comment]
Thank u so much guys! 👍
