### ISSUE TITLE
We have a method that gives the presence or absence of a role That is, it has a word parameter and it has a role

### ISSUE THREAD

**Issue by mrbardia72** [casbin/casbin#834]
We have a method that gives the presence or absence of a role
That is, it has a word parameter and it has a role

**Comment by hsluoyz** [comment]
@closetool @tangyang9464

**Comment by tangyang9464** [comment]
@mrbardia72 Do you mean you need a method to determine whether the role exists?
Could you describe it in detail？

**Comment by closetool** [comment]
@mrbardia72 Does this method satisfy your requirement?
https://casbin.org/docs/en/rbac-api#hasroleforuser

**Comment by mrbardia72** [comment]
> @mrbardia72 Do you mean you need a method to determine whether the role exists?
> Could you describe it in detail？

I want a method to take only one input
And that input is the role and in the output tell whether this role exists or not
Note: Take only one input, that input also plays a role

**Comment by mrbardia72** [comment]
> @mrbardia72 Does this method satisfy your requirement?
> https://casbin.org/docs/en/rbac-api#hasroleforuser

No, this is not the way
I want a method to take only one input
And that input is the role and in the output tell whether this role exists or not
Note: Take only one input, that input also plays a role

**Comment by mrbardia72** [comment]
@tangyang9464 @tangyang9464 @hsluoyz 
‍‍‍```
For example, something like the following
e.hasrole ("role: admin)
Which returns true or fasle output
```

**Comment by hsluoyz** [comment]
@mrbardia72 if you only use `g`, you can use this API: https://casbin.org/docs/en/management-api#getfilteredgroupingpolicy

If you use `g2` and more, you can use this instead: https://casbin.org/docs/en/management-api#getfilterednamedgroupingpolicy

**Comment by mrbardia72** [comment]
@hsluoyz No, this is not the answer to my question

**Comment by hsluoyz** [comment]
@mrbardia72 can you describe a little more about it?

**Comment by mrbardia72** [comment]
@hsluoyz I solved the problem, I came with a function, I took all the roles, then I came in a presentation and searched whether there is a role or not.
I did this in the golang programming language

**Comment by hsluoyz** [comment]
Good to hear it's resolved!
