### ISSUE TITLE
[Feature] Multiple policy definitions 

### ISSUE THREAD

**Issue by wgarunap** [casbin/casbin#835]
I am referring https://casbin.org/docs/en/syntax-for-models#policy-definition
similar question thread https://github.com/casbin/casbin/issues/720

Currently I am using all in one policy line for RBAC and ABAC which is lengthy and little messy. 
```
p  = type, role,domain,resource,action,requesterOb,dataOb,eft
```

I think having multiple policy definitions can make the implementation more clear and efficient. As a example

**My Expected Model :**
```ini
[request_definition]
r = role,domain,resource,action,requesterOb, dataOb

[policy_definition]
p = role, domain, resource, action,eft
p2= role,domain,requesterOb,dataOb,action,eft
```

**My Expected Policy file:**
```
p,admin, dom1, /data1, edit, allow
p2,user, dom1, r.requesterOb.id!=r.dataOb.id, view, deny
```

```
req1 
admin,dom1,/data1,edit ---> allow

req2
user,dom1,{"id":123},{"id":12444444},view ---> deny
user,dom1,{"id":123},{"id":123},view ---> allow
```

**Comment by hsluoyz** [comment]
@closetool @tangyang9464 plz implement this feature.

**Comment by tangyang9464** [comment]
@wgarunap your request params must corresponding request_define.
But in your example,you have two kind of request

@hsluoyz @closetool this means we need r2 if the example request don't change？

**Comment by wgarunap** [comment]
@tangyang9464 
Ideally there should be multiple request types and multiple policy types.

**Comment by tangyang9464** [comment]
@wgarunap I think so.I'll try to make it more generic
