### ISSUE TITLE
Filter items by criteria in policy

### ISSUE THREAD

**Issue by Scukerman** [casbin/casbin#84]
How would you suggest me to implement this?

```golang
type User struct {
	Id   int
	Role string
}

type Application struct {
	Id     int
	UserId int
}

// All Applications with many different Developers (User with Role == Developer)
type Applications []Application

func (apps Applications) List( /*...*/ ) {
	/*...*/
}
```

`User` with role `Developer` can call `List` and should get only his `Applications`.
`User` with role `Admin` can call `List` and should get all `Applications`.

I'm trying to implement CRUD for RPC based on conditions to filter.
The preffered way is to keep conditions in policy list.
Smth like this:

| role      | service     | action | conditions                 |
| --------- | ----------- | ------ | -------------------------- |
| Developer | Application | List   | self.Id == service.UserId, ... |
| Admin | Application | List   |  |

The `self` is a reserved keyword that references the current user's properties.

**Comment by hsluoyz** [comment]
Your requirement is normally seen need. But based on how Casbin works, currently there is no way to directly filter items. You have to determine the access based on a single item. If you have any idea about how to make it work beautifully, please let me know. And I will also try to find how to realize such a scenario.

**Comment by hsluoyz** [comment]
We have a solution now, use `BatchEnforce()` API: https://github.com/casbin/casbin/issues/710
