### ISSUE TITLE
Casbin in multithreaded manner

### ISSUE THREAD

**Issue by Pyav123** [casbin/casbin#840]
For Performance Optimization, multithreading is given as an option in casbin documentation, but the document isn't telling how we can use casbin in multi threading manner. Any example on how multithreading can be achieved? Can anyone suggest me how it can be implemented ?

**Comment by hsluoyz** [comment]
![image](https://user-images.githubusercontent.com/3787410/125790247-9f728922-c753-4358-8cd1-d52f08f56f74.png)

See: https://casbin.org/docs/en/multi-threading
