### ISSUE TITLE
How to use function pass multiple params in policy？

### ISSUE THREAD

**Issue by piecego** [casbin/casbin#843]
**Your model:**

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub_policy, dom, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = eval(p.sub_policy) && r.dom == p.dom && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, roleMatch('Author', r.sub.Roles), d01, /data1, read
```

**Your request(s):**

```
{ Rules: ["Author"] }, d01, /data1, read
```

I cannot use the `roleMatch('Author', r.sub.Roles)`, It says `Unclosed ( at character 75` after run the test, I guess it conflict with policy separator, How should i solve this problem?

**Comment by hsluoyz** [comment]
@closetool @tangyang9464

**Comment by piecego** [comment]
I use space instead of comma, it works.

**Comment by tangyang9464** [comment]
@piecego
Why don't you use it like this ``m = roleMatch('Author', r.sub.Roles)``
now ``p, roleMatch('Author', r.sub.Roles), d01, /data1, read`` is use ``,`` as the separator.So ``roleMatch('Author', r.sub.Roles)`` cannot be recognized as a whole

**Comment by piecego** [comment]
@tangyang9464 Because it is dynamic.

**Comment by hsluoyz** [comment]
> I use space instead of comma, it works.

@piecego what do you mean by this?

**Comment by piecego** [comment]
> > I use space instead of comma, it works.
> 
> @piecego what do you mean by this?

`p, roleMatch('Author' r.sub.Roles), d01, /data1, read`

Use space symbol in after `'Author'`

**Comment by closetool** [comment]
@piecego In fact, we don't know why it works, cause it shouldn't be.
Casbin parses csv file through https://pkg.go.dev/encoding/csv, you can find escape grammer here.
So the recommanded policy should be like this
```csv
p, "roleMatch('Author', r.sub.Roles)", d01, /data1, read
```

We will add this into docs too
