### ISSUE TITLE
Optimize the performance when listing permissions

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin#845]
We need to analyze the user scenario and see how to optimize the performance.

1. https://github.com/devtron-labs/devtron/issues/596
2. https://github.com/devtron-labs/devtron/pull/598

**Comment by hsluoyz** [comment]
@closetool @tangyang9464

**Comment by closetool** [comment]
@hsluoyz @tangyang9464 I found that devtron still using casbin v1, and it uses dep manage dependencies
I try to update dependency for it, but suffered network errors.
```
➜  devtron git:(main) dep ensure -update github.com/casbin/casbin
dep: WARNING: redundant prune option "non-go" set for "github.com/aws/aws-sdk-go"
dep: WARNING: redundant prune option "non-go" set for "github.com/argoproj/argo-cd"
^CSignal received: waiting for 1 ops to complete...
The following issues were found in Gopkg.toml:

  ✗ unable to deduce repository and source type for "google.golang.org/grpc": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://google.golang.org/grpc?go-get=1": Get "http://google.golang.org/grpc?go-get=1": context canceled

ProjectRoot name validation failed
```
@tangyang9464 Could you try to update this dependency?

**Comment by hsluoyz** [comment]
@closetool plz ask them to update to Go Modules first.
