### ISSUE TITLE
Access roles from code or enable wildcard search

### ISSUE THREAD

**Issue by Vlado90** [casbin/casbin#846]
Hi, 

is it possible to add method(s) to access roles (g and g2 rows) from code, or to perform a wildcard search? Currently i can not find any way to perform such task. 

Thanks.

**Comment by hsluoyz** [comment]
Hi @Vlado90 , see: https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac

**Comment by hsluoyz** [comment]
Closed as resolved.
