### ISSUE TITLE
Ask a question about how to associate users and roles simultaneously in RBAC, and how to associate user groups and roles

### ISSUE THREAD

**Issue by twgcode** [casbin/casbin#849]
I would like to ask casbin a question about how the model file is defined
1. User Association Role
2. User Association User Group
   User groups can also be associated with roles
3 Finally, use roles and resources + actions to associate

p, admin, data1, read
p, admin, data1, write
p, default, data, read

g, user1, admin
g, use2, admin
g, user_group, admin
g2, user3, user_group

The final goal user3 can also read data1
In this case, if you use the casbin model file to achieve, how to write the file
(The way I can deal with now is to not define g2, and treat the user group as a user. Associate with the role in g, but in this way, the relationship between the user and the user group has to be handled in the program)

> @twgcode请在问题标题和文本中使用英语。

sorry my English is not good

**Comment by hsluoyz** [comment]
@twgcode plz use English in issue title and text.

**Comment by tangyang9464** [comment]
@twgcode
What is the difference between using g2 and not using g2, for solving user and user group?
I can't understand how you handle the relationship between the user and the user group in your program?

**Comment by tangyang9464** [comment]
@twgcode By the way,please edit your issue title in English

**Comment by twgcode** [comment]
> @twgcode By the way,please edit your issue title in English

The title has been updated

**Comment by twgcode** [comment]
> @twgcode
> What is the difference between using g2 and not using g2, for solving user and user group?
> I can't understand how you handle the relationship between the user and the user group in your program?

I didn't know much about caspin model before. After asking others yesterday,

I've learned that role inheritance / role hierarchy in caspin can be used to solve this problem.

https://casbin.org/docs/en/rbac#role-hierarchy

**Comment by tangyang9464** [comment]
@twgcode ok.But it's ``casbin`` not ``caspin`` :smile:
