### ISSUE TITLE
sync.map error

### ISSUE THREAD

**Issue by supriyapatil123** [casbin/casbin#85]
getting issue while getting casbin for sync.map

**Comment by hsluoyz** [comment]
Can you be more specific? Like the env, the code that causes the error?

**Comment by hsluoyz** [comment]
Please use latest Go 1.10

**Comment by supriyapatil123** [comment]
![image](https://user-images.githubusercontent.com/25053809/38419315-a0582a4c-39bd-11e8-9465-a1df7f74e72a.png)

**Comment by hsluoyz** [comment]
I have tested it under my Ubuntu 16.04 LTS x64 VM with Go 1.10.1. 

I have run the ``go get github.com/casbin/casbin-authz-plugin`` command and there's no error.

![image](https://user-images.githubusercontent.com/3787410/38451325-56d76d80-3a60-11e8-8ab8-e422f270439a.png)

From your screenshot, I saw some info about go 1.6.2. Have you fully uninstalled the old Go 1.6.2 version? Or update all the Go libraries?

**Comment by supriyapatil123** [comment]
Thanks

**Comment by supriyapatil123** [comment]
can you please help me in understanding how Casbin authenticated Docker works with the REST APIs?

**Comment by hsluoyz** [comment]
Did you follow the instructions in: https://github.com/casbin/casbin-authz-plugin ? And please raise an issue there.
