### ISSUE TITLE
[Question] What is the best model for policy Inheritance

### ISSUE THREAD

**Issue by nguyenpc** [casbin/casbin#850]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
We are trying to build an authorization system for an SaaS platform. On that platform, there will be hierarchy organizational structure which is looks like this

![image](https://user-images.githubusercontent.com/5871448/127047649-9a210dba-e105-4c27-814d-976aa747646b.png)
or can be this
![image](https://user-images.githubusercontent.com/5871448/127047692-76ab232e-01bc-44ec-90f9-47b22dc39e67.png)

The Admin of parent org can have the same policy on the children organization data.

I have tried to follow some examples in this  https://github.com/casbin/casbin/issues/99
But it seems having an issue regarding policy inheritance. There are so many unnecessary policy need to be created.
So do you guys have any suggestion for such business model?
Thank you so much.

**Comment by hsluoyz** [comment]
@closetool @tangyang9464

**Comment by closetool** [comment]
@nguyenpc Something like this?

model.conf
```
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub==p.sub && g(r.dom,p.dom) && r.obj == p.obj && r.act == p.act
```

policy.csv
```csv
p, user, domain1, something, read
p, admin, domain1, something, write
p, admin, domain1, something, read

g, domain2, domain1
g, domain3, domain1
g, domain4, domain2
```

requests and results
```
user, domain1, something, read
user, domain1, something, write
user, domain2, something, read
user, domain2, something, write
user, domain4, something, read
user, domain4, something, write

admin, domain1, something, read
admin, domain1, something, write
admin, domain2, something, read
admin, domain2, something, write
admin, domain4, something, read
admin, domain4, something, write
```
```
true
false
true
false
true
false
// ignore
true
true
true
true
true
true
```

**Comment by hsluoyz** [comment]
Closed as stale
