### ISSUE TITLE
Really confused about how to implement resource roles

### ISSUE THREAD

**Issue by stickystyle** [casbin/casbin#851]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

I've been trying to get this figured out for the last week, and I just cannot wrap my head around it - so I'm reaching out for any possible assistance that might be available.

My desire is to create roles that are assigned polices that, then assign users to those roles - basic RBAC. What is confusing me is how do I implement that while still using the keyMatch for wildcard object paths? When I check the implicit roles for the users, I can see that `sub://alice` gets `['group://103_OfficeWorker', 'policy://ShipmentPricing', 'policy://ShipmentRead']` and I'm pretty sure that is correct. However, when I check the implicit permissions for the users - I get nothing back.

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = priority, sub, obj, act, eft

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = priority(p.eft) || deny

[matchers]
m = g(r.sub, p.sub) && keyMatch(r.obj, p.obj)  && r.act == p.act
```

**Your policy:**

```
p, 2, policy://ShipmentPricing, Shipment/subtotalUSD, read, allow
p, 2, policy://ShipmentPricing, Shipment/totalUSD, read, allow

p, 5, policy://ShipmentRead, Shipment/subtotalUSD, read, deny
p, 5, policy://ShipmentRead, Shipment/totalUSD, read, deny
p, 10, policy://ShipmentRead, Query/getShipments, read, allow
p, 10, policy://ShipmentRead, Shipment/*, read, allow

g2, group://103_WarehouseWorker, policy://ShipmentRead

g2, group://103_OfficeWorker, policy://ShipmentRead
g2, group://103_OfficeWorker, policy://ShipmentPricing


g, sub://bob, group://103_WarehouseWorker

g, sub://alice, group://103_OfficeWorker
```

**Your request(s):**

```
sub://bob,   Shipment/subtotalUSD, read  -> false // expected: false
sub://bob,   Shipment/id,          read  -> false // expected:true
sub://bob,   Query/getShipments,   read  -> false // expected:true

sub://alice, Shipment/subtotalUSD, read  -> false // expected:true
sub://alice, Shipment/id,          read  -> false // expected:true
sub://alice, Query/getShipments,   read  -> false // expected:true
```

**Comment by stickystyle** [comment]
Changing my policy and conf file to remove `g2`, I am able to have my requests resolve with the expected results. 

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = priority, sub, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = priority(p.eft) || deny

[matchers]
m = g(r.sub, p.sub) && regexMatch(r.obj, p.obj)  && r.act == p.act
```

```
p, 20, policy://ShipmentPricing, ^Shipment/subtotalUSD, read, allow
p, 20, policy://ShipmentPricing, ^Shipment/totalUSD, read, allow

p, 40, policy://ShipmentRecord, ^Shipment/subtotalUSD, read, deny
p, 40, policy://ShipmentRecord, ^Shipment/totalUSD, read, deny
p, 50, policy://ShipmentRecord, ^Shipment/*, read, allow

g, group://103_WarehouseWorker, policy://ShipmentRecord

g, group://103_OfficeWorker, policy://ShipmentRecord
g, group://103_OfficeWorker, policy://ShipmentPricing

g, sub://bob, group://103_WarehouseWorker
g, sub://alice, group://103_OfficeWorker
```

**Comment by hsluoyz** [comment]
@closetool @tangyang9464

**Comment by closetool** [comment]
@hsluoyz @stickystyle It is a design limitation, https://github.com/casbin/casbin/blob/b6f62112061bd1b6b0163e4428423dac3cb4e092/rbac_api.go#L175, we could not determine which `gtype` was chosen.

**Comment by basimsahaf** [comment]
@hsluoyz are there any updates to this? How do I return the resource roles for a user?

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by hsluoyz** [comment]
@basimsahaf you'd better create a new issue for this, as this issue has been resolved 1 year ago.
