### ISSUE TITLE
[Question] Result is not matched to the editor in golang program when using RBAC with domain and pattern

### ISSUE THREAD

**Issue by ErikXu** [casbin/casbin#855]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
My golang code should be the same with the online editor, but they show different results.

**Your model:**

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && keyMatch(r.dom, p.dom) && r.obj == p.obj && keyMatch(r.act, p.act)
```

**Your policy:**

```
p, role||1, *, menu||1, *
p, role||2, *, menu||2, *
p, role||3, *, menu||3, *
p, role||4, *, menu||4, *
g, role||5, role||1, *
g, role||5, role||2, *
g, role||5, role||3, *
g, role||5, role||4, *

p, role||6, *, menu||5, *
p, role||7, *, menu||6, *
p, role||8, *, menu||7, *
p, role||9, *, menu||8, *
g, role||10, role||6, *
g, role||10, role||7, *
g, role||10, role||8, *
g, role||10, role||9, *

g, user||1, role||5, tenant||1
g, user||2, role||10, tenant||2
g, user||3, role||5, tenant||1
g, user||4, role||10, tenant||2
```

**Your request(s):**

```
user||1, tenant||1, menu||2, * ---> false (expected: true)
```

**Golang code:**

``` golang
package main

import (
	"fmt"

	"github.com/casbin/casbin/v2"
	defaultrolemanager "github.com/casbin/casbin/v2/rbac/default-role-manager"
	"github.com/casbin/casbin/v2/util"
)

func main() {
	e, err := casbin.NewEnforcer("./model.conf", "./policy.csv")
	if err != nil {
		fmt.Println(err)
	}

	//e.EnableLog(true)
	e.GetRoleManager().(*defaultrolemanager.RoleManager).AddDomainMatchingFunc("keyMatch", util.KeyMatch)

	ok, _ := e.Enforce("user||1", "tenant||1", "menu||2", "*")
	
        // output false here
        fmt.Println(ok)
}
```

**Editor result:**
![image](https://user-images.githubusercontent.com/6275608/128116604-7d364675-f480-43af-a5fe-e4471580062d.png)

**Comment by hsluoyz** [comment]
@closetool @tangyang9464

**Comment by ErikXu** [comment]
I had tried in another two languages, nodejs and dotnet. The results are different either. 

**dotnet code:**

``` csharp
 class Program
 {
     static void Main(string[] args)
     {
         var e = new Enforcer("model.conf", "policy.csv");
         var rm = new DefaultRoleManager(10);
         rm.AddDomainMatchingFunc((arg1, arg2) => BuiltInFunctions.KeyMatch(arg1, arg2));
         e.SetRoleManager(rm)
         Console.WriteLine($"Enforce: user||1, tenant||1, menu||2, *"); 
         var result = e.Enforce("user||1", "tenant||2", "menu||2", "*");
         Console.WriteLine($"Result:{result}")
         Console.WriteLine($"Enforce: user||1, tenant||2, menu||2, *");
         result = e.Enforce("user||1", "tenant||1", "menu||2", "*");
         Console.WriteLine($"Result:{result}");
     }
 }

// Output:
//Enforce: user||1, tenant||1, menu||2, *
//Result:True
//Enforce: user||1, tenant||2, menu||2, *
//Result:True --> Should be False
```

**nodejs code:**

``` node
import { newEnforcer, DefaultRoleManager, Util } from 'casbin'

async function main() {
        const enforcer = await newEnforcer('model.conf', 'policy.csv');
        const rm = enforcer.getRoleManager() as DefaultRoleManager;
        await rm.addDomainMatchingFunc(Util.keyMatchFunc);

        console.log('user||1, tenant||1, menu||2, *')
        const res1 = await enforcer.enforce('user||1', 'tenant||1', 'menu||2','*');
        console.log(res1);

        console.log('user||1, tenant||2, menu||2, *')
        const res2 = await enforcer.enforce('user||1', 'tenant||2', 'menu||2','*');
        console.log(res2);
        return "ok";
}

main().then(console.log).catch(console.error);

// Output
//user||1, tenant||1, menu||2, *
//true --> Correct
//user||1, tenant||2, menu||2, *
//false --> Correct
```

The problem might be due to the different handling or result for `GFunction`.

Nodejs will call [generateTempRoles](https://github.com/casbin/node-casbin/blob/master/src/rbac/defaultRoleManager.ts#L299) to generate temp roles for domain, while the other two don't.

**Comment by ErikXu** [comment]
Just for curious, the `GFunction` in golang seems to be called for more times than in dotnet.

**model:**

``` ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.obj == p.obj && keyMatch(r.act, p.act)
```

**policy:**

```
p, role||1, tenant||1, menu||1, *
p, role||2, tenant||1, menu||2, *
p, role||3, tenant||1, menu||3, *
p, role||4, tenant||1, menu||4, *
g, role||5, role||1, tenant||1
g, role||5, role||2, tenant||1
g, role||5, role||3, tenant||1
g, role||5, role||4, tenant||1

p, role||6, tenant||1, menu||5, *
p, role||7, tenant||1, menu||6, *
p, role||8, tenant||1, menu||7, *
p, role||9, tenant||1, menu||8, *
g, role||10, role||6, tenant||1
g, role||10, role||7, tenant||1
g, role||10, role||8, tenant||1
g, role||10, role||9, tenant||1

p, role||1, tenant||2, menu||1, *
p, role||2, tenant||2, menu||2, *
p, role||3, tenant||2, menu||3, *
p, role||4, tenant||2, menu||4, *
g, role||5, role||1, tenant||2
g, role||5, role||2, tenant||2
g, role||5, role||3, tenant||2
g, role||5, role||4, tenant||2

p, role||6, tenant||2, menu||5, *
p, role||7, tenant||2, menu||6, *
p, role||8, tenant||2, menu||7, *
p, role||9, tenant||2, menu||8, *
g, role||10, role||6, tenant||2
g, role||10, role||7, tenant||2
g, role||10, role||8, tenant||2
g, role||10, role||9, tenant||2

g, user||1, role||5, tenant||1
g, user||2, role||10, tenant||2
g, user||3, role||5, tenant||1
g, user||4, role||10, tenant||2
```

**golang:**

``` golang
package main

import (
	"fmt"

	"github.com/casbin/casbin/v2"
)

func main() {
	e, err := casbin.NewEnforcer("./model.conf", "./policy.csv")
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println("Enforce: user||1, tenant||1, menu||2, *")
	ok, _ := e.Enforce("user||1", "tenant||1", "menu||2", "*")
	fmt.Println("Result:", ok)

	fmt.Println("Enforce: user||1, tenant||2, menu||2, *")
	ok, _ = e.Enforce("user||1", "tenant||2", "menu||2", "*")
	fmt.Println("Result:", ok)
}
```

**golang output:**

```
Enforce: user||1, tenant||1, menu||2, *
GFunction: user||1 role||1 tenant||1 true
GFunction: user||1 role||2 tenant||1 true
GFunction: user||1 role||3 tenant||1 true
GFunction: user||1 role||4 tenant||1 true
GFunction: user||1 role||6 tenant||1 false
GFunction: user||1 role||7 tenant||1 false
GFunction: user||1 role||8 tenant||1 false
GFunction: user||1 role||9 tenant||1 false
Result: true
Enforce: user||1, tenant||2, menu||2, *
GFunction: user||1 role||1 tenant||2 false
GFunction: user||1 role||2 tenant||2 false
GFunction: user||1 role||3 tenant||2 false
GFunction: user||1 role||4 tenant||2 false
GFunction: user||1 role||6 tenant||2 false
GFunction: user||1 role||7 tenant||2 false
GFunction: user||1 role||8 tenant||2 false
GFunction: user||1 role||9 tenant||2 false
Result: false
```

**dotnet:**

``` csharp
class Program
{
    static void Main(string[] args)
    {
        var e = new Enforcer("model.conf", "policy.csv");

        Console.WriteLine($"Enforce: user||1, tenant||1, menu||2, *"); 
        var result = e.Enforce("user||1", "tenant||1", "menu||2", "*");
        Console.WriteLine($"Result:{result}");

        Console.WriteLine($"Enforce: user||1, tenant||2, menu||2, *");
        result = e.Enforce("user||1", "tenant||2", "menu||2", "*");
        Console.WriteLine($"Result:{result}");
    }
}
```

**dotnet output:**

```
Enforce: user||1, tenant||1, menu||2, *
GFunction: user||1, role||1, tenant||1, True
GFunction: user||1, role||2, tenant||1, True
Result:True
Enforce: user||1, tenant||2, menu||2, *
GFunction: user||1, role||1, tenant||2, False
GFunction: user||1, role||2, tenant||2, False
GFunction: user||1, role||3, tenant||2, False
GFunction: user||1, role||4, tenant||2, False
GFunction: user||1, role||6, tenant||2, False
GFunction: user||1, role||7, tenant||2, False
GFunction: user||1, role||8, tenant||2, False
GFunction: user||1, role||9, tenant||2, False
Result:False
```

**Comment by hsluoyz** [comment]
> Just for curious, the GFunction in golang seems to be called for more times than in dotnet.

@ErikXu can you put this in another issue? So they can be handled separately.

**Comment by tangyang9464** [comment]
@ErikXu I test the first example in online editor, but the result is false?
![image](https://user-images.githubusercontent.com/45587763/128200219-6bb813ef-28f8-4ec7-bdf4-030904db1178.png)

**Comment by ErikXu** [comment]
@tangyang9464 Did you set the `matchingDomainForGFunction` function as the highlight shows in the previous screenshot?

![image](https://user-images.githubusercontent.com/6275608/128116604-7d364675-f480-43af-a5fe-e4471580062d.png)

**Comment by ErikXu** [comment]
@hsluoyz ok, I will try to open another issue. But I think it's just an enhancement. 😃

**Comment by ErikXu** [comment]
@tangyang9464 As I mentioned before, I think we should implement the [generateTempRoles](https://github.com/casbin/node-casbin/blob/master/src/rbac/defaultRoleManager.ts#L299) for `GFunction` in golang. I am trying to do so, but the progress should be slower than yours, as the code and logic written in nodejs is a little difficult for me. 😃

> **nodejs code:**
> 
> ```js
> import { newEnforcer, DefaultRoleManager, Util } from 'casbin'
> 
> async function main() {
>         const enforcer = await newEnforcer('model.conf', 'policy.csv');
>         const rm = enforcer.getRoleManager() as DefaultRoleManager;
>         await rm.addDomainMatchingFunc(Util.keyMatchFunc);
> 
>         console.log('user||1, tenant||1, menu||2, *')
>         const res1 = await enforcer.enforce('user||1', 'tenant||1', 'menu||2','*');
>         console.log(res1);
> 
>         console.log('user||1, tenant||2, menu||2, *')
>         const res2 = await enforcer.enforce('user||1', 'tenant||2', 'menu||2','*');
>         console.log(res2);
>         return "ok";
> }
> 
> main().then(console.log).catch(console.error);
> 
> // Output
> //user||1, tenant||1, menu||2, *
> //true --> Correct
> //user||1, tenant||2, menu||2, *
> //false --> Correct
> ```
> 
> The problem might be due to the different handling or result for `GFunction`.
> 
> Nodejs will call [generateTempRoles](https://github.com/casbin/node-casbin/blob/master/src/rbac/defaultRoleManager.ts#L299) to generate temp roles for domain, while the other two don't.

**Comment by closetool** [comment]
@ErikXu I don't think it is needed, for there's cache in golang version. https://github.com/casbin/casbin/blob/b6f62112061bd1b6b0163e4428423dac3cb4e092/util/builtin_operators.go#L311

**Comment by sagilio** [comment]
We use `generateTempRoles` on the old version. 

Casbin.NET remove it at the PR: https://github.com/casbin/Casbin.NET/pull/160,it about this issue https://github.com/casbin/Casbin.NET/issues/156

Casbin (golang) remove it at this PR https://github.com/casbin/casbin/pull/702, about issue is https://github.com/casbin/casbin/issues/701

**Comment by sagilio** [comment]
> @ErikXu I don't think it is needed, for there's cache in golang version.
> 
> https://github.com/casbin/casbin/blob/b6f62112061bd1b6b0163e4428423dac3cb4e092/util/builtin_operators.go#L311

Casbin.NET has this cache too, Is this the reason?

**Comment by tangyang9464** [comment]
> @ErikXu I don't think it is needed, for there's cache in golang version.
> 
> https://github.com/casbin/casbin/blob/b6f62112061bd1b6b0163e4428423dac3cb4e092/util/builtin_operators.go#L311

@closetool I think the `` generateTempRoles`` method is not for cache, isn't right?

**Comment by closetool** [comment]
@sagilio @tangyang9464 
Unluckily, test in casbin-go, result is `false, false`, so we should fix that.

I don't think it's cache's fault, perhaps reason is the role inheritance.

**Comment by tangyang9464** [comment]
> @sagilio @tangyang9464
> Unluckily, test in casbin-go, result is `false, false`, so we should fix that.
> 
> I don't think it's cache's fault, perhaps reason is the role inheritance.

@closetool I think reason is the role inheritance,too. I found the ``default-role-manager`` has logic error.

**Comment by closetool** [comment]
@sagilio @tangyang9464 Sorry, but I guess we forgot something, we should call `BuildRoleLinks` after adding domain match function. Could you @sagilio help me test .net version?

After that, the output is `true, true`
