### ISSUE TITLE
[Feature]Add the Casbin SVG icon to Font Awesome

### ISSUE THREAD

**Issue by ffyuanda** [casbin/casbin#856]
**Is your feature request related to a problem? Please describe.**
Yes. I need a Font Awesomeicon for Casbin to use in third-party website.

**Describe the solution you'd like**
Upload the icon (make a PR) to Font Awesome.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ffyuanda** [comment]
@hsluoyz can add the icon to use in Odoo development (would be better if we have one)

**Comment by hsluoyz** [comment]
@ffyuanda see:

1. https://github.com/casbin/static , the static resource lib, including images
2. https://door.casbin.com/applications , some images in use

**Comment by ffyuanda** [comment]
@hsluoyz yeah but if we can add it to Font Awesome that would be better

**Comment by hsluoyz** [comment]
@ffyuanda you can add our icons to Font Awesome as another copy. But we will still use casbin/static.
