### ISSUE TITLE
[Question]The GFunction in golang seems to be called for more times than in dotnet (C#).

### ISSUE THREAD

**Issue by ErikXu** [casbin/casbin#857]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
`GFunction` in golang seems to be called for more times than in dotnet (C#), The calling times might be the same.

**Your model:**

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.obj == p.obj && keyMatch(r.act, p.act)
```

**Your policy:**

``` 
p, role||1, tenant||1, menu||1, *
p, role||2, tenant||1, menu||2, *
p, role||3, tenant||1, menu||3, *
p, role||4, tenant||1, menu||4, *
g, role||5, role||1, tenant||1
g, role||5, role||2, tenant||1
g, role||5, role||3, tenant||1
g, role||5, role||4, tenant||1

p, role||6, tenant||1, menu||5, *
p, role||7, tenant||1, menu||6, *
p, role||8, tenant||1, menu||7, *
p, role||9, tenant||1, menu||8, *
g, role||10, role||6, tenant||1
g, role||10, role||7, tenant||1
g, role||10, role||8, tenant||1
g, role||10, role||9, tenant||1

p, role||1, tenant||2, menu||1, *
p, role||2, tenant||2, menu||2, *
p, role||3, tenant||2, menu||3, *
p, role||4, tenant||2, menu||4, *
g, role||5, role||1, tenant||2
g, role||5, role||2, tenant||2
g, role||5, role||3, tenant||2
g, role||5, role||4, tenant||2

p, role||6, tenant||2, menu||5, *
p, role||7, tenant||2, menu||6, *
p, role||8, tenant||2, menu||7, *
p, role||9, tenant||2, menu||8, *
g, role||10, role||6, tenant||2
g, role||10, role||7, tenant||2
g, role||10, role||8, tenant||2
g, role||10, role||9, tenant||2

g, user||1, role||5, tenant||1
g, user||2, role||10, tenant||2
g, user||3, role||5, tenant||1
g, user||4, role||10, tenant||2
```

**Your request(s):**

```
The calling times might be the same.
```

**golang:**

Here is my code, and I added [this](https://github.com/ErikXu/casbin/commit/29fdfd106fabea83cac5c6d920e260a96c61ca52?branch=29fdfd106fabea83cac5c6d920e260a96c61ca52&diff=split) to trace the calling times.

``` golang
package main

import (
	"fmt"

	"github.com/casbin/casbin/v2"
)

func main() {
	e, err := casbin.NewEnforcer("./model.conf", "./policy.csv")
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println("Enforce: user||1, tenant||1, menu||2, *")
	ok, _ := e.Enforce("user||1", "tenant||1", "menu||2", "*")
	fmt.Println("Result:", ok)

	fmt.Println("Enforce: user||1, tenant||2, menu||2, *")
	ok, _ = e.Enforce("user||1", "tenant||2", "menu||2", "*")
	fmt.Println("Result:", ok)
}
```

**golang output:**

``` shell
Enforce: user||1, tenant||1, menu||2, *
GFunction: user||1 role||1 tenant||1 true
GFunction: user||1 role||2 tenant||1 true
GFunction: user||1 role||3 tenant||1 true
GFunction: user||1 role||4 tenant||1 true
GFunction: user||1 role||6 tenant||1 false
GFunction: user||1 role||7 tenant||1 false
GFunction: user||1 role||8 tenant||1 false
GFunction: user||1 role||9 tenant||1 false
Result: true
Enforce: user||1, tenant||2, menu||2, *
GFunction: user||1 role||1 tenant||2 false
GFunction: user||1 role||2 tenant||2 false
GFunction: user||1 role||3 tenant||2 false
GFunction: user||1 role||4 tenant||2 false
GFunction: user||1 role||6 tenant||2 false
GFunction: user||1 role||7 tenant||2 false
GFunction: user||1 role||8 tenant||2 false
GFunction: user||1 role||9 tenant||2 false
Result: false
```

**dotnet:**

Here is my code, and I added [this](https://github.com/ErikXu/Casbin.NET/commit/5374debc603369c081ccada7e3f81f49045460cb#diff-649a76a7c7473220ad07236b50ff1b8c53039df0c9480f4d8b68f9b17951d2ac) to trace the calling times.

``` csharp
class Program
{
    static void Main(string[] args)
    {
        var e = new Enforcer("model.conf", "policy.csv");

        Console.WriteLine($"Enforce: user||1, tenant||1, menu||2, *"); 
        var result = e.Enforce("user||1", "tenant||1", "menu||2", "*");
        Console.WriteLine($"Result: {result}");

        Console.WriteLine($"Enforce: user||1, tenant||2, menu||2, *");
        result = e.Enforce("user||1", "tenant||2", "menu||2", "*");
        Console.WriteLine($"Result: {result}");
    }
}
```

**dotnet output:**

``` shell
Enforce: user||1, tenant||1, menu||2, *
GFunction: user||1, role||1, tenant||1, True
GFunction: user||1, role||2, tenant||1, True
Result: True
Enforce: user||1, tenant||2, menu||2, *
GFunction: user||1, role||1, tenant||2, False
GFunction: user||1, role||2, tenant||2, False
GFunction: user||1, role||3, tenant||2, False
GFunction: user||1, role||4, tenant||2, False
GFunction: user||1, role||6, tenant||2, False
GFunction: user||1, role||7, tenant||2, False
GFunction: user||1, role||8, tenant||2, False
GFunction: user||1, role||9, tenant||2, False
Result: False
```

**Comment by hsluoyz** [comment]
@closetool @tangyang9464

**Comment by closetool** [comment]
@ErikXu I wonder what's the output after GFunction? Can I have your code?

**Comment by ErikXu** [comment]
@closetool I pasted my code when openning the issue, please check.

> **golang:**
> 
> Here is my code, and I added [this](https://github.com/ErikXu/casbin/commit/29fdfd106fabea83cac5c6d920e260a96c61ca52?branch=29fdfd106fabea83cac5c6d920e260a96c61ca52&diff=split) to trace the calling times.
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 
> 	"github.com/casbin/casbin/v2"
> )
> 
> func main() {
> 	e, err := casbin.NewEnforcer("./model.conf", "./policy.csv")
> 	if err != nil {
> 		fmt.Println(err)
> 	}
> 
> 	fmt.Println("Enforce: user||1, tenant||1, menu||2, *")
> 	ok, _ := e.Enforce("user||1", "tenant||1", "menu||2", "*")
> 	fmt.Println("Result:", ok)
> 
> 	fmt.Println("Enforce: user||1, tenant||2, menu||2, *")
> 	ok, _ = e.Enforce("user||1", "tenant||2", "menu||2", "*")
> 	fmt.Println("Result:", ok)
> }
> ```
> 
> **golang output:**
> 
> ```shell
> Enforce: user||1, tenant||1, menu||2, *
> GFunction: user||1 role||1 tenant||1 true
> GFunction: user||1 role||2 tenant||1 true
> GFunction: user||1 role||3 tenant||1 true
> GFunction: user||1 role||4 tenant||1 true
> GFunction: user||1 role||6 tenant||1 false
> GFunction: user||1 role||7 tenant||1 false
> GFunction: user||1 role||8 tenant||1 false
> GFunction: user||1 role||9 tenant||1 false
> Result: true
> Enforce: user||1, tenant||2, menu||2, *
> GFunction: user||1 role||1 tenant||2 false
> GFunction: user||1 role||2 tenant||2 false
> GFunction: user||1 role||3 tenant||2 false
> GFunction: user||1 role||4 tenant||2 false
> GFunction: user||1 role||6 tenant||2 false
> GFunction: user||1 role||7 tenant||2 false
> GFunction: user||1 role||8 tenant||2 false
> GFunction: user||1 role||9 tenant||2 false
> Result: false
> ```
> 
> **dotnet:**
> 
> Here is my code, and I added [this](https://github.com/ErikXu/Casbin.NET/commit/5374debc603369c081ccada7e3f81f49045460cb#diff-649a76a7c7473220ad07236b50ff1b8c53039df0c9480f4d8b68f9b17951d2ac) to trace the calling times.
> 
> ```cs
> class Program
> {
>     static void Main(string[] args)
>     {
>         var e = new Enforcer("model.conf", "policy.csv");
> 
>         Console.WriteLine($"Enforce: user||1, tenant||1, menu||2, *"); 
>         var result = e.Enforce("user||1", "tenant||1", "menu||2", "*");
>         Console.WriteLine($"Result: {result}");
> 
>         Console.WriteLine($"Enforce: user||1, tenant||2, menu||2, *");
>         result = e.Enforce("user||1", "tenant||2", "menu||2", "*");
>         Console.WriteLine($"Result: {result}");
>     }
> }
> ```
> 
> **dotnet output:**
> 
> ```shell
> Enforce: user||1, tenant||1, menu||2, *
> GFunction: user||1, role||1, tenant||1, True
> GFunction: user||1, role||2, tenant||1, True
> Result: True
> Enforce: user||1, tenant||2, menu||2, *
> GFunction: user||1, role||1, tenant||2, False
> GFunction: user||1, role||2, tenant||2, False
> GFunction: user||1, role||3, tenant||2, False
> GFunction: user||1, role||4, tenant||2, False
> GFunction: user||1, role||6, tenant||2, False
> GFunction: user||1, role||7, tenant||2, False
> GFunction: user||1, role||8, tenant||2, False
> GFunction: user||1, role||9, tenant||2, False
> Result: False
> ```

**Comment by closetool** [comment]
Sure, but I need to know what are these 
```
GFunction: user||1 role||1 tenant||1 true
GFunction: user||1 role||2 tenant||1 true
GFunction: user||1 role||3 tenant||1 true
GFunction: user||1 role||4 tenant||1 true
GFunction: user||1 role||6 tenant||1 false
GFunction: user||1 role||7 tenant||1 false
GFunction: user||1 role||8 tenant||1 false
GFunction: user||1 role||9 tenant||1 false
``

**Comment by ErikXu** [comment]
@closetool These are the tracing logs of `GFunction`. I added some codes to the source code of casbin. Please refer:

**golang:** [here](https://github.com/ErikXu/casbin/commit/29fdfd106fabea83cac5c6d920e260a96c61ca52?branch=29fdfd106fabea83cac5c6d920e260a96c61ca52&diff=unified)

![image](https://user-images.githubusercontent.com/6275608/128356719-f09a70da-4c42-460e-bbab-d805b9d8de66.png)

**dotnet:** [here](https://github.com/ErikXu/Casbin.NET/commit/5374debc603369c081ccada7e3f81f49045460cb?branch=5374debc603369c081ccada7e3f81f49045460cb&diff=unified)

![image](https://user-images.githubusercontent.com/6275608/128356987-74d543c5-36fb-483a-af85-0892b6e79935.png)

**Comment by sagilio** [comment]
The Casbin.NET RBAC data structure is a little different with golang casbin, and IChainEffector will support short-circuit better.
I think this case is the cause of IChainEffector, it will less call calculate expression when the effect is `e = some(where (p.eft == allow))`.

**Comment by ErikXu** [comment]
@sagilio Thanks for your explanation. It's reasonable!
