### ISSUE TITLE
[Question] Can the cache reload mechanism be optimized?

### ISSUE THREAD

**Issue by langzhiwu** [casbin/casbin#861]
please to optimize,go to the db to load data when updating the local cache, and then overwrite the local cache to make it seamless. Instead of clearing the local cache first and then loading the data

![image](https://user-images.githubusercontent.com/13376941/129033167-21c76159-68e7-4f1a-a193-754dc02788b4.png)

**Comment by hsluoyz** [comment]
@closetool @tangyang9464

**Comment by closetool** [comment]
@langzhiwu Sorry, I don't get what you say. Could you use google translate https://translate.google.com/
