### ISSUE TITLE
[Discussion] Use [] grammar for `in` operator in matcher.

### ISSUE THREAD

**Issue by Zxilly** [casbin/casbin#863]
From: https://github.com/casbin/casbin-editor/issues/60

As https://casbin.org/docs/en/syntax-for-models#special-grammer says, casbin now supports `in` operator.
As for now, we have same explanation on `in` itself: It means checking whether a word exists in array.
But, we didn't have standard on how to define a array in matcher.
In GoLang, it is https://github.com/casbin/casbin/blob/277c1a2b85698272f764d71a94d2595a8d425915/examples/rbac_model_matcher_using_in_op.conf#L14
But in node-casbin, we should define it with `['data2', 'data3']`.
I think the latter usually seems to make more sense.

@hsluoyz @closetool @nodece @Edmond-J-A

**Comment by hsluoyz** [comment]
@Zxilly Golang Casbin already uses `r.obj in ('data2', 'data3')` for long time and we cannot break the API. It should be node-casbin to follow the Go way. Or at least support both for node-casbin.

**Comment by Zxilly** [comment]
@hsluoyz Maybe we can keep `()` as an compatibility solution, but turn to `[]` internal.
This will also be helpful for other language implementation.

**Comment by closetool** [comment]
@hsluoyz Such as replacing "[]" with "()" in matcher?

**Comment by hsluoyz** [comment]
@closetool yes, maybe it works

**Comment by sagilio** [comment]
> @hsluoyz Maybe we can keep `()` as an compatibility solution, but turn to `[]` internal.
> This will also be helpful for other language implementation.

It is helpful for .NET to implement the full `in` feature.
