### ISSUE TITLE
[Question] How to associate the user table with the role table

### ISSUE THREAD

**Issue by feeman89** [casbin/casbin#865]
How to associate the user table with the role table

**Comment by hsluoyz** [comment]
@closetool @tangyang9464

**Comment by tangyang9464** [comment]
@feeman89 Can you give more information and describe your needs in detail ？

**Comment by hsluoyz** [comment]
@feeman89 Casbin has only one table, this table maintains the user-role mapping and the role-permission mapping. If you have another user entity table or role entity table. You need to make sure you use the user ID and the role ID in Casbin table.
