### ISSUE TITLE
[Question] Policy Group

### ISSUE THREAD

**Issue by itgelo** [casbin/casbin#867]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Is there a config or a way to use multi-policy like methods?

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && regexMatch(r.act, p.act)
```

**Your policy:**

```
p, alice1, /alice_data, (GET)|(POST), allow
p, alice2, /alice_data/:id, (GET)|(PUT)|(DELETE), allow
p, bob1, /bob_data, (GET)|(POST), allow
p, bob2, /bob_data/:id, (GET)|(PUT)|(DELETE), allow

g, alice, (alice1)|(alice2)
g, other, bob1
```

**Your request(s):**

```
alice, /alice_data, GET ---> false (expected: true)
other, /bob_data, POST ---> true (ok)
```

**Comment by tangyang9464** [comment]
@itgelo If you want to user ``g`` with pattern, you should use it like below
```
[matchers]
m = g(r.sub, p.sub) && regexMatch(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && regexMatch(r.act, p.act)
```
```
e, _ := casbin.NewEnforcer("main/model.conf", "main/policy.csv")
e.AddNamedMatchingFunc("g","",util.RegexMatch)
err := e.BuildRoleLinks()
if err != nil {
return 
}
flag,_ := e.Enforce("other", "/bob_data", "POSTS")
fmt.Println(flag)
``` 
``e.AddNamedMatchingFunc`` and ``e.BuildRoleLinks()`` are important

**Comment by itgelo** [comment]
@tangyang9464 I have added `e.AddNamedMatchingFunc` and `e.BuildRoleLinks()` also model `[matchers]`. but still not working.

have you tried with a request like this with the policy I shared in question?
`alice, /alice_data, GET ---> false (expected: true)`

or can you share in casbin editor

**Comment by tangyang9464** [comment]
@itgelo What is the version of the Go-casbin you are using? I test your case is true. The version is [v2.36.1](https://github.com/casbin/casbin/releases/tag/v2.36.1)

**Comment by itgelo** [comment]
@tangyang9464 I'm using version `v2.28.3`

have you tried a request like this?
`alice, /alice_data, GET ---> false (expected: true)`

with policy:
`g, alice, (alice1)|(alice2)`

**Comment by tangyang9464** [comment]
@itgelo Yes, I have tried it. Because there have been some big changes to this part of the function recently. You can test it with the latest version first.

**Comment by tangyang9464** [comment]
> @tangyang9464 I'm using version `v2.28.3`
> in your casbin editor return `false` expected `true`

casbin editor depends on node-casbin, not go-casbin. There are some differences

**Comment by itgelo** [comment]
@tangyang9464 Ok, I will try to upgrade first. thanks btw

**Comment by itgelo** [comment]
> @itgelo If you want to user `g` with pattern, you should use it like below
> 
> ```
> [matchers]
> m = g(r.sub, p.sub) && regexMatch(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && regexMatch(r.act, p.act)
> ```
> 
> ```
> e, _ := casbin.NewEnforcer("main/model.conf", "main/policy.csv")
> e.AddNamedMatchingFunc("g","",util.RegexMatch)
> err := e.BuildRoleLinks()
> if err != nil {
> return 
> }
> flag,_ := e.Enforce("other", "/bob_data", "POSTS")
> fmt.Println(flag)
> ```
> 
> `e.AddNamedMatchingFunc` and `e.BuildRoleLinks()` are important

@tangyang9464 error `domain should be 1 parameter`, v2.36.1

**Comment by tangyang9464** [comment]
@itgelo What is your code？

**Comment by itgelo** [comment]
@tangyang9464 just upgrade to v2.36.1 try to run without any changes

**Comment by tangyang9464** [comment]
@itgelo I’m a little confused. Your model and policy have not changed. Can you try to debug it? I can’t reproduce it.

**Comment by itgelo** [comment]
@tangyang9464 usually after upgrade version is there any other config?
Or should it be running normally?
how to debug it? I just got error message `error: domain should be 1 parameter`

**Comment by tangyang9464** [comment]
Can I have your code? My code is 
```
e, _ := casbin.NewEnforcer("main/model.conf", "main/policy.csv")
e.AddNamedMatchingFunc("g","",util.RegexMatch)
err := e.BuildRoleLinks()
if err != nil {
return
}
flag,_ := e.Enforce("alice", "/alice_data", "GET")
fmt.Println(flag)
```

**Comment by itgelo** [comment]
> Println

@tangyang9464 always error with or without `e.AddNamedMatchingFunc` and `e.BuildRoleLinks()`
```
enforcer, err := casbin.NewEnforcer("./casbin_model.conf", adapter)
// enforcer.AddNamedMatchingFunc("g", "", util.RegexMatch)
// err = enforcer.BuildRoleLinks()

if err != nil {
	log.Fatalf("Error: %s", err)
	return
}

flag, _ := enforcer.Enforce("alice", "/alice_data", "GET")
log.Println(flag)
```

**Comment by itgelo** [comment]
@tangyang9464 have you tried with an adapter?

**Comment by tangyang9464** [comment]
> @tangyang9464 have you tried with an adapter?

not yet

**Comment by itgelo** [comment]
@tangyang9464 I think it's an error if using an adapter.
`adapter, err := gormadapter.NewAdapterByDB(dbSilent)` [v3](https://github.com/casbin/gorm-adapter/tree/v3.3.3)

**Comment by tangyang9464** [comment]
> @tangyang9464 I think it's an error if using an adapter.
> `adapter, err := gormadapter.NewAdapterByDB(dbSilent)` [v3](https://github.com/casbin/gorm-adapter/tree/v3.3.3)

What does your database data look like

**Comment by itgelo** [comment]
> What does your database data look like

Postgre
![image](https://user-images.githubusercontent.com/15007559/129866430-75e1d4bb-7aa2-4ebc-a410-883ebe6a432a.png)

**Comment by tangyang9464** [comment]
@itgelo Why does your ``g`` still have ``allow``? This should be the mistake.

**Comment by itgelo** [comment]
> @itgelo Why does your `g` still have `allow`? This should be the mistake.

@tangyang9464 I deleted it, got the same error. `error: domain should be 1 parameter`

**Comment by tangyang9464** [comment]
@itgelo Can you export your sql data? I think there may be a problem with your data

**Comment by hsluoyz** [comment]
Closed as stale
