### ISSUE TITLE
[Bug] checking permission takes almost 10 seconds, it is so slow

### ISSUE THREAD

**Issue by douxuefeng** [casbin/casbin#869]
my code is below:

```go
	userId := ctx.Values().GetString(viper.GetString("jwtUser"))
	now := time.Now()
	fmt.Println(now)
	CasbinEft.LoadPolicy()
	ok, _ := CasbinEft.Enforce(userId, ctx.Path(), ctx.Method())
	fmt.Println(time.Since(now).Seconds())
```

when i use it, it takes almost 10 seconds, like below:
```
Now listening on: http://localhost:8081
Application started. Press CTRL+C to shut down.
2021-08-20 10:32:08.0962854 +0800 CST m=+10.781512801
8.804166200000001
```

**Comment by sagilio** [comment]
If you enable the `AutoSave` option, it is unnecessary to call `LoadPolicy` every time.

**Comment by hsluoyz** [comment]
@douxuefeng how many rules do you have? Do you have a bad network connection speed?

**Comment by douxuefeng** [comment]
thx for reply. i use it in my local network connection. and about 205 rules

**Comment by douxuefeng** [comment]
> If you enable the `AutoSave` option, it is unnecessary to call `LoadPolicy` every time.

thx i will try

**Comment by hsluoyz** [comment]
> thx for reply. i use it in my local network connection. and about 205 rules

this is impossble. Based on our benchmark: https://casbin.org/docs/en/benchmark , 1100 rules only cost 0.16ms. There must be something wrong. Can you share the reproducable code?

**Comment by douxuefeng** [comment]
> > thx for reply. i use it in my local network connection. and about 205 rules
> 
> @douxuefeng this is impossble. Based on our benchmark: https://casbin.org/docs/en/benchmark , 1100 rules only cost 0.16ms. There must be something wrong. Can you share the reproducable code?

yeah, i see . i have tried many times these days, i use it in my middleware, and record how long it takes .  it runs faster, about 300 mileseconds. i guess maybe it is caused by higher io and less memery , becouse i run many tasks in my local computer

**Comment by hsluoyz** [comment]
@douxuefeng good. Then I think you can try the solution here: https://github.com/casbin/casbin/issues/869#issuecomment-902400000
