### ISSUE TITLE
can we use multiple policy files like basic and rbac in /usr/lib/docker/examples ?

### ISSUE THREAD

**Issue by supriyapatil123** [casbin/casbin#87]

**Comment by hsluoyz** [comment]
Yes, just replace the files in: https://github.com/casbin/casbin-authz-plugin/tree/master/examples with your own.

**Comment by supriyapatil123** [comment]
made changes in make file and replaced files in example folder.But it gives error while running ./casbin-authz-plugin

**Comment by supriyapatil123** [comment]
User we are considering is docker user or system user?

**Comment by hsluoyz** [comment]
As the [Docker documentation](https://docs.docker.com/engine/extend/plugins_authorization/#default-user-authorization-mechanism) said:

```
If TLS is enabled in the Docker daemon, the default user authorization flow extracts the user details from the certificate subject name. That is, the User field is set to the client certificate subject common name, and the AuthenticationMethod field is set to TLS.
```

If TLS is not enabled, I guess there's no user then.

For object, you may see the example in the README: ``/v1.27/images/json, GET``. You can print out the object path by testing the call. Then you will get all the objects.
