### ISSUE TITLE
Is there a way to use RBAC with multiple domains?

### ISSUE THREAD

**Issue by resingm** [casbin/casbin#871]
**What's your scenario? What do you want to achieve?**

Is there a way to define not one but multiple domains for the RBAC with domains model?
I managed to use either a wildcard or a single domain, but I did not manage to get a multi-domain model set up properly.

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g(r.sub, p.sub, "*") && r.obj == p.obj && r.act == p.act) \
  || (g(r.sub, p.sub, r.dom) && r.obj == p.obj && r.act == p.act)
```

```
p, alice, data1, read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write

g, alice, data2_admin

p, super, entity, create
p, super, entity, read
p, super, entity, update
p, super, entity, delete

g, user_wildcard, data, *
g, user_tenant_1, data, 6ec54488-05ac-11ec-8671-9cb6d0dc265f
g, user_tenant_2, data, 7b5aa454-05ac-11ec-8671-9cb6d0dc265f
g, user_both_tenants, data, 6ec54488-05ac-11ec-8671-9cb6d0dc265f
g, user_both_tenants, data, 7b5aa454-05ac-11ec-8671-9cb6d0dc265f

```

`user_wildcard` is allowed to access all domains. `user_tenant_1` and `user_tenant_2` can access their corresponding tenant. But `user_both_tenants` is not allowed for both tenants.

I assume I have to change my model, instead of my policy?

Thanks for an answer.

**Comment by tangyang9464** [comment]
@resingm I don’t quite understand what you mean, can you point out what your request does not meet expectations

**Comment by resingm** [comment]
Yes of course.

So, I try to assign a user to multiple domains. In my system, a tenant is defined as a domain.

Let's assume, there exist three domains `domain_a', `domain_b` and `domain_c`. The user is defined as `sub`, the role is defined as `obj`.

With the regular RBAC model with domains, I can assign a user to just a single domain, e.g. with the record:

```
g, sub, obj, domain_a
```

I extended the RBAC with a wildcard operator as it can be seen in the model definition in the issue:

```
[matchers]
m = (g(r.sub, p.sub, "*") && r.obj == p.obj && r.act == p.act) \
  || (g(r.sub, p.sub, r.dom) && r.obj == p.obj && r.act == p.act)
```

Now, I have the chance to use `*` to assign a user to all domains as follows:

```
g, sub, obj, *
```

This works just fine. I can use the user `sub` to ensure the casbin enforcer let a request pass, no matter whether I check for `domain_a`, `domain_b` or `domain_c`. However, how could I define that a user belongs to a specific selection of domains?
e.g. `domain_a` and `domain_c`, but restrict access to `domain_b`?

AFAIK, the documentation does not cover this case, and also the casbin enforcer (pycasbin) does not support to have an user (`sub`) assigned to multiple domains.

Is the problem clear?

**Comment by tangyang9464** [comment]
@resingm ``m = (g(r.sub, p.sub, "*")`` is wrong. The pattern just be used in policy such as ``g, alice, admin, *``. And you can modify your model and policy, cite your request such as ``r, alice, data1, read --->true (expect false)`` to let me konw what effect you want to achieve or meet what kind of scene.

**Comment by resingm** [comment]
Sorry, saw this issue is still open. Closed
