### ISSUE TITLE
How can I implement hierarchical RBAC

### ISSUE THREAD

**Issue by aravindakumarbootlabs** [casbin/casbin#879]
**What's your scenario? What do you want to achieve?**
I have two domains **organization** and **project**

organization object looks like organization/org1
project object looks like organization/org1/project/proj1

organization has one action read
project has one action read

organization has one role ORG_OWNER which can do read
project has one role PROJ_OWNER which can do read

If I assign ORG_OWNER to user1 for object organization/org1, I need PROJ_OWNER also to be assigned to user1 for organization/org1/project/*

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.obj) && r.act == p.act

```

**Your policy:**

```
p, ORG_OWNER, organization/{org}, read
p, PROJECT_OWNER, organization/{org}/project/{project}, read
g, user1, ORG_OWNER, organization/org1
g, user1, PROJECT_OWNER, organization/org1/project/proj1
```

**Your request(s):**

```
user1, organization/sailor, read
user1, organization/sailor/project/test, read
```

How to do ORG_OWNER -> PROJ_OWNER mapping, is it possible?

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
@aravindakumarbootlabs I don't understand the meaning of ``ORG_OWNER -> PROJ_OWNER mapping``. And is ``organization/{org}`` a pattern matching? Plz cite the request you want to fulfill such as ``user1, organization/sailor, read  -->true (expect false)``

**Comment by aravindakumarbootlabs** [comment]
Sorry, I found the domainmatching functions, that solved my problem thanks
