### ISSUE TITLE
[Question] What's the best way to limit/filter roles by resource? ABAC?

### ISSUE THREAD

**Issue by awmcclain** [casbin/casbin#881]
**What's your scenario? What do you want to achieve?**
I've read through all the docs and I'm having a hard time conceptualizing how to set up roles that are filtered based on a resource ID -- for example, a user creates a room and becomes a "host" of the room -- but _only_ the room that user has created. The concept of "host" is only really a role in the context that it's a relationship between a User and a Room -- it doesn't apply to all Rooms. I'm muddled between using keymatch, ABAC, and how everything interacts with the Enforcer() and my database.

Say I have these API endpoints:
```
POST /rooms
GET /rooms/:id
POST /rooms/:id/open
POST /rooms/:id/close
```

and say i have two "roles" that are specific to a room
```
host      # user-room relationship
attendee  # user-room relationship
``` 

For the purposes of the example, I want to express these access rules:

* A user can POST to `/rooms` to create a new room and become the host of that room
* A host can POST to `/rooms/:id/open` and `/rooms/:id/closed`, **but only for the specific rooms they are the host for**
* An attendee can GET `/rooms/:id`, **but only for the specific rooms they are attendees for**

Assume for this example that user `alice` is a host of rooms 1 and 2, and `bob` is an attendee of room 2.

From what I've read, I don't think I should create a separate policy for each resource, e.g.
```
p, alice, /rooms/1, POST
p, alice, /rooms/1/open, POST
p, alice, /rooms/1/close, POST   
p, alice, /rooms/2, POST
p, alice, /rooms/2/open, POST
p, alice, /rooms/2/close, POST
p, bob, /rooms/2, GET
```

So, would I express the fact that alice is a host for rooms 1 & 2 using a db-stored policy somehow? 
```
p, host, /rooms/:id/open, POST
p, host, /rooms/:id/close, POST
p, attendee, /rooms/:id, GET

g, alice, host, /rooms/1  # <-- somehow express that alice is the host of room with id 1, not all rooms
g, alice, host, /rooms/2
g, bob, attendee, /rooms/2
```

Or would I try and match up the ID in the policy (I think i'm not understanding this)?
```
p, r.sub.id == r.obj.id, /rooms/:id/open, POST 
p, r.sub.id == r.obj.id, /rooms/:id/close, POST
```

Or would I use a custom function in my policy somehow and express the host relationship as a lookup on a join table between User and Room?
```
p, isHost(userID, roomID), /rooms/:id/open, POST
p, isHost(userID, roomID), /rooms/:id/close, POST
```

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
@awmcclain How about this https://casbin.org/casbin-editor/#HEQFW7ZLJ

**Comment by Josheasy111** [comment]
Hi anyone I'm new here can i talk to anyone?

**Comment by tangyang9464** [comment]
> Hi anyone I'm new here can i talk to anyone?

what do you mean?

**Comment by Josheasy111** [comment]
> > Hi anyone I'm new here can i talk to anyone?
> 
> what do you mean?

Kinda wanna know what this are all about

**Comment by Josheasy111** [comment]
Hey

**Comment by tangyang9464** [comment]
> > > Hi anyone I'm new here can i talk to anyone?
> > 
> > 
> > what do you mean?
> 
> Kinda wanna know what this are all about

What do you want to ask? What is your question? Please describe in detail, I am confused.

**Comment by Josheasy111** [comment]
Are you into programming or hacking
