### ISSUE TITLE
Discrepancy in response from editor and golang sdk

### ISSUE THREAD

**Issue by aravindakumarbootlabs** [casbin/casbin#885]
**Describe the bug**
The policy and evaluation done on editor is working as intended, but with the same policy and evaluation in golang is not working properly

**To Reproduce**
1. Tried running the following go code
```go
package main

import (
	"fmt"
	"github.com/casbin/casbin/v2"
	defaultrolemanager "github.com/casbin/casbin/v2/rbac/default-role-manager"
	"github.com/casbin/casbin/v2/util"
)

func main() {
	e, err := casbin.NewEnforcer("rbac/model.conf", "rbac/policies.csv")
	if err != nil {
		panic(err)
	}

	r := e.GetRoleManager()
	r.(*defaultrolemanager.RoleManager).AddDomainMatchingFunc("KeyMatch4", util.KeyMatch4)

	t, _:= e.Enforce("user1", "organizations/org1", "read")
	fmt.Println(t)
}
```

rbac/model.conf:
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.obj) && r.act == p.act
```

rbac/policies.csv
```
p, org_owner, write
p, org_reader, read

g, org_owner, org_reader, organizations/{org}

g, user1, org_owner, organizations/org1
g, user2, org_owner, organizations/org2
```

**Expected behavior**
Should return true for request: `user1, organizations/org1, read`
But returns false

The same setup is working on the online editor, I have added screenshots of both
Using version: v2.36.2

**Screenshots**
editor setup:
![image](https://user-images.githubusercontent.com/79306078/132093504-9693c08c-cced-4260-9099-73130027a25e.png)

go setup:
![image](https://user-images.githubusercontent.com/79306078/132093534-7134da16-ad0d-48dd-a9db-d316f2c7598b.png)

Disclaimer:
I think I am not adding the domainmatchingfunction properly, can you please check

**Comment by tangyang9464** [comment]
@aravindakumarbootlabs you should add ``e.BuildRoleLinks()`` to build again after add match func
```
e.AddNamedDomainMatchingFunc("g","",util.KeyMatch4)
e.BuildRoleLinks()
```
