### ISSUE TITLE
[Bug] When there is a comma in the policy, the policy fails to load.

### ISSUE THREAD

**Issue by techoner** [casbin/casbin#886]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
When there is a comma in the policy, the policy fails to load.

**To Reproduce**

```go
m, _ := model.NewModelFromFile("examples/rbac_model.conf")
persist.LoadPolicyLine(`p, alice, data, r.act in ("get", "post")`, m)
m.PrintPolicy() // Nothing is printed , it should output `[p alice data r.act in ("get", "post")]`
```
**Additional context**
Probably there was a problem in CSV Reader ：https://github.com/casbin/casbin/blob/master/persist/adapter.go#L30
Can we provide a method like this :
```go
func LoadPolicy(tokens []string, m model.Model) {
	key := tokens[0]
	sec := key[:1]
	m[sec][key].Policy = append(m[sec][key].Policy, tokens[1:])
	m[sec][key].PolicyMap[strings.Join(tokens[1:], model.DefaultSep)] = len(m[sec][key].Policy) - 1
}
```

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
@techoner you should use like this
```
persist.LoadPolicyLine(`p, alice, data, "r.act in (""get"", ""post"")"`, m)
l := &log.DefaultLogger{}
l.EnableLog(true)
m.SetLogger(l)
m.PrintPolicy()
```
If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote. 
And you must set a logger.

**Comment by techoner** [comment]
@tangyang9464  I think we have the same problem with orm-adapter, such as [gorm-adapter adapter.go#L398](https://github.com/casbin/gorm-adapter/blob/master/adapter.go#L398), adding double-quotes is unnecessary, we can load the strategy from the array.

**Comment by tangyang9464** [comment]
@techoner Suppose we have a ``policy.csv``, how to get the array? We can solve this problem as above, I think support the specified separator is not necessary

**Comment by techoner** [comment]
@tangyang9464  We can split csv into an array using delimiters. In more cases, we use DatabaseAdapter. However, we need to add double quotes to each column, then concatenate it into a string, and then split it. This is redundant.

**Comment by techoner** [comment]
Use part of gorm-adapter code to make an example :
```go

type CasbinRule struct {
	ID    uint   `gorm:"primaryKey;autoIncrement"`
	Ptype string `gorm:"size:100"`
	V0    string `gorm:"size:100"`
	V1    string `gorm:"size:100"`
	V2    string `gorm:"size:100"`
	V3    string `gorm:"size:100"`
	V4    string `gorm:"size:100"`
	V5    string `gorm:"size:100"`
}

func (CasbinRule) TableName() string {
	return "casbin_rule"
}

func ruleToLineText(line CasbinRule) string{
	var p = []string{line.Ptype,
		strconv.Quote(line.V0), strconv.Quote(line.V1), strconv.Quote(line.V2),
		strconv.Quote(line.V3), strconv.Quote(line.V4), strconv.Quote(line.V5)}

	var lineText string
	if line.V5 != "" {
		lineText = strings.Join(p, ", ")
	} else if line.V4 != "" {
		lineText = strings.Join(p[:6], ", ")
	} else if line.V3 != "" {
		lineText = strings.Join(p[:5], ", ")
	} else if line.V2 != "" {
		lineText = strings.Join(p[:4], ", ")
	} else if line.V1 != "" {
		lineText = strings.Join(p[:3], ", ")
	} else if line.V0 != "" {
		lineText = strings.Join(p[:2], ", ")
	}

	return lineText
}

func Test(t *testing.T) {
	m, _ := model.NewModelFromFile("examples/rbac_model.conf")
	rule := CasbinRule{
		Ptype: "p",
		V0:    "alice",
		V1:    "data",
		V2:    `r.act in ("get", "post")`,
	}

	line := ruleToLineText(rule)
	fmt.Println(line)
	persist.LoadPolicyLine(line, m)
	t.Log(m["p"]["p"].Policy) // [] Does not meet expectations

	rule.V2 = `r.act in (""get"", ""post"")`
	line = ruleToLineText(rule)
	fmt.Println(line)
	persist.LoadPolicyLine(line, m)
	t.Log(m["p"]["p"].Policy) // [] Does not meet expectations 
}
```

**Comment by tangyang9464** [comment]
@techoner I got it and I think the csv file (FileAdapter) still needs double quotes to split. But the database adapter doesn't need delimiter. Maybe we can implement a method ``LoadPolicyLineByArray`` specifically for the database adapter.
In csv file, you still need to use like ``"r.act in (""get"", ""post"")"`` but in db you can just use normally like ``r.act in ("get", "post")``

**Comment by techoner** [comment]
@hsluoyz @tangyang9464 Did I not understand enough? 
### In my database like this :
|  ptype   | v0|v1|v2|
|  ----  | ----  |----  |----  |
| p| alice |data |r.act in ("get", "post") |
| p  | bob | data | 1 == 1 |
### Code like this:
```go
	m, _ := model.NewModelFromString(`
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && eval(r.act)
`)
	a, _ := gormadapter.NewAdapter("mysql", "root:yourpassword@tcp(127.0.0.1:3306)/", "test") // Your driver and data source.
	e, _ := casbin.NewEnforcer(m, a, true)

	t.Log(e.GetModel()["p"]["p"].Policy)  // It only outputs:  [[bob data 1 == 1]]
```
### Why the first policy is not loaded ?

**Comment by tangyang9464** [comment]
> @hsluoyz @tangyang9464 Did I not understand enough? 
> ### In my database like this :
> |  ptype   | v0|v1|v2|
> |  ----  | ----  |----  |----  |
> | p| alice |data |r.act in ("get", "post") |
> | p  | bob | data | 1 == 1 |
> ### Code like this:
> ```go
> 	m, _ := model.NewModelFromString(`
> [request_definition]
> r = sub, obj, act
> 
> [policy_definition]
> p = sub, obj, act
> 
> [role_definition]
> g = _, _
> 
> [policy_effect]
> e = some(where (p.eft == allow))
> 
> [matchers]
> m = g(r.sub, p.sub) && r.obj == p.obj && eval(r.act)
> `)
> 	a, _ := gormadapter.NewAdapter("mysql", "root:yourpassword@tcp(127.0.0.1:3306)/", "test") // Your driver and data source.
> 	e, _ := casbin.NewEnforcer(m, a, true)
> 
> 	t.Log(e.GetModel()["p"]["p"].Policy)  // It only outputs:  [[bob data 1 == 1]]
> ```
> ### Why the first policy is not loaded ?
> 
>  

As mentioned above, I will make some changes to the adapter. Then it can  be used normally after that

**Comment by tungdn3** [comment]
I have tried the suggestion to escape commas and quotes but it does not work. Please refer to this: https://casbin.org/casbin-editor/#6NDKB3HMP
Does anyone know what's wrong here? Thanks.

**Comment by tangyang9464** [comment]
@tungdn3 You can test it by Go-casbin. The editor depends on node-casbin and they have some differences.

**Comment by hsluoyz** [comment]
@tungdn3 moverover, if you really find difference between Casbin-editor (Node-Casbin) and (Golang) Casbin and believe it's a bug, please report to us!
