### ISSUE TITLE
Help at modeling a user/role/group combined model

### ISSUE THREAD

**Issue by JanakaSandaruwan** [casbin/casbin#892]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------
Need a help in modeling our scenario considering:
- The users belong to groups
- Groups have roles
- Roles have permissions

For example, `alice` is a user in the system. `alice` belongs to `developer` group. `developer` group has set of roles such as `app-devloper`. These roles have permissions on resources.

My request is like `user,resource,permission`

How to implement a model for this scenario?

**Comment by tangyang9464** [comment]
@JanakaSandaruwan How about this https://casbin.org/casbin-editor/#B5EF3B4N6 ?

**Comment by hsluoyz** [comment]
@MRGUOKING this issue should be labeled as "question", as there's a "How to"

**Comment by JanakaSandaruwan** [comment]
Seems this fit my scenario. Here group is considered as a role and uses role hierarchy model ? 
Thanks for the help

**Comment by tangyang9464** [comment]
@JanakaSandaruwan yes, use role hierarchy
