### ISSUE TITLE
Role Manager performance / scaling issue

### ISSUE THREAD

**Issue by dahu33** [casbin/casbin#893]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Is your feature request related to a problem? Please describe.**

Using the standard RBAC model:
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

The `(*RoleManager).HasLink` function is called N time, where N is the the number of unique subjects found in the policies. While this may work ok if the relationships are stored in memory, it just doesn't scale at all if the relationships are stored in an external datastore.

Examples with a model containing 100 unique subjects that all have at least one policy:
- our custom RoleManager that stores relationship in PostgreSQL would make 99 SQL queries (one per `(*RoleManager).HasLink` function call) for each `(*Enforcer).Enforce` call.
- the https://github.com/casbin/okta-role-manager  would make 99 Okta API calls (one per `(*RoleManager).HasLink` function call) for each `(*Enforcer).Enforce` call.
- the https://github.com/casbin/auth0-role-manager would make 99 Auth0 API calls (one per `(*RoleManager).HasLink` function call) for each `(*Enforcer).Enforce` call.
- etc...

As you can see with the examples above, this cannot really scale past a few unique subjects and I'm surprised that this issue hasn't been raised before.

**Describe the solution you'd like**
Ideally, when enforcing a policy, instead of calling `(*RoleManager).HasLink` for each unique subjects, the `(*RoleManager).GetRoles` function should be called to get all the relations of a subject in one shot.

**Comment by tangyang9464** [comment]
@dahu33 I have a few opinions and questions
1. I don't konw what means about ``call GetRoles to get all the relations of a subject in one shot.``. Below is the code that calls ``HasLink`` each time in funtion ``g(r.sub, p.sub)``. Plz indicate how you think the code should be improved
https://github.com/casbin/casbin/blob/8987b1435512c363eb07e5b2b4a9057c1dfa58e6/util/builtin_operators.go#L310-L339
2. I think there are some problems in the implementation of these two manager (auth0, okta), and they cannot be used as a reference.
3. I don't know how your custom manager is implemented. I think there is no logic problem with every ``enforce`` call to ``haslink``. Maybe the relationship should be loaded into memory when setting up the manager? 

Looking forward to your reply!

**Comment by hsluoyz** [comment]
@dahu33 yes, the built-in role manager uses cache to achieve fast speed in HasLink(). okta-role-manager and auth0-role-manager may have a bad implementation and queries DB each time. They should be modified to cache the get roles result and serves the HasLink() query locally in memory, so they will be fast.
