### ISSUE TITLE
Model not working

### ISSUE THREAD

**Issue by supriyapatil123** [casbin/casbin#90]
I want to change policy file to add sub in it. I tried ``sub := req.User``, ``sub:=UserNMethod``, ``sub:=UserNMethod.string()`` but its not working and when I provided ``sub="user_name"`` hardcoded then its working.

**Comment by hsluoyz** [comment]
Can you provide the complete content of your model file and policy file?

**Comment by supriyapatil123** [comment]
[request_definition]

r = sub, obj, act[policy_definition]

p = sub, obj, act[policy_effect]

e = some(where (p.eft == allow))[matchers]

m = r.sub == p.sub && keyMatch(r.obj, p.obj) && keyMatch(r.act, p.act)

**Comment by supriyapatil123** [comment]
p, supriya, /v1.37/*, GET

**Comment by supriyapatil123** [comment]
sent you both files.

**Comment by supriyapatil123** [comment]
policy.go 

// Docker RBAC & ABAC Authorization Plugin based on Casbin.

// Allows only authorized Docker operations based on access control policy.

// AUTHOR: Yang Luo <hsluoyz@gmail.com>

// Powered by Casbin: https://github.com/casbin/casbinpackage mainimport (

    "github.com/casbin/casbin"

    "github.com/docker/go-plugins-helpers/authorization"

    "log"

    "net/url"

)// CasbinAuthZPlugin is the Casbin Authorization Plugin

type CasbinAuthZPlugin struct {

    // Casbin enforcer

    enforcer *casbin.Enforcer

}// newPlugin creates a new casbin authorization plugin

func newPlugin(casbinModel string, casbinPolicy string) (*CasbinAuthZPlugin, error) {

    plugin := &CasbinAuthZPlugin{}    plugin.enforcer = casbin.NewEnforcer(casbinModel, casbinPolicy)    return plugin, nil

}// AuthZReq authorizes the docker client command.

// The command is allowed only if it matches a Casbin policy rule.

// Otherwise, the request is denied!

func (plugin *CasbinAuthZPlugin) AuthZReq(req authorization.Request) authorization.Response {

    // Parse request and the request body

    reqURI, _ := url.QueryUnescape(req.RequestURI)

    reqURL, _ := url.ParseRequestURI(reqURI)

    //username := url.ParseRequestURI(reqURI)    obj := reqURL.String()

    act := req.RequestMethod

    log.Println("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")

    log.Println(req)

    log.Println("............")

    //sub := "root"

       //log.Println("SUB TEST 1")

       //log.Println(sub)

       //log.Println(req)

       //log.Printf("%+v\n", req)

       //log.Println("SUB TEST 2")

       sub := req.User

       //sub := "supriya"

    log.Println("SUB TEST 3")

       log.Println(sub)

       log.Println(req)

       log.Printf("%+v\n", req)

       log.Println("SUB TEST 4")    if plugin.enforcer.Enforce(sub, obj, act) {

            log.Println("sub:", sub, "obj:", obj, ", act:", act, "res: allowed")

        return authorization.Response{Allow: true}

    }    log.Println("sub:", sub, "obj:", obj, ", act:", act, "res: denied")

    return authorization.Response{Allow: false, Msg: "Access denied by casbin plugin"}

}// AuthZRes authorizes the docker client response.

// All responses are allowed by default.

func (plugin *CasbinAuthZPlugin) AuthZRes(req authorization.Request) authorization.Response {

    // Allowed by default.

    return authorization.Response{Allow: true}

} (edited)

**Comment by supriyapatil123** [comment]
Error response from daemon: plugin casbin-authz-plugin failed with error: Post http://%2Frun%2Fdocker%2Fplugins%2Fcasbin-authz-plugin.sock/AuthZPlugin.AuthZReq: EOF

**Comment by supriyapatil123** [comment]
If made changes in policy.go like 



/ Docker RBAC & ABAC Authorization Plugin based on Casbin.

// Allows only authorized Docker operations based on access control policy.

// AUTHOR: Yang Luo <hsluoyz@gmail.com>

// Powered by Casbin: https://github.com/casbin/casbinpackage mainimport (

    "github.com/casbin/casbin"

    "github.com/docker/go-plugins-helpers/authorization"

    "log"

    "net/url"

)// CasbinAuthZPlugin is the Casbin Authorization Plugin

type CasbinAuthZPlugin struct {

    // Casbin enforcer

    enforcer *casbin.Enforcer

}// newPlugin creates a new casbin authorization plugin

func newPlugin(casbinModel string, casbinPolicy string) (*CasbinAuthZPlugin, error) {

    plugin := &CasbinAuthZPlugin{}    plugin.enforcer = casbin.NewEnforcer(casbinModel, casbinPolicy)    return plugin, nil

}// AuthZReq authorizes the docker client command.

// The command is allowed only if it matches a Casbin policy rule.

// Otherwise, the request is denied!

func (plugin *CasbinAuthZPlugin) AuthZReq(req authorization.Request) authorization.Response {

    // Parse request and the request body

    reqURI, _ := url.QueryUnescape(req.RequestURI)

    reqURL, _ := url.ParseRequestURI(reqURI)

    //username := url.ParseRequestURI(reqURI)    obj := reqURL.String()

    act := req.RequestMethod

    log.Println("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")

    log.Println(req)

    log.Println("............")

    //sub := "root"

       //log.Println("SUB TEST 1")

       //log.Println(sub)

       //log.Println(req)

       //log.Printf("%+v\n", req)

       //log.Println("SUB TEST 2")

       sub := req.User

       //sub := "supriya"

    log.Println("SUB TEST 3")

       log.Println(sub)

       log.Println(req)

       log.Printf("%+v\n", req)

       log.Println("SUB TEST 4")    if plugin.enforcer.Enforce(sub, obj, act) {

            log.Println("sub:", sub, "obj:", obj, ", act:", act, "res: allowed")

        return authorization.Response{Allow: true}

    }    log.Println("sub:", sub, "obj:", obj, ", act:", act, "res: denied")

    return authorization.Response{Allow: false, Msg: "Access denied by casbin plugin"}

}// AuthZRes authorizes the docker client response.

// All responses are allowed by default.

func (plugin *CasbinAuthZPlugin) AuthZRes(req authorization.Request) authorization.Response {

    // Allowed by default.

    return authorization.Response{Allow: true}

} 

then also not working but if  hardcoded then its working

**Comment by supriyapatil123** [comment]
I have provided my content of files on github.Please check and tell me what
are  changes that needs to be done in order to achieve what I want.

**Comment by hsluoyz** [comment]
Can you format your code in Go in the GitHub editor? The current form makes me difficult to read.

**Comment by hsluoyz** [comment]
Not yet, please reformat this code in Goland

**Comment by supriyapatil123** [comment]
Is it ok to have model and policy file as it is?

**Comment by hsluoyz** [comment]
Casbin authz plugin relies on TLS to get the subject (user). So please enable TLS on Docker daemon and make sure Docker has passed in the user variable to Casbin.

**Comment by supriyapatil123** [comment]
so code sub:= req.User is correct in policy file

**Comment by supriyapatil123** [comment]
Am I right?

**Comment by supriyapatil123** [comment]
Because my doubt is the policy file provided by casbin does not contain sub field, So Is it neccessary to add sub field in policy file like     sub := req.User .

**Comment by hsluoyz** [comment]
Of course yes.
