### ISSUE TITLE
Prior "allow" policies for users that belong to multiple groups

### ISSUE THREAD

**Issue by nikitabray** [casbin/casbin#911]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
I have tree-like hierarchical structure. node_1 and node_2 has common ancestor: root. Alice can read from node_1 and cannot from node_2, bob can read from node_2 and cannot from node_1, duck should be able to read from both nodes, but it's not. Can this be done with some stub function or should I use completely different model? I think i somehow need to prioritise "allow" rule if user inherits both "deny" and "allow" from different user groups.
**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && r.act == p.act
```

**Your policy:**

```
p, moderator_node_1, root, read, allow
p, moderator_node_1, node_2, read, deny
p, moderator_node_2, root, read, allow
p, moderator_node_2, node_1, read, deny

g, alice, moderator_node_1
g, bob, moderator_node_2
g, duck, moderator_node_1
g, duck,  moderator_node_2

g2, node_1, root
g2, node_2, root
```

**Your request(s):**

```
duck, node_1, read ---> false (expected: true)
duck, node_2, read ---> false (expected: true)
```

**Comment by hsluoyz** [comment]
Hi @nikitabray , why don't use the Priority model? https://casbin.org/docs/en/priority-model

**Comment by Abingcbc** [comment]
> Hi @nikitabray , why don't use the Priority model? https://casbin.org/docs/en/priority-model

@hsluoyz Priority model can pass @nikitabray 's requests. But it will fail in the following case:

```
alice, node_2, read ---> true (expected: false)
```

Because the first policy it matches is `p, moderator_node_1, root, read, allow` and the effect is `allow`. It directly return True.

**Comment by Abingcbc** [comment]
One way to walk around is making policies of parent resource is after the children's. This is a requirement for users.

**Comment by hsluoyz** [comment]
@Abingcbc can you provide the model and policy here?

**Comment by Abingcbc** [comment]
Model:
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = priority(p.eft) || deny

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && r.act == p.act
```

Policy:
```
p, moderator_node_1, node_1, read, allow
p, moderator_node_2, node_2, read, allow
p, moderator_node_1, node_2, read, deny
p, moderator_node_2, node_1, read, deny
p, moderator_node_1, root, read, allow
p, moderator_node_2, root, read, allow

g, alice, moderator_node_1
g, bob, moderator_node_2
g, duck, moderator_node_1
g, duck,  moderator_node_2

g2, node_1, root
g2, node_2, root
```

Test cases:
```
alice, node_1, read --->  true
alice, node_2, read --->  false
bob, node_1, read --->  false
bob, node_2, read --->  true
duck, node_1, read --->  true
duck, node_2, read --->  true
```

There are 3 points about the policy we should pay attention to:
1. We should explicitly write `allow` policies.
e.g. `p, moderator_node_1, node_1, read, allow`
2. `Allow` policies should be before `deny` policies.
e.g. `p, moderator_node_1, node_1, read, allow` should be before `p, moderator_node_2, node_1, read, deny`.
3. Policies of children's resources should be before parent's resources'.
e.g. `p, moderator_node_1, node_2, read, deny` should be before `p, moderator_node_1, root, read, allow`.

**Comment by hsluoyz** [comment]
Closed as resolved
