### ISSUE TITLE
[Bug] Casbin ABAC rules fail if policy includes any "deny" rows

### ISSUE THREAD

**Issue by silverspace** [casbin/casbin#917]
**Describe the bug**
When an **ABAC** `Super Admin` matcher is used in conjunction with a **policy** that includes `deny` effects, the matcher erroneously fails if **any** policy in `policy.csv` contains a `deny` effect. 

**To Reproduce**
See this shared example I created using the casbin editor: 
https://casbin.org/casbin-editor/#E3LXSU3ZS

Observe that the two requests succeed if the `"foobar"` rule in the policy is changed to `"allow"`, and both fail if the `"foobar"` rule is `"deny"`. 

Note that I pared down my actual model and policy files to be the minimal reproducible use case, which is why this does not use any groups, actions, users, etc. This fails even if I have legitimate users and roles that do not match to the "foobar" user. 

Short summary without the above online editor:

**model.conf**:
```
[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = r.sub.Superuser || r.sub.User == r.obj.Owner
```

**policy.csv**:
```
p, foobar, /blah, read, deny
```

**Request**:
```
{ User: 'alice', Superuser: true }, { Owner: 'bob'}, read
```

**Expected behavior**
If we have an ABAC rule to allow access for `Super Users`, that access should not be contingent upon unrelated subjects having `deny` effects in the policy file. 

**Screenshots**

**Successful run without `deny` rule in policy file:**
![image](https://user-images.githubusercontent.com/15318933/141872427-a710dace-ed85-487d-a1cd-a457e15a66cf.png)

**Unsuccessful run with unrelated `deny` rule in policy file:**
![image](https://user-images.githubusercontent.com/15318933/141872473-5d69afa3-44f1-4475-afdf-fbfb1cc56060.png)

**Comment by hsluoyz** [comment]
@abichinger @Abingcbc

**Comment by tlyyxjz** [comment]
Really nice minimal repro. The `!some(where(p.eft == deny))` clause makes any unrelated deny row poison the entire evaluation — easy to forget when you mix ABAC (subject attributes) with policy effects. That ABAC × deny interaction is a classic "silently wrong" trap: it looks fine in tests, fails deep in prod. Exactly the kind of matcher/effect combination an automated diagnostic (over policy_effect + matcher) should catch before it ships.
