### ISSUE TITLE
Request and response flow 

### ISSUE THREAD

**Issue by supriyapatil123** [casbin/casbin#92]
I want to check how docker responses to library output. so I have made one go file which contain only authz request and response method and passed value to authorization.response as true/ false. So as per documentation if value = true then it should allow user to use docker command on CLI and if false then it should not.
but when I am providing any value as true or false it does not reflect on docker CLI.
Can we provide solution that how should I write my go file.

**Comment by hsluoyz** [comment]
It seems that the Casbin authz plugin is not working for the Docker daemon. Please follow the configuration instructions in the README. And please raise the issue in the plugin's issues page: https://github.com/casbin/casbin-authz-plugin/issues instead of here.
