### ISSUE TITLE
Get permission for user in domain - filtering policies without domains

### ISSUE THREAD

**Issue by timabilov** [casbin/casbin#920]
------

**What's your scenario? What do you want to achieve?**

There might be the cases when policy has dynamic(patterns?) domains or don't even have any domains
As a reference this is an example  (performance example)
https://github.com/casbin/casbin/blob/master/examples/performance/rbac_with_pattern_large_scale_policy.csv
other model  example(https://github.com/casbin/casbin/issues/493)

`GetPermissionsForUserInDomain` will not work for all above examples. Because for `p` we might have either domains with patterns, or even don't have them at all. But `GetPermissionsForUserInDomain` filters policies by hardcode domain string.

For my case (no domains) this works: matching roles by domain, but filtering policies only by `singleUser` - skip optional domain
```
func (e *Enforcer) GetPermissionsForUserInDomain(user string, domain string) [][]string {
	var res [][]string
	users, _ := e.GetRolesForUser(user, domain)
	users = append(users, user)
	for _, singleUser := range users {
		policy := e.GetFilteredPolicy(0, singleUser, domain) # *this* domain part should be optional or domain keymatched by fn?
		res = append(res, policy...)
	}
	return res
}
```

**Your model:**

```ini
[request_definition]
r = sub, obj, act, dom

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && keyMatch4(r.obj, p.obj) && r.act == p.act
```

**Your policy:**

```
p, role::admin, data1, read
p, role::developer, data1, write

g, role::super_admin, role::developer, *
g, role::super_admin, role::admin, *

g, alice, role::super_admin, mydomain

```

**Your request(s):**

```
alice, data1, read, mydomain --->  true (expected: true)
e.GetPermissionsForUserInDomain('alice', 'mydomain') # [] empty -> expected [ data1:read, data1:write]
```
 GetPermissionsForUserInDomain  will not be consistent with above request(no `data1, read`) 

I Checked 'performance' example on pycasbin and it **is** returning empty permissions and now  after checking the source code i believe that gocasbin implementation is the same.

So, If this performance example **is** relevant, and i am not missed anything - i have PR for  empty domain pycasbin if needed ( i can adapt ), can make it for GO
 or please explain the domains patterns in `p` record  performance example, why we even need them if GetPermissionsForUserInDomain ignores all of them.

**Comment by hsluoyz** [comment]
@nodece @sagilio @abichinger @Abingcbc

**Comment by timabilov** [comment]
For cases with domains with patterns in policy records, ideally we have to match them by matching function, not filtering them as plain string.

Considering that get permissions by domain *can* filter by domains and in case of keymatching domains(added domain match fn) we should not ignore keymatching when filtering domains in policies instead of strict str checking.

That why i think this is  inconsistent behaviour

**Comment by abichinger** [comment]
We could add an additional parameter `fn` to `GetPermissionsForUserInDomain` to fix this issue.

```go
type fieldIndexValues func(user string, domain string) (int, []string)

// GetPermissionsForUserInDomain gets permissions for a user or role inside a domain.
func (e *Enforcer) GetPermissionsForUserInDomain(user string, domain string, fn fieldIndexValues) [][]string {
	var res [][]string
	users, _ := e.GetRolesForUser(user, domain)
	users = append(users, user)
	for _, singleUser := range users {
		var fieldIndex, fieldValues = fn(singleUser, domain)
		policy := e.GetFilteredPolicy(fieldIndex, fieldValues...)
		res = append(res, policy...)
	}
	return res
}
```

To mimic the present behavior of `GetPermissionsForUserInDomain` you can pass the following function:
```go
func PolicyFilter(user string, domain string) (int, []string) {
	return 0, []string{user, domain}
}
```

In your example, you can pass this function:
```go
func PolicyFilter(user string, domain string) (int, []string) {
	return 0, []string{user}
}
```

This approach does not support matching function on policy records.

**Comment by timabilov** [comment]
@abichinger
It is really interesting that after domain **match** support this filter part is missed. Isn't this a bug rather than enhancement? 


Also its sad that `matchers` internals is not quite flexible to reuse them for filtering policies. I think that will be fair and more consistent rather than  actual implementation. Because matcher is source of truth.  
Otherwise you have to give the same matchers flexibility for user to reproduce that query for GetFilteredPolicy. 

Is there maybe any easier way to somehow partly duplicate and integrate matchers part for filter as a start?

as a temporary solution -  optional matching function (cover matcher)  to pass into GetFilteredPolicy, even with performance hit it is the only way i believe

**Comment by timabilov** [comment]
from performance example:
 That is for all cases which is not just == 
we have regex for action and keymatch4 for domain
```
[matchers]
m = g(r.sub, p.sub, r.obj) && keyMatch4(r.obj, p.obj) && regexMatch(r.act, p.act)
```


but here we filter only with  ==
```
return [
            rule
            for rule in self[sec][ptype].policy
            if all(
                value == "" or rule[field_index + i] == value
                for i, value in enumerate(field_values)
            )
        ]
```

**Comment by hsluoyz** [comment]
@timabilov `GetPermissionsForUser()` only works for the default RBAC scenario, it's much simpler and not equal to `Enforce()`, you should use `BatchEnforce()` instead
