### ISSUE TITLE
CoreEnforcer.php There is an incorrect resolution [Bug]

### ISSUE THREAD

**Issue by 490626721** [casbin/casbin#923]
**Describe the bug**
An error occurred while trying to create the RBAC model. 

`array_combine(): Both parameters should have an equal number of elements`

Check the error code address and find that the error exists in line CoreEnforcer.php 645

`{
    "file": "E:\\phpstudy_pro\\WWW\\c.com\\vendor\\casbin\\casbin\\src\\CoreEnforcer.php",
    "line": 645,
    "function": "array_combine",
    "args": [
        [
            "p_sub",
            "p_obj",
            "p_act"
        ],
        [
            "测试, /admin/setup/wx",
            "ANY"
        ]
    ]
}`

It processes "test" and "/ admin / setup / Wx" into one field. The correct one should be

`      [
            "测试“,
            ”/admin/setup/wx",
            "ANY"
        ]`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hsluoyz** [comment]
@490626721 this repo is for Golang Casbin. Please send the issue to PHP-Casbin.
