### ISSUE TITLE
[Bug] Model ToText ignores to conver `p_eft` to `p.eft`

### ISSUE THREAD

**Issue by Abingcbc** [casbin/casbin#926]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**

`Model.ToText` (https://github.com/casbin/casbin/blob/master/model/model.go#L339)
uses tokens of model (e.g. `p_act`) to replace `_` with `.` because users may use `_` for their own purpose. This is quite reasonable.

However, from these codes https://github.com/casbin/casbin/blob/master/model/model.go#L69 , we can see that model only stores tokens in `p` and `r`. So it will ignore tokens in `e` (e.g. `p_eft`)

Therefore, the behavior of `ToText` is confusing.
Take `examples/rbac.conf` as an example, the output of `ToText` is as follows:

![image](https://user-images.githubusercontent.com/34068205/145413149-7a49518b-2de0-4a70-b659-f5cfb637fbfe.png)

We can see that tokens like `sub` are converted from `r_sub` to `r.sub`. But `p_eft` still keeps the format stored in casbin's model.

**Comment by hsluoyz** [comment]
@abichinger @nodece any comments?

**Comment by abichinger** [comment]
It does not affect the behaviour of the model, but to be consistent we should replace `p_eft` with `p.eft`.

**Comment by hsluoyz** [comment]
@Abingcbc plz fix it
