### ISSUE TITLE
[Question] Parameters in Cache interface for CachedEnforcer

### ISSUE THREAD

**Issue by alikhanz** [casbin/casbin#927]
**What's your scenario? What do you want to achieve?**

I'm want to use Redis cache in CachedEnforcer

I'm trying to implement `Cache` interface for using Redis

https://github.com/casbin/casbin/blob/3d0481d5d8357c466c4b9abe04b54d137a7c8cf1/persist/cache/cache.go#L21-L39 

And i'm not understand why 3rd parameter in `Set` method is `extra ...interface{}` and not like `expiration time.Duration`? In `CachedEnforcer` 3rd parameter is expriation time:

https://github.com/casbin/casbin/blob/master/enforcer_cached.go#L86

https://github.com/casbin/casbin/blob/3d0481d5d8357c466c4b9abe04b54d137a7c8cf1/enforcer_cached.go#L82-L88

My point of view is that not strictly specifying the parameter can lead to errors in the future, may be change this signature?

**Comment by hsluoyz** [comment]
@closetool any reason for using `extra` and `interface{}`? Actually I didn't see anywhere the arg is used or type casted?

**Comment by alikhanz** [comment]
Also im not understand why `expireTime` property defined as `uint`, and not `time.Duration`? 
I can't find comments what is `expireTime`: milliseconds/seconds/minutes/hours?

**Comment by hsluoyz** [comment]
@alikhanz I think this function and its args may be not very well-designed. Can you make a PR with a more precise declaration?

**Comment by alikhanz** [comment]
> @alikhanz I think this function and its args may be not very well-designed. Can you make a PR with a more precise declaration?

Yes i can, but this changes can break backward compatibility with others `Cache` implementation, will this PR be released in v3?

**Comment by hsluoyz** [comment]
@alikhanz I think there are no other Cache implementations in any other repos (you can also search on GitHub to confirm it). Only this repo uses it. So changing the function args will not cause visible breaking changes to the users.

**Comment by alikhanz** [comment]
> @alikhanz I think there are no other Cache implementations in any other repos (you can also search on GitHub to confirm it). Only this repo uses it. So changing the function args will not cause visible breaking changes to the users.

Done: https://github.com/casbin/casbin/pull/934

**Comment by hsluoyz** [comment]
Closed as: https://github.com/casbin/casbin/pull/934
