### ISSUE TITLE
[Question] User group membership and role assignment to groups

### ISSUE THREAD

**Issue by amit-chandak-unskript** [casbin/casbin#929]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Want to implement a scenario wherein users are part of groups and groups get assigned different roles in different domains. There is a group named superGroup which has access to all.

**Your model:**

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _, _
# g2 is used to capture user->group mapping.
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && keyMatch(r.act, p.act) && keyMatch(r.obj, p.obj) || g2(r.sub, p.sub)
```

**Your policy:**

```
# Top level roles.
# Admin role.
p, role:admin, *, *
# Editor role.
p, role:editor, obj:runbook, create
p, role:editor, obj:runbook, update
p, role:editor, obj:runbook, delete
p, role:editor, obj:credential, create
p, role:editor, obj:credential, update
p, role:editor, obj:credential, delete
p, role:editor, obj:lego, create
p, role:editor, obj:lego, update
p, role:editor, obj:lego, delete
# Requestor role.
p, role:requestor, obj:runbook, request
# Approver role.
p, role:approver, obj:runbook, approver
# Executor role.
p, role:executor, obj:runbook, execute

# SuperAdmin group.
g2, group:superAdmin, role:admin

# Group Membership
g, group:editor, role:editor, domain1

g, bob, group:editor, domain1
```

**Your request(s):**

```
bob, domain1, obj:runbook, write
```

This model works fine, but i want to avoid writing the user group membership domain specific as shown here.
```
g, bob, group:editor, domain1
```
I would rather keep the domain empty but I am not able to figure how to avoid it, i tried giving domain as * as well, but then it didnt work, for eg. I changed the group membership to this

```
g, bob, group:editor, *
```

Then this request starts failing
```
bob, domain1, obj:lego, write
```
Which should have passed if i had the non * way of defining group membership.

Any help on this will be greatly appreciated

**Comment by hsluoyz** [comment]
@amit-chandak-unskript `g, bob, group:editor, *` only works if you set up `AddNamedDomainMatchingFunc()`. See docs: https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac

**Comment by amit-chandak-unskript** [comment]
Awesome, thanks @hsluoyz . I just added 'keyMatch' for Domain Matching func and it worked. Checkout the example [here](https://casbin.org/casbin-editor/#BRB6ZL2Y3) if someone is interested.

**Comment by amit-chandak-unskript** [comment]
Hi @hsluoyz , sorry, the casbin editor [here](https://casbin.org/casbin-editor/#E56Z9VMVC) works fine, however my following golang function doesnt work

```
func main() {
	// Initialize a Redis adapter and use it in a Casbin enforcer:
	//a := redisadapter.NewAdapterWithKey("tcp", "127.0.0.1:6379", "tenantFOO/blah") // Your Redis network and address.
	// Use the following if Redis has password like "123"
	//a := redisadapter.NewAdapterWithPassword("tcp", "127.0.0.1:6379", "123")
	e, err := casbin.NewSyncedEnforcer("sampleCode/casbin/rbac_model.conf", "sampleCode/casbin/rbac_policy.csv")
	if err != nil {
		panic(err)
	}
	/*
		w, _ := rediswatcher.NewWatcher("127.0.0.1:6379", rediswatcher.WatcherOptions{
			Options: redis.Options{
				Network:  "tcp",
				Password: "",
			},
			Channel: "/casbin",
			// Only exists in test, generally be true
			IgnoreSelf: false,
		})

		e.SetAdapter(a)
		e.SavePolicy()
		// Set the watcher for the enforcer.
		_ = e.SetWatcher(w)

		// Set callback to local example
		_ = w.SetUpdateCallback(updateCallback)
	*/
	//e.AddPermissionForUser("", "data3", "read")
	e.EnableLog(true)
	e.AddNamedDomainMatchingFunc("g", "keyMatch", util.KeyMatch)
	_, err = e.AddNamedGroupingPolicy("g2", []string{"anika", "group:superAdmin"})
	if err != nil {
		panic(err)
	}
	//g, group:editor, role:editor, domain1
	//e.AddRoleForUserInDomain("group:editor", "role:editor", "domain1")
	//g, alice, group:viewer, *
	//e.AddRoleForUserInDomain("bob", "group:editor", "*")
	//a.AddPolicy("p", "p", []string{"alice", "data1", "read"})
	// Load the policy from DB.
	//e.LoadPolicy()
	p := e.GetPolicy()
	fmt.Println(p)
	//g2 := e.GetNamedGroupingPolicy("g2")
	//fmt.Println(g2)
	g := e.GetNamedGroupingPolicy("g")
	fmt.Println(g)
	// Check the permission.
	r, _ := e.Enforce("bob", "domain1", "obj:lego", "create")
	fmt.Println(r)
	//r, _ = e.Enforce("anika", "*", "*", "write")
	//fmt.Println(r)

	// Delete rules for alice.
	//e.RemoveFilteredNamedGroupingPolicy("g2", 0, "alice")
	//fmt.Println(e.GetNamedGroupingPolicy("g"))
	// Modify the policy.
	// e.AddPolicy(...)
	// e.RemovePolicy(...)
	// Save the policy back to DB.
	//e.SavePolicy()
	//time.Sleep(30)
}
```

```
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _, _
# g2 is used to capture user->group mapping.
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && keyMatch(r.act, p.act) && keyMatch(r.obj, p.obj) || g2(r.sub, p.sub)
```

```
#
# NOTE: The actions here should match with the constants defined in pkg/rbac/constants.go
#
# Top level roles.
# Admin role.
p, role:admin, *, *
# Editor role.
p, role:editor, obj:runbook, create
p, role:editor, obj:runbook, update
p, role:editor, obj:runbook, delete
p, role:editor, obj:credential, create
p, role:editor, obj:credential, update
p, role:editor, obj:credential, delete
p, role:editor, obj:lego, create
p, role:editor, obj:lego, update
p, role:editor, obj:lego, delete
# Requestor role.
p, role:requestor, obj:runbook, request
# Approver role.
p, role:approver, obj:runbook, approver
# Executor role.
p, role:executor, obj:runbook, execute

# SuperAdmin group.
g2, group:superAdmin, role:admin

g, group:editor, role:editor, domain1
g, group:editor, role:requestor, domain2
g, bob, group:editor, *

```

Not able to figure out why this that enforcement is saying false

**Comment by amit-chandak-unskript** [comment]
```
$ go run sampleCode/casbin/main.go
[[role:admin * *] [role:editor obj:runbook create] [role:editor obj:runbook update] [role:editor obj:runbook delete] [role:editor obj:credential create] [role:editor obj:credential update] [role:editor obj:credential delete] [role:editor obj:lego create] [role:editor obj:lego update] [role:editor obj:lego delete] [role:requestor obj:runbook request] [role:approver obj:runbook approver] [role:executor obj:runbook execute]]
[[group:editor role:editor domain1] [group:editor role:requestor domain2] [bob group:editor *]]
2021/12/12 00:51:24 Request: bob, domain1, obj:lego, create ---> false
Hit Policy:
false
```

I expected this to be true

**Comment by hsluoyz** [comment]
@abichinger @Abingcbc @sagilio @nodece any comments?

**Comment by Abingcbc** [comment]
@amit-chandak-unskript  @hsluoyz  I think the root cause is that the role inherits twice (bob --> group:editor --> role:editor). 
`node-casbin` use a third party parser. It can parse this kind of inheritance relation and match the policy. But `casbin` implement the parser itself and it cannot.

**Comment by amit-chandak-unskript** [comment]
> @amit-chandak-unskript @hsluoyz I think the root cause is that the role inherits twice (bob --> group:editor --> role:editor). `node-casbin` use a third party parser. It can parse this kind of inheritance relation and match the policy. But `casbin` implement the parser itself and it cannot.

Thanks @Abingcbc , so should we track this with an issue then?  Is there a quick fix i can try to keep going? Using custom functions. Sorry, i am not at all familiar with the code.

**Comment by Abingcbc** [comment]
> @amit-chandak-unskript @hsluoyz I think the root cause is that the role inherits twice (bob --> group:editor --> role:editor). `node-casbin` use a third party parser. It can parse this kind of inheritance relation and match the policy. But `casbin` implement the parser itself and it cannot.

To be more precise, the root cause is the domain changes in this two-level inheritance relation. `bob --> group:editor` is under domain `*` , but `group:editor --> role:editor` is under domain `domain1`.

For the latest `casbin`, it can only extend `bob`'s role to `group:editor`. As a result, the matcher will not match the policy `p, role:editor, obj:lego, create`.

**Comment by amit-chandak-unskript** [comment]
Thanks @Abingcbc , thats why, as a workaround, i have changed user->group membership to have domain as well and its working fine that way (meaning 
```
g, bob, group:editor, domain1
```

But thats not how ideally i want to model this. So, please keep us posted on the progress of this issue and any quick workaround, if you have any in mind.
