### ISSUE TITLE
[Bug]`GetAllSubjects` doesn't return subjects when using `priority model explicit`

### ISSUE THREAD

**Issue by zsh1995** [casbin/casbin#930]
**Describe the bug**
When using priority model explicit:
```
[policy_definition]
p = priority, sub, obj, act, eft
```
`GetAllSubjects` will return priority(such as "1", "2"...) rather than subject.

**Additional context**
`GetAllSubjects` always get first field of policy,  however index of `sub` depends on  policy definition. 
```go
func (e *Enforcer) GetAllSubjects() []string {
	return e.model.GetValuesForFieldInPolicyAllTypes("p", 0)
}
```

**Comment by hsluoyz** [comment]
@zsh1995 put `priority` at last.

```ini
[policy_definition]
p = sub, obj, act, eft, priority
```

**Comment by boromil** [comment]
If this is O.K., the [docs](https://casbin.org/docs/en/priority-model#load-policy-with-priority-explicitly) are misleading: `The first element in policy must be priority, and the smaller priority value will has higher priority.`.

In the long run, having casbin not use and index based "column" lockup would be a good thing.

**Comment by hsluoyz** [comment]
@boromil sorry, maybe I'm wrong.

@nodece @sagilio @abichinger @Abingcbc can priority be put to other places than the 1st element?

**Comment by sagilio** [comment]
@hsluoyz Yes, here is a part of loadModel.
https://github.com/casbin/casbin/blob/50d9daab83c57f02d0d4892daa7d7fc94125bead/model/model.go#L310-L319

We can find `sub`  index at `GetAllSubjects` to return the correct result in this issue case.

**Comment by hsluoyz** [comment]
@sagilio OK. Then the docs is wrong. Can you fix it in the docs? https://casbin.org/docs/en/priority-model#load-policy-with-priority-explicitly
