### ISSUE TITLE
enforce 方法的错误

### ISSUE THREAD

**Issue by JokerBruceChan** [casbin/casbin#94]
当我的库中存入

p_type | v0 | v1 |v2
--  | -- | -- | --
g | 6 | 2 |
g | 6 | 4 |
g | 2 | 1 |
p | 1 | api/users/ | GET

为什么 enforce("6","api/users/","GET") 的返回结果为 true ? 这是否是一个错误的表现？
casbin 中的 enforce 方法是如何工作的？

**Comment by hsluoyz** [comment]
这是因为默认的Role Manager设置的角色继承层次是10，所以6继承了角色2,2继承了角色1,1具有权限。你可以修改下面的maxHierarchyLevel值，修改为0，表示不允许角色继承。

https://github.com/casbin/casbin/blob/25ad5e60dee6815826ceb9fe2a9873362a32ce0b/rbac/default-role-manager/role_manager.go#L32-L37
