### ISSUE TITLE
Understanding Priority Setup

### ISSUE THREAD

**Issue by jherman** [casbin/casbin#944]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Your answer here

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = priority, sub, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = priority(p.eft) || deny

[matchers]
m = (p.sub == '*' || has_perm(r.sub, p.sub)) && keyMatch2(r.obj, p.obj) && (p.act == '*' || regexMatch(r.act, p.act))
```

**Your policy:**

```
p, 100, *, /api/tenant/:id, GET, allow
p, 1, user:list, /api/tenant/user, GET, allow
```

**Your request(s):**

```
[user_perms], "/api/tenant/user", "GET" ---> true (expected: false)
```

Hi. Perhaps I'm not understanding how priorities work. In my scenario, assume the user doesn't have the permission string `user:list`. My thought process tells me that if there is a failure in the first URL match, request would be denied. Since `/api/tenant/user` has a priority of 1, it would be checked first. This should fail and bail out with a deny since the `user:list` permission string is missing. However, stepping through the code, it continues on to `/api/tenant/:id`, where it is allowed.

Any advice for me? Thanks!

**Comment by hsluoyz** [comment]
@abichinger @Abingcbc @sagilio

**Comment by Abingcbc** [comment]
@jherman You can refer to https://casbin.org/docs/en/priority-model
`the order determines the priority, policy appeared earlier has higher priority`

Casbin doesn't support defining priority by a parameter, but you can define the priority by your policy order.
```
p, user:list, /api/tenant/user, GET, allow
p, *, /api/tenant/:id, GET, allow
```

**Comment by hsluoyz** [comment]
@jherman you should use deny as effect to make it work.

**Comment by jherman** [comment]
Just an FYI for those who find this case via Google: Unfortunately re-arranging the order and then trying the deny as an effect didn't work for me. I ended up just writing my own custom middleware. Surprisingly was easy/fast enough to do.
