### ISSUE TITLE
[Question] RBAC with Tennants, how to efficently enumerate subjects wtih read access to object?

### ISSUE THREAD

**Issue by Alec-Bailey** [casbin/casbin#948]
Consider a standard implementation of RBAC with Domains/Tennants, assuming there are at least 10<sup>6</sup> subjects, with 10<sup>7</sup> objects.

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act
```
I have a use case which requires relatively frequent Reverse policy evaluation.

Is it possible with Casbin, to efficiently query for all subjects with 'Read' access to any given object within a domain?

Example: 
I would need to query with parameters
> obj: device1, act: read, dom: mydomain 
>
Returns a list of subjects whom have read access to this object. I am having a difficult time finding documentation which would support this use case.

**Comment by hsluoyz** [comment]
@Alec-Bailey see: https://casbin.org/docs/en/data-permissions

**Comment by hsluoyz** [comment]
Closed as resolved
