### ISSUE TITLE
[Question] Incremental Add/Delete role in `SyncedEnforcer`

### ISSUE THREAD

**Issue by zsh1995** [casbin/casbin#949]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
I use casbin in an environment with many departments and users, the `enforcer` i'm using is `SyncedEnforcer`. I use adapter to load policies from mysql periodically(5s).Like the loading cycle, the cpu usage increases periodically.
I try to use `LoadIncrementalFilteredPolicy`，but I found it still rebuilds role manager.
Is there any better way?

**Comment by hsluoyz** [comment]
@fabian4

**Comment by hsluoyz** [comment]
@abichinger @Abingcbc @nodece @sagilio

**Comment by Abingcbc** [comment]
Maybe `WatcherEx` is a better solution? https://casbin.org/docs/en/watchers#watcherex
You can set a callback to notify `casbin` to update its policies when you change your policies in MySQL, instead of loading periodically.

**Comment by hsluoyz** [comment]
@zsh1995 use WatcherEx
