### ISSUE TITLE
[Question] How to match any user with wildcard *

### ISSUE THREAD

**Issue by resokou** [casbin/casbin#951]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
I'm trying to use casbin to set user permissions for a website/API. I understand how to explicitly write the configuration for known usernames but I don't understand how to allow generic usernames (any string) to a specific url.

For example:
- admins (usernames known) can access everything
- any username can access `/api/v1/user/*`

Below my full example.

**My model (changes required):**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.user, "role_admin") || g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && (r.act == p.act || p.act == "*")
```

**My policy (changes required):**

```
p, role_user, /api/v1/login, POST
p, role_user, /api/v1/register, POST
p, role_user, /api/v1/user/*, *

p, role_uploader, /api/v1/upload/*, *

p, role_analytics, /api/v1/stats/*, *

g, alice, role_uploader
g, bob, role_analytics
g, candice, role_admin
g, *, role_user
```

`*` should match any username (even empty string) for the role `role_user` . I know both my policy and models are not correct but they serve the example.

**Want:**

```
dain, /api/v1/login, POST ---> true
dain, /api/v1/user/profile, POST ---> true

dain, /api/v1/stats/all, GET ---> false
dain, /api/v1/upload/review, POST  ---> false
dain, /api/v1/admin/ban, POST ---> false
```
In this case **dain** is a generic username (not necessarely known).

If it's easier the roles could also be made hierarchical, like `role_admin` > `role_uploader` > `role_analytics` > `role_user`.

I tried to use something like `keyMatch(r.user, p.user)` but I couldn't do it.

**Comment by hsluoyz** [comment]
@abichinger @Abingcbc @sagilio

**Comment by abichinger** [comment]
@resokou you can use [`e.AddNamedMatchingFunc`](https://github.com/casbin/casbin/blob/61e3352e2c4bbfb2bdc3b5cf104f957c4976b5fd/enforcer.go#L740) to automatically grant roles to unknown users.

`.*` should match any username, if you use [`RegexMatchFunc`](https://github.com/casbin/casbin/blob/61e3352e2c4bbfb2bdc3b5cf104f957c4976b5fd/util/builtin_operators.go#L271) as your `defaultrolemanager.MatchingFunc`.

**Comment by resokou** [comment]
@abichinger 
Thanks for the reply but I still quite don't get it. How do I change my .conf file? My tests still fail on what should be allowed for generic users. What I changed so far:

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.user, "role_admin") || g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && (r.act == p.act || p.act == "*")
```
```
p, role_user, /api/v1/login, POST
p, role_user, /api/v1/register, POST
p, role_user, /api/v1/user/*, *

p, role_uploader, /api/v1/upload/*, *

p, role_analytics, /api/v1/stats/*, *

g, alice, role_uploader
g, bob, role_analytics
g, candice, role_admin
g, .*, role_user
```
```go
package policy

import (
	"testing"

	"github.com/casbin/casbin/v2"
	"github.com/casbin/casbin/v2/util"
)

func TestPolicyUser(t *testing.T) {
	e, _ := casbin.NewEnforcer("policy_user.conf", "policy_user.csv")
	e.AddNamedMatchingFunc("g", "", util.RegexMatch)
	err := e.BuildRoleLinks()
	if err != nil {
		t.Error("BuildRoleLinks() function failed")
	}

	ok, _ := e.Enforce("dain", "/api/v1/login", "POST")  // FAILS
	if ok != true {
		t.Error("supposed to be true")
	}
	ok, _ = e.Enforce("dain", "/api/v1/user/profile", "GET")  // FAILS
	if ok != true {
		t.Error("supposed to be true")
	}
	ok, _ = e.Enforce("johndoe", "/api/v1/upload/data", "POST")
	if ok != false {
		t.Error("supposed to be false")
	}
	ok, _ = e.Enforce("johndoe", "/api/v1/stats/download", "GET")
	if ok != false {
		t.Error("supposed to be false")
	}
	ok, _ = e.Enforce("johndoe", "/api/v1/admin/ban", "POST")
	if ok != false {
		t.Error("supposed to be false")
	}
}
```

**Comment by abichinger** [comment]
@resokou
I think you meant to write `g(r.sub, "role_admin")` instead of `g(r.user, "role_admin")`
Aside from that, your solution looks correct.

It looks like there is an issue with the `RoleManager`, because is doesn't grant user `dain` the role `user_role`.
#942 should fix this issue.

**model**
```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, "role_admin") || (g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && (r.act == p.act || p.act == "*"))
```

**policy**
```
p, role_user, /api/v1/login, POST
p, role_user, /api/v1/register, POST
p, role_user, /api/v1/user/*, *

p, role_uploader, /api/v1/upload/*, *

p, role_analytics, /api/v1/stats/*, *

g, alice, role_uploader
g, bob, role_analytics
g, candice, role_admin
g, .*, role_user
```

**test**
```go
func TestPolicyUser(t *testing.T) {
	e, _ := NewEnforcer("examples/951_model.conf", "examples/951_policy.csv")
	e.AddNamedMatchingFunc("g", "", util.RegexMatch)
	e.BuildRoleLinks()

	testGetImplicitRoles(t, e, "dain", []string{"role_user"})

	testEnforce(t, e, "dain", "/api/v1/login", "POST", true)
	testEnforce(t, e, "dain", "/api/v1/user/profile", "GET", true)
	testEnforce(t, e, "johndoe", "/api/v1/upload/data", "POST", false)
	testEnforce(t, e, "johndoe", "/api/v1/stats/download", "GET", false)
	testEnforce(t, e, "johndoe", "/api/v1/admin/ban", "POST", false)
}
```

**output on 61e3352e2c4bbfb2bdc3b5cf104f957c4976b5fd**
```
--- FAIL: TestPolicyUser (0.00s)
   casbin/951_test.go:28: Implicit roles for  dain :  []
   casbin/951_test.go:28: Implicit roles for  dain :  [] , supposed to be  [role_user]
   casbin/951_test.go:32: johndoe, /api/v1/upload/data, POST: true, supposed to be false
   casbin/951_test.go:33: johndoe, /api/v1/stats/download, GET: true, supposed to be false
   casbin/951_test.go:34: johndoe, /api/v1/admin/ban, POST: true, supposed to be false
FAIL
FAIL	github.com/casbin/casbin/v2	0.003s
FAIL
```

**output on ff46edf7d6320b638054ad739e24a75ea05a1256**
```
ok  	github.com/casbin/casbin/v2	0.004s
```

**Comment by resokou** [comment]
@abichinger 
I see thanks. That seems quite an important fix. So maybe a new version tag should be created when the changes are pushed back into the master branch.

Thanks again.

**Comment by resokou** [comment]
I'm closing this since the pull request mentioned was merged and the issue is fixed with the latest release. Thanks.

**Comment by resokou** [comment]
@hsluoyz The one mentioned by @abichinger which is https://github.com/casbin/casbin/pull/942 as he wrote, which made it into **2.43.2** according to the bot. I just upgraded my dependencies at the time and saw everything worked so I closed this issue. Sorry I didn't check Github and didn't see your mention.
