### ISSUE TITLE
[Question] No support to match baces placeholder that like "/user/{userId}" 

### ISSUE THREAD

**Issue by GavinWLove** [casbin/casbin#953]
Hi , 
Enforcing authorization to control access of restful API .
But No support to match baces placeholder that like "/user/{userId}". 
Is exist other solutions except customize match function ?

** model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && XXXMatch(r.obj , p.obj) && r.act == p.act
```

** policy:**

```
p, alice, /user/{userId}, GET
p, bob, /order/{orderId}, GET
p, bob, /order/{orderId}, DELETE

```

**request(s):**
alice /user/1 GET
```
alice, /user/{userId}, GET---> false (expected: true)
```

**Comment by hsluoyz** [comment]
@GavinWLove see `keyMatch3()`: https://casbin.org/docs/en/function
