### ISSUE TITLE
[Question] Matching function not working for the second role definition

### ISSUE THREAD

**Issue by basimsahaf** [casbin/casbin#955]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
I am trying to build a system where my features can have sub-features within them and any user having access to the parent feature should get access to all the child features. I am also using domains and pattern matching so I can configure roles within domains. I also want some roles to be active across all domains. 

To establish a parent-child relationship between the features, I am creating another role system `g2`. Here's my model

```ini
[request_definition]
r = role, domain, resource, action

[policy_definition]
p = role, domain, resource, action

[role_definition]
g = _, _, _
g2 = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.role, p.role, r.domain) && g2(r.resource, p.resource, r.domain) && keyMatch(r.domain, p.domain) && r.action == p.action
```

**Your policy:**

```
p, feature_1_group, *, feature_1, read

g2, sub_feature_1, feature_1, *
g, admin, feature_1_group, *
```

Here I am defining `feature_1_group` to get read permission on `feature_1` in all domains. Then, I am making `sub_feature_1` a part of `feature_1` in all domains and finally, I am assigning the role`feature_1_group` to `admin` in all domains as well. Then I try the following request:

```
admin, random_domain, sub_feature_1, read  #should return true but returns false
```

Since admin has read access on feature_1 and sub_feature_1 is a part of feature_1, should this not be true?

I'm not sure why this doesn't work because I am using keyMatch for the domain. This however works for the first role group `g`

```
admin, random_domain, feature_1, read
admin, random_domain_1, feature_1, read
```

Both are true as expected. 

My case works if I don't use * while defining g and g2 in my policy:

```
p, feature_1_group, *, feature_1, read

g2, sub_feature_1, feature_1, domain_1
g, admin, feature_1_group, domain_1
```

Now if I do:

```
admin, domain_1, sub_feature_1, read
```
This returns True. But this is not scalable as I have to define this for all domains.

I would really appreciate the help here

**Comment by basimsahaf** [comment]
I think this is working for me in code locally if I do

```golang
e.AddNamedDomainMatchingFunc("g", "", util.KeyMatch)
e.AddNamedDomainMatchingFunc("g2", "", util.KeyMatch)
```

However, your online editor doesn't work. Can this be fixed?

**Comment by tangyang9464** [comment]
> I think this is working for me in code locally if I do
> 
> ```go
> e.AddNamedDomainMatchingFunc("g", "", util.KeyMatch)
> e.AddNamedDomainMatchingFunc("g2", "", util.KeyMatch)
> ```
> 
> However, your online editor doesn't work. Can this be fixed?

@basimsahaf  Maybe you should add ``keyMatch`` here
![image](https://user-images.githubusercontent.com/45587763/152670628-914bba0a-54bf-483c-9548-1572eca8134f.png)
