### ISSUE TITLE
[Question] Role inheritance for hierarchical resources.

### ISSUE THREAD

**Issue by ikarstein** [casbin/casbin#956]
Sorry if this is a stupid question or the question has been asked 1000 times. I've been trying to find an answer for a while, but my searches give no result.

The permissions in a file system are my scenario.  
+ Objects ("files" or "resources") are in containers. 
+ One object belongs to 1 container. 
+ There is a root container.
+ Containers can contain containers.
+ Users are members in groups. Groups can be member of other groups.
+ Containers and objects can have "allow" and/or "deny" permissions for different actions (read, write, delete,...) for different users and/or groups.
+ Permissions should be "generic" and extensible. "Read" and "write". Mayby later "edit", "delete", "update", "view", "approve" ...
+ Perfect would be a system of "permission sets" that replace "permissions" and that costist of "base permissions". So a permission set called "read" would consist of the base permissions "base_read, base_view". 
+ I store the assignment of permissions (Allow/Deny per action per user/group) for each container and object.  
+ I want to ask "a access control system" (CASBIN?) at any point in time whether "user A is allowed to access object O1 with action READ" based on the object location (in the hierarchical object/container tree and based on the users group membership.

Is this possible with Casbin - and how?

Thanks a lot!
Ingo

**Comment by hsluoyz** [comment]
@tangyang9464 @abichinger @Abingcbc

**Comment by Abingcbc** [comment]
@ikarstein Could `RABC with domain/tenants` solve your problem? You can try an example with Casbin by https://casbin.org/casbin-editor/#GDZCMGNXK
In the above example:
* `Containers can contain containers.` can be solved by `keyMatch` with hierarchical path like `/` and `/data1`. More details of different kinds of matching functions are at https://casbin.org/docs/en/function
* `Users are members in groups` is like `alice` is a member of `user`. 
* `Groups can be member of other groups.` is like `admin` is in domain `domain1`

You can refer to the online editor for more details :)

**Comment by amit-chandak-unskript** [comment]
We had the same issue. We used the following 
```
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && keyMatch(r.act, p.act) || g2(r.sub, p.sub)

```

We used g2 to capture the user->group relationship

@Abingcbc , can we use g2 kind of container relationship for resources too? We use domain for something else, so cant use that. Was wondering if we can have g2 kind of relationship for resources too. That way, i can capture the resource hierarchy via g2.

**Comment by hsluoyz** [comment]
@amit-chandak-unskript see: https://casbin.org/docs/en/rbac#:~:text=when%20you%20need%20roles%20(or%20groups)%20on%20both%20users%20and%20resources.%20Please%20see%20the%20rbac_model.conf%20and%20rbac_model_with_resource_roles.conf%20for%20examples.

**Comment by hsluoyz** [comment]
Closed as resolved
