### ISSUE TITLE
LoadPolicy() is called automatically when initializing with filtered adapter

### ISSUE THREAD

**Issue by jeremiahmmartinez** [casbin/casbin#96]
When I call `enforcer.InitWithAdapter()`, it results in `adapter.LoadPolicy()` being called via `enforcer.InitWithModelAndAdapter()`, even when the adapter is of the type `persist.FilteredAdapter`.

This seems to defeat the purpose of using a filtered adapter for performance considerations. I could check whether the adapter is a filtered adapter inside `adapter.LoadPolicy()` and not query the database if it's filtered. Is this the intended solution?

**Comment by hsluoyz** [comment]
Sounds good to me. Please make a PR for it, do not forget to update the test script.
