### ISSUE TITLE
[Question] Does casbin support watcher currently?

### ISSUE THREAD

**Issue by neWs1587** [casbin/casbin#960]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------
I see it in casbin docs. The docs last updated on 2/13/2022.
'We hope it can notify other instances when the policy changes, but there is currently no implementation of WatcherEx.'

I am not sure can I use it now.

**Comment by hsluoyz** [comment]
@neWs1587 why close?

FYI: https://github.com/search?q=casbin+WatcherEx&type=code
