### ISSUE TITLE
[Question] Can use custom condition? 

### ISSUE THREAD

**Issue by GerryLon** [casbin/casbin#961]
https://github.com/ory/ladon
![image](https://user-images.githubusercontent.com/25873611/155480725-7dfe9634-c40a-466c-8242-3b2cb6c097a7.png)

can support feature like above: custom condition?

**Comment by hsluoyz** [comment]
@Abingcbc @seriouszyx

**Comment by hsluoyz** [comment]
@GerryLon yes, you can use the built-in `ipMatch()` function here: https://casbin.org/docs/en/function or define your own customized function
