### ISSUE TITLE
[Question] Adding KeyMatch2 to group policy

### ISSUE THREAD

**Issue by hadarhaviv** [casbin/casbin#962]
Hello. I'm trying to use KeyMatch2 with group policy. no matter what I've tried, I keep getting 403.
I've configured the enforcer as such:

Enforcer.AddNamedMatchingFunc("g2", "KeyMatch2", util.KeyMatch2)
Enforcer.BuildRoleLinks()

here is the rest of my configuration:

**My Model**

# Request definition
[request_definition]
r = sub, obj, act

# Policy definition
[policy_definition]
p = sub, obj, act

# Role Definition
[role_definition]
g = _,_
g2 = _,_

# Policy effect
[policy_effect]
e = some(where (p.eft == allow))

# Matchers
[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && regexMatch(r.act, p.act)

**My Policy**

p, pages_group_sub, pages_group_res ,GET

g, alice, pages_group_sub
g2, /users/:id , pages_group_res

**My Request**

alice, /users, GET

-----------

please help!
thanks in advance

**Comment by hsluoyz** [comment]
@tangyang9464 @abichinger @Abingcbc

**Comment by abichinger** [comment]
@hadarhaviv the first error I encountered is
```
the number of "_" in role definition should be at least 2
```
To solve this error you need to correct your role definition
```ini
[role_definition]
g = _,_
g2 = _,_
```

Secondly the policy contains some misplaced spaces.
**Corrected Policy**
```
p, pages_group_sub, pages_group_res, GET

g, alice, pages_group_sub
g2, /users/:id, pages_group_res
```

You didn't specifiy the expected result of the request.
**Results of my tests**
```
alice, /users, GET -> false, because /users does not match /users/:id
alice, /users/123, GET -> true
```
