### ISSUE TITLE
[Question] How can I declare a policy without domain and use the domain just in role definition

### ISSUE THREAD

**Issue by sasakiyori** [casbin/casbin#968]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

Hello. I want to limit the authority of accessing different uri path, also I prefer to have a basic policy for these limits.
Assume that a system has some isolated domains, all of them use a basic policy and every domain has its own user who may 
inherit and add external access policy.
When I try using p, g, g2 (or with p2, g2) to achieve what I supposed, I found: 
Once I use the feature of domain, I cannot use the policy without domain. Or the inherited policies don't work. I don't known if my statement is correct, the following example may explain.

**Your model:**

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```ini
# basic policy, should not involve with domain
# I have tried different definitions, like:
# p, visitor,  /list, GET
# or p2, visitor, /list, GET
# but they didn't work

p, visitor, *, /list, GET
p, visitor, *, /menu, GET
p, visitor, *, /insight, GET
p, user, *, /update, POST
p, manager, *, /manage, POST
p, sysadmin, *, /account, GET


# I don't expect these roles inherited with domain
g2, user, visitor
g2, manager, user
g2, sysadmin, manager

# This is what I want to achieve. 
# I can create a user in one domain, define his original identity, and add external access authorization if needed.
p, bob, domain1, /dosth, GET
g, bob, manager, domain1
```

**Your request(s):**

```ini
# bob is manager, inherited by user and visitor, but can't access /insight method generated from visitor. 
bob, domain1, /insight, GET ---> false (expected: true)
bob, domain1, /manage, POST ---> true (expected: true)
bob, domain1, /account, GET ---> false (expected: false)
```

Can domain be inherited ? 
Or can I use the p2, g2 or somehow to fix this problem?
Or maybe just use a different way to achieve what I want to do.

Thanks in advance.

**Comment by sasakiyori** [comment]
Your model:

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.obj == p.obj && r.act == p.act
```

Your policy:


```ini
p, visitor, *, /list, GET
p, visitor, *, /menu, GET
p, visitor, *, /insight, GET
p, user, *, /update, POST
p, manager, *, /manage, POST
p, sysadmin, *, /account, GET


g, user, visitor, domain1
g, manager, user, domain1
g, sysadmin, manager, domain1


p, bob, domain1, /dosth, GET
g, bob, manager, domain1
```

Your request(s):

```ini
bob, domain1, /insight, GET ---> true (expected: true)
bob, domain1, /manage, POST ---> true (expected: true)
bob, domain1, /account, GET ---> false (expected: false)
```

**The example above suits all results I expected, when I straightly use 'domain1' declaration but not '*'.**
**'*' just means one string but not the reg for all?**
**How can I achieve this? I don't want to add so many specific roles when a new user is created.**

**NOT**
```ini
g, user, visitor, domain1
g, manager, user, domain1
g, sysadmin, manager, domain1
```

**BUT**

```ini
g, user, visitor, *
g, manager, user, *
g, sysadmin, manager, *
```

Thanks.

**Comment by hsluoyz** [comment]
@Abingcbc @seriouszyx

**Comment by Abingcbc** [comment]
@sasakiyori You can use `e.AddNamedDomainMatchingFunc("g","KeyMatch",util.KeyMatch)`

Here is a successful test case of your example: https://casbin.org/casbin-editor/#AYPMTXPN9 . Pay attention to the left custom config
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/34068205/158222326-05b7ab2d-200d-4f01-938d-4d812b1bb466.png">


You can find detailed docs at https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac

**Comment by sasakiyori** [comment]
It works, thanks for your help @Abingcbc .
