### ISSUE TITLE
[Question] Get implicit permissions with pattern-matching in RBAC don't work

### ISSUE THREAD

**Issue by sasakiyori** [casbin/casbin#969]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**

Hello. From the [Issue:968](https://github.com/casbin/casbin/issues/968), I use this function to achieve what I expected:
```go
e.AddNamedDomainMatchingFunc("g", "KeyMatch", util.KeyMatch)
```
It uses the ```KeyMatch``` func, trickily make it access all domains. But I found something wrong when I tried to get user's permission list.

As the [tutorial](https://casbin.org/docs/en/rbac-api#getimplicitpermissionsforuser) said, I tried ```GetImplicitRolesForUser``` and ```GetImplicitPermissionsForUser``` func to get the roles and permissions for user.

I found the execution result of  ```GetImplicitRolesForUser``` is what I need, but the result of ```GetImplicitPermissionsForUser``` is empty!

---
**Your model:**

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, visitor, *, /list, GET
p, visitor, *, /menu, GET
p, visitor, *, /insight, GET
p, user, *, /update, POST
p, manager, *, /manage, POST
p, sysadmin, *, /account, GET


g, user, visitor, *
g, manager, user, *
g, sysadmin, manager, *


g, bob, manager, domain1
```

**Your request(s):**
```go
// result: [manager user visitor]  --> (expected: [manager user visitor])
e.GetImplicitRolesForUser("bob", "domain1")

// result: [] --> (expected: [[manager * /manage POST] [user * /update POST] [visitor * /list GET] [visitor * /menu GET] [visitor * /insight GET]])
// or [[manager domain1 /manage POST] [user domain1 /update POST] [visitor domain1 /list GET] [visitor domain1 /menu GET] [visitor domain1 /insight GET]] be better!
e.GetImplicitPermissionsForUser("bob", "domain1")
```

---
**I found ```KeyMatch``` func doesn't affect the ```GetImplicitPermissionsForUser``` func at all.**

I tried to add multiple domain parameters ("domain1" and "*") into ```GetImplicitPermissionsForUser``` func, but found that ```GetImplicitPermissionsForUser``` func actually allows at most one domain param...

As I annotated bellow, the domain "domain1" cannot matches "*", and the func ```KeyMatch``` I registered isn't used. 
~~Also I found that at runtime,  ```model[sec][ptype].RM``` is nil, so that I can't use its ```domainMatchingFunc```(I registered as ```KeyMatch``` func) to do matching.~~

I found the ```GetFilteredPolicy``` function uses ```model["p"]["p"]``` in the loop. But the ```KeyMatch``` func I registered is located in ```model["g"]["g"].RM.(*defaultrolemanager.RoleManager).domainMatchingFunc```. And worse, this func is private, and the wrapped func ```domainMatch``` is private too.

When I make ```domainMatch``` function to be public and straightly add an additional condition in ```GetFilteredPolicy``` func like this: 
```go
!model["g"]["g"].RM.(*defaultrolemanager.RoleManager).DomainMatch(fieldValue, rule[fieldIndex+i])
```
I get these results:
```
[[manager * /manage POST] [user * /update POST] [visitor * /list GET] [visitor * /menu GET] [visitor * /insight GET]]
```

**I expect the domain of implicit permissions result is 'domain1' instead of '*', but solving this problem is the top priority.**

```go
func (e *Enforcer) GetImplicitPermissionsForUser(user string, domain ...string) ([][]string, error) {
	roles, err := e.GetImplicitRolesForUser(user, domain...)
	if err != nil {
		return nil, err
	}
        // actually get roles:  [manager, user, visitor]
	roles = append([]string{user}, roles...)

	var res [][]string
	var permissions [][]string
	for _, role := range roles {
                 // can't match the role '*' with domain 'domain1', results in empty slice
		permissions = e.GetPermissionsForUser(role, domain...)

		res = append(res, permissions...)
	}

	return res, nil
}

func (model Model) GetFilteredPolicy(sec string, ptype string, fieldIndex int, fieldValues ...string) [][]string {
	res := [][]string{}

	for _, rule := range model[sec][ptype].Policy {
		matched := true
		for i, fieldValue := range fieldValues {
                         // when I straightly add an additional condition, results come out:
			if fieldValue != "" && rule[fieldIndex+i] != fieldValue
                         && !model["g"]["g"].RM.(*defaultrolemanager.RoleManager).DomainMatch(fieldValue, rule[fieldIndex+i]) {
				matched = false
				break
			}
		}

		if matched {
			res = append(res, rule)
		}
	}

	return res
}
```

Is this problem needed to fix? 

Or use another way to get implicit permissions?

**Comment by Abingcbc** [comment]
@sasakiyori  Sorry for the late response~
One simple way is to use `GetDomains()` first to get all domains in which `bob` has roles and repeat call `GetImplicitPermissionsForUser ` with each domain.

**Comment by sasakiyori** [comment]
@Abingcbc  hey I tried the way you said, but it didn't seem to work.

Inside the function ```hasAnyRole``` called by ```GetDomains```, first get ```[*, domain1]``` result by ```getPatternDomain```. Then when repeating calling ```hasRole``` for each domain, it just considers ```pattern``` without ```domainPattern```, which results in the response of ```GetDomains``` is only ```domain1```.

```go
func (rm *RoleManager) hasRole(domain, name string) bool {
	roles, _ := rm.allDomains.LoadOrStore(domain, &Roles{})
	allRoles := roles.(*Roles)
        // "rm.hasPattern" is false, but "rm.hasDomainPattern" is true
	if rm.hasPattern {
		return allRoles.hasRole(domain, name, rm.match)
	} else {
                // matchingFunc is nil, "*" cannot be matched
		return allRoles.hasRole(domain, name, nil)
	}
}
```

Assume that we get the "*" result from ```GetDomains```,  ```e.GetImplicitPermissionsForUser("bob", "*")``` returns empty, which doesn't satisfy what we need.

And If we can get the results ```[[manager * /manage POST] [user * /update POST] [visitor * /list GET] [visitor * /menu GET] [visitor * /insight GET]]```  from ```e.GetImplicitPermissionsForUser("bob", "*")```, just like the way you said, I don't think the rising of **time complexity** is acceptable. 

Now that ```domainMatchingFunc``` already exists and it works for ```Check```, maybe making it work in other functions is the better way to achieve this problem?
