### ISSUE TITLE
[Question] How do I retrieve all objects that can access a subject?

### ISSUE THREAD

**Issue by basimsahaf** [casbin/casbin#970]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
I am trying to get all the objects associated with a particular subject
**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, admin, data1, read
p, bob, data1, read
g, alice, admin
```

**Your request(s):**
In the above example, I want to get all the objects that i defined in the policy to have read access to data1. In this case, it should return admin and bob but not alice. I know alice does have read access to data1 but I only want to return the objects I defined in the policy to be returned. How do I achieve this using the API?

**Comment by hsluoyz** [comment]
@basimsahaf see: https://casbin.org/docs/en/rbac#how-to-query-implicit-roles-or-permissions

**Comment by basimsahaf** [comment]
@hsluoyz Sorry but the above link does not answer my question. I'm not talking about getting roles for a "user". I want all the roles that can access a "resource". Like I want to be able to know which roles can access `data1` in the above example

**Comment by hsluoyz** [comment]
@basimsahaf see the RBAC API: https://casbin.org/docs/en/rbac-api
