### ISSUE TITLE
[Feature] I want to get the current domains

### ISSUE THREAD

**Issue by wangdyqxx** [casbin/casbin#971]
t seems that there is no API for getdomains. Would you like to add it? Because the adapter is implemented with MySQL

**Comment by hsluoyz** [comment]
@wangdyqxx hi, please change all texts to English

**Comment by wangdyqxx** [comment]
@hsluoyz   I wanted to use the API getdomains, but I couldn't find it. I only found API getallusersbydomain ...

**Comment by hsluoyz** [comment]
@wangdyqxx plz modify these:

![image](https://user-images.githubusercontent.com/3787410/158565699-56c5c70e-49f9-46fd-9eba-ee5e316a2c7a.png)

**Comment by wangdyqxx** [comment]
> @wangdyqxx请修改这些：
> 
> ![图片](https://user-images.githubusercontent.com/3787410/158565699-56c5c70e-49f9-46fd-9eba-ee5e316a2c7a.png)

ok

**Comment by wangdyqxx** [comment]
@hsluoyz  hi, Can you have a look at it?

**Comment by BudhirajaMadhav** [comment]
Hey @hsluoyz, I want to work on this. Can I be assigned?

**Comment by hsluoyz** [comment]
@BudhirajaMadhav go ahead

**Comment by hsluoyz** [comment]
@BudhirajaMadhav you can communicate with the issue owner directly and the final goal is to help him resolve the issue

**Comment by wangdyqxx** [comment]
@BudhirajaMadhav @hsluoyz  is ok, we all aim to finally solve the problem. when do you expect to finish it ? or can I re implement API getdomains myself

**Comment by BudhirajaMadhav** [comment]
Hey @wangdyqxx, I wanted to confirm first if you'd like have all the domains a user has or all the domains that exist within the role manager?

**Comment by wangdyqxx** [comment]
@BudhirajaMadhav  I want is all domains. All domains of users are API GetDomainsForUser

**Comment by BudhirajaMadhav** [comment]
Okay @wangdyqxx I will make a PR for the same today.

**Comment by wangdyqxx** [comment]
> 好的@wangdyqxx我今天也会做一个 PR。

ok

**Comment by wangdyqxx** [comment]
@BudhirajaMadhav  I also need an API getRolesInDomain, can you submit it together?
