### ISSUE TITLE
[Bug] Enforce not detecting invalid request size

### ISSUE THREAD

**Issue by Shivansh-yadav13** [casbin/casbin#973]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
On enforcing, even after passing an invalid request size, it doesn't seem to throw any error about it.

**Expected behavior**
On passing invalid request size, it should probably throw an error.
https://github.com/casbin/casbin/blob/833f1af33cb49776d966fa877b16a7c75eeea427/enforcer.go#L542

**Additional context**

model
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

policy

```
p, data2_admin, data2, read

g, alice, data2_admin
```

code

```go
package main

import (
	"fmt"

	"github.com/casbin/casbin/v2"
)

func main() {
	e, _ := casbin.NewEnforcer("./model.conf", "./policy.csv")
	ok, _ := e.Enforce("alice", "data2");
	fmt.Print(ok)
}

```

Output expected: `invalid request size: expected 3 got 2 ...` got `false`.

**Comment by hsluoyz** [comment]
@Abingcbc

**Comment by tangyang9464** [comment]
@Shivansh-yadav13 Maybe you shouldn't ignore the returned error.
```
e, err:= casbin.NewEnforcer("./model.conf", "./policy.csv")
ok, err:= e.Enforce("alice", "data2");
fmt.Print(ok,err)
```

**Comment by Shivansh-yadav13** [comment]
> @Shivansh-yadav13 Maybe you shouldn't ignore the returned error.
> ```
> e, err:= casbin.NewEnforcer("./model.conf", "./policy.csv")
> ok, err:= e.Enforce("alice", "data2");
> fmt.Print(ok,err)
> ```

Ahh mb I'm just newbie with golang 😅
