### ISSUE TITLE
[Question] concurrent map

### ISSUE THREAD

**Issue by wangdyqxx** [casbin/casbin#979]
type Model map[string]AssertionMap
type AssertionMap map[string]*Assertion
Assertion.PolicyMap

these types cannot guarantee concurrency security. why not use sync.map ? 
golang is concurrent. what's the significance of this implementation ?
@hsluoyz

**Comment by tangyang9464** [comment]
> type Model map[string]AssertionMap type AssertionMap map[string]*Assertion Assertion.PolicyMap
> 
> these types cannot guarantee concurrency security. why not use sync.map ? golang is concurrent. what's the significance of this implementation ? @hsluoyz

@wangdyqxx For concurrency use ``SyncedEnforcer``

**Comment by wangdyqxx** [comment]
I use SyncedEnforcer now, but he uses sync.RWMutex, the performance is too poor. why not use  sync.Map ？

**Comment by tangyang9464** [comment]
> I use SyncedEnforcer now, but he uses sync.RWMutex, the performance is too poor. why not use  sync.Map ？
> @hsluoyz  @tangyang9464 

It didn't consider concurrency at first.  SyncedEnforcer is implemented in a simple way, using RWMutex.

**Comment by hsluoyz** [comment]
@tangyang9464 can we change to use sync.Map to improve performance?

**Comment by tangyang9464** [comment]
> @tangyang9464 can we change to use sync.Map to improve performance?

@hsluoyz Does this mean that ``Enforcer`` should fully support thread safety and discard ``SyncedEnforcer``? Or just use sync.map in ``SyncedEnforcer`` to replace RWMutex?

**Comment by tangyang9464** [comment]
Simply replacing ``map`` with ``sync.map`` isn't thread safe and still requires the use of ``RWMutex``. It doesn't seem to solve the problem.

**Comment by wangdyqxx** [comment]
i think concurrency can not be considered in the design of permission model, but concurrency must be considered in engineering implementation. at the same time, as a golang implementation, concurrency security must be implemented. otherwise, what practical significance does this have, it has no use value in engineering application.

**Comment by wangdyqxx** [comment]
@hsluoyz @tangyang9464 
i think concurrency can not be considered in the design of permission model, but concurrency must be considered in engineering implementation. at the same time, as a golang implementation, concurrency security must be implemented. otherwise, what practical significance does this have, it has no use value in engineering application.

**Comment by wangdyqxx** [comment]
i think concurrency security should be achieved in the implementation, at least I think so.

**Comment by wangdyqxx** [comment]
sync.map itself is multi thread safe. I don't know where it is not satisfied? if there are places that do not meet thread safety, you can add read-write lock to achieve it. do you think it's ok? In this way, there will be a lot less read-write locks.
@hsluoyz  @tangyang9464

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
@hsluoyz @wangdyqxx ok, I'll try to do it

**Comment by wangdyqxx** [comment]
i think of other ways, but it's really not a project that can be used online.

**Comment by wangdyqxx** [comment]
let me think of other ways, but this is really not a project that can be used online with high concurrency

**Comment by hsluoyz** [comment]
@wangdyqxx you can try the Casbin Enterprise version

**Comment by wangdyqxx** [comment]
ok，let me try
