### ISSUE TITLE
[Question] Can I load policy from a string?

### ISSUE THREAD

**Issue by basimsahaf** [casbin/casbin#980]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
Similar to how we can load a model from string using `model.NewModelFromString()`, is there an equivalent for policy as well? I could not find anything in the API but I was wondering if someone has achieved this in a different way?

**Comment by tangyang9464** [comment]
@basimsahaf Use [String Adapter](https://github.com/qiangmzsx/string-adapter).

**Comment by hsluoyz** [comment]
@basimsahaf see example: https://github.com/casdoor/casdoor/blob/3cf1b990bed23682dd745d83007fa0f688af5421/authz/authz.go#L73-L105
