### ISSUE TITLE
[Feature] Support context

### ISSUE THREAD

**Issue by johanneswuerbach** [casbin/casbin#982]
**Is your feature request related to a problem? Please describe.**

I would like to trace calls through casbin to troubleshoot slow queries / adapter performance issues, but this requires a context to be passed through and into the adapter layer so adapter actions can be associated with incoming requests ([opentelemetry tracing](https://opentelemetry.io/docs/instrumentation/go/getting-started/#trace-instrumentation) / [datadog](https://docs.datadoghq.com/tracing/setup_overview/custom_instrumentation/go#manually-creating-a-new-span))

**Describe the solution you'd like**

Add a `WithContext` version for methods (similar to [AWS](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.HeadObjectWithContext)) using the adapter and pass the context through the call stack.

**Describe alternatives you've considered**

Looked at rebasing https://github.com/casbin/casbin/pull/635, but it is missing a lot.

I looked at implementing this myself, but wasn't sure on the best approach. While adding a `WithContext` version to the interface is easy, passing the `ctx` parameter through the call stack is more challenging. I guess plainly duplicating internal methods to a with context and without version isn't really desirable so I wondered whether you would be open to always use context internally like:

```golang
func (e *Enforcer) LoadPolicy() error {
  return e.LoadPolicyWithContext(context.Background())
}

func (e *Enforcer) LoadPolicyWithContext(ctx context.Context) error {
  // code
}
```

This way the overhead would stay fairly slim with the downside of creating unused context objects everywhere. In addition this approach would ensure that context passing is test covered from the beginning. How does that sound?

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by johanneswuerbach** [comment]
Raised a draft of how this could be implemented https://github.com/casbin/casbin/pull/983

**Comment by johanneswuerbach** [comment]
See https://github.com/casbin/casbin/pull/983#issuecomment-1125995353
