### ISSUE TITLE
[Bug] fix CI lint error

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin#984]
See: https://github.com/casbin/casbin/runs/5888664254?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/162551264-1dce1559-ea09-4b22-9db5-1287761b7af9.png)

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
> @tangyang9464 

@hsluoyz resolved, see [981](https://github.com/casbin/casbin/pull/981)
