### ISSUE TITLE
[Bug] StartAutoLoadPolicy locks the entire enforcer on every sync

### ISSUE THREAD

**Issue by johanneswuerbach** [casbin/casbin#987]
**Describe the bug**
Using the `SyncedEnforcer` together with `StartAutoLoadPolicy` lock the entire enforcer on every sync, which can be a long time (1-2s) if the number of policies grows.

**To Reproduce**
1. https://github.com/casbin/casbin/blob/73cd2bcfa90dd7d8479f55fb199bb41e114ce7f2/enforcer_synced.go#L72
2. https://github.com/casbin/casbin/blob/73cd2bcfa90dd7d8479f55fb199bb41e114ce7f2/enforcer_synced.go#L114-L115

**Expected behavior**

The `LoadPolicy` function is already [written in a way](https://github.com/casbin/casbin/blob/73cd2bcfa90dd7d8479f55fb199bb41e114ce7f2/enforcer.go#L284-L285) that expensive work could be done in the background and the lock is already needed when [replacing the state](https://github.com/casbin/casbin/blob/73cd2bcfa90dd7d8479f55fb199bb41e114ce7f2/enforcer.go#L321). It would be great if the syncing logic is doing this instead of locking everything for the full sync loops.

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
@johanneswuerbach LoadPolicy locks to achieve strong data consistency. If it is not locked, then you need to be able to accept the errors caused by some data inconsistencies. For example, one routine is  calling ``LoadPolicy``, another routine is calling ``enforce``, then it will read out of date data and get the wrong result.

**Comment by johanneswuerbach** [comment]
The same out of date reading is already happening before a sync so I think a couple of seconds more or less don’t really hurt here. To prevent stale data we also use the watcher, so this sync loop is mainly a precaution for us.

Would you accept a PR making only the swap concurrency safe and not the entire loading operation?

**Comment by tangyang9464** [comment]
> The same out of date reading is already happening before a sync so I think a couple of seconds more or less don’t really hurt here. To prevent stale data we also use the watcher, so this sync loop is mainly a precaution for us.
> 
> Would you accept a PR making only the swap concurrency safe and not the entire loading operation?
> 
> 

@johanneswuerbach 
1. After the lock is added, other methods cannot be called before the LoadPolicy, which ensures that expired data will not be read

2. Watcher usually tells other instances to call LoadPolicy to synchronize data, so it has nothing to do with this concurrency problem
3. So, the solution you propose will not solve the problem

**Comment by johanneswuerbach** [comment]
Sorry, I might not have explained this well.

Usually data is stale in casbin after the first loading. A way to mitigate this is to regularly re-sync the data, but the data will always be stale between those syncs.

As data syncing is slow it locks the enforcer for a fairly long time, so the question is: Can this locking be somehow avoided?

My idea was to slightly increase the stale time and instead of locking the enforcer for the entire re-load period, only lock it while swapping the underlying model, which is fairly quick.

The downside is obviously that the stale period is slightly increased, but as data is already stale today (as syncs are only done on an interval or via async messages), this seems reasonable.

Rough code could look like:

```go
case <-ticker.C:
	// error intentionally ignored
	newModel, err = e.loadNewModel()
        if err != nil {
           e.swapModel(newModel)
        }
        
func swapModel(newModel model.Model) error {
	e.m.Lock()
	defer e.m.Unlock()
	if e.autoBuildRoleLinks {
		// code
	}
	e.model = newModel
}
```

`loadNewModel` would essentially be the same as a `LoadPolicy` except the swapping part.

**Comment by tangyang9464** [comment]
@johanneswuerbach I see. You're right. Could you please make a PR for it?

**Comment by johanneswuerbach** [comment]
Sure, here is the PR https://github.com/casbin/casbin/pull/988 :-)
