### ISSUE TITLE
RBAC with roles and fixed roles hierarchy across all domains

### ISSUE THREAD

**Issue by adamwasila** [casbin/casbin#99]
Here is my model; nothing really special here - standard RBAC with domains model:

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.obj == p.obj && r.act == p.act

[role_definition]
g = _, _, _
```
and here is an example policy file:

```csv
p, USER, resource, read
p, ADMIN, resource, write

# role-to-role mapping
g, MASTER, USER, domain1
g, ADMIN, MASTER, domain1

# again, same hierarchy but for different domain
g, MASTER, USER, domain2
g, ADMIN, MASTER, domain2
g, adam, ADMIN, domain1
g, adam, USER domain2
g, bolek, ADMIN, domain2
```

So far so good: I can easily add new users to domain and assign them some roles. Problem is that my roles hierarchy is static, exactly the same across each domain (eg. ADMIN is an MASTER, MASTER is an USER etc.) but I have to repeat it every time I add new domain.
This is boring and repetitive (means: in production mistakes/inconsistences will appear, it is only matter of time) and causes it being maintenance nightmare (eg.: what if, having hundres of domains, I try to add new role inside that hierarchy?). 

Ideally, such static role-inheritance hierarchy should be written just once for all domains (like in this broken example just to express an idea):

```csv
p, USER, resource, read
p, ADMIN, resource, write

g, MASTER, USER, *
g, ADMIN, MASTER, *
g, adam, ADMIN, domain1
g, adam, USER domain2
g, bolek, ADMIN domain1
```

Is there any way/trick to express it in casbin in current version? If not - may we discuss how could it be handled in the future and what should be implemented to support it?

**Comment by hsluoyz** [comment]
I don't know why you use RBAC with domains model. It seems that the roles in different domains do the same thing. Why don't use the basic RBAC model:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.dom + "::" + r.sub, p.sub) && r.obj == p.obj && r.act == p.act

[role_definition]
g = _, _
```

```csv
p, USER, resource, read
p, ADMIN, resource, write

# role-to-role mapping
g, MASTER, USER
g, ADMIN, MASTER

# again, same hierarchy but for different domain
g, MASTER, USER
g, ADMIN, MASTER
g, domain1::adam, ADMIN
g, domain2::adam, USER
g, domain2::bolek, ADMIN
```

**Comment by hsluoyz** [comment]
Moreover, your idea can be generalized, for example:

```csv
g, adam, ADMIN, domain[1-3]
```

It means to add user ``adam`` to ``ADMIN`` role in ``domain1, domain2 and domain3``. This part ``domain[1-3]`` is regex match.

However, such an extension slows down the performance. And most people will not have need for this flexibility. But you can implement a custom role manager and provide this extension. The people who need it will switch to use your ``regex-based role manager`` and they are also willing to afford the performance cost. See: https://github.com/casbin/casbin#role-manager for how to implement a custom role manager.

**Comment by adamwasila** [comment]
Thank you for quick reply! Yes, replacing domains with user prefixes solves the problem. One has to accept, that separator ("::" in this case) must not appear in the name of domain, but that's the only drawback I found so far. Real advantage is that I can have any nested sub-domains that way and nothing limits me in that aspect.
I haven't checked custom role-manager yet but this looks promising if my requirements will expand for "any domain name must be supported".

For the record: few words about the domain that requires such quirky model. What I try to implement is a [gitlab style kind of permissions](https://docs.gitlab.com/ee/user/permissions.html). I have users that are assigned to project in some role, roles are in linear hierarchy, where privileges down in the path are always expanding.

**Comment by hsluoyz** [comment]
The separator can be anything you like, just use something that you would never use in normal characters.

The GitLab uses a representative complex set of permissions. Let me know if encounters any issue when using Casbin to fulfill the need.
