### ISSUE TITLE
Why semantic-pr check is gone in every PR?

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin#993]
See: https://github.com/casbin/casbin/pull/992 and https://github.com/casbin/casnode/pull/497

But previously like this PR: https://github.com/casbin/casbin/pull/941 , we have it:

![image](https://user-images.githubusercontent.com/3787410/164467514-d6490b6b-6af7-4703-a356-6401e05251bb.png)

Saw this issue: https://github.com/zeke/semantic-pull-requests/issues/183

Can anyone fix this? We need to fix it in all Casbin orgs.

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by hsluoyz** [comment]
@JalinWang this issue has been here for more than 1 month. Do we have a good fix now?

/cc @tangyang9464

**Comment by JalinWang** [comment]
@hsluoyz 
I find an alternative https://github.com/apps/semantic-prs
FYI: https://github.com/zeke/semantic-pull-requests/issues/183#issuecomment-1120327873

Screenshot on my test repo:
![image](https://user-images.githubusercontent.com/20621784/171627761-679f50d4-3b2e-407c-b741-83ee3dd2c0c6.png)

**Comment by hsluoyz** [comment]
Fixed by solution: https://github.com/zeke/semantic-pull-requests/issues/183#issuecomment-1120327873
