### ISSUE TITLE
[Question] RBAC; match subject with '@email.com' (just the domain, not whole email from req)

### ISSUE THREAD

**Issue by johanforssell** [casbin/casbin#997]
**What's your scenario? What do you want to achieve?**
In a basic RBAC model I want to match _any_ email address to a basic "users" group and _specific_ email addresses to specific groups.

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
???? 
```

**Your policy:**

```
p, admin, the_data, read
p, admin, the_data, write
p, user, the_data, read

g, admin@email.com, admin
g, @email.com, user 
```

**Your request(s):**

I want the following result:
```
admin@email.com, the_data, write ---> true
monkey@email.com, the_data, write ---> false
person@email.com, the_data, write ---> false
chair@email.com, the_data, write ---> false
```

**Comment by tangyang9464** [comment]
@johanforssell You can customize the function ``emailMatch`` to match the email address and the user. see [how to add customized function](https://casbin.org/docs/en/function#how-to-add-a-customized-function). matcher is ``emailMatch(r.sub, p.sub) && r.obj == p.obj && r.act == p.act``

**Comment by johanforssell** [comment]
Ok, easy enough to write this
```
emailDomainMatch: function(rSub, pSub) { 
    const emailParts = rSub.split('@')
    if (emailParts.length != 2) { return false}
    return emailParts[1] === pSub
}
```

This will match `person@email.com` against `email.com`.

BUT I don't understand how this can be used in the matcher
